### ISSUE TITLE
[Feature/BugFix Request] Keep-alive for services

### ISSUE THREAD

**Issue by JCKodel** [meetfranz/franz#1000]
Today, some services (mostly Microsoft) doesn't work until I log in (even if I save the password). But, once logged in, those services keep up all day.

WhatsApp has a problem somewhat similar: when I get to work, the service is displaying a button [Use it here] (because there can be only one browser running web whatsapp). While in this state, notifications doesn't work.

### Feature Description

One of this two options:
Automatic logon on services when Franz starts.

### Motivation and Context
* Why is this change required?
Some services (in my case Outlook, MS Teams and WhatsApp) doesn't work right after I start to work on my machine.

* How is this improving the Franz experience?
Sometimes I forget that detail and lose some important notifications.

* What problem does it solve?
My bad memory ;-)

(this is issue #1000. Do I win something 🎉?)

**Comment by barraponto** [comment]
I kind of have the same issue. Some services just don't load until i nudge them (reload) and because of that I miss important notifications :/
