### ISSUE TITLE
Franz stays in the taskbar when it should go to system tray

### ISSUE THREAD

**Issue by solid-pixel** [meetfranz/franz#1006]
### Expected Behavior
After clicking on X (or CTRL+W) ![image](https://user-images.githubusercontent.com/18260178/41584073-99be3014-73a6-11e8-94d0-833991d7950f.png)
 Franz should keep running but stay minimised in the system tray

### Current Behavior
It just goes to the taskbar, the same as if I click the icon to minimise: 
![image](https://user-images.githubusercontent.com/18260178/41583836-f2d625f4-73a5-11e8-8d4b-efbeb6dc371b.png)

I know I can tick "Minimize Franz to system tray" but that will ALWAYS send it to the system tray. I would like to decide when to keep it in the taskbar, and when to send it to the tray. It worked this way for the first few days, then it stopped. No idea why.

### Steps to Reproduce (for bugs)
1. Set these settings:
![image](https://user-images.githubusercontent.com/18260178/41583896-22d68906-73a6-11e8-8f58-62eda8973587.png)

2. Click the X icon to close the window
3. Franz stays in the taskbar

![franz](https://user-images.githubusercontent.com/18260178/41584377-6d6d5890-73a7-11e8-9001-8ceabdaa0f65.gif)

### Environment

* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 with latest updates installed - not sure where to find the version

Thank you!

**Comment by imaginarny** [comment]
This would be prevented if minimization setting was not interfering with closing and implemented right, as already described in my comment here: https://github.com/meetfranz/franz/issues/763#issuecomment-377345406.

**Comment by solid-pixel** [comment]
@imaginarny I agree. Such a tiny and yet very annoying issue.

On a side note, wow: that issue is 5 months old and there is still zero feedback from the devs, and there are 400 open/unresolved issues in total. These numbers aren't reassuring at all. I'd love to upgrade to pro in our company but these stats are definitely holding me back.

Another discouraging situation:
File -> Quit does nothing (at least on W10), and the fix (PR #888) has been waiting for 4 months to be merged.

At this point I'm wondering if they even test the most basic features before releasing a beta to the public.

**Comment by imaginarny** [comment]
I had a time to take a look at it myself as it annoys me too much. So I just did pull request and hopefully it gets to be merged sooner than in another 4 months. 🙏

**Comment by solid-pixel** [comment]
@imaginarny thanks a lot for the effort, you're great! Now let's cross our fingers 🤞
