### ISSUE TITLE
Unable to add self-hosted Mattermost Server

### ISSUE THREAD

**Issue by thmsnhl** [meetfranz/franz#1007]
### Expected Behavior

I type my Mattermost server address and add the service to my account.

### Current Behavior

No Feedback on "Save service"-button click. After a second click it says "Your Mattermost server could not be verified." 

### Steps to Reproduce (for bugs)

1. Add new service
2. Search for Mattermost
3. Fill in the address 
4. Click "Save service"

### Context

I wanted to add my company's server to use franz for all communication.
### Your Environment

* Franz Version used: 5.0.0.18
* Operating System and version: Mac OS 10.13.5

**Comment by g3d** [comment]
Here is ad hoc solution described https://github.com/meetfranz/franz/issues/927#issuecomment-412261934

**Comment by thmsnhl** [comment]
Thank you, @g3d.

This works perfectly fine.

**Comment by Steinblock** [comment]
Changing the code according to the PR worked. Please merge this.
