### ISSUE TITLE
Feature request: add recipe https://messages.android.com/

### ISSUE THREAD

**Issue by iceuponfire** [meetfranz/franz#1008]
### Feature Description
Please add a recipe for  https://messages.android.com/

### Motivation and Context
Support sending sms from franz for android devices

Thank you :)

**Comment by lumitesi** [comment]
It's very easy to add a recipe.
Following the guide in the link below you can have it working in under 5 minutes.
https://github.com/meetfranz/plugins

I can do a pull request in https://github.com/meetfranz/plugins/pulls and add the recipe.

**Comment by jnischler** [comment]
+1 for this plugin!

**Comment by lumitesi** [comment]
I still didn't make the pull request, because I need to find where they keep the counter for unread messages so that the correct badge can be presented in Franz UI.
It's not hard, but it takes a little bit of time and testing efforts that I don't have this week. Next week if no one comes first I make the pull request.

**Comment by jpshelley** [comment]
Could @lumitesi or @cpjolicoeur submit their PR as is and then someone can come in later (maybe myself) and add the unread badge support? Think it would add value as is to just have it in Franz without badges yet then iterate on it.

**Comment by cpjolicoeur** [comment]
It appears someone else has already opened one so I'm just going to let that one ride out.

https://github.com/meetfranz/plugins/issues/164

**Comment by iceuponfire** [comment]
Oups sorry i didn't saw the other issue.

**Comment by lumitesi** [comment]
That's a big queue of open "[Deploy]" issues. I guess the integration will take its time.
Oh, @jpshelley it seems that the guy in there as the badge counter working. But I didn't test that.

**Comment by efraimbart** [comment]
@lumitesi The counter is fully functional, including muted conversations not being counted. There currently is no direct VS indirect count, I don't know if it is possible, but either way I personally prefer it like this.

**Comment by jpshelley** [comment]
How do deploy's happen? Is that something we can help with or need the maintainers?

**Comment by efraimbart** [comment]
@jpshelley It might just be worth downloading the recipe and installing it manually until the deploy actually happens.

**Comment by rohitksharma** [comment]
I just came across this... is there perhaps some sort of write-up of how to add these custom "recipes"? Or is there an ETA when it would be officially added to the next release by any chance?

**Comment by efraimbart** [comment]
@rohitksharma have a look at https://github.com/meetfranz/plugins/issues/164#issuecomment-412521673
