### ISSUE TITLE
No UI, reinstall causes complete failure to start

### ISSUE THREAD

**Issue by thekrugers** [meetfranz/franz#1009]
### Expected Behavior

The Franz user interface should start up when the desktop icon is double clicked.

### Current Behavior

Before uninstall and re-install: Double-clicking the Franz desktop icon fired up two Franz background processes and did nothing else, no UI and no Task Tray icon.
After uninstall and re-install: Double-click on the desktop icon appears to do nothing at all, so UI, no Task Tray icon and no background processes that I can identify in Task Manager.

### Screenshots (if appropriate):
LOL

### Steps to Reproduce (for bugs)

1. Boot PC
2. Double-click desktop icon
3. Check Task Manager

### Your Environment

* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 Enterprise version 1803, 64-bit

**Comment by thekrugers** [comment]
An update:
When I tried to delete the AppData\Roaming\Franz folder I discovered that the background processes had started up again. Once ended those tasks and deleted the folder Franz started up as if it had never been installed on this PC.

**Comment by n4ru** [comment]
+1, this has been reported multiple times and has been an issue since I believe beta-16
