### ISSUE TITLE
When a whatsapp group is muted, Franz still show the notification

### ISSUE THREAD

**Issue by ms-lemos** [meetfranz/franz#101]
I have some muted contacts/groups, but on Franz it keeps showing the notification that I have an unread message, even though the group is set to hide notifications. 

### Expected Behavior
It shouldn't show the notification as the group is configured to not show. 

### Current Behavior
It shows the notification that I have an unread message. 

### Possible Solution
Check if the group is configured to hide notifications. 

### Steps to Reproduce (for bugs)
1. Log in to whatsapp
2. Mute a group and configure it to hide notifications
3. Receive a message on that group
4. You'll see that the notifications are shown in Franz

### Context
Well, I don't want to be bothered by these groups. 

### Your Environment
* Franz Version used: 5.0.0-beta.10
* Operating System and version: Windows 10 - Build 1511

**Comment by GustavoKatel** [comment]
Is this the same issue? https://github.com/meetfranz/recipe-whatsapp/issues/1

**Comment by ms-lemos** [comment]
Yes, I didn't know if the thread was supposed to be opened here or there, apparently all threads are being opened here...

**Comment by GustavoKatel** [comment]
I'm not sure, but I don't think duplicated issues is ok. What do you think @adlk ?

**Comment by ms-lemos** [comment]
Oh, ok, didn't know. I'm new here, just tell me which one to delete and I'll do so.

**Comment by adlk** [comment]
Thats actually pretty a tough question as I personally prefer having recipe issues directly at the recipe repo. Every issue that is not directly connected with the client creates a lot of distraction. At the same time I believe we are expecting a bit much from the average user to find the right repo and post it there.

In this case here, @ms-lemos please copy your issue to the [whatsapp repo](https://github.com/meetfranz/recipe-whatsapp/issues/1) as it's a pretty good explanation. Thanks!
