### ISSUE TITLE
New GMail unread count is misleading with priority inbox

### ISSUE THREAD

**Issue by lucymhdavies** [meetfranz/franz#1010]
### Expected Behavior

I expect Franz to display the total unread emails.

In priority inbox mode, GMail now displays the unread count as X : Y.

For example, 3 : 190, for 3 unread priority emails, and 190 other unread emails.

Assuming Franz can only display a single number, this should be displayed as 193 unread emails.

### Current Behavior

GMail displays the unread count as X : Y, e.g. 3 : 190, for 3 unread priority emails, and 190 other unread emails.

Franz displays this by concatenating X and Y, i.e. 3190

### Screenshots (if appropriate):

New GMail shows unread as:
<img width="246" alt="screen shot 2018-06-19 at 12 12 24" src="https://user-images.githubusercontent.com/1116529/41594119-3acc1ba2-73ba-11e8-98d3-74c50d635e0f.png">

Franz displays this as:
<img width="69" alt="screen shot 2018-06-19 at 12 12 19" src="https://user-images.githubusercontent.com/1116529/41594131-47b0433e-73ba-11e8-87cb-e4722029ea98.png">

### Possible Solution

In the case of GMail displaying unreads as ( 3 : 190 ), you could sum these values, and display as 193.

### Steps to Reproduce (for bugs)

1. Use gmail in priority inbox mode.
2. Have unread emails in the priority inbox, and unread emails not in the priority inbox.

### Your Environment

* Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version:
macOS 10.11.6 El Capitan

**Comment by closingin** [comment]
Hello Lucy,

This bug has been addressed in [PR#4](https://github.com/meetfranz/recipe-gmail/pull/4) of [meetfranz/recipe-gmail](https://github.com/meetfranz/recipe-gmail), but is awaiting merge (there are conflicts).

That said, please open issues where they belong to, can you close this one ? :slightly_smiling_face:

**Comment by lucymhdavies** [comment]
Thanks. I wasn't aware of the project structure when I raised this issue originally. Good to see it's being addressed.

As it happens, GMail seems to have stopped using the `3 : 190` syntax since I originally raised it.

**Comment by closingin** [comment]
Hmm, I don't use Gmail that much so not very aware of this. This PR doesn't need to be merged anymore you say ?

**Comment by lucymhdavies** [comment]
I do not personally have the issue anymore. Following the steps to reproduce, I currently have 1 priority unread email, and a bunch of other non-priority unread emails. GMail displays the full count, not the `X : Y` syntax, so perhaps not.

**Comment by closingin** [comment]
Alright, thanks for the information
