### ISSUE TITLE
Attempt to download picture recieved from WhatsApp causes freeze

### ISSUE THREAD

**Issue by halas** [meetfranz/franz#1013]
When I try to download image received in WhatsApp conversation (zoom on picture, download button) Franz freezes after the system choose file location window is open. 

### Expected Behavior

I should be able to choose file name and location, save file and proceed with using the app. 

### Current Behavior

The program freezes after the system window to save file is open - doesn't react to any clicks, requires killing process and starting again. 

### Steps to Reproduce (for bugs)

1. Use WhatsApp service. 
2. Recieve picture in conversation. 
3. Click on picture to zoom in.
4. Click on download button in upper right corner. 

### Your Environment

* Franz Version used:
5.0.0-beta.14
* Operating System and version:
Debian 9.4, i3 window manager v 4.13-1

**Comment by at0mzk1** [comment]
I'm currently experiencing this behavior right now by executing same steps as OP.

### Context
### Your Environment

    

- Franz Version used:
    5.0.0-beta.18
- Operating System and version:
    Ubuntu 18.04

**Comment by Zamus** [comment]
Same issue on my env:

Mac OS Mojave v10.14.1 
Franz version: 5.0.0-beta.19

**Comment by noway1987** [comment]
Same issue here:

OS:
macOS Mojave v10.14.1

Franz version:
5.0.0-beta.19

**Comment by sirLisko** [comment]
I had a similar issue and I solved deleting the service and adding it back.
Whatsapp is still super slow though :(

Hope it helps :)

**Comment by abhinavms** [comment]
Same issue here. I can't download any file. Once the dialogue box appears, move pointer changes to select and reacts to nothing. But name of the file can be changed and enter to save the file in the downloads.

> I had a similar issue and I solved deleting the service and adding it back.
>
@sirLisko That didn't work for me :(

**OS:** Manjaro 18.0 Illyria
**Kernel:** x86_64 Linux 4.19.8-2-MANJARO
**Franz Version:** 5.0.0-beta.22

**Comment by sirLisko** [comment]
@abhinavms it helped me for a couple of hours and then the same issue :(

**Comment by samhk222** [comment]
Same here!

**Comment by hknoener** [comment]
For me, the problem happens to any media. If there's an audio/video/pic in the conversation, it freezes for around 1-2 minutes before coming back. During this period, Whatsapp service is frozen and the whole machine becomes pretty slow.

MacOS Mojave 10.14.2
Franz 5.0.0-beta.22

**Comment by sirLisko** [comment]
I think the latest version `beta-23` solved the issue 🎉

**Comment by rogelioprieto** [comment]
I 've downloaded the 5.6.0 (2020-11-13) version and it works, solved the issue!
