### ISSUE TITLE
Internet Bandwidth Usage

### ISSUE THREAD

**Issue by linuxtopia** [meetfranz/franz#1014]
**Native Telegram vs Franz for Bandwidth Usage**

Hello,

Franz Internet data/bandwidth usage is really gigantic when comparing with native Telegram app on Windows 10.

Why there is that so much difference? And how to solve it?

**Comment by djalmaaraujo** [comment]
@linuxtopia probably because it's the web version, needs to download all the assets while in desktop everything is downloaded and packed.
