### ISSUE TITLE
Hangouts chat boxes are small on first load

### ISSUE THREAD

**Issue by iONinja** [meetfranz/franz#1015]
### Expected Behavior

Hangouts chat boxes should be their normal size.

### Current Behavior

Hangouts chat boxes are very small (i.e. for small screen sizes) when first loading. I need to reload the Franz tab after loading Franz to get the chat boxes back to normal.

### Possible Solution

Temporary patch: reload the page. I think it's something to do with the page size being very small when Franz first loads, so Hangouts does an initial scaling of the chat boxes. However, they don't automatically resize later on.

### Steps to Reproduce (for bugs)

1. Add Hangouts to Franz
2. Close Franz and load it again
3. (You may need to be on another tab before closing for the bug to show up)
4. Go to the Hangouts tab and open any chat
5. The chat should be smaller than it's meant to be
6. Reload the tab and the chat boxes should be back to normal

### Your Environment

* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 Home

**Comment by bakshi** [comment]
This problem would occur constantly on my end too. I gave up on using Hangouts in Franz, and downloaded YakYak for Hangouts instead. https://github.com/yakyak/yakyak
