### ISSUE TITLE
No spellcheck in Hangouts

### ISSUE THREAD

**Issue by dalingrin** [meetfranz/franz#1016]
### Expected Behavior
Spellcheck should highlight misspelled words as you type in Google Hangouts

### Current Behavior
Spell check works in GMail and Facebook Messenger but does not seem to work in Hangouts

### Steps to Reproduce (for bugs)
- Install Franz 5.0 Beta 18
- Activate Google Hangouts
- Expect spell check to highlight misspelled words

### Your Environment
* Franz Version used: 5.0.0-beta18
* Operating System and version: Windows 10 Version 1803

**Comment by akoebbe** [comment]
Also experiencing this on Mac, same version.

**Comment by Tomasz-Mankowski** [comment]
Same problem here, same specs.

**Comment by jaspergrond** [comment]
Same here on the Ubuntu Linux version running on LM19. Seems like it is not implemented across the board.

**Comment by geekdave** [comment]
Same with Google Hangouts Chat, Franz Version 5.0.0 (5.0.0.1136).

**Comment by janhommes** [comment]
Yes, same here on ubuntu. While it works on the browser and other services. For me, this is a real game changer as I need that so much... now I don't use Franz any more.

**Comment by jaspergrond** [comment]
Yes I agree, I switched to Rambox for that reason... but the spellchecker there doesn't work as well! What are you using @janhommes?

**Comment by janhommes** [comment]
ubuntu 18.04.02 and Franz version 5.0.0 (2019-02-15).

But I tried it on ElementaryOS and there it was also not working. Funny thing is, that it was working before some update (either hangout chat or franz, i donno).

**Comment by jaspergrond** [comment]
@janhommes Oh sorry, I meant what are you using as an alternative (unless you are not any other franz like application now)

**Comment by janhommes** [comment]
@jaspergrond no idea, I was thinking about using chromium and simply pin the tabs, so that I use one browser for surfing and another one for communication.

**Comment by MikeInNY** [comment]
Same here. Unfortunately seems like the support for Franz is non-existent. I won't be renewing.
