### ISSUE TITLE
Android Messages

### ISSUE THREAD

**Issue by seanford** [meetfranz/franz#1017]
any chance we can get Android Messages integrated soon?

https://messages.android.com/

**Comment by okevino47** [comment]
Thanks to Franz for the android message integration.

But I have a bug that occur most of the time. After turning on my computer, the android message service try to get my message (normal), the fact is that an error occur (screenshot) with a google error number 400.

It woudn't be very annoying if I can disconnect my computer with my android message phone application. But it is not possible until I remove this service in purpose to disconect entirely the it, and I have to create a new android message service.

The bug occur just on windows but i never seen it on linux system.

It would be greatb if you can do something about that. (Sorry for my english which must contain severals error)
![CaptureBug](https://user-images.githubusercontent.com/35851082/61992146-b8791900-b05a-11e9-9742-8c6e3b8f8b45.JPG)

**Comment by Romainpetit** [comment]
Same here, getting the 400 error. 
Readding the service used to work, but not anymore. Service is completely down using Franz, but working in a browser.
