### ISSUE TITLE
New feature request - Viber integration

### ISSUE THREAD

**Issue by maddickt** [meetfranz/franz#102]
Could you please integrate Viber? It would be a LIFE SAVER!! My parents are too old to migrate over to Whatsapp and I speak with them regularly (from the other side of the world). I believe Viber has a web app now - https://account.viber.com/en/login

### Feature Description
Integration of Viber via web app - https://account.viber.com/en/login

### Motivation and Context
This change will make Franz the best in the world. 
My parents are old and on the other side of the world, so it's hard to talk through technological changes such as downloading different apps. They use Viber already and aren't able/willing to move over to Whatsapp. 
This solves the problem of me managing multiple message applications (furthering Franz's value proposition). 

### Mockups, Screenshots (if available):
None available but I know you know what this looks like (exactly the same as your other app integrations). 

Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by adlk** [comment]
Unfortunately it's not possible at the moment as Viber doesn't provide a web interface for chatting. Im very sorry!

**Comment by ComradeVVA** [comment]
Viber does have a Desktop client. Can that be integrated? I wouldn't mind basically installing it, as long as it's in the Franz front end.

**Comment by david-nedved** [comment]
Hi @ComradeVVA - I've actually made a franz plugin that does just that: https://github.com/david-nedved/viber-franz

**Comment by arturas10** [comment]
Hi @ned-kelly can you please make a video or some better explanation on how to add viber to franz? Im new guy, can't really understand the instructions. Thanks in advance.

**Comment by Kidlike** [comment]
@ned-kelly Can this be pushed upstream ? I don't see the need for this to be outside of Franz core.

**Comment by bamboorocket** [comment]
+1 please - would like to see this in Core

**Comment by GLObus303** [comment]
+1

**Comment by tzikis** [comment]
Same here!
