### ISSUE TITLE
Disable automatic updates?

### ISSUE THREAD

**Issue by iONinja** [meetfranz/franz#1020]
### Feature Description
Add the ability to ***not*** check for, or install, updates automatically.

### Motivation and Context

Users may want to disable automatic updates for a variety of reasons, but my motivation specifically stems from #811 (Franz no longer opens at all; I rolled back to the previous version to fix this, but the automatic updating of Franz means that I can not use it at all; it has been months since the last update, so I'm not sure how soon a fix will be released).

**Comment by opus-nbo** [comment]
I second that. The credential prompt for available updates is annoying for users who are not administrators.

**Comment by opus-nbo** [comment]
Yes, please add an option to disable automatic updates. It's unbearable to have the user asked for admin credentials to update. Makes me want to switch to Rambox.

**Comment by gabefighter99** [comment]
I third. This would prevent #1720 as well. Which would suck.
