### ISSUE TITLE
Flowdock: Opening link triggers an internal browser rather than local browser

### ISSUE THREAD

**Issue by adimasuhid** [meetfranz/franz#1022]
Flowdock: Opening link triggers an internal browser rather than local browser

### Expected Behavior
When a link is displayed, clicking the link opens it in a local browser.

### Current Behavior
When a link is displayed, clicking the link triggers an internal browser from within the client and attempts to load the link there.

### Screenshots (if appropriate):
![jul-02-2018 17-51-19](https://user-images.githubusercontent.com/2517299/42157552-9590cc8e-7e20-11e8-9e08-df5edff2e748.gif)

*Sidenote: Sorry it looks small, private chat*

### Steps to Reproduce (for bugs)
1. Add Flowdock to service
2. Chat a person then send a link
3. Click the link 
4. Result: Client opens an internal browser to load the link

### Context
Opening the links in the internal browser doesn't allow users to make use of their cookies/sessions/history already stored on the local browser. It currently works for other services I'vet tried: Messenger, Slack.

### Your Environment
* Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version: MacOS High Sierra 10.13.5

**Comment by SimonTod** [comment]
I would love this functionality 👍

**Comment by JoniSykes** [comment]
Not to mention in Flowdock integration you can't even right click and choose 'open link in browser'.
This could do with being fixed.
