### ISSUE TITLE
Stride image previews keep showing loading indicator

### ISSUE THREAD

**Issue by thibmaek** [meetfranz/franz#1024]
### Expected Behavior
When opening an image preview in Stride, the image should be visible.

### Current Behavior
When clicking an image preview, the modal opens but keeps showing the loading indicator

### Steps to Reproduce (for bugs)
1. Enable Stride
2. Log in to Stride
3. Click an image preview

### Context
This is a bit annoying since you can only see images as thumbnails.

### Your Environment
* Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version: macOS High Sierra (latest)

The console shows no errors.

**Comment by piotrek-r** [comment]
Confirmed on Ubuntu, the same version. The same full size image opens correctly in a standard Chrome window.

**Comment by lolmaus** [comment]
Stride has been liquidated. This issue can be closed.
