### ISSUE TITLE
Spellcheck in Polish language doesn't work

### ISSUE THREAD

**Issue by python4ever** [meetfranz/franz#1025]
### Expected Behavior
Writing a correct Polish sentence should not give me red underscores

### Current Behavior
Marks every word in Polish in red if its not an English word as well (like "ten" or "no")

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/15190180/42335577-1b9f49c4-8081-11e8-90a5-9ff1b31f4a00.png)

### Possible Solution
I don't really know :(

### Steps to Reproduce (for bugs)

1. Set Franz language as Polish
2. Relaunched Franz
3. Type in the sentence in Polish -> red underscores
4. Type in the sentence in English -> no underscores

### Context
The context is pretty simple - I would like those red underscores to indicate real typos, not all the words

### Your Environment

* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 Home

**Comment by chybaDapi** [comment]
I have the same problem. On a Windows OS, spell checker works correctly (OS language is set to polish), but on Ubuntu (OS: english language) all polish words are undescored as typos. 

@frynio, what is your OS language?

---- 
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

**Comment by frynio** [comment]
Mine is English with Polish keyboard

**Comment by chybaDapi** [comment]
I looked into Franz source code and now I can see that language of spellcheck depends on OS language. electron-spellchecker (used in Franz) allows to language detection based on sample text, but Franz uses language detection based on navigator.language (so this value is forced by OS). I wanted to change it, but I'm not able to run Franz Development App (a lot of errors) :(
