### ISSUE TITLE
Issue with Attachment Feature in Whatsapp

### ISSUE THREAD

**Issue by nsudds** [meetfranz/franz#1031]
When using Whatsapp in Franz, for some reason the Attachment feature for images and documents is no longer working.   Not sure what may have caused this but it goes through the whole process but then the last step when it would normally upload --- it just disappears. 

### Expected Behavior
Attach image >  Upload > Post to Chat

### Current Behavior
Attach image > Click OK .... Nothing. 

### Screenshots
http://screencasts.techsure.ca/2018-07-18_09h40_29.png

### Possible Solution
I tried things like reloading the service, disable/enable, rebooting, closing and opening... no luck.  I didn't try reinstalling or repairing the whole Franz service yet hoping there's another solution. 

### Steps to Reproduce (for bugs)
Step 1.   Click Attach icon
Step 2.   Choose Photos & Video or  Documents
Step 3.   Add Photo and click OK
Step 4. ----  This is where the issue is on my system.   Usually it will post the photo and ask for a message to go with it but nothing happens. 

### Context
Can't post files and screenshots to contacts. 

### Your Environment
Windows 10  (I'm on an Insider Edition but not sure if that's related to the problem, I've been on that for a while)
* Franz Version used:  5.0.0.0-beta18
* Operating System and version: Windows 10 Insider Preview
http://screencasts.techsure.ca/2018-07-18_09h50_39.png

**Comment by nsudds** [comment]
Just found a workaround ---- drag and drop is working!

**Comment by brunofunnie** [comment]
Yeah I have the same behavior too, also, the same happens if you try to download a file (in my case) but I am using Linux (Pop! OS 18.04 LTS a Ubuntu variation), clean install. The workaround in my case is to ALT+TAB twice, blurring and focusing seems to make the window "work", but not for clicks, just for keyboard (tab to navigate yada yada)
