### ISSUE TITLE
Possible to update to current chromium version

### ISSUE THREAD

**Issue by ManuSevenval** [meetfranz/franz#1032]
We use the cisco spark recipe to communicate with colleagues over cisco webex teams.
This worked fine, until a few days ago.

It started with non working video calls (Error Message: Chromium 59 is not sufficient for the current video call implentation) and ended with us not being able to use the cisco spark recipe at all ( => blank screen).

Would you accept a MR for upgrading to the current chromium version in electron?
If so, I would gladly open the MR for you.

Thanks and greetings from Vienna!

### Your Environment

* Franz Version used:
MacBook Pro 2017, High Sierra 10.13.5
Version: 5.0.0-beta.18
Release: 1.8.4 / darwin / x64

**Comment by morgej** [comment]
I believe that this same problem - needing to update the Chromium version - is required to resolve my current Teams issue.

![image](https://user-images.githubusercontent.com/13367152/56422113-e092f800-6273-11e9-9814-ea8710c0114c.png)
