### ISSUE TITLE
Links from emails in Outlook (Office 365)

### ISSUE THREAD

**Issue by fredpaxton88** [meetfranz/franz#1034]
When clicking a link in an email in the Office 365 Outlook Web App, I expect it to open a Chrome window (or a tab in the window if there's already one open).

Instead, a small pop-up window appears (without the address bar, bookmarks bar and so on). Furthermore, if a second link is clicked it replaces the link within the same pop-up window.

**Comment by cvaliente** [comment]
same issue as https://github.com/meetfranz/franz/issues/1150
