### ISSUE TITLE
Can't login into Slack: form freezes after inputting the password.

### ISSUE THREAD

**Issue by lolmaus** [meetfranz/franz#1035]
### Expected Behavior

I'm able to input login and password into Slack login form and get logged in.

### Current Behavior

I input login and password successfully. When I submit the password, page freezes.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/200884/42996560-99c705c0-8c1c-11e8-8aa4-008564deb119.png)

### Possible Solution

Reloading the service makes it logged in and usable. But I need to wait before reloading: if I reload immediately after the freeze, I'll see the login form again.

### Steps to Reproduce (for bugs)

Not sure if it's reproducible on other machines.

### Context

I had installed fresh Franz 5, logged in and got my services synced.

### Your Environment

* Franz Version used: Version: 5.0.0-beta.18, Release: 1.8.4 / linux / x64
* Operating System and version: Linux Mint 18.3 64-bit (based on Ubuntu 16.04)

**Comment by OlofHaglund** [comment]
This is also an issue on Fedora 28. Same Franz version and release.

**Comment by devzsolt** [comment]
Same on a fresh install of Manjaro 17.1.12 using Franz 5.0.0-beta.18
What's wrong with it?

**Comment by iamkoch** [comment]
Same happens on Windows 10 and OSX

**Comment by alkaithil** [comment]
Same here on OSX High Sierra 10.13.6

**Comment by D-Workz** [comment]
push, linux manjaro
