### ISSUE TITLE
Bad flickering under Linux despite GPU acceleration disabled

### ISSUE THREAD

**Issue by antifa-ev** [meetfranz/franz#1036]
== Franz ==
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

There is bad flickering with mesa 18.1.4 or mesa-git and a RX 460 GPU.

I'm reporting this because I've DISABLED gpu acceleration, but the problem remains.

Other electron apps like Atom work without problems.

**Comment by antifa-ev** [comment]
The screen gets white block-wise, Franz is nearly unusable by this. Take a look on this screenshot:

![shot](https://user-images.githubusercontent.com/41199978/43252450-cd8acdd8-90c2-11e8-918c-c4a18bb9d4d3.png)

**Comment by dancsonth** [comment]
Have you resolved this? I am now suddenly getting it on my Mac OSX Mojave. Only change that happened that I can think of is me downloading Python 3.x
