### ISSUE TITLE
Notification API does not match spec: missing `close` method.

### ISSUE THREAD

**Issue by brockwhittaker** [meetfranz/franz#104]
The Notification API wrapper implemented by Franz does not have the `close` method when the class is instantiated.

It appears as though `Notification.close` exists, however this is incorrect, and should really be `Notification.prototype.close`. This will cause errors/tracebacks in applications that use the `close` prototype method.

### Screenshots (if appropriate):
<img width="912" alt="screen shot 2017-10-24 at 11 23 28 am" src="https://user-images.githubusercontent.com/10321399/31960844-e12f4a46-b8ad-11e7-8d0d-44718dffd829.png">

### Possible Solution
Change noop function that currently resides in `Notification.close` => `Notification.prototype.close`.

### Steps to Reproduce (for bugs)
Run the following code:

```js
var notification = new Notification({});
// triggers an error as `Notification.prototype.close` does not exist.
notification.close();
```

### Context
This breaks notifications in the Zulip application and creates tracebacks that are sent to our sever.

### Your Environment
* Franz Version used: Version 5.0.0-beta.10 (5.0.0-beta.10.7)
* Operating System and version: MacOS High Sierra

**Comment by adlk** [comment]
@brockwhittaker thanks for bringing this issue up and your clear guide to solve it. This fix will be shipped with beta 12 in the next few days. 🙌
