### ISSUE TITLE
Todoist app doesn't save login session and requires login each time Franz is restarted

### ISSUE THREAD

**Issue by mlevit** [meetfranz/franz#1040]
### Expected Behavior
Todoist should remain logged in if Franz is restarted

### Current Behavior
Todoist reverts back to the login screen after Franz is restarted

### Screenshots (if appropriate): 
![image](https://user-images.githubusercontent.com/233717/43138107-3685e828-8f91-11e8-98a8-c10358328d5a.png)

### Your Environment
* Franz Version used: 5
* Operating System and version: 
![image](https://user-images.githubusercontent.com/233717/43138193-6f27248a-8f91-11e8-9001-1c4bc5ed6f4c.png)

**Comment by avatarkava** [comment]
https://github.com/avatarkava/recipe-todoist/issues/3 I fixed this on my maintained version of the recipe back in February but it hasn't been integrated into the official repository (yet?) - instructions on how to fix in the meantime are there.

**Comment by mlevit** [comment]
@avatarkava yep that solved the issue. Thanks mate.
