### ISSUE TITLE
A _blank window always appear

### ISSUE THREAD

**Issue by leoheck** [meetfranz/franz#1043]
Maybe duplicate but...

I am always getting this _blank window

Using Franz version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

![image](https://user-images.githubusercontent.com/1277920/43273395-b001e700-90d2-11e8-9178-1f4bee150d2d.png)

**Comment by okosowski** [comment]
the same issue on mac os x. during 8h work day, I have to close it at least three times

**Comment by testlaben** [comment]
this happens when opening a web link from within franz.

**Comment by nasmithan** [comment]
Also having this issue. Anytime I open a web link inside Google Chat

**Comment by AntStephenson** [comment]
This happens for me on **all** links on 5.3.3.1582, running OS X 10.14.6
