### ISSUE TITLE
Missing the icon (franz) from the application menu with appimagelauncher

### ISSUE THREAD

**Issue by Lvaskz** [meetfranz/franz#1045]
Hi, I'm using Ubuntu 18.04, Gnome 3.28, 64 bits, community theme. I am currently using appimagelauncher to install appimages in the applications menu. I understand that franz has an installation script, however when using appimagelauncher the icon of the application menu disappears, or gets lost. If I'm not using appimagelauncher, the icon appears in the applications menu. Could you make franz compatible with appimagelauncher?
 see https://github.com/TheAssassin/AppImageLauncher

**Comment by rubensa** [comment]
See: https://github.com/meetfranz/franz/issues/940#issuecomment-386233956

**Comment by closingin** [comment]
@Lvaskz , if rubensa's answer fixed your bug, can you close your issue or elaborate more ? Also please use the template that is provided when you open an issue next time.
