### ISSUE TITLE
No icon, Ubuntu 18.04

### ISSUE THREAD

**Issue by andres-jurado** [meetfranz/franz#1048]
Instead of the Franz logo, a black rectangle is shown in Ubuntu's launcher.

Also, is Franz still being developed? The last version came out in April, I believe.

**Comment by Dargmuesli** [comment]
On Arch it help to create a symbolic link like this:
`sudo ln -s /usr/share/icons/hicolor/1024x1024/apps/franz.png /usr/share/pixmaps/franz.png`

**Comment by Lvaskz** [comment]
I am in ubuntu 18.04, Icon from the dock is mising too, and apps menu.
I am using appimagelauncher to integrate appimages, but this is an appimage type1, this new tools ( appimagelauncher) are designed to operate better with appimages type2, can you update to appimage type 2?

**Comment by rubensa** [comment]
See: https://github.com/meetfranz/franz/issues/940#issuecomment-386233956
