### ISSUE TITLE
[FB Messenger] Notification title from group chat showing up as [object Object]

### ISSUE THREAD

**Issue by andrewwong97** [meetfranz/franz#105]
bug: when I'm in a Facebook group chat, the desktop notification name of the group/person will show up as [object Object]

### Expected Behavior
Notification title should show up as the name of the group chat, or the name of the user who posted the message

### Current Behavior
Notification title shows up as [object Object]

### Screenshots (if appropriate):
![example](https://user-images.githubusercontent.com/7339169/31964600-96181cc0-b8d2-11e7-9610-e93aa8dc7234.jpg)

### Possible Solution
not sure?

### Steps to Reproduce (for bugs)
1. Create a group chat with 3 or more participants
2. Receive a message in the group chat (with desktop notifications turned on)

### Context
Can't see sender/group name of message

### Your Environment
* Franz Version used: 5.0.0-beta.10
* Operating System and version: macOS 10.13 (17A405) High Sierra

**Comment by adlk** [comment]
In [AppStore.js#143](https://github.com/meetfranz/franz/blob/master/src/stores/AppStore.js?utf8=%E2%9C%93#L143) we need to check what the title is to send the correct notification.

**Comment by GustavoKatel** [comment]
Franz 4 is showing the same problem. Did the messenger change something?

**Comment by GustavoKatel** [comment]
Debug point: webview/notification.js#12

This is the notification that messenger is sending:
![image](https://user-images.githubusercontent.com/1891977/32012743-480743fe-b98f-11e7-966d-ef7c18ed7246.png)

MDN says the title should be a DOMString: https://developer.mozilla.org/en-US/docs/Web/API/notification/title :confused: 

If this is a specific case for this recipe, a specific notification parser should be used (maybe defined in the recipe's webview.js)

**Comment by adlk** [comment]
@GustavoKatel You are right, thats a great idea.

On top, in `ServiceStore.js@_handleIPCMessage()` we should add a check if the value for title and text is anything else than a string to provide fallback values.

- [ ] Add additional checks in ServiceStore
- [ ] Add `onNotify` to docs in www.github.com/meetfranz/recipe
- [ ] Update the messenger recipe

Is there something specific that you want to take care of?

**Comment by GustavoKatel** [comment]
I agree with the fallback values. I can create a PR covering the checkboxes :+1: 

PS.: By meetfranz/recipe, you mean meetfranz/plugins ?

**Comment by GustavoKatel** [comment]
[x] Add additional checks in ServiceStore
[x] Add onNotify to docs in www.github.com/meetfranz/recipe
[x] Update the messenger recipe

I hope everything is ok :) Otherwise, let me know

**Comment by abdodaoud** [comment]
Updated to the latest 5.0.0-beta.12 on macOS 10.12.6 and FB Messenger group chat notifications stopped showing up as [object Object] like in previous builds, but instead are just plain empty.

![screen shot 2017-11-06 at 5 45 30 pm](https://user-images.githubusercontent.com/4540475/32449481-592ad6c0-c31a-11e7-8dad-1fe9df358bd3.png)

**Comment by adlk** [comment]
I need to do a few more checks but we might just need to optimize the messenger recipe a little further. The update will be rolled out automatically without a necessary client update. Just expect that notifications will work as expected sometime soon. ;)

**Comment by andrewwong97** [comment]
<img width="234" alt="screenshot 2017-11-09 13 24 10" src="https://user-images.githubusercontent.com/7339169/32622581-54f48ad6-c551-11e7-8a5e-d660e3c88f46.png">

Getting M as the chat title 

Version: 5.0.0-beta.13 on macOS 10.13 (17A405)
