### ISSUE TITLE
Request to add Protonmail service

### ISSUE THREAD

**Issue by Dvlnst** [meetfranz/franz#1050]
[Protonmail](https://protonmail.com/) is a secure email service. It's becoming popular and there is not desktop clients yet.

**Comment by kvsjxd** [comment]
You may like to check this out https://github.com/kvsjxd/electron-ProtonMail

**Comment by closingin** [comment]
"This repository is only for the Franz client. Please use this form ( https://bitly.com/franz-service-request ) for service requests or check out the guide ( https://github.com/meetfranz/plugins ) to create your own service integration."

This message is given to you when you create an issue. Did you read it ? No. You can close your issue.
