### ISSUE TITLE
[Feature Request] Provide RPMs, yum repository

### ISSUE THREAD

**Issue by pschiffe** [meetfranz/franz#1052]
Allow distribution of Franz as RPMs, ideally with yum repository containing this RPMs. For example [Atom Editor](https://flight-manual.atom.io/getting-started/sections/installing-atom/#red-hat-and-centos-yum-or-fedora-dnf) is providing yum repo via [packagecloud](https://packagecloud.io/), which is pretty handy.

### Motivation and Context
RPM package allows better integration with RPM based Linux (Fedora, Centos, RHEL, SUSE...) and the repository makes updating the package super easy.

**Comment by lskillen** [comment]
@adlk @kwk @schiffe Please feel free to consider [Cloudsmith](https://cloudsmith.io) as well for packaging. :-)

It's commercial but has very generous free plans and offerings for open-source projects (100GB of storage and 1TB of bandwidth, with more available on request); you don't need to apply, just create an open-source repository and away you go. You can also setup an org with several users to manage the account.

*Full disclosure*: I work for Cloudsmith, so might be biased (but only _slightly_, honest)!

**Comment by Daemoen** [comment]
I would say this request is reasonably superceded by the 'closed' https://github.com/meetfranz/franz/issues/661 which outlies plenty of the reasoning above, but makes it even more universally accessible.
