### ISSUE TITLE
Add ability to create tab with custom webpage URL in Franz

### ISSUE THREAD

**Issue by MurzNN** [meetfranz/franz#1056]
Franz have support for limited list of services, but people use many different services that missing in Franz and want to have them in quick access near to standard services, not as regular tab in browser between many other tabs.

So will be good to have ability for create new tab in Franz, that shows favicon and webpage from custom URL like regular browser.

**Comment by Lazza** [comment]
You might be interested in checking out the docs:

https://github.com/meetfranz/plugins/tree/master/docs

The quickest way to develop your own plug-ins is to duplicate (and rename) the one for WhatsApp, then customize the base URL, the `getMessages` function and the CSS (if needed).

**Comment by oliver-gramberg** [comment]
https://github.com/jvdmeij/recipe-franz-website

**Comment by MurzNN** [comment]
Creating custom recipie is too hard way for regular users, will be good to implement this feature in frontend interface, like in rambox.pro. So users will can add new services via clicking on button "Add new custom service", filling url and name, and that's all.

**Comment by Lazza** [comment]
> filling url and name, and that's all

That would still require the user to write a custom JS function to display the unread count badge, though.

**Comment by MurzNN** [comment]
Viewing unread count badge is not so Important feature, and can be solved via pasting js into text area field (like in Rambox too)

**Comment by Lazza** [comment]
The fact that it's "not so important" is debatable. To me, the whole point of using Franz or similar tools is to be able to check if I have unread stuff.

Franz does not show the window title nor the favicon, so there is no visual feedback other than the badge.

It seems that Franz makes possible to do what you are suggesting, for people on the paid (highly priced) accounts, though.
