### ISSUE TITLE
Show unread message badge only in Franz window but not in systray

### ISSUE THREAD

**Issue by ilopmar** [meetfranz/franz#1057]
I'm not sure if this is a bug or a feature request. I would like to be able to configure a Slack channel to show the badge when there are unread messages but I want the badge to be displayed only in Franz window but not in systray.
If I enable the option "Show message badge for all new messages", then the badge is displayed in both Franz and systray.

My use case is to have an overview of all my services (slack, gitter,...) in Franz main window but without showing the badge in the systray. I have only enabled the systray notification for really important services.

In main window I would like to have this:

![image](https://user-images.githubusercontent.com/559192/43891941-e87cf78e-9bca-11e8-8b4e-35a6f3e44a0b.png)

This way I know I have pending messages in 2 slack channels. But enabling the "show message badge for all new messages" makes that the badge is also displayed in the systray (which I don't want).
On the other hand, when I disable the option I see:

![image](https://user-images.githubusercontent.com/559192/43892024-25f6d1de-9bcb-11e8-850e-1b148ff8cb1c.png)

But I don't know that there are pending messages in those channels.

I'm using Version: 5.0.0-beta.18 on Linux.

**Comment by herwix** [comment]
+1 
I would love to be able to schedule my use of social media/franz more deliberately and being able to control when the systray notifications show up would be awesome.

**Comment by ilopmar** [comment]
Ohhh :cry:
