### ISSUE TITLE
[Feauture Request] Custom useragent

### ISSUE THREAD

**Issue by ArmeF97** [meetfranz/franz#1060]
Can we add an option to each service in which you can set a custom user agent?
Very useful for, example, instagram web (mobile version)

**Comment by matios13** [comment]
Yeah, it would be very useful in microsoft teams to set user agent to edge

**Comment by alexandruspataru** [comment]
+1 for this feature

**Comment by hongshaoyang** [comment]
https://github.com/meetfranz/plugins/blob/master/docs/backend_api.md should solve this?
