### ISSUE TITLE
Notification badge won't clear in Skype

### ISSUE THREAD

**Issue by KeithGillette** [meetfranz/franz#1064]
### Expected Behavior
Unread message notification badge should only appear when unread messages or service notifications exist in a service.

### Current Behavior
In Skype, I get an unread message badges even though the Skype desktop app reads "No new notifications" in the Notifications tab. The incorrect notification badges persist through Reloading, Disabling/Enabling, & Deleting/Re-adding the services.

### Your Environment
* Franz Version used: 5.0.0-beta.18
* Operating System and version: MacOS X 10.13.6

**Comment by KeithGillette** [comment]
Nevermind. It was a cookie warning in the web version of Skype!

**Comment by alekszi** [comment]
How u solve it?
