### ISSUE TITLE
Franz broken for months on Windows 10

### ISSUE THREAD

**Issue by n4ru** [meetfranz/franz#1065]
The problem is simple. Some version after beta15 has completely broken Franz, and has caused it to completely disappear. Opening it does nothing, yet it runs in the background. There are multiple reports of this issue, yet I have not seen a response or update to fix it.

Even more annoyingly, I have to constantly downgrade back to beta15 because Franz will update itself akin to Windows randomly restarting for updates. If not auto-updating, then Franz will simply persist with an annoying nag at the bottom of the screen which I cannot remove, and obviously I cannot update as that breaks Franz completely.

**Comment by blis5fool** [comment]
Weird. I'm on beta 18 and it's working fine for me.

**Comment by berhir** [comment]
I am not sure if it is the same problem, but on my device from time to time Franz starts outside of my screens view. I see that the app is open in the taskbar, but when I click on it Franz doesn't appear.

Solution: First make sure that Franz is the topmost App and then press "Alt + Space" to open the context menu of the window. Then in the context menu click on Maximize.

**Comment by JeanGalt** [comment]
Hi, 
I have the same problem as n4ru
