### ISSUE TITLE
Franz is starting in development mode??

### ISSUE THREAD

**Issue by FFY00** [meetfranz/franz#1068]
### Expected Behavior
Staring franz normally.

### Current Behavior
Franz starts in development mode.

### Steps to Reproduce (for bugs)

1. Build franz in Arch Linux from [my PKGBUILD](https://github.com/FFY00/franz-pkgbuild) (See instructions [here](https://github.com/Tribler/tribler-arch-pkgbuild))
2. Install the package
3. Start Franz

### Context
My build process uses systems' electron instead of bundling electron together with Franz.

### Your Environment

* Franz Version used: 5.0.0-beta18
* Operating System and version: Arch Linux updated as of 21/8/2018 6PM

**Comment by pascencio** [comment]
@FFY00 I have the same issue... Any workaround?

**Comment by FFY00** [comment]
AFAIK no

**Comment by VinyLimaZ** [comment]
One more here

**Comment by VinyLimaZ** [comment]
Use the `franz-bin` option from AUR to install without this behavior...

**Comment by FFY00** [comment]
I am aware. I'm the packager for `franz` in the AUR.

**Comment by jabossu** [comment]
Same issue. I didn't find any way to disable this behaviour in the settings.

**Comment by Codigos-de-Guerra** [comment]
Same problem over here. Only blank electron runs.
