### ISSUE TITLE
When adding a new service, ordering keeps jumping around

### ISSUE THREAD

**Issue by gjoris** [meetfranz/franz#107]
Not a very important bug, but quite annoying: the order of the services jumps back to the order in which they have been added to the application when adding a new service. I reorder them to have a nice overview, and it's quite annoying that they jump around when I add a new service.

### Expected Behavior
What should happen, is that the order in which I place them, should be kept.

### Current Behavior
They jump back to the order in which they were added.

### Possible Solution
I haven't looked at the code, but I assume that an array is kept somewhere with all the services. This should also contain an order index, which is updated when dragging and dropping the icons in a different order.

### Steps to Reproduce (for bugs)
1. Add services
2. Drag them in a different order
3. Add another service

### Context
As said: I want to change the order, to have a better overview and grouping.

### Your Environment
* Franz Version used: 5.0.0-beta.10.7
* Operating System and version: macOS Sierra 10.12.6

**Comment by adlk** [comment]
Can you please update to beta 11 and check if it's still happening?

**Comment by martincampbell** [comment]
Still happening exactly as described above in Franz 5.0.0-beta.11.135 on macOS High Sierra 10.13.

**Comment by gjoris** [comment]
@adlk Seems to be solved for me! The difference with @martincampbell is the macOS version, I haven't updated to High Sierra yet.

**Comment by GustavoKatel** [comment]
I could reproduce the bug in the latest commit. Submitted a PR that can solve it

**Comment by adlk** [comment]
@GustavoKatel thanks for your PR, will be shipped with beta 12
