### ISSUE TITLE
Please consider optimizing the LinkedIn CSS a bit

### ISSUE THREAD

**Issue by Lazza** [meetfranz/franz#1073]
### Expected Behavior

The LinkedIn chat should be large and readable.

### Current Behavior

Now the LinkedIn chat window is small, it comprises a sidebar that only shows ads and a lot of wasted space.

### Possible Solution

The look can be vastly improved with a bit of CSS:

```
body { overflow-y: auto; overflow-x: hidden; }
.ad-banner-container { display: none }
.msg-messaging-container { height: 100% }
#messaging { margin-bottom: -100px }
#messaging .right-rail { display: none }
#messaging .neptune-grid.two-column .core-rail { width: auto }
#messaging .msg-conversations-container { flex: 0 0 30%; }
#messaging .msg-conversations-container + * { flex: 1; width: auto; max-width: 100%; }
```

### Context

This issue makes it quite inconvenient to use the LinkedIn chat.

### Your Environment

* Franz Version used: 5.0.0-beta
* Operating System and version: irrelevant

**Comment by indykoning** [comment]
I'm sorry but i don't think this is really possible since Franz just opens the LinkedIn website without anything special happening except for it checking some key DOM elements for unread messages.

**Comment by Lazza** [comment]
@indykoning I ended up cloning the Whatsapp plugin (which includes custom CSS) and adapting it to LinkedIn. Now I use my custom plugin instead of the standard one.

Thus it is possible. 😊

**Comment by closingin** [comment]
Hello @Lazza,

Basically, Franz just displays web pages in a window. We don't interact with what is displayed (even though it's possible, but you would have to edit the service integration, not Franz source code), so that wouldn't make too much sense here. You should blame LinkedIn developers hehe.

Might be of interest if the service is not usable, but I don't know where the recipe for LinkedIn is.

**Comment by Lazza** [comment]
@closingin if it so, could you clarify why the official Whatsapp service includes custom CSS?

In fact, I cloned that one to use it as a basis for my own service. Also, given the fact that there is no GitHub repo for the **official** Franz services, it felt natural to post here.

Thank you.

**Comment by closingin** [comment]
Yup, the services are centralized, but most of their sources are listed in [meetfranz/plugins](https://github.com/meetfranz/plugins/) (but not the LinkedIn one apparently).

As said, normally this issue wouldn't fit in this repository, but as I don't know where this service' sources are, that's alright I guess. We'll wait for someone from the team to reply.
