### ISSUE TITLE
Franz Window doesn't move to primery screen when external screens are unplugged on Windows 10

### ISSUE THREAD

**Issue by PackElend** [meetfranz/franz#1076]
Hallo,
I run Franz on notebook what is connected to two external screens via a docking station. The notebook screen is also used, so I have 3 desktops.
When I undock the notebook the Franz window remains on the desktop of the external screen although there isn't any second or third desktop anymore. The shortcut Win+Shif+Key doesn't work either.

**Comment by alapo** [comment]
Had the same issue on my thinkpad

**Comment by aav7fl** [comment]
Partial solution. This only works if Franz is not maximized. So maybe use the Win+Arrow key to un-maximize if the following doesn't work.

When it's on the other monitor:

1. Select it from the taskbar.
2. While in focus (although not visible), press `ALT+Space` to bring up the window accessibility options.
3. Press `M` (on your keyboard). This selects the `Move` accessibility option on the Window.
4. Tap on an arrow key. (I usually tap the left one. This focuses the Window to your mouse)
5. Move your mouse and the Franz window will magically be snapped back onto your monitor. 

I've only had this work when I tap the arrow key before moving the mouse. Not sure why, but I used to have the same problem with Slack.

**Comment by Nikya** [comment]
Same here on Windows 7.
Win+Arrow doesn't work.
But the @aav7fl solution work fine, Thanks !
