### ISSUE TITLE
Why do we need these accounts exactly?

### ISSUE THREAD

**Issue by Gaboris** [meetfranz/franz#1077]
After checking out Rambox(which seems to be HEAVILY "influenced" by Franz) I started wondering about why do these "IM browsers"(as I like to call them) require us to login with an account?

If the reason for the payed versions is mainly the server costs then why can't we have an "offline" version without any of the sync or backup options and keep those for the payed users?
Does our traffic need to be routed through some servers to work or something? A guy once mentioned that on his side my client is said to be coming from Vienna, but I brushed it off as it's the IRC server that's hosted there, but now I'm a bit concerned.

These clients are "just" cut down minimalist browsers only meant to run selected web apps properly. I LOVE this solution! This is the best way to keep all those IMs' functional and manageable, but after hearing that Rambox is collecting their users' data(probably usage analytics) through said browser I'd like to at least know if I'm being treated like a product or not.

Of course IF there really is no data collection going on and Franz really just wants to offer this sync functionality for all users why can't we have the option to opt-out?

**Comment by Wouter0100** [comment]
It's not only the sync feature: also the repository requires a centralised environment. Of course, this could be decentralized - but then there is nearly no business case to make some bucks.

**Comment by Gaboris** [comment]
> 
> 
> It's not only the sync feature: also the repository requires a centralised environment. Of course, this could be decentralized - but then there is nearly no business case to make some bucks.

Okay so I'm an IT guy, but still I sadly never got into actual programming so I'm gonna ask what does "repository" mean here? (I know what the word itself means since even though I'm Hungarian I'm pretty good with English. But not sure if it has a special meaning in this context.)

You mean the fact that they need a server for hosting the website, the code that can be downloaded for installation or updates and the self hosted functionality for some IM's? I get that, but why keep authenticating my logins, store my data and supply me with said data each time when I'm obviously not meaning to pay for such costs?

If it's all about giving an incentive for people to say "Eh, why not. Might as well pay for a subscription." then I can get that from a business standpoint, but it still feels "off".

But again, my main complaint is that I don't know if my traffic is just between me and the other client as in point-to-poitn or is it being routed through some servers for whatever reason?

**Comment by Wouter0100** [comment]
@Gaboris The latter is exactly the reason why I prefer clients (like Franz) that are open source: you're able to see what is happening and you will see that - for example - your Messenger of WhatsApp isn't rerouted through any Franz server.

With a `repository` I mean a collection of recipes available for Franz, and the ability to install recipes on-the-fly. In Franz example, this list: https://api.franzinfra.com/v1/recipes (including downloads, and so on). 

And it all comes back to UX/user friendliness. If you'd like to build a "skip" button at the login page and by that login as a guest and not apply for the paid services in any way (and so, only use the free available resources), then I think it'll get accepted - but that's not quite user friendly, in a way that you need to do everything again when you reinstall your system.

**Comment by Gaboris** [comment]
Oh yeah, I know. That's pretty sweet, but I'm asking about this exactly cuz I myself don't know where to look for such info within the code and as I mentioned Rambox has data collecting system in it that they didn't mention in their docs and was only found by a user recently.
So I'm asking this in case someone has either already has or just might get the idea to look into it after someone asks about it. :)

Also I know how we can build our own stuff with a given source code, but again if I had the skills and time to do that I might as well try to make my own or even create a fork of it here and then spend all my time maintaining it for later updates. XD

**Comment by indykoning** [comment]
You can always check what is happening with your data and connection using wireshark while starting franz or logging into your account using franz. However from as far as i have seen nothing special happens. When i make a custom franz app connect to localhost it actually does go to my computer.

**Comment by Gaboris** [comment]
In light of the recent "server outage" I'd like ti bump this thread of mine and also append the idea of adding an "offline" backup option to it if nothing else.

I'm still not sure if development is going to start up again or not after such a long time let it be health issues or lack of interest, but if anything happens I'd like this option to be the first added just to be safe.

**Comment by benwaffle** [comment]
Franz uses Google Analytics - https://github.com/meetfranz/franz/blob/1790b795238c2abe832285197cb88c0833bd98ca/src/lib/analytics.js

**Comment by jirutka** [comment]
Is source code of the Franz server (https://api.franzinfra.com) available? I'd like to run my own instance to avoid centralized service.

**Comment by MagicLegend** [comment]
Any progress @Wouter0100? Would also like to run my own Franz server :-)

**Comment by bisby** [comment]
Without having read all the source code, I would also love to know why we can't skip Franz account creation.

The privacy statement (https://meetfranz.com/privacy/) says:
> If you explicitly opt in to synchronize your session data

I read that as sync is optional. To use what is essentially a "per-tab sandbox" browser, requiring an account feels very overkill.

**Comment by lodi-g** [comment]
@adlk Please read

**Comment by Chrzi** [comment]
> It's not only the sync feature: also the repository requires a centralised environment. Of course, this could be decentralized - but then there is nearly no business case to make some bucks.

Yes it makes sense to centralize this, but that is **no** reason to force a login.
Just ship it with the repository available during the build. For on-the-fly updates request it from the server and update the local one if necessary.

If you really want to DDOS the API server, then a login is not going to stop you.
 
>  but that's not quite user friendly, in a way that you need to do everything again when you reinstall your system.

I really don't care if I have to setup my 3-5 accounts once I reinstall Franz. That is something I do maybe once or twice a year. And I am going to take the privacy benefit other that little bit of comfort (as many others would as seen here #71 )

**Comment by jnvandermeer** [comment]
So I used Franz previously without the login option. This was really handy and hassle-less. Now with the password login requirement, it's no longer a program I can recommend to others. Please remove this (rather stupid) requirement? I do not buy into the argument "can easily sync with other computers you install Franz on".

**Comment by adlk** [comment]
This has already been discussed in length at #71.
