### ISSUE TITLE
Franz System Tray  icon on KDE 

### ISSUE THREAD

**Issue by Amonir** [meetfranz/franz#1082]
Franz System Tray  icon on KDE is not displayed correctly 

Currently, I am using Kubuntu 18.04 with KDE Plasma 5.12.6
The Icon displayed in the system tray is not correct (attached )

### Screenshots 
![image](https://user-images.githubusercontent.com/35955136/45685848-feb44080-bb4a-11e8-896a-8c6bd48a5c0b.png)

**Comment by npantos** [comment]
Same issue on KDE Neon 5.14
![image](https://user-images.githubusercontent.com/1032634/46904094-51c9ab00-cedf-11e8-9287-aa28be4945ff.png)

**Comment by gringo-go-go** [comment]
This is related to Electron apps. 
In "Edit applications" KDE menu, change path from "/usr/bin/franz" to "XDG_CURRENT_DESKTOP=Unity /usr/bin/franz". Or edit the .desktop file.

**Comment by pat-s** [comment]
Or use https://github.com/bilelmoussaoui/Hardcode-Tray

**Comment by MurzNN** [comment]
gringo-go-go solution works well, thanks! Hardcode-Tray is also good way, but too serious for this simple problem.

**Comment by MasterGeekMX** [comment]
> This is related to Electron apps.
> In "Edit applications" KDE menu, change path from "/usr/bin/franz" to "XDG_CURRENT_DESKTOP=Unity /usr/bin/franz". Or edit the .desktop file.

Tested on KDE Neon 5.16. Didn't worked

What it worked was replacing Unity by GNOME in the XDG parameter

![imagen](https://user-images.githubusercontent.com/10291989/61801117-dabd2d80-adf3-11e9-8dfd-0450e74f6145.png)

**Comment by cidwel** [comment]
Working too on KDE neon using:
"XDG_CURRENT_DESKTOP=KDE /usr/bin/franz"
