### ISSUE TITLE
Google Calendar not loading events at first opening

### ISSUE THREAD

**Issue by bimbo1989** [meetfranz/franz#1085]
### Expected Behavior
When showing the google calendar, I should be able to see the events in my calendar for the current month.

### Current Behavior
Now, when opening the tab, the calendar appears with no events. To make events load, I must change month with the arrows on top of the page. For example, now september looks empty. If I go to october it loads october events correctly. If I switch back to september now loads september correctly too.

### Steps to Reproduce (for bugs)
1. Add Google Calendar to Franz
2. Open it

### Your Environment
* Franz Version used: Franz 5.0.0-beta.18
* Operating System and version: latest Windows 10

**Comment by supermarkert** [comment]
Same issue, on Windows 7. 
Quick fix is to simply press Ctrl-R on first open, as that will reload the page.

**Comment by derdritte** [comment]
I am experiencing the same issue on xubuntu Franz version 5.0.0-beta.18 (but I cannot remember it ever working correctly).

**Comment by jonhil** [comment]
Got the same problem on Windows 10 with Franz 5.0.0 beta.18
Quick fix with Ctrl-R does work for me too but shouldn't be the solution.

**Comment by TjebbeKerstens** [comment]
I can confirm this on MacOS 10.13.6 as well with Franz 5.0.0-beta.28. Refreshing on opening works, but as @jonhil mentioned, this shouldn't be the solution

**Comment by sNiXx** [comment]
Happens for me too on Windows 10 with Franz 5.0.0-beta.28. Reloading works, but is tedious...

**Comment by mumrau** [comment]
Still happening on both Linux and Windows installs.

I can't find the Google Calendar recipe in `meetfranz` repositories, maybe I could take a look if I find it.

Service is disabled on my end until then... Reloading is just not a nice way to use Franz.

**Comment by supermarkert** [comment]
I noticed that if Google Calendar is the last tab left open when Franz closes, then it does automatically reload the page when Franz re-launches (and that tab will be the default focus).
But if _another_ tab was the last primary when it closed, then Franz doesn't reload it in the background when it is launched again.

**Comment by supermarkert** [comment]
Not sure what changed, but this appears fixed now and is always refreshed when launched. I'm still on beta.22 and it is working correctly. I've received several notices over the last few days about how "modules were updated", so maybe that was it.
Anyway, it's working for me now.

**Comment by mumrau** [comment]
Apparently working for me too under beta 24, on a Fedora 29 environment.
Will check on Windows by tomorrow.

**Comment by sNiXx** [comment]
Yes, I can confirm that this seems to be solved with Franz 5.0.0-beta.24 on Windows 10!

**Comment by mumrau** [comment]
Confirmed as well under Windows. Working under `5.0.0` release as well.

Pretty sure this issue can be closed.
