### ISSUE TITLE
Alt + Shift (which is used to change system's keyboard layout) in Linux opens the application "File" menu blocking the input

### ISSUE THREAD

**Issue by driver-by** [meetfranz/franz#1088]
### Expected Behavior
Alt + Shift, while typing in the app, should change the keyboard layout and nothing else.
### Current Behavior
It opens the "File" menu with "Settings"/"Quit" options and blocks the input.

### Possible Solution
Seems to be Linux related (my system is Linux Mint 18 Cinnamon x64) and it's common Electron issue. I faced this with slack too. There is the same [issue with Rocket.chat](https://github.com/RocketChat/Rocket.Chat.Electron/issues/50) and their [solution](https://github.com/RocketChat/Rocket.Chat.Electron/commit/5b684bbd4df4a583ac39a7f96a980da6feeabbe4) - to add underline shortcuts in the menu items with "&".

### Your Environment
* Franz Version used: Version: 5.0.0-beta.18 Release: 1.8.4 / linux / x64
* Operating System and version: Linux Mint 18 Cinnamon x64

**Comment by MurzNN** [comment]
Here https://github.com/electron/electron/issues/11106#issuecomment-441350115 is fix (workaround) for this problem, that must be applied to Franz menu:

> i fix this when building electron apps by assigning keyboard shortcut for each menu item &File instead of just File , this should be done to all top level menu items

**Comment by MurzNN** [comment]
Seems this can be simply fixed via adding to 
https://github.com/meetfranz/franz/blob/master/src/lib/Menu.js `&` symbols to each first level menu items. But there are no `label` field, like in other apps (eg [Rambox](https://github.com/ramboxapp/community-edition/blob/master/electron/menu.js)), so will be right to add them into `defaultMessage` variable?

Something like this:
```
const menuItems = defineMessages({
  edit: {
    id: 'menu.edit',
-    defaultMessage: '!!!Edit',
+    defaultMessage: '!!!&Edit',
},
```

**Comment by MurzNN** [comment]
Here is same solved issue in Riot Electron app https://github.com/vector-im/riot-web/issues/4345
And my pull request for fix it https://github.com/vector-im/riot-web/issues/4345

**Comment by nforced** [comment]
This is **still** happening today

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

**Comment by MurzNN** [comment]
Here https://github.com/electron/electron/issues/22213 is upstream issue about this problem.
