### ISSUE TITLE
Mac OS - program window too bright

### ISSUE THREAD

**Issue by shalafi83** [meetfranz/franz#109]
When using version 5.0 of Franz, the program window seems to be brighter than desktop and windows of other programs, like it has a setting by itself. This did not happen with previous versions. It seems to have a whitish film above.

### Expected Behavior
Colors coherent with the rest of desktop/windows.

### Current Behavior
Too much brightness / "whitish film" above the program window 

### Steps to Reproduce (for bugs)
install and try. Slack with default colors is quite evident

### Your Environment
* Franz Version used: 5.0
* Operating System and version: Mac OS Sierra 10.12.6

**Comment by adlk** [comment]
Is this something you can make a screenshot of? Is it visible on the screenshot as well?

**Comment by shalafi83** [comment]
<img width="765" alt="schermata 2017-10-25 alle 12 09 37" src="https://user-images.githubusercontent.com/5689644/31993528-b2c72252-b97d-11e7-8034-dcedb1bc0fe3.png">

upper part is what I see in Chrome, lower is from Franz

**Comment by shalafi83** [comment]
after yesterday update, it seems to be fixed now. Thank you!

**Comment by shalafi83** [comment]
Hello, yesterday update brought back the same problem :(

**Comment by adlk** [comment]
The interesting thing here is that electron hasn't changed. If you restart Franz and/or your machine. Does this problem persist?

**Comment by shalafi83** [comment]
Restarting Franz the problem remains, I'll try restarting my Mac asap, thank you!

**Comment by adlk** [comment]
@shalafi83 any update?

**Comment by haraldox** [comment]
@shalafi83 interesting observation, it's cool that this even occured to you ... do you have any screen brightness / color adjust tools running, e.g. Flux?

**Comment by shalafi83** [comment]
hello @haraldox, no I don't have any of it; but recently I noticed something.
I use Franz on my Mac at work, where I have an external monitor plugged via HDMI, and the setup is main desktop on the external monitor, secondary desktop on the notebook monitor. 
With this setup, it is likely to found franz with the "bright"/whitish effect. 
When unplugging the Mac and using it by itself, Franz seems to remain with that strange effects.
After a while, it returns to normal.

Now, I used it for the weekend without external monitor and Franz was fine. This morning, I plugged the monitor and Franz remained fine.

I'll give a check if, maybe, a restart with or without the external monitor plugged could make the trick, to better understand the situation.


Does it behave the same for you?

**Comment by haraldox** [comment]
@shalafi83 i haven't noticed anything, but I just may be not as keen as you remarking these things ;-)

**Comment by shalafi83** [comment]
ok, I can confirm, and I think this can help @adlk: it depends if the external monitor is plugged or not when I start Franz.
If it is, than the effect is as described; if it is not, everything is fine.
Plugging/unplugging after Franz is launched does not change the actual situation
