### ISSUE TITLE
Degraded performance

### ISSUE THREAD

**Issue by Sigri44** [meetfranz/franz#1090]
Hello,

I am seeing a deterioration in performance, which is getting worse and worse.
I have 4 services: Hangout/Chat, Trello, Messenger & Linkedin.

The software permanently consumes 2 GB of RAM, and often reaches peaks of 4 to 8 GB of RAM (out of 16, not bad!).

When dragging and dropping images, 2 times out of 3 the module crashes and asks to restart the service.

I have been using the service for almost 2 years, and as the days go by, the slowness becomes more and more apparent.

I have the highest 2016 MBP, so I don't think the machine's performance is at stake (regular cleaning, nightly shutdown, SSD optimization).

Sincerely.

Lastest version : 5.0.0-beta.18

**Comment by miku86** [comment]
For me, on Ubuntu 18.04,
Franz with all services disabled needs 150MB,
and every additional service adds around 150-200MB.

It would be useful to check which additional service adds how many additional MB to your RAM usage.

Furthermore, it is not bad if the memory is used as long as it does not lead to errors or lags.
Perhaps your RAM usage only correlates with your issues, not causes them.

**Comment by yangnaihua** [comment]
me too , and it is use  CPU too high 
![image](https://user-images.githubusercontent.com/7445145/49460168-005bdf00-f7f1-11e8-9845-85d37a59d735.png)

**Comment by bvdlingen** [comment]
Franz is using 12gb on my computer, when starting Franz my computer (16gb ram, 4 core i7)  is freezing for minutes this is really an issue
