### ISSUE TITLE
Is it possible to integrate Yammer?

### ISSUE THREAD

**Issue by schuelli238** [meetfranz/franz#1093]
Is it possible to integrate Yammer?

**Comment by indykoning** [comment]
This seems to be an issue for the [Plugin Repository](https://github.com/meetfranz/plugins/issues)

**Comment by closingin** [comment]
Hello Andre,

As indykoning said, from the "New issue" template that you obviously didn't read : _This repository is only for the Franz client. Please use this form ( https://bitly.com/franz-service-request ) for service requests or check out the guide ( https://github.com/meetfranz/plugins ) to create your own service integration._

Can you close your issue please ? :slightly_smiling_face:

**Comment by schuelli238** [comment]
Ok. For now, Yammer doesn't work for me in Franz - I will go for the plugin repository.
Thank you
