### ISSUE TITLE
Change User-agent string for Microsoft Teams on Linux to allow Video conferencing

### ISSUE THREAD

**Issue by riottino** [meetfranz/franz#1095]
Changing the user-agent string in Chrome/Chromium allows Linux users (I'm on ubuntu 16.04) to use almost all features of MS Teams (crucially, video conference and meetings).
Franz is, so far, the best solution available to have elegant notifications in the taskbar.
Spoofing the "correct" user-agent string in Franz for MS teams would make it -**by far** - the best solution available on linux for Teams.
https://techcommunity.microsoft.com/t5/Microsoft-Teams/TEAMS-and-LINUX-The-Future-is-Now/td-p/251876

**Comment by thefuzzyorange** [comment]
Agree with the above. I just came across the article now and it is a blessing as not being able to conference call is a really downer. 

This would definitely make Franz the prefered solution for running teams on linux!

**Comment by Xnst** [comment]
Hi,

I changed the user agent to MS-Edge in Franz MS-Teams service and the video meeting option came up. 

For each added Service a new recipe is added in ~/.config/Franz/recipes/ . In the one for MS-teams the file index.js already change the userAgent to Chrome. I changed it to dge for windows and it worked.

the line:
     return window.navigator.userAgent.replace(/(Franz|Electron)([^\s]+\s)/g, '').replace(/(Chrome\/)([^ ]*)/g, '$163.0.3239.84');

was changed to:

    return window.navigator.userAgent.replace(/(Franz|Electron)([^\s]+\s)/g, '').replace(/(Chrome\/)([^ ]*)/g, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393');

I know it is a bit crude to hard code a version like that - but it works. Perhaps someone can write something better.

**Comment by k0d3r1s** [comment]
while the mentioned "fix" helps with calls, i can't see any messages when i add Edge part in UA. without edge part there's no calls but messages work

**Comment by abmantis** [comment]
The following UA makes calls working and doesn't mess up the history:
`return window.navigator.userAgent.replace(/(Franz|Electron)([^\s]+\s)/g, '').replace(/(Chrome\/)([^ ]*)/g, '$163.0.3239.84 Edge/14.14393');`

**Comment by k0d3r1s** [comment]
@abmantis no messages for me, calls work

**Comment by abmantis** [comment]
> @abmantis no messages for me, calls work

I forgot to add "You have to *delete* and re-add the service inside Franz"

**Comment by k0d3r1s** [comment]
yeay :) it works :)

**Comment by iainb123** [comment]
I'm running Franz 5.1 on MacOS.  The recipe now lives in a different location (see https://github.com/meetfranz/plugins/blob/master/docs/integration.md) - the file is ~/Library/Application Support/Franz/recipes/msteams/index.js on MacOS.  I made the edit suggested by @abmantis and found that restarting Franz (no need to delete and re-add the services) worked - I'm now able to make video calls in MS Teams.
