### ISSUE TITLE
Not responding to mousewheel when moving around displays

### ISSUE THREAD

**Issue by chris579** [meetfranz/franz#1096]
### Expected Behavior
Every service reacts to the mouse wheel like normal.

### Current Behavior
When moving Franz from my main display (which is 4k res. with 200% scaling) to my full HD monitor without scaling some web services are not reacting to my mouse wheel any more. This especially includes Discord and WhatsApp.

When unplugging my main monitor this behaviour is not present any more. I'm quite sure this is because of the scaling and not because of the difference in resolution. When moving the window back to the scaled one the mouse wheel reacts again.

### Steps to Reproduce (for bugs)
1. Scale one monitor on 200%.
2. Add WhatsApp as a service and move Franz from the scaled monitor to the non scaled.
3. At least the active chat should not react to the mouse wheel any more.

### Context
Reloading the web service is enough to make it work again. 

### Your Environment
* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 1803
* Middle monitor: 3840 x 2160 200% scaling
* Right monitor: 1920 x 1080 100% scaling
* Left monitor: 1600 x 900 100% scaling

**Comment by chris579** [comment]
I noticed that the scrollable area is shifted to the left. If I scroll a bit more left than the visible scrollable area it’s working.

**Comment by arjel** [comment]
Same as @chris579 using 2 monitors main 1920x1080@125% and 1440x900@100%. I usually have Franz on the smaller display and scroll only works on the left side of the screen. The right-most 200px or so are not reactive to the mouse wheel.

**Comment by ShayMo1** [comment]
I'm also having this problem with the scroll area not being positioned correctly when the app is scaled. It works correctly at 100% but I'm on a laptop with 3200x1800 resolution and it's pretty much unusable with everything so tiny. The recommended scaling is 250%.
