### ISSUE TITLE
Message labels don't disappear on focus

### ISSUE THREAD

**Issue by mroeling** [meetfranz/franz#110]
### Expected Behavior
When there are unread messages, and you click on a conversation, the unread count badge should disappear automatically.

### Current Behavior
When there are unread messages, and you click on a conversation, the unread count badge remains visible. In Slack, only by clicking the blue bar with "number of new messages since" the counter is reset and disappears. 

### Your Environment
* Franz Version used: 5.0.0 Beta 11 (and in Beta 10 as well)
* Operating System and version: Kubuntu 17.10

**Comment by Wouter0100** [comment]
I guess this is specific to a recipe and not really related to Franz, if you'd ask me. This because the counter is simple still there and there are unread messages according to Slack.

**Comment by adlk** [comment]
@Wouter0100 indeed.
Slack has updated it's logic on when to remove the badge almost a year ago. I'm not really a fan of it but they might get the best overall experience of it. 

Happy to get a PR on www.github.com/meetfranz/recipe-slack if anyone wants to tackle this.

**Comment by adlk** [comment]
I'm closing this issue for now as this is nothing the client should handle.
