### ISSUE TITLE
Franz Suddenly stopped working

### ISSUE THREAD

**Issue by rajsharma1612** [meetfranz/franz#1100]
I can't log in. When I start Franz, it says unable to load

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/11499534/47540243-1da6af00-d90f-11e8-9c82-2149cd91732c.png)

Even if I'm able to use chrome and other browsers, Franz doesn't connect.
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by oceanstrang** [comment]
I had the same issue. Started maybe half an hour ago? I forget exactly what happened, but somewhere connection was lost, so I first rebooted, checked again, and deleted the app and supporting files and reinstalled. I get tossed back to the login / setup screen and it won't let me login.

**Comment by jjperezaguinaga** [comment]
Server is a bit overloaded atm. @adlk any way we can provide a bit of support there?

![image](https://user-images.githubusercontent.com/1128312/47540378-2c707000-d8d5-11e8-9d14-69b076c001e1.png)

**Comment by marceloau** [comment]
Error is also happening here with me.

**Comment by MarceloSaldias** [comment]
Same here :c

**Comment by ggalihpp** [comment]
+1

Same issue

**Comment by whitfin** [comment]
We're all going to have this issue if the backend is down, there's no need to report that we have the issue. I suggest we keep this thread quiet so we can all subscribe and when we see notifications we know it's something worth reading (i.e. it's fixed).

**Comment by nerd7473** [comment]
Same issue here...

**Comment by benwaffle** [comment]
Franz should cache the data locally. It's got all the cookies already...

**Comment by wongy91** [comment]
same here

**Comment by kmgalanakis** [comment]
Same here!

**Comment by DigitalSolutionsCZ** [comment]
Same here.

**Comment by Granvanoeli** [comment]
Same

**Comment by way2jatin** [comment]
Same here ..

**Comment by MagicLegend** [comment]
The creator is from Austria, and the day is just starting here on the EU continent. We'll probably need to give it some more time...

Looked around a bit, found that there are two ip's that resolve to `api.franzinfra.com`. They both however give the aforementioned 503. No use in forcing one or the other ip on Franz.

**Comment by MagicLegend** [comment]
And it just started working again for me... Let's hope it stays up :)

**Comment by johanvanhelden** [comment]
FYI: franz is working again!

**Comment by MagicLegend** [comment]
Would still love to hear from the developers why their server is needed for Franz to run. This issue seems really similar to #627. This question has been asked before in #1077, but was never answered. Any comment?

**Comment by jjperezaguinaga** [comment]
Would love to hear @adlk 's input, because I agree that there should be an alternative backup, either locally or online.

**Comment by adlk** [comment]
We had some issues with our database servers. Even though the server issues are resolved, having a local cache is definitely a good idea.
