### ISSUE TITLE
Franz development dead?

### ISSUE THREAD

**Issue by mrzapp** [meetfranz/franz#1105]
As far as I can tell, there has been limited feedback on issues for some time, and, as far as the Git history goes, no development either.

@adlk it's perfectly understandable if you're moving on to other things, but to be fair, donating money to you is beginning to make little sense if development is stagnant. That's not to say anything against your achievement of building the app so far, no one can take that from you.

Before everyone starts moving to Rambox, which is also nice, but lacks some polish, wouldn't it be time to start thinking about how to let the community maintain this project?

From my perspective, just 2 things need to be prepared:
- Removing the requirement of connecting to a remote "Franz service" entirely. User accounts will be local.
- Fixing the deprecation and dependency issues that we're seeing when building the package with yarn/npm, so it actually builds.

Is anyone else interested in this? I can also fork this repo and implement the needed changes, if this issue doesn't get any developer response.

**Comment by pieterdd** [comment]
+1 for a decentralized open source version of Franz that doesn't contain Google Analytics tracking.

**Comment by Gaboris** [comment]
Well the "official" statement is that @adlk got real sick and is unable to work on Franz.
IF this is true and that's the reason why we're stuck on Beta18 I can understand and wish a quick recovery to him, BUT I'm kinda worried that this project is LITERALLY has a "bus-factor" of 1 and absolutely no backup for "catastrophic" events like a server outage or just some client update breaking the whole system.
Heck, Discord's unread messages marker hasn't been working for me for months and it's either a client problem or currently Franz just accumulates problems as it goes on so it might need to be reinstalled every few months.

**Comment by mrzapp** [comment]
Ok, it seems that the entire app is wired into this service. It would take some pretty serious refactoring to decouple it, almost to the point that it'd be more sensible to redo this app from scratch.

Rambox it is, then.

**Comment by mrzapp** [comment]
@keunes I am looking into it right now. A big problem is that they are both electron apps with a ton of patch solutions, so it's a bit hard to just dive right in and maintain.

**Comment by mrzapp** [comment]
@matkatmusic @keunes I've started a new project using GTK and WebView instead of Electron. It can pretty much already do what Franz does, and it starts up a bit faster. There's still optimisation to be done though, as each WebView instance takes up significant RAM.

Project is here, if you're interested: https://gitlab.com/Putaitu/jagaimo

**Comment by Gaboris** [comment]
Seems like @adlk has made several merges from pull requests today.
Maybe we'll get an update at least with those at some point?

**Comment by mrzapp** [comment]
@matkatmusic @keunes @RajatArora08 @Gaboris Ok, nix that last project. I've created a WebExtension instead, as browsers already handle all of that memory management for you. Here it is for Firefox, let me know if you're interested in Chrome: https://addons.mozilla.org/en-US/firefox/addon/browser-chat/

**Comment by Gaboris** [comment]
Nice idea @mrzapp
Does it create a separate profile after it's installed and access it as a separate entity from within a browser or does it just modify the current one and run off of a tab?

Might try it out later, but gonna wait and see if Franz gets a nice update or not. :)

**Comment by mrzapp** [comment]
@Gaboris as for now, you'll have to create the separate profile manually. Than you can run the app like so: `firefox --no-remote --profile ~/.mozilla/firefox/chat`

Example .desktop file here:

```
[Desktop Entry]
Version=1.0
Name=Browser Chat
GenericName=Web based chat
Comment=Use Web services to chat
Exec=/usr/lib/firefox/firefox --no-remote --profile ~/.mozilla/firefox/chat
Icon=/usr/share/icons/browser-chat.svg
Terminal=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Categories=Network;WebBrowser;
Keywords=web;browser;internet;
Actions=new-window;new-private-window;
```

SVG icon is the [the repo](https://gitlab.com/mrzapp/browser-chat)

**Comment by Gaboris** [comment]
Thanks @mrzapp lucky I actually did stuff like this when I side-installed FF Quantum on my system and I'd say a "manual setup" is fine for an alpha. The question is if pure WebExtensions will allow automating it in any way?

Though I gotta ask before I try, will this completely disable other browser functionality like browsing, extensions, bookmarking and the likes even if just later on, or will it still work as normal just with some modifications that server the chats?

ALSO do you have any other places where we could keep track of development outside of GitLab since that one doesn't seem to have issues for a community to form like over here... Plus even if this is closed it shouldn't be discussed here.
