### ISSUE TITLE
Muted conversations getting added to the message count badge in Hangouts

### ISSUE THREAD

**Issue by vedantvohra1** [meetfranz/franz#1106]
### Expected Behavior
Muted conversations should not generate any kind of notification/badge

### Current Behavior
The message count gets updated whenever i receive a Hangouts message in a conversation which is actually muted. 

### Your Environment

* Franz Version used: 5.0.1-beta
* Operating System and version: Ubuntu 16.0.4 LTS

**Comment by closingin** [comment]
I just looked at the integration source code, it's a problem with the way it counts messages, the issue has to be opened [here](https://github.com/meetfranz/recipe-hangouts/issues) instead. I might look at it as it doesn't seem hard to fix.

Can you close this issue and open another one where I pointed you ? I'll investigate. Thanks !

**Comment by closingin** [comment]
Hello @adlk , could you please have alook at this issue and my associated PR ? I provided a fix for this bug a long time ago 😕
