### ISSUE TITLE
Feature Request: Webex Teams

### ISSUE THREAD

**Issue by ecoitsolutions** [meetfranz/franz#1109]
Any plans for supporting Webex Teams?
### Feature Description
Cisco Webex Teams (previously known as Cisco Spark) is a very popular and broadly used service among enterprise customers, are there any plans on supporting it? They provide complete Rest API and web browser chat support.

### Motivation and Context
I think it will be very nice to have for business customers

**Comment by riptide-dev** [comment]
@ecoitsolutions - Have you considered creating your plugin for it? You can find the documentation for creating your integration, here: https://github.com/meetfranz/plugins/tree/master/docs

**Comment by ecoitsolutions** [comment]
Yes, i might try just that but i wil definitely need some help with the notification API and specific payloads

**Comment by closingin** [comment]
Hello,

From the "New issue" template that you obviously didn't read : _This repository is only for the Franz client. Please use this form ( https://bitly.com/franz-service-request ) for service requests or check out the guide ( https://github.com/meetfranz/plugins ) to create your own service integration._

You can close your issue :slightly_smiling_face:

**Comment by MatthiasRoelandts** [comment]
https://github.com/meetfranz/plugins/issues/257
