### ISSUE TITLE
Missing translate label for hover on Settings

### ISSUE THREAD

**Issue by mroeling** [meetfranz/franz#111]
### Expected Behavior
Label should be translatable

### Current Behavior
After switching the language, the label still mentions "Settings (Ctrl+,)"

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/2706186/31989659-37d8d964-b973-11e7-8617-5d9e7f15c73b.png)

### Steps to Reproduce (for bugs)
1. Set the language to non-English
2. Hover the Settings icon in the bottom left corner

### Your Environment
* Franz Version used: 5.0.0Beta 11
* Operating System and version: Kubuntu 17.10

**Comment by DBozhinovski** [comment]
I'd like to give this a try :)

**Comment by phmigotto** [comment]
The same issue happens when you hover the "Add new service (Ctrl+N)" (right above Settings)

**Comment by DBozhinovski** [comment]
I don't see a translation for that particular string. I'll fix this, but new translation ids should be added too.

**Comment by DBozhinovski** [comment]
Should be good as of #141 :)

**Comment by adlk** [comment]
@DBozhinovski thanks for taking care of this.
