### ISSUE TITLE
Dark Mode in Linux

### ISSUE THREAD

**Issue by SoyDiego** [meetfranz/franz#1112]
Hi people, I read posts about get Franz in Dark Mode but nothing work in Manjaro Linux.
Someone can tell me how can I do? I hate the white background in Whatsapp/Messenger etc...

Thanks

**Comment by Gy0m** [comment]
I wait it too for ubuntu

**Comment by SoyDiego** [comment]
> I wait it too for ubuntu

I found a solution and I could put the dark theme in Whatsapp. 
But you have others dark themes here: [Dark Telegram](https://github.com/bloodf/franz-dark-telegram), [Dark Messenger](https://github.com/bloodf/franz-dark-messenger) or you can write your own CSS lines.

Here the steps:

1) Download Whatsapp [darkTheme.css](https://github.com/bloodf/franz-dark-whatsapp/blob/master/darkTheme.css) .
2) Found the folder **recipes**, In **Linux** you can find it here: 

> /home/yourUser/.config/Franz/recipes

In **Windows** you can find it here:

>%appdata%\Franz

3) Paste the file downloaded darkTheme.css inside the folder **Whatsapp**.
4) Open the file **webview.js** and replace the line this:

> Franz.injectCSS(path.join(__dirname, 'services.css'));

for this:

> Franz.injectCSS(path.join(__dirname, 'darkTheme.css'));

AND THAT'S ALL! :)

**OPTIONAL**
This theme haven't background dark in the section icons/gif/stickers.

![deepinscreenshot_seleccionar area_20181113194350](https://user-images.githubusercontent.com/19764334/48435424-c319a980-e77c-11e8-93f5-520f4130fb90.png)


so I add CSS lines to modify this background. If you want, **add this lines in darkTheme.css**:

```
._1vDUw._1UbeR, .l90LN.GclUX, ._2rR_l._29nQu, ._24k3z, ._1rADT, ._3Seam._2e6ev, ._1ifyO, ._1vDUw._33zGE {
    background-color: var(--dark) !important;
}
```

**FINAL RESULT**

![deepinscreenshot_seleccionar area_20181113194515](https://user-images.githubusercontent.com/19764334/48435451-d6c51000-e77c-11e8-84f8-cdbf8090bb2e.png)

**Comment by faqndo97** [comment]
@guillecura

**Comment by ThomasF34** [comment]
Is it working on Mac ? I've found that the equivalent of your recipes folder is `~/Library/Application Support/Franz/recipes/` but when i put the git's files under Whatsapp , Messenger or Telegram folder it doesn't work. Anyone with the same issue ?

**Comment by Gy0m** [comment]
I find this post : [https://github.com/meetfranz/franz/pull/362](url) where talking about dark mode of the right bar. A script with ctrl + alt + i and copy that script : 

`var cssStyle = document.createElement('style'); cssStyle.type = 'text/css'; var minCss = 'body{color:#d0d0d0}.badge{color:#000}#electron-app-title-bar,.list-item,.settings-navigation .settings-navigation__link,.toolbar-dropdown.open .button-component{color:#d3d3d3!important}#ReactVirtualized__Grid,#electron-app-title-bar,.list-item,.menu-pane,.settings .account .account__box,.settings-navigation,.settings__close,.settings__controls,.settings__header,.sidebar,.toolbar-dropdown.open .button-component{background:#222!important;box-shadow:1px 0 5px rgba(0,0,0,.38)!important}.settings__main{background:#333!important}.tab-item.is-active{border-left:4px solid rgba(255,255,255,.4);background:rgba(255,255,255,.15)}.service-table .service-table__row:hover,.settings .settings__close:hover,.settings-navigation .settings-navigation__link:hover{background:#000!important}', rules = document.createTextNode(minCss); cssStyle.appendChild(rules); document.getElementsByTagName("head")[0].appendChild(cssStyle);`

But it only last the time Franz is open, you need to redo the operation every times you open Franz.

**Comment by Gy0m** [comment]
not dark in page ...but less a dark left bar you  could expect

**Comment by adlk** [comment]
Dark Mode is part of beta 19 (currently not in official rollout).

To get your recipes ready for Dark Mode, check the docs here: https://github.com/meetfranz/plugins/blob/master/docs/integration.md#user-content-dark-mode

**Comment by Dimfred** [comment]
That is awsome thank you!
