### ISSUE TITLE
"Error: One of the params is missing or invalid" 

### ISSUE THREAD

**Issue by lionellloh** [meetfranz/franz#1121]
I was collaborating with my friends for a project and stupidly pasted a base64 string in the telegram group chat on Franz. 
It was too long, but there is no way I could edit it. An error dialog box pops up all the time, effectively disabling me from using the group chat anymore other than reading. 

### Expected Behavior

I should be able to delete the string even though it was very long. 

### Current Behavior

A pop up that says Error: One of the params is missing or invalid. 

I clicked `See technical details` and it showed:
```Method: messages.saveDraft
Result: {"_":"rpc_error","error_code":400,"error_message":"MESSAGE_TOO_LONG"}
```

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/29104062/48672489-803b4580-eb71-11e8-9c29-1671604945f7.png)

### Steps to Reproduce (for bugs)

1.  Paste a base64 encoding of an image. 
2. The chat should be jammed. 

### Context

I cannot reset it. I can no longer use the chat group in Telegram on Franz. 

### Your Environment

* Franz Version used: 5.0.0-beta.18.903
* Operating System and version:
macOS Mojave Version 10.14

**Comment by closingin** [comment]
Uh, Franz is meant to be a wrapper for applications, I don't think this has anything to do with this product, are you sure it's not on the side of Telegram directly ?

**Comment by adlk** [comment]
This needs to be reported here as Franz doesn't ship the services: https://github.com/zhukov/webogram
