### ISSUE TITLE
Franz support for Amazon Chime

### ISSUE THREAD

**Issue by bryanchen18** [meetfranz/franz#1122]
Amazon Chime web feature as service in Franz

**Comment by closingin** [comment]
Hello Bryan,

From the "New issue" template that you obviously didn't read : _This repository is only for the Franz client. Please use this form ( https://bitly.com/franz-service-request ) for service requests or check out the guide ( https://github.com/meetfranz/plugins ) to create your own service integration._

You can close your issue :slightly_smiling_face:
