### ISSUE TITLE
The "BACK" function is not working

### ISSUE THREAD

**Issue by kosokrychlov** [meetfranz/franz#1124]
### Expected Behavior
Go back one step by pressing the "ctrl + z" key on the keyboard, or selecting a function from the menu or clicking the mouse button for this feature.

### Current Behavior
When using the function, nothing happens.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/45166153/48700444-4f4c2680-ebec-11e8-8acb-a7191ed45eec.png)

### Context
In no service, you can not use the "back" and "forward".

### Your Environment
* Franz version:
![image](https://user-images.githubusercontent.com/45166153/48700808-3b54f480-ebed-11e8-904a-71cb794fec45.png)

* Operating System and version:
![image](https://user-images.githubusercontent.com/45166153/48700850-57589600-ebed-11e8-8edd-d20804bba702.png)

Thanks for the reaction / repair feature.

**Comment by closingin** [comment]
Hello,

What do you think the behavior for this action should be ? I don't know anywhere where this is currently used in the software. But when you ctrl+z in a service, the standard behavior is applied (example : delete some text, ctrl+z, and the text is back).

Maybe removing these two entries from the menus would be a good idea.

**Comment by kosokrychlov** [comment]
I apologize for your stupidity. I will point to the right.

"Edit"> "Back" works correctly. I thought the "back" and "forward" features I know from my browser. For example, in Gmail, I use "back" to return from an open email to my inbox.

**Comment by closingin** [comment]
Just so you know, when you're asking for help or comments, I don't think that insulting people who reply to you is very smart. :slightly_smiling_face: 

Your issue explains that the "back" function is not working, but there is no such thing as a back function, because the existing ones are "undo" and "redo", so it's unclear. If I understand correctly, what you want is to add a real back/forward behavior, similar to the one used in a web browser ?

**Comment by kosokrychlov** [comment]
Exactly.

For example, WhatsApp or Skype is a back/forward feature unnecessary. For services such as Gmail, the back/forward (mouse button) feature is a great help.

**Comment by adlk** [comment]
Back will be added to the context menu within a service!

> I apologize for your stupidity. I will point to the right.
@kosokrychlov please stay friendly. There is no reason to be like this.

**Comment by appel** [comment]
> Back will be added to the context menu within a service!

That is great news! Do you think it would be possible to attach the keyboard shortcut `Alt + back` to it?

**Comment by kosokrychlov** [comment]
> Back will be added to the context menu within a service!
> 
> > I apologize for your stupidity. I will point to the right.
> > @kosokrychlov please stay friendly. There is no reason to be like this.

I thought my stupidity ... I found out only now
@closingin I'm so sorry :-)
