### ISSUE TITLE
local server

### ISSUE THREAD

**Issue by beppe9000** [meetfranz/franz#1126]
I see we can use a [local server](https://github.com/meetfranz/franz/blob/e8d7e7c1044ae1c7680ab0c675c6004590ae0791/src/config.js#L7) for development/debug, but how can I run it? Is it in a separate repository?

**Comment by adlk** [comment]
The local server is only an option for the core team. For development purposes, please use the dev server.

**Comment by beppe9000** [comment]
.... right.
