### ISSUE TITLE
? > Support points to a 404 at https://meetfranz.com/support

### ISSUE THREAD

**Issue by appel** [meetfranz/franz#1128]
The `Support` option under the `?` menu opens the URL `https://meetfranz.com/support`, which gives a 404 status code.

### Expected Behavior
Either `https://meetfranz.com/support` should not give a 404, or the `Support` option under the `?` menu should open a different, valid URL.

### Current Behavior
It's dead, Jim.

### Possible Solution
Fix the link.

### Steps to Reproduce (for bugs)
1. Click on `?`
2.  Click on `Support`
3. Gasp at the 404.

### Your Environment
* Franz Version used: 5.0.0-beta.18, release 1.8.4 / win32 / x64
* Operating System and version: Windows 10 Pro 1803

**Comment by closingin** [comment]
Hello there,

Nice catch ! Maybe it would be better to point this link to the Slack workspace (as written in the support section of the README), or this URL might be a work in progress on the website side ?

I guess we need @adlk here.

**Comment by adlk** [comment]
Fixed :)
