### ISSUE TITLE
HipChat does not save the login credentials

### ISSUE THREAD

**Issue by rehoehle** [meetfranz/franz#113]
At the moment HipChat does not save my login. So if i close Franz and restart again i have to login again. It's a bit annoying to login every time. 

Version Franz 5 Beta 11

And i have set the marker for stay logged in.

**Comment by Wouter0100** [comment]
Same problem with Gitter.

**Comment by marcusboon** [comment]
Still not fixed in Franz 5 beta 14

**Comment by haraldox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HipChat session logout](https://trello.com/c/xhxYteyM/1-hipchat-session-logout)

**Comment by llovelock** [comment]
Can confirm this happens on my Franz (OSX 10.13) & my colleague's windows 10.

**Comment by ioannisjt** [comment]
I still get the issue in 5 beta 15 
I am using windows 10.

**Comment by bdhoine** [comment]
Any update on this one? Also having issues on version `(5.0.0-beta.15.607)` on macOS version `10.13.3 (17D47)`. My HipChat account is synced with the Atlassian account, maybe this is why it's working for some people?

**Comment by goldmantx** [comment]
Any updates on this, still getting the issue on Version 5.0.0-beta.17 (5.0.0-beta.17.834)?
Super annoying...

**Comment by dbogdanov** [comment]
Same issue here.

**Comment by ffont** [comment]
same here, this is really annoying...
