### ISSUE TITLE
Feature Request: Add a browser as service 

### ISSUE THREAD

**Issue by francwalter** [meetfranz/franz#1130]
Hallo

I just discovered Franz and am happy about it. Thanks a lot for it. I use it on my Mac OS 10.11.6

One thing I would love to have added: a service which is a simple browser, where I can open any page with the pages own cookies. So I could add there even any browser based messenger service as well.
I know that Franz is in his heart a browser anyway, so this would not be that difficult I guess?

I use Franz 5.0.0 Beta 18.903
Thanks.
frank

**Comment by closingin** [comment]
Hello Franc,

From the "New issue" template that you obviously didn't read : This repository is only for the Franz client. Please use this form ( https://bitly.com/franz-service-request ) for service requests or check out the guide ( https://github.com/meetfranz/plugins ) to create your own service integration.

Can you close your issue please ? :slightly_smiling_face:

**Comment by francwalter** [comment]
The Service Request Form does not help, there is only space for real services, like WhatsApp or sites like that, but not for a thing like I proposed.
But thanks for the link to create own service. I won't do it, but at least it is maybe possible to do :)

**Comment by closingin** [comment]
I'm not sure a web browser service would fit with the purpose of Franz (which is messaging) anyway, because this software is not meant to replace your preferred browser :slightly_smiling_face:

In case you want to do it yourself, I think that just adding service that loads your search engine will be enough ! Good luck !
