### ISSUE TITLE
Skype audio plugin not loading on Mac

### ISSUE THREAD

**Issue by thomasd3** [meetfranz/franz#1133]
When I try to do a skype call on the Mac, it tells me to install the plugin.
Even if the plugin has already been installed, it tells me to install it.

When I install it, it instantly succeeds (probably because it is already there).

Then the button to use it and place the call is not responsive.

**Comment by closingin** [comment]
I don't use Skype anymore, but as far as I know, Skype calls just don't work on Franz.

**Comment by thomasd3** [comment]
The plugin is behaving as if they do, but then nothing happens; there is no message, warning, etc

**Comment by Gektorian** [comment]
This ticket is duplicate of raised before #686. I would recommend close and merge it with #686.
