### ISSUE TITLE
Not possible to connect through a proxy anymore for Franz beta.19

### ISSUE THREAD

**Issue by cyChop** [meetfranz/franz#1145]
### Expected Behavior

After the beta.18 to beta.19 upgrade, Franz should start and services should be available.

### Current Behavior

Franz beta.19 starts. However, service tabs are blank.
When connecting to a proxy-free network and reloading all services (ctrl +  shift + R), services load fine.

### Steps to Reproduce (for bugs)

1. Connect on a corporate network.
2. Launch your Franz application.

### Context

I upgraded the solution and lost all access to functionality.
The fact that it worked was what made me choose (and recommend) Franz in the first place.
I don't know if it's a regression related to the new proxy settings (which would solve #919) or a choice to promote those.
Either way, it's a show-stopper.

### Your Environment

* Franz Version used: beta.19
* Operating System and version: Windows 10

**Comment by cyChop** [comment]
> I believe this is the same issue as #1142 . 

True, I forgot to mention this might be related. In my case, though, Franz starts and doesn't ask me to connect to Internet. Only services don't show.

(btw, #1142 reminds me very much of why I let Rambox go: unable to start behind a proxy, even in Pro mode)

**Comment by hknoener** [comment]
Same here, pretty bad problem.

**Comment by pvdochtend** [comment]
Indeed... Our company network uses proxy. Now this app is useless... please fix it...

**Comment by sathish804** [comment]
Me too having the same issue on beta19, anyone found any workaround?

**Comment by bentles** [comment]
same problem... how do i downgrade :'(

**Comment by mariachini** [comment]
> 
> 
> Me too having the same issue on beta19, anyone found any workaround?

You can try to use proxycap.

**Comment by dragn** [comment]
Downgrade to beta18 fixes the problem. Just uninstall, and install the older version, which you can find here: https://github.com/meetfranz/franz/releases/tag/v5.0.0-beta.18

**Comment by BoldlyGoingNoWhre** [comment]
While I can understand the rationale (somewhat) to have a premium feature to have per service proxy, but no proxy what so ever would render the free version totally useless.

**Comment by cpauls** [comment]
> Downgrade to beta18 fixes the problem. Just uninstall, and install the older version, which you can find here: https://github.com/meetfranz/franz/releases/tag/v5.0.0-beta.18

Ok. The beta18 works for me. 
@adlk Do you know what happend?

**Comment by adlk** [comment]
The "official" work around for this is currently to downgrade to beta 18. I've stopped the automatic rollout for b19. 

b19 is introducing the long promised proxy feature that however introduced this bug. This is _not_ the wanted behaviour and will be fixed!

**Comment by adlk** [comment]
So, there are two different issues related to proxies.

1. Franz can't connect at all
1. Franz can connect but services can't

I've created a test build for users that have the latter issue. You can download it here for [macOS](http://franz-travis.s3-eu-central-1.amazonaws.com/1012/Franz-5.0.0-beta.19-mac.zip), [windows](https://ci.appveyor.com/api/buildjobs/b0442o379swesjir/artifacts/out%2FFranz%20Setup%205.0.0-beta.19.exe) and linux ([deb](http://franz-travis.s3-eu-central-1.amazonaws.com/1012/franz_5.0.0-beta.19_amd64.deb)) ([tar.gz](http://franz-travis.s3-eu-central-1.amazonaws.com/999/franz-5.0.0-beta.19.tar.gz)) ([AppImage](http://franz-travis.s3-eu-central-1.amazonaws.com/1012/franz-5.0.0-beta.19-x86_64.AppImage))

Please understand that it is insanely hard to debug and test as no proxy setup is similar to the other and I can't take a peek into corporate environments.

I'm looking forward hear if this resolves the issues (at least for group 2)

**Comment by sathish804** [comment]
The test build fixed the issue for me on the Windows 10 Enterprise with Corporate proxy pac file. Thank you!!

**Comment by adlk** [comment]
@pvdochtend @sathish804 I assume both of you were of the second group?
> 2. Franz can connect but services can't

**Comment by adlk** [comment]
@VanniViolett @mikechernev I'm pulling you into this issue. Can you please check the versions from here:
https://github.com/meetfranz/franz/issues/1145#issuecomment-444095912

**Comment by pvdochtend** [comment]
> @pvdochtend @sathish804 I assume both of you were of the second group?
> 
> > 2. Franz can connect but services can't

@adlk Indeed.

**Comment by sathish804** [comment]
> @pvdochtend @sathish804 I assume both of you were of the second group?
> 
> > 1. Franz can connect but services can't

Yes correct, I am in the second Group. but I have a new scenario the services are not reachable on the Test version.

1) On Lan cable with proxy connected the Franz and all services.
2) When switched to wifi network with same proxy like lan the services were not reachable.
3) Only after restart of Franz all the services connected.

Can anyone test this scenario.

**Comment by jimivdw** [comment]
@adlk For me this new version fixes connecting to external services, but breaks the connection to our internally hosted Mattermost. The latter _did_ work in b19.

I tried it both with and without using the new proxy setting, but didn't work in either case.

**Comment by mikechernev** [comment]
The test build fixed it for me on MacOS 😊

**Comment by aksh98md** [comment]
> 2. Franz can connect but services can't

Test build fixes issue 2 for Windows 10 connecting to corporate network.

**Comment by adlk** [comment]
> Yes correct, I am in the second Group. but I have a new scenario the services are not reachable on the Test version.
> 
> On Lan cable with proxy connected the Franz and all services.
> When switched to wifi network with same proxy like lan the services were not reachable.
> Only after restart of Franz all the services connected.

@sathish804 only the services? Is it possible to e.g. search and add a new service?

**Comment by imingser** [comment]
The test build in Windows 10 works for me (I was in group 2). 👍

**Comment by sathish804** [comment]
> Overall, this is great news! Thanks so much for testing this update.
> 
> @jimivdw alright, let's get your issue resolved as well! I'll prepare another test build soon. Can you please send me an email to [stefan@adlk.io](mailto:stefan@adlk.io) with your contact details in case I have some questions for you?
> 
> Does it work in your Mattermost settings if you set the proxy host to `direct://`?
> 
> > Yes correct, I am in the second Group. but I have a new scenario the services are not reachable on the Test version.
> > On Lan cable with proxy connected the Franz and all services.
> > When switched to wifi network with same proxy like lan the services were not reachable.
> > Only after restart of Franz all the services connected.
> 
> @sathish804 When switching the network setup does this affect only the services? Is it possible to e.g. search and add a new service?

Hi, Good day!! I am able to add a new service but the existing service is not reachable.

**Comment by adlk** [comment]
I have created another test build that should automatically adopt the systems proxy preferences.
Please test the build from here: [macOS](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/Franz-5.0.0-beta.19-mac.zip), [Windows](https://ci.appveyor.com/api/buildjobs/3be28jmtaym9prt1/artifacts/out%2FFranz%20Setup%205.0.0-beta.19.exe), [AppImage](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/franz-5.0.0-beta.19-x86_64.AppImage), [.deb](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/franz_5.0.0-beta.19_amd64.deb), [.tar.gz](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/franz-5.0.0-beta.19.tar.gz)

Please check this build once more!

@jimivdw this should resolve your issue with Mattermost as well!

**Comment by jimivdw** [comment]
> I have created another test build that should automatically adopt the systems proxy preferences.
> Please test the build from here: [macOS](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/Franz-5.0.0-beta.19-mac.zip), [Windows](https://ci.appveyor.com/api/buildjobs/3be28jmtaym9prt1/artifacts/out%2FFranz%20Setup%205.0.0-beta.19.exe), [AppImage](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/franz-5.0.0-beta.19-x86_64.AppImage), [.deb](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/franz_5.0.0-beta.19_amd64.deb), [.tar.gz](http://franz-travis.s3-eu-central-1.amazonaws.com/1017/franz-5.0.0-beta.19.tar.gz)
> 
> @jimivdw this should resolve your issue with Mattermost as well!

It does, thanks!

**Comment by adlk** [comment]
I'm going to close this issue for now. Feel free to reopen it if the problem reappears.

**Comment by jaraudea** [comment]
this issue is happening me again in 5.0.1 version, I had to downgrade to 5.0.0 beta 22. in beta  23 the issue reappears.

**Comment by mikechernev** [comment]
Same thing here. When I downgrade I constantly get the notification for update and restart.
Running this on MacOS btw :)

**Comment by mikechernev** [comment]
@adlk can you check if the 5.1.0 version missed the fix for this issue?
