### ISSUE TITLE
Franz is slow in beta 19

### ISSUE THREAD

**Issue by MangoTwo2** [meetfranz/franz#1146]
After the update Franz is slow and unresponsive. I even get delays writing messages on whatsapp.

**Comment by Gaboris** [comment]
What system are you using and does it also "lag" with other clients as well?

I'm on a 64bit Win7 and can't see any problem with Skype, Messenger, IRCCloud or Discord.
Franz itself is just as fast as before and I did the update last night.

I'm just adding this here so it might help testing and not to say that you're wrong.

**Comment by MangoTwo2** [comment]
I am on Win10 (10.0.18290.1000) and just bringing up the Telegram or Whatsapp pages takes a few seconds to transition. Typing is also slow, there is a 1-2 second delay to every character I type.

**Comment by MangoTwo2** [comment]
Also the shortcut on the taskbar disappeared. So the app doesn't show as active. Even though when I press it it pops up.

**Comment by MangoTwo2** [comment]
![image](https://user-images.githubusercontent.com/7004862/49372703-d83e8400-f6fb-11e8-85d3-fab8514b3628.png)
No Franz Icon even though app is open

**Comment by adlk** [comment]
Please don't mix multiple issues in one. You can easily move the last two comments into a new issue. Thanks!

**Comment by SimoneGianni** [comment]
I'm on OSX (MacOs Sierra 10.12.6, macbook pro retina 15 mid-2014) and Whatsapp is making Franz (5.0.0-beta.19 (5.0.0-beta.19.1004) hang quite often, especially when there are images involved. It looks like the UI is still working (the loading spinner of the image keeps spinning), but it's completely unresponsive, cannot switch to other services nor interact in any other way.

It keeps like that for some 5 to 30 seconds, then the image spinner stops spinning and it gets back working. It does produce a CPU spike when it happens.

It happens almost 100% of time when I receive an image. Reloading the single service, or the entire app, doesn't help. Let me know if I can help debug the problem further.

**Comment by tjarkorikkerink** [comment]
Same here, Franz 5.0.0-beta20 is unbelievable slow, typing is with a delay, I'm on newest Chrome, Windows 7 64 bit system.

**Comment by Adioz01** [comment]
Same here ✌️

**Comment by luisguilhermemsalmeida** [comment]
I'm having freezing issues with Whatsapp, probably because of memory leak (windows 10 latest release)

**Comment by actuallymentor** [comment]
Having freezing issues on whatsapp. It unfreezes within 1-4 minutes. OSX Mojave.

**Comment by menthol** [comment]
Same here, look that is a picture issue, my whatsapp conversation with no images are responsive, and more images the conversation have, more irresponsive franz is.

**Comment by menthol** [comment]
The freezing have a strange behavior on MacOs Mojave.

When you have a freezing on full screen mode, you can access the menu to unfreeze the app.

**Comment by chrizmaster** [comment]
Same here with WhatsApp since updated to Mojave. Always freezing when trying to load pictures in the chat history...

**Comment by venanx** [comment]
Same problem with image loading.
Franz : Version 5.0.0-beta.22 (5.0.0-beta.22.1059)
Mac : Mojave 10.14.2

**Comment by dawidadach** [comment]
Same here, are you planning to do anything with that?

**Comment by SimoneGianni** [comment]
On OSX I noticed that clicking on the top screen menu, for example clicking "Franz" top left of the screen near the apple, un-freezes it when it's stuck on loading whatsapp images.

**Comment by bertolo1988** [comment]
Super slow here too. I am using 5.0.0-beta.19
Mojave: 10.14.2

**Comment by fhferreira** [comment]
+1

**Comment by timojuonoja** [comment]
I just downgraded to Franz 5.0.0-beta.18.
It tends to even start way faster than newer builds and is is "more rock solid".

**Comment by wloske** [comment]
Confirmed. Was using beta .22 and downgraded to beta .18 to remedy the enormous performance issues.

**Comment by psteinweber** [comment]
It seems that Whatsapp becomes particularly slow as soon as images are involved. Unfortunately it's not usable at the moment :(

**Comment by lolmaus** [comment]
I'm running a top spec PC running Windows 10 and experiencing WhatsApp being terribly slow.

It does not happen in the browser, nor does it happen in Franz on Linux.

**Comment by theelectricsoul** [comment]
Super laggy here. Annoying to use. 
Version: 5.0.0 (2019-02-15)

**Comment by theelectricsoul** [comment]
I've fallen back to .18. Runs smooth

**Comment by timojuonoja** [comment]
Yeah, seems like official 5.0.0 version is very unresponsive too. I will stick into beta.18 even though Slack is not liking it (will pop up, out-of-date messages very often).

I'm curious to know, that is someone investigating the problem at all? Few months already since this was reported?!

**Comment by Luxian** [comment]
I have the same issue since the last update. Running Linux here (but I don't think it makes a difference). The problem shows up for both Slack and Whatsapp

**Comment by theelectricsoul** [comment]
Nothing changed yet. Still horribly slow :/ Opening the webservices directly with Chrome and Firefox performs much better.

Tested: 5.1.0, R. 4.1.4

**Comment by Luxian** [comment]
Version 5.1.0 (Release 4.1.4 / linux / x64)  seems to work better so far (had it open for ~8 hours).

**Comment by BooVeMan** [comment]
I'm on MacOS 10.13.6 with Chrome 73 and Franz 5.1.0.1334 is especially slow on WhatsApp

**Comment by theelectricsoul** [comment]
I switched to Firefox and permanent tabs.

**Comment by keilabcs** [comment]
I'm on MacOS Sierra and I realize that when Franz Version 5.4.1 is turned on, my computer starts a heavy processing to the point that all other jobs are slow.

**Comment by keilabcs** [comment]
I'm on MacOS Sierra and I realize that when Franz Version 5.4.1 is turned on, my computer starts a heavy processing to the point that all other jobs are slow.

**Comment by wloske** [comment]
Hi @keilabcs ... I am running Version 5.5.0 an have no issues anymore.

**Comment by keilabcs** [comment]
@wloske So I will update, I use version 5.4.1.

**Comment by idankor** [comment]
MacBook Pro 2020 and latest OS to date., WhatsApp is really slow. I really wanted to, but I can't continue with Franz. It's a shame that it's a choice of slow speed vs high clutter, why can't we enjoy both?
