### ISSUE TITLE
Selection happens all the time when dragging

### ISSUE THREAD

**Issue by Gaboris** [meetfranz/franz#1147]
Since beta.19 Franz started to use selection no matter where I start dragging from and it messes with my scroll dragging while trying to navigate any of my clients.

Before the update selection only happened while left clicking on text(while the cursor is changed to a text input) and then dragging, but now if I click on any surface that's displaying actual text it starts selecting everything I pass.

As far as I know this is actually a default "bug/feature" of Chrome and the stuff that build upon its base, but I've seen some apps that got rid of it so if there were an option to either revert or disable this behavior I'd be really happy.

**Comment by adlk** [comment]
I'm having a hard time to reproduce this. Can you please provide more detailed instructions and services where it is especially easy to reproduce.

**Comment by Gaboris** [comment]
Well for me it's mainly a Discord problem, but my other clients with the exception of FB's Messenger like Skype and IRCCloud also produce it.

For example, I switch over to Discord, open up a channel, I hover over any parts of the window that has user made text(doesn't need to be above or even near text), hold down any of my mouse buttons and move it around.
Now it MIGHT be that this was the same behavior in previous versions for the mouse buttons which I just never experienced, but I'm sure that this wasn't happening for the scroll wheel since I use that for drag scrolling every day.

That is the only description I can give about it, but I'll try to make some screenshots while doing it if this is still not helping.
I don't know what causes this, but I know that Chrome and other Chromium based browsers work like that(main reason why I use FireFox), but if this is a local problem at least I'll know to look into it on my end.

**Comment by Gaboris** [comment]
OH! BTW it seems that either b.23 or b.24 have solved this problem so I'm gonna close it.
I guess it was the Electron upgrade. Thanks for that. :)
