### ISSUE TITLE
App stuck on startup

### ISSUE THREAD

**Issue by Cuddl3s** [meetfranz/franz#115]
### Expected Behavior

App starts up and lets me choose my services.

### Current Behavior

App is stuck loading (showing the spinner animation).

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/6339474/31998288-7dfafc08-b98f-11e7-83e1-39519caa1188.png)

### Possible Solution

-
### Steps to Reproduce (for bugs)

1. Start the app

### Context

I tried it on 2 different Windows 10 systems, both had a previous version of Franz installed. Upon it not starting I uninstalled all versions and did a clean install, but the issue persisted.

### Your Environment

* Franz Version used: 5.0.0-beta.11
* Operating System and version: Windows 10 Enterprise x64 Version 10.0.14393 Build 14393

**Comment by adlk** [comment]
Did you import mattermost or rocketchat when signing up for an account? If yes, try to restart. The issue should be fixed.

**Comment by Cuddl3s** [comment]
Yes, I imported mattermost! It works now, thanks!
