### ISSUE TITLE
Click on link should be settable to choose between open link on franz window or default browser window

### ISSUE THREAD

**Issue by SimonTod** [meetfranz/franz#1150]
At this point, when I click on a link inside a frianz recipe, it opens the target in a new small franz window.
There is the possibility to open the link in my own default browser if I right-click first, then select `Open Link`.
It would be nice to have a parameter to set the default behavior when opening a link. The user would choose between these two choices at least:
- Default behavior (small franz window)
- Open in default browser.

Those behaviors both already exist, it is just a matter of settings. So it shouldn't be to complicated (my guess).

Thanks

**Comment by Gaboris** [comment]
On my Win7 system clicking on any link opens it in my default FireFox browser in the case of Discord, IRCCloud, FB Messenger and probably also in Skype, but I wasn't able to test that.

What service are you using, with which browser and on what system?

**Comment by SimonTod** [comment]
Thanks for the reply.
I'm on Windows 10, I have tried this with Chrome and Brave (made on top of chromium).
I'm quite sure it happens with all the different services I'm using (Inbox, Office 365, Slack, Messenger and Whatsapp). It does not do that all the time though. Sometimes it opens the link on the default browser on its own.

**Comment by Gaboris** [comment]
Hmmm... Could be that Franz is sometimes confused as the default browser if the browser is Chromium based when it's being handled by the default "opening" code?
Interesting, guess we'll see what @adlk can say about it.

**Comment by SimonTod** [comment]
I'm on the 5.0.0-beta.18 version

**Comment by thefuzzyorange** [comment]
I concur this same behaviour occurs on the linux client.
I do think it is service related though. On my end, specifically for Outlook. 
When I click a link directly in an email a small franz window appears.
Right click open results in default browser launching.

Whatsapp / Slack / Microsoft Teams = default browser always

Franz Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

**Comment by cvaliente** [comment]
I am using Franz 5.0.1 Version 4.0.8/linux/x64 on fedora.
I have the same issue with the outlook 365 owa: links I click on are opened in a new window of what I assume is franz's web browser instead of my system's web browser (Chrome). I have to do right click -> open in browser to do that. Other services like slack or gmail correctly open links in the system browser by default. So it is a service specific issue.

**Comment by icheered** [comment]
After a recent update Franz started opening links in new Franz windows, as well as in an open browser.

OS: Linux (kernel 5.8.18-1)
Distro: MANJARO x86_64 20.2 Nibia
Franz version: 5.5.0
