### ISSUE TITLE
Services doesn't close when not used (which eat RAM)

### ISSUE THREAD

**Issue by QuantumSheep** [meetfranz/franz#1151]
**Description**
_This is a bug report AND a feature request._

When you add services, they never stop to work. Which means that 1 service will be constantly open in memory, whatever you does.

It could be fixed by closing the unused services webview after 5-10 minutes. Even if it takes a little starting time, it will be better than keeping them in background and letting them eat memory.

Another way to fix it could be to add a button that enable or disable background mode.

**To Reproduce**
Just add like ~6-7 services and you will notice that your RAM usage is huge (2Gb for 7 services).

**Screenshots**
6 services (Messenger, Discord, Telegram, Slack, Github and Outlook):
![image](https://user-images.githubusercontent.com/7271496/49506347-27142700-f87e-11e8-896f-fd3b8943d0aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - Version 1803 (17134.407)
 - Franz version: 5.0.0-beta.19

**Comment by adlk** [comment]
This was already discussed a few times. The issue with that is that services that are triggering notifications and notification badges won't work any longer – as the service is disabled.

At this point, I don't see a way to fix this.
