### ISSUE TITLE
WhatsApp: Safari - MacOS session from inside a Linux machine

### ISSUE THREAD

**Issue by marcob3t** [meetfranz/franz#1152]
**Describe the bug**
While checking active WhatsApp sessions from WhatsApp Android mobile app, the only active session shown was a Safari - MacOS session, while Franz was running on a Linux machine.

**To Reproduce**
Issue happened only once, logging in to WhatsApp service and looking for active sessions on the mobile.

**Expected behavior**
WhatsApp Web connected devices list should provide only a Linux x86_64 device, using Chrome browser.

**Screenshots**
Not applicable.

**Desktop:**
OS: Fedora 29 Linux x86_64.

**Additional context:**
Franz-5.0.0-beta.18 - AppImage version (franz-5.0.0-beta.18-x86_64.AppImage).

**Comment by adlk** [comment]
Technically it's not a bug 👼 
While debugging the WhatsApp issue (Chrome 36+ is required), we've tested if changing the user agent from chrome to e.g. safari does make a difference. While it initially looked like it did solve the issue, we now know it didn't. 
The WhatsApp mobile app just displays whatever the user agent was when the QR code was scanned.

**Comment by marcob3t** [comment]
Thanks :)
