### ISSUE TITLE
Spell check shows all words as incorrect (Mac 5.0.0-beta.20.1022)

### ISSUE THREAD

**Issue by ste7enm** [meetfranz/franz#1153]
**Describe the bug**

The spell check service (_alt: spellcheck_) shows all words spelled incorrectly since updating to 5.0.0-beta.20.1022 on Mac. Tested in Telegram and Slack, both yield the same results. Tried changing the language off of English and back, same issue.

![screen shot 2018-12-05 at 11 08 38 am](https://user-images.githubusercontent.com/9658882/49526898-c76a4b80-f87e-11e8-959e-133af21b2236.png)

**Expected behavior**

Spell check should only be flagging spelling mistakes.

**Desktop:**

 - OS: MacOS High Sierra 10.13.16
 - Version 5.0.0-beta.20.1022

**Comment by adlk** [comment]
In `~/Library/Application Support/Franz` do you have a folder called `dicts`? If not, please create one and restart Franz.

**Comment by ste7enm** [comment]
@adlk –

Yes, I do have a `dicts` folder already:

![screen shot 2018-12-05 at 1 23 37 pm](https://user-images.githubusercontent.com/9658882/49535293-ce4e8980-f891-11e8-9b26-d8d4abd7294f.png)

**Comment by adlk** [comment]
🤔 Interesting! 

I know that I'm asking you to restart the app quite often, but... What happens if you remove the `dicts` folder and start Franz again?

**Comment by adlk** [comment]
It seems like the dictionary download is failing on your machine. Let's find out why this happens!

1. Please open the dev tools <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>i</kbd>
1. Go to console and execute `localStorage.setItem('debug', 'Franz:DictionaryStore')`
1. Reload with <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>r</kbd>

It would be great if you can share the debug logs/error.

**Comment by ste7enm** [comment]
Here's the log, @adlk –

[Franz-1544048486030.log](https://github.com/meetfranz/franz/files/2650859/Franz-1544048486030.log)

**Comment by ste7enm** [comment]
@adlk –

This morning I started Franz before connecting to VPN and the dictionary download worked and spell check works. So it seems (maybe) that v19 introduced something different over v18 from a spell check perspective that doesn't play as well with the network's proxy or something.

I'll mark the issue as closed because it's more localized to my machine, but obviously your continued investigation is up to your discretion to prevent this one single feature jamming up on people in similar network configs.

Thank you for your efforts. 👍
