### ISSUE TITLE
Add option to hide notification badge

### ISSUE THREAD

**Issue by noirrak** [meetfranz/franz#116]
![43](https://user-images.githubusercontent.com/20505787/31998829-705614d2-b991-11e7-9231-d6fd3434579e.jpg)

* Franz Version used: 5.0.0-beta.11
* Operating System and version: macOS 10.12.6

**Comment by Wouter0100** [comment]
I guess this one should be posted [here](https://github.com/meetfranz/recipe-telegram) instead.

**Comment by adlk** [comment]
This was discussed quite a few times with the old versions. There were always two parties. One that wants the system notifications disabled but get the badge. And the other party that wants to disable both.

Maybe it would be fine to just add an option to "Show notification indicator" (or else). Let me think of that for a while as I don't want to run into an "Add service" screen with 300 different option toggles.

**Comment by willian** [comment]
Is there an update on this topic?
In my case, I have Gmail added with notifications disabled, but the badge with the number of unread messages are still there. I'd like to be able to toggle badges as we toggle notifications.

**Comment by haraldox** [comment]
this is implemented in Franz 5.0.0-beta.15 ... please update to the latest version!
