### ISSUE TITLE
Franz always starts up in silent mode

### ISSUE THREAD

**Issue by Gaboris** [meetfranz/franz#1161]
A few versions ago Franz started to always turn on in silent mode.

No matter if I turn it off or not after a restart it's always back to being silent by default.

**Comment by adlk** [comment]
Which OS do you use?
Is it possible that your systems DND mode is enabled?

**Comment by Gaboris** [comment]
Sorry, I was unable to edit my post after I made it.

I'm on a 64bit Hungarian Win7. It's up to date, but I actually don't know what DND mode is since I didn't change any of my settings when this happened.

**Comment by MartinDrenth** [comment]
I have (sort of) the same. Franz startsup minimized in the taskbar. If I try to open it Franz is not showing. Might be because I sometimes use two screens? I have tried everything to show Franz on my (only) screen. No succes

**Comment by adlk** [comment]
@Gaboris thanks for the info, I'll do some checks on Win 7

@MartinDrenth please open a new issue for that.
