### ISSUE TITLE
1Password Integration?

### ISSUE THREAD

**Issue by KyleAtDND** [meetfranz/franz#1163]
**Is your feature request related to a problem? Please describe.**
Some services (including custom recipe's I've made) by necessity require me to log in each time. This makes it just not worth it to use in Franz. However, a 1Password integration would make it worth me to use that service in Franz.

**Describe the solution you'd like**
A meaningful way to fill-in usernames and passwords with 1Password.

**Describe alternatives you've considered**
Copying and pasting, boo!

**Additional context**
I know 1Password requires a match on the code-signature, so you'd probably have to request them to add you, and they might now, but it would be amazing if it worked out.

**Comment by Gaboris** [comment]
Personally I use Bitwarden as a browser extension, but as I can see 1P also has that so maybe SOME Chrome extensions could be integrated or even have a fixed list of them and let people choose which ones they'd like to use?

This is a pretty neat idea actually. :)

**Comment by closingin** [comment]
Hello,

This repository is only for the Franz client. Please use [this form](https://bitly.com/franz-service-request) for service requests or check out [the guide](https://github.com/meetfranz/plugins) to create your own service integration. Anyway, 1Password doesn't fit with the purpose of Franz which is messaging.

Can you close your issue please ? :slightly_smiling_face:

**Comment by bvdlingen** [comment]
Bitwarden user here too, 

would be very usefull especially for my Office 365 account used for Microsoft teams

**Comment by sundbing** [comment]
1password has a chrome extension, so it would be very helpful to add it.

That way I would not have to reenter the full data for: 
Azure DevOps (as custom website at the moment),
Microsoft Teams (from several tenants),
Custom website for HR tool called rexx,
and a lot more.

**Comment by closingin** [comment]
Adding support for third-party extensions or integrations is not a simple feature, so I don't think you should expect to see it possible in a near future!
