### ISSUE TITLE
Gmail displays the draft count as the unread count when there are no unread messages

### ISSUE THREAD

**Issue by DanFMoore** [meetfranz/franz#1169]
### Expected Behaviour
If there are no unread messages, gmail should not display an unread count in the left sidebar or dock / taskbar icon, regardless of how many drafts I have.

### Current Behaviour
I have no unread emails in my inbox, but 4 drafts. It shows 4 for the unread count in the left sidebar and taskbar / dock icon.

### Screenshots (if appropriate):

<img width="344" alt="screen shot 2018-12-11 at 13 30 21" src="https://user-images.githubusercontent.com/837591/49803867-f97d2100-fd48-11e8-86cc-2ca27cb72533.png">

### Steps to Reproduce (for bugs)
1. Add gmail account to Franz
2. Login
3. Mark all inbox emails as read (or read them)
4. Click the "compose" button
5. Enter some text in the body of the new email
6. Don't send it but click the close button so that it goes into draft folder
7. The sidebar icon for gmail now shows up with "1" next to it as well as the taskbar / dock icon

### Your Environment
* Franz Version used: 
Version: 5.0.0-beta.19
Release: 2.0.13 / darwin / x64
* Operating System and version:
macOS High Sierra 10.13.6 (17G65)

**Comment by adlk** [comment]
Thanks for the heads up. I've deployed a patch to resolve this. Please go to settings and "check for updates".
