### ISSUE TITLE
Franz and services unstable pas week

### ISSUE THREAD

**Issue by s1h4d0w** [meetfranz/franz#1172]
**Describe the bug**
1. Franz said my services had been updated and I needed to reload, then Whatsapp said I needed "Chrome version X for Whatsapp web to work"
2. Later that went away, but Whatsapp now constantly says it's not connected to my phone, while my phone is working fine. Normally opening Whatsapp on my phone would fix it immediately but not when it breaks now
3. I've seen the "Your services have been updated" loads more times but haven't dared to click it again
4. Facebook Messenger logged me out, when trying to log back in I got sent to some Facebook error pages, then was logged out again and eventually managed to get it to work

**To Reproduce**
Pretty much explained above, no exact way to reproduce

**Expected behavior**
Whatsapp and Messenger working correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/5654654/49811438-91880400-fd63-11e8-85a8-964f7454b704.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 64bit
 - Browser: None, or Chromium? Whatever is built into Franz
 - Version: 5.0.0 Beta 19 // Release 2.0.13 - Win32 - 64bit

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 12.0.1
 - Browser: none

**Additional context**
These could be problems relating to the services themselves, but seeing as this seems to have started happening when I click the "Your services have been updates, reload" and the other weird problems I'm thinking it might be Franz related.

**Comment by miku86** [comment]
When you open Whatsapp in Franz, press `Cmd+Alt+i` or go to `View > Toggle Developer Tools` and go to the Tab `Console`.
Are there any messages, especially in _red_ color?

**Comment by s1h4d0w** [comment]
I'm at work currently and today everything seems to be working fine again. I did open up the console just to check and it has a lot of errors:

![image](https://user-images.githubusercontent.com/5654654/49857206-42d57b00-fdf2-11e8-9f59-3046a94ff1aa.png)

Log (phone number removed): 
[-1544604174188.log](https://github.com/meetfranz/franz/files/2671067/-1544604174188.log)

**Comment by adlk** [comment]
The issues you've mentioned are (un)fortunately not Franz related. We have some issues with WhatsApp right now that are however issues with WhatsApp directly. 

Clicking "Your services have been updated" is usually not the worst idea as it's actively fixing issues with services. But then again, there are issues with WhatsApp that aren't in our hands which is a bit like gambling.
