### ISSUE TITLE
WhatsApp not working on windows, need to update chrome

### ISSUE THREAD

**Issue by kachrahp** [meetfranz/franz#1173]
**Describe the bug**
Over 2 weeks or so I have been getting this messge on my windows 10 64 bit computer. I have the lastest franz up and chrome is up to date. I was getting same message on my macbook however after i guess a fix from franz (an update its working again) but yeh its annoying as hell. As my desktop is my main computer.

**To Reproduce**
Not sure how to reproduce as it been there for 2 weeks tried updating, reinstalling franz, And updateing chrome nothing is working.

1. Click WhatsApp tab 
2. See error

**Expected behavior**
I should be able to use whatsapp and see my message under the whatsapp tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/15350081/49825406-56310980-fd52-11e8-81ab-2229393262d1.png)

![image](https://user-images.githubusercontent.com/15350081/49825773-3a7a3300-fd53-11e8-81b1-08a82a726540.png)

**Desktop (please complete the following information):**
 - OS: windows 10 64bit
 - Browser chrome
 - Version Version 70.0.3538.110 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: oneplus 5
 - OS: oxygwnOs 5.1.7
 - Browser chrome
 - Version 

**Additional context**

**Comment by LionelBino** [comment]
I have the same problem in Linux version.

**Comment by closingin** [comment]
You gotta be kidding us. Can't you search before opening a new issue ? #1115 and #1138 already talk about this problem, and there's even an announcement on the [website](https://meetfranz.com/support/).

Can you close this please ?

**Comment by adlk** [comment]
Locking in favor of #1185
