### ISSUE TITLE
KeeWeb service integration

### ISSUE THREAD

**Issue by vallahaye** [meetfranz/franz#1174]
Hello!

### Feature Description
I've just finished integrating KeeWeb into Franz and I taught it would be great if it could be added as an official service. Here is the link to my repository: https://github.com/vallahaye/franz-recipe-keeweb
I'm currently using the badge API to indicate when the password database is out of sync.

### Motivation and Context
KeeWeb is a free cross-platform password manager compatible with KeePass that I use a lot in my everyday life either at home or at work. More info at: https://keeweb.info

Thank you :)

**Comment by closingin** [comment]
Hello @vallahaye, thanks for your work ! But even though it works like those, Franz is not meant to replace your web browser, it's a messaging software... I don't think your service will be deployed for this reason, but anyway you're not supposed to ask here for this.

Can you close your issue and open a new one following [this documentation](https://github.com/meetfranz/plugins/blob/master/docs/integration.md#deployment) please ? :slightly_smiling_face:

**Comment by vallahaye** [comment]
@closingin Oh I see, I'll re-open my issue in the right place then. Regarding the role of Franz, I'm using KeeWeb to store the passwords that I use for my messaging services so I guess it kinda makes sense to have it directly inside Franz. But anyway, we'll see :)

Thanks for your reply!
