### ISSUE TITLE
Spell checker in beta 21 is not working

### ISSUE THREAD

**Issue by appel** [meetfranz/franz#1178]
It appears the spell checker in the new beta (21) is not working. Even though the language is set to English, every word is underlined. I tried switching to a different language and back and I tried restarting Franz, but to no avail.

Running Windows 10 build 1803. Tried uninstalling Franz, rebooting Windows and reinstalling Franz, but no dice, unfortunately.

**Comment by Gaboris** [comment]
Same here. Both English and Hungarian is broken.

The Dictionaries folder is within Franz's folder and it's also populated with 9 languages(out of which 7 has never been used before). Maybe I'll try quitting Franz, deleting the language files and restarting so it can maybe recreate them? We'll see later.

**Comment by ccioanca** [comment]
+1 here. English just underlines every word. No other languages seem to work. Tested at random with Google Translate.

**Comment by modivin** [comment]
Verifying this for greek as well.

**Comment by adlk** [comment]
Ok this is weird!

**As a general info:** dictionaries are no longer dynamically downloaded. Instead they are shipped with the app – for proxy reasons. 

I've stopped the windows rollout until this is further investigated! Thanks for letting me know.

**Comment by Gaboris** [comment]
Okay in that case I won't delete my dictionaries. Maybe a clean reinstall of Franz? We'll see...

**Comment by ccioanca** [comment]
Looks like that fixed English. 

The lazy developer in me says that I don't need to test any other languages and that they're probably all fixed.

**Comment by appel** [comment]
@adlk I can confirm it works for both Dutch and English. Thanks for the speedy fix!

**Comment by modivin** [comment]
I'm afraid something is wrong with my installation.
 
I uninstalled and made a clean install. There is no dicts folder and I'm having trouble changing languages either from Settings or by right clicking.

**Comment by modivin** [comment]
English seems to work fine. Greek not so much. Every word is underlined and there are no suggestions available.

Also you are missing an E in front of "λληνικά (Greek)". It should be "Ελληνικά (Greek)". Nothing critical but well, since I'm here :)

**Comment by adlk** [comment]
@modivin Thanks for the report! Can you please open a separate issue for spell checking?

**Comment by modivin** [comment]
Sure thing

**Comment by adlk** [comment]
Closing this as it's fixed in d5dadc116d18c49cb78da7d892c95b0c34df2c96 and will be released in the next couple of hours.

Thanks for your support! ❤️

**Comment by Gaboris** [comment]
THANK YOU! THIS is what I've been waiting for the most after dark mode. :)
