### ISSUE TITLE
(Feature request] Jira & Confluence integration (Atlassian)

### ISSUE THREAD

**Issue by jordyvdboom** [meetfranz/franz#1182]
### Feature Description
Currently we have an integrated option for Hipchat, made by Atlassian. For larger product teams like I'm in, it should be very handy to have Jira and Confluence as integrated apps within Franz.

### Motivation and Context
* It improves the Franz experience bu adding another feature that is heavily used in the product development landscape.
* The only 2 apps that I use outside Franz are Jira and Confluence.

### Mockups, Screenshots (if available):
* https://atlassian.com/software/jira
* https://www.atlassian.com/software/confluence

**Comment by adlk** [comment]
Those are non-standard Franz services. For now, we won't officially support those. 

You can however look for 3rd party recipes:
https://github.com/meetfranz/plugins/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+jira

Also

**Comment by ThatGuyinIT** [comment]
Confluence cloud
https://github.com/ThatGuyinIT/recipe-franz-confluence

Jira cloud
https://github.com/ThatGuyinIT/recipe-franz-jira
