### ISSUE TITLE
Enable kerberos authentication

### ISSUE THREAD

**Issue by aiguofer** [meetfranz/franz#1193]
I have a corporate Google Chat account which can use Kerberos to authenticate. If I use my browser it can detect my kerb ticket and log me in. It'd be nice if I could do the same in franz.

**Comment by closingin** [comment]
Not really the same, but it's related to #1163 ! It's about adding a way to provide integration for third-party software. That is a huge feature I think, but I don't know if it's on the roadmap. @adlk might help you there.
