### ISSUE TITLE
New Service Integration - Feeldy RSS Reader

### ISSUE THREAD

**Issue by wetterSpitze** [meetfranz/franz#1196]
##  [Feedly](https://feedly.com/i/welcome) Integration
Hi guys, first of all props for your development of this awesome project :+1: . Ive been using Franz since the early days and i am very happy for such a nice application!

After quite some time i spend in searching for a desktop rss-feed application to read some news, i havent found any suitable project. BUT today Franz came in my mind. Since i like to read my news at [Feedly](https://feedly.com/i/welcome) i want to ask if you guys want to integrate that as a new service in Franz? That would be very awesome :call_me_hand: :+1: !!

**Comment by closingin** [comment]
Hello,

This repository is only for the Franz client. Please use [this form](https://bitly.com/franz-service-request) for service requests or check out [the guide](https://github.com/meetfranz/plugins) to create your own service integration.

By the way, Franz is a software for messaging, so I don't think this integration would fit, but thanks for the kind message !

Can you close your issue please ? :slightly_smiling_face:
