### ISSUE TITLE
Twitter DM images cropped

### ISSUE THREAD

**Issue by tjebb** [meetfranz/franz#1199]
Using the Twitter DM service, images sent are 'zoomed in' so images that are wider than high only show the middle part. 

When clicking on a preview, this does not show the full image scaled with the normal aspect ratio, but cropped. This behavior does not occur in normal Safari or Chrome.

### Your Environment
* Franz Version used: 5.0.0-beta.22.1059
* Operating System and version: macOS Mojave 10.14.2 (18C54)

**Comment by closingin** [comment]
Hello,

Could you please provide more information ? At least a screenshot showing the difference would help.

Thanks.
