### ISSUE TITLE
Telegram Messanger in mobile view

### ISSUE THREAD

**Issue by maikischa** [meetfranz/franz#12]
If you use the telegram messenger in mobile view the visualization is broken (see screenshot). In desktops mode everything is perfect.

<img width="462" alt="franz" src="https://user-images.githubusercontent.com/6735769/31707463-b3c526a4-b3ec-11e7-8e3d-7464791049a4.png">

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
[https://github.com/meetfranz/recipe-telegram]
