### ISSUE TITLE
Dropping a file on Whatsapp fails. 

### ISSUE THREAD

**Issue by duarteocarmo** [meetfranz/franz#120]

**Comment by adlk** [comment]
Please use the issue template to describe your problem with all the necessary information. 
https://raw.githubusercontent.com/meetfranz/franz/master/.github/ISSUE_TEMPLATE.md

**Comment by duarteocarmo** [comment]
I didn’t feel like it. Sorr

_____________
Duarte O.Carmo
<https://www.linkedin.com/in/duarteocarmo/>

On 25 October 2017 at 16:14:23, Stefan Malzner (notifications@github.com)
wrote:

Please use the issue template to describe your problem with all the
necessary information.
https://raw.githubusercontent.com/meetfranz/franz/master/.github/ISSUE_TEMPLATE.md

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meetfranz/franz/issues/120#issuecomment-339343876>, or mute
the thread

**Comment by adlk** [comment]
Unfortunately this helps no one.

**Comment by duarteocarmo** [comment]
No worries. Keep up the good work.

Cheers.

_____________
Duarte O.Carmo
<https://www.linkedin.com/in/duarteocarmo/>

On 25 October 2017 at 16:16:55, Stefan Malzner (notifications@github.com)
wrote:

Unfortunately this helps no one.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meetfranz/franz/issues/120#issuecomment-339344759>, or mute
the thread
