### ISSUE TITLE
Can you add Asana

### ISSUE THREAD

**Issue by Caine-Boelhouwer** [meetfranz/franz#1200]
Can you add the service Asana to Franz 5. 

https://asana.com/

**Comment by closingin** [comment]
Hello,

This repository is only for the Franz client. Please use [this form](https://bitly.com/franz-service-request) for service requests or check out [the guide](https://github.com/meetfranz/plugins) to create your own service integration.

By the way, Franz is a software for messaging, so I don't think this integration would fit. Still, that doesn't prevent you from being polite.

Can you close your issue please ? :slightly_smiling_face:

**Comment by adlk** [comment]
Also, there is already a 3rd party plugin available.
