### ISSUE TITLE
Franz Window takes up full screen (hiding taskbar) and won't allow itself to be moved [windows 10]

### ISSUE THREAD

**Issue by goleary** [meetfranz/franz#1207]
**Describe the bug**
When I start Franz it opens in one of my 3 monitors in fullscreen, not as a window.  This fullscreen state hides the taskbar at the bottom of the screen, and doesn't not allow itself to be moved or minimized. I can only view my taskbar by hitting the windows key.  I'm not able to move the app to another window.

I can't even use the windows key + arrow to move the app like I can with other apps/windows.

**To Reproduce**
1. open app
2. it takes up fullscreen and cannot be moved.

**Expected behavior**
Franz should not cover up the taskbar and should allow itself to be moved to another screen and minimized.

**Screenshots**
this screenshot shows franz taking up the whole of one display while the taskbar is visible on the display to the right.
![image](https://user-images.githubusercontent.com/16123225/50659564-de6d8d80-0f51-11e9-8558-9ca34e5440f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise version 1809
 - Browser irrelevant...
 - I have 3 monitors

**Additional context**

**Comment by closingin** [comment]
I don't have problems with two monitors running on Arch Linux, has to be investigated I guess.

Just in case, are you sure it's not a scaling problem with your GPU ? Or a setting that would set your window to full screen automatically ? I assume it only occurs with Franz.

**Comment by goleary** [comment]
I've never experienced with any other application.  I also do not experience the issue on my laptop, so it very well may have something to do with the multiple displays (on windows 10).

**Comment by closingin** [comment]
I have a virtual machine set up, I'll try to reproduce this behavior and will come back to you asap.

**Comment by closingin** [comment]
Hello @goleary, I failed at reproducing the bug you describe, here's what I tried so far:

- Opening the window on the primary screen, quit the program
- Opening the window on the secondary screen, quit the program
- Opening the window maximized on the primary screen, quit the program
- Opening the window maximized on the secondary screen, quit the program

Every time it worked well without going full screen, so I think it's a problem on your side. Have you tried resetting the window size/location cache using a tool like CCleaner ? Maybe it can help.

**Comment by DanielFNG** [comment]
This was happening for me as well. In the AppData/Roaming/Franz folder I checked the window_state.json file and "isFullScreen" was set to true. I closed Franz, changed this to false, reloaded and it was fixed. I was then able to move the window around & maximise it while still seeing toolbars. 

Previously there was no way to get out of full screen from the app itself that I could see.

**Comment by okko7** [comment]
Simply hitting "F11" also does the trick. 

Source: https://github.com/meetfranz/franz/issues/825

**Comment by ThatGuyinIT** [comment]
+1

I also had this problem and F11 was the fix.
