### ISSUE TITLE
Can't log in to company's microsoft accounts, stuck on sign in screen

### ISSUE THREAD

**Issue by mearleycf** [meetfranz/franz#1213]
I'm attempting to sign into my company's outlook and teams accounts. I have been able to successfully sign in to my client's outlook and team accounts, but not my own company's microsoft accounts. 

**To Reproduce**
1. Add a new microsoft service (teams or outlook for me)
2. Enter company email address
3. System hangs

**Expected behavior**
App redirects me to company sign in page, and I sign in after 2fa. 

**Screenshots**
<img width="932" alt="franz" src="https://user-images.githubusercontent.com/1252826/50838377-e2235a80-132b-11e9-8f83-63e9b688740d.png">

**Desktop (please complete the following information):**
 - Device: Macbook Pro (most recent version)
 - OS: OSX 10.14.2 Mojave
 - Browser ? Chrome is default browser
 - Version of Franz: 5.0.0-beta.22.1059

**Comment by nortimer** [comment]
same environment, same problem. The login to the company's Teams hangs on the "taking you to your organization's sign in page" indefinitely.
<img width="1659" alt="screenshot 2019-01-10 at 16 30 33" src="https://user-images.githubusercontent.com/741398/50978603-139b5200-14f5-11e9-8528-e99669f0855d.png">

**Comment by nortimer** [comment]
bump. any progress on this? Can we help with the troubleshooting somehow?

**Comment by klonos** [comment]
Not sure if this is the same as the problem I am facing when logging in to TEAMS...

1. I type my username -> I get asked to select between work/school account or personal account:

![screen shot 2019-02-04 at 9 28 32 am](https://user-images.githubusercontent.com/2423362/52183755-5edc2280-285f-11e9-9fb0-f8e9d2e1f2f7.png)

2. I select work as per usual -> get asked to enter my password to sign in -> error:

![screen shot 2019-02-04 at 9 25 15 am](https://user-images.githubusercontent.com/2423362/52183789-acf12600-285f-11e9-8475-15ba7e95ed3b.png)

This has worked in the past, but for some time now doesn't (it happened randomly; not after an update). Upgrading to the latest betas (22, 23, 24) does not fix the issue.

PS: I can log in to TEAMS fine via my browser following the same process. Could this be a cookie issue? Does Franz store cookies, and if so, where (on Mac)?

**Comment by archang3l-media** [comment]
> I'm attempting to sign into my company's outlook and teams accounts. I have been able to successfully sign in to my client's outlook and team accounts, but not my own company's microsoft accounts.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Add a new microsoft service (teams or outlook for me)
> 2. Enter company email address
> 3. System hangs
> 
> **Expected behavior**
> App redirects me to company sign in page, and I sign in after 2fa.
> 
> **Screenshots**
> <img alt="franz" width="932" src="https://user-images.githubusercontent.com/1252826/50838377-e2235a80-132b-11e9-8f83-63e9b688740d.png">
> 
> **Desktop (please complete the following information):**
> 
> * Device: Macbook Pro (most recent version)
> * OS: OSX 10.14.2 Mojave
> * Browser ? Chrome is default browser
> * Version of Franz: 5.0.0-beta.22.1059

I can confirm this bug on windows. Earlier this year everything worked fine on OSX though.

**Comment by sebastiennoir** [comment]
Same problem for me :

- Latest version of Franz (5.0.0.1136)
- Mac OS 10.14.2

Any solution?

**Comment by maroleks** [comment]
+1 for this issue. please, solve it

**Comment by igoroctaviano** [comment]
Same problem for me:
- Latest version of Franz (5.0.1)
- Mac OS 10.14.4

**Comment by rbpisupati** [comment]
Same problem for me.. company login redirecting to another login page is struck.

- Latest version of Franz (5.0.1)
- Linux OS (Ubuntu)

**Comment by Mattee** [comment]
Same problem for me:
- Latest version of Franz (5.1.0)
- macOS High Sierra

**Comment by arnigunnar** [comment]
Same here
- 5.2.0-beta2
- Windows 10

**Comment by cchlanger** [comment]
Same here stuck on:
Taking you to your organization's sign-in page

- Ubuntu 18.04.2 LTS
- Version: 5.1.0
- Release: 4.1.4/linux/x64

**Comment by cchlanger** [comment]
> Same here stuck on:
> Taking you to your organization's sign-in page
> 
> * Ubuntu 18.04.2 LTS
> * Version: 5.1.0
> * Release: 4.1.4/linux/x64

I just realized after reading following Issue:
https://github.com/meetfranz/franz/issues/790#issuecomment-448661864
It only happens when I try to login from the company network. Seems an issue how it handles the Identity token.

For everybody else try to use a non company network, for example your phones wifi hotspot during login.

**Comment by spidie** [comment]
Same problem here - was facing another issue so I cleared my cache and reinstalled - now I am stuck at the same screen as the rest of you. Running teams_1.3.00.5153_amd64 on Ubuntu 18.04
