### ISSUE TITLE
Notifications - Show the icon of the service

### ISSUE THREAD

**Issue by UtechtDustin** [meetfranz/franz#1214]
**Is your feature request related to a problem? Please describe.**
Its not really a problem... its a feature request..
Currently the notifications shows the franz logo for me.

**Describe the solution you'd like**
Show the icon of the service which had the notification, e.g. if i get a message on whatsapp the icon should be the whatsapp logo (currently its the franz logo).

**Comment by rickytribbia** [comment]
I think it's a great feature. Plan this, please
