### ISSUE TITLE
GMail badge shows wrong number of new messages

### ISSUE THREAD

**Issue by LordNacho** [meetfranz/franz#1215]
<img width="61" alt="screenshot 2019-01-09 at 13 20 37" src="https://user-images.githubusercontent.com/1208668/50914039-9eb11500-142d-11e9-9dd1-7594f74deb50.png">

Recently whenever I get a new mail the badge shows thousands instead of 1. It seems to be the total number of emails in that inbox, but I'm not sure.

**To Reproduce**
Send yourself an email. See the badge appear with the wrong number.

**Expected behavior**
Badge shows 1

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Browser Chrome 71.0.3578.98

**Comment by nilsringersma** [comment]
The same issue has been happening for me over the last 2-3 weeks. Both on MacOS and Windows 10. Browser, Versie 71.0.3578.98 (Official build) (64-bits)

**Comment by mattmorgante** [comment]
I am having the same issue and would love for this to be resolved

**Comment by D4N3-777** [comment]
Somebody already made a PR that would fix this issue in the respective Gmail repo: [PR](https://github.com/meetfranz/recipe-gmail/pull/9)

**Comment by ulentini** [comment]
Hello, is there any idea on when this could be merged?

**Comment by plezervi** [comment]
+1

**Comment by ulentini** [comment]
This is still not working.

**Comment by aarondfrancis** [comment]
Would love to see this fixed!
