### ISSUE TITLE
[Feature Request] Search the Page Contents

### ISSUE THREAD

**Issue by KyleAtDND** [meetfranz/franz#1216]
**Is your feature request related to a problem? Please describe.**
Sometimes, I need to search the page and/or message stream that I’m on. Not using the websites, search, but searching the actual text on the page.

**Describe the solution you'd like**
A similar, but different function to Chrome so that I can do ⌘F and a search-box will pop-up. Then when I start typing, it'll start searching. Hitting "enter" to jump through entries.

**Comment by SpectralKH** [comment]
+1 This has been annoying me for a long time

**Comment by dbogdanov** [comment]
This will be very useful for some of the plugins, for example Evernote (https://github.com/iamcxa/franz-recipe-evernote/issues/1).

**Comment by izll** [comment]
+1

**Comment by gservat** [comment]
Duplicate of #193?
