### ISSUE TITLE
Just summon Franz from the MacOS menu icon, don't allow to close

### ISSUE THREAD

**Issue by LordNacho** [meetfranz/franz#1217]
At the moment there's a red dot when there's a message. If you click it you get a menu to either show Franz or close it.

It's quite easy to accidentally close it.

I would just remove the menu and have the icon focus the window. People can close it from the menu if they want, most of the time by far they want to see the window.

**Comment by closingin** [comment]
Duplicate of #1179 I think

**Comment by LordNacho** [comment]
Not sure it's a dupe. I just want to be able to click the menubar icon and get the existing window, instead of getting a menu where I have to click one more time, or accidentally close it.

**Comment by closingin** [comment]
Yes I understood, but I think that the implementation for these two things might be the same. It has to be investigated, but I agree with you, it could be nice to have.
