### ISSUE TITLE
Switch between messaging services with control/command + arrow keys

### ISSUE THREAD

**Issue by alexstoken** [meetfranz/franz#1219]
Just began using Franz today and love it. I plan on sharing it will all my colleagues and friends. However, switching between services is difficult using the [Command + #] keyboard shortcuts (small fingers and keyboard layout are getting in my way!). It would be great to cycle through active messaging services with [Command + left/right/up/down arrow keys] instead. Thanks for considering this request!

**Comment by pvdissel** [comment]
In the 5 beta, ctrl+tab worked... but just upgraded off the beta to 5.3.3 on linux and noticed ctrl+tab doesn't work anymore :sob: 
Can't find an overview of shortcuts to tell the new key combo (expecting there atleast be a new combo :D )
