### ISSUE TITLE
Add LINE support

### ISSUE THREAD

**Issue by picsi** [meetfranz/franz#122]
LINE is by far the most popular messaging app in Japan: http://line.me/en/

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by yuriality** [comment]
Just FYI
The link on this page https://meetfranz.com/support/ under Request a Service doesn't seem to be working. Doesn't jump to that form.

**Comment by adlk** [comment]
Ah thanks for the hint. I'm just replacing typeform with google forms.
