### ISSUE TITLE
Facebook Messenger no longer working

### ISSUE THREAD

**Issue by wsfuller** [meetfranz/franz#1220]
**Describe the bug**
Trying to load Facebook Messenger and only getting a white screen

**To Reproduce**
1. Install Service
2. Login 
3. White Screen

**Expected behavior**
Would like to see the Messenger portal

**Screenshots**
<img width="1282" alt="screen shot 2019-01-14 at 6 27 31 am" src="https://user-images.githubusercontent.com/3144419/51118484-585d0c80-17c5-11e9-9f7b-5d9ff30de896.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 10.14.2
- Franz Version: Version 5.0.0-beta.18 (5.0.0-beta.18.903)

**Additional context**
Has been working fine for years. I've since try restarting the service, deleting the service, restarting the computer. Seems like an integration is broken somewhere

**Comment by Sudiukil** [comment]
Have the exact same issue. Tried to restart and delete the service, tried to clear Franz cache, nothing worked.

*Environment*
- OS: Linux and Windows
- Version: Debian 9, Windows 10 (1809, build 17763.195)
- Franz version: 5.0.0-beta.22

**Comment by lauro365** [comment]
same behavior here, but i also found that messenger itself is the one not working after some digging, so its probably not a franz-side problem/bug

**Comment by PlaceboPRS** [comment]
> 
> 
> same behavior here, but i also found that messenger itself is the one not working after some digging, so its probably not a franz-side problem/bug

Not sure what you mean Messenger is working fine in Waterfox for me but not Franz?

**Comment by mrtonks** [comment]
I just got the same problem. Tried deleting the service, adding it back and restarting Franz. It only shows a blank screen. Everything else works fine.

**Comment by PlaceboPRS** [comment]
Yep working here.

**Comment by closingin** [comment]
Hello @wsfuller,

The problem wasn't related to Franz, can you close your issue please ? :slightly_smiling_face:

**Comment by mentarus** [comment]
Same problem here, definitely not fixed as of 10.0.18362

**Comment by Cassiopeia-the-Elf** [comment]
Not sure why issue was closed, as this problem still persists :( Messenger.com IS working, so that is not the reason.

**Comment by KYoungLR** [comment]
Any update on this? Have been experiencing this for weeks, tried uninstalling Franz, deleting/readding messenger app, and updating to latest version but still having same issue.
