### ISSUE TITLE
Window won't open after it has been closed

### ISSUE THREAD

**Issue by soutone** [meetfranz/franz#1221]
Using elementary OS 5.0 Juno, the Franz app won't open from the Dock or the App Launcher after being previously closed. It only opens again after being killed via the Terminal or the System Monitor.

To reproduce this behavior just open the app on a computer running elementary OS 5.0 Juno, close it and then try to open it again.

 - OS: elementary OS 5.0 Juno x86_64
 - App Version: 5.0.0-beta.22

**Comment by nraiha** [comment]
Same happens to me. The process is running but cannot open the window again without killing the process first.

OS: Manjaro Linux x86_64
Kernel: 4.19.13-1-MANJARO
App version 5.0.0-beta.22
