### ISSUE TITLE
Slack 3rd party notification

### ISSUE THREAD

**Issue by thisischrys** [meetfranz/franz#1222]
I got a message inside slack that I am using a 3rd party application that is not up to date with a link here:
https://get.slack.help/hc/en-us/articles/115002037526

Looks like they will prevent anything not on that list from working starting March 15

**Comment by ilopmar** [comment]
I saw the same message:

![screenshot from 2019-01-16 13-16-06](https://user-images.githubusercontent.com/559192/51248627-0cf75980-1991-11e9-99db-dea8683cd4f0.png)

**Comment by IeuanK** [comment]
Getting the same notification, I have seen some other web apps show similar ones
Franz version info;
Version: 5.0.0-beta.22
Release: 2.0.13 / win32 / x64

**Comment by ccioanca** [comment]
Got the same here.

**Comment by davekeane** [comment]
Looks like Slack is moving to supporting Chrome 66+, and Franz is currently reporting that it's using Chrome 61

**Comment by udikafri** [comment]
Same here
Version: 5.0.0-beta.22
Release: 2.0.13 / win32 / x64

**Comment by tiagoboldt** [comment]
beta21 updated "a ton of dependencies", namely chrome to report version 66. That might be enough to fix this. I have updated to the latest beta and haven't seen the warning since.

**Comment by ilopmar** [comment]
I'm using beta22 and I've seen the error message. Maybe it's just a matter of report Chrome version 67 or higher...

**Comment by tiagoboldt** [comment]
Correcting my comment above, I confirm @ilopmar observation. beta22 uses chrome 66, it probably needs the bump to 67+.

**Comment by whoey** [comment]
I've just seen this popup as well, beta22 on Ubuntu here.

**Comment by Kaspik** [comment]
@adlk Could we please get some update to newer Chrome? :)

**Comment by akinofftz** [comment]
Threema has similar issue.

**Comment by Glennmen** [comment]
Current beta uses the master branch and this branch uses electron version 2.0.13: https://github.com/meetfranz/franz/blob/262198a78bf02b021df4e58c8effb3aca4ff55bb/package-lock.json#L3550-L3551

Electron added Chromium 69 in [v4.0.0](https://electronjs.org/releases/stable#4.0.0) and this has currently only been updated on the develop branch:
https://github.com/meetfranz/franz/blob/449ea5889f03f74aeb1d14894e7e3825177f4948/package-lock.json#L3532-L3533

**Comment by OJ7** [comment]
I'm not seeing this issue anymore with the latest update to Franz (5.0.0-beta23) as that is using electron 4.0.2 / Chromium 69

**Comment by leonardoleal** [comment]
After updating to Franz 5.0.1-beta.1 this issue was apparently solved.

**Comment by martin-sweeny** [comment]
Updating to Franz 5.0.0 on Linux my third-party messages disappeared.

![image](https://user-images.githubusercontent.com/3329959/54653562-8266cf80-4a91-11e9-93c0-043f8278401a.png)

Running on Fedora 29

**Comment by gitanoqevaporelmundoentero** [comment]
Franz 5.0.0 on Ubuntu 18.04 Linux NOT working with Slack:

Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

**Comment by Glennmen** [comment]
@gitanoqevaporelmundoentero That version is really old, Franz 5.0.0-beta23 contained the fix: https://github.com/meetfranz/franz/releases/tag/v5.0.0-beta.23

Anyways you should use the latest release version and not the beta version.

**Comment by Cousjava** [comment]
I had the same issue, but found that it is due to the way Ubuntu reads version numbers; 5.0.0 comes before 5.0.0-beta.18. The way to get 5.0.0 is to download it from https://meetfranz.com/#download and then force install it with

    sudo dpkg -i franz_5.0.0_amd64.deb

**Comment by ondrakrat** [comment]
Update to `5.0.1-beta.1` solved the problem for me on Ubuntu 18.04.

**Comment by gitanoqevaporelmundoentero** [comment]
Thanks a lot @Glennmen. Updating to latest stable release (5.0.0) solved the problem for me.

**Comment by hutber** [comment]
![image](https://user-images.githubusercontent.com/1344898/54751503-1a200700-4bd3-11e9-85de-51c05ee34f8e.png)
Update to the latest beta:
https://github.com/meetfranz/franz/releases

Currently:
https://github.com/meetfranz/franz/releases/tag/v5.0.1-beta.1

**Comment by issei126** [comment]
Slack Notification on Franz does not work.
The badge work fine. 

Franz : 5.1.0
OS: macOS 10.14.5

Help me 🙇

**Comment by deepak365** [comment]
> Slack Notification on Franz does not work.
> The badge work fine.
> 
> Franz : 5.1.0
> OS: macOS 10.14.5
> 
> Help me 🙇

@issei126 Is this issue is fixed for you

**Comment by deepak365** [comment]
> Slack Notification on Franz does not work.
> The badge work fine.
> 
> Franz : 5.1.0
> OS: macOS 10.14.5
> 
> Help me 🙇

> Slack Notification on Franz does not work.
> The badge work fine.
> 
> Franz : 5.1.0
> OS: macOS 10.14.5
> 
> Help me 🙇

@issei126 Is this issue fixed for you?

**Comment by issei126** [comment]
@deepak365 

No, it isn't.

Franz has been updated for 5.2.0, but the Slack notification doesn't work yet.

**Comment by Alwahsh** [comment]
> Slack Notification on Franz does not work.
> The badge work fine.
> 
> Franz : 5.1.0
> OS: macOS 10.14.5
> 
> Help me 🙇

There's a fix for this in the beta version: https://github.com/meetfranz/franz/commit/44c413b
I tried it and it works

**Comment by issei126** [comment]
@Alwahsh 

I tried it and it works too ! Thanks !
