### ISSUE TITLE
Google Calendar cannot inject any styles

### ISSUE THREAD

**Issue by ccioanca** [meetfranz/franz#1223]
The Google Calendar recipe fails to inject its own `calendar.css` styles, or the optional `darktheme.css` styles. 

When trying to append the modal to the `body` of the page, the recipe throws an error, and never actually gets to the line that injects the `calendar.css` styles to the recipe.

Also, not sure if this is related, but injecting the `darktheme.css` also errors out due to the recipe being undefined. 

Stack Trace for the first problem is as follows: 

````
Recipe initialization failed TypeError: Cannot read property 'appendChild' of null  webview\recipe.js:77

    at module.exports.Franz (webview.js:33)

    at RecipeController.loadRecipeModule (webview\recipe.js:72)

    at EventEmitter._class.initialize.Object.keys.forEach._electron.ipcRenderer.on (webview\recipe.js:47)

    at emitTwo (events.js:126)

    at EventEmitter.emit (events.js:214)
````

And the Stack Trace for the `darktheme.css` problem is as follows: 

````
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1] TypeError: Cannot read property 'path' of undefined
    at RecipeController.update (webview\recipe.js:97)
````

Thrown at `...\AppData\Local\Programs\franz\resources\app.asar\node_modules\mobx\lib\mobx.js:1651`

I cannot unpack app.asar at the moment, so I cant delve any deeper there.

**Attached Screenshots**
The problems at hand: 

![capture](https://user-images.githubusercontent.com/13683999/51276166-f60d3300-19a1-11e9-889b-8d872a9df35e.JPG)
![capture2](https://user-images.githubusercontent.com/13683999/51276167-f60d3300-19a1-11e9-9a7e-6c4974b474b4.JPG)

**Device Information:**
 - OS: Windows
 - Chrome
 - V5.0.0-beta.22

**Comment by cohoe** [comment]
This still affects v5.0.0-beta.24 (both Windows and Linux)

I believe this occurs when Google Calendar is "slow" (ish) to load. Per this [StackOverflow post](https://stackoverflow.com/questions/16873323/javascript-sleep-wait-before-continuing), I have been able to successfully render with darkmode styles by modifying `webview.js` to wrap the add/append operations like this:

```js
...
  const getMessages = () => Franz.setBadge(updates);

  modal = createModal();
  setTimeout(function() {
    console.log(document.body.appendChild)
    document.body.appendChild(modal);
    document.addEventListener('keydown', event => event.keyCode === 27 && hideModal());
  }, 2000);

  Franz.injectCSS(path.join(__dirname, 'calendar.css'));
...
```

I do not believe this is a stable thing to do as service definitions change, but ¯\\\_(ツ)_/¯

**Comment by ccioanca** [comment]
I've noticed that darkmode works sometimes, and not other times.

**Comment by cohoe** [comment]
Yeah, I noticed similar. I'm no JS expert but I suspect `document`/`document.body` aren't always quite ready when this script assumes they are. Hence your exception of `Cannot read property 'appendChild' of null`. But those functions are available by the time I pulled up the dev tools. That's what led me to believe it's a timing issue and a delay (2000ms in my example above) would at least make it more likely to succeed.

**Comment by ccioanca** [comment]
if the script tries to run before `document.body` is loaded, instead of the timeout, it could be put in a ready function.

See [here](https://learn.jquery.com/using-jquery-core/document-ready/) for more detail

**Comment by cohoe** [comment]
Nice! Though it looks like jQuery isn't automatically available. [StackOverflow](https://stackoverflow.com/questions/799981/document-ready-equivalent-without-jquery) again to the rescue:
```js
  document.addEventListener("DOMContentLoaded", function(event) {
    document.body.appendChild(modal);
    document.addEventListener('keydown', event => event.keyCode === 27 && hideModal());
  });
```
I forgot to mention I had to drop the last line in `webview.js` that smells like a checksum. Probably voids the warranty. 
`//# sourceMappingURL=data:application/json;charset=utf-8;base64, BLAHBLAHBLAH`

**Comment by ccioanca** [comment]
Good solution! I guess you could make a PR for this!

**Comment by mihirlad55** [comment]
Hey, I was wondering why this never made it to master. I just stumbled upon this issue using `franz-5.5.0-2`. I wasn't able to get darkmode working at all without this patch.

**Comment by ccioanca** [comment]
I closed this after @cohoe merged it into master. Maybe they have something more to add.

**Comment by cohoe** [comment]
My PR was against the plugin, but idk how that actually makes it's way into the Franz ecosystem. Maybe @adlk could elaborate?
