### ISSUE TITLE
Please add Clockify Service to franz.

### ISSUE THREAD

**Issue by kevindrc** [meetfranz/franz#1225]
**Is your feature request related to a problem? Please describe.**
Add support for more services like Clockify, which is alternative to toggl in time tracking application.

**Describe the solution you'd like**
Add Clockify in Services.

**Describe alternatives you've considered**

**Additional context**
Site Link : **https://clockify.me/tracker**

**Comment by closingin** [comment]
Hello,

This repository is only for the Franz client. Please use [this form](https://bitly.com/franz-service-request) for service requests or check out [the guide](https://github.com/meetfranz/plugins) to create your own service integration.

By the way, Franz is a software for messaging, so I don't think this integration would fit. Can you close your issue please ? :slightly_smiling_face:

**Comment by kevindrc** [comment]
I got your point.

Thanks for the info, I will close the issue.

 

Thank You

Kind Regards,

Kevin Patel
