### ISSUE TITLE
Franz service keeps requesting keychain access to System [macOS Mojave] 

### ISSUE THREAD

**Issue by armartar** [meetfranz/franz#1226]
**Describe the bug**
From time to time franz service starts requesting keychain access to System on macOS Mojave. No matter if correct auth info is input or I just deny the request popup reappears after few seconds rendering computer unusable. This issue is solved by restaring the system. 

**To Reproduce**
No special action, appears random while using the app. 

**Expected behavior**
Expected behavior would be for an app developer to use official Apple Dev API which would probably do the same prompt but only once using official popup and not some popup which has franz logo in it. 

**Screenshots**
System popup disables option to make a screenshot. 

**Desktop (please complete the following information):**
 - OS: MacOS Mojave

**Additional context**
Please fix the problem. I really enjoy using your app but described behavior makes it really hard to use which will force me to remove the app.

**Comment by BAndonovski** [comment]
Actually, I would expect that a mere web site wrapper would not need access to the keychain, whatsoever.  
Really not sure why Franz would request that, one way or the other?

**Comment by armartar** [comment]
Can I please get any feedback on this issue?

**Comment by tmhrbr** [comment]
Same problem here, removed the app since the problem is solved.

**Comment by mloureiro** [comment]
This is still happening in **v5.3.3**

<img width="282" alt="Screenshot 2020-05-19 at 12 49 48" src="https://user-images.githubusercontent.com/3427665/82318122-9ed10580-99cf-11ea-865c-a3401b740cf4.png">

In my case want's to access ExpressVPN, not that it should make any difference, but the client is not even open.

<img width="435" alt="Screenshot 2020-05-19 at 12 52 00" src="https://user-images.githubusercontent.com/3427665/82318242-ce800d80-99cf-11ea-8227-3d45acc9f6c6.png">

What I've found so far:
-  closing and re-opening Franz re-triggers the request (most of the times)
- continuously clicking "deny" will eventually stop it (what I often do is move the pop up to a corner)
- clicking "allow" or "always allow" doesn't solve it either (if you want to try it, click "allow" on your own risk, I advice to change whatever the app had access after)

-----

In case this helps, the apps that I have are:
- slack
- 3x gmail (different accounts)
- facebook messenger
- skype
- twitter
- discord
(and a few Gitter, Telegram and Expo disabled)

**Comment by Javascipt** [comment]
I just started experiencing the same thing too. These are the apps I have:

- 3x slack
- Whatsapp
- Skype

**Comment by osimar-medeiros** [comment]
Started today here too.
MacOS Catalina
Franz 5.5.0-beta.4.1756

**Comment by yuriydk** [comment]
Same here
macOs High Sierra 10.13.6
Franz Version 5.3.3 (5.3.3.1582)

**Comment by bucatzel** [comment]
Same here
MacOS Catalina
Version 5.5.0 (5.5.0.1762)
Also happened earlier in the day, while i still had the previous version (5.4.0, i think). Upgraded, but no luck

**Comment by shuttle842** [comment]
Same with me, issue started earlier today
MacOS Catalina 10.15.4
Franz Version 5.5.0-beta.4 (5.5.0-beta.4.1756)

**Comment by jcifuentes91** [comment]
Started Happening 
MacOS Catalina 10.15.4
Franz Version 5.4.1 (5.4.1.1703)

**Comment by guadalupeba83** [comment]
Samezies here. Started a few weeks ago.
