### ISSUE TITLE
Gitter notifications don't work after a while

### ISSUE THREAD

**Issue by jjperezaguinaga** [meetfranz/franz#1231]
**Describe the bug**
In short, if I'm using Gitter.im, I get notified from various conversations. However, if I don't, after a while, I stop getting any notifications and I need to remember I have that open so I check that service.

**To Reproduce**
1. Add gitter.im, add any group.
2. Have a normal conversation.
3. Stop having a conversation.
4. Wait until you see you miss a day of conversations for no reason.

**Expected behavior**
Ideally I'll keep getting notified from Gitter notifications.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 5.0.0-beta.19 (5.0.0-beta.19.1004)

**Additional context**
I've noticed the same issues in Twitter Deck and Discord, but I'm happy if we focus on Gitter first.

**Comment by vojtechjelinek** [comment]
Hi, I'm having the same problem, notifications stop showing after a while for Gitter, even when I'm tagged.
