### ISSUE TITLE
Skype:  badge and image link don't work

### ISSUE THREAD

**Issue by alekszi** [meetfranz/franz#1232]
I don't see on skype logo badge with unread messages and when some one send me links/images I can't open this.

How can I solve this problems?

PS already I can't cmd+c text.

mac os, mojave

**Comment by lzakrzewski** [comment]
I have exactly the same issue.

**Comment by enrij** [comment]
> [sarcasm mode on]
> Thanks for support on github and email.
> I feel that my money was well spent
> [sarcasm mode off]

email?

**Comment by dade-shinji** [comment]
Same here, even on the new version 5.50-beta2.
I'm on osX 10.11.6 btw!
