### ISSUE TITLE
KDE: Xorg icon displayed in task switcher

### ISSUE THREAD

**Issue by ChTBoner** [meetfranz/franz#1233]
**Describe the bug**
On KDE, the icon displayed in the task changer (aka Alt+Tab) is the Xorg icon.

Did a little digging online, and it seems it is due to the fact that the _NET_WM_ICON(CARDINAL) value is not set for Franz. (checked with xprop)

**To Reproduce**
1. Open Franz
2. Use Alt+Tab to trigger the task switcher
3. See the Xorg icon

**Expected behavior**
The Franz icon should be displayed instead of the Xorg icon.

**Screenshots**
![franz xorg icon](https://user-images.githubusercontent.com/14848356/51538465-a622e600-1e51-11e9-9a90-e271ae7ce550.png)

**Additional context**
OS: Fedora 29
KDE 5.14.4
Reproduced with the latest AppImage et tar.gz package (5.0.0-beta.22)

**Comment by BunnyTheLifeguard** [comment]
I would love to see this fixed, too :)

Operating System: Manjaro 18.0.3 
KDE Plasma Version: 5.15.1
AUR Package 5.0.0-1

**Comment by ChTBoner** [comment]
Still the case with the latest appimage.
