### ISSUE TITLE
gmail open email in new window brings up a blank screen

### ISSUE THREAD

**Issue by Gohowardtx** [meetfranz/franz#1234]
**Describe the bug**
open email in new window brings up a new screen that is blank.

**To Reproduce**
in Gmail, if you have a two column layout with reading pane on the right-hand side.
when you click on an email on the left-hand side you have an option to open in a new window.
when you do this a new window opens but it is blank.

**Expected behavior**
the email should be displayed in the new window

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 7 64-bit
 - Browser chrome
 - Version  63.0.3239.84 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chrisbeardy** [comment]
I have the same issue with office 365 mail
