### ISSUE TITLE
Services forgot between sessions

### ISSUE THREAD

**Issue by alecive** [meetfranz/franz#124]
Hi, 

I just installed franz 5.0 on Ubuntu 14.04 from deb file (see #3 ). At the first run everything was fine, I was able to import services from my previous franz 4.4, to add new services and create an account. 

But after closing franz and opening it again, services are not saved and it prompts again to add services. Furthermore, if I click on any service it doesn't actually let me set it, but rather it stays there doing nothing.

**Comment by adlk** [comment]
I have experienced some issues with the import of on premise services. Can you please send me an email to stefan@adlk.io to let me know what email address you have used during signup?

**Comment by alecive** [comment]
sure!

**Comment by alecive** [comment]
Ok after debugging we found out it was because I was loading a custom recipe that I was using with Franz 4. Thanks for the help @adlk !
