### ISSUE TITLE
Dark theme for telegram

### ISSUE THREAD

**Issue by filipejesse** [meetfranz/franz#1240]
Hi, 
can you allow the function to change telegram's theme please.

**Comment by closingin** [comment]
Hello filipejesse,

Could you be polite please ? :slightly_smiling_face:

**Comment by filipejesse** [comment]
Sorry, my bad man...

**Comment by HasEPhenix** [comment]
what is the status on telegram dark theme? 
I would appreciate it to a huge degree as I need dark theme to aid my bad vision. 
Thanks!

**Comment by Gaboris** [comment]
Hey @HasEPhenix 

Franz doesn't really have anything to do with adding dark themes to services by default, but if you look around there are several "issues" about dark themes for services. Mainly in the closed list, but still. :)

As far as I know custom themes are supported in all services, but correct me if that's not the case with Telegram.

- You need to find a custom dark theme style sheet off of Stylish or other similar sites.
https://userstyles.org/styles/browse?search_terms=telegram
- Edit its code so it won't have Stylish related stuff at the end and beginning of it. (if you have no idea how that works you'll need to find someone to help you.)
- Find the recipes folder of Franz by typing "%AppData%\Franz\recipes\" into your file explorer's top bar and insert that new style sheet into the telegram folder with the name "darkmode.css".
- Go to Franz's settings, find Telegram within services and enable dark mode for it.

If you did everything right it SHOULD work after a Franz restart.

**Comment by HasEPhenix** [comment]
Hello,

thanks a lot for your fast reply and suggestions.
I looked around at found this theme for telegram
https://github.com/bloodf/franz-dark-telegram

However I am having trouble applying it.
I unpacked all files and moved them to
AppData\Roaming\Franz\recipes\telegram

My main question is: where am I supposed to to change the theme? I looked
under
Settings/your services/telegram and went trough all options however I do
not see something like "change design" "change theme" "color" "appearance"
etc.

Do you have a idea how I should proceed?

Thanks in advance and have a nice day
Lars

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am So., 7. Apr. 2019 um 16:59 Uhr schrieb Gaboris <notifications@github.com

**Comment by Gaboris** [comment]
Hey @HasEPhenix

Sorry, didn't have time to respond.

Okay wait. That's a recipe. I have NO idea how those work within Franz. They are just used for adding services to the system that aren't already in it as far as I know. :P

You need to get a clean .CSS style from the Stylish website I linked and use that.

There should be a plain and simple "Enable dark mode" setting in each service's settings, but maybe it only appears if it detects the appropriate darkmode.css file or something.

**Comment by joeytwiddle** [comment]
Thanks for the instructions Gaboris. The first link worked for me: [Web Telegram Dark by Haron Prime](https://userstyles.org/styles/132781/web-telegram-dark)

But there was one extra step required:

After copying the CSS code into `darkmode.css`, remove the top lines:

    @-moz-document domain("web.telegram.org"), domain("web.tlgrm.eu")
    {

and the bottom line:

    }

to make a pure CSS file.

**Comment by Gaboris** [comment]
Hey @joeytwiddle glad I could help.

Yeah sorry, I forgot to repeat that part since I already said it in my comment before that one. :)
