### ISSUE TITLE
Can't use rocket chat self-hosted

### ISSUE THREAD

**Issue by Gsantomaggio** [meetfranz/franz#1241]
**Describe the bug**
I can't use rocket chat for self-hosted, I get the error:
`Could not validate custom rocket chat` 

_Using the official client  works correctly_

**To Reproduce**
1. Go to 'rocketchat'
2. Click on 'Selfhosted'
3.  Insert selfhosted url

**Expected behavior**
Enable the connection
**Screenshots**

![issue](https://user-images.githubusercontent.com/386987/51819688-954ff580-22d3-11e9-926f-1c0549ebd390.png)
**Desktop (please complete the following information):**

**Additional context**
Using Ubuntu, version 5.5.0-beta.22
Our server is inside a vpn

**Comment by adlk** [comment]
please send an email to stefan@adlk.io. I'd like to do some debugging.

**Comment by brunorozendo** [comment]
I have the same issue.

![erro_franz](https://user-images.githubusercontent.com/5125193/83876122-b1a54300-a70e-11ea-83d5-541cce1363dd.png)

OS: Arch Linux x86_64 
Kernel: 5.6.15-arch1-1 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 
CPU: Intel i7-7500U (4) @ 3.500GHz 
GPU: NVIDIA GeForce 940MX 
GPU: Intel HD Graphics 620 
Memory: 5771MiB / 15798MiB
