### ISSUE TITLE
Loading message doesn't disappear

### ISSUE THREAD

**Issue by alexandre1985** [meetfranz/franz#1243]
**Describe the bug**
When I start Franz, the pages of the activated services that I have always appears with a "Loading" dialog message that never disappears, even after the service page is totally loaded.

**To Reproduce**
1. Put Franz to start at boot and boot the PC

**Expected behavior**
The Loading dialog message should disappear after the service page has been loaded

**Screenshots**
![deepinscreenshot_20190129202332](https://user-images.githubusercontent.com/5586308/51938055-055d9900-2404-11e9-96a8-11c46f78ed22.png)

**Desktop (please complete the following information):**
 - Manjaro Linux Deepin
 - Firefox
 - 5.0.0-beta

**Other info:**
When I disable a service and re-activate it again the problem is solved. But have to do that everytime the PC boots for every franz service that I have

**Comment by Kamahl19** [comment]
restarting the franz works for me too

**Comment by alexandre1985** [comment]
When I boot the pc I always get this issue

**Comment by adlk** [comment]
Please specify the exact beta version.

**Comment by alexandre1985** [comment]
version: 5.0.0-beta.22
release: 2.0.13 / linux / x64

**Comment by Scritik** [comment]
Same here, on macOS (High Sierra), Franz 5 beta 24.
Sometimes, I have to restart the app multiple times.
