### ISSUE TITLE
Franz doesn't launch after being closed on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by elyaB** [meetfranz/franz#1246]
**Description**
Franz launches at startup. I exit the application using GUI.
Then i attempt to restart it, clicking on its icon in the Activities overview (pressing Super key). But it never launches.
![image](https://user-images.githubusercontent.com/26736365/52040186-f0355700-2536-11e9-8669-4940a15a9ab2.png)

**Actual**
Franz doesn't launch GUI when it's icon is clicked in the search menu
However, its process is visible using the top command :
![image](https://user-images.githubusercontent.com/26736365/52040962-591dce80-2539-11e9-9dc1-6f408512dafc.png)

**To Reproduce**
1. Franz should start at the startup of your computer
2. Click on the cross of GUI to close the app
3. Press Super key ton open Activities Overview, type in Franz
4. Click on Franz's icon
5. Franz doesn't launch

**Expected behavior**
Franz launches when its icon is clicked in the search menu

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 16.04.3

**EDIT :**
I remember having the same issue on Fedora 27

**Comment by omrishalev22** [comment]
Also can reproduce on version 18.04
