### ISSUE TITLE
Feature request: notification color depending on service

### ISSUE THREAD

**Issue by kingjr** [meetfranz/franz#1248]
Currently the notification in the taskbar is always red. 

It would be great if its color could be parametrized depending on the service it corresponds to:e.g. red for gmail, blue for messenger etc.

**Comment by Gaboris** [comment]
You mean the little "unread message" dot on the icon or those popup/toaster notifications?

I'm down with both, but if it's the dot then how would Franz color it if there were multiple services? Always keep the color of the last one or keep them stacked in a line next to the icon? THAT would be useful.

**Comment by kingjr** [comment]
> You mean the little "unread message" dot on the icon or those popup/toaster notifications?

yes

> I'm down with both, but if it's the dot then how would Franz color it if there were multiple services? Always keep the color of the last one or keep them stacked in a line next to the icon? THAT would be useful.

I would stack the dots, and show the 3-4 most recent ones:
![image](https://user-images.githubusercontent.com/4881164/52064841-b33c8500-2575-11e9-8832-ec6d38cad3cf.png)
