### ISSUE TITLE
Ability to choose between two or more hosted environments for a service as well as non-hosted.

### ISSUE THREAD

**Issue by adambirds** [meetfranz/franz#125]
### Feature Description
I would like the ability to be able to choose between multiple "hosted" environments for a single service as well as non-hosted environments.

### Motivation and Context
Zulip has two hosted environments:
*https://chat.zulip.org
*https://{teamid}.zulipchat.com

Zulip also allows users to have their own non-hosted environments as well so this is also required at the same time as the above two hosted environments.

Currently this isn't available in Franz.

**Comment by adambirds** [comment]
@adlk is this getting done at some point? Thanks

**Comment by cmoulliard** [comment]
+1 to have this feature

**Comment by adambirds** [comment]
Closing. You can do this now.
