### ISSUE TITLE
Can't change the skin color of some WhastApp emoji

### ISSUE THREAD

**Issue by luuurq** [meetfranz/franz#1250]
**Describe the bug**
In the mobile version of WhatsApp, some emoji are available in different skin colors. If you want to select a different colored emoji, you should tap and hold the emoji you wish to use and select the color you want.
However, in the current Franz version, this is not available for all the emoji with this function. Some work, some don't. In my Franz/WhatsApp, only the icons down to the Papa/Mama Noel work as expected. From the wizards on/down, it doesn't work.

**To Reproduce**
1. Go to a WhatsApp conversation
2. Open the emoji selection menu
3. Find the shrug emoji, for example. Tap and hold.
4. The skin colors don't appear :(

**Expected behavior**
The different skin colors should appear.

**Screenshots**
Papa Noel and the (working) skin colors:
![image](https://user-images.githubusercontent.com/47246620/52124229-db38f080-2628-11e9-9d7b-1f82594bef34.png)

The non-working skin color emoji:
![image](https://user-images.githubusercontent.com/47246620/52124265-fdcb0980-2628-11e9-902c-16f5220b8885.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome (Version 72.0.3626.81 - up to date)
 - Franz Version 5.0.0-beta.18 - Release 1.8.4 / win32 / x64

Thanks!!

**Comment by ZtheLeader** [comment]
Facing same issue on:
- OS: macOS Mojave V 10.14.5
- MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)
- Browser Chrome (up to date)

**Comment by zipperdeedo** [comment]
Facing same issue on Windows 10, Chrome, all up to date. 

Haave tried for months raising tickets with Whatsapp support, they seem to almost intentionally misudnerstand what i'm saying, despite attaching screenshots and video

**Comment by pablorms** [comment]
Have been seeing this problem for over a year now on different machines!

**Comment by luuurq** [comment]
This bug has been fixed for me :D if others confirm, then I would close this issue :)
Franz version: 5.3.3
Platform: win32 release: 10.0.17134

**Comment by zipperdeedo** [comment]
Also resolved finally for me!

**Comment by pablorms** [comment]
Yep it's fixed
