### ISSUE TITLE
5.0.0-beta.23 Breaks darkmode.css

### ISSUE THREAD

**Issue by ccioanca** [meetfranz/franz#1251]
5.0.0-beta.23 (2019-02-01) seems to no longer render the styles that come from darkmode.css

**To Reproduce**
Update to 5.0.0-beta.23 and try to use custom darkmode.css styles.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

EDIT:

Looks like `webview/darkmode.js -> injectDarkModeStyle()` never gets called. Neither are `isDarkModeStyleInjected()` and `removeDarkModeStyle()` so it isnt ever reaching here. It also isnt tricking itself into thinking darkmode is already injected or tricking itself into removing said styles.

**Comment by IjonFryderyk** [comment]
Same on Ubuntu 18.04.
