### ISSUE TITLE
5.0.0-beta.23.1101 - slack messages jump back in time when switching services

### ISSUE THREAD

**Issue by epfrankle** [meetfranz/franz#1252]
**Bug Description**
I have 10 slack services integrated with desktop Franz. After updating to 5.0.0-beta.23.1101, I switched from an extracurricular Slack to my work Slack, and after loading the most recent messages very briefly, the messages in the open channel jumped back about a week.

When switching back to the other slack service, it also jumps back in time; switching back yet again moves the work slack messages up another several weeks.

**To Reproduce**
1. Go to a Slack service in Franz.
2. Switch to another slack service in Franz.

**Screenshots**

Where I started:
<img width="400" alt="screen shot 2019-02-01 at 6 04 59 pm" src="https://user-images.githubusercontent.com/28760377/52154517-2fa19780-264c-11e9-8d91-0f9cab07a889.png">

After switching:
<img width="400" alt="screen shot 2019-02-01 at 6 08 18 pm" src="https://user-images.githubusercontent.com/28760377/52154565-755e6000-264c-11e9-9cfe-815d73a4067b.png">

An instant later:
<img width="400" alt="screen shot 2019-02-01 at 6 09 39 pm" src="https://user-images.githubusercontent.com/28760377/52154606-a63e9500-264c-11e9-8cf2-37b77f10a375.png">

Switching back:
[Links to screen capture](https://drive.google.com/open?id=1jB4-vrxZoh9Jgrr0CBCOEj3yWVvgIL3n)

**Desktop (please complete the following information):**
 - OS: OS Mojave 10.4.2
 - Version: 5.0.0-beta.23.1101

**Comment by fagnerpsantos** [comment]
Same here

**Comment by pete001** [comment]
Yep, same here

**Comment by philippeller** [comment]
same here!

**Comment by mstratford** [comment]
Same, and in my case, the channel menu also disappears apart from the workspace name and my name.

**Comment by mstratford** [comment]
Can confirm, fixed for me 👍

**Comment by epfrankle** [comment]
Also confirmed! Thanks so much for the quick response and fix, @adlk--vielen Dank!

**Comment by midsandhighs** [comment]
Confirmed fixed in b24

**Comment by pete001** [comment]
Phew, that manual scrolling was brutal! Nice fix.
