### ISSUE TITLE
Quick-switching between services does not focus text input

### ISSUE THREAD

**Issue by jsanford8** [meetfranz/franz#1255]
**Describe the bug**
Since the beta 23 upgrade, after utilizing quick switch (cmd+num) to switch between services, the keyboard is not focused on the new service. Instead, it is still focused on the previous service.

For instance, if you are on Slack, and you CMD+2 to a new service (say gmail), and try to use keyboard shortcuts (j/k to move up/down the email list), nothing will happen. Moving back to Slack, you'll see each keyboard input shown in the text field (i.e. a bunch of j's and k's).

This did not happen prior to beta-23

**To Reproduce**
See above. Go to Slack within Franz. Quick Switch (cmd+num) to gmail. Press j or k to navigate message list.

**Expected behavior**
j and k should navigate through the message list. It does not. Instead, each j and k input (and all keyboard input) is in the active chat window within the Slack service.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Desktop... so Chrome?
 - Version 5.0.0 beta 23

**Additional context**
Again, this never happened until beta 23, which seems to have broken a lot of things. Franz has been great, but these updates breaking _core_ existing functionality borderline make this not worth using,

**Comment by adlk** [comment]
Thanks for reporting. 

> Again, this never happened until beta 23, which seems to have broken a lot of things. Franz has been great, but these updates breaking core existing functionality borderline make this not worth using,

We updated electron from chromium 61 to 69 so in theory a lot could have gone wrong. If a _lot_ of core functionality isn't working then please report it.
