### ISSUE TITLE
Unable to login into mysms service with google account

### ISSUE THREAD

**Issue by mtadmk** [meetfranz/franz#1258]
**Describe the bug**
Unable to login into mysms service with google account

**To Reproduce**
1. click "sign in with google"
2. popup window appears and straigh afterwards closes
3. I'm not logged in

**Expected behavior**
User is authenticated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs mojave
 - Version 5.0.0 beta 19

**Smartphone (please complete the following information):**

**Additional context**

**Comment by am-os** [comment]
I am also having this issue

**Comment by wesleymostien** [comment]
same here
