### ISSUE TITLE
Error message : "node.dll is missing" (beta 23/24)

### ISSUE THREAD

**Issue by seyhajin** [meetfranz/franz#1259]
**Describe the bug**
I have an error message : "node.dll is missing" after restart and update from app or complete reinstall from binaries.

**To Reproduce**
1. Click on "Restart and install new update" from app or reinstall from executable binaries (beta 23 or 24)
2. Error message become when Franz Installer relaunch application.

**Screenshots:**

![image](https://user-images.githubusercontent.com/24609692/52196271-7ca78880-285b-11e9-80d5-e654a12d8fd3.png)

**Desktop:**
 - OS: Windows 10 Professional (64 bits)
 - Browser: Chrome 72 (64 bits)

**Workaround**
Reinstall beta 22.

**Comment by adlk** [comment]
When this issue is happening, it usually helps to restart your machine before trying to re-install the app.

**Comment by seyhajin** [comment]
I have : 
- Uninstall Franz
- Reboot machine
- Reinstall Franz

It's ok now. Thanks.

**Comment by ichpen** [comment]
Confirmed too on Win 10.

I noticed that beta 23 and beta 24 do not have node.dll in the install package but beta 22 does. Reinstalling beta 22 fixes this issue.

@adlk
