### ISSUE TITLE
Support for password managers

### ISSUE THREAD

**Issue by oliver-gramberg** [meetfranz/franz#1260]
**Feature Description**
As a user, I want to use my password manager (e.g., KeePass) to log in to services integrated in Franz.

**Motivation and Context**
Not all sessions live forever, so I need to log in to a service in Franz every now and then. Actually, there is one service I use where I have to log in at least once a day. Password managers are my way of handling those very safe, 30-character passwords I have set.

**Is your feature request related to a problem? Please describe.**
Password managers (at least some) provide a shortcut key that, when the user presses it, determines the credentials to apply to the top-most window and automatically enters them. For that to work, password managers generally look at the window title or the URL displayed on the address bar of a browser window. Franz doesn't have an address bar, and the window title is always just "Franz" (according to Windows's task manager and KeePass's list of available window titles), no matter which service is currently showing.

**Describe the solution you'd like**
If Franz would show the name of the recipe in the window title (maybe in addition to "Franz"), password managers could (be configured to) find the applicable credentials and automate log-in.

**Describe alternatives you've considered**
* I can manually look up the credentials in the password manager and start automation from there, but that takes a lot of clicks and time more than just pressing a global shortcut key that automates all of this.
* I can create, for each Franz service represented in my password manager, a second entry for that service to be used when applying the global shortcut key to the Franz window. I would then be presented a list of all such second entries, and would have to choose manually the one to be applied to the current service. This is a lot of additional configuring and still not as convenient as can be.

**Additional context**
To be fair, I want to mention #1174, but I am not happy with storing passwords online.

**Comment by SoliElvis** [comment]
Honestly this is the feature that would make me go platinum or pro version

**Comment by Gittyperson** [comment]
Since you are using KeePass, you can already do this. Just use Auto-Type. Create multiple service entries for the single window title "Franz" and you are done. Your entries' titles could be for example, "Franz-Skype", "Franz-Telegram" and so on.

I'm using it, works fine.

**Comment by oliver-gramberg** [comment]
@Gittyperson 
> Create multiple service entries for the single window title "Franz", properly configure each auto-type sequence and you are done.
I have added in the OP a second "alternative I have considered". Is that how it works for you? If not, let me know. Thanks

**Comment by Gittyperson** [comment]
Yes, that's it. That's how the [Global Auto-Type Hot Key](https://keepass.info/help/base/autotype.html#autoglobal) works. If you use a lot of services, then configuring them all could be a pain but once done, usage should be smooth.

It'd be nice to have what you propose but I'm guessing it wouldn't be a priority.
