### ISSUE TITLE
Whatsapp no longer working

### ISSUE THREAD

**Issue by tyranteon** [meetfranz/franz#1263]
**Describe the bug**

Since yesterday, clicking on Whatsapp only leads to a page that tells me to update chrome.

**To Reproduce**
- Add Whatsapp Service
- Try opening it

**Expected behavior**
It should open Whatsapp

**Screenshots**
![image](https://user-images.githubusercontent.com/4991312/52262946-32430c00-292e-11e9-87c4-4cf5d7cbed4c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 5.0.0-beta.24
- Release 4.0.2 / win32 / x64

**Comment by Dergonic** [comment]
Got same issue here, but I went a little bit further

**Observations : **
- When you start Franz, WhattsApp fails loading as @destructive-dragon described.
- When you right click on the WhattsApp icon on the left panel and hit "reload", WhattsApp starts fine !

- When WhattsApp have started (after the "reload"), it proposes to update WhattsApp
![image](https://user-images.githubusercontent.com/11134717/52329156-3f293380-29f2-11e9-91ed-77d4a9947689.png)
(Sorry, screen in french as I'm French speaking :( )
- Updating used to be successfull

- When you close Franz, you have to restart the whole process : Start Franz - Reload WhattsApp - Update WhattsApp

**Environement :**
* OS: Windows 10 pro 
* Version 5.0.0-beta.24
* Release 4.0.2 / win32 / x64

**Comment by Dergonic** [comment]
After deep check, it looks like issue is already known

#https://github.com/meetfranz/franz/issues/1185
