### ISSUE TITLE
Franz ignore system proxy settings

### ISSUE THREAD

**Issue by Serubin** [meetfranz/franz#1265]
**Describe the bug**
Since beta.24 franz has been ignore the system proxy enabled on my mac. This causes all outgoing connections to fail. 

**Expected behavior**
Normal connections

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Version beta.24

**Additional context**
Similar proxy related issues were happening with previous versions of franz in specific services  such as Messenger and Discord.

**Comment by sanchocsa** [comment]
I have the same issue, even with the latest version of Franz. It ignores the system proxy (Windows 10, inside my corporate network), so I can't connect to my account nor load my services.

I can temporarily work-around it by connecting to an open "guest" wifi, letting Franz load and connect my services, and then going back to my corporate network.

**Comment by Serubin** [comment]
The issue here is that franz doesn't pay attention to local certs and thus can't verify unknown connections. 

Likely a low priority as this doesn't effect too many customers.
