### ISSUE TITLE
MS Teams don't allow to call but now CPU goes better

### ISSUE THREAD

**Issue by sstraus** [meetfranz/franz#1270]
With the latest beta 5.0.0-beta.24 The CPU usage decreased by 10%, but with the Microsoft Teams integration is no more possible to start a call. 

The client asks to install the app, and probably is something related to the user agent. 
On the previous version, I had the problem just clicking the call button inside the user card. With current version also clicking the call button on the chat window.

**Comment by CluelessTechnologist** [comment]
Would it be possible to Franz to spoof user agent like this: https://techcommunity.microsoft.com/t5/Microsoft-Teams/TEAMS-and-LINUX-The-Future-is-Now/td-p/251876

**Comment by pj-r** [comment]
@CluelessTechnologist It is. See https://github.com/meetfranz/franz/issues/1095#issuecomment-461086679
Screen sharing on call is still not possible as far as i know.

**Comment by ramalhovfc** [comment]
Still not possible in v5.1.0-beta.1
