### ISSUE TITLE
Inactive tabs are stuck on loading

### ISSUE THREAD

**Issue by AfzalivE** [meetfranz/franz#1271]
I have about 8 enabled services and as of late, most of the time only the active service loads up. When I switch to another service, it's still loading. Happens with Whatsapp, Messenger, Slack.

Disabling and re-enabling the service usually works but if loading is failing at some point, it should be reloading automatically.

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md
