### ISSUE TITLE
Tray icon - toggle app visibility option

### ISSUE THREAD

**Issue by mrandreastoth** [meetfranz/franz#1276]
It should be possible to configure the tray icon behaviour so that, if the app is showing, when the icon is clicked, the app is hidden, and, if hidden and the tray icon is clicked, then the app is shown (as it currently always does).

**Comment by tchiotludo** [comment]
As I remember, it works this way on beta 21 or 22. and stop working on beta 23
(for information, I'm on linux)

**Comment by jerry1970** [comment]
Same here, Ubuntu 18.04, I remember it once worked, then it didn't and I switched to Rambox. Now Rambox doesn't have this anymore either so I need a new dock for my web apps. Hope to go back to Franz!

**Comment by kendoori** [comment]
I loaded the app image from beta 23 and the toggle behavior worked again. Easy enough to run the app image without uninstalling the newer release: https://github.com/meetfranz/franz/releases

**Comment by jeroenst** [comment]
+1 (not working on current release and latest beta release 5.2.0-beta.2 (2019-06-12))
