### ISSUE TITLE
Franz Helper is killing my Mac

### ISSUE THREAD

**Issue by dm82m** [meetfranz/franz#1277]
**Describe the bug**
"Franz Helper" CPU usage constantly nearly at 50%.

**To Reproduce**
Just start Franz and wait a few seconds...

**Expected behavior**
No high CPU usage of "Franz Helper".

**Screenshots**
![image](https://user-images.githubusercontent.com/736311/52568811-164cd800-2e10-11e9-9609-1d5cda687efb.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Chrome Version 71.0.3578.98 (Offizieller Build) (64-Bit)
 - Franz Version: Version 5.0.0-beta.24 (5.0.0-beta.24.1110)

**IMPORTANT**
  - If I disabled the Facebook messenger, everything is okay!

**Comment by dm82m** [comment]
I guess it is related to: https://github.com/meetfranz/franz/issues/24

**Comment by jooray** [comment]
Same here, seems that after a recent update, Franz is killing my Mac - Franz Helper is eating almost half of the CPU, very similar to the screenshot above.

The culprits seem to be Messenger and Discord. Is there a way to find out which service it is? Except for clicking on disable for each service until I find the process that generates the load. And is there a way to see what the process is doing? (JavaScript calls or anything like that).

I think it would be great to use the freezing feature of chrome and disable the processing in background "tabs" for most of the time. I don't need an instant notification, so the service can be frozen for 55 seconds out of a minute in order not to generate load and consume battery.

Franz has become totally unusable for me lately, if I want to travel and preserve the battery, I just have to kill it.

(I have the latest model Macbook Pro, so no old computer issue, everything is up to date)

**Comment by LordNacho** [comment]
Same issue here. How do you know which service is responsible? @jooray

**Comment by jooray** [comment]
Messenger and Discord use the most CPU.

I think what would be useful would be to freeze the windows in the background for configurable intervals (for me, even one minute would be OK) and then let them run event loop for a few seconds.

I don't need all the tabs to be constantly active in the background, I just need fast access to an account without needing to log in again.

Also the event loops that check the badge every second should be configurable I think. For example for me even once per 10 minutes badge is enough.

**Comment by noway1987** [comment]
Got the same problem here with microsoft teams - constant 18-25% CPU usage

* OS: MacOS Mojave 10.14.3
* Chrome Version 72.0.3626.119 (Offizieller Build) (64-Bit)
* Franz Version: Version 5.0.0 (5.0.0.1136)

**Comment by juliojlgon** [comment]
Same Problem as well. For me it seems to be slack, as soon as I start it my Mac gets crazy.

OS: MacOS Mojave 10.14.3
Chrome: Version 72.0.3626.119
Franz Version: Version 5.0.0 (5.0.0.1136)

**Comment by jamiedarcher** [comment]
I just posted a similar issue report before I saw this thread... it seems closing and reopening helped a little but after a while it ramps again

**Comment by dm82m** [comment]
Franz is not usable anymore, will switch back to Rambox. So sad that even such critical bugs are not beeing fixed...

**Comment by dm82m** [comment]
any idea how to stop franz on mac to auto-update?

**Comment by jooray** [comment]
Did the new version Version 5.0.1-beta.1 (5.0.1-beta.1.1221) fix this issue? I noticed it's there but no mention of this bug in the changelog.

**Comment by dm82m** [comment]
I'll give it a try ... ;-)

**Comment by dm82m** [comment]
Not fixed. Franz is not usable anymore. So sad!

**Comment by niebloomj** [comment]
Not fixed :(

**Comment by diananoias** [comment]
Franz Helper using the 150% of my CPU! The computer's fan is running like there's no tomorrow. Suggestions?

**Comment by dm82m** [comment]
switch to https://rambox.pro and the problem is gone.

**Comment by djxcee** [comment]
I'm running Mojave and the CPU usage is insane with Franz Helper.  I'm trying to Catalina to see if that helps.

**Comment by jamiedarcher** [comment]
I switched to Rambox I couldn't deal with the resource death on my 2013
Macbook Pro

[image: View my portfolio] <http://secondvariety.org>

Jamie Archer
UX/UI Designer | Interaction Design | Digital Project Manager
jamie@secondvariety.com

WhatsApp +44 7512 834 168
Tel. +30 698 558 79 70

http://secondvariety.org


[image: Twitter] <https://twitter.com/ApacheSenzala> [image: Facebook]
<https://web.facebook.com/jamie.d.archer> [image: Instagram]
<https://instagram.com/apachesenzala> [image: LinkedIn]
<https://www.linkedin.com/in/jamiearcher/>
