### ISSUE TITLE
Alt-tab to cycle through services not working.

### ISSUE THREAD

**Issue by joshuak94** [meetfranz/franz#1280]
**Describe the bug**
Before I updated (not sure what previous version was), I was able to alt+tab to cycle through the active services. I can no longer do this.

**To Reproduce**
1. Open Franz with more than one service.
2. Hold alt, press tab.
3. Nothing happens.

**Expected behavior**
The window should switch to show the next active service.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Browser: Firefox
 - Version: 65

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS 12.1.2
 - Browser: Safari
 - Version: N/A

**Additional context**
Franz version: 5.0.0 beta 2.4

**Comment by ZoidbergVA** [comment]
I can also confirm this issue with version 5.0.0 beta 2.4, version 5.0.0 beta 2.3 did not have this issue.

**Comment by marcelotedeschi** [comment]
I just updated to version `5.0.0.1136` for Mac and I'm not able to switch between services using `ctrl + tab`. Since the issue is potentially the same, I'll leave my comment here.

**Comment by harrytouche** [comment]
Just updated to 5.0.0 (Win10, not beta) and seeing this. Previously I was able to CTRL-TAB to go to the next service, and CTRL-SHIFT-TAB to go to the previous one
+1 for a fix

**Comment by hutber** [comment]
:+1:
