### ISSUE TITLE
Skype - "Browser not supported"

### ISSUE THREAD

**Issue by ghost** [meetfranz/franz#1281]
**Describe the bug**
Skype shows:

_Browser not supported
Use Microsoft Edge or Google Chrome to access Skype for Web (Preview) experience.
Alternatively, download Skype on your desktop computer._

**To Reproduce**
1. Create a Skype service.

**Expected behavior**
Skype to work.

**Screenshots**
https://i.imgur.com/Nl5jNuV.png

**Desktop (please complete the following information):**
Windows 7. My default browser is Firefox, where I notice Skype Web has the same error. However Franz has ordinarily shown up as Chrome.

_"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Franz/5.0.0-beta.18 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36"_

**Additional context**
Issue started today.

**Comment by anewtonlevey** [comment]
Experiencing the same issue with 5.0.0-beta.18

**Comment by tkreque** [comment]
> Experiencing the same issue with 5.0.0-beta.18.
> 
> Updating to 5.0.0.-beta.24 has resolved the issue.

Thanks, this fixed the issue for me :)

**Comment by find-evil** [comment]
I'm on OS X Mojave 10.14.3 and not getting the option to upgrade from 5.0.0.-beta.18 to beta.24

I did not have beta updates enabled so not sure how I ended up with this version, but checking for an upgrade isn't working.

<img width="282" alt="screen shot 2019-02-20 at 5 08 47 pm" src="https://user-images.githubusercontent.com/1427897/53128225-5f98d800-3532-11e9-84e9-d7826fe4f33c.png">

**Comment by vdaele** [comment]
I'm on Linux (Ubuntu 16.04) and I'm also stuck with 5.0.0-beta.18 (and no skype :-( )

**Comment by tymik** [comment]
when will this come to stable?

**Comment by yermulnik** [comment]
There might be a manual workaround like this https://github.com/meetfranz/franz/issues/1347#issuecomment-475107222 I guess. Any clue about this? I don't have any User Agent settings in `~/.config/Franz/recipes/skype/index.js` =(

**Comment by yermulnik** [comment]
@anewtonlevey @tkreque Could you guys please show the contents of `~/.config/Franz/recipes/skype/index.js` on your system?

**Comment by vdaele** [comment]
Here is mine
```
"use strict";

module.exports = Franz => Franz;
```

**Comment by yermulnik** [comment]
Oh, I see. This means that default Franz User Agent has been updated in betas to align with new Skype and Slack requirements...

**Comment by pnenov** [comment]
Browser not Supported ..... dude, it i so, so, so BORING !

**Comment by mitelg** [comment]
same problem here since today. I'm using current 5.0.1-beta.1 on Ubuntu 18.10

**Comment by leasti** [comment]
Same problem, i've updated the index on skype recipe and reloaded Franz, but it still not working.

**Comment by q4z1** [comment]
@ yermulnik replacing chrome version ain't enough - just use the complete Microsoft Edge User agent:

`module.exports = Franz => class Skype extends Franz {
  overrideUserAgent() {
    return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136";
  }
};`

**Comment by kikislater** [comment]
New release is coming ?

**Comment by yermulnik** [comment]
@q4z1 That worked, Kai! Thanks a bunch.

**Comment by mitelg** [comment]
@q4z1 worked for me, too! thanks a lot

**Comment by yermulnik** [comment]
Hmm, wondering if this is related but after fixing Franz I've got all of my Skype chats outdated: it shows no new messages since ~1 month ago. Anyone experiencing this as well?

**Comment by gmauro** [comment]
> Hmm, wondering if this is related but after fixing Franz I've got all of my Skype chats outdated: it shows no new messages since ~1 month ago. Anyone experiencing this as well?

the same here. Ubuntu 18.10, Franz 5.0.0

**Comment by kikislater** [comment]
> @yermulnik: replacing chrome version ain't enough - better use the complete Microsoft Edge User agent:
> 
> `module.exports = Franz => class Skype extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };`

Nice, it works !

**Comment by cristianrcv** [comment]
> @yermulnik: replacing chrome version ain't enough - better use the complete Microsoft Edge User agent:
> 
> `module.exports = Franz => class Skype extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };`

Thank you for the quick patch! It worked for me as well in OpenSUSE Leap 15.0, Franz 5.0.0. 

Just to clarify, you should edit the file `~/.config/Franz/recipes/skype/index.js` and replace the module.exports line by the one provided here. Guess you guys are more into Franz than me but I had to look for it :(

**Comment by cristianrcv** [comment]
> Hmm, wondering if this is related but after fixing Franz I've got all of my Skype chats outdated: it shows no new messages since ~1 month ago. Anyone experiencing this as well?

Same here. OpenSUSE Leap 15.0, Franz 5.0.0.

**Comment by q4z1** [comment]
> Hmm, wondering if this is related but after fixing Franz I've got all of my Skype chats outdated: it shows no new messages since ~1 month ago. Anyone experiencing this as well?

I stumbled upon Franz last night because my web.skype didn't work anymore with Chrome & Chromium on Linux Mint 19 - same error with the "compatible browser". My skype chatlog on my "new" Franz setup  is up2date though. Maybe try to completely remove and re-install the service?

**Comment by cristianrcv** [comment]
> > Hmm, wondering if this is related but after fixing Franz I've got all of my Skype chats outdated: it shows no new messages since ~1 month ago. Anyone experiencing this as well?
> 
> I stumbled upon Franz last night because my web.skype didn't work anymore with Chrome & Chromium on Linux Mint 19 - same error with the "compatible browser". My skype chatlog on my "new" Franz setup is up2date though. Maybe try to completely remove and re-install the service?

That worked for me :dancer:

**Comment by premkolindala** [comment]
What is user agent using is v5.0.1 for skype?

**Comment by premkolindala** [comment]
@q4z1 "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136" this user agent is not working in mac os

**Comment by bittner** [comment]
My `recipes/skype/index.js` looks like this, and I get just a blank page:
```javascript
"use strict";

module.exports = Franz => class Messenger extends Franz {
  overrideUserAgent() {
    return window.navigator.userAgent.replace(/(Franz|Electron)([^\s]+\s)/g, '');
  }

};
```
Looks like that approach is no longer working.

The agent override using Edge (as suggested above) at least gets Skype start loading, but in the end also shows a blank screen. I even tried to use an up-to-date agent string from an actual Edge on a Windows desktop, but no change, still broken:
```javascript
module.exports = Franz => class Skype extends Franz {
  overrideUserAgent() {
    return "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362";
  }
};
```
Any hints on how to get that working again?

**Comment by q4z1** [comment]
@bittner: This is usually a temporrary issue with skype. Try using the latest chrome or chromium User-Agent.
Regards.

**Comment by matteomelotti** [comment]
on Franz 5.4.0 Gmail complains regarding the browser version.
