### ISSUE TITLE
Franz main windows shows nothing after installing on Windows 7

### ISSUE THREAD

**Issue by robcsi** [meetfranz/franz#1286]
I've installed latest version on Windows 7 and the main window shows nothing, it's just empty blue.
![mi_a_franz](https://user-images.githubusercontent.com/5070886/52838862-bc445f00-30fc-11e9-944f-1f72f29bdce1.jpg)

I need to mention that I'm behind a proxy, which is not yet implemented, if I'm correct (although I see a proxy.json file in the %appdata%/franz/config directory...).  It workd fine on my Ubuntu machine, which is not behind proxy and on a different network.

I've also tried about 5 previous versions, but the same issue happens.

Is Windows 7 not supported? Shouldn't it present a message that proxy is not yet supported in such cases?
What can I do?

Thanks

**Comment by sanderdias699** [comment]
I've the same problem too... I'm use Win10... any solve?

**Comment by cridasua** [comment]
You may wanna try deleting the files suggested on #1262, uninstalling Franz then deleting the files and installing it again fixed it for me.

**Comment by robcsi** [comment]
It didn't solve it for me. The same thing happens.

I didn't have the last directory, which is mentioned in the other bug, so that is a difference, but if I guess if it's not there, it doesn't hurt...
