### ISSUE TITLE
Franz always chrashes without any error message 

### ISSUE THREAD

**Issue by Kpunkt10243** [meetfranz/franz#129]
Using Version 5.0.0-beta.11 (5.0.0-beta.11.135) on OS X El Capitan Version 10.11.6 and Franz always (every few minutes) crashes mostly while not using it. I don't get any error message or notification. Just realizing it when I want to check something and then see it's not running anymore. 

Really love the app, hope it will be more stable soonish. Thanks for your great work!

**Comment by adlk** [comment]
Huh.. Need to find an old macbook with 10.11 to figure out what's the issue. 
When you delete all services. Maybe do a restart in between, is it still crashing?

**Comment by adlk** [comment]
Duplicate of #70
