### ISSUE TITLE
Microsoft Teams no longer supported on Version 5

### ISSUE THREAD

**Issue by PaintrockConsulting** [meetfranz/franz#1292]
**Describe the bug**
Launching Microsoft Teams channels yields the message "The page cannot be displayed because an internal server error has occurred."

**To Reproduce**
(Prerequisite - have Microsoft Teams established as a Service)
1.  Click on the Teams channel/logo
2.  View error message. 

**Expected behavior**
Display of my Teams chats. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20844514/52966990-efd5f200-3365-11e9-9fbc-66eb073f5104.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by MichaelDemeyer** [comment]
It was a Microsoft Team server issue. Not Franz related

**Comment by riclund** [comment]
Yes, Teams is working fine for me on 5.0 across two different tabs/tenants.

**Comment by PaintrockConsulting** [comment]
Thanks for the feedback - Teams was working fine for me, but I use Franz so I don't have to keep signing in and out of multiple Teams.  It was just not working on Franz but has been resolved.
