### ISSUE TITLE
Support Zulip hosted Instance.

### ISSUE THREAD

**Issue by gauthamzz** [meetfranz/franz#1295]
Zulip has a hosted instance, it would be great if you support it. Since slack already has that, it should be possible with free tier i hope.

zulipchat.com is the URL for hosted instances

eg: [hackinthenorth.zulipchat.com](https://hackinthenorth.zulipchat.com) and [anna.zulipchat.com
](https://anna.zulipchat.com)
![screenshot from 2019-02-20 12-33-21](https://user-images.githubusercontent.com/12110844/53089241-4846f400-350c-11e9-8729-07e48a487b2a.png)

**Comment by Alex-Mann** [comment]
Is there anyone who can provide an update on what is needed to support this?

**Comment by gauthamzz** [comment]
Cc: @hackerkid

**Comment by timabbott** [comment]
Also https://github.com/adambirds/recipe-zulip has a few bugs that I'd be happy to help fix; I'm not sure what the right way to get that integrated, though, since @adambirds seems inactive.
