### ISSUE TITLE
Cisco Spark crashes on receipt of message

### ISSUE THREAD

**Issue by harrytouche** [meetfranz/franz#1296]
**Describe the bug**
When I receive a message in Cisco Spark / WebEx Teams, the service crashes, forcing me to refresh

**To Reproduce**
1. Have Cisco Spark as a service in Franz
2. Ask a colleague to send you a message
3. The attached screen is seen as soon as the message is received

**Expected behavior**
When a message is received, the service does not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/28261887/53099383-97495500-351d-11e9-8c06-47bed0008415.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Franz 5.0.0 (not Beta)

**Comment by PetarMetodiev** [comment]
I am having the exact same problem.
- OS: macOS 10.14.3 mojave

**Comment by hyetech-git** [comment]
Same issue here.  Webex teams is basically unusable. 

Windows 10 x64
Franz 5.3.1

**Comment by martinspudich** [comment]
I have same issue with Webex Teams. I can confirm it's unusable. It's possible to solve this issue, please. I'm using Webex Teams on a daily basis.

Ubuntu 18.04
