### ISSUE TITLE
Upgrade form broken on the Franz site?

### ISSUE THREAD

**Issue by RicLund** [meetfranz/franz#1297]
_I know this is not specifically the app itself but I can't see how to get help with this..._

When I try to complete the [subscribe form](https://meetfranz.com/user/subscribe) the Upgrade button at the bottom just does nothing - page is broken perhaps? I've tried filling every field, tried PayPal and credit card payment methods, tried incognito mode and a different browser but nothing. Should I be able to upgrade or is the product dead/having issues?

**Comment by adlk** [comment]
Fixed!
