### ISSUE TITLE
Cmd-option + left/right are broken after latest upgrade (5.0)

### ISSUE THREAD

**Issue by tnrich** [meetfranz/franz#1298]
**Describe the bug**
Hitting Cmd-option + left/right no longer moves the active tab up or down.

**To Reproduce**
1. Open franz with multiple tabs
2. Hit cmd+option+left 
3. nothing happens..

**Expected behavior**
It should work like it did before the upgrade

**Desktop (please complete the following information):**
 - OS: mac OSX
 - Browser chrome
 - Version 72.0.3626.109

**Comment by BrandonMorr** [comment]
+1, also experiencing this issue on MacOS Mojave 10.14.3 (Franz 5.0.0 Release 4.0.4 / Darwin / x64)
