### ISSUE TITLE
Share with Franz

### ISSUE THREAD

**Issue by SergioSGil** [meetfranz/franz#13]
Would be a nice feature: Share with Franz on MacOS 
![captura de pantalla 2017-10-18 a las 11 19 18](https://user-images.githubusercontent.com/3636232/31710767-4af36262-b3f6-11e7-8ac2-74d3579c5cef.png)

**Comment by adlk** [comment]
Well this would be an awesome feature but it would require to interact deeper with the services as we don't access anything else than the services notification count.

I'm not trying to saying no but at the moment I don't see a solution.
I'll closing this issue for now and tag it with "not feasible" to revisit later.
