### ISSUE TITLE
Sign-in does not seem to work

### ISSUE THREAD

**Issue by cbrendel82** [meetfranz/franz#130]
Would expect to proceed to next screen upon clicking "Sign in", but nothing happens.

Console shows the following output:

ServerApi.js:40 POST https://api.franzinfra.com/v1/auth/login 400 (Bad Request)
login @ ServerApi.js:40
login @ UserApi.js:10
_promise.Promise @ Request.js:44
execute @ Request.js:43
_login @ UserStore.js:125
executeAction @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:915
res @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:906
action.listeners.forEach.listener @ actions.js:14
action.notify.params @ actions.js:14
action @ actions.js:9
onSuccess @ Login.js:94
exec @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx-react-form/lib/shared/Actions…:140
(anonymous) @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx-react-form/lib/shared/Actions…:150
UserStore.js:130 Uncaught (in promise) Response {type: "cors", url: "https://api.franzinfra.com/v1/auth/login", redirected: false, status: 400, ok: false…}body: (...)bodyUsed: trueheaders: Headersok: falseredirected: falsestatus: 400statusText: "Bad Request"type: "cors"url: "https://api.franzinfra.com/v1/auth/login"__proto__: Response
_login @ UserStore.js:130

**Comment by adlk** [comment]
Thanks for reporting this.
Can you please send me a message in [slack](http://slack.franz.im) to @ stefan or an email to stefan@adlk.io with the email you have signed up.
