### ISSUE TITLE
"Show Franz" and clicking on notifications should unminimize window on Linux

### ISSUE THREAD

**Issue by skoruppa** [meetfranz/franz#1300]
**Describe the bug**
When you receive a notification in Linux (Ubuntu 18.04) for a new message and main window is minimized, clicking on that new message should unminimize Franz and show the new message in the relevant application.

Similarly, when Franz's window is minimized clicking on "Show Franz" in systray should bring its window to the front  

**To Reproduce**
1. Minimize Franz's window
2. Wait for new message
3. Click on the notification 
4. Nothing happens

or 

1. Minimize Franz's window
2. Click Franz's tray icon and select "**Show Franz**"
3. Nothing happens

**Expected behavior**
Window should be unminimized and brought to the front. When window is not minimized but not on the front, it should be brought to the front.
Everything works as expected when window is closed to systray 

**Desktop:**
 - OS: Ubuntu 18.04.2 LTS
 - Version 5.0.0 
 - Release: 4.0.4 / linux / x64

**Additional context**
I don't know if this is related but when Franz is closed to systray clicking on Franz icon in dock (so from system perspective, running *_franz_* command again, should behave as "**Show Franz**" action from systray. Right now, nothing happens

**Comment by Gaboris** [comment]
It's the same for me on Win7 x64 with all major browsers installed, but Firefox being default in case that's important.

**Comment by Gaboris** [comment]
It's the same for me on Win7x64 in the case of the notifications. Not sure if all services have this problem since I think it worked at some point in the past, but Discord and IRCCloud definitely doesn't work  right now.

**Comment by skoruppa** [comment]
@Gaboris I'm not really a programmer but I have tried to fix this by myself ;) You can check my pull request above. My brief tests shows that everything behaves now exactly as I wanted (at least on Ubuntu). Would be nice if you could check my version on Windows

**Comment by Gaboris** [comment]
@skoruppa I looked at the code and although I code a lot my web developer work doesn't involve much windows side interactions so I don't know if that fixes the problem or not, but I'm looking forward to it. :)

**Comment by fquinner** [comment]
@skoruppa Thanks this has been annoying me for ages

**Comment by jerry1970** [comment]
Same here: the thing I use the most (dozens of times per day!) is to click the tray icon to show/hide the main window.

I switched to Rambox because they had this feature (click to show/hide, right-clich to show menu) but they removed it from the latest version so now I am hoping to go back to Franz, but this is not helping.

**Comment by skoruppa** [comment]
@jerry1970 My pull request is already merged with main branch so it should be fixed with next release. If you want to have this fixed asap you can compile code by yourself ;)
