### ISSUE TITLE
Messenger constantly reloading and slow

### ISSUE THREAD

**Issue by mamash** [meetfranz/franz#1301]
For the past two weeks or so, the FB Messenger service has been annoyingly slow for me. When switching between chats, the service seems to be reloading the entire page (i.e. everything, including the chat list on the left), and sometimes doesn't even switch to the new chat after the reload.

Oddly, switching *to the first chat* on top is always instant, but switching to any other always reloads the entire page.

Using 5.0.0-beta.24 on MacOS Mojave.

Other services like Telegram, Discord or LinkedIn seem to behave normally. Messenger behaves normally (fast) at messenger.com in Safari.

Not sure if related to #1277 or #24, I don't see Franz pegging the CPU much.

**Comment by mamash** [comment]
Turns out this was likely caused by about 2 GB of cache used by Franz. Clearing out the cache in Settings make Messenger (reasonably) quick again.

It's a little disturbing how the cache got so big with no control, and how it affected performance.

**Comment by AnthoPakPak** [comment]
Had the same issue, and clearing out the cache (2.5GB in my case) also solved the issue. Thanks!

**Comment by deathemperor** [comment]
confirmed this still exists.

**Comment by geoffguillain** [comment]
Same issue using Version 5.3.3 on Mac OS Catalina
The cache was around 2GB. Clearing out the cache solved the issue.
