### ISSUE TITLE
Hangouts Chat Wasm exception likely prevents darkmode

### ISSUE THREAD

**Issue by cohoe** [meetfranz/franz#1303]
**Describe the bug**
A Wasm exception surrounding the hunspell.js module is likely blocking the injection of `darkmode.css`. Similar to #1223 I suspect that if the exception is gracefully handled injection will proceed as expected.

**To Reproduce**
1. Enable darkmode and install a proper `darkmode.css` for Hangouts Chat
2. Open Google Hangouts Chat

**Expected behavior**
Custom CSS rendered and no Wasm exceptions in the service developer tools

**Screenshots**
![exception](https://user-images.githubusercontent.com/505621/53195785-6aac4080-35e4-11e9-8a56-bed58ac95417.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Franz
 - Version 5.0.0-beta.24

**Additional context**
I am not at all certain that the wasm exception is really the blocker of the darkmode CSS. But it seems very similar to the other bug linked above that I was able to inject a workaround to.

This occurs even with spell-checking disabled in Franz.

**Comment by MarcoMartins86** [comment]
Hey not sure if you're interested in a workaround but I've replaced the electron.asar in "franz\resources" with the one from https://github.com/paveyry/better-hangoutschat and it worked for Hangouts Chat and I did not notice anything else strange while using Franz at least for now.

**Comment by cohoe** [comment]
@MarcoMartins86 good find!
