### ISSUE TITLE
Notification sounds persisting, despite being disabled

### ISSUE THREAD

**Issue by oranmornz** [meetfranz/franz#1307]
Since updating the app yesterday I've found that notification sounds are playing despite being turned off. I've sought out every possible option for this within the app, and the accounts hosted within it, and disabled the notification sounds, however they continue to persist.

I've also disabled the apps notification sounds within OS X's system preferences, and yet they still play.

As I work in audio, this is extremely irritating whilst I'm trying to work, and having to keep the application open to communicate with clients. This is also extremely risky to ones hearing, given that I often have to work with high volume levels for various purposes.

Any assistance in resolving this would be greatly appreciated.

I am using Version 5.0.0 (5.0.0.1136)

**Comment by divyenduz** [comment]
I can also confirm that this is happening with version: `Version 5.0.0-beta.22 (5.0.0-beta.22.1059)`
