### ISSUE TITLE
System tray: 'Show Franz' option in is not working (macOS)

### ISSUE THREAD

**Issue by Novitsh** [meetfranz/franz#131]
On macOS you have an icon of Franz in the task bar. 
Clicking the option 'Show Franz' does not put the application to the foreground.

### Expected Behavior
Clicking the option 'Show Franz' should put the application on the foreground.

### Current Behavior
It seems nothing really happens. Console is also not reporting any errors.

### Screenshots (if appropriate):
![screen shot 2017-10-26 at 10 24 21](https://user-images.githubusercontent.com/5877591/32042452-e155f9da-ba37-11e7-9255-c883d11f789a.png)

### Steps to Reproduce (for bugs)

1. Click the icon
2. Click 'Show Franz'

### Your Environment

* Franz Version used: 5.0.0-beta.11
* Operating System and version: macOS High Sierra (10.13)
MacBook Pro (Retina, 13-inch, Early 2015)
3,1 GHz Intel Core i7
16 GB 1867 MHz DDR3

**Comment by phips28** [comment]
+1

**Comment by adlk** [comment]
Fixed in https://github.com/meetfranz/franz/pull/134
Will be shipped with beta 12
