### ISSUE TITLE
Dark/blank screen after upgrade 

### ISSUE THREAD

**Issue by ichpen** [meetfranz/franz#1310]
**Describe the bug**
Was just offered an upgrade (I assume to v5) and immediately after was greeted by a dark screen (see attached). Same issue after restart and reboot.

The window can be repositioned and maximized but nothing ever shows.

Note I was running a dark skin.

**To Reproduce**
Upgrade

**Expected behavior**
Something to see

**Screenshots**
Attached below

**Desktop (please complete the following information):**
Windows 10 (1809)
Chrome

**Additional context**

![image](https://user-images.githubusercontent.com/5346876/53448021-792f9900-39e4-11e9-8571-64262b4cab10.png)

**Comment by ichpen** [comment]
To top up on this, I've attempted to uninstall/reinstall v5 and get the same issue.

**Comment by awreccan** [comment]
Same here. Upgraded to 5.0.0. I have 8 services, and the app is very laggy on startup. If I'm lucky, 5 out of 8 will load (slowly). The others remain stuck at `Loading <app-name> <spinner>`.

![image](https://user-images.githubusercontent.com/10543509/53508336-80de6300-3af4-11e9-9977-d14432a59b26.png)

**Comment by JustusW** [comment]
Issue here as well, Black screen after update. Any suggestions?

**Comment by JustusW** [comment]
After going to C:\Users\<yourusername>\AppData\Local\franz-updater\pending I found an installer file vor indeed 5.0.0
I manually executed it and this fixed the problem.

**Comment by algopt** [comment]
I had the same problem. All in blue.
So I tried to uninstall FRANZ, removed all FRANZ folders in %APPDATA%  and re-installed it.
Noticed the same problem occurs.
Then I tried to uninstall FRANZ again, and noticed it's actually not uninstalling. And also, found out I still had someone installed in the system version 4.0.4? And when I press Uninstall, both still stay in the Apps & Features.
OS: Windows 10 64 bit

**Comment by JustusW** [comment]
> Then I tried to uninstall FRANZ again, and noticed it's actually not uninstalling. And also, found out I still had somehow installed in the system version 4.0.4? 

Have you tried going to Local\franz-updater\pending and executing the installer there as I did? It fixed the problem for me.

**Comment by ichpen** [comment]
> > Then I tried to uninstall FRANZ again, and noticed it's actually not uninstalling. And also, found out I still had somehow installed in the system version 4.0.4?
> 
> Have you tried going to Local\franz-updater\pending and executing the installer there as I did? It fixed the problem for me.

That actually fixed my issue also. Thanks @JustusW .

Hoping the author can address this pretty serious problem though.

**Comment by algopt** [comment]
> > Then I tried to uninstall FRANZ again, and noticed it's actually not uninstalling. And also, found out I still had somehow installed in the system version 4.0.4?
> 
> Have you tried going to Local\franz-updater\pending and executing the installer there as I did? It fixed the problem for me.

Dont have such folder in C:\Users\USERNAME\AppData\Local

**Comment by awreccan** [comment]
Any updates for MacOS?

**Comment by Stahlwalker** [comment]
I'm getting a black screen the moment I enter my email as it attempts to verify email. MacOS Mojave
