### ISSUE TITLE
Control + Tab shortcut not working anymore

### ISSUE THREAD

**Issue by filipeabperes** [meetfranz/franz#1313]
**Describe the bug**
At least on Mac OS, it used to be possible to switch between services by pressing Control+Tab, which would move down the list on the left onto the next service. For some weeks now (if I recall correctly), this shortcut is not working anymore. This used to be a more convenient way of switching between "neighboring" services than having to press Command+\<number\>. 

I'm not sure if this is a bug or if it was removed on purpose. If this was indeed on purpose, I'd consider bringing it back, since it was one of the most useful keyboard shortcuts.

**To Reproduce**
Simply open a Franz window with more than one service and press Control+Tab. Possibly, compare with a version from last year to see the functional behavior.

**Expected behavior**
Control+Tab should switch to next service.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra
 - Browser: Chrome
 - Version: at least on 5.0.0, but also a few of the previous versions

**Comment by djbotha** [comment]
Experiencing the same issue on Version 5.0.0 (5.0.0.1136) on MacOS Mojave.

**Comment by NeilHanlon** [comment]
Confirmed over on Linux (Debian 9) with 5.0.0

**Comment by rdewolff** [comment]
Same issue with macOS on last version. 

I noticed after a restart of Franz, I could do once a `CMD+OPTION + left arrow` to go to the next service. But right after the service changed, the keyboard shortcut did not work anymore.

**Comment by FG-TUM** [comment]
Apparently commit 6134c1b49f919dd2c578bc490829d68e4d210f4e by @adlk removed the keystroke actions.
Those appear to have been the relevant lines (sorry I have no Idea about js :D ) https://github.com/meetfranz/franz/blob/afb6a91741c4c5ce9ef1e52266223faa35469d8b/src/stores/AppStore.js#L155-L174

**Comment by rdewolff** [comment]
Would be great if someone could restore this feature properly!

**Comment by rdewolff** [comment]
Would be great if someone could restore this feature properly!

**Comment by hutber** [comment]
Seconded. Super sad :(

**Comment by rdewolff** [comment]
I switched to Station app to have this basic functionality.

**Comment by hutber** [comment]
Ah nice, I will use this then.

**Comment by cpazaras** [comment]
Confirmed also on Manjaro Linux (18.04), Franz version 5.0.1 - would indeed be great if we had this basic functionality back again.

**Comment by Foggalong** [comment]
I mean.... this is something I'd still like to see? And it's still a problem for me in the latest Franz version.
 
I'm really not a fan of this trend where the @stale bot closes older bugs / feature requests just because there's no new activity. What else is there to add to this type of issue other than just more and more comments saying "yes we want this"? That type of thing is why :+1: reactions were added but if issues are now just going to be closed if people don't comment it feels like it defeats the point.

**Comment by cpazaras** [comment]
I would also still like to have this again (used to work on linux too). Completely agree with what @Foggalong above said too.
