### ISSUE TITLE
Serious CPU and power draw on Mac OS Mojave

### ISSUE THREAD

**Issue by jamiedarcher** [meetfranz/franz#1317]
Simply having the app open utilises the CPU with multiple Franz Helper Processes running. The app doesn't even need to be in focus it could be minimised. Closing and then reopening the app works to reduce usage slightly but then it ramps backup.

My system fans are going crazy to keep my CPU cool. 
This wasn't happening before a recent update.

CPU Usage
![image](https://user-images.githubusercontent.com/6596910/53700369-3d3c6f80-3dfa-11e9-9a77-ba8f0c60ab68.png)

Energy Impact
![screenshot 2019-03-03 21 24 19](https://user-images.githubusercontent.com/6596910/53700418-cce21e00-3dfa-11e9-8dd3-e29bd2fadcae.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3 (Macbook Pro 13inch Late 2013 - 2.4 Ghz - 16GB Ram)
 - Franz: Version 5.0.0 (5.0.0.1136)

**Comment by rafaljanicki** [comment]
I can confirm the same, it basically makes my Macbook (3.0 Ghz, 16 RAM) sloooow. However, I believe that started to happen after the latest update (5.0.0.1136) as I didn't have such issues before.

**Comment by khimera80** [comment]
Same here, going back to 5.0.0-beta24 fixes this problem.. but then there is the annoying blue band reminding you of a newer version.
Also, I swear I never push the update button in that blue band, yet, after a day or so, the app updates somehow and I have to restore beta24 again.

**Comment by jamiedarcher** [comment]
@rafaljanicki yeah I didn't notice it before the last update either so I'm guessing is something introduced recently I hope it gets fixed soon as I cannot leave it on while using Sketch or Affinity because the system start to grind to a halt

**Comment by marnovo** [comment]
Can confirm the same on my system. And it's very quick to ramp up, can be from seconds to a few minutes until it peaks.

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.3 (MacBook Pro (15-inch, 2018), 2.2 GHz Intel Core i7, 16 GB 2400 MHz DDR4)
- Franz: Version 5.0.0 (5.0.0.1136)
- Services running: WhatsApp (x2), Messenger, Telegram.
- Services deactivated: Discord, Skype, WeChat.

**Comment by sergiughf** [comment]
Same thing happening for me. Could we kindly prioritize this?

My CPU temperature goes from 49°C to 73°C in about 2 seconds as I open Franz. Completely unacceptable on arch. 

**Desktop (please complete the following information):**

- OS: Arch Linux 5.0.0-arch1-1-ARCH (Dell XPS 13" 9550)
- Franz: Version 5.0.0
- Services running: WhatsApp, Messenger, Gmail x2, Slack, Protonmail, Google Calendar

**Comment by khimera80** [comment]
Seems to be OK with 5.0.1-beta1!

**Comment by fluffypony** [comment]
No change with 5.0.1-beta1 for me, the fix I've found is to disable Discord. It also appears that the bulk of the draw is GPU related, not sure if that's indicative of anything other than Discord having a poorly written webapp?

In the screenshot I startup 5.0.1-beta1, then disable every service, and then re-enable every service one at a time except Discord.

<img width="1680" alt="Screenshot 2019-03-21 at 3 13 07 PM" src="https://user-images.githubusercontent.com/1944293/54754418-295f7e80-4bec-11e9-969e-9f56586c11b6.png">

**Comment by so-lost** [comment]
Happening for me aswell on my macbook pro on newest update 5.2.0.1455
Was completely fine before and now with the new update things are going through the roof

**Comment by AtomCollector** [comment]
I can confirm this is STILL an issue! It's so bad that my mac now has screen issues when it gets too hot. As soon as I close down Discord voila, the fan winds down and everything is great again. I'm tempted to use the Discord API to write a "Discord Lite"

**Comment by mvaneijgen** [comment]
I moved to [Hamsket](https://github.com/TheGoddessInari/hamsket) missing some features, but open source and doesn't use all your CPU

**Comment by AtomCollector** [comment]
thank you! will check it out.
