### ISSUE TITLE
Updates don't work in linux

### ISSUE THREAD

**Issue by philb61** [meetfranz/franz#1318]
**Describe the bug**
When checking for updates, nothing happens.  The button stays in "is searching for update" status forever, and, as such, updates are never found.

**To Reproduce**
Go to File -> Settings, scroll down to the bottom, to the "Updates" section.  If the button is enabled and says "Check for updates", click it.  It will change to "Is searching for updates" and never change again, even after restarting.

**Expected behavior**
It should actually check for updates and notify you when there are new versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/468390/53749319-f97a5200-3e5b-11e9-8bf5-14d52cb47f82.png)

**OS/Verssion**
 - Ubuntu 18.10
 - 5.0.0-beta-24, but was also observed in 5.0.0 and 5.0.0-beta-18.

**Comment by micuda** [comment]
Does not work on _5.0.0-beta-17_ also.

**Comment by fabriciopirini** [comment]
Can confirm that the same happens on 5.0.1, using Ubuntu 18.04.2. The same happens if I run it with sudo.

**Comment by JohnMoutafis** [comment]
Same thing happens for version 5.2.0 in Linux Mint 19.1 Cinnamon (Cinnamon version: 4.0.10) and current kernel: 4.15.0-65.
