### ISSUE TITLE
[Mac] [Gmail] Spellchecking is not working

### ISSUE THREAD

**Issue by wkoncki** [meetfranz/franz#1319]
**Describe the bug**
No matter what language I select, spellchecker is not working. I don't get words underlined on spelling mistakes.

**To Reproduce**
1. Open new message panel or message reply
2. Make a typo
3. Notice it's not underlined 
4. Try not to cry
5. Cry a lot

**Expected behavior**
Words should get red underlines on spelling mistakes

**Screenshots**
Gmail
![screen shot 2019-03-05 at 3 59 01 pm](https://user-images.githubusercontent.com/9073427/53814651-48111480-3f60-11e9-80d8-b3b2d2586ef5.png)
Messenger (working)
![screen shot 2019-03-05 at 4 06 07 pm](https://user-images.githubusercontent.com/9073427/53814783-9cb48f80-3f60-11e9-9ee9-956854914e02.png)

**Desktop**
 - OS: macOS
 - Version 5.0.0

**Comment by wkoncki** [comment]
Small update: messenger is now also not working.

**Comment by apostolisd** [comment]
Greek is also not working 

![grafik](https://user-images.githubusercontent.com/16398125/59089521-a5738380-890a-11e9-80ad-e2eb3e1f14da.png)

**Comment by alacret** [comment]
Any news on this?
