### ISSUE TITLE
Blue Splash stays when opening Franz on WIN7

### ISSUE THREAD

**Issue by hoodpablo** [meetfranz/franz#1322]
**Describe the bug**
Blue Splash on opening on Windows 7

**To Reproduce**
1. Go to 'Shortcut and open Franz'
2. Blue(lightblue) splash screen apears and stays

**Expected behavior**
Franz should open normally

**Screenshots**
![image](https://user-images.githubusercontent.com/8660094/53879717-e7c8b400-3fed-11e9-9de8-196f8e3c9585.png)

 - OS: Windows 7

**Comment by AgusNahas** [comment]
I'm having the same issue right now in Win10. Any clues?
