### ISSUE TITLE
Franz keeps logging out

### ISSUE THREAD

**Issue by dzigner** [meetfranz/franz#1324]
### Expected Behavior

Franz should keep logged even after quitting Windows

### Current Behavior

Everytime I login to my laptop, I have to login to Franz also. This issue started from yesterday. I cannot find any settings for "keep logged in".

### Steps to Reproduce (for bugs)

1. Login to Franz
2. Shut down laptop (Windows 10)
3. Switch on laptop
4. Franz starts, but have to login to my account.

### Your Environment

* Franz Version used: **franz 5.0.0**
* Operating System and version: **Windows 10 version 1803**

**Comment by frankamente** [comment]
I'm having the same issue.
Checked with same result previous version.

**Comment by frankamente** [comment]
I just "solved" in my local deleting all Franz folder.
What I did:

1. Upgrade Franz to last version.
2. Go to C:\Users\"Your User"\AppData\Roaming\Franz
3. Delete all files contained in that folder.
4. Open Franz and log in.

Hope that works for you too.

**Comment by Bo0sted** [comment]
This issue is also occurring for me. It seems to happen when I connect/disconnect from a VPN. Then eventually it breaks entirely. Frustrating
