### ISSUE TITLE
Error: ERR_CERT_AUTHORITY_INVALID 

### ISSUE THREAD

**Issue by gouthamkumaran** [meetfranz/franz#1327]
** How to load a custom or invalid SSL page in Franz**

First of all sorry if this is a easy one, i'm kind of a newbie here.

Thanks in advance for your help.

I'm trying to create a page that is kinda new and doesn't have a valid SSL certificate as a new plugin and want to know how and where to set rejectUnauthorized as false in Franz recepie for only my particular recepie.

**Comment by birduser** [comment]
Any news about this problem?
Tried to add a self-signed service, but even with this mentioned "trick" (https://github.com/meetfranz/franz/issues/1479#issuecomment-532228031) #1479 it is not possible to load your custom service.

Thanks, Markus

**Comment by birduser** [comment]
Find a solution for this problem:

Windows: Start certmgr.msc
> CA Root certificates > certificates > import:

Now import your CA-Root and your CA-Intermediate certificate.

Apply https://github.com/meetfranz/franz/issues/1479#issuecomment-532228031 to your custom-website recipe in folder C:\Users\>username>\AppData\Roaming\Franz\recipes\franz-custom-website.

index.js (modified) must look like this:
```
"use strict";
	
	module.exports = Franz => class CustomWebsite extends Franz {
	
	
	};
```
Restart Franz and test again!

Good luck!!!

**Comment by BananaAcid** [comment]
Sorry. Had no luck - since there is no CA Root certificate available to be imported on the test service I am working on.
