### ISSUE TITLE
Hide icon in menu bar (macOS)

### ISSUE THREAD

**Issue by noirrak** [meetfranz/franz#133]
Add possibility to hide icon from the menu bar (macOS).

**Comment by dannyqiu** [comment]
This can already be done in the preferences:
<img width="269" alt="screen shot 2017-10-26 at 10 41 14 am" src="https://user-images.githubusercontent.com/1170755/32059471-3e6c6832-ba3a-11e7-9958-6a25ae1e80af.png">

**Comment by AllanLRH** [comment]
Would be nice if Franz was also hidden from the Dock and the Task Switcher, when it's minimized to the system tray. IMHO it's the main reason for why it should be in the system tray / manu bar.

**Comment by adlk** [comment]
@AllanLRH you can always open a feature request for that ;)
