### ISSUE TITLE
Telegram not working

### ISSUE THREAD

**Issue by samuelswiftt** [meetfranz/franz#1332]
**Describe the bug**
Its a blank screen when I click into telegram tab, nothing is loaded. 

**To Reproduce**
1. Start Franz
2. Enable Telegram service
3. Click into the tab
4. Blank screen
5. After refresh service and also the whole Franz app, problem persists. 

**Expected behavior**
To go into Telegram webpage where it asks for my phone number to log in

**Screenshots**
![Screenshot (12)](https://user-images.githubusercontent.com/48377642/54068103-99344780-4283-11e9-86e8-6c5fd5540af8.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [72.0.3626.121]

**Smartphone (please complete the following information):**
 - Device: [Oneplus 2]
 - OS: [OxygenOS 3.6.1; Android 6.0.1]
 - Browser [Google Chrome]
 - Version [72.0.3626.121]

**Additional context**
I reinstalled Franz right before this because it wasn't working out of sudden. This is another problem, it crashes after using for a while, but my solution is to wipe out all data and reinstall again.

**Comment by Bryanpedini** [comment]
I have a kindly similar problem... actually I don't get to the blank screen at all, Telegram just makes Franz to crash completely after saying "Oh no, Telegram was not loaded correctly", and after 10 seconds you're sure to lose your current worktime until Franz reopens itself.
You are then able to proceed your work as intended, until of course you misclick again on any Telegram tab, causing Franz to crash again after those 10 seconds...
I have basically the same specs as the OP Author except that I use FF as my main browser and I have a Xiaomi Mi 7 phone also with FF as main browser.

**Comment by Derr22** [comment]
**Describe the bug**
Telegram service is not working at all. Proxy didn`t help me.

**To Reproduce**
Steps to reproduce the behavior:
1. Start Franz
2. Enable Telegram service
3. Click into the tab
4. See error


**Expected behavior**
Working Telegram  =)


**Screenshots**
![изображение](https://user-images.githubusercontent.com/35798877/62684771-10ecd680-b9ca-11e9-9315-d2baa721147f.png)


**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 76.0.3809.100

**Comment by anilkrao** [comment]
I still see this issue on Franz on Mac Book Pro MacOS 10.13.6 High Sierra. Franz is an aggregator varied services. When Telegram is added to Franz, it shows ERR_CONNECTION_CLOSED

**Comment by martinezpenya** [comment]
> **Describe the bug**
> Its a blank screen when I click into telegram tab, nothing is loaded.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Start Franz
> 
>     2. Enable Telegram service
> 
>     3. Click into the tab
> 
>     4. Blank screen
> 
>     5. After refresh service and also the whole Franz app, problem persists.
> 
> 
> **Expected behavior**
> To go into Telegram webpage where it asks for my phone number to log in
> 
> **Screenshots**
> ![Screenshot (12)](https://user-images.githubusercontent.com/48377642/54068103-99344780-4283-11e9-86e8-6c5fd5540af8.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [Windows 10]
> 
>     * Browser [Google Chrome]
> 
>     * Version [72.0.3626.121]
> 
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: [Oneplus 2]
> 
>     * OS: [OxygenOS 3.6.1; Android 6.0.1]
> 
>     * Browser [Google Chrome]
> 
>     * Version [72.0.3626.121]
> 
> 
> **Additional context**
> I reinstalled Franz right before this because it wasn't working out of sudden. This is another problem, it crashes after using for a while, but my solution is to wipe out all data and reinstall again.

Same to me in Kubuntu 20.04.

**Comment by honzap** [comment]
It stopped working after some service update for me too. I removed that service and add it again. After such a time (I also tried to reload the service more times and open already developer tools to debug it) it's loaded also with some new look-and-feel.
