### ISSUE TITLE
Outlook doesn’t stay logged in (but remembers password)

### ISSUE THREAD

**Issue by lukefisklennon** [meetfranz/franz#1343]
**Describe the bug**
Outlook doesn’t keep me logged in. Every time I open Franz afresh, I have to enter my email into the login form, but it does remember my password.

**To Reproduce**
1. Add the Outlook service
2. Enter your login details
3. Close Franz
4. Open Franz
5. Outlook requires login again

**Expected behavior**
It should keep me logged in even when I close Franz.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Franz Version: 5.0.0
 - Franz Release: 4.0.4 / win32 / x64

**Comment by dcferreira** [comment]
This issue still persists on Ubuntu 18.04, Franz 5.1.0.
However, "Office 365 - Outlook" doesn't have this problem, try using that one if possible.
