### ISSUE TITLE
Ctrl+Tab does not work when focus is on a service.

### ISSUE THREAD

**Issue by AxlLind** [meetfranz/franz#1348]
**Describe the bug**
I just updated Franz to the latest version and switching between services via `Ctrl+Tab` / `Ctrl+Shift+Tab` no longer works unless I click out of the service, i.e only if I click on the services bar first.

**To Reproduce**
1. Click on a service.
2. Press `Ctrl+Tab` and see that nothing happends
3. Click on the bar (i.e where the list of services are).
4. Press `Ctrl+Tab` and see that service switches.

**Expected behavior**
To be able to switch between services with `Ctrl+Tab` seamlessly.

**Desktop (please complete the following information):**
 - OS: macOS mojave v10.14
 - Version: Franz 5.0.0

**Comment by AxlLind** [comment]
FYI, got the same problem on windows 10.

**Comment by AxlLind** [comment]
Appears to be duplicate of #1298 and #1313. It hasn't been fixed for over a month and this is making Franz really annoying to use for me. Will close this issue but please prioritize this..

**Comment by malammar** [comment]
Since both Rambox and Franz use Electron, this looks like the same issue as:

https://github.com/ramboxapp/community-edition/pull/2138
