### ISSUE TITLE
Unable to open links in google plus dropdown menu

### ISSUE THREAD

**Issue by alecive** [meetfranz/franz#135]
Hi,

opening links in franz usually works fine. My only problem is when I use the top-right dropdown menu in gmail to read my google plus notifications (see pic below):

![screenshot_2017](https://user-images.githubusercontent.com/4378663/32052623-daf321a0-ba26-11e7-95ed-b816ab4888d3.png)

If I click a link on there (e.g. the launchpad link), nothing happens but I get this output from the terminal:

```
[alecive@malakim]$ franz
xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
```

It seems like `xdg-open` is not properly called?

**Comment by adlk** [comment]
Might be related to https://github.com/electron/electron/issues/1348
We could replace `shell.openExternal` with `xdg-open 'https://foo'` is this working on linux across all platforms?

**Comment by alecive** [comment]
AFAIK yes, `xdg-open` should be  universal.

The issue you linked is interesting. But again, if `shell.openExternal` works most of the time, why it does not work on that specific instance? Are you using a different command to e.g. open a link from a gmail email or a slack comment? Because those work flawlessly!

I am also noticing other inconsistencies by the way. For example, if I am trying to open a link with the Office 365 recipe, this creates a new `franz` window with the link opened there, whereas all the other recipes open a `firefox` tab as it should be.

**Comment by haraldox** [comment]
@alecive here is @BrianGilbert's workaround: right-click and select "Open Link"
