### ISSUE TITLE
Memory Leak on Linux Mint

### ISSUE THREAD

**Issue by TobiasSchaffner** [meetfranz/franz#1351]
**Description**
Franz is eating up all the Ram after a short period of time. This seems to be unrelated to the the number of services running and which services are active.
Never the less at the moment I have WhatsApp, Slack, Skype and Telegram configured.

After about an hour this raises to 12 GBytes. (My maximum memory including swap)

I assume that this is related to #1070 and does not only affect Linux Mint.

**To Reproduce**
Configured:  WhatsApp, Slack, Skype and Telegram
Monitored in htop.

**Desktop (please complete the following information):**
OS: Linux Mint 19.1 Cinnamon

Franz Version 5.0.0
Franz Release: 4.0.4 / linux / x64

**Comment by adlk** [comment]
Is it still happening with Franz 5.0.1-beta.1
https://github.com/meetfranz/franz/releases

**Comment by TobiasSchaffner** [comment]
Thanks for your reply. I will test the beta this evening.

**Comment by STMurph6409** [comment]
A friend was reporting issues with this as well on a Windows machine. After playing around and testing a little, it seems like the culprit might be tied to Slack.

Memory use was much more modest and seemed to be stable once he unlinked his Slack chats.

**Comment by TobiasSchaffner** [comment]
I ran into the same issues with the new version today. Can confirm this problem again with 5.0.1 beta 1

**Comment by benjaminvdb** [comment]
Same problem here on MacBook Pro 8GB RAM running macOS 10.14.4. Franz 5.1.0 beta 1 uses 2.20GB of RAM after having been restarted today.

<img width="557" alt="Screenshot 2019-04-17 at 16 02 18" src="https://user-images.githubusercontent.com/8875786/56293917-4d9a7680-612a-11e9-9e7c-4f8270ef4011.png">

**Comment by maxiwoj** [comment]
Same here on MacBook Pro 16GB with macOS 10.14.4. Franz (Version 5.1.0 (5.1.0.1334)) also taking a large amount of virtual memory:

![image](https://user-images.githubusercontent.com/18395874/58876500-93a59c80-86ce-11e9-9272-4a5a680036c8.png)

**Comment by bvdlingen** [comment]
> Is it still happening with Franz 5.0.1-beta.1?
> https://github.com/meetfranz/franz/releases

same issue here on linux, also with the latest beta

**Comment by miku86** [comment]
> > Is it still happening with Franz 5.0.1-beta.1?
> > [meetfranz/franz/releases](https://github.com/meetfranz/franz/releases)
> 
> same issue here on linux, also with the latest beta

Instead of flooding multiple issues,
it would be great,
if you would fill out a proper issue report.

Hardware, operating system, version of Franz, how to reproduce your issue, how many opened Franz services etc.

**Comment by typoworx-de** [comment]
I noticed on my Ubuntu 16.04 Franz is consuming about 12G Virtual Memory. Does this also have to do with this memory leak?
