### ISSUE TITLE
A way to organize services into profiles and toggle

### ISSUE THREAD

**Issue by bartier** [meetfranz/franz#1352]
**Is your feature request related to a problem? Please describe.**
There is no way to organize my left bar in diferent profiles, for example:
I would like to create a profile to all my services I use in my work and another profile to my personal life services.
![image](https://user-images.githubusercontent.com/18057391/54890301-7ca12d80-4e87-11e9-8db5-f6a5b2ce48c6.png)
In the image above there are services related to my personal life (last 5 icons) AND my work (first 4 icons).

**Describe the solution you'd like**
A way to toggle into profiles, so I can hide services when I am working.
(a separator like related in #243 could be a way to separate but not to hide in fact)

**Describe alternatives you've considered**
I considered add all services into together like the image above (Franz only way I guess to organize)

Does this feature makes sense to Franz? =p Actually I am new to Franz (using since Feb/19)...Just trying to help =)

Thanks!

**Comment by adlk** [comment]
This is coming soon ;)
I'm closing this as we're already internally testing this feature.
