### ISSUE TITLE
*urgent* app doesn't work after update

### ISSUE THREAD

**Issue by Yvaine8** [meetfranz/franz#1355]
after automatically updating to 5.0.1, franz restarted as a blank screen.
restarting franz doesn't fix the issue, restarting the computer doesn't fix the issue.

screenshot:
![image](https://user-images.githubusercontent.com/13449415/54955169-3adeb880-4f55-11e9-8e7f-6b685ebd688b.png)

 - OS: windows 10
 - Browser: chrome

**Comment by alexgutiar** [comment]
The same happens to me

**Comment by alexgutiar** [comment]
yo lo resolví  borrando todas las carpetas de franz y volviendo a instalar 
![1](https://user-images.githubusercontent.com/5580225/54974160-a5ddbe80-4f58-11e9-8d9a-15e8380525a7.PNG)

**Comment by PlaceboPRS** [comment]
I've had problems with the last two updates, as soon as I click "update" in Franz it then shows: 

![Franz](https://user-images.githubusercontent.com/23120453/54983037-4dd0a780-4fac-11e9-8b02-62e1e5126c1f.jpg)

Uninstalling from the control panel doesn't fix it, so I delete all the files I can find, then the installer runs through, vanishes, no Franz.

**Comment by darrenldz** [comment]
Yeah doesn't work for me either. (Windows 10)

Starts "Franz", nothing happens, no process in task manager.

**Comment by Nincodedo** [comment]
I reinstalled Franz but the login doesn't work. After I hit sign in, it just does nothing. I also can't sign in on the website.

**Comment by filip-van-hoeckel** [comment]
Same here. Uninstalling and reinstalling the application does not solve it. Neither does removing the /whatsapp/ folder. Is there a way to rollback to a previous (working) version?
