### ISSUE TITLE
Ads in outlook

### ISSUE THREAD

**Issue by Elghat** [meetfranz/franz#1356]
**Is your feature request related to a problem? Please describe.**
Getting ads when i use outlook in Franz
When i'm using it in my eb broxser i have an addon to block ads 
And that's frustrating me to get this ads on franz outlook service

**Describe the solution you'd like**
add a "adblock" adon like just for outlook if possible or if there already is a solution could you give me it ?

**Comment by alete89** [comment]
same with gmail if you use tabs. Usually, social and promotion tabs have ads if you are not using an adblocker.

**Comment by eaorak** [comment]
I was gonna ask the same question. It's very annoying to have ads while you don't have them on the browser when you use an ad blocker like uBlock. Would it be possible to use/integrate browser plugins within Franz?

**Comment by davidalb97** [comment]
Why should an issue be closed for inactivity when it hasn't be resolved...
