### ISSUE TITLE
Android messages URL has changed

### ISSUE THREAD

**Issue by brandonh-msft** [meetfranz/franz#1357]
![image](https://user-images.githubusercontent.com/20270743/55033677-ebd66900-4fd0-11e9-8184-f78ff773db13.png)

**Comment by 8bitgentleman** [comment]
Commit [9aa4996](https://github.com/dweinber/franz-recipe-android-messages/commit/9aa499683ff0acba2325c06223c82060503ae1f3) to the android-messages recipe should fix this. I don't know when that fix will be available to us though

**Comment by brandonh-msft** [comment]
boomski!
