### ISSUE TITLE
Command+W on macOS

### ISSUE THREAD

**Issue by mvc3131** [meetfranz/franz#136]
Previously, when we hit command+w on macOS, the franz used to close but the app used to run in background. But now the app is completely quit. 

### Expected Behavior
When a user hits command+W the app should close yet work in background. 
When a user hits command+Q the app should completely close. 

### Current Behavior
When a user hits command+W the app is completely quit. 

### Context
While in middle of some work, if I'm chatting with someone, I use Franz in one of my desktop tabs. This makes it really easy to switch between my desktops and work simultaneously while chatting. Command+W used to essentially minimise the app instead of closing it. 

### Your Environment
Macbook Pro - 15" Retina.
Franz-5.0.0-beta.10
macOS Sierra
Version: 10.12.6

**Comment by dannyqiu** [comment]
This can be set in the preferences:
<img width="422" alt="screen shot 2017-10-26 at 10 48 12 am" src="https://user-images.githubusercontent.com/1170755/32059809-33faedbe-ba3b-11e7-91cc-1f8362b69137.png">
