### ISSUE TITLE
App Delay Even After Premium

### ISSUE THREAD

**Issue by andrejohansson** [meetfranz/franz#1368]
**Describe the bug**
I just paid one year for Franz premium. But even after a restart of the program I still get "App Delays".

**To Reproduce**
1. Download and install Franz
1. Create account
1. Run evaluation for a couple of days
1. Pay premium
1. Quit Franz by right clicking the systray icon
1. Start Franz again
1. Verify you have premium in settings
1. Continue using Franz

**Expected behavior**
I expected to not be bugged by "App Delay" timers anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/2828428/55185374-83d08000-5194-11e9-98ae-389a4cbbbc70.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 
![image](https://user-images.githubusercontent.com/2828428/55185504-bf6b4a00-5194-11e9-80bd-09f313744f93.png)

**Comment by jasmines** [comment]
The new message icon is not showing correctly: it should be the mustaches icon with a red dot, instead it's showing as the first on top left in this screenshot:

![image](https://user-images.githubusercontent.com/894920/58013506-00c60900-7af7-11e9-8719-a2da318da823.png)

Only flatpak version seems affected.
