### ISSUE TITLE
Tabs to organize apps

### ISSUE THREAD

**Issue by fossett** [meetfranz/franz#1371]
It would be cool to be able to have a tab system on the left-hand side to organize apps. 

Use case, I have 10 apps between work and personal apps. I'd like to have tabs to organize Work apps on one tab, and Personal apps on the other.

Thank you for the great product. I use it for everything!

**Comment by bonki** [comment]
This already exists but is a premium feature (workspaces).

**Comment by oliver-gramberg** [comment]
@adlk Are workspaces the same as/a valid replacement for "categories" as used in the label, "wait for category feature" in meetfranz/plugins? If so, can that label be removed now, and some progress made on submitted recipes? - Also, if there's a label, "help needed", on a recipe, what would that entail?
