### ISSUE TITLE
Sync Google Account

### ISSUE THREAD

**Issue by xerus2000** [meetfranz/franz#1373]
**Is your feature request related to a problem? Please describe.**
For almost all services, I use my Google Account, and on every device I have to log in to my Google Account in every service.

**Describe the solution you'd like**
Attaching a Google Account to my Franz account, which could be used as the default for logging in. Or somehow syncing the login from one tab to another.

**Comment by stephanvierkant** [comment]
I agree this is somewhat inconvenient. I want to use Keep, Calendar and Gmail but I have to login separately. I can imagine that an quick'n'dirty fix for this problem creates security risks and problems if you have multiple Google accounts (personal Gmail, work Calendar for example).

**Comment by PandaWhisperer** [comment]
I have this issue as well. I thought that maybe refreshing the Google Calendar tab after logging into Gmail would do the trick, like it does in Chrome, but that doesn't seem to work here. Does each tab use its own cookie store?

**Comment by xerus2000** [comment]
not stale
