### ISSUE TITLE
Infinite system tray icon in ubuntu

### ISSUE THREAD

**Issue by amir1376irani** [meetfranz/franz#1377]
**Description of bug**
opening many system tray icon instead of just one!

**To reproduce**
1. Open Franz
2. Go to `File` -> `Setting`
3. Open `Setting` tab.
4. Under `General` section you see `Show Franz in system tray`
5. change it several times

**Expected behaviour**
To have only one system tray icon when activating it

**What really happens**
It will add an icon every time you activate but will not remove it when deactivated

**Screen shot**
![Franz](https://user-images.githubusercontent.com/16348405/55401261-7127c380-5565-11e9-893a-6348fcb0e2b7.png)

**Desktop**
 - OS: ubuntu 18.04
 - Franz: 5.0.1

**Additional info**
Only last created icon works (can show Franz or make it exit)

**Comment by vishnureddy17** [comment]
This issue seems to affect many Electron applications running on Linux with GNOME. A temporary workaround for GNOME users is to press 'alt+F2' and then enter 'r' to restart GNOME.

**Comment by amir1376irani** [comment]
I'm aware of that, but isn't there a way to have consistency for that `tray.destroy` even on GNOME and KDE desktops?
By the way thanks for referencing this issue there, they may make more progress by checking this too.

**Comment by vishnureddy17** [comment]
I'm not sure, since I don't have much expertise with Electron and/or GNOME and KDE.

**Comment by chfanghr** [comment]
No progress. Instead of using tray in electron, I try to use kde’s tray service directly via D-Bus, and fortunately it works. Again, this is not a bug caused by desktop itself.

**Comment by chfanghr** [comment]
It seems that I found a bug in tray implementation.

https://github.com/electron/electron/blob/e7c48922e77b0043f2d829b4e8c44c0d2b45d500/atom/browser/ui/tray_icon_gtk.cc#L20

When JavaScript api is called , the call will pass to  this function to do the exact job , but as you can see, it just create a new tray without destroying the previous one , which may cause the issue.

**Comment by rrhythmsharma** [comment]
@chfanghr brilliant job, did you try to fix this?

**Comment by chfanghr** [comment]
I don’t know how to, because I cannot find the _icon variable  . Perhaps it’s generated on runtime in linux_ui/... ??? I can not even find the header.  That’s quite confusing. I am not familiar with electron’s build system indeed.

**Comment by rrhythmsharma** [comment]
me too, I tried to solve it but I didn't understand it correctly, though we can inform electron community core developer they can figure it out sometime
