### ISSUE TITLE
German translation of "Minimize to taskbar" misleading

### ISSUE THREAD

**Issue by DaBozzz** [meetfranz/franz#138]
### Expected Behavior
I have the minimize to taskbar option activated, Franz should minimize but still show as an active window when clicking the minimize button.

### Current Behavior
The Franz window is closed and minimized to systray.

### Your Environment
* Franz Version used: 5.0.0.-beta.11
* Operating System and version: Windows 10 Pro x64, with Fall Creators update

Thanks very much for your help!

**Comment by DaBozzz** [comment]
Update:
Seems like the German translation is wrong. In English it says minimize to systray, while the German version is speaking of the taskbar. If you disable all options except the third one it works now.

**Comment by adlk** [comment]
@DaBozzz thanks for reporting & investigating this issue. 

As a german native speaker I could do this on my own but I believe it's simple enough to provide a great entry point for first time contributors. Happy to get your PRs.
