### ISSUE TITLE
Icon with bug KDE and LXQT (desconfigured)

### ISSUE THREAD

**Issue by rikex** [meetfranz/franz#1382]
**Describe the bug**
Franz Icon is desconfigured. See print.

**Additional context**
![Franz KDE](https://user-images.githubusercontent.com/36997163/55626135-11a5ff80-5781-11e9-970d-cb75b2aa22bd.png)
![Franz LXQT](https://user-images.githubusercontent.com/36997163/55626136-123e9600-5781-11e9-9566-62675dd3f0b5.png)

**Comment by eqagunn** [comment]
Same issue present here. Running KDE Neon.
