### ISSUE TITLE
Unable to install and start Franz 5.0.1

### ISSUE THREAD

**Issue by jslkha** [meetfranz/franz#1384]
Installation starts then nothing happens - lurking process in task manager that persists. After a while a desktop shortcut appears which launches franz but no UI - just a process running in the background in task manager. 

NOTE: issue doesn't occur if older release is installed. 

### Expected Behavior
Smooth installation with a notification it's complete and for Franz to launch via shortcut

### Current Behavior
Installation process runs in background but no visual representation of whether it's done or not 

### Steps to Reproduce (for bugs)

1. Clean uninstall and restart
2. Clear registry and temp files and remaining folders from uninstall 
3. Download latest version of Franz 5.0.1
4. Run install 
5. Wait appropriate time (roughly 30 mins for good measure) 
5. Try to launch Franz via shortcut

### Your Environment

* Franz Version used: 5.0.1
* Operating System and version: Windows 10 x64

**Comment by SophieMo** [comment]
same issue since last version 5.0.1 installed.

**Comment by TheWitcher92** [comment]
I have the same issue. Its running in the task manager but I dont see anything.

**Comment by jslkha** [comment]
So it appears we're all running into this? Strange how not more people are reporting this.

**Comment by embql** [comment]
I could install and start Franz 5.0.1 beta.1, however, data seems to not load, see attached.
Not sure where to troubleshoot, other than install a previous release to see if it still works.

![image](https://user-images.githubusercontent.com/19207128/56247548-72003f80-60a5-11e9-8ac5-4e6513e0dc1a.png)

**Comment by jslkha** [comment]
After some time and effort it took me a while to deal with just rolling back to an earlier version to avoid this issue. However the software updated itself recently and now seems fine. Closing the issue.
