### ISSUE TITLE
Can't login to Gmail - clicking "Sign in" opens the browser

### ISSUE THREAD

**Issue by apaatsio** [meetfranz/franz#1386]
**Describe the bug**
When I open the Gmail service, it's not logged in. When I click the Sign in link, it launches the sign-in form in the browser. Signing in in the browser does not affect Franz, so the Gmail service inside Franz remains in logged-out state.

**To Reproduce**
I don't know how I ended up in this situation so I don't know the exact prerequisites.
1. Start Franz
2. Select Gmail service
3. Click Sign in

**Expected behavior**
Google sign-in opens inside the Franz app.

**Actual behavior**
Google sign-in opens in the browser.

**Screenshots**
![gmail login](https://user-images.githubusercontent.com/195210/55709232-2a641e80-59e8-11e9-9d4b-7d61903482f0.png)

**Desktop:**
 - OS: Manjaro Linux XFCE 18.0.4
 - Browser chrome 75.0.3753.4 (Official Build) dev (64-bit)
 - Franz Version: 5.0.1 (release 4.0.8 / linux / x64) *Edit (July 23, 2019): Still happens on 5.2.0* 

**Additional context**
I have two Gmail accounts: a personal account (`@gmail.com`) and a company account (`@customdomain.com`). The personal account works fine, but the company account is the one with the issue.

**Comment by nelsonloud** [comment]
I have the same issue!

**Comment by amanjohar** [comment]
Same, any fix for this.

**Comment by amanjohar** [comment]
the following procedure seems to work
    Please remove the "gmail" folder in:
        macOS: ~/Library/Application Support/Franz/recipes/
        Windows: %appdata%/Franz/recipes/
        Linux: ~/.config/Franz/recipes/
    Delete Gmail from your Franz services
    Restart Franz
    Add Gmail via "Add new service"

This worked for me

**Comment by maielo** [comment]
+1 same issue but on windows

**Comment by apaatsio** [comment]
I haven't experienced this anymore on 5.5.0.

I'm closing this issue for now. If someone is still experiencing this problem on 5.5.0+, I can reopen the issue.

**Comment by roeeyn** [comment]
Hey @apaatsio I'm having this issue in a fresh Franz installation. Clicking on the "login" just opens the browser and then the authentication redirects to the same browser instead of Franz. I'm using Franz 5.5.0.1762 installed with homebrew in a macos.
![Uploading image.png…](demo)

**Comment by roeeyn** [comment]
Nevermind, following @amanjohar suggestion worked. 🎉
