### ISSUE TITLE
Telegram do not send SMS confirmation to enable login - HTTP 406 code

### ISSUE THREAD

**Issue by lccezinha** [meetfranz/franz#1387]
**Describe the bug**

I'm trying to put my cellphone number to receive the SMS that will enable me to use franz in my desktop, but when I fill the SMS number and click in SEND, nothing happens.

**To Reproduce**

Download the version 5.0.1 (64 bit) on Linux Mint 19.1

1. Download & Install the APP
2. Try to add telegram as a new service
3. Insert your cellphone number and confirm
4. Nothing happens and if you check the dev tools console, I'll see a 406 error as I show in the print bellow.

**Expected behavior**

I expected that when I fill the cellphone number, I would receive an SMS and connect to the franz app.

**Screenshots**

![telegram1](https://user-images.githubusercontent.com/2160392/55721873-f0405000-59da-11e9-9d66-4df73d9aa588.png)

![telegram2](https://user-images.githubusercontent.com/2160392/55721874-f0d8e680-59da-11e9-917f-7028d0c52dea.png)

**Desktop:**
 - OS: Linux Mint 19.1 (amd64 / 64 bit)
 - Version Franz 5.0.1

**Additional context**

**Comment by thatvirtualboy** [comment]
Same behavior in macOS

**Comment by lccezinha** [comment]
@thatvirtualboy I remove all references in my computer about franz and try to reinstall today (4/11/2019) and now works fine.

**Comment by thatvirtualboy** [comment]
That’s weird. It happened to me with a brand new install - never had Franz on my system before

**Comment by lccezinha** [comment]
@thatvirtualboy Really weird.

But try that, maybe it could work for you as it worked for me.

**Comment by l0aded** [comment]
It is broken on Station as well.   Possible Telegram changed something?

**Comment by Gby56** [comment]
Broken for me too here, fresh new install.
A few days ago it worked flawlessly on windows, I'm on the macOS build but I don't really expect a difference.

**Comment by rafaelmaeuer** [comment]
not working on macOS 10.14.4 with Franz 5.0.1

**Comment by mxmucan** [comment]
Same issue here, the environment:
macOs Mojave 10.14.4 
Fresh install for Franz

What worked for me: delete Franz from Applications, and install again from the terminal using brew  (brew cask install franz), if you don't have installed brew, run this in the command line: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by rafaelmaeuer** [comment]
Today I tried it again and it worked on the first try, but I have no idea why, nothing was different.

**Comment by Zonkooo** [comment]
Same here, Windows 10, error happens on both Chrome and Firefox.

**Comment by alpha7540** [comment]
I turned on a VPN and it started working

**Comment by rafaelmaeuer** [comment]
using a vpn telegram refuses to load images and therefore the message "connecting" is persistent

**Comment by paulfecht** [comment]
not working here on chrome and Win 7

**Comment by Kabelstapler** [comment]
Not working on Mac OS High Sierra neither... got 4x the same code. Doesn't work in Franz. Please fix this...

**Comment by SolarpunkJackal** [comment]
I'm completely unable to use Telegram on my older Android phone as well as the Telegram program I installed on my Windows 10 gaming PC here; after I enter my phone number and country and go to next it says a SMS message is on its way to my phone, but that never happens.
