### ISSUE TITLE
Slack not working anymore

### ISSUE THREAD

**Issue by cgarciae** [meetfranz/franz#1389]
I get this message:

> Please update your third-party app or use the Slack desktop app
> 
> We are no longer supporting this version of the third-party app you’re using to access Slack. We know that updating or changing apps can be a pain, and we’re sorry for asking you to do it. You can learn more about why this is necessary in our FAQ.
> 
> If you’re unable to update, you can download the Slack app instead. It offers the best Slack experience — plus no more worrying about updates.
> 
> As always, feel free to contact us if you have any questions.

I had to switch to using the slack app but loose of the benefits of franz.

**Comment by stephanvierkant** [comment]
Related to #1185?

**Comment by merryndd** [comment]
#1347 has the fix.

**Comment by davereid** [comment]
I can confirm the latest releases have addressed this issue, I think it can be closed.
