### ISSUE TITLE
Add keyboard shortcut to reload current (and/or all) service(s) e.g. F5 for current, Ctrl+Alt+F5 for all

### ISSUE THREAD

**Issue by WHeesters** [meetfranz/franz#1392]
**Is your feature request related to a problem? Please describe.**
Some services require me to reload the service to be able to relogin after my session is over, reloading now is kind of a pain if you've got many services.

**Describe the solution you'd like**
I would like for F5 to reload the current service and for Ctrl+Alt+F5 to reload all (enabled) services.

**Comment by schimizzimj** [comment]
@WHeesters If I understand your issue correctly, there is a current set of shortcuts that will reload the current service and all services. Not sure if it's the same on all devices, but on Linux Ctrl+R reloads the current service and Ctrl+Shift+R will reload all of them. 

I know these aren't the same as the shortcuts you asked for, but there do seem to be shortcuts for it. 

This is also using Franz version 5.0.1

**Comment by WHeesters** [comment]
@schimizzimj I didn't know that the shortcuts for reloading services already existed, thanks! I'm going to close this issue now. However, it would be nice if the available shortcuts were visible in the context menu.
