### ISSUE TITLE
Add cursor: pointer; to sidebar service icons

### ISSUE THREAD

**Issue by sadiqevani** [meetfranz/franz#1396]
**Is your feature request related to a problem? Please describe.**
Its a bit annoying when I see the default cursor when I hover over the Service Icons.

**Describe the solution you'd like**
A simple css rule over the service Icons: `cursor: pointer;`

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by DominikGuzei** [comment]
Franz is a desktop application and thus the default cursor is kept on purpose (it's not a website)
