### ISSUE TITLE
Discord auto-login

### ISSUE THREAD

**Issue by odedta** [meetfranz/franz#1397]
**Is your feature request related to a problem? Please describe.**
I use about 6-7 services, when I start Franz all of them auto-login, Discord doesn't. Anyway to change that?

**Describe the solution you'd like**
Auto-login for Discord

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Gaboris** [comment]
Huh, that is odd. My Discord service logs in just fine.
Do you manually log off Discord before you close Franz or just shut Franz down cuz that just works for me without any problems.

Maybe it's because I only use 4 services? Try changing the order of yours so Discord in higher up?

**Comment by odedta** [comment]
Hey @Gaboris,

Thanks for your reply, I had 2FA enabled so I think that's what caused this issue. I'll keep you posted if this problem persists.

Thanks

**Comment by Snuggle** [comment]
I use Discord with TOTP two-factor authentication and I have never had this issue?

**Comment by Wouter0100** [comment]
I had this in the past, but seem to be fixed now. With 2FA.

**Comment by Kookabura** [comment]
Hello,
I have the same problem. Discord auto-login doesn't work for me. 2FA is not enabled. I don't need this feature.
As I understand 2FA if I enabled it so auto-login won't work because I will need to enter 2FA code.

Franz version is 5.3.3
