### ISSUE TITLE
Should we wait for Viber and Instagram support?

### ISSUE THREAD

**Issue by Shevbo** [meetfranz/franz#14]
Should we wait for Viber and Instagram support?

**Comment by adlk** [comment]
Unfortunately Viber has no Web version. 

Ad Instagram and service requests in general:
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by david-nedved** [comment]
HI @Shevbo  - I've actually made a franz plugin that integrates Viber (running from your desktop) into Franz here: https://github.com/david-nedved/viber-franz
