### ISSUE TITLE
Unable to add new services in drop down menu 

### ISSUE THREAD

**Issue by aujoy** [meetfranz/franz#140]
### Expected Behavior

Be able to scroll down to add new services as there are too many services added 

### Current Behavior

stuck screen, unable to add 

### Screenshots (if appropriate):
![Uploading Screenshot 2017-10-27 11.02.26.png…]()

### Possible Solution

Scroll bar to add new services 
Or just move add services button to the top instead of the bottom

### Steps to Reproduce (for bugs)

1. add up to 12 services and u can see the error 
2.
3.
4.

### Context

Unable to add new service and aggregate all messaging services into one 

### Your Environment

* Franz Version used:

Latest
* Operating System and version:
Version 4.0.4 (4.0.4)

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)

**Comment by aujoy** [comment]
Thank you 

With gratitude, 
Audrey
