### ISSUE TITLE
Could not load service or user information

### ISSUE THREAD

**Issue by notNSANE** [meetfranz/franz#1400]
**Describe the bug**
Nothing works after updating to 5.0.1. I restarted the program and still same error no matter what. Doesn't load any services either.

**To Reproduce**
1. Install 5.0.1

**Expected behavior**
Services work normally.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by adlk** [comment]
We had some server issues last week that are now resolved.

**Comment by pakoito** [comment]
I just had a small heart attack. It's all back now.

**Comment by LaurentPerche** [comment]
Looks like the issue is back again.

**Comment by HeikoKanzler** [comment]
Same here, had to restart my Mac and Franz is not connecting.

**Comment by shugli** [comment]
Same here. https://api.franzinfra.com/v1/me/services --> net::ERR_CONNECTION_RESET

**Comment by dgtexan** [comment]
Happening for me today. Services and user info could not be loaded, Making this post with the same device, so not an overall network issue. Unless my employer blocked Franz traffic? No services show in list to add new services, either. Not sure what else to provide.

**Comment by supermarkert** [comment]
Also happening for me today. A little further digging and it looks like my employer now blocks the domain "franzinfra.com". So I guess Franz is worthless unless it can access this API server? That's disappointing, as now I need to find another app.
