### ISSUE TITLE
Can't connect to Franz online services after update

### ISSUE THREAD

**Issue by kjeffrisps** [meetfranz/franz#1401]
I was prompted by the bottom of the application to update Franz and restart, but when I did it abruptly restarted and then nothing was accessible.  It showed that I was still logged in, but services were not accessible and same with the settings.  I logged out, and now I can't login and at the top it says "Can't connect to Franz online services".  It doesn't fix itself after restarting either.

 - Device: macOS 10.14.4

Update: I tried reinstalling and had the same problem.  I restarted my computer and was able to then login, but the update bar was at the bottom again.  The update did work this time.

**Comment by hassankhan** [comment]
+1 came here to report the same.

**Comment by lexielex** [comment]
Same thing happened to me. 

Restarting didn't solve the problem . Device is also macOS 10.14.4

**Comment by nccurry** [comment]
I am seeing something similar to this as well on Fedora 29.

**Comment by adlk** [comment]
We had some server issues last week that are resolved now.

**Comment by thcrnk** [comment]
I got the same issue today, are the servers ok?

**Comment by franz0r** [comment]
same here

**Comment by gabiailincai** [comment]
It's working for me now. If it's hosted on Google Cloud, there were some networking issues earlier.

**Comment by thcrnk** [comment]
Now everything is working, the google cloud platform was offline, so I guess it is hosted there.

**Comment by kjeffrisps** [comment]
It seems this is a recurring issue when google's servers are down, which really can't be helped by the developers.  Should we close this issue or keep it open for others to have reference in the future?
