### ISSUE TITLE
Slack services failing to connect due to lost team configuration (after update, restart)

### ISSUE THREAD

**Issue by davereid** [meetfranz/franz#1405]
**Describe the bug**
I recently updated to the latest version and found that all my Slack services lost their "Team" setting which is the subdomain for slack.com. All my Slack services were loading with a network connection error until I discovered this.

![image](https://user-images.githubusercontent.com/62967/56430822-3de77300-628d-11e9-91ec-c4d8630ebcf3.png)

**To Reproduce**
1. Have a recent version of Franz installed with a fully-configured Slack service already active.
2. Close the Franz application and ensure it is no longer running.
3. Start the Franz application back up.
4. View Slack services no longer load after update
5. Edit the Slack service and notice that the "Team" configuration is blank.

![image](https://user-images.githubusercontent.com/62967/56430891-81da7800-628d-11e9-94f3-2247c210d2f0.png)

**Expected behavior**
For Slack service to not lose its configuration.

**Desktop:**
 - OS: Windows 10
 - Version 5.1.0-beta.1

**Comment by ianseyer** [comment]
Also experienced this issue just today on `5.0.0-beta.18` on Arch.

Editing the service to re-add the team id worked.

**Comment by Cahl-Dee** [comment]
Same issue on my end. But I'm not on Franz beta so I initially thought I had a different problem.

Issue title should be updated accordingly.

@ianseyer's workaround solved the issue.

![image](https://user-images.githubusercontent.com/1673298/56430318-0203dc00-6294-11e9-8356-a095345b0adc.png)

**Comment by davereid** [comment]
Updated the title. I've been reviewing the meetfranz/slack-plugin for anything that could have caused this, but I don't see anything obvious.

**Comment by davereid** [comment]
Okay, this just happened again while I had Franz active open!

**Comment by davereid** [comment]
I am able to reproduce this after just restarting Franz. Every time the application starts my Slack service configurations are lost.

**Comment by Fire-Dragon-DoL** [comment]
I can confirm this is happening to me too.
I added back the configuration (10 workspaces), closed/reopened the app, config lost (argh!)

**Comment by mangledmonkey** [comment]
Same issue, even after updating from the latest public release to the latest beta. I have four Slack apps, all of which are failing to load.  If I edit the settings for each, the slack URL is missing. Entering the URL and saving settings allows Slack to load—until I restart Franz, and the issue repeats.

**Comment by Fire-Dragon-DoL** [comment]
I don't think it's directly related to Franz though, it's something loaded from outside. I didn't update the app in a while (I'm not on beta, i was on 5.0.0) and the problem appeared suddenly

**Comment by obvionaoe** [comment]
This is happening to me as well, but I think it has something to do with Slack itself...

**Comment by Fire-Dragon-DoL** [comment]
Has this been fixed? I still can't use Franz
