### ISSUE TITLE
"Open account settings" in Slack has no effect

### ISSUE THREAD

**Issue by logological** [meetfranz/franz#1407]
**Describe the bug**
In the "Profile & account" pane of a Slack service, the "Open account settings" command has no effect.

**To Reproduce**
1. Open a Slack service
2. Click on the name of the service to activate its pull-down menu
3. Click on "Profile & account"
4. In the new pane that appears, click on the "…" button
5. Click on "Open account settings"

**Expected behavior**
I expect some sort of menu or dialog to appear that allows me to change my account settings (e-mail address and password, I suppose, and maybe other settings).  Instead, nothing happens.

**Desktop (please complete the following information):**
 - OS: openSUSE 15.0
 - Browser: SeaMonkey
 - Version: 2.49.4

**Comment by logological** [comment]
I've tried to access the "Open account settings" pane using a web browser (Chromium) and it works as expected.  In the web browser, the account settings page is opened in a new tab as opposed to the current tab.  This might be why Franz has trouble displaying it.

**Comment by DominikGuzei** [comment]
This seems to be an issue of electron compatibility with openSUSE 15.0 … this works as expected on all major platforms we test …
