### ISSUE TITLE
No notifications for Android Messages

### ISSUE THREAD

**Issue by jfriedmanphilo** [meetfranz/franz#1409]
### Expected Behavior
When a new message comes in there's a notification: badge on Messages icon in app, badge on dock icon, and dot on menu bar icon.

### Current Behavior
No badges or dots anywhere (although new message is showing up in MacOS notification center). No problems with dots and badges for other services, e.g., Whatsapp.

This started last week.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:  5.1.0-beta.1.1326
* Operating System and version: MacOS Mojave 10.14.4

**Comment by changkm** [comment]
Happening to me as well. Franz 5.1.0-beta.1. Ubuntu 18.04. Slack and Outlook recipes have no problem.

**Comment by changkm** [comment]
I have reinstalled the messenger recipe as well as upgrading to the latest Franz 5.1.0 (not beta), and issue is still happening.

**Comment by JDoe0000** [comment]
Same! Still no notifications...

**Comment by Jonathanwalls** [comment]
Same issue as well. No notifications for Android Message.

**Comment by JDoe0000** [comment]
Still not fixed for me. And now lost WhatsApp notifications as well...

**Comment by jaminroe** [comment]
I'm not seeing an unread badge either. I'm a paying customer, so hope to see this fixed since I'm sure this app has a large number of users.

**Comment by JDoe0000** [comment]
Mine started working again for a bit, but then they disappeared again with the latest update (5.2.0.1455). I, too, hope this gets resolved soon!

**Comment by rizqiimani** [comment]
2020 and still no notification banner for WhatsApp and Telegram
