### ISSUE TITLE
Franz and LINE chat.

### ISSUE THREAD

**Issue by maryadavies** [meetfranz/franz#1411]
I thought I'd ask even tho right now, i'm having a unrelated issue.

Is there any way we can get LINE working with Franz?  (http://www.line.me). They have a messenger for both Windows, a Chrome extension (maybe start with that?) and for Android.

It's a odd omission right now. ^^

**Comment by LastStarDust** [comment]
Just passing by to comment that the only reason keeping me from purchasing Franz is the lack of LINE integration ...
