### ISSUE TITLE
Franz does not launch, with error "Ordinal 345 not found"

### ISSUE THREAD

**Issue by heistak** [meetfranz/franz#1415]
**Describe the bug**
Since a month or so ago, Franz on Windows refuses to launch.

**To Reproduce**
1. Install Franz into Windows PC from https://meetfranz.com/ (This happened with at least 5.0.0, 5.0.1 and 5.1.0)
2. Attempt to launch Franz from Start Menu or Desktop shortcut
3. Franz does not launch, its main window does not show up, and the below error message appears. Upon dismissing the message, nothing further happens.

**Expected behavior**
Franz launches, the main window appears, and the app becomes usable.

**Screenshots**
![image](https://user-images.githubusercontent.com/658927/56847572-8cdd7a00-6917-11e9-82f9-a2d2e831b983.png)
The error message appears in Japanese because the primary language of this installation of Windows 10 is set to Japanese. The message translates to the below:
"Franz.exe - Ordinal not found
Ordinal 345 was not found from dynamic library C:\Users\Needle\AppData\Local\Programs\franz\Franz.exe"
However, the message stayed in Japanese even after I changed Windows's Region, Regional Format, and Display Language to US English, logged out and logged back in.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Version: 1809
 - CPU: AMD Ryzen 7 1700
 - Motherboard: BIOSTAR X370GTN
 - GPU: EVGA NVIDIA GeForce GTX 1070 SC

**Additional context**
 - Unity 2018.2.7f1, 2018.2.4f1, 2017.4.10f1, and 2017.3.1p1 are installed on this system.
 - Visual Studio 2015, 2017, and 2019 are all installed on this system due to me having installed various versions of Unity and the Unity installer installing VS with itself.
 - These "ordinal" errors appear to be fairly uncommon among the web. After googling around for similar errors and solutions, I tried things like running "sfc /scannow" from an elevated PowerShell prompt, and installing the latest Microsoft Visual C++ Redistributable, both to no avail.
 - As seen in the above path, my username does not contain spaces or non-latin characters. This is a common source of errors in western-developed programs running in Asian environments, but I took care to avoid them.
 - Not sure of the relevance, but just FYI, Rambox, another Electron-based multi messenger app, also refuses to run with the same "Ordinal 345 not found from C:\Users\Needle\AppData\Local\Programs\Rambox\Rambox.exe" error (again, the error message is originally in Japanese.)
 - Slack and Discord's own dedicated native Windows apps both run fine. Oculus Software, which IIRC was based on Electron, runs fine.

**Comment by heistak** [comment]
With Franz 5.0.0 beta 17, the issue still occurs. In beta 11, however, it does not. I'll keep trying to binary-search the exact version where this starts happening.

**Comment by heistak** [comment]
The point where this error begins occurring appears to be Franz 5.0.0 beta 14.
Betas 11, 12, and 13 launch fine. However, betas 14 and 17 both exhibit the Ordinal 345 error. 
(I have not tried other versions.)

**Comment by closingin** [comment]
Hello,

As someone who currently learns japanese, I have to say that your english is very good.

For your problem, I just read on your blog that you have found `MacType` to be the origin of the bug? We're currently running Franz 5.1.0, so you should try to update to see if the issue persists. But I think the problem is specific to your windows installation, it seems messy out here!

**Comment by heistak** [comment]
Uninstalling the beta version of MacType and replacing it with the release version seems to have fixed the issue. Not sure what exactly it was doing to cause this, but I guess this was installation-specific. Sorry for not following up immediately, I'll close this issue out.
