### ISSUE TITLE
Export/Save Settings for a backup

### ISSUE THREAD

**Issue by bexelbie** [meetfranz/franz#1417]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to save my Franz configuration (minimally which services I have enabled and their current ordering) so I can more easily rebuild/reinstall my machine in case of failure.

**Describe the solution you'd like**
A single file that I can backup and restore so that Franz restarts the same way on a new system.

**Describe alternatives you've considered**
I've gone through the files in ~/.config/Franz and don't see likely candidates.

**Additional context**
Thank you!

**Comment by KristerV** [comment]
Related: https://github.com/meetfranz/franz/issues/1790

So theoretically if you bring over the partitions folder (4gb in my case, unfortunately) you should have all the services and sessions (so not going to ask for password). I'm going to backup the whole ~/.config/Franz folder just in case. The rest of the stuff is only a few mb extra anyway.
