### ISSUE TITLE
Services active when macOS/MacBook closed

### ISSUE THREAD

**Issue by promarcel** [meetfranz/franz#1420]
**Describe the bug**
When I closed my MacBook Pro, after some time in my WhatsApp connected devices it appears the client from Franz come alive. Also on another desktop the display switched to "active on another screen".

Power options are set to only disable the hard drive, options like wakeup by WiFi or powernap mode is disabled. Don't know why this happen.

**To Reproduce**
1. Close lid of MacBook
2. After some time (approx. 30 minutes) WhatsApp showing the session from Franz was alive

**Expected behavior**
No action wehen lid of MacBook is closed.

**Desktop:**
 - OS: macOS Mojave 10.14.4
 - Franz version: 5.1.0

**Comment by joeherold** [comment]
same to me. also with whatsapp app
