### ISSUE TITLE
Workspaces - Can't change order of services

### ISSUE THREAD

**Issue by promarcel** [meetfranz/franz#1421]
**Describe the bug**
I've created some Workspaces today to manage the services I need. After adding some I want to change the order/sort of the services. In the "All services" tab this is possible but selecting a Workspace and drag & drop the services to reorder them, they get back to his old position.
It should possible/is needed to reorder this services for better organization.

**To Reproduce**
1. Try drag & drop a service to reorder it in a Workspace
2. The service will jump back to his old order and not stay at the new one

**Expected behavior**
The services is ordered by users selection and order by each own is possible and saved.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Franz 5.1.0
 - Happen on Windows 10, with same Franz version too

**Comment by jaminroe** [comment]
Same here

**Comment by DominikGuzei** [comment]
Thanks for the report @promarcel, this has been fixed in #1425 and will be released with the next version!

**Comment by Eckybrazzz** [comment]
+1, really annoying that you can't change the order of the services once added. Waiting for the next version!
