### ISSUE TITLE
empty attachments

### ISSUE THREAD

**Issue by qingchuwudi** [meetfranz/franz#1427]
Files translated by Franz5 (for WeChat) is empty on the recver. It's zero size after download. Any size and any type.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS (Desktop)
 - Browser: chrome
 - Version Franz 5.1.0(Release 4.1.4 / linux / x64)

**Comment by wrathofthomas** [comment]
As above, when files/attachments are sent through chat in a web wechat client open in Franz, Franz downloads them as empty files. Has been like this for much of version 5 at least. Really destroys a large part of the utility of having Wechat in Franz.
