### ISSUE TITLE
impossible to install on last version of windows

### ISSUE THREAD

**Issue by adrienko** [meetfranz/franz#143]
hi, 

it's impossible to install franz 5.0 on a windows Windows 10, version 1709
franz il install but will but stuck at the blue loading screen (after being obliged to complete emails ) 
already uninstalled it, and uninstalled the version 4 and re-installed it and still the same
thanks

**Comment by adlk** [comment]
Hey, can you please send me an email to stefan@adlk.io with the email you have signed up with. I need to check a few things.
