### ISSUE TITLE
Microsoft Teams: No call possible

### ISSUE THREAD

**Issue by sebna** [meetfranz/franz#1434]
**Describe the bug**
Using Microsoft Teams, I´d like to make and receive calls.
To do this, the user agent should change to e.g. Chrome.

<img width="603" alt="Screenshot 2019-05-15 at 14 16 02" src="https://user-images.githubusercontent.com/22451140/57775340-11eccf80-771d-11e9-859f-31dba3a33c36.png">

**Comment by m-osmani** [comment]
I have the same issue.

i would appreciate any help

**Comment by kitingChris** [comment]
That is the limitation of the webview. Guess there might be no solution until microsoft or some crazy javascript guru may find an hack

**Comment by bittner** [comment]
The basis for MS Team's "for your browser" decision is simply the user-agent string. You can prove that by changing your user-agent string to, e.g.

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.11 (KHTML, like Gecko) Ubuntu/18.04.3 Chrome/81.0.3990.0 Safari/537.36

I have tried this in Firefox on Ubuntu 18.04.4 (Bionic) with the [User Agent Switcher](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) extension, and the video call works. Hence, we can simply override the user-agent string in the [MS Teams recipe](https://github.com/meetfranz/plugins) to get voice and video calls working.

**Comment by bittner** [comment]
This seems to work now out of the box! :confetti_ball:  I verified video calls with [Ferdi](https://github.com/getferdi/ferdi/).

Probably we can close this ticket?
