### ISSUE TITLE
OSX: Reordering applications doesn't work

### ISSUE THREAD

**Issue by danpaulson** [meetfranz/franz#1435]
**Describe the bug**
Trying to reorder applications on the sidebar in OSX does not save the ordering

**To Reproduce**
1. Open Franz
2. Add multiple applications
3. Attempt to reorder by dragging the icons
4. Bug: icons are not reordered

**Expected behavior**
The Icons should stay in their reordered location.

**Screenshots**
https://i.imgur.com/fUT8PYr.mp4

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6

**Comment by closingin** [comment]
Hi Dan,

I cannot reproduce on 10.14.4, this works fine for me. Have you tried to reinstall the software or to update it to the latest version?

**Comment by DominikGuzei** [comment]
Also cannot reproduce this issue.

**Comment by danpaulson** [comment]
Updated to 14.4 - still happening. I should say - it is only in Workspaces that it happens, when viewing all services, re-ordering works correctly.

**Comment by DominikGuzei** [comment]
The reordering issue was already reported in #1421 and we have a fix that will be available in the next release 👍
