### ISSUE TITLE
Franz start sets it as default for *.html files on Ubuntu 16.04

### ISSUE THREAD

**Issue by mimre25** [meetfranz/franz#1447]
**Describe the bug**
When starting Franz, it sets itself as default application for html files on Ubuntu 16.04

**To Reproduce**
1. Close Franz.
2. Set other application as default application for *.html files (rightclick on html file -> properties -> open with) 
3. Open Franz
4. Double click *.html file and it will point to Franz (or check default application)

**Expected behavior**
Nothing should happen except that Franz is started when I start Franz. It shouldn't change system/user settings.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser Chrome
 - Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by mhatvan** [comment]
I could not reproduce this issue on Ubuntu 19.04 or find any code in the repository related to changing default application behavior, are you still encountering this issue?

**Comment by mimre25** [comment]
Yes I still do.
The first screenshot shows the setting after I changed it to manually use chrome
![Screenshot from 2019-06-14 08-13-59](https://user-images.githubusercontent.com/2582811/59508623-99dd0b00-8e7c-11e9-8824-c522c628d0af.png)

Then I closed Franz and started it again and got what is seen in the second screenshot.
![Screenshot from 2019-06-14 08-14-30](https://user-images.githubusercontent.com/2582811/59508656-ab261780-8e7c-11e9-89e0-eea86c621a75.png)

(Needless to say that I didn't set Franz as default application to open html files.)
