### ISSUE TITLE
Franz does not work anymore

### ISSUE THREAD

**Issue by flavioxy** [meetfranz/franz#1448]
A few days ago, I was logged out of all services, only prompting me to "get started". Clicking this led me to choose my services. However, no services were found whatsoever (I normally use Whatsapp, Facebook Messenger and Gmail). 

I logged out and tried to log in again. Upon logging in, the wheel turned for a while and stopped, leaving me logged out and saying "Can't connect to Franz online services". Reinstalling didn't resolve the issue.

This happened on three computers and on Mac OS X High Sierra and Windows 10 64-bit, both current versions and in several networks. 

I tried logging in on the website without success. I was also unable to create a new account. I used Chrome browser current version for website use.

**Comment by EduardsE** [comment]
Same issue here. Already created an issue for it, which was completely ignored.
[https://github.com/meetfranz/franz/issues/1438#issue-446214199](1438)

**Comment by mlcbrito** [comment]
Franz inicializa o serviço porém não carrega e fica como inicializado no Gerenciador de Tarefas.
