### ISSUE TITLE
Franz is showing very high CPU usage, in 50s%

### ISSUE THREAD

**Issue by dabrazhe** [meetfranz/franz#1451]
Franz is causing very high CPU usage, which is first observable by the Macbook sounding like a jet, kicking in all the fans. 

CPU Usage is above 48.5 % 

 - OS: macOS 10.14.4 (18E226), Macbook pro 2015
 - Franz gui app 
- Version 5.1.0 (5.1.0.1337)

This is very weird, as it's higher than even Chrome with youtube playing. 

To reproduce:
enable Slacks, Facebook msgr, Skype, telegram, discord 
wait about 3 minutes, listen to fans spinning
view the CPU stats in Activity Monitor

**Comment by destyl** [comment]
Same issue..

**Comment by flips** [comment]
Same issue here, after adding a second Slack service. Franz Helpers at 120% + 26% CPU (in Activity Monitor)

**Comment by vistalba** [comment]
Same issue here... almost unusable.

Windows 10, 19H1 with Version 0.5.1

**Comment by thomasbrueggemann** [comment]
I also experience the issue within the last 7-10 days. Franz became unusable.

macOS 10.14.5
Franz 5.1.0 (5.1.0.1334)

**Comment by dabrazhe** [comment]
What helped is removing and reinstalling Franz from the brew cask. You can also try using the installer from the web site if this does not work.

**Comment by vistalba** [comment]
@dabrazhe I used the windows installer from website and the installation is brand new. Just installed it 1-2h before my initial posting above.
