### ISSUE TITLE
Franz not starting up after latest Windows updates

### ISSUE THREAD

**Issue by MathiasRenner** [meetfranz/franz#1452]
**Describe the bug**
When I start Franz (latest 5.1.0), it does not start. Also, no process is started showing up in the task manager.
I tried reinstall, same thing.

**To Reproduce**
1. Make sure no instance of Franz is running, in no other Display that you just don't see.
2. Start Franz
3. Search for The window of the app... -> there is none.

**Expected behavior**
Showing the app Window after start.

**Desktop (please complete the following information):**
 - OS: Windows 10, latest

**Comment by MathiasRenner** [comment]
Interesting, using "start as administrator" works

**Comment by weberro** [comment]
Same here. Latest Insider Build (1903 / 18898.1000).
"Franz" process is running, shows up in Task manager, but no window. Doesn't work in elevated mode either on my machine. Even tried to uninstall and reinstall.

**Comment by weberro** [comment]
> **Describe the bug**
> When I start Franz (latest 5.1.0), it does not start. Also, no process is started showing up in the task manager.
> I tried reinstall, same thing.
> 
> **To Reproduce**
> 
> 1. Make sure no instance of Franz is running, in no other Display that you just don't see.
> 2. Start Franz
> 3. Search for The window of the app... -> there is none.
> 
> **Expected behavior**
> Showing the app Window after start.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10, latest

Found a solution:
Delete the "Franz folders" from "$USERPROFILE$\AppData\Local" and "$USERPROFILE$\AppData\Roaming" and eventually reinstall "Franz". Worked for me.

**Comment by MathiasRenner** [comment]
@weberro It works for me, thank you so much for your help!
