### ISSUE TITLE
Hangouts Chat - issue with notification counter and opening links 

### ISSUE THREAD

**Issue by pwojewodzic** [meetfranz/franz#1456]
**Bug description**
In the programme both on Windows and macOS, I have a problem with missing notification counter on Hangouts Chat service. Additionally, when I want to open a link, the blank window showing up and the link is opening in the default system browser.

**Screenshots**
On Windows 10 -> https://gyazo.com/c41499c73a21f40faaff885350546a8e

**Expected behaviour**
* Franz should show the number of unread conversations from Hangouts Chat
* links should be opened without this blank window

**System info**
- Windows 10 ver 1809
- macOS 10.14.5
- the latest stable version of Franz

**Comment by csharp** [comment]
Also see this on Ubuntu 19.04, Franz 5.0.0, V4.0.4/lnux/x64.
Thanks.

**Comment by ilopmar** [comment]
Is it possible to merge the related PR and include it in the next version? I'd be happy to help to test this.

Thanks!

**Comment by mokipedia** [comment]
it got even worse for me, I still do not get notifications (as this seems not merged yet) and now the links do not work at all with chrome (although that blank windows opens).
Franz 5.4.0-beta3, mac 10.14.3 & 10.15.0 & 10.15.1

**Comment by ilopmar** [comment]
Same happens to me with the links (blank window) using Franz 5.3.3 on Linux

**Comment by ilopmar** [comment]
I've just updated to Franz 5.4.1 and now there is no blank window but links don't work.
