### ISSUE TITLE
Mac Notification Badge do not show | Mac version 10.14.5 | Franz version 5.1.0

### ISSUE THREAD

**Issue by Ere00** [meetfranz/franz#1458]
**Describe the bug**

I have WhatsApp service. I do not get notification badges from new Whatsapp messages in Franz app in Mac app bar.  

**Expected behavior**
When I receive a new message I would like to see some indicator from it.

**Desktop (please complete the following information):**
 - Mojave 10.14.5

**Comment by JDoe0000** [comment]
Same!

(Android Messages notifications stopped working last month as well...)

**Comment by valentiniljaz** [comment]
Same! No badges for services are being display, yet I still get notifications.

* Mojave 10.14.5

**Comment by imadphp** [comment]
Any news on this? Catalina 10.15

**Comment by Nixo76** [comment]
open
