### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by rubensa** [meetfranz/franz#1462]
Can't login neither in the app not in the web.  There seems to be a problem with the API server.

### Current Behavior
With Firefox developer tools I can see the call to https://api.franzinfra.com/v1/auth/login with response: **503** Service Unavailable.

### Screenshots (if appropriate):
![Screenshot from 2019-06-03 07-52-41](https://user-images.githubusercontent.com/1469340/58778919-9328db00-85d4-11e9-8ce8-e11fd52c6deb.png)
![Screenshot from 2019-06-03 07-52-03](https://user-images.githubusercontent.com/1469340/58778907-899f7300-85d4-11e9-992b-abf197ea22b4.png)

### Your Environment

* Franz Version used: 5.1.0
* Operating System and version: Linux 4.15.0-50-generic 54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by carel-lubbe** [comment]
I have the same issue

**Comment by kinglau66** [comment]
is it due to server issue again? 
why does server issue affected the installed local service, this seems like a flaw to me?

https://github.com/meetfranz/franz/issues/1400

**Comment by mkohlenbusch** [comment]
same here ... no login possible

**Comment by rubensa** [comment]
> is it due to server issue again?
> why does server issue affected the installed local service, this seems like a flaw to me?
> 
> #1400

**'A chain is only as strong as its weakest link'**

**Comment by SplittyDev** [comment]
This is significantly affecting our business right now. Any ETA for the fix?

**Comment by zyv** [comment]
Yesterday Google melts down, today Franz... where the world is going?

**Comment by michel1986** [comment]
same here ... no login possible!

**Comment by mgilank** [comment]
same here

**Comment by ilopmar** [comment]
Same issue again that happened some months ago? Once all the accounts are configured Franz should be able to start without connecting the backend...

**Comment by evanesac** [comment]
yep, Franz is down...

**Comment by pix-art** [comment]
Fixed! Thanks :-)

**Comment by Ickerday** [comment]
Not working for me as well.

**Comment by selwynorren** [comment]
If I look over at their twitter feed, seems like there are DNS issues, so it should be resolved pretty soon. I was up for me and then went back down again

**Comment by Jntz** [comment]
> If I look over at their twitter feed, seems like there are DNS issues, so it should be resolved pretty soon. I was up for me and then went back down again

Source?

**Comment by DerBernie** [comment]
Not sure if related, but https://www.meetfranz.com/ shows a certificate error ("The certificate is only valid for the following names: meetfranz.com, web-test.meetfranz.com"). I know the correct url is meetfranz.com but the www subdomain used to work as well. Maybe there's an SSL error with some service?

**Comment by hexangel616** [comment]
Same issue here.

**Comment by k0d3r1s** [comment]
please fix this, having ms teams in browser tab is so impractical

**Comment by ChTBoner** [comment]
> Not sure if related, but https://www.meetfranz.com/ shows a certificate error ("The certificate is only valid for the following names: meetfranz.com, web-test.meetfranz.com"). I know the correct url is meetfranz.com but the www subdomain used to work as well. Maybe there's an SSL error with some service?

Only on Firefox for some reason.

Same issue here, but could login for a short amount of time.

**Comment by fabriciopirini** [comment]
Just got back for me! Anyone?

**Comment by Jntz** [comment]
Yup. Now it's working!

**Comment by Kaspik** [comment]
Back for me as well.

After last week and now again, this seriously needs some PR and refactoring how to not be affected locally when server has issue.

**Comment by JeremLa** [comment]
@kinglau66 @Kaspik Franz is collaborative project guys, you have nice idea, so feel free to join the community :tada:

**Comment by KrisBataican** [comment]
I still have the same problem - can't login through app or web, is there something i not doing correctly?

**Comment by robtheriot** [comment]
Im having this problem but looks like about a year since this 
happend....
