### ISSUE TITLE
Could not load your Services

### ISSUE THREAD

**Issue by nbranquinho** [meetfranz/franz#1465]
### **Describe the bug**
I got the error message "Could not load your services" (under "Your Services Tab") or "Could not load user information" (under "Account" tab)

### **To Reproduce**
1. Have a PAC proxy script configured on windows machine
2. Login franz Account
3. See error

**Expected behavior**
Load srvices/account info correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/2866871/58891611-be9aeb00-86e4-11e9-8d39-5fa95d011146.png)

using Developer tools, it's show this:
![image](https://user-images.githubusercontent.com/2866871/58891815-19ccdd80-86e5-11e9-8fbb-209a7ed157e9.png)

**Desktop (please complete the following information):**
 - OS: windows 10 x64 
 - Version 5.1.0 / Release: 4.1.4 / win32 / x64

**Additional context**
The IT department has installed the Zscaler Root CA certificate because of the proxy script configuration

**Comment by zbhoy** [comment]
I am having same issue at work computer because my company uses Zscaler to configure the network. You need some type of browser page to login and allow the application to access and Franz doesn't have that so everything gets blocked. Hopefully this is resolved soon.

**Comment by k1sr** [comment]
I have had the same issue with Zscaler for everything (Google Drive, Dropbox, Android Messages for Web, Franz, and surely more to crop up).

Dropbox can be fixed by changing from Auto-Proxy to No-Proxy - I wonder if something similar could work for Franz?
