### ISSUE TITLE
No notifications on Windows 10 19H1 with Franz 5.0.1

### ISSUE THREAD

**Issue by vistalba** [meetfranz/franz#1474]
**Describe the bug**
There is no notification shown on my Windows 10 19H1 with Franz 5.0.1 installed.
This is a fresh install of Franz.
Other apps like Telegram, Outlook etc. are working fine with notification on same windows installation.
Already checked the settings app (notifications settings are set to sound and banner for Franz).

**To Reproduce**
- Install Franz on Win10
- Add Chat Account (e.g. Telegram)
- Double Check that notifications for this Account are enabled
- Minimize App to tray
- Wait for incomming message

**Expected behavior**
Notification PopUp of Windows 10 should appear with contact/text

**Desktop (please complete the following information):**
 - OS: Windows 10 19H1
 - Franz 5.0.1

**Comment by chrisheyward** [comment]
I second this. Notifications not working for WhatsApp either and this is on a fresh install of Windows 10 and first time using Franz. All notification settings are enabled. Also checked Android Message and Messenger too and I never got a notification sound or push notification. Franz gets a flag to notify you that you have notifications, but other than that, I get none.

**Comment by dzeidzei** [comment]
No one seems to care... Got to wonder if someone is paying for this sort of service.
