### ISSUE TITLE
Does not start unless Google Analytics domains are resolvable

### ISSUE THREAD

**Issue by alessio-signorini** [meetfranz/franz#1475]
**Describe the bug**
Google Analytics domains seem to be necessarily reachable/resolvable for the app to work. In particular, unless both
* www.google-analytics.com
* www-google-analytics.l.google.com

are resolvable (by DNS) the application will not start nor offer to login. There will just be a blue screen.

**To Reproduce**
1. Add the following lines to your `/etc/hosts` file
```
0.0.0.0 www.google-analytics.com
0.0.0.0 www-google-analytics.l.google.com
```
2. Start the app

**Expected behavior**
The app should load normally.

**Screenshots**
![Screen Shot 2019-06-08 at 00 46 57](https://user-images.githubusercontent.com/453354/59137219-f628c200-8986-11e9-995f-b56b280a4ce3.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14.5)
 - Version: 5.1.0.1337

**Comment by yucolabjames** [comment]
Why is Google analytics required? are our usage being tracked?

**Comment by jorgesumle** [comment]
I cannot reproduce it. The program works fine for me blocking Google, so maybe they solved the issue or it is something with MacOS. I'm using GNU/Linux.

**Comment by jorgesumle** [comment]
I found [Ferdi](https://github.com/getferdi/ferdi#what-makes-ferdi-different-from-franz), which takes privacy more seriously.
