### ISSUE TITLE
Could not validate Custom Website server

### ISSUE THREAD

**Issue by sNiXx** [meetfranz/franz#1479]
**Describe the bug**
When trying to add a custom website, upon clicking "Save service" the error message "Could not validate Custom Website server" appears right below the "Custom server" line. I'm trying to add my own Nextcloud server, which is reachable via the provided URL.
When I had a quick look at the console, it stated "ERR_TOO_MANY_REDIRECTS". The server URL (cloud.server.com) redirects to another URL (mycloudserver.duckdns.org) and the latter redirects to the IP - maybe this is related?

**To Reproduce**
1. Go to 'Available services'
2. Click on 'Custom Website'
3. Add the 'Name' and the 'Custom server'
4. Click on 'Save service'
5. The following error appears: "Could not validate Custom Website server"

**Expected behavior**
As with other URLs, the website should subsequently be loaded

**Screenshots**
![Error1](https://user-images.githubusercontent.com/3066873/59417089-e7973c00-8dc6-11e9-8878-f07c62027a21.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox, Brave (latest versions)
 - Version: 5.2.0-beta.2

**Comment by Techsigns** [comment]
Same here, seems to be a problem when entering subfolders instead of (sub)domain only. https://cloud.myserver.com works, https://cloud.myserver.com/folder doesn't.

**Comment by YOUR1** [comment]
I've tried to add a server on a different port then 80 (i.e. http://somesite.local:8080), also not working.

**Comment by filipbartek** [comment]
I am experiencing the error message "Could not validate custom Custom Website server." when I try to save the custom server `https://email.seznam.cz/`. Adding the custom website `https://www.seznam.cz/` works fine (but does not suffice as an alternative to the former website).

* OS: Ubuntu 18.04
* Franz client version: 5.1.0

**Comment by YOUR1** [comment]
I think the problem is in the custom website plugin itself, it does a validate on the given URL, but I don't think its following the redirect. OR NodeJS is having issues accepting the ssl certificates.

**Comment by numerosept** [comment]
having the same issue. Any update on this ?

**Comment by promarcel** [comment]
I have the same problem. Same requirements as all others.

But I was able to find a quick workaround to get around it: Open your Franz data folder (at Windows in your APPDATA). Navigate to the `recipes` folder and open up `franz-custom-website`, open & edit the file `index.js` and remove the whole `validateUrl` async function.
After this reload/restart Franz to apply the code changes. Now any URL can be used. Just a workaround, no fix.

**Comment by sNiXx** [comment]
Sad to say that, despite the boasted claims, custom websites are still not working correctly in the latest release (5.4.0). I especially take issue with the statement that user feedback has been implemented to improve the feature, because we still have no official comment and it's been over four months. Please fix asap, @adlk!
@promarcel: Thanks for the hint, I will try it out!
