### ISSUE TITLE
[linux] Shortcuts for recipes should be consistent with those on browser tabs

### ISSUE THREAD

**Issue by alecive** [meetfranz/franz#148]
I think that the current shortcut choice (at least on linux, probably on Windows too) doesn't make much sense. Usually, browser tabs have an `Alt+1, 2, 3` shortcut, whereas on Franz we have a `Ctrl+1,2,3` shortcut. That comes from the fact that I think it's a norm to assume that the `Ctrl` shortcuts are used by the system and/or the web app currently running.

@stefan would there be a chance to change the `Ctrl` to `Alt` ? I'd be glad to do a PR if you can show me where to look at.

**Comment by alecive** [comment]
Without exactly 0 time spent looking at the code, [this quick search](https://github.com/meetfranz/franz/search?utf8=%E2%9C%93&q=ctrl&type=) shows that there are not many places where this should be changed, so it would be a quick fix I assume.

**Comment by adlk** [comment]
Thanks for bringing this up!
Windows is using `Ctrl` as a trigger for switching between tabs. So this would just apply for Linux.

I'm actually working on the shortcuts right now so I'll take care of this.

**Comment by alecive** [comment]
Thanks for the help!

I don't care about windows at all (I just use it very rarely), but overall I think this should apply also to windows, for two reasons: i) consistency ii) the same thing I said about browsers that use `Alt` for tab switching is true on windows.

**Comment by adlk** [comment]
You would be surprised how many people care about windows :smile:

Ad consistency: tab switching in windows works with the `Ctrl` (tested with edge and chrome)

**Comment by alecive** [comment]
Ok then (I guess it's only firefox then that uses `Alt`), fine with me! :+1:

**Comment by mroeling** [comment]
FYI in FireFox Windows, it's ctrl too... Which makes sense, since Alt is primarily used as navigation through menu items (Alt + underlined letter). Also, ctrl-tab is in-app navigating through the tabs, whereas alt-tab is navigating through all windows on system level.

**Comment by alecive** [comment]
Correct! I don't know why I was sure about that `Alt` thing in windows.

**Comment by Wouter0100** [comment]
Here, Chrome on Ubuntu, both works. Although, I'm used to using `Ctrl` as this was in the previous versions of Franz the same (and in Chrome). Maybe it would be awesome to make this custom/changeable.

**Comment by adlk** [comment]
@Wouter0100 I might have been a little too quick to replace `ctrl` on linux as I believe both options could/should work.

But tbh, I don't use linux with desktop environment that much to have proper opinion on that. What do you think @alecive @mroeling @Wouter0100 ?

**Comment by alecive** [comment]
Having the option would be great! But to me all browsers work with `Alt` (even chrome), so I thought that was the standard on Linux.

**Comment by mroeling** [comment]
Configurable would be nice, 
To me, I've only seen ctrl+<#> as combination, but this could be different on non-us keyboards. But I would prefer ctrl.

@alecive , @Wouter0100 , curious: what keyboard do you use?

**Comment by alecive** [comment]
@mroeling as a matter of fact, that makes sense! I have an italian configuration keyboard, so that may be the culprit.

**Comment by Wouter0100** [comment]
@mroeling US QWERTY keyboard. 
@adlk I wouldn't replace `ctrl` indeed, maybe an additional `alt` shortcut or configurable.

**Comment by adlk** [comment]
👍 thanks for your input.

I'll offer customizable controls at one point but let's stick with `ctrl` and  `alt` on Linux for now :)
