### ISSUE TITLE
Nothing shows on Touchbar in 5.2.0-beta.2

### ISSUE THREAD

**Issue by OJ7** [meetfranz/franz#1480]
After updating to 5.2.0-beta.2, the touchbar does not show any options on Mac. Downgrading back to 5.1.0 fixes the issue so something changed between the releases that broke it.

**Comment by ClaudiaReuvers** [comment]
I have the same issue after updating to 5.2.0-beta.2

**Comment by ClaudiaReuvers** [comment]
I've updated to 5.2.0-beta3 today, and now the touchbar shows options again 👍
