### ISSUE TITLE
Toggl is broken (5.2.0-beta-2)

### ISSUE THREAD

**Issue by Emptyfruit** [meetfranz/franz#1481]
**Describe the bug**
Since update to 5.2.0-beta.2 Toggl service hangs 100% when loaded or enabled.

**To Reproduce**
1. Switch to Toggl or Disable/Enable it

**Expected behavior**
Toggl loads successfully

**Screenshots**
![Screen Shot 2019-06-14 at 13 06 06](https://user-images.githubusercontent.com/14968783/59497839-43d08d80-8ea5-11e9-95ff-57ed846afb26.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6

**Comment by Emptyfruit** [comment]
Reload hotkey doesn't work also

**Comment by jeffmitchel** [comment]
Confirming this. Toggl worked prior to beta.2 and hangs since the update. OS: macOS 10.14.5

**Comment by selwynorren** [comment]
I can confirm this for Elementary OS 5 as well

**Comment by Ruluk** [comment]
Confirming this too here.

**Comment by Ruluk** [comment]
The workaround in #1483 seems to work here as well (sometimes).

**Comment by jeffmitchel** [comment]
Thank you @Ruluk. It works inconsistently for me and sometimes not at all. Even when it does work, changing the view breaks it.

**Comment by jeffmitchel** [comment]
Franz just updated to 5.2.0-beta.3 (1437) and Toggl appears to be functioning correctly.

**Comment by Ruluk** [comment]
I've seen this fine after the update. I suggest closing this issue.

**Comment by selwynorren** [comment]
Even though this does fix the issue, its only because electron was downgraded (I presume temporarily) so its a workaround, but not a fix.
