### ISSUE TITLE
Cannot sign into Google Hangouts

### ISSUE THREAD

**Issue by arlenn** [meetfranz/franz#1483]
**Problem**
Hangout provider starts and presents with the standard google Hangouts login screen.  Cursor will not appear in user-name box, Screen will not accept keystrokes.

**To Reproduce**
1. Go to 'Hangouts provider
2. Click on username, no cursor appears, will not accept keystrokes
3. Cannot log-in to hangouts

**Expected behavior**
Hangout provider starts and presents with the standard google Hangouts login screen.  clicking in username, cursor appears, accepts keystrokes, I log in.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by djshadowxm82** [comment]
@adlk This is breaking just about every google service and this is breaking many people's work flow. Can we please get this issue looked at sooner than later please?

**Comment by Wouter0100** [comment]
Found a workaround, when the service is loaded, go to settings and disable spell check. Close settings, login to the service(s) and enable it again. Maybe restart franz afterwards.

**Comment by arlenn** [comment]
Bizarre, but confirmed :)

However I got my password incorrect, and it's the act of simply toggling Spell-Check, not its position.
The provider "stalled" after entering the correct credentials, and I did have to restart Franz (not just the app) to continue to the normal hangouts page.

**Comment by Wouter0100** [comment]
Hmm, only opening settings seems to fix it.

**Comment by beck** [comment]
Slacks that use google for authentication are also broken.

**Comment by incace** [comment]
> Found a workaround, when the service is loaded, go to settings and disable spell check. Close settings, login to the service(s) and enable it again. Maybe restart franz afterwards.

What if spell check is already disabled?

**Comment by Wouter0100** [comment]
> > Found a workaround, when the service is loaded, go to settings and disable spell check. Close settings, login to the service(s) and enable it again. Maybe restart franz afterwards.
> 
> What if spell check is already disabled?

Enable it and disable it. Play around a bit ;)

**Comment by Ruluk** [comment]
Open settings or enabling/disabling spellcheck doesn't seem to fix anything here. Sorry.

**Comment by ralts00** [comment]
Check please check versión 5.2.0-beta.3 (5.2.0-beta.3.1437),
Works for me

**Comment by Ruluk** [comment]
I've seen this fine after the update. I suggest closing this issue.
