### ISSUE TITLE
Unable to paste images in slack

### ISSUE THREAD

**Issue by ePascalC** [meetfranz/franz#1485]
Using any picture, I can do a CTRL+C and then CTRL+V in slack in the browser.
The CTRL+V used to work fine some weeks ago, but I suppose there has been an update of Franz and since then the paste does not work anymore in a Slack Service.

**Comment by jmartsch** [comment]
Same problem here

**Comment by bab5470** [comment]
Happening for me too. I paste images constantly - enough so that I may have to stop using Franz and go back to the official slack client.

**Comment by junalmeida** [comment]
Same here

**Comment by bab5470** [comment]
Upgrading to 5.0.0 beta 3 (released today) resolved this issue for me - FYI.

**Comment by ePascalC** [comment]
5.2.0 beta 3 did it! Thanks.
