### ISSUE TITLE
Spellcheck is always on even though it's disabled in settings

### ISSUE THREAD

**Issue by jobo90** [meetfranz/franz#1486]
**Describe the bug**
I updated to the newest Franz Beta version 5.2.0-beta.2 and noticed right away that many words in English were underligned. I checked and disabled the spell checking but no matter what I try it still underligns nearly all the English words. My system language is German.

**Expected behavior**
No red underligned words for any service and any word.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/34029589/59568011-19352f00-9075-11e9-91f5-095bf0a10872.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 (Build 17763.134)
 - Franz Version 5.2.0-beta.2

**Comment by janmyler** [comment]
I experience similar issue, however, in my case it occurs with many English contractions. Also, the spellcheck kicks in even if it's disabled in the settings.

![image](https://user-images.githubusercontent.com/718501/59849971-050a6e00-93a4-11e9-9bfd-4db7c39aa1e5.png)

**Desktop:**
- OS: macOS 10.13.6 (17G7024)
- Franz Version 5.2.0-beta.2

**Comment by janmyler** [comment]
The issue does not appear anymore for me in 5.2.0-beta.3. 🙌

**Comment by jobo90** [comment]
Yep, same here. Electron was downgraded and this seems to have done the trick.

**Comment by magiker** [comment]
Version: Version 5.5.0-beta.4 (5.5.0-beta.4.1756) on OS X.

Spell checking is always on when Franz is started. To disable it needs to be turned on, then off, in settings.
