### ISSUE TITLE
Flat logo/icon

### ISSUE THREAD

**Issue by alecive** [meetfranz/franz#149]
The website uses flat design.
The icon on the slack channel uses flat design.
There's a franz icon on the website (the one used for plugins) that uses flat design.

Why not moving to flat design for the franz logo? That gradient and white border could be removed and that would be it. I can take charge of that if you want.

**Comment by alecive** [comment]
Here's an example!!


![logo](https://user-images.githubusercontent.com/4378663/32106308-48a1698c-baf9-11e7-8d3f-05fe4f54a200.png)

**Comment by adlk** [comment]
I have tried that in the past and while I like the flat logo as a standalone graphic. It doesn't work well in the context of the dock or taskbar as it looks a little _pale_ in comparison to other apps.
![Dock](https://user-images.githubusercontent.com/3265004/32161349-825ee736-bd55-11e7-91dc-af0e4d1e6f44.png)

I'm planning to do a redesign of the brand when Franz 5 officially leaves it's beta state (if this is a thing 😄)

**Comment by alecive** [comment]
Ha ha okay then! Closing this (for now :sunglasses:)

**Comment by ingebretsen** [comment]
Have you seen this one...it's really nice! https://www.sketchappsources.com/free-source/1851-franz-icon-redesign-sketch-freebie-resource.html

**Comment by danjessen** [comment]
Yeah, I'm also using that one. Looks great.
