### ISSUE TITLE
Freeze when Spotify embedded link in a Slack channel

### ISSUE THREAD

**Issue by Kernael** [meetfranz/franz#1490]
**Describe the bug**
Franz freezes when a Spotify embedded link is displayed in a Slack channel

**To Reproduce**
1. Go to a Slack service
2. Click on a channel with a message containing an embedded Spotify player link
3. Try to switch channel, type text, scroll, ...
4. Franz becomes unresponsive

**Screenshots**

<img width="337" alt="image" src="https://user-images.githubusercontent.com/10853726/59673939-7ab6e400-91c2-11e9-9b95-9fdd41d31f57.png">

**Versions**
 - OS: macOS Mojave 10.14.5
 - Franz: 5.2.0-beta.2

**Additional context**
This doesn't seem to occur when the Spotify player preview is hidden by clicking the small arrow

**Comment by olbrew** [comment]
Just noticed the exact same behaviour. Had a Spotify embed open in a thread in the sidebar and couldn't use Slack at all anymore until I reset it.

**Comment by Gaboris** [comment]
Might be the same problem I'm having with Discord where if YT embeds are played the whole service freezes if on switching channels.

**Comment by olbrew** [comment]
Reverting Electron fixed this as well as in #1492. You can close this as well :).
