### ISSUE TITLE
Discord freezes on channel/server switching

### ISSUE THREAD

**Issue by Gaboris** [meetfranz/franz#1492]
**Describe the bug**
If an embedded YT video has been launched on the current Discord "page" the services will fully freeze if a new page is loaded by switching channels/servers.
It also requires Franz to be reloaded to work again. Just reloading the service won't work.

**To Reproduce**
1. Open Discord service
2. Find an embedded YT video
3. Start it. No need to actually watch any of it
4. Try to switch to another channel or server
5. If the video is left running(happens either way) the sounds keeps playing after the service has frozen and all other services work fine

**Expected behavior**
Franz probably fails to shut down the YT player when Discord tells it to and that causes the problem so at least have an internal check should be implemented that handles such bugs.

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate 64bit Hungarian
 - Browser Firefox, Opera, Vivaldi, Chrome, Blisk even IE
 - Version 5.2.0 Beta-2

**Comment by M0UL** [comment]
already reported `[here](https://github.com/meetfranz/franz/issues/1490)`

**Comment by Gaboris** [comment]
@M0UL

Yep I know, I've actually made a post about my problem being related in that thread already. Still thanks about the heads up. :D

Also, since that issue limits itself to a single service like mine it might be useful to keep these things separated for the sake of searches.

**Comment by Gaboris** [comment]
Seems like reverting the Electron version back solved the problem so I'll close this now. :)
If anything changes I'll be back.
