### ISSUE TITLE
Discord - screen/application window sharing not working

### ISSUE THREAD

**Issue by infide1** [meetfranz/franz#1494]
The screen/application sharing during a video chat in Discord is not working

### Expected Behavior
During a video call, clicking on the screen sharing icon displays a window with a preview of your desktop. Optionally you can switch to application sharing that shares only a window and not entire desktop

### Current Behavior
The preview of the desktop is not shown and the share button is disabled
Same goes for the application sharing

### Screenshots (if appropriate):
https://i.postimg.cc/Dzj8d1Td/screenshot-78.png

### Steps to Reproduce (for bugs)
1. Start video call
2.Click on "start screen share icon"
3. try to share desktop

### Your Environment

* Franz Version used: 5.1.0
* Operating System and version: win 10 pro 1903

**Comment by y3rt** [comment]
Same on Mac OS 10.15.4 Franz: Version 5.3.3 (5.3.3.1582)

**Comment by AdrianCarreno** [comment]
I can confirm this. It happens with Franz on Pop_os! 20.04 and Windows 10.
