### ISSUE TITLE
unconventional behaviour for "keep franz in background"

### ISSUE THREAD

**Issue by D33pTh0ught** [meetfranz/franz#1497]
If "Keep Franz in background when closing the window" is enabled the window does not get closed at all and is still visible in the taskbar.
In combination with the setting "Minimize Franz to system tray" the window closes correctly again but the minimize button now also closes the window (so both "close" and "minimize" do the same).

Problem:
- No possibility to get the expected behaviour of "close" and "minimize" while still keeping the application in the system tray.

Solution:
- If "Keep Franz in background when closing the window" is enabled the close button should remove the application from the taskbar while also keeping Franz in the system tray.

**Comment by imaginarny** [comment]
This is very old issue which I fixed once but back in version v5.2.1-beta.1 it was reintroduced and got into stable even if I was pointing it out.

It was mentioned in serveral issues: #468, #902, #763, #1006, probably even more. Some of them were described misleadingly, the last one is spot on.

Past pull request which was merged was #1038, gif with fixed behaviour included.

This is the commit which reintroduced this problem: [#1344](https://github.com/meetfranz/franz/commit/78a372272d5001e2033eeddafbb57cf42c2f666a). No idea what was `fix(Windows): Fix losing window when "Keep Franz in background" is enabled`. Basicaly, it added one condition which I removed to fix this issue.
