### ISSUE TITLE
No gmail login or interaction 

### ISSUE THREAD

**Issue by ralts00** [meetfranz/franz#1501]
When I add the Gmail service you can not write in the input to log in.

**Comment by bzajacc** [comment]
I have the same issue, BUT you can type passowrd, but you cant see it, try to enter yours and hit enter - for me its just login, but showing blank page.

It's not only with gmail, but google calendar or google chat not working as well..

Mac OS 10.14.5
Franz 5.2.0-beta.2.1423

**Comment by Wouter0100** [comment]
Duplicate of #1488 and #1483

**Comment by ralts00** [comment]
Solved in the versión 5.2.0-beta.3 (5.2.0-beta.3.1437)
