### ISSUE TITLE
Can't connect to Franz online services

### ISSUE THREAD

**Issue by julian916** [meetfranz/franz#1502]
**Describe the bug**
I cannot login to Franz account in my Mac (its in my work). Since Wednesday 19 of June. That week my Mac had been updated so it may cause the issue.

**To Reproduce**
1. Open Franz

**Expected behavior**
normal login using my google account.

**Screenshots**
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/25458451/60116659-dea35480-974e-11e9-9fe1-68a4eb16178b.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/25458451/60116697-ebc04380-974e-11e9-9649-c9c185517635.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Version: app Franz 5.1.0

**Comment by radaiko** [comment]
I got a similar problem.

Login at Windows 1809 is not working.

400 Bad Request

![image](https://user-images.githubusercontent.com/15850003/60171696-6189e500-980b-11e9-84c2-af11d7f939e7.png)
![image](https://user-images.githubusercontent.com/15850003/60171745-7f574a00-980b-11e9-8e68-23b07c7df967.png)

**Comment by julian916** [comment]
In my company they found out that in our net they were blocking the login of this. 
Solution: Had to login from other hotspot then return to normal wifi.

**Comment by radaiko** [comment]
same for me.

@julian916 thank you 👍
