### ISSUE TITLE
Microsoft Teams - re-authenticaton required after re-opening the app

### ISSUE THREAD

**Issue by janegilring** [meetfranz/franz#1503]
**Describe the bug**
When re-opening the app, re-authentication is required against Microsoft Teams.

**To Reproduce**
1. Go to a Microsoft Teams workspace and sign in
2. Close Franz
3. Open Franz
4. Go back to the same Microsoft Teams workspace

**Expected behavior**
The session against Microsoft Teams should still be active

**Actual behavior**
Prompted for credentials

**Desktop (please complete the following information):**
 - OS: Windows 10 (1903)
 - Version: 5.1.0

**Additional info**
I have 3 Teams services added, one using a Microsoft account and two using Azure AD accounts. The issue seems to occur only for the two which uses Azure AD accounts.

**Comment by pvdochtend** [comment]
It's also the same issue with Outlook

**Comment by JoostGadellaa** [comment]
For me the issue only started after I changed my password for both services. In the past it was necessary to re-add the service after a password change, but this time that didn't work either.
