### ISSUE TITLE
Office365 - Outlook opens in some kind of lightweight mode (like webmail in 1990)

### ISSUE THREAD

**Issue by pvdochtend** [meetfranz/franz#1504]
**Describe the bug**
Outlook opens in some kind of lightweight mode. Light version is not enabled in the settings

**To Reproduce**
1. Start Franz
2. Click Office 365 - Outlook
3. Login
4. See old version of webmail

**Expected behavior**
Would expect the normal version. If I open it in a normal (Google Chrome) browser it looks like the normal version.

**Screenshots**
![image](https://user-images.githubusercontent.com/3694460/60177457-3b6b4180-9819-11e9-8a09-fd1f6e072918.png)

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by pvdochtend** [comment]
After reinstalling Franz it's gone....

**Comment by pvdochtend** [comment]
Anders after a few restarts it's back... :(

**Comment by jandekkerongit** [comment]
I have this issue aswell. Tried removing Outlook and it was fine for a while, but the next day it reverted back to 1990's mode. I'm running the latest version of Franz on the latest version of OSX.

**Comment by pvdochtend** [comment]
This happens on several of mine workstations. The only real solution is apparently to delete the correct folder from: "%AppData%\Roaming\Franz\Partitions". But it's very annoying.

**Comment by franciscopinheir** [comment]
I have the same problem.

**Comment by jonnyparris** [comment]
Same issue here too - started today for some reason :(
