### ISSUE TITLE
Notification for Google Calendar not working

### ISSUE THREAD

**Issue by nickel715** [meetfranz/franz#1508]
**Describe the bug**
Notification for Google Calendar not working.

**To Reproduce**
1. Add have google calender service configured
2. Make sure Desktop notifications for google calender are enabled in the settings
3. Create a appointment in 35mins and make sure the appointment has a notification for 30min before 
4. Wait until it is 30 min before the appointment

**Expected behavior**
I get always notified about my calendar appointments.

**Desktop**
 - OS: Mac OS 10.14.5
 - Franz Version 5.2.0-beta.3

**Additional context**
* I did the same steps in Chrome there it is working
* Notification in Franz are enabled
* Maybe related issues: #1269, #666

**Comment by nickel715** [comment]
Some times, in very rare cases it works

**Comment by alejom99** [comment]
I have the same problem. Any updates? Thanks.
