### ISSUE TITLE
Is there a way of getting Wire into Franz again?

### ISSUE THREAD

**Issue by itstheandre** [meetfranz/franz#1510]
**Is your feature request related to a problem? Please describe.**
I think Franz used to have Wire back in the day, but not anymore. Is it possible to add it once again?

**Describe the solution you'd like**
Having Wire as another service

**Describe alternatives you've considered**
I know other messaging aggregation apps do this, so was jsut wondering if franz could have it too.

**Comment by BenoitFroment** [comment]
+1

**Comment by bittner** [comment]
Some background information for those not knowing their service:

- Seems like another usual Electron app: https://wire.com/en/features/
- There also seem to be Enterprise plans, hence Franz can implement their usual Rocket-Chat strategy.

If it is true that it was in the list of supported services, was there a specific reason why it was pulled out?

**Comment by bittner** [comment]
Related issues on Wire support:

- https://github.com/meetfranz/franz/issues/328#issuecomment-346773534
- https://github.com/wireapp/wire-webapp/issues/1209#issuecomment-300717950

**Comment by blopa** [comment]
+1

**Comment by bittner** [comment]
I created a Franz recipe for Wire. https://gitlab.com/sckreuzlingen/franz-recipe-wire

It's simple to install by following the instructions in Franz > <kbd>+</kbd> > Available services > <kbd>Custom Services</kbd>. (You may have to create the mentioned "dev" folder manually, especially when the <kbd>Open folder</kbd> doesn't react.) After reloading Franz you'll find a "Wire" recipe in the <kbd>Custom Services</kbd> tab.

PR https://github.com/meetfranz/plugins/pull/436 adds a link to the Custom Service to Franz's plugins repository.

**Comment by sergiufalcusan** [comment]
@bittner , i was just creating a recipe by myself as well. And I did it exactly like you but it didn't work for me. To make it work I just copied the code from whatsapp in index.js

`"use strict";

module.exports = Franz => class Messenger extends Franz {
  overrideUserAgent() {
    return window.navigator.userAgent.replace(/(Franz|Electron)([^\s]+\s)/g, '');
  }
`

**Comment by bittner** [comment]
@sergiufalcusan Can you describe "it didn't work" a bit more in detail? Do you know why it didn't work for you? Which operating system are you using?

**Comment by sergiufalcusan** [comment]
I am using ubuntu 18.04, franz version 5.0.0

it was saying something like: current browser version is not supported

**Comment by reginastracii** [comment]
didn't work for me too. with the "whatsapp" index.js it does load, but after log in just loops back to the login page.

**Comment by Wheest** [comment]
Replacing `index.js` with the one suggested by @sergiufalcusan didn't load the service on Debian 10, Franz 5.5.0.  Has the custom service syntax changed in recent versions?

**Comment by bittner** [comment]
I can only confirm again, I use [Ferdi v5.5.0](https://github.com/getferdi/ferdi/releases) and the [Wire plugin](https://gitlab.com/sckreuzlingen/franz-recipe-wire), which works flawlessly (as much as Wire permits).
