### ISSUE TITLE
Error adding custom website

### ISSUE THREAD

**Issue by willemjvermeulen** [meetfranz/franz#1517]
**Describe the bug**
Unable to add custom website
**To Reproduce**
1. Add a new service
2. Use an IP or a url without www. in the custom server field
3.  Save service

**Expected behavior**
I expected a new service to be saved

**Screenshots**
![image](https://user-images.githubusercontent.com/778375/60576056-900c4080-9d74-11e9-925f-56fc5436b973.png)

**Desktop (please complete the following information):**
 - OS: win 10 and Mojave
 - Browser 
 - Version 5.2.0beta4

**Comment by YOUR1** [comment]
Same as https://github.com/meetfranz/franz/issues/1479
