### ISSUE TITLE
All Services Loading Forever

### ISSUE THREAD

**Issue by SemnoSao** [meetfranz/franz#1523]
**Describe the bug**
Whenever I open the app all my services show: "Loading *name of the service*" and it never finishes.

**To Reproduce**
1. Open the app
2. Click on any service
3. Wait Indefinitely
4. Services never load

**Expected behavior**
Services should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/16153554/60821253-8a01cf80-a179-11e9-95f0-8a89fa075449.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Chrome
All updated to the latest versions.

**Additional context**
It was all working fine 2 days ago.

**Comment by Kombustor** [comment]
Same OS, same issue. The problem is probably here:
![Devtools Error](https://user-images.githubusercontent.com/4238281/60887922-cf93ca80-a255-11e9-9a55-9ff9659a0075.png)

**Comment by odelucca** [comment]
Same issue here.

**Comment by odelucca** [comment]
I think this can be a compatibility issue with Cinnamon 4.2

**Comment by GiulioCentorame** [comment]
Same issue with Firefox on the same OS, in my case it stopped working after the update.

**Comment by PieterWaegeman** [comment]
I got the exact same issue. Running Arch Linux with the latest Google Chrome Beta. I have this issue since a week now. Anyone got a fix for this? Or do you need more feedback or steps that I can provide more info?

**Comment by odelucca** [comment]
Pieter, they have already fixed that issue. Just update your Franz by running:
```console
yay -S franz
```
(You can also run it with `yaourt` or other client

That should fix your problem
