### ISSUE TITLE
No banner notifications in Mac 

### ISSUE THREAD

**Issue by awgordon** [meetfranz/franz#1528]
I'm no longer getting any banner notifications for any of the services. Have tried enabling/disabling notifications on a per-service basis, doesn't change anything. I checked Mac notifications center and everything is enabled there. Notifications for other apps/programs are working fine.

OS Mojave 10.14.5
Franz 5.2.0 and 5.2.0-beta.4

**Comment by Schoonzie** [comment]
I'm having the same issue.

**Comment by jaminroe** [comment]
Same here. Related to #1409

**Comment by felixpenrose** [comment]
None of my notifications are working on Windows 10 either. I've resorted to downloading individual client software to replace Franz as I keep missing messages.

Franz 5.2.0, release 4.2.4 win 32 / x64

**Comment by SomniumDigital** [comment]
Having the same problem on MacOS 10.14.5 running Franz Version 5.2.0 (5.2.0.1455)

**Comment by robbykim** [comment]
same, macos 10.14.5, franz 5.2.0

**Comment by sushinger** [comment]
same here on 10.11 and 10.13

**Comment by felixpenrose** [comment]
> None of my notifications are working on Windows 10 either. I've resorted to downloading individual client software to replace Franz as I keep missing messages.
> 
> Franz 5.2.0, release 4.2.4 win 32 / x64

I received an update today which has fixed the notifications. V5.2.1-beta-1

**Comment by jaminroe** [comment]
Doesn't look like it's completely fixed. Seems pretty inconsistent when it comes to badge indicators. My Android Messages doesn't show an unread badge and Slack doesn't either
