### ISSUE TITLE
Image of the sender for WhatsApp notifications

### ISSUE THREAD

**Issue by Jendker** [meetfranz/franz#1529]
It would be nice if the photo of the sender would be also included in the WhatsApp notification. Would it be possible with Franz?

**Comment by philb61** [comment]
Franz is just a wrapper to various services' web apps.  If web.whatsapp.com doesn't show this, there's no way Franz could.

**Comment by Jendker** [comment]
Any WhatsApp client does it, I am not sure why Franz couldn't do it. It is also working with Rambox.

**Comment by philb61** [comment]
Apologies, I wasn't aware that the web app does it...I parsed it as you meaning the icon changing, not the notifications themselves...

**Comment by skumblex** [comment]
+1
The web client of WhatsApp shows the image of the sender so it should be possible for Franz to do the same. The strange thing is: For me Franz shows the picture for group chats but not for chats with individual contacts.
