### ISSUE TITLE
Display services from current workspace on touch bar (Macbook Pro)

### ISSUE THREAD

**Issue by tswistak** [meetfranz/franz#1530]
**Is your feature request related to a problem? Please describe.**
I really would like to use Macbook's touchbar with Franz, but unfortunately it doesn't show services from my current workspace what is a bit annoying.

**Describe the solution you'd like**
Every time I switch workspace, it would be nice to see on touch bar only services that are in that specific workspace.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jcalvillo** [comment]
**alternatives considered**
Although there are keyboard shortcuts (command+1 etc), it is difficult to program these globally. *BetterTouchTool* might be an option, but I do not see how to configure an app-specific toolbar that is dynamic to the Franz workspace.

**additional context**
The default macOS touch bar is simply displaying ALL TABS open (like a browser), but the non-workspace touchbar buttons don't actually result in an action when pressed. 

**screenshots**
<img width="94" alt=" 2019-08-11 at 12 00 39 AM" src="https://user-images.githubusercontent.com/29272115/62827414-ac4e9900-bbce-11e9-934c-8b7e69f236c8.png">
<img width="1092" alt=" 2019-08-10 at 11 57 43 PM" src="https://user-images.githubusercontent.com/29272115/62827415-ac4e9900-bbce-11e9-8b2d-58217986ca51.png">

**Comment by ValentinTaleb** [comment]
Is there any update about this issue?

That would be great to see this bug fixed :)
