### ISSUE TITLE
Microsoft Teams Not loading

### ISSUE THREAD

**Issue by strigona-worksight** [meetfranz/franz#1535]
**Describe the bug**
Microsoft Teams does not load correctly. When launching, you get a white page and after a period of time a Teams error page appears with a button to "refresh" or sign out. I have tried deleting the service and adding it again. 2 other coworkers are experiencing the same issue.

**To Reproduce**
1. Add Teams
2. Open Teams and login
3. Close Franz
4. Open Franz
5. Teams now just has a white screen and after a few minutes an error appears.

**Expected behavior**
Teams loads correctly

**Screenshots**

![Franz-Teams1](https://user-images.githubusercontent.com/13368604/61476011-eebee600-a940-11e9-87bc-f0ff21cc809a.png)
![Franz-Teams2](https://user-images.githubusercontent.com/13368604/61476020-f1b9d680-a940-11e9-8837-7893ade5c1f1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04, kubuntu 19.04
 - Franz: Version 5.0.0, Release 4.0.4

**Comment by strigona-worksight** [comment]
I have upgraded to
```
Version: 5.1.0
Release: 4.1.4 / linux / x64
```
and am still experiencing the same issue.

**Comment by andyrozman** [comment]
Same problem. Teams just don't load... I had same problem with Franz 5.0.1, which is why I upgraded.

OS: Ubuntu 18.04 LTS
Franz: 5.1.0, amd64 (downloaded 24.7.)

**Comment by strigona-worksight** [comment]
I have upgraded Franz to 5.2.0 and still experiencing the same issue.

**Comment by marcusboon** [comment]
Same issue.

OS: Windows 10 Pro 1903
Version: 5.2.0
Release: 4.2.4 / win32 / x64

**Comment by binarymelon** [comment]
I'm experiencing the same issue.  I actually have two Teams instances and I only started experiencing this issue on one (starting July 30th), so it must be updates that are slowly rolling out.  Web works fine in Chrome.

OS: Windows 10 Pro
Version: 5.2.0

**Comment by spectrummind** [comment]
Same issue started today (July 30th)
OS: MacOS, Windows Server 2016
Version: 5.2.0

**Comment by Jebroer** [comment]
Still the same with 5.2.1-beta.1 :(

**Comment by brandung-sjorek** [comment]
Same here - MacOS 10.14, Franz Version 5.2.0 and 5.2.1-beta.1.1464 … 

My current “Workaround”: wait with blank-Screen in Franz until Teams reloads itself several times and start to show a screen wich offers to use the “Desktop- or Web-App Version”. There I choose the Web-App Version and Teams starts to work again.

**Comment by cmccandless** [comment]
Also experiencing this. The only workaround that has worked for me is deleting the service, and re-adding it. After this, Teams works until I switch to another service or close Franz.

OS: Ubuntu 18.04
Version: 4.2.1-beta.1

**Comment by fearphage** [comment]
I believe this error thrown from MS's angular is the problem:

![image](https://user-images.githubusercontent.com/23887/62788002-a0a68980-ba8b-11e9-9ebf-46b4cc85cfc9.png)

I don't believe IPC exists inside of the Teams by default. IPC is generally used to refer to the [event bus](https://electronjs.org/docs/api/ipc-main) that electron uses to drive the app. It looks like Franz is trying to establish a bridge to interface with Teams and it's failing in a non-stack traceable way.

**Does anyone know where the source for the Teams plugin/service is stored?** I don't see it listed anywhere:

https://github.com/meetfranz/plugins
https://github.com/meetfranz/plugins-legacy

and Google didn't turn up anything. I also can't access it on disk. It seems Franz is using some method to obscure the source. (`/opt/Franz/resources/app.asar.unpacked` only contains 1 directory: `dictionaries`).

**Comment by fearphage** [comment]
## Workaround? 

1. From Franz menu choose `View -> Service Developer Tools`
2. In dev tools go to `Application -> Clear Storage -> click Clear Site Data` (I had every box selected)
3. From Franz menu choose `View -> Reload Service`

Teams loaded immediately for me. I had already gone through the login process although I don't know if that's required.

**Comment by strigona-worksight** [comment]
That workaround works until you restart Franz - similar to removing/adding the service back.

As for the source of the plugin, I could not find the source online, but for me in Ubuntu, the files can be found here: `~/.config/Franz/recipes/msteams`. A quick read through the files shows very little in way of code injection, just adjusting the userAgent (I did update the injected Chrome version number to 74.x with no behaviour change) and retrieving unread message count.

**Comment by Lomanic** [comment]
I couldn't find in which online repository is defined the MS Teams recipe, but here is a proper fix https://github.com/IsmaelMartinez/teams-for-linux/issues/171#issuecomment-520156196

**Comment by cmccandless** [comment]
@Lomanic where is that snippet meant to be placed?

**Comment by istrasci** [comment]
@Lomanic Yes, I would also like to know where that snippet goes.

**Comment by cmccandless** [comment]
> ## Workaround?
> 1. From Franz menu choose `View -> Service Developer Tools`
> 2. In dev tools go to `Application -> Clear Storage -> click Clear Site Data` (I had every box selected)
> 3. From Franz menu choose `View -> Reload Service`
> 
> Teams loaded immediately for me. I had already gone through the login process although I don't know if that's required.

Simply clearing the cache seems to be sufficient. Uncheck all boxes except those under "Cache".

**Comment by fearphage** [comment]
> Simply clearing the cache seems to be sufficient. Uncheck all boxes except those under "Cache".

I can confirm. I found only clearing the `Application Cache` (last one on the list) worked for me.

**Comment by strigona-worksight** [comment]
This service now appears to be fixed. Franz popped up saying that the service has been updated and needs to be reloaded. There is new code in the ~./config/Franz/recipes/msteams/webview.js to adjust the IPC:

```
window.electronSafeIpc = {
  send: () => null,
  on: () => null
};
```

**Comment by fearphage** [comment]
@adlk Where is the source for the msteams service located?

**Comment by strigona-worksight** [comment]
@fearphage Source appears to have been made public here: https://github.com/meetfranz/Microsoft-Teams

**Comment by tidg** [comment]
> This service now appears to be fixed. Franz popped up saying that the service has been updated and needs to be reloaded. There is new code in the ~./config/Franz/recipes/msteams/webview.js to adjust the IPC:
> 
> ```
> window.electronSafeIpc = {
>   send: () => null,
>   on: () => null
> };
> ```

Hi @strigona-worksight,
When i set the window.electronSafeIpc variable to skip the blank page it works! 
But we lose the notification toaster when some people send me a message :( 
Do you know how to keep the feature of notification?
Thank you again for your advice !

**Comment by strigona-worksight** [comment]
@tidg Good catch - I hadn't noticed that. I would submit an issue on the Teams service: https://github.com/meetfranz/Microsoft-Teams

**Comment by lukiffer** [comment]
@tidg I was able to preserve notifications by instead of unregistering all of the service workers and letting Teams re-register them, instead of overwriting `window.electronSafeIpc`. Not sure if this is actually progress or just a different brand of duct tape.

```js
navigator.serviceWorker.getRegistrations().then((registrations) => {
  for(const registration of registrations) {
    registration.unregister();
  }
});
```

**Comment by tlsimmons88** [comment]
Hello, it is now 5/5/21 and I am getting a blank white screen for Teams in Franz.  Here is my Franz debug info.


"franz": {
        "version": "5.3.3",
        "electron": "4.2.4",
        "installedRecipes": [{
                "id": "discord",
                "version": "1.0.3"
            }, {
                "id": "facebookpages",
                "version": "1.1.0"
            }, {
                "id": "franz-custom-website",
                "version": "1.0.0"
            }, {
                "id": "hangouts",
                "version": "1.0.0"
            }, {
                "id": "irccloud",
                "version": "1.0.2"
            }, {
                "id": "linkedin",
                "version": "1.0.0"
            }, {
                "id": "msteams",
                "version": "1.1.0"
            }, {
                "id": "mysms",
                "version": "1.0.0"
            }, {
                "id": "skype",
                "version": "1.2.2"
            }, {
                "id": "slack",
                "version": "1.0.16"
            }, {}
