### ISSUE TITLE
Does Franz work with Pop!_OS?

### ISSUE THREAD

**Issue by harrisonford** [meetfranz/franz#1536]
That's all, sorry couldn't find info.

**Comment by felixpenrose** [comment]
This isn't an _issue_ is it? It's a question you could answer yourself.

**Comment by harrisonford** [comment]
I only found this snap package in the making 

https://forum.snapcraft.io/t/call-for-testing-franz/4132

Rambox has a snap package just saying, and yes I know it's not really an issue I just wanted some insight from people that may know, sorry for that!

**Comment by alecive** [comment]
PopOS is an ubuntu derivative, so the answer is yes. Just download the `.deb` from the website!

**Comment by harrisonford** [comment]
Yep! They're both debian, I was able to make it work. After using Rambox too I thought it would be cool to have an autocode feature for applying css to services but that's another matter, thanks for the reply.
