### ISSUE TITLE
Password transmitted in plain text via GET-Parameter

### ISSUE THREAD

**Issue by 0x6368** [meetfranz/franz#1537]
**Describe the bug**

These are two bugs, which lead to passwords being saved in the browser history.

First bug:
Microsoft Edge is unable to execute the Javascript code on https://meetfranz.com/login

Second bug:
When you login via https://meetfranz.com/login, the email address and password are transmitted via the GET parameter instead of the POST parameter if a Javascript error occurred or Javascript is disabled. This leads to the email address and password being saved to the browser history and being visible to other users. In the worst case, this could lead to third party websites being able to access the credentials via the Referrer-HTTP-Header.

**To Reproduce**
1. https://meetfranz.com/login
2. Enter any email address and an incorrect password.
3. Click "Login"
4. Check the address bar to see the entered email address and password.

**Expected behavior**
The password should be transmitted via the POST parameter.

**Screenshots**
![meetfranz](https://user-images.githubusercontent.com/7045209/61589059-55dcd480-aba5-11e9-9b7f-9057190b0734.png)

**Desktop (please complete the following information):**
Any with disabled Javascript or an error in the javascript file.

**Smartphone (please complete the following information):**
Any with disabled Javascript or an error in the javascript file.

**Comment by cbierFL** [comment]
I have verified that this is happening in Microsoft Edge 42.17134.1.0 on Windows 10
