### ISSUE TITLE
Electron and Other Packages Outdated

### ISSUE THREAD

**Issue by CptDinosaur** [meetfranz/franz#1539]
**Describe the bug**
Electron and other packges needed updating.
Electron was rolled back from 5.0.3 to 4.2.4, an outdated version, in commit [404c87a](https://github.com/meetfranz/franz/commit/404c87a)

**Expected behavior**
Electron and other packages should be updated to provide better security

**Comment by kitingChris** [comment]
Also some of the services that use browser features would work then better (microsoft teams for example)
