### ISSUE TITLE
Facebook Messenger Service Conversation switching issue

### ISSUE THREAD

**Issue by SebastianS09** [meetfranz/franz#1541]
**Describe the bug**
When on the facebook messenger service, switching between conversation threads leads to the application to lag and then reload the whole service

It appeared after the latest update of the Facebook Messenger app

**To Reproduce**
1. Go to Facebook Messenger Service
2. Click on another conversation thread
3. Lag
4. Service restarts on selected conversation 

**Expected behavior**
Should not lead to reloading service 

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5 
 - Franz Version 5.2.0 (5.2.0.1455)
Releas

**Comment by Donaldini** [comment]
I have the same issue also on same MacOs and Franz version.

**Comment by PetarMetodiev** [comment]
I have the same issue - MacOS 10.14.6 and Franz 5.3.1

**Comment by PetarMetodiev** [comment]
After some poking around I managed to fix this by clearing the cache and reloading the service.
