### ISSUE TITLE
Consolidate Slack Electron instances a la new Slack desktop app

### ISSUE THREAD

**Issue by jpinnix** [meetfranz/franz#1548]
Franz uses an instance of Electron for each Slack workspace, thereby using a massive amount of RAM.

I would like Franz to consolidate the instances of Slack Electron apps used to geometrically decrease memory usage.

The new Slack desktop client has accomplished this by rearchitecting the app to use a single Electron process for all workspaces. I'm assuming that Franz benefits from their web app changes automatically, but can't take advantage of the Electron setup without some modification.

More details on how they accomplished this: https://slack.engineering/rebuilding-slack-on-the-desktop-308d6fe94ae4

**Comment by briankendall** [comment]
I too would love to see this happen.
