### ISSUE TITLE
GMail let open PDF in default system viewer

### ISSUE THREAD

**Issue by Condorello** [meetfranz/franz#1550]
### Feature Description
Add an option for set chromium to open PDF (from gmail for ex.) in the system viewer and not to chrome preview.

### Motivation and Context
Chrome/Chromium viewer isn't 100% compatible with all kind of PDF. And in chrome/chromium this option is present so i think it's not impossible to pass that option from franz to that.

Thanks!

**Comment by kamyweb** [comment]
same issue with custom website app with internal webmail client - zimbra - that open attachments on default system viewer that is not correctly auth and fails. 
Will be great if every app has its own flag "open external link" and choose internal browser - with same session that the opener - or external default system viewer.

**Comment by SciCrea** [comment]
Is this expected in the near future? It is not convenient and pointless to open attachments in the browser. The meaning of the service is lost.
