### ISSUE TITLE
All calls to https://api.franzinfra.com returning 503 - Service Not Available

### ISSUE THREAD

**Issue by ChickenF622** [meetfranz/franz#1554]
**Describe the bug**
Currently no services are being loaded from https://api.franzinfra.com. Instead it's returning a 503 - Service Not Available error.

**To Reproduce**
1. Open Franz or go to https://meetfranz.com/services

**Expected behavior**
Franz should load services.

**Desktop**
 - OS: Ubuntu 19.04
- Browser: Chrome
 - Version 5.2.0

**Comment by insaneadinesia** [comment]
![Screen Shot 2019-07-30 at 10 39 04](https://user-images.githubusercontent.com/23309748/62098839-4a309280-b2b6-11e9-8851-0b40cabd09c3.png)

So do I. My Franz App suddenly cant connect to the service since this morning.

**Environtment Used**
- OS : High Sierra (10.13.6)
- Franz Version : 5.1.0

**Comment by mgilank** [comment]
same here

**Comment by hashtafak** [comment]
Services down..

**Comment by leicozit** [comment]
Houston, we've had a problem.

**Comment by imalisiddique** [comment]
Same here

**Comment by pentatonicfunk** [comment]
same here. :feet:

**Comment by ChickenF622** [comment]
Appears to be back up
