### ISSUE TITLE
Franz dock / taskbar icon does not show number when Slack message received

### ISSUE THREAD

**Issue by DanFMoore** [meetfranz/franz#1558]
**Describe the bug**
The taskbar / dock icon does not display a red number when a new message is received in Slack when Franz is hidden or minimised.

This is similar to #1545, which has been fixed in 5.2.1-beta.1, but that is about the notifications that appear in the corner of the screen, not the taskbar / dock icon, which still remains unchanged.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add slack as a service
2. Login
3. Put another window in front of Franz, or minimise it
4. Receive a message
5. You will get a notification in the corner, but the taskbar / dock icon remains unchanged with no red number appearing on it

**Expected behaviour**
The taskbar dock icon should display a red 1 when a message is received in Slack when Franz is minimise or hidden

**Screenshots**
This screenshot shows a notification for the message, but no number on the taskbar / dock icon:

![Screenshot 2019-08-01 at 16 31 01](https://user-images.githubusercontent.com/837591/62307199-13f04000-b47b-11e9-9b78-6f3b76c2f754.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.4 (18E226)
 - Version: 5.2.1-beta.1 (5.2.1-beta.1.1464)

**Comment by jaminroe** [comment]
Same here. I think this bug was only partially fixed. Guessing it's related to #1528

**Comment by DanFMoore** [comment]
I've updated to Version 5.3.2 (5.3.2.1572) and this issue is still exactly the same.
