### ISSUE TITLE
No unread notification badge for Microsoft Teams

### ISSUE THREAD

**Issue by nirusuu** [meetfranz/franz#1564]
**Description**
When receiving a new chat message, Franz doesn't display a notification badge on Microsoft Teams icon.

**Expected behaviour**
A unread notification badge should be displayed on the MS Teams icon whenever activity is detected in MS Teams.

**Desktop:**
 - OS: Windows Pro 10 10.0.17763 Build 17763
 - Chrome Version 76.0.3809.87 (Official Build) (64-bit)
 - Franz 5.2.0

**Comment by COsborn2** [comment]
Also occurring on Mac OS 10.14.6, Franz 5.2.0.

**Comment by COsborn2** [comment]
As of today this functionality is working again.

**Comment by nirusuu** [comment]
confirmed to work also for me on windows.

**Comment by kasuke5** [comment]
this feature has never worked for me. No notification, no badges nothing at all. The other apps works great Franz 5.3.3

**Comment by riweston** [comment]
I also have this issue with Teams and frequently miss messages

Mac 10.15.1 / Franz 5.3.3

**Comment by trauma717** [comment]
I also have this issue with Teams, and the other services as well, and have missed quite a few messages. For whatever reason, it will sporadically show a badge for a two second window every now and then but I cannot find any pattern

macOS Mojave (10.14.6) / Franz 5.4.1.1703

was planning to purchase application but does not appear the trial is working well enough yet. Only day one, so I will see if it improves.
