### ISSUE TITLE
Will Franz ever support Gitlab?

### ISSUE THREAD

**Issue by ghost** [meetfranz/franz#1565]
!--- Provide a general summary of your changes in the Title above -->

For my small company of 5 (Lucidy) we are looking to use Franz permanently because of its ease in meetings. The only thing stopping us from buying a Premium or Business liscense is the lack of support with Gitlab. Github works but already have everything on Gitlab so this will be more convenient.  

### Feature Description
Add support for Gitlab

### Motivation and Context
* This will ensure people that use Gitlab for their workflow can work with Franz
* This will give many a insentive to buy Franz permanently for their selves or their business. 
* It ensures that people using Gitlab can use Franz to manage their code workflow  

### Mockups, Screenshots (if available):
* Add the option to add Gitlab as Service

**Comment by cmccandless** [comment]
You could add a custom service. Here's an [example for Bitbucket](https://github.com/adgllorente/recipe-franz-bitbucket).
