### ISSUE TITLE
Keyboard shortcuts to switch between Workspaces

### ISSUE THREAD

**Issue by sinstein** [meetfranz/franz#1569]
**Is your feature request related to a problem? Please describe.**
Having created workspaces for various tracks such as `Work`, `Personal` etc, I would like to be able to switch between them using keyboard shortcuts.
I can press <kbd>CMD</kbd>+<kbd>D</kbd> to open the Workspace drawer but need to use my mouse/trackpad to switch between the available options.

**Describe the solution you'd like**
A second level of shortcuts to switch between Workspaces like we have to switch between Services. They could be something like <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>[0-9]</kbd>

**Describe alternatives you've considered**
Perhaps the same shortcuts used for switching services can be utilised. When the Workspace Drawer is open, pressing <kbd>CMD</kbd>+<kbd>[0-9]</kbd> to activate the corresponding workspace

**Comment by dimitar-ebot7** [comment]
I would really love to see this implemented as well. I think implementing the same shortcuts as for the tabs completely makes sense and will be very useful for keyboard power users.

**Comment by sinstein** [comment]
I was looking around the code to add this shortcut myself and found that they already exist:
https://github.com/meetfranz/franz/blob/master/src/lib/Menu.js#L920

Press: 
<kbd>CTRL</kbd> + <kbd>Alt</kbd> + <kbd>[0-9]</kbd> on Windows

<kbd>CMD</kbd> + <kbd>Option</kbd> + <kbd>[0-9]</kbd> on Mac

To switch between workspaces. Index `0` is set for `All Services`. The workspace drawer does not need to be open for this to work.
