### ISSUE TITLE
Greek spell check not working

### ISSUE THREAD

**Issue by EgwOidios** [meetfranz/franz#1574]
**Describe the bug**
Hi,
The Greek spell check is not working in franz 5.2.1-beta.1. I tried a few languages as English, Spanish, Italian and the spell check shows suggestions for the correct word when you made a mistake but not in the Greek languages which i am using. When i write in Greek it marks every word i write with red line even when it's correct spelled. Also i get no suggestions from the spell check either when the word is correct or misspelled. Can you please have a look at this when you got some time.

Desktop 
 - OS: Windows 10 1903
 - Version Franz: 5.2.1-beta 1

**Comment by kmgalanakis** [comment]
I still have the exact same issue!

Desktop
* OS: Windows 10 18362
* Version Franz: 5.4.0-beta.3
