### ISSUE TITLE
whatsapp messages not appearing

### ISSUE THREAD

**Issue by raiteixhikari** [meetfranz/franz#1576]
Whatsapp Message window doesn't display the messages. they look like small chat bubbles but nothing appears from there. 
Every other service is perfectly fine. 

![image](https://user-images.githubusercontent.com/51220356/63349649-61115480-c34b-11e9-8cd5-2ec57ae196dc.png)

**Desktop (please complete the following information):**
 - Fedora 30 / KDE Plasma 5: [e.g. iOS]
 - Chrome
 - Version 5.2.0

**Comment by daniethom** [comment]
I have the same issue. The images in chats shows, but the text messages doesn't display. I tested with Whatsapp web in Chrome and Firefox. That works as expected.

I am running:
 - Fedora 30
 - Franz 5.2.0  - Release 4.2.4 / Linux / x64 (Flatpak install)
 - Chrome Version 76.0.3809.100 (Official Build) (64-bit)
 - Firefox Quantum 68.0.2

**Comment by timrichardson** [comment]
same with me on KDENeon.

**Comment by leandropaz** [comment]
Same issue here:

- Fedora 31
- Franz 5.3.3 - Flatpak install)
- Chrome Version 78.0.3904.87-1
- Firefox 70.0
