### ISSUE TITLE
Instagram service

### ISSUE THREAD

**Issue by nickjannes101** [meetfranz/franz#1579]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instagram as a new service?

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by georgekarapi** [comment]
I think it's time to check again this feature as Instagram has now DMs directly from the browser on https://www.instagram.com/direct/inbox/ (Inspect it as a smartphone on desktop). So it's plausible!

**Comment by kytwb** [comment]
There is already a recipe available here for Instagram:  https://github.com/alexdevero/franz-instagram-recipe. As @georgekarapi said, the inbox URL works if you change your user agent to indicates you are on mobile; that's what the recipe does [here](https://github.com/alexdevero/franz-instagram-recipe/blob/128b1bda8e2c92a09964990233045ffb1eb15eef/index.js#L5). It's missing some bits though to properly pass notifications count to Franz, so it could be improved.
