### ISSUE TITLE
Request - Windows 10 App via Desktop Bridge with support for native Notifications and "My People"-Feature

### ISSUE THREAD

**Issue by Stele77** [meetfranz/franz#158]
It would be amazing to have Franz as a Windows 10 App. This would provide support for native Windows 10 features like native notifications in Action Center, and support for the new "My People" feature that was just released with RS3.

In the Windows Store there are many Apps trying to do what Franz does, but all fail miserably in terms of UI, stability, and being clattered with ads. 
There is a huge demand for a well coded, FOSS app like Franz, especially since there is no official Whatsapp-App on the Store.

With the "Desktop Bridge" it would be possible to convert the current Win32 App to Store App, like many devs have done by now: Evernote, IrfanView, Inkscape, GPMDP, Paint.NET, just to name a few.

This would not only provide the benefits i outlined above, but also provide Win 10S users with a useable App for Whatsapp, as they only can use Store Apps, and no Win32 Apps.

Plus, Updates are secure and easy also for non-technical persons; Donations for dev. support would be possible in App, and a clean installation of windows would be faster when one can just download it from the store in 1 click instead of manually.

Anyway, kudos for the V5, nice UI, responsive and fluid, and a big update IMHO. OFC would look even greater when the dark theme request comes to fruition. ;)

As i am no dev, i cant provide more detailed info on the technical backgrounds of the Desktop Bridge/Win32 to Store converter, but AFAIK there must be good documentations available now, and there are quite a few devs who had their Win32 Apps ported without problems.

Kind regards,
Steven

**Comment by alecive** [comment]
Do you know any electron app that has been converted to a Windows 10 app?

**Comment by kentgen** [comment]
I have never tried to convert any electron app, but the process seems to be possible and quite straightforward:
https://blogs.msdn.microsoft.com/appconsult/2017/03/14/convert-your-electron-app-using-the-desktop-bridge/
https://github.com/felixrieseberg/electron-windows-store

I really would love to see this feature as well. I only would be willing to pay for a well done native UWP app like this.

**Comment by adlk** [comment]
Converting the app to an UWP app does not change anything about how the app is written and of all, it doesn't make it "more native". It might give users more trust but managing store builds is an overhead that can't be managed right now.

However, AppStore as well as Windows Store builds are planned in a more distant future.

**Comment by HammyHavoc** [comment]
Would love to see My People integration.
