### ISSUE TITLE
Disabled "Play sound for notifications" for Franz in System Preferences/Notifications is ignored

### ISSUE THREAD

**Issue by yellow-pumpkin** [meetfranz/franz#1580]
**Describe the bug**
Disabling the "Play sound for notifications" setting in System Preferences → Notifications → Franz has no effect. Notifications still arrive with sound. Sound is only disabled when the setting is disabled within Franz for every service (e.g. disable "Enable audio" in WhatsApp). 

**Expected behavior**
All Franz Notifications should arrive without sound, if the setting "Play sound for notifications" is disabled for Franz in the System Preferences. Otherwise, one has to disable the "Enable audio" setting for all services within Franz. Also, the text underneath "Enable audio" reads: When disabled, all notification sounds and **audio playback** are muted - I do not want to disable audio playback, only notification sound.

**Screenshots**
<img width="368" alt="Screenshot 2019-08-27 at 15 28 04" src="https://user-images.githubusercontent.com/18584147/63775290-50c71f80-c8df-11e9-995c-f6e12dd9d8dd.png">

**Desktop (please complete the following information):**
 - macOS 10.14.6 (Mojave)
 - Version 5.2.0.1455

**Comment by paltaa** [comment]
This also happens in Ubuntu 16.05

**Comment by firewater2** [comment]
Happens in my High Sierra setup too.

**Comment by mjfreem1** [comment]
Also happens in macOS 10.15.4, Franz version 5.5.0.1762
