### ISSUE TITLE
Cache folder

### ISSUE THREAD

**Issue by DamianoP** [meetfranz/franz#1581]
Hey,
Franz is an amazing product
I want to suggest you an improvement:

You are using chrome for the services management
Please add the feature to use a specific folder for the cache
For instance when you run chrome you can specify a command "--disk-cache-dir=PATH"
If you add in the program settings page an option, for example "cache path:", we can specify the folder for the cache.
Then, in the code of Franze the services path will be sometingh like:
--disk-cache-dir=PATH+"/"+service1 <- for service1
--disk-cache-dir=PATH+"/"+service2 <- for service2
............
--disk-cache-dir=PATH+"/"+serviceN <- for serviceN

For the power users this will be an amazing improvement

**Comment by mloskot** [comment]
Looks like dup of #1107
