### ISSUE TITLE
ESSENTIAL: JavaScript injection per app

### ISSUE THREAD

**Issue by ylluminate** [meetfranz/franz#1587]
In certain programs it is essential to have JavaScript injection, such as Protonmail for autologin (but this autologin should not be saved from computer to computer unless desired - ie, it shouldn't be saved on the Franz servers):
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/kpuyOK0x/example.png?v=3cf104e0fa17cbe862f95911ea7517c8)

Notice how Rambox implements this, but there should be an additional option checkbox as to whether to save this property with the account (on the server) or locally only.

**Comment by devcline** [comment]
Must Have!
