### ISSUE TITLE
Android Message service fails to load

### ISSUE THREAD

**Issue by clementlesne** [meetfranz/franz#1588]
**Describe the bug**

The Android Message service only produce a 400 error from the provider. It's append since September 1rst 2019 at 22h00 CET.

**To Reproduce**
1. Install Franz with Flatpak/Flathub
2. Add a service for Android Messages
3. Load the new service
4. See the 400 error

**Expected behavior**

The service has to load the content without error.

**Screenshots**

![Screenshot from 2019-09-02 07-21-19](https://user-images.githubusercontent.com/10001945/64092036-55625c80-cd53-11e9-8fd3-0b385fd85213.png)

**Desktop (please complete the following information):**
 - OS Fedora 30 Silverblue
 - Gnome v3.32.2
 - Franz v5.2.0 (stable branch)
 - Flatpak v1.4.2

Thanks :)

**Comment by ChTBoner** [comment]
https://github.com/meetfranz/franz/issues/1583 and https://github.com/meetfranz/franz/issues/1575 already mention that issue and have a workaround.

**Comment by gitrummy** [comment]
Is there any fix for this yet? The workarounds posted don't work. Cheers.

**Comment by mturley** [comment]
I'm also seeing this. Sometimes reloading the service will fix it, but most of the time it won't. Strangely, sometimes it will be working fine and then I'll stop being able to send/receive messages, then when I reload it goes to the 400.
