### ISSUE TITLE
Service and Settings Icons are Not Loading - Windows Franz Client

### ISSUE THREAD

**Issue by PandoraH** [meetfranz/franz#159]
### Expected Behavior
Service and Setting Icons Should Show Proper Icons (Gear for the settings icon, and Brand icons for the Services). I expected to see the icons from the Available Services list, which show clearly. Screenshot:
![working-services](https://user-images.githubusercontent.com/10833058/32124720-0d9a12bc-bb26-11e7-995b-a47c9622a0bd.png)

### Current Behavior - Sidebar
1. Upon adding a new service, a broken image shows instead of the Service Type image. 
2. If service's are moved above or under other services, the icon changes to a white empty box.
3. The settings icon is showing a broken image (but briefly showed a gear before I added Services)

### Current Behavior - Settings
1. When looking at settings, my list of added services all have broken image icons.

### Screenshots (if appropriate):
![side-bar-icons-not-loading](https://user-images.githubusercontent.com/10833058/32124199-2e52cf3c-bb24-11e7-9980-006a4846415f.png)

![services list icons not loading](https://user-images.githubusercontent.com/10833058/32124564-749c2f96-bb25-11e7-8f1b-e45f30e4ac06.png)

### Possible Solution
Fix service and settings icons so that they show the proper image in the Windows Franz client.

### Context
It's a serious hassle having to hover over every icon to see the tooltip of what it is.

### Your Environment

Date Downloaded: 10/27/17
* Franz Version used: 5.0.0-beta.11
* Operating System and version: Windows 7 Professional, 64bit.

**Comment by haraldox** [comment]
@PandoraH Do you still experience the issue in 5.0.0-beta.15?
