### ISSUE TITLE
Service title for "proton-mail" is misspelled

### ISSUE THREAD

**Issue by clementlesne** [meetfranz/franz#1590]
**Describe the bug**

The service "proton-mail" is written "proton-mail" in the application, as this name is not the name of the service but "Proton Mail".

**To Reproduce**

1. Add the "proton-mail" service
2. Hover the new service icon
3. See the translation

**Expected behavior**

The name has to be equal to the service name, as "Proton Mail".

**Screenshots**

![Screenshot from 2019-09-03 21-40-28](https://user-images.githubusercontent.com/10001945/64203328-79c55280-ce93-11e9-9d69-37256c39c5cf.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Franz version 5.2.0 (from Flathub)

**Comment by vantezzen** [comment]
This is a problem in https://github.com/lukas-reineke/franz-recipe-proton-mail. For now, you can change the name by editing the service inside Franz.
