### ISSUE TITLE
Service icon for "proton-mail" is inconsistent

### ISSUE THREAD

**Issue by clementlesne** [meetfranz/franz#1591]
**Describe the bug**

The icon for the service named "proton-mail" does not have the same border ratio as the others icons.

**To Reproduce**

1. Add a "proton-mail" service
2. See the new service icon

**Expected behavior**

The icon image has to be draw by the same sizing, dimensions and borders as the others icons.

**Screenshots**

![Screenshot from 2019-09-03 21-45-12](https://user-images.githubusercontent.com/10001945/64203610-26073900-ce94-11e9-847c-2ae2728b4db7.png)
![Screenshot from 2019-09-03 21-45-04](https://user-images.githubusercontent.com/10001945/64203612-26073900-ce94-11e9-82b9-e89da7bea689.png)
![Screenshot from 2019-09-03 21-44-51](https://user-images.githubusercontent.com/10001945/64203613-26073900-ce94-11e9-9bd3-158632a3211e.png)

**Desktop (please complete the following information):**

 - OS: Fedora 30
 - Franz version 5.2.0 (from Flathub)

**Comment by vantezzen** [comment]
This issue is already resolved in the recipe itself (<https://github.com/lukas-reineke/franz-recipe-proton-mail/pull/2>), but the Franz recipe store hasn't updated the package yet.
