### ISSUE TITLE
Slack workspace icon not reflecting existing avatar

### ISSUE THREAD

**Issue by megaroeny** [meetfranz/franz#1594]
**Describe the bug**
If a Slack workspace already has an avatar for it, I would expect Franz to use the same logo for that service's icon.

**To Reproduce**

1. Sign into a new Slack workspace
2. You will see that Franz shows the Slack logo, not the Slack workspace/team avatar.

**Expected behavior**
Franz should show the existing Slack workspace avatar, for the Franz workspace icon

**Screenshots**
![Screen Shot 2019-09-04 at 2 01 05 PM](https://user-images.githubusercontent.com/1559447/64279248-99548d80-cf1c-11e9-9003-1e68f8ee34b9.png)

**Desktop (please complete the following information):**
https://whatsmybrowser.org/b/VQ9DR8G

**Additional context**
Refreshing Franz doesn't help

**Comment by bittner** [comment]
That used to work in the past, but for about half a year this is broken unfortunately.
