### ISSUE TITLE
Allow use of PayPal balance to pay for Franz

### ISSUE THREAD

**Issue by Safihre** [meetfranz/franz#1597]
I enjoy using the app on a daily basis and as such would like to support the development and get rid of that annoying delay. 

I was delighted to see I can use PayPal, however, it doesn't let me pay with my PayPal balance. It only allows me to pay with a linked debit or credit card. 

As I am paying for other subscriptions each month using my PayPal balance, I wonder if you could enable this also for Franz? 

Thank you. 

PS: I know Github is most likely not the place for this, but I can't find any other contact information.

**Comment by mylemans** [comment]
@Safihre Try contacting billing@meetfranz.com - I receive my subscription related mails from that email address

**Comment by Safihre** [comment]
Thanks! I did and promptly received this response, so at least now we know!

> Hi,
> 
> thanks for your email.
> Unfortunately, the billing service we use (Recurly) does not allow for this payment method.
> We're sorry for this inconvenience!
> 
> All the best,
> Bettina
>

**Comment by Safihre** [comment]
Actually today it deducted the money from my PayPal and while I had to select my bank account during the sign up, it used PayPal balance! All is good in the world 🕺
