### ISSUE TITLE
Spell Check Toggle is toggling Todos instead

### ISSUE THREAD

**Issue by gtumbaga** [meetfranz/franz#1601]
**Describe the bug**
After the 5.3.0/5.3.1 update, spell check is permanently disabled. When you click the toggle to turn spell check back on, the Franz Todos gets toggled on/off instead.

**To Reproduce**
1. Click the gear icon to open Franz settings.
2. Scroll down to the toggle switch labeled "Enable spell checking"
3. Notice it is off.
4. Click the toggle switch in order to enable spell checking.
5. Notice that Franz Todos has been toggled on/off instead.

**Expected behavior**
Clicking on the toggle switch for spell checking should actually toggle spell checking, and not toggle Franz Todos.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Franz App
 - Version 5.3.1

**Comment by AmyAmy** [comment]
The "Enable GPU Acceleration" toggle does work, but _also_ toggles Todos.

**Comment by dankessler** [comment]
At least for me in Windows 10, toggling literally *anything* also toggles the state of Todos. Fortunately, toggling todos doesn't toggle anything else so it's possible to set the state appropriately, but it basically requires one extra toggle of "todos" if you are doing an odd number of toggles.

**Comment by felixpenrose** [comment]
I can confirm the same issue here. Windows 10 same Franz version as OP

**Comment by ste7enm** [comment]
This also happens to me on a Mac in version 5.3.1.1528:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9658882/64722106-a58f9c00-d482-11e9-88c4-f0572817cc38.gif)

**Comment by rogergbh** [comment]
Nothing mentioned in the changelog but the pricing page shows spell check as part of a subscription tier. Feels like a bait and switch.

https://meetfranz.com/pricing

![Capture](https://user-images.githubusercontent.com/54034205/64730900-18623c80-d4ae-11e9-8d92-bd6f3049469b.PNG)

**Comment by Gaboris** [comment]
Okay is the Spellchecker is actually a paid function now and this isn't just some bug like it was before then I'm installing Hamsket and jumping boat this weekend.

**Comment by ste7enm** [comment]
Well, today's update fixed the toggle issue for me, but Spell Check is still not able to be toggled on. Too bad.

**Comment by tensor-programming** [comment]
Wow, amazing; take away features.

**Comment by gtumbaga** [comment]
Spell Check is a feature built in to Chromium.  It seems almost unethical that the franz folks would deliberately disable this feature so that they can start charging for it.

I have completely stopped using franz, and I will ensure to spread the word to others to stop using it as well.

**Comment by vector310** [comment]
Yeah, this is the last straw for me too. Bye Franz.
