### ISSUE TITLE
Move Todo toggle to somewhere that doesn't cover important functionality

### ISSUE THREAD

**Issue by cdaveb** [meetfranz/franz#1608]
**Is your feature request related to a problem? Please describe.**
Since the new Todo feature was included in Franz, I've been unable to interact with the menus on the right side of Discord posts until the text scrolls up unless I disable the Todo feature. I wasn't sure whether to list this as a bug or a feature request.

**Describe the solution you'd like**
I'd like there to either be a better way to toggle the todos list, or the position should be configurable in some way. Right now it's basically not usable for me because it interferes with the main chat functionality of Franz. I actually enabled the premium trial because I couldn't figure out how to make that go away and I thought it would, then realized it was still showing it because of the Todo thing.

**Describe alternatives you've considered**
The only alternative I have for now is to turn off the Todo feature.

**Additional context**
![Screen Shot 2019-09-11 at 10 06 47 PM](https://user-images.githubusercontent.com/6133808/64755748-f0d89780-d4e0-11e9-85f7-3bd57c06b327.png)

**Comment by alecive** [comment]
Fixed in the latest version of Franz!
