### ISSUE TITLE
Slack Dark Mode

### ISSUE THREAD

**Issue by leoheck** [meetfranz/franz#1612]
I saw this, then I was thinking if we could have the same.

https://www.theverge.com/2019/9/12/20862234/slack-dark-mode-macos-windows-linux-desktop-features

**Comment by alecive** [comment]
I thought the same, then I realized that Franz uses the webapp and not the desktop app and dark mode was available in the settings for the longest time! I now switched all my workspaces to dark mode.

**Comment by joeytwiddle** [comment]
Slack also allows you to select its own dark theme.

- Just go to Slack's menu in the top left (your network name).
- Then Preferences
- Then Themes
- Select Dark theme

**Comment by bittner** [comment]
This issue can probably be closed, right?

Universal dark mode is available from the Franz settings and Slack's specific dark mode can be configured individually for each Slack team, alternatively or in addition.

**Comment by leoheck** [comment]
Yes, sure.
