### ISSUE TITLE
Franz now requires account sign up?

### ISSUE THREAD

**Issue by MichaelMallett** [meetfranz/franz#1614]
I know that the issue of accounts has been discussed before, but I've been using Franz without one until today, where I now cannot access anything. I had presumed that this had been made optional (especially as I can't see any use for me having a franz account at all), as I've never had this issue. Is this a recent change? I won't be signing up for an account, I'll just not use franz, which is a shame imo.

OSX 10.13.6
Franz 5.3.2

**Comment by bittner** [comment]
I've seen performance issues today as the application tried to connect to the Franz server, but that was seemingly under load. The result of this was that my accounts weren't loaded, hence I couldn't use the application.

A solution that would make Franz more resilient would be to cache the account settings locally, load them when starting up, and then only connect to the Franz server to sync with the settings stored online. This way the Franz server could also go into maintenance mode or be totally offline for longer, without users being severely affected. The application could sync changes to the settings or the account as soon as the Franz server shows up again.

This approach would both make Franz more resilient (aka stable) and available offline without any separate business logic (technically, for free). Any thoughts?

**Comment by vantezzen** [comment]
+1 for @bittner's idea of storing/caching user data locally and only updating the store from the server.

This could also improve startup times as Franz wouldn't have to wait for Franz's API to respond to multiple requests and, depending on the implementation, also reduce load on Franz's servers.

**Comment by MichaelMallett** [comment]
I don't really know what I need an account for really, it's not clear? I'm using it to use facebook messenger and whatsapp rather than having another 2 tabs open. What is the benefit of having an account? It just makes me think I'm giving over more data than I thought, I genuinely just thought franz was a wrapper chromium wrapper.

**Comment by joonasy** [comment]
+1 Please make sign up optional. I see no point in having an additional wrapper account for using my actual account

**Comment by bittner** [comment]
> I see no point in having an additional wrapper account for using my actual account

Well, there are reasons that make sense to have the _possibility_ to have an account: e.g. if you want to sync your settings between several of your devices. Or if your machine stops working and your get a new one. Then it's nice to have your accounts all set up automatically, simply by logging in.

The problem with the current implementation (that is [what I'm pointing out](https://github.com/meetfranz/franz/issues/1614#issuecomment-532673612)) is its current implementation:

- The application startup _requires_ a connection to the server that hosts your account data.
- This has several disadvantages, one of them potentially sluggish performance when the Franz server has performance issues or is completely offline.
- Making the process more resilient, by _not requiring_ the Franz server to be present, would not only be a modern state-of-the-art approach but also optimize startup performance.

Once this improvement is implemented, making saving your account data actually _optional_ (via a switch in the settings) is apparently easy.

**Comment by MichaelMallett** [comment]
I can understand that as a potential advantage if you have a lot of
accounts, but it's not strong enough to require an account imo

**Comment by keunes** [comment]
@MichaelMallett You're not the only one: see also:
https://github.com/meetfranz/franz/issues/429
https://github.com/meetfranz/franz/issues/71
https://github.com/meetfranz/franz/issues/1211

In this context, you might want to follow this issue of a fork: https://github.com/getferdi/ferdi/issues/5
