### ISSUE TITLE
When account is not yet activated, app hangs.

### ISSUE THREAD

**Issue by sjerpbouwtsites** [meetfranz/franz#1616]
### Expected Behavior
Message should appear: hey user, you still need to confirm your account. Please go to your email.

### Current Behavior
No notifications; Whatsapp gives a weird error that I should download Chome even though I'm inside Chromium. Telegram hangs at making the keys. Slack didn't connect to the given account but rather just opens slack.com.

### Screenshots (if appropriate):
Well I accidentally went to my email because I wanted to file this bug. Activating alleviated it (without notice, again); I saw some 👌 going over the network, I suppose those are hung network requests that got returned late. Long story short, no screenshots. 

Here's some probably useless console errors: https://gist.github.com/sjerpbouwtsites/065fab96907589a83f8b92a71dec313f

### Possible Solution
I think the root cause is requests that don't timeout and a server that doesn't error back. This also probably means that low connectivity would be an issue.

### Steps to Reproduce (for bugs)
Window10.
Install franz and dont see the email.
Free.
whatsapp, slack and telegram.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/65212160-69bb8e80-daa1-11e9-8b4d-615a32f633d8.png)

![afbeelding](https://user-images.githubusercontent.com/34159539/65212176-6fb16f80-daa1-11e9-977c-c3e1d22ce714.png)

Oops no, nothing fixed. This thing is just clitching. Restarted because telegram hung.

**Comment by sjerpbouwtsites** [comment]
Wait a second here's some possible information. I'm behind a VPN. Nord.

**Comment by qazplm00** [comment]
Absolutly ask for remboursment ! this is a bug app develop !
