### ISSUE TITLE
Workspaces - Set custom sort order for workspaces

### ISSUE THREAD

**Issue by dwillitzer** [meetfranz/franz#1620]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Inability set the desired sort order for services but not workspaces.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Ability to set any order in workspaces desired, for the ease of use with a keyboard shortcut to jump to the workspace by order id.

---
Default order:
(A) Acme Corp              + keyboard binding (CMD + Option + 1)
(B) Example Corp          + keyboard binding (CMD + Option + 2)
(C) ABC Example Corp + keyboard binding (CMD + Option + 3)

Desired Order 
(A) ABC Example Corp  + keyboard binding (CMD + Option + 1)
(B) Acme Corp              + keyboard binding (CMD + Option + 2)
(C) Example Corp         + keyboard binding (CMD + Option + 3)

**Comment by TheCoinAxe** [comment]
Would be great having this feature
