### ISSUE TITLE
Switch Between Personal FB to Business Page

### ISSUE THREAD

**Issue by zeeshanish** [meetfranz/franz#1623]
Hello,

I wanted to use Franz for business purposes but whenever I log in to messenger service it just log me into my personal facebook messenger rather than my business/page messenger. I can't find a way to switch my service to Facebook page messenger.  

Please add an option as I would like my organization to use this app to communicate with our customers.

**Comment by patdnf** [comment]
Same problem here, cannot manage my messenger business page messages.
