### ISSUE TITLE
Cannot join the Franz Slack Channel

### ISSUE THREAD

**Issue by sinstein** [meetfranz/franz#1624]
**Describe the bug**
When following the link in the README to join the Franz Slack Channel, user is prompted to enter their email. When submitted, the request returns with `Failed! token_revoked`

**To Reproduce**
1. Go to http://slack.franz.im/
2. Enter your email
3. Click on submit

**Screenshots**
![Screenshot 2019-09-23 at 9 59 08 PM](https://user-images.githubusercontent.com/4283218/65444310-67fd1c80-de4d-11e9-91f2-1781d2b134b8.png)

**Desktop (please complete the following information):**
 - Browser: Chrome and Safari on macOS

**Response Data**
`<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Join the Franz Community community on Slack!</title><link href="css/style.css" rel="stylesheet" type="text/css"><link href="//fonts.googleapis.com/css?family=Lato:300,400,700,900,700italic|Open+Sans:700italic,400,600,300,700,800" rel="stylesheet" type="text/css"></head><body><div id="wrapper"><div class="main"><div class="header"><h1><strong>Franz Community</strong></h1><h2 class="error">Failed! token_revoked</h2></div></div></div></body></html>`

**Comment by taylorjdawson** [comment]
I am having the same issue. @adlk what's the deal here? Why was the slack community shut down?

**Comment by jnials** [comment]
Same issue.  And it is 21 January 2020.
