### ISSUE TITLE
Setting to keep all workspaces loaded does not work

### ISSUE THREAD

**Issue by Stanzilla** [meetfranz/franz#1626]
**Describe the bug**
The toggle can't be toggled

**To Reproduce**
1. Go to Settings
2. Click on the toggle for keeping workspaces loaded

**Expected behavior**
It should enable the feature 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome	
 - Version 5.3.3

**Additional context**

**Comment by DominikGuzei** [comment]
This should have been

**Comment by Stanzilla** [comment]
@DominikGuzei nope. when where how?

**Comment by DominikGuzei** [comment]
@Stanzilla this works without any issues on version 5.3.3 - can you describe / show your remaining issue in more detail?

**Comment by DominikGuzei** [comment]
Note: if you have many services toggling can take a few seconds since all the services are loaded … so maybe you just disabled the toggle by clicking on it a second time?

**Comment by Stanzilla** [comment]
@DominikGuzei here you go https://dl.dropboxusercontent.com/s/6406oz0hkb0w361/2019-10-03_18-33-57.mp4

**Comment by Stanzilla** [comment]
@DominikGuzei @adlk please re-open, this is still broken on 5.4.0-beta2

**Comment by Artofaj** [comment]
I am having the same issue in 5.4.1 stable

**Comment by laurentiuonac** [comment]
Broken for me, too.

**Comment by t-ricci-enhancers** [comment]
Still broken, doesn't work. @DominikGuzei
