### ISSUE TITLE
Tab switching via shortcuts crashes app 

### ISSUE THREAD

**Issue by askalburgi** [meetfranz/franz#163]
### Steps to Reproduce (for bugs)

1. Open Franz with all services set up
2. Switch via Cmd+number
3. Crashes
Also when trying to click on any of the topmenu items (Check for updates, etc) 

### Context

Just hella annoying for being quick. Works via mouse.

### Your Environment
* Franz Version used:
* Operating System and version: MacOS 10.13

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)
