### ISSUE TITLE
Franz doesn't handle pop-ups well

### ISSUE THREAD

**Issue by bry-huang** [meetfranz/franz#1636]
When using a browser (Chrome for me): In Trello, when you click to add a Google Drive document to a card, a pop-up window opens that allows you to pick navigate your Google Drive and pick a doc to attach to the card.

When using Franz: Nothing happens when I click to "Attach a file" from Google Drive.  It looks like it blocks or doesn't handle requests for pop-up windows well.  I've resorted to using my browser for Trello.  Please fix!

**Comment by petecuff** [comment]
Bump
