### ISSUE TITLE
New public recipe integration

### ISSUE THREAD

**Issue by celber** [meetfranz/franz#1639]
Hello!

I am MeWe developer and we would like to submit our recipe, but I am not sure now how project submission looks like since 5.x. Which repository should be merged? Thank you in advance.

**Comment by karammell** [comment]
recipe creation and deployment is decribed in the docs: https://github.com/meetfranz/plugins/blob/master/docs/integration.md#user-content-deployment

**Comment by Girmii** [comment]
Has there been any progress on the integration of MeWe into Franz?

**Comment by Gi11i4m** [comment]
> Has there been any progress on the integration of MeWe into Franz?

Well, [now there has been](https://github.com/meetfranz/plugins/issues/487) 😉

**Comment by melvinchia** [comment]
This plugin now crashes with the latest Franz update: version 5.7.0-beta.1.1845
