### ISSUE TITLE
Some sticker can not be displayed on telegram

### ISSUE THREAD

**Issue by ragusa87** [meetfranz/franz#1640]
**Is your feature request related to a problem? Please describe.**
Some sticker can not be displayed on telegram.
The following message appears instead:

> The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.

**Describe the solution you'd like**
Upgrade the browser version to fix this

**Additional context**
Clearing the cache and service workers didn't help

**Comment by geeks-r-us** [comment]
I just wrote a recipe for telegram-react client which can display stickers.
See here: https://github.com/geeks-r-us/recipe-telegram-react

**Comment by francwalter** [comment]
> I just wrote a recipe for telegram-react client which can display stickers.
> See here: https://github.com/geeks-r-us/recipe-telegram-react

Nice, works. 
But in this service the Download-Button is missing on attachments. Look:

![grafik](https://user-images.githubusercontent.com/927269/87013696-582baa80-c1cb-11ea-9bc2-5282a8785e7d.png)

and this is the original Telegram service of Franz (with Download Button):

![grafik](https://user-images.githubusercontent.com/927269/87013795-785b6980-c1cb-11ea-835c-46f2f5835d5a.png)

Is there some setting to get it back? 
I don't want to use two services for the same messenger :(
Thanks.
frank

**Comment by geeks-r-us** [comment]
@francwalter This is an issue you need to push to https://github.com/evgeny-nadymov/telegram-react
recipe-telegram-react just wraps it for franz

**Comment by francwalter** [comment]
Ah, thank. Will do...
... done it: 
[No Download Button for attachments](https://github.com/evgeny-nadymov/telegram-react/issues/200)
