### ISSUE TITLE
Slack calling doesnt work

### ISSUE THREAD

**Issue by JAicewizard** [meetfranz/franz#1647]
**Describe the bug**
Slack calling doesn't work. If I call someone or join a call the call is opened in a browser window

**To Reproduce**
1. Be in a slack workspace 
2. Call someone or be called by someone

**Expected behavior**
In a previous release calling work flawlessly, I don't have any version number for that though.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox (what is this used for?)
 - Version 5.3.3

**Additional context**
The issue is pretty straight forward, and (for me) reliably reproducible.

**Comment by mikerj1** [comment]
This is a duplicate of issue 1603. https://github.com/meetfranz/franz/issues/1603

**Comment by JAicewizard** [comment]
ok, closing now, I searched the issues but nothing related came up :/
