### ISSUE TITLE
Telegram, Whatsapp do not fill the space, following last update

### ISSUE THREAD

**Issue by PashaKagan** [meetfranz/franz#1648]
**Describe the bug**
Telegram and Whatsapp used to fill the space of the window.
Restarted for the update, now they don't fill and stretch across the screen.

**Expected behavior**
Services used to fill the entire window.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
![snip_20191006103654](https://user-images.githubusercontent.com/8081472/66265853-d5358800-e825-11e9-9357-5a58a9c108ed.png)

**Comment by dade-shinji** [comment]
happen the same to me with Telegram service, i'm on macOS
