### ISSUE TITLE
Dark mode in services

### ISSUE THREAD

**Issue by Zedespook** [meetfranz/franz#1655]
**Dark mode in applications/services**
Many services already have built-in dark-mode, but there are some which doesn't have dark-mode on desktop, and it's bad for my eye. For example Messenger.

**Add a slider or button, which can invert the colors from white to gray/blue/black.**
This solution wouldn't be only good for Messenger (as I said above), but for applications that have a dark mode, but it doesn't cover the whole application. For example Gmail. When I look at my e-mails, some of them have white backgrounds, and it's off-putting to see dark text, then all of a sudden bright white just flashes into my eye.

**Dark reader**
There is a Chrome extension called "Dark Reader" which is a perfect example of how I imagine this feature, please make something like that one as a solution to my issue.

**How I would want this fix**

**Messenger:**
![image](https://user-images.githubusercontent.com/26501287/66690407-126ba100-ec90-11e9-9f15-d32ff894e047.png)
![image](https://user-images.githubusercontent.com/26501287/66690483-8312bd80-ec90-11e9-92aa-7fdbce3cbfa5.png)

**Dark Reader:**
![image](https://user-images.githubusercontent.com/26501287/66690420-27e0cb00-ec90-11e9-8f2b-356fe2c31377.png)

**Gmail:**
![image](https://user-images.githubusercontent.com/26501287/66690487-945bca00-ec90-11e9-86fd-866cdcbec4de.png)
![image](https://user-images.githubusercontent.com/26501287/66690496-a0478c00-ec90-11e9-96e8-d90b720294af.png)

**Comment by karammell** [comment]
[Ferdi](https://github.com/getferdi/ferdi) already has this feature (at least in the latest betas).
