### ISSUE TITLE
Launching Franz hidden does not work (Mac OS)

### ISSUE THREAD

**Issue by bramvbilsen** [meetfranz/franz#1656]
**Describe the bug**
In Mac OS, users have the ability to add "Login items". These can normally start hidden but this does not work with Franz. Thus instead of launching hidden on start, it pops up on start which I find rather annoying.

**To Reproduce**
1. Go to `System Preferences` in Mac OS
2. Click on `Users & Groups`
3. Click on the `+` and add `Franz`
4. Check the `Hide` checkbox next to `Franz`
5. Restart Mac and watch Franz launch behavior

**Expected behavior**
Franz should be hidden on boot.

**Screenshots**
<img width="780" alt="franz" src="https://user-images.githubusercontent.com/16825392/66715727-e43cad00-edc6-11e9-9797-634fa9a46e0a.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 5.3.3

**Comment by yafp** [comment]
assume this is related with the auto-launch package (https://github.com/Teamwork/node-auto-launch).

See: https://github.com/Teamwork/node-auto-launch/issues/81

The core project is not really actively developed, Franz is afaik using a self-hosted fork 

* https://github.com/meetfranz/node-auto-launch
