### ISSUE TITLE
Darkmode totally broken on latest 5.4.0-beta.3

### ISSUE THREAD

**Issue by incace** [meetfranz/franz#1662]
After update, no darkmode.css files work for any service.

**To Reproduce**
1. Update Franz to 5.4.0-beta.3
2. Check a service...
3. Go blind...

**Expected behavior**
Darkmode for services retained.

**Desktop:**
 - OS: MacOS High Sierra 10.13.6

**Additional context**
I've tried reloading Franz, reloading all services, enable/disable darkmode, etc. Nothing seems to fix it.

**Comment by alsteven** [comment]
Version 5.3.3 on Windows seems to have the same problem. Dark mode in the Franz frame works as expected, but adding a darkmode.css file doesn't seem to have any effect on any service.
