### ISSUE TITLE
Keep getting "Your services have been updated."

### ISSUE THREAD

**Issue by deinfluence** [meetfranz/franz#1667]
**Describe the bug**
When loading Franz 5.3.0 or 5.4.0-beta 3, I keep getting notifications that the services have been updated and I need to **Reload services**. On reloading, the same thing happens a few mins after.

I have the following services loaded:

- WhatsApp
- Hangouts
- Messenger
- Telegram
- Android Messages

**To Reproduce**
As stated - happens soon after load.

**Desktop (please complete the following information):**
 - OS: Win 10 1903

**Comment by incace** [comment]
Having the same issue. Aesthetically annoying.

**Comment by ConnorDY** [comment]
I am also having the same issue. The issue persists after uninstalling and reinstalling. I'm on Arch Linux.
