### ISSUE TITLE
Hyperlink launch feature not working

### ISSUE THREAD

**Issue by JHGelpi** [meetfranz/franz#1671]
**Describe the bug**
When a user tries to click on a hyperlink in a Franz chat (regardless of service, but experienced most frequently in Google chat.google.com) the _blank window appears, but the browser does not launch the hyperlink.  The only way to launch a hyper link from Franz is to copy/paste the hyperlink into the browser address bar.  This happens consistently.

**To Reproduce**
1. Receive hyperlink as a message inside service
2. Click on hyperlink in chat service to launch url
3. Observe _blank window pop up
4. Observe web browser never launches desired url

**Expected behavior**
When clicking on hyper link the url should launch without further action from user in web browser.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser: Chrome, Firefox
 - Version 
Firefox version: 70.0 (64-bit)
Franz version: 5.3.3 x86_64

**Smartphone (please complete the following information):**
N/A

**Additional context**
Debug information:
{"host":{"platform":"linux","release":"5.3.6-200.fc30.x86_64","screens":[{"bounds":{"height":1080,"width":1920,"x":0,"y":1080},"id":13761487533244482,"rotation":0,"scaleFactor":1,"size":{"height":1080,"width":1920},"touchSupport":"unknown","workArea":{"height":1080,"width":1920,"x":0,"y":1080},"workAreaSize":{"height":1080,"width":1920}},{"bounds":{"height":1080,"width":1920,"x":0,"y":0},"id":25442309496751944,"rotation":0,"scaleFactor":1,"size":{"height":1080,"width":1920},"touchSupport":"unknown","workArea":{"height":1053,"width":1920,"x":0,"y":27},"workAreaSize":{"height":1053,"width":1920}}]},"franz":{"version":"5.3.3","electron":"4.2.4","installedRecipes":[{"id":"android-messages","version":"1.1.2"},{"id":"googlecalendar","version":"1.0.0"},{"id":"hangouts","version":"1.0.0"},{"id":"hangoutschat","version":"1.1.0"},{"id":"linkedin","version":"1.0.0"},{"id":"messenger","version":"1.0.8"},{"id":"slack","version":"1.0.9"},{"id":"telegram","version":"1.0.5"},{"id":"whatsapp","version":"1.0.17"},{}],"devRecipes":[],"services":[{"id":"eaa7c3f9-d61f-4983-acf0-d355c53bb24a","recipe":"hangoutschat"},{"id":"1e4277d4-4465-4c45-8d26-f9157613336f","recipe":"whatsapp"},{"id":"b8b978e6-7cde-481b-8a5e-0f64db6b95c0","recipe":"slack"},{"id":"b7e2e083-9ef8-4579-a078-b294c9112318","recipe":"telegram"},{"id":"90d0da23-3df0-4c8b-aeca-d240d337ba24","recipe":"linkedin"},{"id":"ddcf7cc3-fa5d-4652-b764-a2222b1e540c","recipe":"googlecalendar"}],"workspaces":[],"windowSettings":{"width":960,"height":1043,"x":960,"y":1117,"displayBounds":{"x":0,"y":1080,"width":1920,"height":1080},"isMaximized":false,"isFullScreen":false},"user":"6f0741dd-9e78-4d91-b6c9-11988960f523"}}

**Comment by riontel** [comment]
Observe the same behavior with Hangouts Chat on Mac OS (Yosemite, Mojave, and Catalina)

**Comment by marielb** [comment]
Same issue with Google Calendar
