### ISSUE TITLE
Facebook Messenger doesn't load chat window

### ISSUE THREAD

**Issue by dovry** [meetfranz/franz#1674]
Facebook Messenger doesn't load previous messages in the chat window. It shoes if someone sends a message after you've opened the chat.

**To Reproduce**
1. Add facebook messenger service
2. Log in
3. ???
4. No profit

**Expected behavior**
Load older messages

**Screenshots**
![image](https://user-images.githubusercontent.com/15201298/67846909-405f3b00-fb02-11e9-84a3-bb50b2908d32.png)

**Desktop (please complete the following information):**
Both win 10 and ubuntu 18.04

**Comment by miyagui** [comment]
Same problem any solutions? 
Cleared cache but it seems like it's beyond franz. Something changed with the web service.

**Comment by JBlocklove** [comment]
I updated Franz through the AUR and that fixed the issue for me. I don't believe the image for Ubuntu is as up-to-date so I'd look to build from source and see if that solves the issue.

As for Windows, I think you might just need to wait for a new stable release.
