### ISSUE TITLE
Services stuck in "getting started" panel

### ISSUE THREAD

**Issue by nmiculinic** [meetfranz/franz#1675]
**Describe the bug**
I've added few services, but all are stuck in the getting started panel

**To Reproduce**
1. Install franz 5.4.0 on linux via debian
2. Add riot service
3. Add facebook messenger service

**Expected behavior**

The matrix/riot/messenger login window should appear. I've used franz long time ago..and yeah, it's not here.

**Screenshots**
![bug_status](https://user-images.githubusercontent.com/3183610/67864479-f6884c00-fb25-11e9-933f-e9a2f8daa8d4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Linux Mint 19, Cinnamon DE

**Comment by ParadoxicalNerd** [comment]
I am facing the same problem for Whatsapp and Gmail. I am using Elementary 5.0 Juno.

**Comment by NeddieSeagoon** [comment]
Same here, just installed the latest version and am unable to actually log in to any of the services I add.

**Comment by matoushybl** [comment]
Also happening to me on Manjaro i3.

**Comment by zefram-cochrane** [comment]
Same on Manjaro KDE.  Is Franz still supported?

**Comment by zefram-cochrane** [comment]
Ah, found a fix on another issue here. Go to the View menu and select "Reload Franz".
