### ISSUE TITLE
Can't change zoom level in Slack

### ISSUE THREAD

**Issue by Naatan** [meetfranz/franz#1677]
**Describe the bug**
When using Slack you cannot change the zoom level as described in the Slack help:

https://slack.com/intl/en-ca/help/articles/236067467-adjust-your-zoom-level-in-slack

**To Reproduce**
1. Add Slack
2. Use the steps in the help article linked above
3. Alternatively use View > Zoom In

**Expected behavior**
Text becomes bigger

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by tnaseem** [comment]
Happens to me too (Windows 10) and isn't limited to Slack, but all the services. I can CTRL-0 to reset the zoom, but the CTRL- and CTRL+ do nothing. Trying the Zoom In/Out from the View menu does nothing either. 

It used to work, but not now. Version 5.4.0-beta-3.

**Comment by jboyens** [comment]
As a fix in the meantime, View -> Toggle Developer Tools and execute this Javascript in the console:
```javascript
const webviews = document.getElementsByTagName('webview');
for (let e of webviews) {
  e.setZoomLevel(2);
}
```

Where `2` is the zoom level you want.
