### ISSUE TITLE
Services not loading after standby

### ISSUE THREAD

**Issue by rehoehle** [meetfranz/franz#168]
I have a problem under OSX. When my macbook starts after standby the all the service pages are white and i have to right click on the service and have to reload the page. It's a bit annoying if you have a lot of services.

**Comment by adlk** [comment]
Thanks for reporting this. Until we have a proper solution for that, you can reload single services with `Cmd+R` or all services with `Cmd+Shift+R`.

**Comment by rehoehle** [comment]
Ok thx :) the second command is very helpfull.

**Comment by gth001** [comment]
its super annoying, i switched to this and im having better luck https://chrome.google.com/webstore/detail/all-in-one-messenger/lainlkmlgipednloilifbppmhdocjbda/related?hl=en

**Comment by adlk** [comment]
@gth001 this is quite helpful...

**Comment by mroeling** [comment]
I recognize the problem. I think it is because the internet connection doesn't exist on first repaint of the Franz app. 

Perhaps you could do something like Google Chrome: when the connection comes back, it reloads the frame automatically on click. 

FWIW, the problem also existed on Franz 4 on Unix.

**Comment by andypillip** [comment]
I'm on Fedora/Wayland with Franz 5 and I'm seeing the same issue (makes sense according to @mroeling's last comment.

**Comment by batje** [comment]
I have been having this issue on 4 and now also on 5. It almost never happens on whatsapp or fb messenger, but a lot (almost always) on skype and sometimes on gitter. Now that I installed 5, I do see the first Skype page, where I need to provide my username, but if I click Next, the next page is white again.
What is odd is that the service actually does load: the html is there, the page is rendered. Though completely white. When you hover your mouse over the page, everything seems to be there. The mouse pointer will change to a text-insert thingie over textboxes, and to a hand when hoovering over a link. If you right-click on a hidden image, it will neatly suggest to save the image. The only thing is: you dont see anything.

So, that would invalidate @mroeling 's suggestion, I think.
Hope that helps.
(Running on Kubuntu 17.10)

**Comment by adlk** [comment]
@batje this issue is related to #253

**Comment by haraldox** [comment]
for me, services reload automatically after standby in Franz 5.0.0-beta.15...

@rehoehle @gth001 @mroeling @andypillip @batje could you please test, if that milestone fixes the problem?

**Comment by andypillip** [comment]
I installed Franz Beta 15, but I'm still seeing this issue on Fedora 27.

**Comment by haraldox** [comment]
@andypillip please comment on the aggregated issue #594

**Comment by rehoehle** [comment]
After the last Update to Franz Beta 5.0.0-beta.15 i have to relogin after every standby... it's unusable. 

Perhaps that problem caused by the last OSX update. Since that i have to use the native application. That is not really usable. I can't login every time to HipChat after every standby.

**Comment by rionita** [comment]
Still seeing this issue on Windows 10 Pro:
Franz version 5.0.0 beta19
release 2.0.13 / win32 / x64
