### ISSUE TITLE
Audio/video calls in Messenger does not work in Catalina

### ISSUE THREAD

**Issue by zanami** [meetfranz/franz#1680]
**Describe the bug**
No popup window created, nothing happens/

**To Reproduce**
1. Go to 'Messenger account'
2. Click on 'camera or phone icon'
3. ...
4. Nothing happens at all

**Expected behavior**
A window opens with audio/video call.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15 or 10.15.1
 - Version Franz 5.4.1.1703

**Additional context**
Video/audio calls in Messenger web version works fine in Chrome (it doesn't support Safari)
It also worked fine in Franz before Catalina

Console messages

> com.apple.PerformanceAnalysis: __PerfLogging__: Franz__WSWindow__WSWindowDrag __updates (Slow WS Update count)__ 0
> 
> runningboard: Invalidating assertion 390-109-522 (target:executable<Franz(501)>) from originator 109

> Sandbox: Franz Helper (Re(3249) deny(1) iokit-get-properties image-path
> Violation:       deny(1) iokit-get-properties image-path 
> Process:         Franz Helper (Re [3249]
> Path:            /Applications/Franz.app/Contents/Frameworks/Franz Helper (Renderer).app/Contents/MacOS/Franz Helper (Renderer)
> Load Address:    0x10e21a000
> Identifier:      com.meetfranz.franz.helper.(Renderer)
> Version:         5.4.1.1703 (???)
> Code Type:       x86_64 (Native)
> Parent Process:  Franz [3172]
> Responsible:     /Applications/Franz.app/Contents/MacOS/Franz

**Comment by danielregis81** [comment]
i have the same problem with MS Teams, Skype, Hangouts, Whatsapp. The camera support does not work inside franz. On google chrome all works fine.
