### ISSUE TITLE
Wasm code generation disallowed by embedder

### ISSUE THREAD

**Issue by cherniid** [meetfranz/franz#1683]
**Describe the bug**
Unable to use custom service with WebAssembly.

**To Reproduce**
Yandex.Mail (https://mail.yandex.com/) switched to WebAssembly and doesn't work anymore. 

Steps:
1) Successful login 
2) Error on load and compile wasm module, redirect to Fatal page

Service dev tools shows error in Console:

```
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder

Uncaught (in promise) CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
    at /opt/Franz/resources/app.asar/node_modules/hunspell-asm/dist/cjs/lib/node/hunspell.js:8:832600
    at Object.fs.readFileSync (electron/js2c/asar.js:602:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:797:22)
    at Module.load (internal/modules/cjs/loader.js:645:32)
....
```

**Version info:**
 - OS: Ubuntu 19.04
 - Franz User-Agent: Franz/5.4.0 Chrome/76.0.3809.146 Electron/6.0.10 Safari/537.36

**Comment by jjason685** [comment]
Any fix? Getting this on Electron v10.1.1 but hard to reproduce let alone find a fix for ourselves, anyone have an idea for a C++ patch?
