### ISSUE TITLE
Franz does not load any services anymore and keeps "playing the trumpet" or "saddling the unicorn"

### ISSUE THREAD

**Issue by awunder** [meetfranz/franz#1690]
**Describe the bug**
Franz does not load any services anymore and keeps "playing the trumpet" or "saddling the unicorn"

after a while (a real long while) it throws an error that it couldnt load services

**To Reproduce**
1. start franz (under linux) 

**Expected behavior**

**Screenshots**
![Selection_216](https://user-images.githubusercontent.com/13486613/68652938-9962a200-04f8-11ea-9907-937537beb445.png)

**Desktop (please complete the following information):**
 - Manjaro with Gnome

**Comment by pix-art** [comment]
Duplicate: https://github.com/meetfranz/franz/issues/1689

**Comment by hope-atlast** [comment]
Yes Same Issue here
![upload](https://user-images.githubusercontent.com/29015880/68654187-68fc2180-0553-11ea-9300-039a8937a373.png)
What to do ?

![up2](https://user-images.githubusercontent.com/29015880/68654256-89c47700-0553-11ea-8938-d0798a3e3a58.png)

**Comment by awunder** [comment]
have some hope... (pun intended) ;)

**Comment by DavidZenz** [comment]
Same issue here

![franz](https://user-images.githubusercontent.com/25434431/68654426-31c74980-052e-11ea-9d85-46cf365e9bed.png)

**Comment by fafarafiel** [comment]
Same issue here:) looks like Franz global error:/ which gonna makes my day a nightmare:)

**Comment by Systho** [comment]
Issue seems to be fixed

**Comment by DavidZenz** [comment]
works again

**Comment by DarwinOnLine** [comment]
It's OK for me !

**Comment by hope-atlast** [comment]
Working Properly Now

**Comment by mimavox** [comment]
Still not working for me; Samma issue on Gnome/Manjaro, Franz v. 5.4.1-1 (AUR). Downgrade to 5.3.3-1 starts fine but cannot login (signing in spins forever). Nothing wrong with my account either; works fine on MacOS.

**Comment by jm96441n** [comment]
Same issue on MacOS (Mojave 10.14) spins forever and then stops responding or just crashes
