### ISSUE TITLE
High power consumption due to decreased timer resolution

### ISSUE THREAD

**Issue by neon-dev** [meetfranz/franz#1695]
**Describe the bug**
When Franz is running, the computer draws more power from the wall because it requests to change the Windows timer resolution down to 1ms. This is a known issue for years and has been discussed on many sites. Example: https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

**To Reproduce**
1. Install a Watt meter
2. Look at idle power draw
3. Start Franz
4. Check the difference

**Expected behavior**
Franz should not increase idle power consumption.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win 10
 - Processor: Ryzen 3000 Generation (Zen2)

**Smartphone (please complete the following information):**
n/a

**Additional context**
Maybe doesn't affect all CPUs equally. For me it increases idle power consumption by about 15W.
This is the message that `powercfg /energy /duration 5` generates when Franz is running:
```
Warnungen

Plattform-Zeitgeberauflösung:Plattform-Zeitgeberauflösung
Die standardmäßige Plattform-Zeitgeberauflösung beträgt 15,6 ms (15625000 ns) und sollte immer dann verwendet werden, wenn sich das System im Leerlauf befindet. Wenn die Zeitgeberauflösung erhöht wird, sind die Technologien zur Prozessorenergieverwaltung möglicherweise nicht wirksam. Die erhöhte Zeitgeberauflösung kann auf eine Multimediawiedergabe oder Grafikanimationen zurückzuführen sein.
Aktuelle Zeitgeberauflösung (100-ns-Einheiten) 	10000
Maximale Zeitgeberperiode (100-ns-Einheiten) 	156250
```

**Comment by fuzzl** [comment]
not sure its the same issue, but i noticed also that franz idle power cosumption is increased! 
with franz in the background my notebook remains ~40min and without 4 hours

**Comment by neon-dev** [comment]
Issue does not exist anymore due to either a Franz update or service update.
