### ISSUE TITLE
Problem spellcheck Portuguese-Brazil(pt-br)

### ISSUE THREAD

**Issue by supernoi** [meetfranz/franz#1697]
Hello,

A strange behavior that the spell checker of Portuguese Brazil (pt_br).
The wrong word is indicated, but the correction alternatives are apparently from another language.

The fix I found, is to replace the pt-br.dic and pt-br.aff files.

sudo cp /usr/share/hunspell/pt_BR.aff /opt/Franz/resources/app.asar.unpacked/dictionaries/hunspell-dict-pt-br/pt-br.aff 
sudo cp /usr/share/hunspell/pt_BR.dic /opt/Franz/resources/app.asar.unpacked/dictionaries/hunspell-dict-pt-br/pt-br.dic

Each time Franz updates it returns to display wrong correction suggestions.

* Franz Version used: 5.3.3
* Operating System and version: Elementary OS 5.0 Juno

Thanks

**Comment by danielsuguimoto** [comment]
@supernoi I'm facing the same issue...could you send me these files or tell me where you found them?

**Comment by supernoi** [comment]
> 
> 
> @supernoi I'm facing the same issue...could you send me these files or tell me where you found them?

I get it from another application, but you can download in the LibreOffice repository:
https://github.com/LibreOffice/dictionaries/tree/master/pt_BR

**Comment by danielsuguimoto** [comment]
@supernoi thx! But still facing this issue with those files
