### ISSUE TITLE
"Launch Franz on start" not working

### ISSUE THREAD

**Issue by floqqi** [meetfranz/franz#17]
### Expected Behavior

"Launch Franz on start" disabled: Should not start at boot.

### Current Behavior

"Launch Franz on start" disabled: Application starts at boot.

### Screenshots (if appropriate):

Not necessary. Just disable "Launch Franz on start" in the settings.

### Possible Solution

Looks like it does not remember the setting. Close and re-open -> "Launch Franz on start" is turn on (even if turned off before closing).

### Steps to Reproduce (for bugs)

1. Disable "Launch Franz on start"
2. Restart (or just close and re-open application)
3. Look into the settings: "Launch Franz on start" is enabled

### Context

I just want to disable launching at startup.

### Your Environment

* Franz Version used: 5.0.0-beta.10
* Operating System and version: macOS 10.13

**Comment by adlk** [comment]
Seems like there is an issue with windows as well with Franz _not_ starting even though the option is et.
https://twitter.com/aaneric/status/921429385495941120

**Comment by rwkyyy** [comment]
@adlk can confirm the "start on windows" issue and disabling on MacOS

**Comment by adlk** [comment]
Ok, I did my tests on 10.12 and it worked fine. I'm going to upgrade now to 10.13 and hope that I'm able to reproduce it.

**Comment by adlk** [comment]
It seems like that there is an issue with Electron & High Sierra with disabling autostart.
I'll update Franz to not automatically start until this issue is resolved.

Here is the issue on electron for reference: https://github.com/electron/electron/issues/10880

If you need a solution to disable autostart 
* Go to System Preferences -> User -> Login
* Select Franz 
* Remove it with the minus button

<img width="874" alt="bildschirmfoto 2017-10-23 um 16 17 57" src="https://user-images.githubusercontent.com/3265004/31894182-f0f81f34-b80d-11e7-8fb3-427895ef3ec2.png">

Sorry for the german screenshot but I assume you'll get it anyway :)

**Comment by SergioSGil** [comment]
It continue failing on High Sierra

**Comment by adlk** [comment]
I'm currently using the built in electron autostart option but I'm not really satisfied how it works.

Might use node-auto-launch again as it did a much better job with previous Franz versions.
https://github.com/Teamwork/node-auto-launch

**Comment by SergioSGil** [comment]
Would be better, on previous versions autostart on/off works very well

**Comment by jescode** [comment]
On my initial tweet https://twitter.com/aaneric/status/921429385495941120 I meant if u turn the start up option on and fully close franz and open it back up or after a reboot, "the launch franz on start" option is turned off again and thats why franz is not starting up with windows, hope it'll get fixed soon. anyways I love the new update so far, keep it up 💪😊

**Comment by darekaze** [comment]
This bug is still exist in linux.
- Franz Version: 5.0.0-beta.15
- OS: Debian 9.3

Issue: "Launch Franz at Start up" is toggled "on" everytime when Franz is launched.

**Comment by jakobsudau** [comment]
This bug also still exists for macOS High Sierra (10.13.3).

Please fix this!

**Comment by rwkyyy** [comment]
@jakobsudau remove and download the latest version. then from dock, right click and open at startup.

for me it works. also macOS High Sierra.

**Comment by maxxscho** [comment]
Same here. Re-Installed Franz - removed it from Login Objects… it still start on Launch. macOS 10.13.2

**Comment by chadhamre** [comment]
Same problem for me. OSX v10.13.3 and Franz Version 5.0.0-beta.15

**Comment by LjAce** [comment]
Same problem for me as well: OSX v10.13.13, Franz: 5.0.0-beta.15.  Come on guys ... I've been struggling with this for over a month now .. and it's really maddening.  This can't be complicated .. I don't understand how this is still not fixed. Can you please provide something asap on this? PLEASE!!!

**Comment by kecinzer** [comment]
Same problem here macOS 10.12.6.

**Comment by leehblue** [comment]
Same problem on POP!_OS (Ubuntu) 17.10 
Current version: 5.0.0-beta.15

**Comment by LjAce** [comment]
Hey Guys ... FYI ... very happy to report .. the latest Beta Update which came out in the past few days (5.0.0-beta-16.762)  fixes the problem on all 3 of my Macs (all running High Sierra 10.13.3, and one 10.13.4 beta).    Note: after you first update and re-launch ... go into your Mac System Preferences to your user account "Login Items" settings, and check / remove all the Franz entries, as  the initial update may have added an extra one in there upon update ... which makes sense if you think about it.  

Thanks to all the Franz dev guys ... as I know this probably didn't seem like a big deal as most people probably have it set to auto-launch anyway, but for the few of us who don't want it to auto-launch ... this really was driving us (at least me) mad. 👍
