### ISSUE TITLE
Refreshing Franz crashes the application

### ISSUE THREAD

**Issue by chrispike1** [meetfranz/franz#170]
Current Behavior
Each time I use Command+R to refresh the application, Franz "quits unexpectedly". This also happens when refreshing from the taskbar.

Environment
* Franz Version used: 4.0.4
* Operating System and version: Mac - Sierra 10.12.6

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)
