### ISSUE TITLE
Franz makes macOS 10.15.1 Freeze :/

### ISSUE THREAD

**Issue by wrybit** [meetfranz/franz#1701]
**Describe the bug**
After about 1h of Franz use, my macOS Freezes.
If I look into the stats it seems like the App consumes large sets of memory ~8-10gb.

**To Reproduce**
Just use Franz.

**Expected behavior**
Use Franz without crashing the system.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1 (19B88)
 - App: Franz 'Electron'
 - Version 5.4.0-beta.3

**Additional context**
Is there any workaround to limit Franz in a way?

**Comment by rctneil** [comment]
I'm getting issues very similar to this. It uses soooo many system resources that I can't even have the app open anymore.  Is there a solution?

**Comment by stacksjb** [comment]
I frequently see the same thing. I restart the app and the issue generally resolves. It's frustrating when I encounter it because I can't leave it running.
