### ISSUE TITLE
Integrate Signal

### ISSUE THREAD

**Issue by RalfRoemling** [meetfranz/franz#1702]
#767

As of 11.2019 Signal has a Windows version which was the stopper before. 
https://signal.org/de/download/

How can it be integrated?

Thx in advance,
Ralf

**Comment by Makazzz** [comment]
Not possible.

[From adlk in 767](https://github.com/meetfranz/franz/issues/767#issuecomment-446354586)
> Signal is not available as a web version - this is required for being available in Franz. I've been in talks with Signal and they made it clear that they are not planning to support web as a platform.

So no signal for web == no signal for Franz.

**Comment by RalfRoemling** [comment]
sorry, my bad. 

thought a Windows version would equal a web version.
