### ISSUE TITLE
google hangouts - telefon calls not working

### ISSUE THREAD

**Issue by gerald-drissner** [meetfranz/franz#1703]
Since the update to the latest version, google hangouts does not work properly. I cannot make phone calls anymore. (Franz tries to load all my conacts - but this doesn't happen). Videocalls are fine. 

  - OS: manjaro kde linux

**Comment by batcheck** [comment]
Same issue on Windows 10 November 2019 build. Just get an error saying "Cell phones feature is not available"

Feature still works fine on gmail in Chrome.
