### ISSUE TITLE
Slack unread badge appears when it shouldn't

### ISSUE THREAD

**Issue by tjyrkinen** [meetfranz/franz#1712]
**Describe the bug**
I have settings to only show the message badge when there are new mentions, but starting today after reloading services when Franz prompted me to it's now showing the unread badge for any new messages on any channel.

**To Reproduce**
Apply notification settings:
Enable notifications: **false**
Enable audio: **false**
Show unread message badges: **true**
Show message badge for all new messages: **false**

**Expected behavior**
I should not get the unread message badge for common messages in Slack.

**Desktop:**
 - OS: Kubuntu 18.04.3 LTS
 - Version 5.4
 - Logged into a premium account

**Additional context**
I was using the version 5.2 when this happened first, then upgraded to 5.4 and the problem persists. I have several other services as well, but only Slack seems to have introduced this problem.

**Comment by briankendall** [comment]
I'm experiencing precisely the same issue. Currently running Franz 5.3.3 on macOS 10.14.6.

**Comment by aphistic** [comment]
I'm also seeing this on Arch Linux (kernel 5.3.13-arch1-1, i3 4.17.1) with Franz 5.4.1-1 installed from the AUR package `franz-bin`.

**Comment by TwistedIsles** [comment]
I am also able to reproduce on Windows 10 - OS Build 19025.1052, Franz 5.3.3

**Comment by Rophuine** [comment]
Same problem, Win 10 version 1809 (build 17763.864), Franz 5.3.3.

**Comment by bndnio** [comment]
Also experiencing. Running macOS 10.14.6 with Franz 5.3.3

**Comment by deepak365** [comment]
I am also facing the same issue. 

macOS: 10.15.1 (19B88)
Franz: Version 5.4.0-beta.2 (5.4.0-beta.2.1646)

**Comment by Donaldini** [comment]
I'm having the same issue.
**macOS**: 10.15.1 (19B88)
**Franz**: 5.3.3 (5.3.3.1582)

**Comment by Donaldini** [comment]
I saw others had a newer version than me so I've updated. Unfortunately the issue still remains.
**macOS: **10.15.1. (19B88)
**Franz: **5.4.1 (5.4.1.1703)

The auto-update also does nothing on my machine. I had to download a new version from the site

**Comment by kylemacey** [comment]
Getting the same thing, but also wanted to note that I disabled "Show message badge for all new messages" to no avail

![image](https://user-images.githubusercontent.com/519171/70157073-e57dae00-1682-11ea-9bf7-faf77f9e862e.png)

|Software|Version|
|:-|-:|
|MacOS|10.14.6|
|Franz|5.3.3|

**Comment by kemenaran** [comment]
A workaround tested on my machine:

1. Go to https://github.com/meetfranz/recipe-slack
2. Download the latest version of the Slack recipe in zip format
3. Unzip the file
4. Rename the directory from `recipe-slack-master` to `slack`
5. Replace the existing Slack recipe with the new folder (see `Franz ▸ Settings ▸ Available services ▸ Custom services` for the location)
6. Restart Franz

**Comment by Donaldini** [comment]
@kemenaran 
It would seem that this kills all notifications. Even though my settings still say I should.

![image](https://user-images.githubusercontent.com/2185680/71072656-40350080-217f-11ea-920e-37d4c4d8d858.png)

**Comment by coertg** [comment]
Any progress on this issue?

**Comment by arlenn** [comment]
I am having this problem as well, slack is always showing one unread message.  

Franz 5.4.1, Windows 10

**Comment by grmmph** [comment]
This issue still exists. should I switch to fredi? :)

**Comment by coertg** [comment]
@grmmph I have made the switch to ferdi, but the issue still persists. Its probably a slack issue :-| .

**Comment by grmmph** [comment]
This happens also on Ferdi :\
