### ISSUE TITLE
Badges notification count always report at least "1" even without mentions

### ISSUE THREAD

**Issue by magobaol** [meetfranz/franz#1715]
I was used to see in Franz badges for slack workspaces a single dot when there are unread messages in any channel, and a number when there are unread mentions, reporting the total of unread mentions.
Now I always see numbers: when I have any amount of unread messages in channels without direct mentions, Franz shows "1" instead of the red dot, confusing me because I think I've mentioned while I'm not.

### Expected Behavior

In the service's badge, I should see:

Unread messages without direct mentions to me (nor @here nor @channel): red dot.
Unread messages directed to me (including @here or @channel): unread direct messages count

### Current Behavior

In the service's badge, I see:

Unread messages without direct mentions to me (nor @here nor @channel): the number "1" (wrong)
Unread messages directed to me (including @here or @channel): unread direct messages count (right)

### Screenshots (if appropriate):
As you can see in the screenshot, the selected service badge reports "1" but I have no mentions in any channel.
![Screenshot 2019-12-06 at 19 18 13](https://user-images.githubusercontent.com/1880350/70346310-5af1a600-185e-11ea-94b3-fcfe3053ee01.png)

### Steps to Reproduce (for bugs)
1. Open Franz, add a slack service.
2. Mark everything as read
3. Wait for any new message in any channel without direct mention
4. See that the service badge shows "1"

### Context
I think the context should be pretty clear by now.

### Your Environment
* Franz Version used: Version 5.3.3 (5.3.3.1582)
* Operating System and version: macOS Mojave 10.14.6 (18G103)

**Comment by magobaol** [comment]
Side note: I know that sometimes the channel does not report a number even when there are direct mentions, but I can guarantee that, in the above screenshot, I didn't have any mention in those two channels

**Comment by LuggLD** [comment]
I have noticed the same problem with slack accounts starting this week - there's now an unread message notification icon for every message, even when I have those disabled:
![image](https://user-images.githubusercontent.com/404530/70388658-eed58600-19b4-11ea-99e0-7d2809eb6004.png)
...and yet, no mention:
![image](https://user-images.githubusercontent.com/404530/70388679-3e1bb680-19b5-11ea-9d40-b24031942447.png)
