### ISSUE TITLE
Cannot connect added services credentials

### ISSUE THREAD

**Issue by muchmoreamusing** [meetfranz/franz#1717]
I have created a Franz account, and added several services on my Mac (Messenger, Sype etc) but after doing so there doesn't appear to be a way to connect those services with my account credentials (Facebook login etc) so when I click on the service nothing appears - only the "Welcome to Franz - Get Started" screen Is there. How on earth do I log in to the services I've added?

Frans v 5.4.1 (5.4.1.1703)
macOS Catalina v 10.15.1

**Comment by PTMGitHub** [comment]
I had this. Reloading Franz sorted it. (View > Reload Franz).
