### ISSUE TITLE
BUG: ToDo drawer shows 'empties' for items

### ISSUE THREAD

**Issue by Capital75** [meetfranz/franz#1718]
The ToDo drawer let's you move ToDo's around. If I do that, a random ToDo becomes an empty spot in the list (screenshot below).

![image](https://user-images.githubusercontent.com/58769076/70607496-d5277f00-1bfe-11ea-93e8-d8314d165f6e.png)

I've restarted Franz, now my ToDo drawer doesn't show anything anymore (another screenshot).

![image](https://user-images.githubusercontent.com/58769076/70607541-ec666c80-1bfe-11ea-8e22-d304812280c7.png)

Franz Version 5.3.3
Windows 10

**Comment by stklik** [comment]
Same bug here. When I rearrange the order of my Todos, some existing elements in the list disappear.

Mac OS Catalina (10.15.2)
Franz 5 (5.4.1.1703)

<img width="301" alt="FranzBug" src="https://user-images.githubusercontent.com/235894/72691645-56612280-3b6a-11ea-9939-9f41243458ab.png">

Here's a screenshot of the errors in the Dev Console:
![image](https://user-images.githubusercontent.com/235894/72691731-f61eb080-3b6a-11ea-8773-e6200fc72a83.png)
