### ISSUE TITLE
GMAIL yield a warning regarding Chrome version in use

### ISSUE THREAD

**Issue by drorata** [meetfranz/franz#172]
When logging into GMAIL, I get the following warning:

```
This version of Chrome is no longer supported. Please upgrade to a supported browser. Dismiss
```

### Expected Behavior

I expect that when the GMAIL screen is opened, no warning will be issued.

### Current Behavior
See screenshot:

<img width="617" alt="screen shot 2017-10-30 at 07 57 45" src="https://user-images.githubusercontent.com/2905978/32158256-1694c316-bd48-11e7-8a46-28387ef08517.png">

### Steps to Reproduce (for bugs)

1. Open Franz
2. Add a GMAIL account
3. Log in to the account
4. See the warning

### Context
I cannot tell what is the impact of this warning and what features work or not.

### Your Environment

* Franz Version used: 4.0.4
* Operating System and version: macOS 10.13

**Comment by adlk** [comment]
There is a new Version of Franz available with a newer chrome version underneath. Please upgrade to Franz 5 (www.meetfranz.com/#download)

**Comment by drorata** [comment]
When checking for updates, I am not notified that there's a newer version. Is it a new bug?

**Comment by adlk** [comment]
Luckily not 😄 
I've made quite drastic changes with the new version and I don't want to force anyone with auto update to use the new version. I'm advertising the new release to a small chunk of users as an optional download.
