### ISSUE TITLE
AppImage v5.4.1 crashes on start, wrong permissions for chrome-sandbox

### ISSUE THREAD

**Issue by vphantom** [meetfranz/franz#1724]
Thanks for sharing Franz as open source! :smiley:

**Describe the bug**
After having manually hunted and found your latest release's `Franz-5.4.1.AppImage` (the download link on the web site yields a 404 at GitHub), I tried running it but after about 5-10 seconds at 100% CPU it crashed (see below).

Seems related to #1477.

**To Reproduce**
1. Download `Franz-5.4.1.AppImage` to `/tmp/`
2. Run: `chmod 755 ./Franz-5.4.1.AppImage`
3. In `/tmp/`, run: `./Franz-5.4.1.AppImage`
4. See error:

```text
[32741:1217/153020.980107:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper
binary was found, but is not configured correctly. Rather than run without sandboxing
I'm aborting now. You need to make sure that /tmp/.mount_Franz-eqhFhl/chrome-sandbox
is owned by root and has mode 4755.
Trace/breakpoint trap
```

**Desktop (please complete the following information):**
 - OS: Debian Buster: Linux titanium 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux

**Comment by andoruB** [comment]
I'm having the exact same issue on Debian Sid
5.3.0-3-amd64 #1 SMP Debian 5.3.15-1 (2019-12-07) x86_64 GNU/Linux

**Comment by jocuen** [comment]
Try to chmod of the file
`sudo chmod 4755 /tmp/.mount_Franz-eqhFhl/chrome-sandbox`
and it should work :-)

**Comment by Krzyrok** [comment]
> sudo chmod 4755 /tmp/.mount_Franz-eqhFhl/chrome

The file is automatically removed after crash so how to change the permission? When executed again, new file in `/tmp` is generated (with new unique hash name)
