### ISSUE TITLE
Cannot sign into Google Hangouts with Franz 5.4.0

### ISSUE THREAD

**Issue by ricmorag** [meetfranz/franz#1727]
I added the Hangouts service on Franz and by logging in I was informed that this browser or app may not be secure.
How to log in to the service through Franz?

**Comment by ricmorag** [comment]
Can someone/anyone help me?

**Comment by gersoncjunior** [comment]
Same with me!

**Comment by gillesguillemin** [comment]
Same applies to other (all?) Google services (e.g. Gmail)

**Comment by gersoncjunior** [comment]
In my case Gmail too.

**Comment by ferbar** [comment]
https://support.google.com/accounts/answer/7675428

So, if the browser is embedded the browser is seen as unsupported. Hopefully Franz finds a workaround...

**Comment by unstressable** [comment]
the thin is, that one of my gmail accounts work, but the other does not work!
The on that works is older and also an @googlemail.com
The newer one that does not work is an @gmail.com only account.

Maybe that helps!

I realized also that my gmail does not apply read items.
For example: I read an email at iPhone and then it appears as unread in franz.
Franz was able to detect that things some time ago...

**Comment by unstressable** [comment]
Issue is doubled:
https://github.com/meetfranz/franz/issues/1720

**Comment by andregce** [comment]
I have an account that works and one that does not. Maybe this is related to 2FA? The account that works does not have 2FA enabled.
