### ISSUE TITLE
Notifications not working at all on Windows 10

### ISSUE THREAD

**Issue by Boosik** [meetfranz/franz#173]
### Expected Behavior
When a message from any service arrives I expect Franz to show notification.

### Current Behavior
When a message from any service arrives, no notification is displayed even if enabled. This issue is present for all my services (Messenger, Hipchat, Inbox, Skype, Allo, Hangouts).

### Steps to Reproduce (for bugs)
1. Add service like Messenger
2. Receive message
3. No notification is shown

### Context
This issue started when updated from v4 to v5.

### Your Environment
* Franz Version used: v5.0.0 beta 11
* Operating System and version: Windows 10 Fall Creators Update

**Comment by adlk** [comment]
I have finally been able to reproduce the issue on Windows 10 and will replace the notification stack with `electron-windows-notifications`.

This might also solve #34 

https://github.com/electron/electron/issues/10864

**Comment by adlk** [comment]
It seems like the Win 10 Fall Creators Update broke the electron notifications. Unfortunately `electron-windows-notifications` nor `node-notifier` work after the specific update. 
I need to do some more testing but I fear that we need to work for a) an electron or b) a windows update. 😱

**Comment by Boosik** [comment]
Would it be possible to convert Franz to UWP and release it on Windows Store? That way you can use native windows notifications.

**Comment by mnakalay** [comment]
I have the exact same problem on Windows 7 64 after upgrading from 4 to 5.

Actually, at first, Franz would show a notification but not the little red number of messages on the icon anymore. I didn't modify my settings but now it's not showing the notifications anymore. And still no red number of messages.

The sound signaling a new message still works though

**Comment by AugustoResende** [comment]
Please fix 👍

**Comment by Tommy544** [comment]
Also have the same problem. Maybe look at Rambox. Similar client build on Electron as well and it has working notifications on Windows even after Fall Creators Update.
