### ISSUE TITLE
Spell check not working in Slack

### ISSUE THREAD

**Issue by joshua-nicholson** [meetfranz/franz#1736]
**Describe the bug**
If I misspell a word in Slack within Franz, I do not get any indication of this.

**To Reproduce**
1. Open Slack
2. Type any word incorrectly in a chat window, like 'wndow'

**Expected behavior**
Slack should underline 'wndow' to note that is is misspelled.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Version 5.4.1.1703

**Additional context**
I understand spell check in Franz is a premium feature and I am on the free tier, but Slack already has spell check so surely I should be able to use it?

**Comment by joshua-nicholson** [comment]
Can I please get a response to this?

**Comment by shaigecelter** [comment]
any update to this? its happening to me also.

**Comment by VivekUday26** [comment]
Happening to me too.
