### ISSUE TITLE
Toggl tracking in MacOS Dock

### ISSUE THREAD

**Issue by erisol** [meetfranz/franz#174]
### Expected Behavior
Either no tracking or correct tracking of Toggl with the opportunity to enable/disable badges.

### Current Behavior
Tracks your Toggl usage, and displays seconds in 1000's.

### Screenshots (if appropriate):
https://imgur.com/a/K6JpB

### Possible Solution
Toggling toggl tracker in the service settings menu

### Context
It's noisy to have a badge that reflects your Toggl activity, especially when the seconds display is in 1000.

### Your Environment

* Franz Version used: Version 5.0.0-beta.11 (5.0.0-beta.11.135)
* Operating System and version: macOS High Sierra Version 10.13

**Comment by adlk** [comment]
A new version of toggl was deployed that solves this issue.
