### ISSUE TITLE
Franz fails to start after update (running flatpak)

### ISSUE THREAD

**Issue by jon2100** [meetfranz/franz#1747]
Updated flatpak Franz
will not run after update get error 

$flatpak run com.meetfranz.Franz
[2:0115/091710.096389:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/Franz/chrome-sandbox is owned by root and has mode 4755.

### Expected Behavior
Franz to start running 

### Current Behavior
does not start and returns this error to the console if you try to start it there.
flatpak run com.meetfranz.Franz
[2:0115/091710.096389:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/Franz/chrome-sandbox is owned by root and has mode 4755
#Entries in /var/log/messages 
Jan 15 09:30:13 fedora29 systemd[7869]: Started flatpak-com.meetfranz.Franz-16532.scope.
Jan 15 09:30:13 fedora29 audit[16542]: ANOM_ABEND auid=1000 uid=1000 gid=1001 ses=13 pid=16542 comm="franz" exe="/app/Franz/franz" sig=5 res=1
Jan 15 09:30:13 fedora29 kernel: traps: franz[16542] trap int3 ip:55cfcc3531a5 sp:7ffd33a57190 error:0 in franz[55cfca3d6000+531d000]
Jan 15 09:30:13 fedora29 systemd[1]: Started Process Core Dump (PID 16544/UID 0).
Jan 15 09:30:13 fedora29 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@13-16544-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 15 09:30:14 fedora29 systemd-coredump[16545]: Process 16542 (franz) of user 1000 dumped core.#012#012Stack trace of thread 2:#012#0  0x000055cfcc3531a5 n/a (/app/Franz/franz)#012#1  0x000055cfcd84ff08 n/a (/app/Franz/franz)#012#2  0x000055cfcd84f38c n/a (/app/Franz/franz)#012#3  0x000055cfcb8c2f58 n/a (/app/Franz/franz)#012#4  0x000055cfcd84e71f n/a (/app/Franz/franz)#012#5  0x000055cfcd854521 n/a (/app/Franz/franz)#012#6  0x000055cfcb8c278c n/a (/app/Franz/franz)#012#7  0x000055cfcd854c24 n/a (/app/Franz/franz)#012#8  0x000055cfcac6ed81 n/a (/app/Franz/franz)#012#9  0x000055cfca3d627b n/a (/app/Franz/franz)#012#10 0x00007f9182200173 n/a (/usr/lib/x86_64-linux-gnu/libc-2.30.so)
Jan 15 09:30:14 fedora29 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@13-16544-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 15 09:30:14 fedora29 abrt-server[16555]: Unsupported container technology
Jan 15 09:30:14 fedora29 abrt-server[16555]: Lock file '.lock' was locked by process 16558, but it crashed?
Jan 15 09:30:14 fedora29 abrt-server[16555]: Error: No segments found in coredump './coredump'
Jan 15 09:30:14 fedora29 abrt-server[16555]: Can't open file 'core_backtrace' for reading: No such file or directory
Jan 15 09:30:14 fedora29 abrt-server[16555]: Deleting problem directory ccpp-2020-01-15-09:30:14.396586-16542 (dup of ccpp-2020-01-15-08:23:28.724156-10883)
Jan 15 09:30:14 fedora29 org.freedesktop.problems[1547]: abrt-dbus: Lock file '.lock' is locked by process 16600
Jan 15 09:30:14 fedora29 abrt-notification[16601]: Process 10883 (franz) crashed in ??()

### Steps to Reproduce (for bugs)
1. flatpak run com.meetfranz.Franz  

### Your Environment
* Franz Version used: latest
* Operating System and version: fedora 29
All other flatpak applications are running as expected

**Comment by jon2100** [comment]
Update if I run with --no-sandbox it will run correctly

**Comment by Timecrash** [comment]
For me, Franz started working again once I restarted my machine.
