### ISSUE TITLE
Google calendar with 2FA won't sign in

### ISSUE THREAD

**Issue by mhatvan** [meetfranz/franz#1749]
**Describe the bug**
I recently added 2FA with Google Authenticator to my Google account, then had to re-login to my Google Calendar, but it didn't work.

**To Reproduce**
1. Enter username in Google Calendar
2. Enter password in Google Calendar
3. The message provided in the screenshot appears

**Expected behavior**
Expect the Google Calendar display how it was without 2FA. 

**Screenshots**
![Screenshot from 2020-01-21 08-15-11](https://user-images.githubusercontent.com/16797721/72783758-7a366e00-3c27-11ea-9462-04f279c056dc.png)

**Desktop**
 - OS: Ubuntu 18.04.3 LTS, but same for higher Ubuntu version.

**Comment by JoeStead** [comment]
This looks to be the same as #1573 btw - and I have recently hit this too, it's bloody annoying

**Comment by supermarkert** [comment]
And same as #1720
