### ISSUE TITLE
Todoist service does not work on version 5.0.0-beta.11

### ISSUE THREAD

**Issue by Sparkiechu** [meetfranz/franz#175]
This is the message that appears: https://puu.sh/yaDJ1/fa6ece9f71.png
I have tried reloading the service but it does not change. Please fix.

**Comment by erisol** [comment]
This is most likely due to your browser (Chrome) settings now allowing third-party cookies. Probably nothing the developer can do.

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
https://github.com/avatarkava/recipe-todoist
