### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by rctneil** [meetfranz/franz#1754]
Is Franz dead or alive? It's not had an update or message from a dev for a long time now.

There's some sort of bug that causes so much CPU/memory usage that is completely stopping me from using the app.

What's the status?

**Comment by vantezzen** [comment]
It looks like Franz development is still going on in the https://github.com/meetfranz/franz/tree/release/5.5.0 branch.
Otherwise you can also take a look at https://getferdi.com/ which is a community fork of Franz.

**Comment by lisaq** [comment]
The 5.5.0 branch also doesn't look particularly active. I'll try out Ferdi, thanks!

I'm having the same CPU issue, but only on the instance where I have Workspaces set up.

**Comment by Serubin** [comment]
I also wonder this. I have several active PRs to fix known issues and have tried to reach out to @adlk and his team. I heard heard nothing since November... I pay for this and contribute, I'm a little frustrated at the lack of response

**Comment by alexdevero** [comment]
@sergiughf  I've been using Franz for about a year and it does look like the development has been slowing down in the last few months. I suggest what @vantezzen mentioned, i.e. looking at Ferdi, for of Franz. This project seems to be more active.
