### ISSUE TITLE
Franz was several years with me, now he is knocking on the gates of heaven. 

### ISSUE THREAD

**Issue by Eckybrazzz** [meetfranz/franz#1755]
**Describe the bug**
Suddenly won't start, simply dies.

**To Reproduce**
Click on start as normal
**Expected behavior**
That meetfranz starts up as it did for the last several years.
**Screenshots**
Not possible, due lack of startup
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 PRO

**Comment by PolCPP** [comment]
Just had this issue too, its annoying but if you delete %appdata%/Franz it launches

**Comment by Eckybrazzz** [comment]
@PolCPP Thanks, one correction. I had to delete %appdata%/Roaming/Franz and it launches

**Comment by Drenock** [comment]
> @PolCPP Thanks, one correction. I had to delete %appdata%/Roaming/Franz and it launches

@Eckybrazzz your %APPDATA% environment variable should be set to the Roaming Folder by default in Windows installations, @PolCPP Path is the correct one. Please report to this article :
https://www.computerhope.com/issues/ch000088.htm
