### ISSUE TITLE
Feature Request: Choose Browser That Links Open in by Workplace

### ISSUE THREAD

**Issue by KyleAtDND** [meetfranz/franz#1762]
### Feature Description
The idea is that I use different browsers for different parts of my work/home balance. I have a workplace and browser for "home" stuff then another one for workplace and browser for "work" stuff. It would be AMAZING to have a feature on the Workplace level where we could select which browser external links would open in when they are clicked when the workplace is open. For instance, I’m in Slack in my "Personal" workplace. I have my "Personal" workplace set to open external links in Firefox (even though my system default browser is Google Chrome). I click an external link in this Slack channel, and that link open in Firefox.

### Motivation and Context
This helps integrate Franz better with a user's browser experience. Many people use different browsers and don't necessarily want all external links opening in the default browser. This would solve that problem and be fairly easy to implement. It would be a setting on the Workspace level (the default setting would be to open the links in the system default browser).

**Comment by Gaboris** [comment]
Oh so basically add an option to set what browser to default to instead of only using the one set to default in the system? I'm in! +1
