### ISSUE TITLE
Sync TODO list with custom server / Franz TODOs API

### ISSUE THREAD

**Issue by bergercookie** [meetfranz/franz#1763]
Hi there,

Is there an API to connect and fetch the Franz TODOs?
I'm interested in syncing my franz todos with my todo list in [taskwarrior](https://taskwarrior.org/).

P.S. Franz is awesome, thanks so much for open-sourcing and maintaining it.

**Comment by rob-orch** [comment]
The Todos are stored on https://app.franztodos.com - maybe you can open and use that page using a script.

Otherwise you can try https://github.com/getferdi/ferdi which allows you to change the Todos service to any other website

**Comment by leikoilja** [comment]
Oh, some API endpoints would be so so so useful! Love Franz
