### ISSUE TITLE
Is this software still in development?

### ISSUE THREAD

**Issue by jamc92** [meetfranz/franz#1768]
Google services are not working

See the images below
![Captura de pantalla 2020-02-19 a la(s) 8 57 32 a  m](https://user-images.githubusercontent.com/1733996/74841236-5c2b5e80-52f6-11ea-8794-0543c29e4ca2.png)
![Captura de pantalla 2020-02-19 a la(s) 8 57 27 a  m](https://user-images.githubusercontent.com/1733996/74841241-5e8db880-52f6-11ea-8648-d76be70363c9.png)
There is no much to explain just to make them work

I am using Mac OS X High Sierra and the latest version of Franz

**Comment by kohlmanndean** [comment]
I had the same issue and [this](https://github.com/meetfranz/franz/issues/1573#issuecomment-566464050) worked for me after a fresh install. 

Good luck!

**Comment by mssngr** [comment]
The issue has been going on for a year, though. I'm on the 14 day free trial. Would be nice to know if there is a dev team, still, before I shell out subscription dollars. Last commit to master was 4 months ago.

**Comment by rctneil** [comment]
@mssngr Give Ferdi a try: https://github.com/getferdi/
