### ISSUE TITLE
Gmail + Google Calendar Unable to login

### ISSUE THREAD

**Issue by chewwwwwwwwww** [meetfranz/franz#1771]
**Describe the bug**
Whenever I try and login to a Gmail or Gcal, it redirects me to this page

**To Reproduce**
1. Add Gmail/Gcal as a service
2. Try logging into an account with a @gmail or business domain
3. See error

**Screenshots**
<img width="431" alt="Screenshot 2020-02-27 at 1 13 50 PM" src="https://user-images.githubusercontent.com/7550669/75414772-9a62f680-5964-11ea-8392-c2e582269232.png">

**Desktop (please complete the following information):**
 - macOS 10.15.3 Catalina
 - Franz Version 5.4.0-beta.3

**Comment by thenamelessthing** [comment]
I have the same problem with Gmail and Hangout...

**Comment by brian-jarvis** [comment]
You can override this issue by editing the index.js file in the recipe.
Change 
```
module.exports = Franz => Franz;
```
To
```
module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
```

The recipe should be located at:
Mac: `~/Library/Application Support/Franz/recipes/`
Windows: `%appdata%/Franz/recipes/`
Linux: `~/.config/Franz/recipes/`

**Comment by shimatai** [comment]
This is not working anymore for Linux (I'm on Ubuntu 18.04).

> You can override this issue by editing the index.js file in the recipe.
> Change
> 
> ```
> module.exports = Franz => Franz;
> ```
> 
> To
> 
> ```
> module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
> ```
> 
> The recipe should be located at:
> Mac: `~/Library/Application Support/Franz/recipes/`
> Windows: `%appdata%/Franz/recipes/`
> Linux: `~/.config/Franz/recipes/`

**Comment by jasonsyoung** [comment]
Duplicate: https://github.com/meetfranz/franz/issues/1573

**Comment by RoiArthurB** [comment]
> This is not working anymore for Linux (I'm on Ubuntu 18.04).
>> You can override this issue by editing the index.js file in the recipe.
>> Change
>> ```
>> module.exports = Franz => Franz;
>> ```
>> To
>> ```
>> module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
>> ```
>> The recipe should be located at:
>> Mac: `~/Library/Application Support/Franz/recipes/`
>> Windows: `%appdata%/Franz/recipes/`
>> Linux: `~/.config/Franz/recipes/`

@shimatai it worked for me. I changed it in the folder corresponding to the proper service (so `~/.config/Franz/recipes/hangouts/index.js` for me), changed the line and it did the tricks !

I'm on Manjaro 19.0.2 :ok_hand:

**Comment by jasonsyoung** [comment]
> > This is not working anymore for Linux (I'm on Ubuntu 18.04).
> > > You can override this issue by editing the index.js file in the recipe.
> > > Change
> > > ```
> > > module.exports = Franz => Franz;
> > > ```
> > > 
> > > 
> > > To
> > > ```
> > > module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
> > > ```
> > > 
> > > 
> > > The recipe should be located at:
> > > Mac: `~/Library/Application Support/Franz/recipes/`
> > > Windows: `%appdata%/Franz/recipes/`
> > > Linux: `~/.config/Franz/recipes/`
> 
> @shimatai it worked for me. I changed it in the folder corresponding to the proper service (so `~/.config/Franz/recipes/hangouts/index.js` for me), changed the line and it did the tricks !
> 
> I'm on Manjaro 19.0.2

Do you have 2 factor authentication enabled?

**Comment by RoiArthurB** [comment]
Yes

**Comment by SrBrahma** [comment]
> module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
> ```
> 
> The recipe should be located at:
> Mac: `~/Library/Application Support/Franz/recipes/`
> Windows: `%appdata%/Franz/recipes/`
> Linux: `~/.config/Franz/recipes/`

Solution works. Why it isn't the default?

**Comment by ehausen** [comment]
Didn't work for me. Gmail behaviour changed though. Now I first get the first marketing page of gmail and when clicking Sign in --> Link opens in a new tab and I end up at the Account Chooser page.

Also Slack has a similar problem.

Could i be the **_device_** which is apparently _**Electron**_?


![image](https://user-images.githubusercontent.com/6204129/77996713-ce9c4f00-7336-11ea-9444-befda0026b19.png)

![image](https://user-images.githubusercontent.com/6204129/77997312-d8728200-7337-11ea-8168-e59ad12bc935.png)

![image](https://user-images.githubusercontent.com/6204129/77997472-26878580-7338-11ea-88f8-6c8c266a0a1b.png)
