### ISSUE TITLE
Remove Google Inbox

### ISSUE THREAD

**Issue by Prajwal-Koirala** [meetfranz/franz#1774]
Let's remove google inbox.

```
Last September, Google broke a lot of hearts when it announced that Inbox by Gmail would be shutting down in March 2019. While it may be March 19 and Inbox is working just fine, the end is nigh. Google's started showing a pop-up on the Inbox app and website confirming that the app will shut down in 14 days.Mar 19, 2019
```

https://www.extremetech.com/mobile/287967-google-inbox-closes-for-good-on-april-2
https://www.androidcentral.com/google-shutting-down-inbox-april-2-2019
https://www.theverge.com/2018/9/12/17848500/google-inbox-shut-down-sunset-snooze-email-march-2019
https://seo-hacker.com/google-inbox-shutting-down/

**Comment by nishp77** [comment]
hi could anyone help me with this where exactly is the code?? There's not enough documentation
