### ISSUE TITLE
Focus moves to last loaded service instead of staying on the active one

### ISSUE THREAD

**Issue by Sayrus** [meetfranz/franz#1776]
**Describe the bug**
When using a service, if another service finish loading (for instance, it refreshed or after login), focus will be moved to this service.
If you are typing your password several times, you might end up typing your password in another service (like gmail or chat app)

**To Reproduce**
With the services I use:
- Use two services: GMail and GCalendar, both on login screen
- Open GMail and login
- Move to GCalendar before GMail is fully loaded (type Enter and move to GCalendar)
- Begin typing your credentials

The focus should move back to GMail while you are typing.

**Expected behavior**
The focus should always stay on the active service (or the active service should be switched but that sounds like a bad idea).

**Screenshots**
I should be able to do a video if you need help reproducing the bug.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Browser : Safari (Version 13.0.5 (15608.5.11)) / Firefox (default) (73.0.1 (64-bit))
 - Version [e.g. 22] : ---

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JoeyFerg** [comment]
I have a similar issue - if I'm typing an email in Gmail and get a message in Google Chat, it will switch my "typing focus" to reply to the message in Google Chat (but it doesn't actually switch services). I'm on Mac OS 10.15.4, Franz version 5.5.0-beta.4.

Super frustrating and annoying when you have a lot of messages going on. I would love to see this fixed soon. Thank you guys!
