### ISSUE TITLE
Microsoft teams - sharing screen on linux does not work

### ISSUE THREAD

**Issue by henriquesschmitt** [meetfranz/franz#1780]
**Describe the bug**
when i'm on a call via microsoft teams and i try to share my screen, no action is taken.

**To Reproduce**
1. Start a Call
2. Clink on share screen
4. Nothing happens

**Expected behavior**
your screen should start to be shared with the people on the call

**Comment by asymetricbalance** [comment]
Same issue on Win10. I can see the shared screen from my conversations partner, but are not able to share mine from franz.

**Comment by evilSwanson** [comment]
I experience the same problem on Ubuntu 19.10 with the Franz-5.4.1.AppImage.

**Comment by nirusuu** [comment]
I believe this is a duplicate of #1725

**Comment by dutscher** [comment]
teams in chrome itself is able to share the screen. it might be an issue with the browser api?
i have win10 and newest chrome.
