### ISSUE TITLE
Google Calendar not working

### ISSUE THREAD

**Issue by alexseuthe** [meetfranz/franz#1782]
When logging in to the Google Calendar feature I get:

```python
Anmeldung nicht möglich
Dieser Browser oder diese App ist unter Umständen nicht sicher.
Weitere Informationen

Verwenden Sie einen anderen Browser.
Wenn Sie bereits einen unterstützten Browser nutzen, 
können Sie Ihren Bildschirm aktualisieren und noch einmal versuchen, 
sich anzumelden.
```

Could you please fix this in the pay version or am I doing something wrong?

**Comment by blaise-io** [comment]
My Google Calendar is working.

I get this message in Whatsapp sometimes when the app has been open for a few days. Reloading the app helps in that case, maybe that also works for your Google Calendar.

**Comment by alexseuthe** [comment]
Hi @blaise-io thanks for the advice. I rebooted my Mac and restarted the software, but the error persists.

**Comment by askemeline** [comment]
Hi, you can do this
`vi ~/Library/Application\ Support/Franz/recipes/googlecalendar/index.js`
and past 
```
"use strict";

module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
```

**Comment by alexseuthe** [comment]
@askemeline thanks for the information. This fix is working indeed!

**Comment by VTiSnaut** [comment]
Hey guys, 
I am facing the exact same problem as alex. However, I'm a complete noob and fool in terms of coding, so I would really like to fix the problem - however, I don't quite get askemeline's answer. can you explain it a little more step-by-step to me? That would be much appreciated :) 

Cheers

Seb

**Comment by askemeline** [comment]
Hello,
You can open the file and modify it with Visual Studio Code, I think it's the simple way. 
Go to the folder :
for Mac:` ~/Library/Application\ Support/Franz/recipes/googlecalendar/`
for Windows: `%appdata%/Franz/recipes/googlecalendar/`
for Linux:` ~/.config/Franz/recipes/googlecalendar/`

And open `index.js`
Now you can modify the file and add the new one

```"use strict";

module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
```

Hope It's will be ok for you :)

**Comment by VTiSnaut** [comment]
It worked! 
Hallelujah, you guys and gals are amazing! THANK YOU :) :)

**Comment by explorovatel** [comment]
> Hello,
> You can open the file and modify it with Visual Studio Code, I think it's the simple way.
> Go to the folder :
> for Mac:` ~/Library/Application\ Support/Franz/recipes/googlecalendar/`
> for Windows: `%appdata%/Franz/recipes/googlecalendar/`
> for Linux:` ~/.config/Franz/recipes/googlecalendar/`
> 
> And open `index.js`
> Now you can modify the file and add the new one
> 
> ```
> 
> module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
> ```
> 
> Hope It's will be ok for you :)

Hi, thank you for sharing. I think I'm more noob in this as I can't find this link ~/Library/Application\ Support/Franz/recipes/googlecalendar/` or really don't know how to find it and fix it. I'm having Mac and download the Visual Studio code. I'm really lost with my google calendar and Gmail. Would you be nice to show me either in Video or write easier for me? Much appreciate your time. Thank you!

**Comment by askemeline** [comment]
> > Hello,
> > You can open the file and modify it with Visual Studio Code, I think it's the simple way.
> > Go to the folder :
> > for Mac:` ~/Library/Application\ Support/Franz/recipes/googlecalendar/`
> > for Windows: `%appdata%/Franz/recipes/googlecalendar/`
> > for Linux:` ~/.config/Franz/recipes/googlecalendar/`
> > And open `index.js`
> > Now you can modify the file and add the new one
> > ```
> > 
> > module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
> > ```
> > 
> > 
> > Hope It's will be ok for you :)
> 
> Hi, thank you for sharing. I think I'm more noob in this as I can't find this link ~/Library/Application\ Support/Franz/recipes/googlecalendar/` or really don't know how to find it and fix it. I'm having Mac and download the Visual Studio code. I'm really lost with my google calendar and Gmail. Would you be nice to show me either in Video or write easier for me? Much appreciate your time. Thank you!

Hi, no problem ^^
- Open the Terminal ( Command + Space and Type in “Terminal”)
- Then copy past this `open ~/Library/Application\ Support/Franz/recipes/googlecalendar/`
(it's open the current folder for google calendar from Franz)
- You will see different files (calendar.css, icon.svg, package.json ...) but don't worry about that just you need to check `index.js`
- Right-click on index.js and Open With Visual Studio Code
- Now you see some code, change all the code with
```
"use strict";

module.exports = Franz => class useragent extends Franz { overrideUserAgent() { return "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136"; } };
```
- Now save index.js on vscode and restart Franz 

By the way for Gmail it the same logic (just change the folder googlecalendar by gmail)
`open ~/Library/Application\ Support/Franz/recipes/gmail/` and changed index.js as you did in googlecalendar :)

Hope it helps :)
