### ISSUE TITLE
Gmail Integration not working

### ISSUE THREAD

**Issue by ahuang91** [meetfranz/franz#1786]
**Describe the bug**
Logging into gmail gives a "this browser or app may not be secure" prompt

**To Reproduce**
1. Go to gmail integration
2. attempt to log in
3. See error

**Expected behavior**
get logged in

**Screenshots**
![image](https://user-images.githubusercontent.com/1687122/76913646-dbb83900-6874-11ea-94dc-249b78ad8837.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser - N/A
 - Version - Version 5.4.0 (5.4.0.1695)

**Comment by anandx** [comment]
https://github.com/meetfranz/franz/issues/1771

that worked for me

**Comment by shimatai** [comment]
I'm using Franz on Ubuntu 18.0.4 and #1771 doesn't work anymore.
I think that Franz team will have to do a workaround in code, forcing the webview to use a user-agent that Gmail cannot probe using another technics.

**Comment by mylemans** [comment]
When can we expect a fix for this?

**Comment by rispig** [comment]
Any news about this? both gmail and gcal are not working
