### ISSUE TITLE
Franz won't start in Ubuntu 18.04

### ISSUE THREAD

**Issue by valeriocomo** [meetfranz/franz#1789]
**Describe the bug**
Franz won't start in Ubuntu 18.04 with _/tmp_ mounted in RAM

**To Reproduce**
1. Run Franz 
2. Application won't start

**Expected behavior**
I expect to run Franz

**Screenshots**
From Franz console:
![franz](https://user-images.githubusercontent.com/7393493/77231851-c8231000-6b9d-11ea-82c0-ea5c6efed4f0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: N/A
 - Version: Franz 5.4

**Additional context**
My PC mount /tmp in RAM. In order to do so, please follow this steps:
1. From terminal, open _/etc/fstab_ with root privileges
2. Add the following line at the end of the file:
`tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777 0 0`
3. Save and exit
4. Run _sudo mount -av_ in order to mount /tmp in RAM

**Comment by maximegti** [comment]
Hi Valerio! I just installed Linux mint LMDE4 on USB SSD. All is working fine, but Franz won't start!
Do you think that mount /tmp in ram could be the solution?

**Comment by valeriocomo** [comment]
hi @maximegti! I think /tmp in ram is the problem. Franz starts if /tmp is not mounted in ram. Otherwise, if /tmp is mountend in ram, Franz won't start.

**Comment by maximegti** [comment]
SOLVED!
Esecuting Franz from terminal this was the error: 
[_26070:0323/171100.876021:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Franz/chrome-sandbox is owned by root and has mode 4755._
Then I do that:
sudo chown root:$USER /opt/Franz/chrome-sandbox
sudo chmod 4755 /opt/Franz/chrome-sandbox_
Now it works!

**Comment by carlosnewmusic** [comment]
> SOLVED!
> Esecuting Franz from terminal this was the error:
> [_26070:0323/171100.876021:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Franz/chrome-sandbox is owned by root and has mode 4755._
> Then I do that:
> sudo chown root:$USER /opt/Franz/chrome-sandbox
> sudo chmod 4755 /opt/Franz/chrome-sandbox_
> Now it works!
I also had the same error in debian buster and it has been solved with those commands
