### ISSUE TITLE
Hangouts service lost functionality

### ISSUE THREAD

**Issue by stealthgyro** [meetfranz/franz#179]
The dial feature from hangouts no longer appears to work nor can it read from my contacts. So all of my SMS from Project FI are just phone numbers. Clicking phone call just gets stuck at "loading contacts"

**Comment by canac** [comment]
Duplicates https://github.com/meetfranz/recipe-hangouts/issues/1

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
https://github.com/meetfranz/recipe-hangouts/
