### ISSUE TITLE
Place of personal passwords for saving/backup (missing manual/description)

### ISSUE THREAD

**Issue by Winteriver** [meetfranz/franz#1790]
General summary
As described on the Franz-weppage all services are saved in the cloud, but no password of each service.

Expected Behavior
There should be a password file/settings file, which can backuped locally, of the user/user profile must be mooved or changed.

Current Behavior
There is no description, in which file/places local passwords are saved.

Possible Solution
Please provide information, where local passwords for services are saved.
Alternatively provide information, where local Coockies, keeping this information, are saved.

Steps to Reproduce (for bugs)
This is the folder of a Franz installation:
C:\Users\<username>\AppData\Roaming\Franz

In this folder there are several folders (e.g. Coockies).
Which folder keeps local password data?

Your Environment
Windows 10 Pro x64 Build 1909
Franz Pro 5.4.0

Thanks to all of you for this great piece of software!!!

Cheers, Markus

**Comment by rob-orch** [comment]
Your sessions are saved in `C:\Users<username>\AppData\Roaming\Franz\Partitions` - Password itself are never stored. Copying that file should at least copy your current sessions over.

**Comment by KristerV** [comment]
I reinstalled my linux from scratch and took the 4gb of data from ~/.config/Franz with me. Put in in the same place, installed Franz, and din't even have to log it - everything is as I left it. Nice!
