### ISSUE TITLE
Franz needs a lot of resources on MacOS 10.15.3

### ISSUE THREAD

**Issue by klouisbrother** [meetfranz/franz#1791]
**Description:**
As soon as Franz is started on MacOS 10.15.3, the CPU resources are more than 50% are comited to Franz. Also the fan starts. I already cleared the cache, didn't help.

**To Reproduce**
1. Start Franz
2. Watch the CPU
3. Close Franz (Fixes the Problem).

**Expected behavior**
Less resources and no Fan start

**Desktop (please complete the following information):**
- Hardware: MacBook Pro (Retina 13 Zoll, Early 2015), 2,7 GHz Dual-Core Intel Core i5, 8 GB Ram
 - OS: MacOs 10.15.3
 - Browser: Google Chrome
 - Version: 80.0.3987.132

**Comment by rob-orch** [comment]
Maybe you have too many services in Franz? If removing services doesn't help then I can recommend Ferdi (http://getferdi.com/) which seems to have some features (like service hibernation and a process manager) that helped me get the resource usage down quite a bit.

**Comment by klouisbrother** [comment]
> Maybe you have too many services in Franz? If removing services doesn't help then I can recommend Ferdi (http://getferdi.com/) which seems to have some features (like service hibernation and a process manager) that helped me get the resource usage down quite a bit.

Thank you! I will have a look - but this will not solve the issue with / in Franz. I have 6 services in use in parallel. Is this „too much“? 😅
