### ISSUE TITLE
No vk account

### ISSUE THREAD

**Issue by karaalat** [meetfranz/franz#18]
No Vk account 

### Feature Description
On the previous version there was a Vk account 

### Motivation and Context

* I used it
* More users will use your new app
* Some users including me won't delete this app

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
