### ISSUE TITLE
Couldn't Sign Into Google Keep

### ISSUE THREAD

**Issue by Joejoboi** [meetfranz/franz#1802]
### Screenshots (if appropriate):
<img width="652" alt="Screen Shot 2020-03-28 at 11 38 47 AM" src="https://user-images.githubusercontent.com/34189649/77831109-54778a80-70ea-11ea-8071-113a82c32536.png">

### Steps to Reproduce (for bugs)
{"host":{"platform":"darwin","release":"18.7.0","screens":[{"bounds":{"height":1050,"width":1680,"x":0,"y":0},"id":69733632,"rotation":0,"scaleFactor":2,"size":{"height":1050,"width":1680},"touchSupport":"unknown","workArea":{"height":1027,"width":1680,"x":0,"y":23},"workAreaSize":{"height":1027,"width":1680}}]},"franz":{"version":"5.3.3","electron":"4.2.4","installedRecipes":[{"id":"android-messages","version":"1.3.0"},{"id":"franz-custom-website","version":"1.0.0"},{"id":"gmail","version":"1.2.0"},{"id":"googlecalendar","version":"1.0.0"},{"id":"googlekeep","version":"1.0.0"},{"id":"hangouts","version":"1.0.0"},{"id":"linkedin","version":"1.0.0"},{"id":"messenger","version":"1.0.8"},{"id":"pocket","version":"1.0.0"},{"id":"skype","version":"1.2.0"},{"id":"slack","version":"1.0.12"},{"id":"toggl","version":"1.0.1"},{"id":"tweetdeck","version":"1.0.2"},{"id":"whatsapp","version":"1.0.20"},{}],"devRecipes":[],"services":[{"id":"3fc115d0-187a-4fc9-aa04-5f53f3d245b7","recipe":"googlekeep"},{"id":"6cb67c3e-faaf-4d2f-a8a4-ef47c15144d8","recipe":"whatsapp"},{"id":"a9d2482d-c2db-4358-9e25-3441c4d7c9de","recipe":"slack"},{"id":"38b45fd4-6277-4ac9-9189-be5beaa6da15","recipe":"slack"},{"id":"346f4cb4-218c-4a9e-a2b1-dee63ec4963a","recipe":"googlecalendar"},{"id":"2d8a081f-2168-40d9-8462-75d9c1babac0","recipe":"linkedin"},{"id":"c1ab2a5b-ecae-4530-9287-0d927a9f3992","recipe":"gmail"},{"id":"b6430c01-3cce-49e3-b813-7c09d129c6ab","recipe":"slack"},{"id":"0485ad2b-31bf-4200-a84e-aaa9d37f2e10","recipe":"slack"},{"id":"6e0db9b8-fde9-4a99-b302-4dd6a9da8791","recipe":"messenger"},{"id":"a6c57eb1-29ae-4b7d-a8e8-db748e772673","recipe":"pocket"},{"id":"7d39f0ae-9359-4efe-ae74-c615d8905894","recipe":"toggl"},{"id":"a155e922-511c-4e48-93f2-a44830619192","recipe":"hangouts"},{"id":"b3eff08c-835b-4c7b-8c57-43388cb6b5fc","recipe":"tweetdeck"},{"id":"2851189c-516a-46d5-a28c-ea9d072996d3","recipe":"skype"},{"id":"4c702e54-86d5-4135-81cb-47d20f1cae4e","recipe":"slack"},{"id":"3b1ac7d7-0248-48f9-b4e0-b1d5111701ad","recipe":"android-messages"}],"workspaces":[],"windowSettings":{"width":1019,"height":751,"x":150,"y":101,"displayBounds":{"x":0,"y":0,"width":1680,"height":1050},"isMaximized":true,"isFullScreen":false},"user":"99cd9bfa-9f3f-4dd4-a7a3-d23bf7c760c3"}}

### Your Environment

* Franz Version used: Version 5.3.3 (5.3.3.1582)
* Operating System and version: macOS Mojave 10.14.6 
Chrome: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by thomasboni** [comment]
Seems to be related to  #1786

**Comment by asymetricbalance** [comment]
All issues related to Google seem to have the same underlying issue. Try solution described in multiple threads -i.e. #1584 
Franz and Ferdi seem to have different development status at this point.
