### ISSUE TITLE
Zoom in/zoom out not working

### ISSUE THREAD

**Issue by maguayo6** [meetfranz/franz#1806]
**Describe the bug**
When adjusting the size of a service under the <View> tab, none of my services resize smaller or larger whether I'm using the menu option or ctrl+- and ctrl+=

This was a fresh install on a new windows operating system. The commands work fine in all other applications.

**Comment by embql** [comment]
It's been an issue for a while (#1668 #1673 #1677)
However, have you tried installing the new 5.5.0-beta.1 ?
Looks like zoom is fixed: 8d06fbc36d2ba69e0c38b09d59988f29664247f1 thanks to @vantezzen

**Comment by maguayo6** [comment]
Oh cool thanks, do I have to install the beta separably or can I activate it through the settings within Franz?

**Comment by embql** [comment]
If you're on an older version, my best bet is to download and upgrade to the newest version from here (as of this time, 5.5.0-beta1) right here: https://github.com/meetfranz/franz/releases/tag/v5.5.0-beta.1
No need to uninstall the previous one, and second, the upgrade will keep your apps and settings, don't worry.
