### ISSUE TITLE
Impossible to reinstall Franz on windows 10.0.17763.1098

### ISSUE THREAD

**Issue by malagem** [meetfranz/franz#1815]
Had Franz 5.4.0 installed on windows 10.0.17763.1098 and working fine. Got a notice for a updated version 5.5.0 featuring new "hibernation" mode. Decided to give it a try and went for the update.

After installing update, Franz won't start anymore. Running the app gives an error popup stating "**This file does not have an app associated with it for performing this action**".

Tried several reboots => **no luck**.

Tried several updates to 5.4.0 => **no luck**.

Tried uninstalling 5.4.0 =>**uninstaller hanged up**.

Killed the uninstaller from the task manager and rebooted. Tried again => **same issue**.

Ended up rebooting, deleting /users/xxx/appdata/local/programs/franz, then reboot again.

After reboot, attempted fresh install of 5.4.0 => **Installer freezes right after launch they hangs forever**.

Killed installer from task manager, then reboot.

Retried several times => **no luck**.

Ended up rebooting one last time, copied the /users/xxx/appdata/local/programs/franz folder from another machine (was running 5.3.3 I think, not sure), then ran the update to 5.4.0, and boom, voilà, it worked.

Don't know what happened here, but that's quite odd.

**Comment by mzhang13** [comment]
How do I even find the uninstaller? Franz keeps popping up and I cannot figure out how to remove it from my Windows as well.
