### ISSUE TITLE
Repeatedly getting notification on losing connection to Hangouts Chat

### ISSUE THREAD

**Issue by chadlwilson** [meetfranz/franz#1818]
**Describe the bug**
Over the last few days (maybe since `5.5.0-beta.2` update?), I repeatedly get the popup on my Hangouts Chat service that Franz has lost connection "Oh no! Franz lost the connection to Hangouts Chat.". Sometimes this happens immediately after reloading the service, sometimes a bit later.

The service otherwise seems to be working though, can send and receive messages, so not sure if this is a false positive.

**To Reproduce**
1. Connect to Hangouts Chat
2. Wait. Sometimes immediate

**Expected behavior**
Connections not lost, or at least no persistent pop-ups.

**Desktop (please complete the following information):**
 - **OS**: MacOS Catalina 10.15.4
 - **Browser**: Firefox is my default browser, but not sure what Franz does internally.
 - **Version**: Franz `5.5.0-beta.2`

**Comment by cuperusj** [comment]
Also an issue, chrome default, same build

**Comment by mucki1987** [comment]
Same issue with other services. e.g. whatsapp, threema, trello.
Slack, Telegram and others are working fine.

**Comment by chadlwilson** [comment]
Interesting, I don't have any issues with WhatsApp, Slack, Messenger, Telegram. Only Hangouts Chat is an issue here.

**Comment by xFeXx** [comment]
Same Issue here, Whatsapp and Hangouts show the message.
**Desktop:**
**OS**: MacOS Mojave 10.14.6
**Version**: Franz 5.5.0-beta.2

from dev console I saw this message:
`Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: ERR_FAILED (-2) loading 'https://web.whatsapp.com'
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke (electron/js2c/renderer_init.js:2470)`

**Comment by chadlwilson** [comment]
In `5.5.0-beta3` the visibility of this issue seems to have been changed to a big red highlighting of the service button rather than the notification (which is an improvement since the notification was over the top of the message box in Hangouts Chat!) however I am inferring that the issue is still present.

**Comment by chadlwilson** [comment]
This problem seems to have gone away for me now. Not sure if due to `5.5.0-beta4` or a change on Google side, but closing this as a result. For others, let me know if you are still having issues on `beta4`+.
