### ISSUE TITLE
Can't see Hangouts desktop and icon notification on mac

### ISSUE THREAD

**Issue by erezr** [meetfranz/franz#182]
### Expected Behavior
Get desktop notification and new message icon when receiving new message.

### Current Behavior
When receiving a message on hangouts I can only hear the sound but no desktop notification or red icon of number of new messages in the top menu is appearing.
I'm indeed getting the icon on gmail or whatsapp.

### Steps to Reproduce (for bugs)
get new message in hangouts

### Context
As hangouts is my main working platform its hard to use Franz on my mac. using the chrome extension instead.

### Your Environment
macOS Sierra. Version 10.12.5
![image](https://user-images.githubusercontent.com/29533717/32215221-0b208f32-be2a-11e7-8c2d-43146e13ccf3.png)

Thanks.

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
[Hangouts repository](https://github.com/meetfranz/recipe-hangouts)
