### ISSUE TITLE
Franz API is Down

### ISSUE THREAD

**Issue by seesemichaelj** [meetfranz/franz#1833]
**Describe the bug**
I'm receiving an error:
> Could not load services and user information

If I open the developer tools, it looks like both the `https://api.franzinfra.com/v1/me/services` and `https://api.franzinfra.com/v1/me` api requests are responding with a `503 Temporarily Unavailable` error

I was silly and tried to reload Franz completely, and now I can't get to any of my services

**To Reproduce**
1. Open the Developer Tools
1. Go to the Network tab
1. Notice failing requests to `me` and `services`

**Screenshots**

![image](https://user-images.githubusercontent.com/549323/80417357-73547280-888a-11ea-94f6-bf55b8351c92.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Franz AppImage
 - Version 5.5.0-beta.4
 - Release 8.1.1 / linux / x64

**Comment by richardsim7** [comment]
Same on Win10 x64

**Comment by Arkanius** [comment]
Same here

**Comment by bonachea** [comment]
Same - please fix ASAP!

**Comment by firewater2** [comment]
Same

**Comment by richardsim7** [comment]
It's back up for me

**Comment by MasterGeekMX** [comment]
Same in Arch and Fedora 31

**Comment by scbarton** [comment]
Same on Mac, but it seems to come and go (mostly go)

**Comment by piotrsmajek** [comment]
Same here on Mac

**Comment by oblivion2k** [comment]
Thought I broke it when I tried did a clean boot on Windows to troubleshoot another issue. Wiped my Franz installation for nothing just like OP

**Comment by richardsim7** [comment]
> 
> 
> It's back up for me

Yeah it's back down again, won't be making the mistake of rebooting again 😄

**Comment by seesemichaelj** [comment]
Thanks everyone for confirming this! Looks like we have enough reports to make it seem like this isn't specific to OS or version. If this issue is affecting you, please :+1: the original post instead of commenting "same here". Thanks! (and my inbox thanks you too :smile:)

It's almost midnight in Vienna, so we may be out of service for awhile until @adlk can get a chance to addressing this.

**Comment by seesemichaelj** [comment]
Just as an update from my end: the service has been up for me for several hours

**Comment by seesemichaelj** [comment]
Closing as I haven't had any issues in the last 2 weeks
