### ISSUE TITLE
System tray icon disappears after screen lock

### ISSUE THREAD

**Issue by borospeti** [meetfranz/franz#1834]
**Describe the bug**
5.5.0-beta.4, on Ubuntu 19.10: The Franz icon disappears from the system tray after the screen is locked and unlocked.

**To Reproduce**
1. Go to 'File' -> 'Settings'
2. Turn off 'Show Franz in system tray', than turn it on again.
3. Verify that the Franz icon is in the system tray
4. Lock screen
5. Unlock screen
6. The Franz icon is no longer in the system tray

**Expected behavior**
The Franz icon is expected to stay visible in the system tray after screen lock/unlock or suspend/resume.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 5.5.0-beta.4

**Comment by mhadidg** [comment]
I'm experiencing the same issue;

- OS: Ubuntu 20.04 LTS
- Version 5.5.0-beta.3

**Comment by pacomo** [comment]
Same here with Ubuntu 20.04 LTS and Franz Version 5.5.0-beta4.

**Comment by mhadidg** [comment]
Seems like the issue only affect Ubuntu!

**Comment by jambocurious** [comment]
Just updated from 19.10 to 20.04 POP LTS and icon dissapeared. If you install the flatpak version of Franz it is displayed correctly, otherwise just the invisible box.

**Comment by pacomo** [comment]
I just want to add that i updated to v 5.5.0 (deb package) from beta4 and the issue still stands.

**Comment by rionita** [comment]
reproduces for Franz 5.5.0 on Ubuntu 18.04.4

**Comment by Salvoru** [comment]
Same with Ubuntu 20.04
