### ISSUE TITLE
Franz window disappears when out of focus/minimized, hampering drag & drop operations

### ISSUE THREAD

**Issue by beppe9000** [meetfranz/franz#1840]
This happens when the minimize to tray icon in enabled.

System Windows 10 x64

**Comment by virattendulkar** [comment]
Ya same things happens to me.

**Comment by beppe9000** [comment]
![image](https://user-images.githubusercontent.com/6625123/81714980-f7584e00-9477-11ea-9930-55878fabfe32.png)

Basically when both `1` and `2` are enabled I would expect Ferdi to minimize to notification area without need for `3`. Maybe a new checkbox (`minimize to notification area when closed`) could be added to enable this behaviour?

**Comment by beppe9000** [comment]
sad bot
