### ISSUE TITLE
Skype download

### ISSUE THREAD

**Issue by yanninie** [meetfranz/franz#1844]
Hello,

I have a question from an observation I had. When having Skype session on Franz, the download doesn't work. To download a file (pdf,etc) from a discussion it redirects me to a browser (which mine is Safari) and it downloads instead of the file something else : with the name "original", coming from " https://weu1-api.asm.skype.com/v1/objects/0-weu-d7-712dd4382cb933aa30212409204ba1c3/views/original " . 
Can this be resolved by a user such as me or is this a work in progress ?

Desktop :
 - OS: version 10.14.6
 - Browser: safari version 13.1 
- Franz version 5.3.3 
 bests, 
Yannick

**Comment by BananaAcid** [comment]
Same on OSX 10.15.4 in Franz.
