### ISSUE TITLE
does Franz run on raspberry pi ?

### ISSUE THREAD

**Issue by hary66** [meetfranz/franz#1847]
Hi
Is the Franz App image supposed to be able to run on Raspberry pi Raspbian ?

I understood Appimage are supposed to run on any distribution easily, but is it the case for Raspbian ?

Thanks.

**Comment by srini-pro** [comment]
im afraid that appimages do not work on raspberry pi we need an intel prosesor even then deb does not work maybe you can close this now?

**Comment by hary66** [comment]
Thanks for the response

**Comment by srini-pro** [comment]
your welcome
