### ISSUE TITLE
DeprecationWarning and default value of app.allowRendererProcessReuse

### ISSUE THREAD

**Issue by AlexMuresan** [meetfranz/franz#1849]
**Bug description**
When opening Franz the usual way it crashes after a few seconds of showing the loading screen. If I try to launch it from the terminal it gives the following errors:

`(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397`

`(node:6860) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.`

`(node:6860) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.`

`(node:6860) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.`

`(node:6860) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.`

`[1]    6860 segmentation fault (core dumped)  franz`

**To Reproduce**
Steps to reproduce the behavior from GUI:
1. Click on Franz icon
2. Wait
3. Experience Crash

Steps to reproduce the behavior from Terminal:
1. write 'franz' in terminal
2. See errors

**Expected behavior**
Franz should start and behave normally

**Desktop:**
 - OS: Ubuntu 20.04
 - Installed from deb package provided on the website

**Other mentions**:
Seems like an instance of https://github.com/electron/electron/issues/18397. The link is also referenced in the error but I don't know how to fix this.

**Comment by dpinol** [comment]
I didn't have this issue on a previous ubuntu 20.04, but now I have Linux mint 20 and I always get this crash
