### ISSUE TITLE
Franz wants to export key "<key>" from your keychain.

### ISSUE THREAD

**Issue by HeikoKanzler** [meetfranz/franz#1851]
As of today, my Mac opens a dialog "Fraz wants to export key "<key>" from your keychain.
I am asked to enter the "login" keychain password.

This dialog comes over and over again, I have to quit / force quit franz. or to enter my password, which I am not going to do without any reason.

Any ideas why this is happen and what is this required for?

The console also files tons of messages

default	16:43:51.495948 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.497595 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.499893 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.501842 +0200	Franz	dbBlobVersion() failed for a non-existent database
default	16:43:51.502289 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.503988 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.505520 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.507125 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.509025 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.510891 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.512880 +0200	Franz	dbBlobVersion() failed for a non-existent database
default	16:43:51.513375 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.515387 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.516991 +0200	Franz	CSSM Exception: -2147413737 CSSMERR_DL_DATASTORE_DOESNOT_EXIST
default	16:43:51.519342 +0200	Franz	skipping upgrade for locked keychain

**Comment by haoweicrushu** [comment]
Same here
franz wants export key "<key>" from your keychain

**Comment by HeikoKanzler** [comment]
Looks like Skype is the problem - at least on my machine.

I stopped Franz and opened Skype and was logged out, try to log in, but got logged out again - repeated it a couple of times, checked the logs and found the same entry "CSSMERR_DL_DATASTORE_DOESNOT_EXIST" , but this time from Skype.

Removed Skype from Franz: no dialog, no entries in the logs.
