### ISSUE TITLE
electron 9 support

### ISSUE THREAD

**Issue by yuyichao** [meetfranz/franz#1856]
**Describe the bug**
When running under electron 9, the loading banner does not go away even after the services are loaded.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**

Following the [release note for electron 9](https://www.electronjs.org/releases/stable#release-notes-for-900), the following patch seems to fix the issue.

However, I've never done anything with electron before so I'm not sure if all the changes are correct.

```patch
From d7688fc94ec01e7c7bea7e40482bf3dcb9c39e3c Mon Sep 17 00:00:00 2001
From: Yichao Yu <yyc1992@gmail.com>
Date: Sun, 31 May 2020 00:22:50 -0400
Subject: [PATCH] .

---
 src/containers/settings/RecipesScreen.js | 2 +-
 src/electron/webview-ime-focus.js        | 3 ++-
 src/models/Service.js                    | 3 ++-
 3 files changed, 5 insertions(+), 3 deletions(-)

diff --git a/src/containers/settings/RecipesScreen.js b/src/containers/settings/RecipesScreen.js
index 132820b..d1765ef 100644
--- a/src/containers/settings/RecipesScreen.js
+++ b/src/containers/settings/RecipesScreen.js
@@ -121,7 +121,7 @@ export default @inject('stores', 'actions') @observer class RecipesScreen extend
           recipeFilter={filter}
           recipeDirectory={recipeDirectory}
           openRecipeDirectory={() => {
-            shell.openItem(recipeDirectory);
+            shell.openPath(recipeDirectory);
             gaEvent('Recipe', 'open-recipe-folder', 'Open Folder');
           }}
           openDevDocs={() => {
diff --git a/src/electron/webview-ime-focus.js b/src/electron/webview-ime-focus.js
index 1213b51..2153edb 100644
--- a/src/electron/webview-ime-focus.js
+++ b/src/electron/webview-ime-focus.js
@@ -1,4 +1,5 @@
 const { releaseDocumentFocus } = require('./webview-ime-focus-helpers');
+const { remote } = require('electron');

 function giveWebviewDocumentFocus(element) {
   releaseDocumentFocus();
@@ -9,7 +10,7 @@ function giveWebviewDocumentFocus(element) {
 }

 function elementIsUnfocusedWebview(element) {
-  return element.tagName === 'WEBVIEW' && !element.getWebContents().isFocused();
+  return element.tagName === 'WEBVIEW' && !remote.webContents.fromId(element.getWebContentsId()).isFocused();
 }

 function webviewDidAutofocus(element) {
diff --git a/src/models/Service.js b/src/models/Service.js
index 650787b..24debb3 100644
--- a/src/models/Service.js
+++ b/src/models/Service.js
@@ -3,6 +3,7 @@ import path from 'path';
 import normalizeUrl from 'normalize-url';

 import userAgent from '../helpers/userAgent-helpers';
+const { remote } = require('electron');

 const debug = require('debug')('Franz:Service');

@@ -209,7 +210,7 @@ export default class Service {
   }

   initializeWebViewEvents({ handleIPCMessage, openWindow, stores }) {
-    const webContents = this.webview.getWebContents();
+    const webContents = remote.webContents.fromId(this.webview.getWebContentsId());

     const handleUserAgent = (url, forwardingHack = false) => {
       if (url.startsWith('https://accounts.google.com')) {
--
2.26.2
```

**Comment by Artofaj** [comment]
I can confirm this

**Comment by detierno** [comment]
> I can confirm this

Me too

**Comment by irvelervel** [comment]
Absolutely confirming this. The app is unusable.

**Comment by Artofaj** [comment]
> Absolutely confirming this. The app is unusable.

I wouldn't say unusable. A quick fix is to open the developer tools (ctrl/cmd+ alt + i) and give the element the property `display: none `. That should do the trick as a workaround, of course.

**Comment by yuyichao** [comment]
That workaround was what I used to get a message sent before investigating in the issue. The problem is that the message box appears every time after switching service....

**Comment by irvelervel** [comment]
Exactly. Toggling the display property works until you switch service. Thanks @Artofaj anyway for the feedback.

**Comment by yuyichao** [comment]
As an aside, I assume quite a few ppl here are arch users. I've already commented on AUR about this. The package in [archlinuxcn repo](http://repo.archlinuxcn.org/x86_64/) is built with the patch above. Use it at your own risk though I've been using it for a few days without much problems and it even seems to have fixed https://github.com/meetfranz/franz/issues/1841 for me.....

You can also find the PKGBUILD at [archlinuxcn](https://github.com/archlinuxcn/repo/tree/8a958fedaa8540aee80dad3a8595611d111aea25/archlinuxcn/franz) if you don't want to add the archlinuxcn repo or download the binary package from there...

**Comment by kriation** [comment]
@yuyichao - I just finished testing your patch with 5.5.0-1, and while the UI comes up, keyboard input is not captured.

**Comment by yuyichao** [comment]
I have no idea who/what component is responsible for what so I'm not able to offer much help... It works for me though... Only thing I can suggest would be to check other electron apps, try different windows from franz (e.g. dev tools) and check in cmdline/dev tools if there's any errors etc...

**Comment by Artofaj** [comment]
The issue was solved for me with the last update.

**Comment by yuyichao** [comment]
You mean the last AUR update? There doesn't seems to be a new release here. (in fact there haven' been a new commit here since the issue report yet...)

**Comment by Artofaj** [comment]
Yes, I meant the newest AUR release. I forgot to write that down, sorry.

**Comment by ItachiSan** [comment]
Hey there, I'm the AUR maintainer. :smile: 
I did actually apply @yuyichao patch within the package.
I saw that there are multiple errors within the internal developer console, but I don't have a nice environment to test it and couldn't fix it.
Will probably work on some extra improvements these days but it's in my opinion the good way to go :smile:

**Comment by yuyichao** [comment]
10 is the default now. 13 support would be nice I guess...
