### ISSUE TITLE
Unread badge for WhatsApp in MacOS Catalina missing

### ISSUE THREAD

**Issue by khenjin** [meetfranz/franz#1859]
In the system preferences Franz is allowed to show badge notifications.
In Franz itself under settings, I have set "Show unread messages if notifications are disabled" to true.

For the WhatsApp service, notifications and sound are both enabled.
Yet I only hear a sound when I receive a new message, but no badge within the sidebar of Franz nor a badge at the app icon in my dock.

Franz version is 5.5.0 (5.5.0.1762) running on Mac OS Catalina 10.15.5.

Also, I have disabled and enabled all settings, cleared the cache, deleted the partitions folder, deleted the service and activated it again - yet, nothing changes so badges would be shown.

**Comment by Axel29** [comment]
Same problem here, it seems like I had the same issue on Windows 10.

**Comment by mgilank** [comment]
got this issue in mac and win 10 also

**Comment by duckpuppy** [comment]
I have the exact opposite problem - WhatsApp is now showing one unread message all the time, started today after I got a service update message and reloaded.

**Comment by Axel29** [comment]
Seems that it just got fixed! Both the notification bubble missing and the window not being full-sized.

Thanks! :D

**Comment by leobastiani** [comment]
I had the same problem, but now I see a new one here https://github.com/meetfranz/franz/issues/1861
