### ISSUE TITLE
Slack signs out when quitting Franz

### ISSUE THREAD

**Issue by mleong245** [meetfranz/franz#186]
### Expected Behavior
Slack stays signed in even after quitting and reopening Franz.

### Current Behavior
In Franz 5.0.0-beta.11, when I quit Franz and reopen it, my Slack service signs out every time.

### Screenshots (if appropriate):
n/a

### Possible Solution
Perhaps cookies are getting cleared? Not sure, though my other services stay signed in.

### Steps to Reproduce (for bugs)
1. Enable a Slack instance as a service.
2. Sign in.
3. Quit Franz.
4. Reopen Franz.
5. See that Slack is signed out.

### Context
In the last version of Franz 4, my Slack service would stay signed in even after quitting Franz, such that on subsequent reopens (even after a restart of the entire machine), Slack would still be signed in, making for a really simple and convenient experience.

My Slack instance is auth'd via SSO, if that matters.

### Your Environment
* Franz Version used: 5.0.0-beta.11
* Operating System and version: OS X El Capitan (10.11.6)

**Comment by mleong245** [comment]
This issue can be closed. I found out that a policy for our Slack instance recently changed to automatically log out users when they quit the application.

**Comment by adlk** [comment]
thanks for the update!
