### ISSUE TITLE
Telegram Secret Chats?

### ISSUE THREAD

**Issue by dm17** [meetfranz/franz#1865]
I'm trying to find a Linux client that supports Telegrams' secret chats (that have been available on OSX desktop client for many years). Does Franz support this?

**Comment by maxap** [comment]
Franz only show the web version of telegram, if I'm right the web version does not support secret chats, so no, franz does not support secret telegram chats

**Comment by dm17** [comment]
Right, so zero Linux support for secret chats in various clients so far in my research.
Thanks.

**Comment by dm17** [comment]
I'm going to close this... Even Telegram with all of its resources won't support secret chats after non-stop bragging online about their security.
