### ISSUE TITLE
Google blocks Google Voice log-in through Franz

### ISSUE THREAD

**Issue by ckrf** [meetfranz/franz#1866]
**Describe the bug**
When adding a Google Voice service, the Google log-in is blocked with the following error: 
> **Couldn't sign you in**
> This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-GB)
> 
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**To Reproduce**
1. Add a Google Voice service
2. Go to the Google Voice service
3. Input your Google Account username
4. Encounter the error

**Expected behavior**
Instead of the error, I expected to be asked to input my password. I then expected to see the same Google Voice interface in Franz that I find by going to voice.google.com in Chrome. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Franz
 - Version: 5.5.0

**Additional context**
I had previously had a Google Voice service installed. In recent weeks, it got forever stuck on the post-login loading screen without showing my messages or voicemail. Before encountering this bug, I had removed the Google Voice service and re-entered it.

**Comment by jeremymeyers** [comment]
#1720
