### ISSUE TITLE
Whatsapp not working

### ISSUE THREAD

**Issue by dzigner** [meetfranz/franz#1876]
Hello
Whatsapp is not working in Franz since morning today, July 14th, 2020, PST. I tried on both Windows and Macbook Pro. The UPC code does not get recognized on my phone.
Have updated Franz on both - v 5.5.0
Windows 10
Macbook OS Catalina 10.15.5

Thanks

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by macbosse** [comment]
Same with me. Franz does not load / recognize Whatsapp Session anymore.
First loads long …
<img width="1184" alt="Bildschirmfoto 2020-07-14 um 22 56 28" src="https://user-images.githubusercontent.com/249058/87475562-50359580-c625-11ea-8e0b-11fd614b30d1.png">

then offers to reconnect an existing session  …
<img width="1185" alt="Bildschirmfoto 2020-07-14 um 22 56 40" src="https://user-images.githubusercontent.com/249058/87475566-5166c280-c625-11ea-8351-1023e9aa3234.png">

**Comment by TiliSleepStealer** [comment]
Same here :/
