### ISSUE TITLE
I cant zoom out in franz on any services

### ISSUE THREAD

**Issue by robertg11** [meetfranz/franz#189]
I cant zoom out in franz on any services

### Expected Behavior
Zoom out/in in FRANZ

### Current Behavior

I cant zoom out in franz on any services
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Please provide as much information as possible via the issue template as we require this information to reproduce your problem.
