### ISSUE TITLE
Media keys support

### ISSUE THREAD

**Issue by ldrrp** [meetfranz/franz#19]
### Feature Description
Media keys support for recipes like google music or other music players

### Motivation and Context
https://github.com/meetfranz/plugins/issues/3

Example electron app that has it working https://github.com/headsetapp/headset-electron

**Comment by adlk** [comment]
How would it work if you have multiple services that make use of the media keys?

**Comment by ldrrp** [comment]
currently the plugin i use for chrome just does it for all of the services haha, but there was a better but now outdated plugin that had a settings for setting priority levels of each service.

**Comment by adlk** [comment]
I'm closing this. After a longer review, this is not a priority feature for Franz.
