### ISSUE TITLE
Add option to display disabled services in tab bar

### ISSUE THREAD

**Issue by gideville** [meetfranz/franz#192]
### Expected Behavior
When I clic on "Disable Service" I don't want to Delete it from my sidebar, just want to "logout".
Could we keep the logos of the service that are disabled ? Maybe add a grayscale filter to them, I don't know but that would allow a simple right clic to enable them back.

### Current Behavior
When I clic on Disable Service, it disappears from my side bar.

**Comment by edwardpakpahan** [comment]
I can't agree more of this. The previous beta followed precisely like this behaviour which is a very HANDY thing to have. Please include this onto this beta as well. I tried Beta 5 at work but not gonna update to Beta 5 at home's mac if things not changed.

**Comment by adlk** [comment]
Fixed in #248
