### ISSUE TITLE
WhatsApp works with Chrome 60+

### ISSUE THREAD

**Issue by grebsai** [meetfranz/franz#1925]
**Describe the bug**
I'm using WhatsApp in Franz and I get the error "WhatsApp works with Chrome 60+". I have already tried the following steps: https://meetfranz.com/de/support#whatsapp-chrome-update

**To Reproduce**
1. Add WhatsApp Service

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome
 - Version 86.0.4240.198

**Comment by iRaySis** [comment]
Just update Franz to version 5.6.1, worked for me

**Comment by grebsai** [comment]
oh damn, thanks man, that helped. I was still on version 5.0.0-beta18

**Comment by shooby83** [comment]
Hi, i'm on 5.7.0 and still get the Chrome 60+ error message.

**Comment by kr4bat** [comment]
Upgrading from 5.4.0 to 5.7.0 *plus* ~/.config/Franz/recipes$ rm -rf whatsapp/
Did finally work out for me.
Maybe it might be a Try to make the Browser String configurable?

**Comment by kr4bat** [comment]
Remaining Problem is a Notification which can not be found or confirmed or deleted - appears again and again.

![20211210-135603](https://user-images.githubusercontent.com/4640728/145577861-31f2b181-9b4d-412c-a32e-3af17c0620d9.png)
