### ISSUE TITLE
Facebook Messenger Showing All of Facebook

### ISSUE THREAD

**Issue by MooseBran** [meetfranz/franz#1937]
**Expected behavior**
Messenger Service shows chats only.

**Actual Behaviour**
Facebook Messenger Service is showing Facebook's actual dashboard and other features such as marketplace, notifications, etc.

**Desktop (please complete the following information):**
Windows 10
Franz Version 5.6.0-beta.1

**Comment by sb18281** [comment]
Can confirm the same is happening to me. Messenger.com in my normal browser works fine though.

**Desktop**:
MacOS 10.15
Franz Version 5.6.0-beta.1

**Comment by MxRay** [comment]
Can confirm same behaviour. Reloading the service sometimes fixes the issue but on the Franz start-up it defaults to the whole facebook interface.

**Desktop:**
Windows 10
Franz Version 5.6.0-beta.1

**Comment by MxRay** [comment]
Ok, found a solution but I haven't tested it yet properly. Change all occurrences of "www.facebook.com/messages" in all files here `<Franz install folder>\recipes\messenger` to "www.messenger.com"

**Comment by TiliSleepStealer** [comment]
As well as OP's issue, notifications are also broken for Messenger.

**Comment by garethjmsaunders** [comment]
> As well as OP's issue, notifications are also broken for Messenger.

Glad that it's not just me. Notifications have been broken for the last couple of days for me.

**Comment by MooseBran** [comment]
> > As well as OP's issue, notifications are also broken for Messenger.
> 
> Glad that it's not just me. Notifications have been broken for the last couple of days for me.

In my case, re-adding the service fixed notifications. 

> Ok, found a solution but I haven't tested it yet properly. Change all occurrences of "www.facebook.com/messages" in all files here `<Franz install folder>\recipes\messenger` to "www.messenger.com" **especially in package.json**

This didn't work for my issue at all, it gave me a File not found error. 
It feels like with every other update FB Messenger integration gets some new issues.

**Comment by garethjmsaunders** [comment]
Changing all occurrences of "www.facebook.com/messages" to "www.messenger.com" resolved the issue of showing all of Facebook rather than just Messenger, but it hasn't resolved the issue of notifications not being shown on the Messenger badge in the left-hand sidebar.

**Comment by pwojewodzic** [comment]
+1

Changing to `www.messenger.com` do not working with dark theme 😄

**Comment by garethjmsaunders** [comment]
> Changing all occurrences of "www.facebook.com/messages" to "www.messenger.com" resolved the issue of showing all of Facebook rather than just Messenger, but it hasn't resolved the issue of notifications not being shown on the Messenger badge in the left-hand sidebar.

A little further exploration I got it to work again.

1. I changed one occurrence of "www.facebook.com/messages" to "www.messenger.com" in webview.js (line 9).
2. I changed one occurrence of "www.facebook.com/messages" to "www.messenger.com" in package.json (line 10).
3. I then removed the Facebook Messenger service from my Franz (Settings > Your services > Delete service).
4. Restarted Franz.
5. Added Facebook Messenger service back, and now message notifications are working again.

**Comment by jprieur-mw** [comment]
> > Changing all occurrences of "www.facebook.com/messages" to "www.messenger.com" resolved the issue of showing all of Facebook rather than just Messenger, but it hasn't resolved the issue of notifications not being shown on the Messenger badge in the left-hand sidebar.
> 
> A little further exploration I got it to work again.
> 
> 1. I changed one occurrence of "www.facebook.com/messages" to "www.messenger.com" in webview.js (line 9).
> 2. I changed one occurrence of "www.facebook.com/messages" to "www.messenger.com" in package.json (line 10).
> 3. I then removed the Facebook Messenger service from my Franz (Settings > Your services > Delete service).
> 4. Restarted Franz.
> 5. Added Facebook Messenger service back, and now message notifications are working again.

Still not getting badge notifications / toast popups after following all of this, but I no longer have all of Facebook showing, so that's good.

**Comment by garethjmsaunders** [comment]
Hmm... disappointingly, it only worked for me once. Then the notifications stopped once more. I then removed the service, rebooted, added the service again but when I try to log in now I get an error: "Sorry, something went wrong."

**Comment by jprieur-mw** [comment]
Wondering if I should start a new issue, as the issue this originally covered is fixed, and this is now a separate issue?

**Comment by MooseBran** [comment]
> Wondering if I should start a new issue, as the issue this originally covered is fixed, and this is now a separate issue?

I think that's a good idea. I'm going to go ahead and close this issue. 
Thanks for the help everyone, things seem to be running smoothly on my end as well.
