### ISSUE TITLE
Default Browser problem - OS X Sierra

### ISSUE THREAD

**Issue by noway1987** [meetfranz/franz#194]
### Expected Behavior
Open links in my default browser set in "Preferences > General"

### Current Behavior
Opens links always in Safari

### Your Environment
MacBook Air (13-inch, 2017)
macOS Sierra (10.12.6 (16G29))
Franz Version 5.0.0-beta.11 (5.0.0-beta.11.135)

**Comment by BrianGilbert** [comment]
if you right click on links and open they will open in your default browser.

**Comment by julianYaman** [comment]
Same issue on Windows 10 too.

**Comment by bcotton** [comment]
Don't see that option in Preferences. 
5.0.0-beta.14

**Comment by jacoblo** [comment]
Same here. No option and all open in Franz rather than my browser which I would have preferred.
