### ISSUE TITLE
Sign in with Github?

### ISSUE THREAD

**Issue by Nifled** [meetfranz/franz#195]
### Context
I've been using Franz for a while now and have an account through Github OAuth. Is that gone now? I really hope it's not.

I'm on Windows and Mac

Thanks!

**Comment by adlk** [comment]
The old version had no account and no option to sign in with Github. I'm really curious about the details here.

**Comment by Nifled** [comment]
This is embarrassing. The issue was regarding a different app apparently.

Sorry! And thanks.
