### ISSUE TITLE
[High Priority] SSL Certificate Of cdn.franzinfra.com Expired

### ISSUE THREAD

**Issue by promarcel** [meetfranz/franz#1951]
**Describe the bug**
Hey guys, the SSL certificate of cdn.franzinfra.com is expired. Sorry for the ping, @adlk but its important.

For example loading of custom service images is not working: `Failed to load resource: net::ERR_CERT_DATE_INVALID` appeared inside Franz developer console logs.

Subject | *.franzinfra.com
-- | --
Common names | *.franzinfra.com
Alternative names | *.franzinfra.com
Serial Number | 067865309c6198df5260be0087bd5865
Valid from | Fri, 29 Nov 2019 00:00:00 UTC
**Valid until** | **Tue, 29 Dec 2020 12:00:00 UTC (expired 8 hours and 59 minutes ago)   EXPIRED**
Key | RSA 2048 bits (e 65537)

**To Reproduce**
Access any content hosted at cdn.franzinfra.com, maybe other domains affected as well due to I cannot save any changes at services.

**Expected behavior**
Everything works and SSL certificate is valid.

**Comment by benguaraldi** [comment]
Note that if you set your computer clock back to when the certificate was working, you can load icons, and they stay loaded as long as you don't quit the app or reboot the machine.

A temporary solution, to be sure, but at least it works...

**Comment by promarcel** [comment]
Issue has been resolved and the certificate is up to date again:



Subject | *.franzinfra.com
----|----
Common names | *.franzinfra.com
Alternative names | *.franzinfra.com
Serial Number | 0fae1281309e836cc0ec75cdf3a6a84d
Valid from | Sun, 03 Jan 2021 00:00:00 UTC
Valid until | Tue, 01 Feb 2022 23:59:59 UTC (expires in 1 year)
Key | RSA 2048 bits (e 65537)

**Comment by benguaraldi** [comment]
Thanks, @promarcel!
