### ISSUE TITLE
Custom icons not showing on side bar

### ISSUE THREAD

**Issue by faunaman** [meetfranz/franz#1955]
**Describe the bug**
My custom icons disappeared form the side bar. Adding them again has no effect. The app was open and fully working and they just disappeared, one of the is still there though, but 7 other are missing. Tried to reinstall Franz again but it didn't work. I had Franz 5.5 and upgraded to 5.6.1 with no success.

**Expected behavior**
I expect the app to show my custom icons.

**Screenshots**
<img width="86" alt="Captura de pantalla 2021-01-01 a las 1 ene 202120 20 56" src="https://user-images.githubusercontent.com/76849791/103445090-4570ca80-4c70-11eb-87d9-5db85d3a19d6.png">
<img width="665" alt="Captura de pantalla 2021-01-01 a las 1 ene 202120 23 02" src="https://user-images.githubusercontent.com/76849791/103445095-4bff4200-4c70-11eb-83d5-be8fc99f343a.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10. 5. 7

**Additional context**

**Comment by ziegenberg** [comment]
This bug also appears on Windows 10 Version 20H2.

**Comment by ziegenberg** [comment]
This seems to be a duplicate of #1926.

**Comment by jlcolburn27** [comment]
I am currently having the same issue. It has been this way for me for the past 2 weeks. I have tried uninstalling and it reinstalling and nothing.

**Comment by benguaraldi** [comment]
Caused by #1951, at least for me.  Temporary solution is setting the clock back to mid-December while loading Franz.

**Comment by b5s** [comment]
Same .. no icon is displayed in Fedora 33 GNOME dock. Cannot add Franz to Favorites, doesn't show up in 'Show Applications' .. these used to work before.

**Comment by faunaman** [comment]
Working fine today for me, I can add them without a problem. Must have been some problem on their side. Thanks to all!

**Comment by ziegenberg** [comment]
Was fixed by resolving #1951.
