### ISSUE TITLE
Enable silent installer

### ISSUE THREAD

**Issue by bc3tech** [meetfranz/franz#199]
The current installer EXE doesn't have any (documented) way to do a silent install. 

Please provide guidance and/or the ability the do so. Thanks!

**Comment by adlk** [comment]
@bc3tech can you please go a little further into detail about the silent installer? 
(Please keep in mind that I'm coming from a non-windows)

**Comment by bc3tech** [comment]
sure!

Usually when a piece of software has an installer, it provides switches to the installer that can perform addtional/different functionality. Lots of times these include outputting verbose messages, logging install messages to a specific file, or, as I'm requesting here, installing the application "silently" aka "no UI"

In many installers, this can be done by specifying `/s` or `/silent` to the installer exe or msi. eg:

```
franz-setup.exe /s
```
upon which Franz would install itself in to the system without popping any UI to the end user whatsoever.

Mostly this type of functionality is used when scripting many installations as part of, say, an OOBE.

Hope that helps!

**Comment by adlk** [comment]
"Learn something new everyday" 😀 

I did a quick test with the latest build (RC for beta 12) and `/S` is now working as we don't require administrator rights for installing the app any longer.

The Franz installer is made with NSIS. Find all the infos/docs [here](http://nsis.sourceforge.net/Docs/Chapter4.html#silent).

**Comment by bc3tech** [comment]
awesome news, thanks!!
