### ISSUE TITLE
Make statusbar icon optional

### ISSUE THREAD

**Issue by tommyninja** [meetfranz/franz#2]
### Expected Behavior

I would like to disable the statusbar icon to lower the distraction level.
### Current Behavior

Franz adds the statusbar icon automatically and show notification badges whenever they come up. With the option added it could also be possible to do a right click on that icon to disable it right on the spot – that's my first attempt to disable something distracting. 
### Possible Solution

Add a checkbox to the settings screen or the contextual menu on right click, to disable the feature.

### Context

The red badge on top of the screen distracts massively while I am working. I have learned to ignore the badge in dock, but I can't resist to the statusbar.
### Your Environment

* Franz Version used: Version 5.0.0-beta.10 (5.0.0-beta.10.7)
* Operating System and version: macOS Version 10.12.6 (16G29)

**Comment by SergioSGil** [comment]
-1 

On Dark MacOS option icon is not working properly:

Icon:
https://imgur.com/a/Pu1F9

If i do click on the icon:
https://imgur.com/a/pTElP
