### ISSUE TITLE
Slack: Unread messages in muted channels show a notification

### ISSUE THREAD

**Issue by jvdmeij** [meetfranz/franz#20]
The red notification icon is being shown for Slack services when a new message is posted in channels that are muted.

### Expected Behavior
I would expect a muted channel to not trigger a notification.

### Current Behavior
The red notification icon is being shown.

### Steps to Reproduce (for bugs)
Add Slack as a channel 
Mute a channel
Ask someone to post something in that channel
Notification badge is shown in the service bar
 a solution that is most useful in the real world -->

### Your Environment
* Franz Version used: Version 5.0.0-beta.10 (5.0.0-beta.10.7)
* Operating System and version: Mac OSX 10.13

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
https://github.com/meetfranz/recipe-slack

Reference to new issue: https://github.com/meetfranz/recipe-slack/issues/1

**Comment by patrickplaggenborg** [comment]
Same problem here. I'm trying to get rid of those red Unread count badges for channels. It's like muting a channel displays a red Mention badge for any unread messages in that channel.

Not as expected.

How to only show unread count badge when actually mentioned? (respecting my default/channel notification settings in Preferences)
