### ISSUE TITLE
Franz 5 Beta 11 working erratically on Ubuntu 16.04.3 from build 249 onwards

### ISSUE THREAD

**Issue by diegobersanetti** [meetfranz/franz#200]
### Expected Behavior

Franz is expected to open and work

### Current Behavior

Builds 249, 251, 252, 253, 254, : Franz gets stuck immediately in the initial blue screen
Build 250:  works apparently fine (not tested, I'm rapidly looking at all the builds to help pinpoint the issue)
Builds 258, 260: the following error ("missing package.json") is shown

Last working and tested build is 246, which is working quite well, with several services (standard and dev) enabled.

Launching Franz from command line does not show any output.

### Screenshots (if appropriate):
![screenshot from 2017-11-02 18-49-05](https://user-images.githubusercontent.com/317627/32341957-49987e38-bfff-11e7-95db-0539715068f4.png)

### Steps to Reproduce (for bugs)

1. Just opening an affected Franz build shows the issue
2.
3.
4.

### Your Environment

* Franz Version used: 5.0.0 beta 11, builds from 246 up to 260
* Operating System and version: Ubuntu Linux 16.04.3 (kernel 4.10.0-38-generic, Unity DE with Intel Haswell Graphics)

**Comment by adlk** [comment]
There are quite a few dev builds in there right now as I need them for testing all sorts of stuff (and unfortunately there is no `[ci skip travis]`) 
The only reliable linux build right now is build 138 http://franz-travis.s3-website.eu-central-1.amazonaws.com/?prefix=138/

**Comment by diegobersanetti** [comment]
Ok, I understand, I just wanted to take a peek in the latest development. :-)

By the way, if you need some testing for specific builds on Ubuntu, feel free to ask!

**Comment by adlk** [comment]
Thanks for your offer. There is enough to test :)
To have the shortest communication ways possible, please join our [Community Slack ](http://slack.franz.im) in #development
