### ISSUE TITLE
plz add Reddit

### ISSUE THREAD

**Issue by btcnadzor** [meetfranz/franz#201]
could not add 3 additions very important to me
1) Reddit
2) the overall design make like TweetDeck with columns from my sheets
ideally so that you can put a tweet in one sheet of Twitter + a certain chat from the channel is slack + channel reddita
3)telegram user filter. i want read only admins without garbage

**Comment by alecive** [comment]
@adlk trying to help here :)

@btcnadzor for what concerns Reddit:  this repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out [the guide](https://github.com/meetfranz/plugins) to create your own service integration.

For the other points, please be more clear: provide example, describe your issue better, eventually provide screenshots :sunglasses:
