### ISSUE TITLE
Add download link for OS X on Readme.md

### ISSUE THREAD

**Issue by pgensler** [meetfranz/franz#202]
It would be really helpfull to have a download link in the Readme.md to download Franz for Mac, as some users may not know how to install via brew:
https://meetfranz.com/#download

**Comment by adlk** [comment]
Wait, what? Why do users have to install Franz via brew?

**Comment by pgensler** [comment]
Per the readme.md.....My point exactly:
![2017-11-02_16-57-26](https://user-images.githubusercontent.com/7308115/32352381-04e3139e-bfef-11e7-959c-c82c8bb86ad5.jpg)

**Comment by adlk** [comment]
Well you are right about adding a download link to the readme. This section you are pointing to however just applies to "Development".
