### ISSUE TITLE
Telegram released new Web Version (actually two)

### ISSUE THREAD

**Issue by yuzhakovvv** [meetfranz/franz#2023]
**Is your feature request related to a problem? Please describe.**
Telegram [released](https://telegram.org/blog/payments-2-0-scheduled-voice-chats#new-web-versions) two new Web Versions:
- https://webk.telegram.org/
- https://webz.telegram.org/

**Describe the solution you'd like**
Create [receipts](https://meetfranz.com/de/developer) for new Telegram Web Versions.

**Describe alternatives you've considered**
None.

**Additional context**
Versions are really similar except some features. Telegram team doesn't explain why they released two almost identical Versions. I assume they will merge them or deprecate one of them eventually and move to main sub domain https://web.telegram.org/ . Feature list:
- https://bugs.telegram.org/c/4003 - WebK
- https://bugs.telegram.org/c/4004 - WebZ

**Comment by cpazaras** [comment]
Allegedly Telegram said the reason for releasing two versions was because they “believe in internal competition”.

**Comment by morgej** [comment]
Bump....the Telegram icon notifications badge is not displaying unread messages for me

**Comment by morgej** [comment]
@yuzhakovvv does closing this ticket mean that this is fixed?

**Comment by yuzhakovvv** [comment]
I've used receipt proposed here. Works for me
https://github.com/meetfranz/recipe-telegram/issues/20

**Comment by yuzhakovvv** [comment]
Also according to this ticket Franz version 5.7.0 has _Telegram K_ by default.
https://github.com/meetfranz/franz/issues/2043

**Comment by jasmines** [comment]
I'm stuck with issues with this. I've filed bugs but no one answers. No new versions of Franz have been released since 2021-06-14 (5.7.0).
It seems the project has been abandoned to itself (or to premium users?).

Anyway, 

K client is selected by default, and Telegram starts with that.
K version is affected by #2038, for the same reason of #1993 and #1995

When switching to OLD version client, #2038 is solved (but #2026 occurrs).

When closing Franz, it doesn't remember the client version and K client is selected again.

**Comment by yuzhakovvv** [comment]
@jasmines I still use the receipt that I mentioned above. Works perfect for me

**Comment by jasmines** [comment]
@yuzhakovvv I can't add the recipe, I tried creating a new folder in ~/.config/Franz/recipes/ , in ~/.config/Franz/recipes/dev/ no luck
I wouldn't like to replace official recipe but moreover, I'd like the developers give life signs.

**Comment by yuzhakovvv** [comment]
@jasmines I use macOS, so have another folder. But I've successfully added a receipt there several months ago. As far as I understand, you don't need to replace original receipt. You can use both in the same time.
```
ui (master) $ ls ~/Library/Application\ Support/Franz/recipes/dev
Franz-Telegram2-Recipe-master
```
