### ISSUE TITLE
Where is WeChat? that gone for new version.

### ISSUE THREAD

**Issue by matthewlgm** [meetfranz/franz#203]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
