### ISSUE TITLE
Can't login to Telegram by any means provided

### ISSUE THREAD

**Issue by camslice** [meetfranz/franz#2039]
I can no longer login to Telegram by QR Code or Phone Number.  I was automatically logged out for some reason, then I was presented with 2 options to log back in: by QR Code or by Phone Number.  Neither option works.

**Steps to reproduce the behavior:**
1. Log out (or get logged out automatically) of Telegram
2. Try to login by QR Code by scanning it from the Andriod app, nothing happens
3. Try to login by Phone Number by clicking the 'LOGIN IN BY PHONE NUMBER' button, nothing happens

**Expected behavior**
I expect that at least one method of logging in should work.

**System info**
 - macOS version 10.15.7 (Catalina)
 - Franz version 5.7.0 (5.7.0.1852)
 - Android version 11 (5 June 2021) — QR Code scanning

**Comment by holdinghausen** [comment]
same here - I got logged out, no QR Code visible (just a rotating circle), nothing happens when I click on "log in by phone number".

**My system info**

- Windows10 20H2
- Franz version 5.6.1

**Comment by camslice** [comment]
Seems to be working again now
