### ISSUE TITLE
Add the possibility to enable/disable "spell check" on macOS

### ISSUE THREAD

**Issue by magobaol** [meetfranz/franz#204]
### Feature Description
Add "Spelling and grammar" menu item inside the Edit Menu, to have the ability to enable/disable the "Check spelling while typing"

### Motivation and Context
The annoying spell check in macOS has to be disabled on a per application basis.
Since Franz does not provide the described menu item, it is not possible to disable the feature in Franz.

**Comment by wickeddd** [comment]
yeah please add this feature, its sooooo annoying to see every fucking word underlined
thanks :)

**Comment by adlk** [comment]
Added in #276

**Comment by iandric** [comment]
I have an issue that I constantly need to enable/disable spell checking to get it to stop highlighting every word. Works fine until I switch to another application and use it for some time. I don't know when does it re-enable spell checking, maybe it's mac os acting up?
