### ISSUE TITLE
MacOS installer does not work on ARM

### ISSUE THREAD

**Issue by APz** [meetfranz/franz#2042]
**Describe the bug**
The DMG based installer does not work on ARM in 5.7.0. It does however work on Intel macs.

**To Reproduce**
1. Download 5.7.0 DMG image
2. Mount the image, drag Franz to Applications
3. The Finder window closes, nothing else happens.

**Desktop (please complete the following information):**
 - OS: MacOS 11.4

**Additional context**
DMG file appears to be valid and can be used on Intel Macs.

**Comment by BrianGilbert** [comment]
I was unable to reproduce this issue, downloaded and installed and runs on my M1 Mac Mini.

I would still like to see an M1 build please!

**Comment by KlyX84** [comment]
I could not reproduce this issue as well. Worked fine so far.
Still +1 for a native M1 Build. Franz is so slow on M1s...

**Comment by APz** [comment]
Curious. This is a fresh install on M1 Mini. The installer appears to crash the Finder window. Previous Franz versions did install without issue.

I'd say chalk it up as a MacOS bug and close this.
