### ISSUE TITLE
Franz crashes due to CEF issues

### ISSUE THREAD

**Issue by Witko** [meetfranz/franz#206]
### Current Behavior
Franz crashes on startup. This is due to CEF(i assume) audio issue.
The message is:
```
[8674:1103/151955.148222:FATAL:pulse_output.cc(136)] Check failed: bytes_to_fill == static_cast<size_t>(params_.GetBytesPerBuffer()) (65472 vs. 65536)
```

### Possible Solution
This can be possibly solved by setting audio buffer size explicitly(works for chromium):
https://bbs.archlinux.org/viewtopic.php?id=225820

### Steps to Reproduce (for bugs)

1. Start franz
2. Franz window is shown
3. Franz loads the services
4. Franz crashes with the message above

### Context
This renders franz unusable.
You can also see the same issue for steam client: 
https://github.com/ValveSoftware/steam-for-linux/issues/4989#issuecomment-303105934

### Your Environment

* Franz Version used: 5.0.0_beta.11-1
* Operating System and version: Archlinux (kernel 4.13.10-1)

**Comment by haraldox** [comment]
@Witko Franz uses Electron, not CEF. Do you still experience the issue in 5.0.0-beta.15?
