### ISSUE TITLE
"WhatsApp has failed to load." ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by bnjroo** [meetfranz/franz#2082]
**Describe the bug**
Suddenly WhatsApp service went non-functional, Oh no! screen with error message: "WhatsApp has failed to load." ERR_NAME_NOT_RESOLVED. (Android Messages loads fine.)

Verified phone and laptop internet connection, NPF.
Reloaded Franz, NG.
Restarted WhatsApp app, NG.
Restarted phone, NG.
Restarted Windows, NG.
Updated Franz, current version 5.7.0, NG.
Deleted %AppData%\Franz\Cache, NG.

**To Reproduce**
1. Start Franz
2. See error

**Expected behavior**
WhatsApp service loads.

**Screenshots**
![SS 1633364105](https://user-images.githubusercontent.com/28360867/135887005-ed896e96-b6fb-4708-bd09-9a902c6f1079.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 94.0.4606.71

**Smartphone (please complete the following information):**
 - Device: LG ThinQ G7
 - OS: Android 9
 - Browser: Chrome
 - Version: 94.0.4606.61

**Additional context**

**Comment by marcolopes** [comment]
Same problem here.
Same problem with **Facebook MESSENGER** service!
(other services, like Skype, Slack, Android Messages, etc, are working fine)

Any worarounds?

**Comment by bnjroo** [comment]
Apologies, this is a worldwide Facebook/Instagram/WhatsApp crash, nothing to do with Franz.
