### ISSUE TITLE
Can't see message content in Facebook Messenger (Mac)

### ISSUE THREAD

**Issue by nickmodernized** [meetfranz/franz#2096]
Similar to the "Teams" issue that popped up that another user was experiencing where a workaround was posted, I can't actually see the conversation in Facebook Messenger.

I've attached a screenshot...this will unfortunately be a dealbreaker for Franz with me as a paid customer for years, as we have a marketing group that I'm a part of that has to use Messenger to coordinate.

Please help - I can edit the "webview.js" file(s) if I need to, but I'm not sure how to debug to the right place...everything else was working fine until probably about a week or so ago, and if I open Facebook Messenger in Chrome or the app on my Android phone, I can see conversations just fine..

TIA!

### Expected Behavior
Should be able to see the conversation history

### Current Behavior
Not able to see conversation history.

### Screenshots
<img width="954" alt="Screen Shot 2021-11-04 at 11 20 37 AM" src="https://user-images.githubusercontent.com/10522648/140388816-b9f78407-83bf-46a3-ae62-031cf9e507fc.png">

### Your Environment

* Franz Version used: 5.3.3 (latest)
* Operating System and version: MacOS Big Sur 11.6

**Comment by TheNCR** [comment]
Same issue in Windows 10


![Screenshot 2021-11-04 191902](https://user-images.githubusercontent.com/40604941/140442578-d03c228f-cbd3-4fd3-aceb-02ac98162374.png)

**Your Environment**

    Franz Version used: 5.3.3 (latest)
    Operating System and version: Windows 10 v21H1 (OS build 19043.1288)

**Comment by ernestkck** [comment]
Updating to the newest version (5.7.0) fixed the issue for me.
You need to download the installer from https://meetfranz.com/
Apparently the update function in version 5.3.3 has been broken for 2 years and I have only realised now.

**Comment by DroWnThePoor** [comment]
@ernestkck 
And people like you are the reason EVERY piece of software should have a Github/Gitlab or if proprietary at bare minimum an issue/bug tracker.

I actually miss the days when Ubuntu would display Whoopsie/Apport with the link to the issue. I'd usually check the comments and find fixes to whatever was wrong that way. Helped a lot when I was brand new to Linux, and it was actually a major selling point for me.
