### ISSUE TITLE
My Franz is not starting

### ISSUE THREAD

**Issue by awilliansd** [meetfranz/franz#2136]
Hi,

after I put the credentials, my franz app doesn't start, freezing in loading screen.
I formatted my Windows 10, so it's a fresh installation.

![image](https://user-images.githubusercontent.com/4139802/155856199-4cb0e55f-79c8-48c8-b257-7738d24309d2.png)

Best regards

**Comment by wadid** [comment]
Same issue here with a windows 11 fresh installation.

**Comment by daniamann** [comment]
same here, fresh Windows 10 installation. Someone got a solution?

**Comment by xcom-magento** [comment]
@awilliansd @wadid @daniamann https://getferdi.com/

**Comment by GiovanniPerini** [comment]
Same here, fresh install Windows 11. If I remove %appdata%\Franz and then create a new account, Franz will start. But then I can't add any services. Screen keeps searching for available services.

**Comment by awilliansd** [comment]
> 

thank you

**Comment by rickelsum** [comment]
Same issue here, I have paid for premium features how to get support or my money back?

**Comment by rickelsum** [comment]
Actually do not even bother. Paying for this program is a scam. There is no support and the developers having clearly gone awol with this many open tickets (currently 375 compared to Ferdi's 3 issues currently open.) After 3 years of paying for premium have cancelled my subscription. For all reading this avoid this program and project and get Ferdi. 

I regret not knowing about Ferdi sooner.

**Comment by GiovanniPerini** [comment]
Same for me. I also canceld my paid subscription to switch to Ferdi. Its free, has more functionality and better support.

**Comment by auanasgheps** [comment]
Same issue on a fresh W11 installation. Thanks for reporting Ferdi, I switched immediatelly!
