### ISSUE TITLE
Can't rise from Systray

### ISSUE THREAD

**Issue by adomas187** [meetfranz/franz#214]
### Expected Behavior
It should rise from system tray, but it just stays there. Have to restart app, to use it again.

### Current Behavior
Stuck in system tray. Terminal output is like this:
`[adomas@genesis ~]$ franz 
TypeError: Cannot read property 'mainWindow' of undefined
    at click (/usr/share/franz/resources/app.asar/lib/Tray.js:36:13)
    at MenuItem.click (/usr/share/franz/resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/usr/share/franz/resources/electron.asar/browser/api/menu.js:121:15)
`

### Screenshots (if appropriate):
I see just tray icon, no screenshot is necessary.

### Possible Solution
Not sure what's wrong...

### Steps to Reproduce (for bugs)
1. Launch
2. Minimize to system tray
3. Try to rise from system tray
4. Stuck

### Context
Trying to use app.

### Your Environment
Built from AUR:
https://aur.archlinux.org/packages/franz/
* Franz Version used: 5.0.0-beta.11
* Operating System and version: Arch Linux x86_64 latest

**Comment by adlk** [comment]
Duplicate #106 – will be fixed in beta 12 which is coming in the next couple of days.
