### ISSUE TITLE
Slack is no longer connecting to audio calls

### ISSUE THREAD

**Issue by acrodrig** [meetfranz/franz#215]
It use to be the case that I could receive and make Slack calls in the client. This is no longer the case. The screen just says "Connecting..." indefinitely. I can however use Slack's client to do this, so I presume it is a Franz issue.

Thanks for solving.

**Comment by Cahl-Dee** [comment]
This has been an issue for weeks. Switched back to Slack Desktop client till this is fixed :-(

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins

**Comment by acrodrig** [comment]
@BrianGilbert, consider it my duty to report it. If you think it should go somewhere else, please file it somewhere else yourself. Good bye Franz.
