### ISSUE TITLE
Layout glitches on OSX (5.0.0-beta)

### ISSUE THREAD

**Issue by randomdoe** [meetfranz/franz#216]
### Expected Behavior
Draw all service panes as you would expect.

### Current Behavior
Sometimes when I change windows or click somewhere within the apps I get weird layout glitches like in the screenshots attached. Reloading Franz resets everything to good until it happens again.

### Screenshots (if appropriate):

Both screenshot are from the same window (WhatsApp). Personal information is blacked out, everything else is as it looked like.

![franz_screenshot1-retouched](https://user-images.githubusercontent.com/33398971/32417249-cbdec222-c256-11e7-8797-f0847366d73a.jpg)
![franz_screenshot2-retouched](https://user-images.githubusercontent.com/33398971/32417286-57c00d82-c257-11e7-9f77-b93d6e88b99b.jpg)

### Steps to Reproduce (for bugs)
Unfortunately I can't figure out yet how to reliably reproduce this.

### Your Environment
* Franz Version used: Version 5.0.0-beta.11 (2x WhatsApp, 3x Slack, 1x Telegram)
* Operating System and version: OSX High Sierra 10.13.1 (17B48)

**Comment by adlk** [comment]
Thanks for reporting this.
- Is this happening with all services or just WhatsApp? 
- What kind Mac are you using? Does it have a dedicated GPU or do you have one of those intel thingies?

**Comment by randomdoe** [comment]
I think it also happened in Slack. It's a Mid14 MBP with a dedicated NVIDIA GPU.

**Comment by adlk** [comment]
Any chance you are using Messenger as well? If you have Messenger activated/deactivated can you see dips in CPU usage?

I'm just trying to connect dots here ;)

**Comment by randomdoe** [comment]
I do, totally forgot to mention that above :O

And you're right, with Messenger activated I have a high (33-45%) CPU usage by WindowServer. I'll disable Messenger now and see if it's happening again but as I'm unable to reproduce the glitches I don't know if that leads to anything,

**Comment by adlk** [comment]
Thanks for letting me know. I suspect (in both cases) that GPU Acceleration could be the cause of that but at the moment this is nothing more than hunch.

This issue might be related to #117 #24

**Comment by randomdoe** [comment]
It happens again on beta.13.316 with Messenger disabled:

![franz_screenshot3-retouched](https://user-images.githubusercontent.com/33398971/32490481-a0523b94-c3b3-11e7-8e0b-57934d391a16.jpg)

I also suspect GPU acceleration to be the problem.

**Comment by dannyqiu** [comment]
I think this issue has been temporarily fixed upstream for a number of users in Electron 1.7.10: https://github.com/electron/electron/pull/10898

**Comment by haraldox** [comment]
@dannyqiu wow, nice catch! thanks for pointing that out 👍
especially since i've hadn't had the problem on Sierra
