### ISSUE TITLE
Correct the spelling for the Italian translation

### ISSUE THREAD

**Issue by Alec423** [meetfranz/franz#218]
Here is a list with the wrong and corrected strings of the it.json file (first one is incorrect, second is correct):

- "welcome.slogan": "Messagistica che lavora per te"
"welcome.slogan": _"Messa**gg**istica che lavora per te"_
- "import.notSupportedHeadline": "Servzi non ancora supportati in Franz 5"
"import.notSupportedHeadline": _"Serv**i**zi non ancora supportati in Franz 5"_
- subscription.features.onpremise": "Agiunge servizi on-premise/hosted come HipChat"
subscription.features.onpremise": _"A**gg**iunge servizi on-premise/hosted come HipChat"_
- "settings.recipes.nothingFound": "Mi dispiace, nessun**o** servizio corrisponde alla tua ricerca."
"settings.recipes.nothingFound": _"Mi dispiace, nessun servizio corrisponde alla tua ricerca."_
-  "settings.app.updateStatusUpToDate": "You are using the latest version of Franz"
   _"settings.app.updateStatusUpToDate": _"**Stai utilizzando l'ultima versione di** Franz"_
- "subscription.mining.line1": "Abilitando \"Supporta Franz con della potenza di calcolo\",Franz userà circa il 20-50% della tua CPU per fare il mining della criptovaluta Monero che equivale approssimativamente a 5$/anno."
"subscription.mining.line1": _"Abilitando \"Supporta Franz con della potenza di calcolo\"**,** Franz userà circa il 20-50% della tua CPU per fare il mining della criptovaluta Monero che equivale approssimativamente a 5$/anno."_
- "subscription.mining.line2": "Adatteremo l'utilizzo della CPU in base all tue abitudini di lavoro per non scaricare la tua batteria e rallentare la tua macchina.",
"subscription.mining.line2": _"Adatteremo l'utilizzo della CPU in base all**e** tue abitudini di lavoro per non scaricare la tua batteria e rallentare la tua macchina."_

**Comment by adlk** [comment]
Thanks for your support.
You can make suggestions directly in our translation tool: http://i18n.meetfranz.com/it/franz/

**Comment by m4dbra1n** [comment]
@Alec423 I've translated the remaining 100+ strings some days ago but even with the latest beta they are not merged: for example, I've leaved "Account" as it is, but in the app is translated "Conto", which for me is weird :S We have to wait for @adlk ;)

**Comment by adlk** [comment]
I'm working right now on merging everything into Pootle. As soon as this is complete, the translation files will be automatically created and merged back into the github repo.

@m4dbra1n have you updated Italian in Pootle?

**Comment by m4dbra1n** [comment]
@adlk all done, give it a look :grinning:

**Comment by haraldox** [comment]
@Alec423 @m4dbra1n thanks for your contributions, i've verified the correct spellings in the latest version of Franz 5.0.0-beta.15 :) thus, closing this
