### ISSUE TITLE
Drag & drop in the wrong place kills Franz main window

### ISSUE THREAD

**Issue by jhoareau** [meetfranz/franz#219]
### Steps to Reproduce (for bugs)

1. Drag something from a Franz service (that could be a profile picture of one of your friends in the Messenger service, for example)
2. Drop it in the left area, where the list of services is
3. See the Franz window completely replaced by a web page of the service in question

### Context
The only solution is to kill and restart Franz completely, as far as I can see.

### Your Environment

* Franz Version used: 5.0.0-beta.12 (but happened on .11 and also in Franz 4)
* Operating System and version: macOS High Sierra (also happened on Windows in Franz 4)

**Comment by adlk** [comment]
Thanks for reporting this. I've added this to the beta 13 milestone.
