### ISSUE TITLE
Mining info link is dead on application.

### ISSUE THREAD

**Issue by AllanStepps** [meetfranz/franz#220]
https://meetfranz.com/mining is 404.

### Expected Behavior
Clicking on `Get more information` should lead us to info page about minig

### Current Behavior
Clicking on `Get more information` returns a 404.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/4098236/32433456-4cd69718-c2db-11e7-8013-67af017e2271.png)

### Possible Solution
Fix the link.

### Steps to Reproduce (for bugs)

1. Go `edit` on an icon.
2. Select `Account` tab.
3. If you're mining, you should see a link.
4. Click on the link.

### Your Environment

* Franz Version used: 5.0.0-beta.11
* Operating System and version: Win7

**Comment by adlk** [comment]
Thanks for reminding me. I'll update the site later today.

**Comment by AllanStepps** [comment]
Good job, thanks.
