### ISSUE TITLE
"Settings" in German translation does not fit the Sidebar

### ISSUE THREAD

**Issue by gregoralbrecht** [meetfranz/franz#223]
The German word for settings – "Einstellungen" – is too long for the sidebar so it sticks out. You could always just change the font size, it should still be large enough.

<img width="116" alt="bildschirmfoto 2017-11-06 um 11 13 49" src="https://user-images.githubusercontent.com/6179211/32436367-21b46ebc-c2e4-11e7-88ce-4508e062215d.png">

**Comment by tobiasdueser** [comment]
What about removing the word and use an icon? Here a mockup in combination with a mute sound button from https://github.com/meetfranz/franz/issues/162 

![image](https://user-images.githubusercontent.com/1573849/32440905-7f885f24-c2f5-11e7-8d48-fca817d9cbe9.png)

And with a mute notification button:
![image](https://user-images.githubusercontent.com/1573849/32441203-c936c75e-c2f6-11e7-8bb0-389fea9ec978.png)

**Comment by adlk** [comment]
I like the idea.

**Comment by adlk** [comment]
Fixed in #252
