### ISSUE TITLE
Add support for outlook.live.com

### ISSUE THREAD

**Issue by Kamahl19** [meetfranz/franz#224]
### Feature Description
Support outlook.live.com

### Motivation and Context
Currently only office 365 is supported, however I am unable to log into it with my custom domain email - which is working on the outlook.live.com

**Comment by adlk** [comment]
I'm already working on it.

---

This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by kell18** [comment]
@adlk Hi! 
Since issue already created, could you tell us about when to expect a release?

Thanks!
