### ISSUE TITLE
Stuck on loading screen after login on macOS

### ISSUE THREAD

**Issue by definelicht** [meetfranz/franz#225]
### Current Behavior
When I type my username and password into Franz, it displays the loading symbol and does not progress (screenshot 1). There is minimal process activity (screenshot 2).

The login must've at least partially succeeded, because all my services appear (screenshot 3).

### Screenshots:
<img width="795" alt="screen shot 2017-11-06 at 12 48 32" src="https://user-images.githubusercontent.com/2845320/32440211-82388738-c2f2-11e7-90f0-c63d74034df4.png">
<img width="1619" alt="screen shot 2017-11-06 at 12 59 16" src="https://user-images.githubusercontent.com/2845320/32440212-825158a8-c2f2-11e7-926e-43f514e9c39a.png">
<img width="182" alt="screen shot 2017-11-06 at 13 04 29" src="https://user-images.githubusercontent.com/2845320/32440367-1eff430e-c2f3-11e7-9d1c-6cd6e26f7eda.png">

### Steps to reproduce
1. Clean install of Franz with Homebrew cask.
2. Launch Franz normally.
3. Type in username and password.

### Things I've tried
I have tried wiping all Franz-related files from my disk that I could find with `locate`, including cache files and reference files, before reinstalling.

### Environment
* Franz Version used: 5.0.0-beta.11.135
* Operating System and version: macOS High Sierra 10.13.1
* Hardware: MacBook Pro (Retina, Mid 2012)

**Comment by adlk** [comment]
This issue is caused by an error when importing Franz 4 services. The latest beta (beta 12) has addressed this issue. Please grab the latest beta here: www.meetfranz.com/#download

_Note:_ This issue unfortunately renders the auto updater useless. :(

**Comment by definelicht** [comment]
Thanks, 5.0.0-beta.12.304 works. I'll go back to Homebrew once they distribute this version or newer.

**Comment by adlk** [comment]
Great! I didn't even realize that there is an cask for that 😅
