### ISSUE TITLE
Messenger notification badge not working correctly

### ISSUE THREAD

**Issue by Boosik** [meetfranz/franz#226]
### Expected Behavior
When using multiple services I expect Franz to show notification badge for all messages from Messenger, when another service is currently selected on the sidebar.

### Current Behavior
Notification badges are not shown for active Messenger conversation when I'm currently using another service (mainly HipChat, but it happens for all of them).

### Steps to Reproduce (for bugs)
1. Open Messenger, chat with a contact
2. Open HipChat and wait for a new message from above contact to be delivered
3. No Unread Messages badge is displayed on Messenger

### Context
I'm missing messages all the time because I have no way to know when a message from my active conversation arrives (mainly from my GF).

### Your Environment
* Franz Version used: 5.0.0-beta.12
* Operating System and version: Windows 10 Fall Creators Update 1709 build 16299.19

**Comment by adlk** [comment]
Which Franz version are you using?

**Comment by Boosik** [comment]
Sorry, 5.0.0-beta.12

**Comment by adlk** [comment]
I can't reproduce it yet but I assume that you are running on a different messenger version where the classnames are different. I'll boot up a Windows 10 VM to do a few tests.

Thanks!

**Comment by haraldox** [comment]
@Boosik Do you still experience the issue in 5.0.0-beta.15?

**Comment by mathpere** [comment]
Hello,
I meet the same issue with the 5.0.0-beta.15 version

Operating System and version: macOS 10.13.2
