### ISSUE TITLE
Can't quit Franz 5.0b12

### ISSUE THREAD

**Issue by bc3tech** [meetfranz/franz#230]
On **Windows 10**, I have Franz settings set to minimize on window close. To quit Franz, I'm used to going to the system tray icon, right clicking, and choosing "Quit Franz"

However, doing this today with Franz window open just minimizes Franz to the tray. Doing it while minimized to tray does nothing - Franz doesn't quit.

This means the only way I can quit Franz is to open Task Manager and End the Task.

**Comment by adlk** [comment]
I'm right now in the middle of deploying a new version with a fix for that. I'm sorry for the inconvenience.

**Comment by bc3tech** [comment]
yup, fixed in 5.0b13!
