### ISSUE TITLE
Freezes with no response

### ISSUE THREAD

**Issue by jpmyhousetevin** [meetfranz/franz#232]
1. Windows 10 Fall Creators Update 1709 When i upgrade , problem happens.
2. Freezes with no response after using few mins
3. Need to use task manager to end
4. Tried re-install, restart, not work

### Screenshots (if appropriate): 
![2017-11-07_133257](https://user-images.githubusercontent.com/33443566/32485363-245eb5d2-c3de-11e7-8922-58440bb1aff3.jpg)

### Your Environment

* Franz Version used:  5.0.0-beta.12
* Operating System and version: Windows 10, 1709

**Comment by adlk** [comment]
When you restart the app and press `Ctrl+Alt+i` -> go to the console tab. Is there any error output before the app freezes?

**Comment by jpmyhousetevin** [comment]
![2017-11-07_174521](https://user-images.githubusercontent.com/33443566/32487072-8f9073b8-c3e3-11e7-8d25-95ab8b329c4b.jpg)

**Comment by adlk** [comment]
This error unfortunately isn't the issue.
If you disable both WhatsApp instances, does it happen as well?

**Comment by jpmyhousetevin** [comment]
when i receive message on one of the whatsapp, it freezes immediately.

No issue before the windows update to 1709

**Comment by adlk** [comment]
Ok this is weird. However, we are having issues with Windows 1709 (Fall Creators Update) #173 as Microsoft has changed their notification center quite much. Does the problem persist if you disable notifications?
<img width="298" alt="bildschirmfoto 2017-11-07 um 13 59 49" src="https://user-images.githubusercontent.com/3265004/32494961-fb2da37c-c3c3-11e7-95f7-ce766a5309c6.png">

**Comment by jpmyhousetevin** [comment]
It works when i disable the notifications. Will it fix soon? Thanks a lot
