### ISSUE TITLE
Desktop notifications not working for Facebook Messenger [Linux]

### ISSUE THREAD

**Issue by cpazaras** [meetfranz/franz#234]
### Issue
No desktop notification is shown for Facebook Messenger activity.

### Expected Behavior
When a new message arrives (or, in general, any activity that grants a notification to the user happens) on any service while the Franz window is not focused/active, a desktop notification should be shown to the user.

### Current Behavior
While desktop notifications work correctly for the rest of the services that I currently use (namely Slack, Skype, WhatsApp), oddly enough they do not work for Facebook Messenger (although the tray icon does indeed correctly show a new message notification - even for Facebook Messenger).

**\* EDIT \*:** Desktop notifications are enabled for the Facebook Messenger service.

Side note: The problem existed also in the previous version (4.0.4-5).

### Environment:
Arch Linux (Antergos) | kernel version 4.11.9-1-ARCH
Franz version 5.0.0_beta.12-1

**Comment by adlk** [comment]
Do you have desktop notifications enabled in messenger?
- In Messenger click the gear icon on the top left
- Go to settings
- Enable desktop notifications

**Comment by cpazaras** [comment]
Apologies - notifications are on, yes - updated the issue accordingly.

**Comment by cpazaras** [comment]
@adlk My bad - I thought you were referring to Franz's service settings - didn't realize FB messenger had its own setting for notifications, that was indeed off. Please close the issue

**Comment by adlk** [comment]
😁
