### ISSUE TITLE
The language of Franz is German but Skype since a short time ago is English

### ISSUE THREAD

**Issue by max17may** [meetfranz/franz#235]
### Screenshots (if appropriate
![screenshot 44](https://user-images.githubusercontent.com/33460375/32506159-2b83849a-c3e4-11e7-8037-767431a62967.png)
):

### Your Environment

* Franz Version used: 5
* Operating System and version: Win 10 64

**Comment by adlk** [comment]
The webview for the services takes the system language. If you open the Franz dev tools (`Ctrl+Alt+i`) go to the console tab and enter `navigator.language` what is the output?

I need to test if it's possible to easily override the webviews language. Having said that. Skype has a terrible language detection that even displays Arabic on some English machines.

**Comment by max17may** [comment]
Its not opening anything while pressing Ctrl+Alt+i.

**Comment by max17may** [comment]
That is the output of it:
C:\Users\.......\AppData\Local\Programs\franz\resources\app.asar\node_modules\react-intl\lib\index.js:706 [React Intl] Missing message: "settings.app.form.enableSystemTray" for locale: "de", using default message as fallback.

navigator.language
"de"

**Comment by whoey** [comment]
Franz (5 beta14 under linux) set to English here, and hangouts/google profile set to English yet recently my entire hangouts screen switched to Spanish (I am in Spain, but nothing is set to Spanish...) yet loads in English in Chrome. All other services setup in Franz are English. Colour me confused.

**Comment by adlk** [comment]
Interesting! Can you please open the service dev tools?
(Ctrl+Shift+Alt+i) go to the console tab and enter `navigator.language`

**Comment by whoey** [comment]
en-US for me, all the hangouts interface is in Spanish

**Comment by haraldox** [comment]
closing this for now, as it is specific to system settings as well as service used.

 feel free to reopen with any questions or comments!
