### ISSUE TITLE
Github Service (links open webpage and can't go back)

### ISSUE THREAD

**Issue by halorium** [meetfranz/franz#236]
### Expected Behavior
I expected the link in the webpage link in the github pull request to open in my default browser rather than in the Franz client. If it should open in the Franz client then I should have a way to go "Back" to the github page.

### Current Behavior
I clicked on a URL link provided in a github pull request description that opened a webpage in the Franz client under the github service. I had no way of getting back to the github view.

### Screenshots (if appropriate):
<img width="1435" alt="screen shot 2017-11-07 at 10 12 51 am" src="https://user-images.githubusercontent.com/81805/32510154-766b8d1c-c3a4-11e7-9b15-e1c72e8e978d.png">

### Possible Solution
Perhaps the easier solution is to provide a way to go "Back" if a link takes you away from github or just open external links in the systems default browser.

### Steps to Reproduce (for bugs)
1. Open the github service in Franz
2. Click on a Pull Request that has an external link in the description of the PR
3. Click on the external link
4. View webpage in Franz (no way to go back)

### Your Environment
* Franz Version used: 5.0.0-beta.13.316
* Operating System and version: macOS Sierra 10.12.6

**Comment by adlk** [comment]
This issue is already tracked in the Github recipe and will hopefully be resolved soon.
https://github.com/redsox2002/recipe-franz-github/issues/1
