### ISSUE TITLE
XMPP Client (in OMEMO)

### ISSUE THREAD

**Issue by goldyx** [meetfranz/franz#237]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by goldyx** [comment]
Thenk you
