### ISSUE TITLE
Discord voice chat cutting out regularly

### ISSUE THREAD

**Issue by benz145** [meetfranz/franz#238]
### Expected Behavior
Discord voice chat through Franz should transmit consistently.

### Current Behavior
Friends tell me that they occasionally (once a minute or so) can't hear me respond to them. The proper Windows Discord client seems to work fine without cutting out.

### Your Environment
* Franz Version used: 5.0.0-beta.11
* Operating System and version: Windows 10 Home version 1709, build 16299.19

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
https://github.com/meetfranz/recipe-discord
