### ISSUE TITLE
Remove the minimum window size limit

### ISSUE THREAD

**Issue by caioquirino** [meetfranz/franz#239]
Remove the minimum window size limit

### Feature Description
Currently in v5.0.0 beta, I can't resize the application to any size, so it's far bigger than I usually use.

### Motivation and Context
Like the previous version, I want to have the application displayed using any window size.

### Mockups, Screenshots (if available):
If it's needed, I can reinstall the old version and send some screenshots

**Comment by adlk** [comment]
Please don't mix multiple issues together as it gets impossible to track them. Your feature request to remove the minimum window size is tracked. Thank you!

Ad your other issue: I assume that you are on windows. You can display the menu by pressing the <kbd>Alt</kbd> key and go to "View".

**Comment by caioquirino** [comment]
@adlk I'm sorry for mixing two feature requests. I have removed the font size point and left only the Window size :D Thank you @adlk !

**Comment by modo-lv** [comment]
This was an immediate issue after update for me as well. I had sized the Franz window at a comfortable 1/4 of a 1080p screen width (minimum that Facebook messenger would allow without pushing text behind the edge), leaving just enough room to use other software at the same time without overlapping with Franz.
Now Franz needs at least 1/3 of the horizontal space and other program windows have to be reduced even further.
There doesn't seem to be any real reason for a minimum width beyond what's needed for the sidebar, so why the arbitrary limit? Please make Franz window more freely resizeable.

**Comment by adlk** [comment]
Without having to rewrite or add a lot of media queries for small window sizes I am able to reduce the window size to 600x500px as a quick fix. It might not be perfect but will save at least 200px in width and 100px in height.
Going further is no option right now as as there is simply not enough time. If someone wants to help to optimize the UI for even smaller window sizes then pls talk to me at the [community slack](http://slack.franz.im) :)

**Comment by Gittyperson** [comment]
I like Franz and would be willing to go premium, but it currently takes up half of my space screen. Is there any chance for further decrease of the minimum window size?

Actually, I was able to make it narrower using a 3rd-party program, but it becomes a bit hard to drag/move the window. Would you consider making it also draggable from the empty space in the left, vertical sidebar? Or from somewhere else you may see fit?

Thanks

**Comment by rhoehener** [comment]
Please reopen and consider removing the minimum window size entirely.

I understand that the beautiful user interface will not work at very small sizes, but please do not patronize your users by enforcing a minimum size. We have our reasons for wanting to make the window smaller.

Take Notepad++ as an example please.

**Comment by Badim150** [comment]
Please reopen and consider removing the minimum window size entirely.
