### ISSUE TITLE
Messenger recipe constantly 17% CPU usage in Franz 5

### ISSUE THREAD

**Issue by rwkyyy** [meetfranz/franz#24]
Upgraded to Franz 5 yesterday and I noticed a higher CPU usage than the older client.

### Expected Behavior
Not eat a constant 17-20% of cpu.

### Current Behavior
Constantly requires at least 17%

### Screenshots (if appropriate):
![alt text](https://i.imgur.com/3wHOUZA.png "CPU usage")

### Steps to Reproduce (for bugs)

1. Add a Facebook Messenger service
2. Login to service
3. Check CPU usage
4. Disable and it will go down.

### Context

High CPU usage, drains battery and makes the device heat up.

### Your Environment

* Franz Version used: 5.0.0-beta.10.7
* Operating System and version: macOS High Sierra 10.13

**Comment by adlk** [comment]
connected with #15

**Comment by bram-ontoforce** [comment]
Same behaviour here, the Facebook tab is really CPU expensive.

**Comment by rafalenden** [comment]
Rambox also having the same issue: https://github.com/saenzramiro/rambox/issues/366

**Comment by adlk** [comment]
Wow it really puzzles me. I have added quite a lot of services which usually use round 0.1-1% each and sometimes go to 10-15% which I would still consider ok as it's short time. Messenger however is going batshit crazy with it's CPU usage!

I did some tests disabling all recipe code, polling, ... and it doesn't improve anything. I will spend some time profiling the service to figure out what to do!

**Comment by rwkyyy** [comment]
Can confirm the update
<img width="276" alt="screen shot 2017-10-20 at 10 54 03" src="https://user-images.githubusercontent.com/13552349/31810662-4cdecb08-b585-11e7-91fb-6275223725f5.png">

**Comment by adlk** [comment]
@rwkyyy great to hear!

Can we do a little crowd-test to make sure this is actually helping on a larger scale?
In `~/Library/Application Support/Franz/recipes/messenger`, update the index.js with:
```js
module.exports = Franz => class Messenger extends Franz {
  overrideUserAgent() {
    return 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36';
  }
};
```
then reload Franz and take a look your activity monitor.

**Comment by rwkyyy** [comment]
<img width="280" alt="screen shot 2017-10-20 at 11 45 06" src="https://user-images.githubusercontent.com/13552349/31812594-289c1000-b58c-11e7-98e7-a8a07b035778.png">
Even better 😊

**Comment by ridculy** [comment]
Have a high CPU load with two Slack Services actice

**Comment by rwkyyy** [comment]
@ridculy I don't think the service is the problem. my cpu usage is the same as in my previous reply, and I have two slack channels logged.

Most probabbly something else is causing the CPU load (from Franz).

**Comment by ridculy** [comment]
It's the "Support with Processing Power"

**Comment by adlk** [comment]
@ridculy What happens on your machine when disable "Support with Processing Power"?

**Comment by ridculy** [comment]
Without I disable "Support with Processing Power" everything is fine.
When I Enabling it :  

<img width="721" alt="bildschirmfoto 2017-10-23 um 22 03 34" src="https://user-images.githubusercontent.com/780164/31910560-2ca0dda2-b83e-11e7-95b4-543104f3460d.png">

**Comment by rikur** [comment]
I don't know where the Monero mining setting is as I couldn't find it in the UI, but I can no longer use Franz as it cuts my laptops battery life in half. You really shouldn't, by default, drain users batteries to mine a silly cryptocurrency -- especially since I can't even find a way to disable it. This is what viruses do.

Back to using a couple separate clients.

**Comment by adlk** [comment]
it isn‘t on by default. Go to settings -> account. if you see pricing options it‘s not activated.

**Comment by rikur** [comment]
At least it's not supposed to be. What would explain the CPU usage then?

I don't have any pricing options in my settings. Never did.

**Comment by danielbayley** [comment]
Maybe related to #117? As mentioned there, performance is **atrocious** unless I disable Facebook messenger!

@adlk Although your suggestion above to override the user agent does seem to improve it a little bit…

**Comment by adlk** [comment]
@rikur you are on Franz 5? If yes, does the Franz logo in your sidebar has a little ⭐️ ?

@danielbayley it could be. At my machine, CPU usage is now down to ~3-5% for messenger but I don't have a dedicated GPU in my MacBook Pro. At this point I suspect that the availability of a GPU could be a reason here.

**Comment by rikur** [comment]
@adlk I apologize for my harsh language earlier on.. I had installed a "franz 5 beta" from a community package -- however, turns out the maintainer had messed up build and it was still running franz 4.x

The actual Franz 5 is a lot more CPU friendly. Thank you.

**Comment by adlk** [comment]
Due to the messenger recipe update there are almost no complaints. I'm closing this for now. If anything comes up, let me know and I'm happy to reopen this.

**Comment by LekanAli** [comment]
Hi Guys. 

Just installed Franz based on recommendation from Verge ... Straight to the point: Checking my activity monitor, noticed i have 5 "Franz Helper" processes running (and taking a huge chunk of my memory) and also huge energy impact on my laptop. 

Any suggestion on how to deal with this, i don't want to get rid of the app anytime soon. 😞

**Comment by zhezh** [comment]
I was using franz 5.0.0-beta14, I heard laptop fan spin fast without doing heavy computing work. As I check the cpu and gpu usage, the cpu and gpu are both about 50%. 
Since I have mined monero on my computer once, I can recognize the cpu usage pattern of mining monero.

and I cannot find any disable option in setting -- account, now I switch to the latest beta 15 to see if the monero miner is removed.

**Comment by heyoni** [comment]
Is Franz actually mining a cryptocurrency in the background?

**Comment by velsa** [comment]
When I enable ICQ service it jumps from 6-8% to 20-25%
I also have a few gmails, FB, WhatsApp, telegram, keep and calendar. 
In general, why would it take 6-8% when no messages are being sent or received

**Comment by Arsur** [comment]
This is really unprofessional, Sry but you get no information when installing this, that there will be mining. I really liked this tool, but first of all i wont pay 30€ per Year for a tool which is just using some APIs. I would be willing to support but not at this high price, why is there is no lifetime membership (at max 20€).

I will drop this tool now because of bad behavior against your customers or at least against me. Some people seem to have just money bills in their heads.

**Comment by kasperschnack** [comment]
Please reopen. My cooling fan is driving my colleagues crazy while running franz :(

**Comment by KnechtRootRecht232** [comment]
same here, when fb-messenger is open with a group-chat, cpu jumps to 80%

**Comment by AurelienVernay** [comment]
Issue is still there, please reopen and investigate

**Comment by ogtfaber** [comment]
@AurelienVernay same here 
<img width="726" alt="Screenshot 2019-04-25 09 00 47" src="https://user-images.githubusercontent.com/320955/56750525-d1f78580-6738-11e9-9e54-55c0ecafed1e.png">

**Comment by cnf** [comment]
CPU Load is still crazy high

**Comment by mvaneijgen** [comment]
Franz is now unusable. It is now at 150% + while being in the background and not using it.

**Comment by MichaelRo** [comment]
I don't have facebook messanger and franz cpu is crazy high
What do I use:
Notion.so, Todoist, Whatsapp, Slack, Telegram, Gmail, github, Google calendar

**Comment by kasperschnack** [comment]
I've thrown in the towel now and switched to [Rambox](https://rambox.pro/#home). It's open source and does not use nearly as much CPU as franz does. Can recommend 👍

**Comment by cnf** [comment]
I did the same, but with https://github.com/TheGoddessInari/hamsket
