### ISSUE TITLE
Google Services don't work with Google Advanced Security

### ISSUE THREAD

**Issue by austinfathman** [meetfranz/franz#240]
The Chrome Webview used by Franz isn't able to make the appropriate API calls to the USB controller to detect and interact with the two-factor security key

### Expected Behavior
Franz should be able to interact with the two-factor key

### Current Behavior
On the two step page of logging in, the message "Something went wrong. Remove your Security Key and try again" appears.

### Screenshots:
![image](https://user-images.githubusercontent.com/20168296/32555006-9332dc8c-c469-11e7-950c-bfe3d85dcaa4.png)

### Steps to Reproduce

1. Turn on Advanced Protection on your Google Account (https://landing.google.com/advancedprotection/) 
2. Add a Google service (Inbox, Gmail, Hangouts)
3. Try to log in
### Context
Whether for personal security or a corporate security policy, it would be beneficial to support these usb two-factor devices.
### Your Environment
* Franz Version used: 5.0.0-beta.13.316
* Operating System and version: Mac 10.12.6

**Comment by adlk** [comment]
There is a discussion about this in the electron issue tracker:  https://github.com/electron/electron/issues/3226

With the latest comments there, it seems like that progress has been made. I will try to get one of those keys to do my research.

**Comment by D-32** [comment]
Has support for U2F keys been added in the meantime @adlk?

**Comment by D-32** [comment]
Thanks @adlk, would love to see it happen :)

**Comment by adlk** [comment]
There seems to be progress on this topic with electron 4. Migrating Franz to electron 4.x however is just a very bumpy ride that takes time and requires a long testing cycle. But let's hope for the best.
