### ISSUE TITLE
Don't activate badge for muted conversations

### ISSUE THREAD

**Issue by juilyoon** [meetfranz/franz#242]
### Feature Description

Specifically in Whatsapp, I am a part of several group conversations that I check periodically, but I don't want to be notified of updates because there are too many people sending messages. 

Whatsapp has a mute function, but messages in muted conversations still activate the badge in Franz's sidebar and dock.

I don't think this makes sense, especially since the user has muted the conversation already.

### Mockups, Screenshots (if available):

![screen shot 2017-11-08 at 9 42 42 pm](https://user-images.githubusercontent.com/516726/32576445-e480a762-c4ce-11e7-838f-3e5e42cf1dae.png)

**Comment by adlk** [comment]
This is actually an issue with the WhatsApp recipe. Thankfully it was already fixed by @GustavoKatel and is now deployed. You will be notified soon that the update is installed.

**Comment by juilyoon** [comment]
Didn't even notice because it was fixed so seamlessly.
🥂
