### ISSUE TITLE
Feature request: Groups/separators in the left hand services column

### ISSUE THREAD

**Issue by adrienne** [meetfranz/franz#243]
I would like to be able to visually separate my "work" services from my "personal" services inside the Franz window, and it seems like the easiest way to do that would be to allow adding a simple horizontal separator. I've mocked up the sort of thing I mean; see the image below.

![default_2017-11-08--20-09-05](https://user-images.githubusercontent.com/89705/32588098-467bbcb2-c4c1-11e7-93ae-1149e28465dd.jpg)

**Comment by adlk** [comment]
I'm going to add "groups" soon. On top of having dividiers, you'll be able to enable/disable groups and provide overrides for options like notifications, audio, ...

**Comment by benjaminclement7** [comment]
Is there an ETA for when this feature would be added?
Loving FRANZ btw!

**Comment by FilipMalczak** [comment]
I'm with Benjamin, also loving Franz here ;)

I would totally use groups/folders. I don't have too much need for separator, but I guess they could be useful too.

**Comment by phantomwhale** [comment]
Yeah, as I'm moving more into Franz, removing all those pesky pinned tabs from Chrome, I'd also love this feature. A lot of these things are memory hogs (Slack, Gmail, FB messenger) and being able to toggle off "home" / "work" stuff easily to recover that memory, and remove unwanted distractions during the work day / weekend would be good

(right now, I use two chrome profiles, and minimize or shut down the chrome window in question)

**Comment by seesemichaelj** [comment]
Unstale

**Comment by phantomwhale** [comment]
Guess we're not getting separators then?

**Comment by Xerus2000** [comment]
@adlk said in https://github.com/meetfranz/franz/issues/1352 that this is "coming soon". But I wonder if it will also come with disabling multiple grouped services at once, since I do not have enough memory to spare for all my services on my laptop.
