### ISSUE TITLE
Command failed: /home/ktrls/.cache/electron-builder/fpm/

### ISSUE THREAD

**Issue by ktrls** [meetfranz/franz#245]
Hi, I'm trying to update franz-bin package from aur, but I have an error that I don't understand.
This is my log:

> Costruzione in corso di franz-bin...
> Cloning into 'franz-bin'...
> remote: Counting objects: 40, done.        
> remote: Compressing objects: 100% (30/30), done.        
> remote: Total 40 (delta 14), reused 26 (delta 9)        
> Unpacking objects: 100% (40/40), done.
> ==> Creazione del pacchetto: franz-bin 5.0.0_beta.13-1 (gio  9 nov 2017, 09.21.44, CET)
> ==> Controllo delle dipendenze durante l'avvio in corso...
> ==> Controllo delle dipendenze durante la compilazione in corso...
> ==> Download dei sorgenti in corso...
>   -> È stato trovato franz-bin.desktop
>   -> Download di v5.0.0-beta.13.tar.gz in corso...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   131    0   131    0     0    131      0 --:--:-- --:--:-- --:--:--   223
> 100 3932k  100 3932k    0     0  1966k      0  0:00:02  0:00:02 --:--:-- 2097k
> ==> Validazione di source file con sha256sums...
>     franz-bin.desktop ... Verificato
>     v5.0.0-beta.13.tar.gz ... Verificato
> ==> Estrazione dei sorgenti in corso...
>   -> Estrazione di v5.0.0-beta.13.tar.gz usando bsdtar in corso...
> ==> Avvio di build() in corso...
> yarn add v1.3.2                                                                
> [1/4] Resolving packages...                                                    
> [2/4] Fetching packages...                                                     
> info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
> info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> info 7zip-bin-win@2.1.0: The platform "linux" is incompatible with this module.
> info "7zip-bin-win@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
> info fsevents@1.1.2: The platform "linux" is incompatible with this module.    
> info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...                                                  
> warning " > eslint-config-airbnb@14.1.0" has incorrect peer dependency "eslint@^3.15.0".
> warning " > eslint-plugin-jsx-a11y@3.0.2" has incorrect peer dependency "eslint@^2.10.2 || 3.x".
> warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
> [4/4] Building fresh packages...                                               
> success Saved lockfile.                                                        
> success Saved 2 new dependencies.                                              
> ├─ gulp-cli@1.2.2                                                              
> └─ gulp@4.0.0-alpha.2                                                          
> warning "gulp" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
> Done in 52.72s.                                                                
> yarn run v1.3.2                                                                                                       
> $ node_modules/.bin/electron-rebuild --production --non-interactive                                                   
> ✔ Rebuild Complete
> Done in 24.93s.                                                                                                       
> yarn run v1.3.2                                                                                                       
> $ gulp build                                                                                                          
> [09:23:06] Requiring external module babel-register
> [09:23:07] Using gulpfile /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/gulpfile.babel.js
> [09:23:07] Starting 'build'...
> [09:23:07] Starting 'clean'...
> [09:23:07] Finished 'clean' after 4.7 ms
> [09:23:07] Starting 'mvSrc'...
> [09:23:07] Starting 'mvPackageJson'...
> [09:23:07] Finished 'mvPackageJson' after 67 ms
> [09:23:07] Finished 'mvSrc' after 399 ms
> [09:23:07] Starting 'html'...
> [09:23:07] Starting 'scripts'...
> [09:23:07] Starting 'styles'...
> [09:23:08] Finished 'html' after 98 ms
> [09:23:08] Finished 'styles' after 350 ms
> [09:23:12] Finished 'scripts' after 4.17 s
> [09:23:12] Finished 'build' after 4.57 s
> $ node_modules/.bin/electron-builder --publish onTag                                                                  
> electron-builder 0.0.0-semantic-release
> Using electron-builder.yml configuration file
> electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
> 
> To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
> Installing app dependencies for arch x64 to /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/build
> Packaging for linux x64 using electron 1.7.9 to out/linux-unpacked
> Building AppImage for arch x64
> Building deb
> Error: Exit code: 1. Command failed: /home/ktrls/.cache/electron-builder/fpm/fpm-1.8.1-2.3.1/fpm -s dir -t deb --architecture amd64 --name franz --force --after-install /tmp/electron-builder-8vAKuQ/0-2-after-install --after-remove /tmp/electron-builder-8vAKuQ/0-3-after-remove --description 
>  Messaging app for WhatsApp, Slack, Telegram, HipChat, Hangouts and many many more. --maintainer Stefan Malzner <stefan@adlk.io> --vendor Stefan Malzner <stefan@adlk.io> --version 5.0.0-beta.13 --package /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/out/franz_5.0.0-beta.13_amd64.deb --url https://github.com/meetfranz/franz#readme --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license Apache-2.0 /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/out/linux-unpacked/=/opt/Franz /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/build-helpers/images/icons/1024x1024.png=/usr/share/icons/hicolor/1024x1024/apps/franz.png /tmp/electron-builder-8vAKuQ/0-4-Franz.desktop=/usr/share/applications/franz.desktop
> 
> {:timestamp=>"2017-11-09T09:25:14.533668+0100", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
> {:timestamp=>"2017-11-09T09:25:14.947479+0100", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
> {:timestamp=>"2017-11-09T09:26:25.163261+0100", :message=>"Process failed: tar failed (exit code 2). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-98ff3c6f6d2f1aa13efe4990ac120541d5576fa95c1249ea61a4074d2641\", \"-J\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-40c44fe97cfa30f8635da4f66b35bb3e944af1e611446dbbd0f139dce5c5/data.tar.xz\", \".\"]", :level=>:error}
> 
>     at /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder-util/src/util.ts:64:16
>     at ChildProcess.exithandler (child_process.js:279:5)
>     at emitTwo (events.js:125:13)
>     at ChildProcess.emit (events.js:213:7)
>     at maybeClose (internal/child_process.js:927:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> From previous event:
>     at exec (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder-util/src/util.ts:42:3)
>     at /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/targets/fpm.ts:208:11
>     at Generator.next (<anonymous>)
> From previous event:
>     at FpmTarget.build (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/out/targets/fpm.js:256:11)
>     at default.each.it (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/platformPackager.ts:106:87)
>     at runCallback (timers.js:785:20)
>     at tryOnImmediate (timers.js:747:5)
>     at processImmediate [as _immediateCallback] (timers.js:718:5)
> From previous event:
>     at taskManager.addTask.default.map.then (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/platformPackager.ts:106:35)
> From previous event:
>     at LinuxPackager.packageInDistributableFormat (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/platformPackager.ts:106:8)
>     at /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/platformPackager.ts:101:10
> From previous event:
>     at LinuxPackager.pack (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/out/platformPackager.js:171:11)
>     at /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/packager.ts:244:24
> From previous event:
>     at Packager.doBuild (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/out/packager.js:317:11)
>     at /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/packager.ts:175:52
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:785:20)
>     at tryOnImmediate (timers.js:747:5)
>     at processImmediate [as _immediateCallback] (timers.js:718:5)
> From previous event:
>     at Packager.build (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/out/packager.js:236:11)
>     at /tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/builder.ts:256:40
>     at Generator.next (<anonymous>)
> From previous event:
>     at build (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/out/builder.js:69:21)
>     at Object.args [as handler] (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/cli/cli.ts:42:4)
>     at Object.self.runCommand (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
>     at Object.Yargs.self._parseArgs (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
>     at Object.get [as argv] (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
>     at Object.<anonymous> (/tmp/pamac-build-ktrls/franz-bin/src/franz-5.0.0-beta.13/node_modules/electron-builder/src/cli/cli.ts:37:15)
>     at Module._compile (module.js:612:30)
>     at Object.Module._extensions..js (module.js:623:10)
>     at Module.load (module.js:531:32)
>     at tryModuleLoad (module.js:494:12)
>     at Function.Module._load (module.js:486:3)
>     at Function.Module.runMain (module.js:653:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
> error Command failed with exit code 255.                                                                              
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                  
> ==> ERRORE: Si è verificato un errore in build().
>     L'operazione sta per essere interrotta...
> 

### My Environment

* Franz Version used: initial 4.0.4-5 final 5.0.0.beta.13-1
* Operating System and version: Manjaro 17.2

**Comment by haraldox** [comment]
@ktrls found a solution yet / workaround?
