### ISSUE TITLE
IRCCloud incorrect notifications

### ISSUE THREAD

**Issue by cjohnston1158** [meetfranz/franz#247]
When using Franz 5 13.316, the IRCCloud icon is showing unread notifications for all channels that I am in, not just direct pings/PMs. This appears to be a regression from Franz 4 and makes Franz essentially unusable.

### Expected Behavior
Have the ability to only be notified about direct pings/PMs.

### Current Behavior
Being notified about all new messages in all channels.

### Your Environment
* Franz Version used: 5 13.316
* Operating System and version: OS X 10.13.1

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
https://github.com/albertomurillo/recipe-irccloud
