### ISSUE TITLE
Franz 5 states not connected to internet

### ISSUE THREAD

**Issue by cjohnston1158** [meetfranz/franz#249]
Started up my Mac and Franz 5 states that I am not connected to the internet.. I'm filing this issue, so clearly I am. When clicking the "X" to remove the notification bar, nothing happens.

### Expected Behavior
After internet connection is established, the bar should go away, or atleast allow me to get rid of it.

### Current Behavior
The bar stays and takes up real estate on my screen.

### Screenshots (if appropriate):
https://imgur.com/a/cELOl

### Your Environment

* Franz Version used: 5 13.316
* Operating System and version: OS X 10.13.1

**Comment by haraldox** [comment]
@cjohnston1158 Do you still experience the issue in 5.0.0-beta.15?

**Comment by cjohnston1158** [comment]
Yes, I've run into this issue again today on 5.0.0-beta.15

I rebooted a couple of hours ago and it is still showing that I'm not connected to the internet. Clicking the "x" still doesn't remove it.
