### ISSUE TITLE
Provide the possibility of using shortcuts for emoticons

### ISSUE THREAD

**Issue by IskaNeumann** [meetfranz/franz#25]
### Feature Description
It would be cool if you could just write a predefined shortcut instead of clicking on a smiley. After typing the shortcut, the word automatically changes to the corresponding smiley.

### Motivation and Context
It makes it possible to use smileys without a mouse. Programmers like to work only with the keyboard :)

**Comment by edgarjrg** [comment]
Shouldn't  be that a feature for the service itself instead of Franz? eg: slack :name: behavior.

**Comment by adlk** [comment]
@edgarjrg I had something like the _:emoji:_ auto replace behaviour in mind when I labeled this as a feature request. I did a quick test and it seems that most of the major services have added support for this in the last couple of months.  

I'm going to close this as duplicating an already existing feature seems a bit pointless.
