### ISSUE TITLE
Missing labels in services menu

### ISSUE THREAD

**Issue by cjohnston1158** [meetfranz/franz#250]
When clicking the 'Services' dropdown, I see a list of "blank" services.

### Expected Behavior
Show me the services :-)

### Current Behavior
See screenshot

### Screenshots (if appropriate):
https://imgur.com/a/cELOl

### Your Environment

* Franz Version used: 5 13.316
* Operating System and version: OS X 10.13.1

**Comment by adlk** [comment]
Are just the labels missing or is a click on the service broken as well?

**Comment by cjohnston1158** [comment]
Just the labels missing. Clicking seems to work.
