### ISSUE TITLE
Switch tabs with Shortcut skips tabs after cycling around

### ISSUE THREAD

**Issue by brospo** [meetfranz/franz#251]
Shortcut for cycling tabs does not operate correctly.

### Expected Behavior

Cycle through each tab one by one, and wrap around to the first/last when moving past the edge.
### Current Behavior

On Mac, when using Cmd+(Left | Right) for switching tabs works normally. When Cmd+Right is used on the right most tab, it goes to the second tab, then fourth (of four total tabs). From then on it will cycle through the second and fourth tab when using the shortcut until the application is restarted. 

### Possible Solution

Cycle through tabs with shortcut.

### Context

Annoying, who uses the mouse??? :) 

### Your Environment

* Franz Version used:
* Operating System and version:
MacOs

**Comment by adlk** [comment]
Please complete the issue template by adding the Franz version you are using

**Comment by haraldox** [comment]
@brospo The Cmd+(Left | Right) shortcut is not available on Franz 5 ... Not sure yet if it'll come back in one way or another in the future.
