### ISSUE TITLE
Feature request : Tinder integration !

### ISSUE THREAD

**Issue by vlom31** [meetfranz/franz#254]
### Expected Behavior
Have tinder chats integrated to Franz.

### Current Behavior
N/A

### Possible Solution
They have a web app :)

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
