### ISSUE TITLE
CMD+W in macOS to close the window, not the application

### ISSUE THREAD

**Issue by magobaol** [meetfranz/franz#257]
Currently hitting CMD+W in macOS close the application, while the standard beahviour in macOS is to just close the windows, keeping the application running.

### Feature Description
CMD+W should only close the main window, leaving the application running.
CMD+Q should close the application.

### Motivation and Context
What I'm proposing is the standard behaviour in macOS applications: implementing it gives the user a sense of homogeneity with what he use daily.
Additionally, I can suggest that some softwares give the user an option to "Close the application when the main window is closed", for those users that want to close the app with CMD+W.

**Comment by adlk** [comment]
If you take a closer look this isn't actually a standard behaviour of macOS apps as a lot of apps do whatever they think is best. In the past year we've constantly got complaints of two groups who expected the exact opposite behaviour. You can enable the app to run in background in settings. This flag is currently _off_ by default but will be set to _on_ with the next beta coming next week.
<img width="452" alt="bildschirmfoto 2017-11-10 um 23 10 28" src="https://user-images.githubusercontent.com/3265004/32680735-5d149780-c66c-11e7-9b44-2f23defcd411.png">

**Comment by magobaol** [comment]
I totally missed it! Thank you.
