### ISSUE TITLE
Deactivating a service is much more complicated than it was in version 4

### ISSUE THREAD

**Issue by Pawely** [meetfranz/franz#258]
### Expected Behavior

Deactivating a service is much more complicated than it was in version 4.
After deactiting the service through the context menu it should not disappear from the sidebar but just be grayed out.

### Current Behavior

Currently the service disappears from the sidebar after deactivating it and it needs several clicks through the settings menu to activate the service again.

### Possible Solution

After deactiting the service through the context menu it should not disappear from the sidebar but just be grayed out. And through the context menu I should be able to activate it again.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

Easily activate and deactivate a service.

### Your Environment

* Franz Version used:
* Operating System and version:
Windows 7
Franz 5.0.0 beta.13

**Comment by adlk** [comment]
Already resolved in #248 and will be shipped in the next couple of days.
