### ISSUE TITLE
New Franz - How to start?

### ISSUE THREAD

**Issue by srjpfc** [meetfranz/franz#259]
sorry about such a trivial question but i was a Franz 4 user and i updated to the new beta.
as soon as i open Franz i get this screen:

<img width="1107" alt="screen shot 2017-11-10 at 22 11 29" src="https://user-images.githubusercontent.com/19504215/32680829-7713e4b8-c664-11e7-9a20-d762f73c6b92.png">

i was not able to add a new Hangouts service, for instance, or at least change the type of service i'm adding.

am i now forced to have a Franz account before i add any other services?

if so, Franz lost a user.

thank you.

**Comment by adlk** [comment]
This has already been discussed in #71 

I you want to reach out to me you can contact me via [email](mailto:stefan@adlk.io) or on [Twitter](https://twitter.com/smalzner) but **Github is not a place to vent!**
