### ISSUE TITLE
General Data Protection Regulation (GDPR)

### ISSUE THREAD

**Issue by KikiGerritsen** [meetfranz/franz#26]
GDPR is to protect and empower all EU citizens data privacy and to reshape the way organizations across the region approach data privacy.

### Expected Behavior
As the summary says. The GDPR is for EU citizens, yet it will affect ALL instances in the world that use data of people. My question, is Franz GDPR compliant?

I've just updated Franz to the beta and noticed that I had to create an account. There is user data.. Do you keep the data for other instances like Slack or HipChat for example? Or is that just a pipe to the real app? Cuz in may 2018 there'll be new rules. [GDPR site](http://www.eugdpr.org/)

**Comment by adlk** [comment]
Thanks for bringing this up.

Right now Franz is not fully GDPR compliant but we are working on it to get there. 

We only store a very limited amount of personal, and identifiable, data (name, email & organization) while what you do with the services stays untouched as we just display the services web app – we have no intend and interest in getting more out of it.
