### ISSUE TITLE
No user with that email address was found

### ISSUE THREAD

**Issue by roberthopman** [meetfranz/franz#260]
I tried to use my 3 email addresses. None was recognized. 

### Expected Behavior

I want to reset my password, as I don't remember them.

### Current Behavior

Can't reset because it doesn't recognize my email address.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: the current download, Version 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: macOS Sierra

**Comment by adlk** [comment]
Have you created your account with Franz 5? If not, there was no account in v4 and it may be confusing for some people.

If you have created your account with v5 then please send me an email to stefan@adlk.io to check what the issue is.

**Comment by roberthopman** [comment]
aha.
