### ISSUE TITLE
Message preview in notifications + telegram groups' notifications

### ISSUE THREAD

**Issue by kisaita** [meetfranz/franz#262]
Hello, I'm totally in love with the app and totally going for the yearly sub.
The thing that bothers me however is that upon message notification on Windows, I cannot see its preview in bottom right corner :( Just information I got one. Is it possible to add the preview?

Another issue is that Telegram groups messages show in Franz as "unread" even though I have notifications from them off.
Basically having perma notification like this: https://i.gyazo.com/ed452ba3ef11cc89bd2bc32a5969222f.png
I would like to turn it off possibly.

**Comment by adlk** [comment]
@kisaita hey, thanks for your support.
Are you using Windows 10 with the Fall Creators Update? If yes, the windows update broke something with the notifications API. I hope to have a fix for that soon. 
You can follow this issue to stay up to date: #173
