### ISSUE TITLE
Why does Franz have so many background processes?

### ISSUE THREAD

**Issue by SavellM** [meetfranz/franz#265]
Hey guys,

Is there any word on a 64bit installer?

Lastly is there a reason why Franz has so many background processes?
Running 5 services but have between 7 to 12 services running in the background.

### Expected Behavior
5x Background apps, 1 for each service.

### Current Behavior
Currently I have 12 background processes for my 5 services.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/896836/32720720-4aa57488-c85c-11e7-9d5e-2fc5977e5bc5.png)
![image](https://user-images.githubusercontent.com/896836/32735535-e3ccb9d4-c88c-11e7-8d61-f6d8a2a8ec87.png)

### Steps to Reproduce (for bugs)
Configured 2x Slack, 1x WhatsApp, 1x Skype, 1x Discord.
Watch background processes

### Context
Not a big effect, just extra resources taken.

### Your Environment
* Franz Version used: 5.0.0-beta.13
* Operating System and version: Windows 10 - 1607

**Comment by adlk** [comment]
Every service runs in a separate process. Based on your screenshot, I'd guess that you have added 9 services.
If one service for examples crashes, just the service goes down and not the complete app.

64bit installer is on my radar but I'm not quite ready yet.

**Comment by SavellM** [comment]
I only have 5 services added...

That's why I was wondering why there were so many running...
![image](https://user-images.githubusercontent.com/896836/32735073-b1bb2242-c88b-11e7-997b-43d11d68427a.png)

**Comment by adlk** [comment]
When you restart the app and give it some time to initialize everthing, do you already have 12 processes in task manager?

**Comment by SavellM** [comment]
Yup... Its been running now for must be 5+ hours.
Still have 12 instances in background processes.

**Comment by adlk** [comment]
Ok, thanks!
Can you please update your initial post with the missing information from the issue template? Otherwise it's impossible for me to keep track of it.
https://raw.githubusercontent.com/meetfranz/franz/master/.github/ISSUE_TEMPLATE.md

**Comment by SavellM** [comment]
Updated. Let me know if I'm missing anything helpful for you

**Comment by deseven** [comment]
It's kinda the same for me, i have 3 services and 5 (or 6 if you count the main one) processes:  
![](http://eri.deseven.info/scr/AntigodAgrypniaDiethyl.png)

**Comment by adlk** [comment]
@SavellM thanks. I will update this issue once I've ben able to test it.

@deseven in your case, everything seems fine to me :)

Usually those processes will be shown:
- One main process (handles background stuff, managing the windows, ...)
- One render process (everything inside of Franz e.g. UI)
- Every WebView runs in a separate process, even every instance of the dev tools.
- Some background tasks that will be spawned from time to time..

So even with just one service, the minimum of processes is 3.

**Comment by henrebotha** [comment]
Worth pointing out as well that disabled services still consume memory.

**Comment by adlk** [comment]
@henrebotha this issue was resolved in #294

**Comment by haraldox** [comment]
This is normal behavior for Electron apps, but we will of course try to reduce memory usage in the future... stay tuned!

**Comment by IljaDaderko** [comment]
Any updates on this? Experiencing similar issue. 4 Services 8 instances of Franz helper eating up 2 gigs of ram :/

**Comment by keremcankabadayi** [comment]
same on `MacBook Pro (Retina, 13-inch, Late 2013) 10.13.2 Beta (17C79a)` when i start the Franz, my mac goes crazy.

**Comment by KeeeN** [comment]
Same issue on ubuntu 16.04.
Moreover it uses a lot of memory. :cry: 

![screenshot from 2018-04-09 19-49-18](https://user-images.githubusercontent.com/3985700/38513637-244180d8-3c2f-11e8-931c-d25decff49a8.png)

Version: 5.0.0-beta.17
Release: 1.8.4 / linux / x64

**Comment by solalatus** [comment]
Same on Ubuntu 18.04 
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

**Comment by abhanshgiri21** [comment]
I have the same issue. My ubuntu 18.04 was only running franz with 8 services and it was eating up 6.7 GB of ram. This is crazy since i have to spin up my local develpment servers and my editors and they all need memory. with franz taking up more than half of it, it's impossible to for me to keep up with my work. I have 12GB of ram. Any update on this issue????

**Comment by samura** [comment]
Just deleted a couple of services that were disabled and the memory went down about 500MB to 2.33Gb.
Disabled services shouldn't use that much memory.

**Comment by menzow** [comment]
@abhanshgiri21, @samura 
It may be useful to report the exact services that you're using. Also you could try disabling all services and adding them again one  by one to pinpoint the culprits. Only then can your issues be resolved.

By doing this I was able to determine the new gmail interface was hogging huge amounts of memory and constantly churning CPU. Having two gmail services for work and personal email enabled made Franz unusable for me. Switching them to Inbox by gmail helped a lot. I now ended up switching back to the old Gmail UI, and now my resource usage is back to normal.

**Comment by shadi1989** [comment]
Same issue here.

Windows 7 x64
Version: 5.0.0-beta.17
Release: 1.8.4 / win32/ x64

10 services enabled, 2gb+ RAM in use.

**Comment by MarleneMayr** [comment]
Similar issue.
For me it's with Windows 10 x64
Version: 5.0.0-beta.18
Release: 1.8.4 / win32/ x64
8 Services -> 20 open Tasks with minimum 1GB RAM

**Comment by MaciejWWojcik** [comment]
me too, it's almost 2GB!
[screen](https://imgur.com/a/Wh25cSA)

**Comment by TerrorSource** [comment]
@menzow Even better. i made an excel list.
Started with all services enabled. Listed the process RAM usage. Deleted 1, list RAM usage etc etc. until no service were left.

Franz was running for almost 7hours straight after starting up the laptop.

[FranzProcesses.xlsx](https://github.com/meetfranz/franz/files/2379122/FranzProcesses.xlsx)

**Comment by janjurek** [comment]
I'm not impressed by the RAM hungriness of the Franz, I think was not that bad before but when Main app takes usually more than 1.5GB sometimes over 2GB of memory - it's really pretty bad. I love Franz but if this issue will not be addressed, there's really no reason not to use browser that is now way more RAM effective :(. I've also read about slack and other electron apps optimising this problem as well, but I also understand that this is basically a one-man project so no hard feelings, just RAM is the most important bottleneck for me.

![ram](https://user-images.githubusercontent.com/14951952/50043383-6529fb80-0073-11e9-8e82-c44d704baa3d.png)

I'm on newest version: 5.0.0-beta.22 (5.0.0-beta.22.1059)

**Comment by Alsoknownasjazz** [comment]
I'm in the same boat, love the app, using it for 8 services, but RAM consumption is a bit high. Complete agreement with janjurek. If it can be improved, that would rock.

**Comment by felixpenrose** [comment]
Not quite as bad here, but still pretty poor.

5 services, 11 processes running, 900MB total. I did have 8 services but didn't use 3 much so figured I recover some ram.
Kind of defeats the purpose of this program if I have to slim down how many services I use because it eats all my available ram.

5.2.1-beta.1
