### ISSUE TITLE
Is it possible to link Microsoft tools, such as Yammer, Teams ?

### ISSUE THREAD

**Issue by John65r** [meetfranz/franz#266]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Microsoft Teams is already available

---

This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by John65r** [comment]
I can’t see Microsoft Teams in the list of services I can add…

Met attente groeten
Avec toute notre attention

[http://www.attentia.be/sites/default/files/public-email/emailsig_hrexcellenceawards-13-14-15_D.png]<http://www.attentia.be/nl/hr-excellence-awards>

Johan Dekyvere
Product Developer
Attentia
• Sluisweg 1 ,bus 1   • T 0478607672
• 9000 Gent
www.attentia.be<http://www.attentia.be/nl> | LinkedIn<http://www.linkedin.com/company/14692?trk=tyah> | Facebook<https://www.facebook.com/pages/Attentia-Official/262990180445505> | Twitter<https://twitter.com/attentianl>
Disclaimer<http://www.attentia.be/disclaimer>



P Please consider the impact on the environment before printing this e-mail

**Comment by adlk** [comment]
Are you already using Franz 5?
If not get the latest version on www.meetfranz.com
