### ISSUE TITLE
Linux: CPU Usage high with 5 services enabled

### ISSUE THREAD

**Issue by brhahlen** [meetfranz/franz#267]
### Expected Behavior
Low CPU usage when idle

### Current Behavior
High CPU usage when screen is not in focus.
Am using the AppImage version of Franz for Linux.
Have 5 services enabled:
 - WhatsApp (2 times)
 - HipChat
 - Slack (2 times)

### Screenshots (if appropriate):
![screenshot from 2017-11-13 16-46-05](https://user-images.githubusercontent.com/1798663/32734388-2d99a036-c892-11e7-9e50-e4a4d2e9c27d.png)

### Possible Solution
Don't know

### Steps to Reproduce (for bugs)
1. Download AppImage version of Franz
2. Add 5 services, 2x WhatsApp, 1x HipChat, 2x Slack

### Your Environment

* Franz Version used: 5.0.0-beta12, AppImage
* Operating System and version: Fedora 26

**Comment by jdewinne** [comment]
Experiencing the same with 14 services on beta14, Fedora 27

**Comment by superjax** [comment]
I'm seeing the same thing with 5.0.0-beta.16 (ubuntu gnome 16.04)

**Comment by jdewinne** [comment]
My load on beta 16 is way lower. However, after a wakeup from sleep, it jumps up. So I have to do a `killall franz` and start it back up.

**Comment by bbbart** [comment]
Similar behaviour here on Arch Linux for Franz 5.0.0_beta.16-1, with a paid for premium account. Frequent need of `killall franz`, seemingly related to starting up Chromium in parallel with Franz. Franz is becoming more and more unusable as it is eating up my whole system. :-(

**Comment by CGavrila** [comment]
I have the same problem with `franz_5.0.0-beta.18_amd64.deb` on Ubuntu 18.04 with about 7 services open - 2 Slack, Whatsapp, Facebook Messenger, Trello and 2 Gmail. It is literally unusable, since it uses about 50% CPU on 6 cores. 

```
$ uname -a
Linux xxxxxx 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by samwalshnz** [comment]
Same issue on OSX as well

**Comment by Karif** [comment]
Same on Debian 9 with Cinnamon.

**Comment by jnvandermeer** [comment]
Same on Arch Linux, Cinnamon, Franz Version 5.0.1 Release 4.1.4, 64-bit.

Is it not unusable this way - sure the program runs, but there are always 4 'electron' processes running clogging up by CPU with 14-20 % per core, at all times.

What is that CPU power used for?

I am revering back to version 4 until this is solved.

**Comment by klemy** [comment]
I confirm this issue on Windows 10 (update april 2019).

Here are my services:
![image](https://user-images.githubusercontent.com/10001945/57360369-40e1cf00-717a-11e9-9173-1248cae8c971.png)

My system consumption:
![image](https://user-images.githubusercontent.com/10001945/57360400-5a831680-717a-11e9-97b1-93a69438c9ca.png)

Compare this to my 16 tabs on Brave Browser (Chromium based):
![image](https://user-images.githubusercontent.com/10001945/57360634-e5fca780-717a-11e9-94ba-99355df3e6b1.png)

Between Franz and my Browser there is a >x16 ratio in term of CPU consumption, and >x2 for my RAM.

**Comment by itsmeltc** [comment]
Frequently hogging tons of CPU here too, on a fresh macOS Mojave install. 10 services active:

3x Slack
1x Hangouts
1x Messenger
1x Telegram
1x Skype
1x LinkedIn
1x Discord

macOS Mojave 10.14.4 (18E226)
Franz 5.1.0 (5.1.0.1337)

```
  PID USER      PRI  NI  VIRT   RES S CPU% MEM%   TIME+  Command
 1623 lee.cherr  17   0 6253M 96788 ? 40.9  0.6  5:41.88 /Applications/Franz.app/...
 1622 lee.cherr  17   0 6164M  133M ? 12.5  0.8  2:24.27 /Applications/Franz.app/...
 1642 lee.cherr  17   0 16.2G  309M ? 10.6  1.9  1:36.94 /Applications/Franz.app/...
 1640 lee.cherr  24   0 15.0G  196M ?  7.5  1.2  1:14.43 /Applications/Franz.app/...
 1646 lee.cherr  17   0 16.3G  209M ?  7.0  1.3  1:09.88 /Applications/Franz.app/...
 1632 lee.cherr  17   0 15.9G  121M ?  0.5  0.7  0:07.57 /Applications/Franz.app/...
 1625 lee.cherr  24   0 4803M  126M ?  0.4  0.8  0:15.50 /Applications/Franz.app/...
 1636 lee.cherr  17   0 18.0G  135M ?  0.2  0.8  0:12.45 /Applications/Franz.app/...
 1644 lee.cherr   8   0 16.1G  248M ?  0.2  1.5  0:42.82 /Applications/Franz.app/...
 1630 lee.cherr  17   0 15.7G  132M ?  0.1  0.8  0:05.02 /Applications/Franz.app/...
 1628 lee.cherr  24   0 16.3G  423M ?  0.1  2.6  1:51.57 /Applications/Franz.app/...
 1634 lee.cherr  24   0 15.7G  120M ?  0.1  0.7  0:05.11 /Applications/Franz.app/...
 1657 lee.cherr  24   0 15.9G  176M ?  0.1  1.1  0:09.22 /Applications/Franz.app/...
 1649 lee.cherr   8   0 4816M 39808 ?  0.0  0.2  0:00.56 /Applications/Franz.app/...```

**Comment by vistalba** [comment]
Same here on Win10 19H1 with Version 0.5.1 uf Franz.
It looks like there is some issue with the services connected in Franz that are in background.
In my slack channel are very much emojis with animations. If i switch the channel on slack the CPU load of Franz is going down to a much lower level.

**Comment by edmundlaugasson** [comment]
Having same issue when Franz 5.2.0 beta 4 is installed as .deb package in 64-bit Linux Mint 19.1 MATE. Using VirtualBox VM to run Franz and this VM continuously consuming 180....200% of CPUs of my 8-core i7.

**Comment by edmundlaugasson** [comment]
With 5.2.0 final it seems a bit better but still overwhelming to computer and soon or later I need to close Franz in order to save my laptop of overheating.

**Comment by spi43984** [comment]
Just checked Franz 5.5.0-beta3. Power consuption on notebook increased by around 5-8 Watts when Franz with 11 services gets launched.
