### ISSUE TITLE
Adding custom CSS to existing Franz recipes?

### ISSUE THREAD

**Issue by Linkandzelda** [meetfranz/franz#268]
I'm following the recipe API guide and added the following line to the standard messenger recipe.

`Franz.injectCSS(path.join(__dirname, 'service.css'));`

In the same directory I've got that service.css file which is a custom dark theme for Messenger that works via Stylish plugin. 

How can I get this CSS file working?
See the InjectCSS function here: https://github.com/meetfranz/plugins/blob/master/docs/frontend_api.md#user-content-injectcss

**Comment by bfayers** [comment]
Did you get this to work @Linkandzelda  ?
