### ISSUE TITLE
Could we re-run the import ( for v4 services ) from the app (v5) ?

### ISSUE THREAD

**Issue by gabriel-kaam** [meetfranz/franz#27]
### Feature Description

Hey there,

Would it be possible to re-run the importer for old (v4) services from the app (v5) ?
Currently the importer is automatically ran when we launch the v5 app for the first time.

### Motivation and Context
I just upgraded from v4 to v5 , when the importer showed up, I accenditely skipped it, so had to manually re-create all my services... 

### Mockups, Screenshots (if available):

Haha, if I could i would, but the importer only showed up once :)

**Comment by marcossantiago** [comment]
+1 as just happened to me.

**Comment by kidpixo** [comment]
+1 here too, I clicked "yes" but the v5 has no account configured.

**Comment by peroksid5** [comment]
I actually selected all accounts, but still no import happened, have to add services from scratch.

**Comment by wmcheung** [comment]
+1 here as well. None of my accounts got imported to v5

**Comment by adlk** [comment]
There was an issue with the initial public beta that has been fixed. The importer is now working as expected.

Re-running the importer is still on my backlog.
