### ISSUE TITLE
Franz shows twice in Notification Center.

### ISSUE THREAD

**Issue by Ivanveg** [meetfranz/franz#274]
It repeats two times in the notification center. I have a Macbook Pro using Sierra OS. It started since downloaded the v5 Beta. I wont be using Franz until this is fixed. Hope to see you guys in the future. It was a good run. Useful app tho.

### Screenshots (if appropriate):
![captura de pantalla 2017-11-14 a la s 14 35 12](https://user-images.githubusercontent.com/33666799/32795304-093e1bfa-c94a-11e7-815d-585edce68689.png)

### Your Environment

* Franz Version used: 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: 10.12.6

**Comment by adlk** [comment]
Sorry for asking this, but you definitely have just one Franz app running? (Not e.g. v4 and v5 parallel) 

Also, could you please complete the issue with the exact beta and macOS version? Thank you.

**Comment by Ivanveg** [comment]
Hello! Thanks for replying. Yes. I eliminated and reinstall Franz several times and still happens. I made sure i have only one version running, because that's what i thought at first too.

My current Franz version is Versión 5.0.0-beta.13 (5.0.0-beta.13.316). 
My current OS Sierra version is 10.12.6.

Hope that helps!
Thanks again!

**Comment by haraldox** [comment]
@Ivanveg Do you still experience the issue in 5.0.0-beta.15?
