### ISSUE TITLE
Remove blank line in macOS notifications 

### ISSUE THREAD

**Issue by tobiasdueser** [meetfranz/franz#275]
### Expected Behavior

No blank line between name and content (like the first notification in the screenshot)

### Current Behavior

Blank line. 

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/1573849/32795381-c3707ee8-c96b-11e7-8583-08ad94194438.png)

### Your Environment

* Franz Version used: beta-13
* Operating System and version: macOS 10.12.1

**Comment by adlk** [comment]
Is this happening on a a specific service or for all?

**Comment by tobiasdueser** [comment]
For all:

![image](https://user-images.githubusercontent.com/1573849/32803978-a1877646-c985-11e7-8afc-5def4981ca1b.png)

**Comment by haraldox** [comment]
this is the case only in notification center, not with live notifications where there is no blank line.
