### ISSUE TITLE
Can't download attachment images on Skype - gives me an empty file

### ISSUE THREAD

**Issue by entreprenewer** [meetfranz/franz#281]
### Expected Behavior
Should download the file, like on the Skype desktop client 

### Current Behavior
Downloads a blank file (see screenshot)
Also, can't paste images from clipboard into Skype

### Screenshots (if appropriate):
<img width="422" alt="screen shot 2017-11-15 at 10 24 18" src="https://user-images.githubusercontent.com/1540530/32825950-5551b402-c9ef-11e7-91a8-0515c5b8be36.png">

### Steps to Reproduce (for bugs)
1. Have someone send you an image on Skype
2. Try to download it, Safari opens, file downloads
3. See blank file
4. Cry and open up Skype desktop app just to download this one file.

### Your Environment

* Franz Version used: Latest
* Operating System and version: OSX 10.13

**Comment by BrianGilbert** [comment]
@entreprenewer if the download is done by your default browser I'd assume that it's not authenticated with your skype account, therefore when trying to download the file you are prohibited from accessing it, can you please confirm?

Log into skype in your default browser, then try to download file from link in franz, if it works this is a browser auth issue that can't be resolved by franz.

**Comment by BrianGilbert** [comment]
If my ptrevious comment does not resolve the issue for you please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins

**Comment by mikehapner** [comment]
woks!
