### ISSUE TITLE
Dragging a background should do nothing

### ISSUE THREAD

**Issue by deseven** [meetfranz/franz#283]
### Expected Behavior

Nothing should happen if i try to drag the background.

### Current Behavior

Last selected service is starting to move. Also, after the drag operation focus switches to a previously selected service.  
Details on video - http://eri.deseven.info/share/franz_dragging.mp4

### Steps to Reproduce (for bugs)

1. Select any service.
2. Drag the background below services buttons.

### Your Environment

* Franz Version used: 5.0.0-beta.13.316
* Operating System and version: macOS 10.12.4

**Comment by adlk** [comment]
Great catch! Thanks for reporting!
