### ISSUE TITLE
Add shortcut to open Franz when window is closed or in background (e.g Cmd+0)

### ISSUE THREAD

**Issue by maexb** [meetfranz/franz#284]
After closing the main window it can't be reopened

### Possible Solution
Create command to reopen closed main window in menu

### Steps to Reproduce (for bugs)

1. Open Franz
2. Close Main Window (Cmd + W)
3. Franz App still running, try to reopen window
4. Not possible, only by quiting and reopening whole app

### Your Environment
* Franz Version used: 5.0.0
* Operating System and version: Mac OS 10.11.6

**Comment by adlk** [comment]
Thanks for reporting this. How do you try to reopen the app?

**Comment by maexb** [comment]
There seems to be no command available for this … check out screencast:
[franz.zip](https://github.com/meetfranz/franz/files/1474733/franz.zip)

**Comment by adlk** [comment]
What about the dock or system tray?

**Comment by maexb** [comment]
no window in the dock

**Comment by maexb** [comment]
aaah, by clicking on app symbol in dock window reoccurs. shortcut would be nice although. used to be Cmd + 1

**Comment by adlk** [comment]
From my experience, this isn't really a standard behaviour of macOS apps. In the future there will be an option to bring globally bring the Franz Window to the front.

**Comment by maexb** [comment]
Seems to be a standard behavior in Mail and Messages with Cmd + 0 … see screenshots. Anyway, thanks for the effort.

![messages](https://user-images.githubusercontent.com/33689971/32855089-169873ca-ca41-11e7-8658-a74a22e3a14f.png)
![mail](https://user-images.githubusercontent.com/33689971/32855090-16c66dac-ca41-11e7-8eed-48a90b0fbedd.png)

**Comment by adlk** [comment]
Interesting, thanks for the info. This is definitely something we can add. What is the situation on Windows and Linux?

**Comment by maexb** [comment]
You're welcome. And sorry, Mac knowledge only.

**Comment by tobiasdueser** [comment]
It would be nice if the service shortcuts (`cmd+1`  `cmd+2` `cmd+…`) would also open the window and jump directly to the appropriate service.

**Comment by adlk** [comment]
@maexb I just realized that Cmd+0 is already used to reset the zoom. I think using a global shortcut (#197) would be the best way. 

@tobiasdueser how often do you really use this?

**Comment by tobiasdueser** [comment]
@adlk Almost never, but it would be logical. I think it has a really low priority.

**Comment by alecive** [comment]
@tobiasdueser Moreover, that would be pretty bad in Linux when most people have their own custom keybindings and this feature would stomp on their feet.

**Comment by tobiasdueser** [comment]
@alecive Sorry, I should have mentioned that I'm just talking about macOS and I'm not talking about global shortcuts - just when the Franz window is closed but the application isn't. I habe no idea how Linux works in that regard.

**Comment by bwidemann** [comment]
It would be better to avoid using numbers for key shortcuts, simply because they do not work on keyboards such as the French layout, where typing a number requires pressing the `shift` key. They would work, of course, on keyboards with numeric keypads, but this excludes a lot of computers nowadays. 

So, to reopen the main window, I would suggest `cmd-N` as a better solution, like the Finder. Mail and Messages are wrong. :)

`Add New Service…` could adequately move to `cmd-shift-N`, or even to `cmd-O`, considering that it "opens" a service, it does not actually "creates" it. 

FWIW... Thanks for a great product anyway!

**Comment by adlk** [comment]
@bwidemann thanks for the info! You definitely saved a lot of new issues :)
It is actually a shame to see that apple is becoming more and more inconsistent with it's apps.

`microRant = off`

I think we should use <kbd>Cmd</kbd>+<kbd>n</kbd> and rewire "Add a new service" to <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>n</kbd>.

<kbd>Cmd</kbd>+<kbd>0</kbd> is already in use for resetting the service zoom.

I'm currently busy with working on GDPR related issues, If anyone wants to help me on this one then we might be able to ship this with beta 15.

**Comment by brendanjones** [comment]
Off-topic: GDPR. Have fun with that! As a consumer, I fucking love it; as a SaaS product owner, AHHHHHHH FUUUUUUCK. I feel your pain.
