### ISSUE TITLE
Needs an android client

### ISSUE THREAD

**Issue by siparker** [meetfranz/franz#285]
This would be incredible as an android client for a lot of people who are on the go.

I struggle to keep on top of all the chat clients and platforms like Disa have got part way there but are not completely finished.

Franz as an android app.

### Motivation and Context
Android seems to be a next logical step for this platform...
I would use this on a daily basis both for my own business and have at least 3 clients hwo would benefit greatly from it.

**Comment by adlk** [comment]
It would indeed be nice, this is however the wrong place as this is the issue tracker for the desktop app.

We don't have any plans to move towards mobile. From a technical standpoint alone it would be an endless nightmare to bring an usable experience to mobile.

**Comment by siparker** [comment]
fair enough.
