### ISSUE TITLE
The application constanly closes without notification and error message.

### ISSUE THREAD

**Issue by jgimeno** [meetfranz/franz#286]
### Expected Behavior
It happens randomly and without any alert, I just noticed it some days ago.

### Current Behavior
It should at least show an error message that something has happened.

### Screenshots (if appropriate):
What I have is a log of the crash that says this:
`Process:               Franz Helper [25390]
Path:                  /Applications/Franz.app/Contents/Frameworks/Franz Helper.app/Contents/MacOS/Franz Helper
Identifier:            Franz Helper
Parent Process:        Franz [198]
Responsible:           Franz Helper [25390]
    __TEXT                 0000000101185000-0000000101186000 [    4K] r-x/rwx SM=COW  c [/Applications/Franz.app/Contents/Frameworks/Franz Helper.app/Contents/MacOS/Franz Helper]
41  com.electron.franz.helper     	0x0000000101185f26 main + 38
       0x101185000 -        0x101185ff7 +com.electron.franz.helper (0) <4CF9CEEE-ED51-3CFB-8C00-D1C780250227> /Applications/Franz.app/Contents/Frameworks/Franz Helper.app/Contents/MacOS/Franz Helper
       0x10118a000 -        0x1011a4fff +com.github.Squirrel (1.0 - 1) <0A9F60FF-F2D2-364A-962A-65137E68760E> /Applications/Franz.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x101269000 -        0x1051cef53 +com.github.electron.framework (0) <077F6FDF-9D71-317F-B1F2-1E49A6846EA3> /Applications/Franz.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x105805000 -        0x105868ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Franz.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x1058df000 -        0x1058f3fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Franz.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x105908000 -        0x10681afff +libnode.dylib (0) <E190A1BE-9E30-37BC-B707-3516EF6CD32C> /Applications/Franz.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
       0x106ae7000 -        0x106d4bfef +libffmpeg.dylib (0) <C6D0AEFA-0122-35FA-8EDE-369DCD7E9304> /Applications/Franz.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
`

### Your Environment

* Franz Version used: 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: macOs 10.13.1

**Comment by haraldox** [comment]
@jgimeno Do you still experience the issue in 5.0.0-beta.15?
