### ISSUE TITLE
I have a new whatsapp phone number and Franz is no longer responding to my phone for whatsapp

### ISSUE THREAD

**Issue by blackjack77** [meetfranz/franz#287]
I have a new phone number associated with my whatsapp and franz whatsapp client is no longer responding to my phone.  Any tips greatly appreciated

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by jonhil** [comment]
This problem has nothing do to with Franz!
You have to reconnect your Whatsapp webclient to your Whatsapp app running on your phone.

**Comment by blackjack77** [comment]
Got it.  Many thanks :)
