### ISSUE TITLE
Custom icon upload

### ISSUE THREAD

**Issue by ygrange** [meetfranz/franz#291]
I have Franz running with a bunch of slack chanels. Most of those have configured a team icon, and for those the team icon nicely appears in the side bar. However three of my teams did not configure an icon. In the Slack app, those are basically given the first letters as an icon so that I can distinguish them. It seems like Franz doesn't do that and now I have three the same icons, which will for sure lead to some confusion. 

### Expected Behavior
If the slack channel is called "Myslack", then I believe the Icon should be a capital "M". If the name is "My Chanel" it would probably be "MC"; essentially following what Slack does.

### Current Behavior
It just shows the Slack application logo

### Screenshots (if appropriate):
<img width="52" alt="screen shot 2017-11-16 at 23 18 25" src="https://user-images.githubusercontent.com/6578686/32918981-89a2fc76-cb24-11e7-8936-96e25bf5ac9e.png">

### Your Environment

* Franz Version used: 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: OSX 10.12.6

**Comment by adlk** [comment]
I'm working on a custom icon upload for all services.

**Comment by ygrange** [comment]
Fantastic! I can’t wait to see this feature coming.

Thanks.


> Op 16 nov. 2017 om 23:21 heeft Stefan Malzner
<notifications@github.com> het volgende geschreven:

**Comment by haraldox** [comment]
@ygrange there is a custom icon facility for slack in settings, does that solve your problem?

**Comment by ygrange** [comment]
Yeah that works for me (if at some point there could be some default icons to chose from, that'd make it even easier, but this surely is great!). Thanks!
