### ISSUE TITLE
Vkontakte

### ISSUE THREAD

**Issue by Krivonozhki** [meetfranz/franz#292]
Why did you remove service Vkontakte from Franz?

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](http://bit.ly/franz-service-request) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by Krivonozhki** [comment]
I am not requesting service. I'm just curiouse why the service has  been removed.
