### ISSUE TITLE
Missing translation (updater)

### ISSUE THREAD

**Issue by mroeling** [meetfranz/franz#293]
There is a automatic notification when the updater encounters a problem. 

### Expected Behavior
The notification should be translated into the selected language

### Current Behavior
The notification is in English
`
We have experienced issues with our updater. Please follow _ the instructions _ to fix the issue.
`

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/2706186/32946837-7843e61e-cb99-11e7-8b57-7e34bf790dbc.png)

### Possible Solution
Please add the string in the code as translatable (if not already), and add it to Pootle to let the community edit the string in there language.

### Your Environment
* Franz Version used: 5.0.0-beta.12
* Operating System and version: Kubuntu 17.10

**Comment by adlk** [comment]
@mroeling Messages like this are coming from the API and are some kind of general/emergency notification system when I really need your attention or whenever I have messed things up really bad with e.g. the updater.

In almost every case, the text of the message is very specific that can't be planned/translated in advance and should _definitely_ not require an app update.
