### ISSUE TITLE
Jivochat

### ISSUE THREAD

**Issue by AugustoResende** [meetfranz/franz#295]
Add Jivochat to franz. (Google Form is not working)

**Comment by adlk** [comment]
What's the issue with the Google Form? I did a quick check and everything seems fine.
https://goo.gl/forms/cHiqxGA6b2EVSLXx2

**Comment by edmargomes** [comment]
https://github.com/nyxtechnology/franz-recipe-jivochat

@adlk Do you can check the code to add in the Franz services?
