### ISSUE TITLE
Sounds not deactivated for Muted Whatsapp Group Chats

### ISSUE THREAD

**Issue by davbud** [meetfranz/franz#296]
Using Franz 5.0.0-beta.13 (5.0.0-beta.13.316) on Mac OS X 10.12.6 but have had this problem ever since using Franz. 

### Context
Muted conversations in whatsapp still make loud notification noises. 

### Your Environment

* Franz Version used: 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: Mac OS X 10.12.6

**Comment by adlk** [comment]
Audio Notifications and Notifications are two separate things in Franz. We will introduce the option to mute audio notifications with beta 14.
