### ISSUE TITLE
Hangout's Google Voice features not working in Franz 5.0.0-beta10

### ISSUE THREAD

**Issue by gcarrion-gfrmedia** [meetfranz/franz#30]
Hi!

First, congratulations on the new Franz. So happy that is back with a new version.

Wanted to report that the Google Voice features in Hangouts are not working on the latest Franz.

These features are the ability to make and receive Google Voice calls right in Hangouts. 

### Expected Behavior
Whenever I click the Phone Call icon, the left contact bar is supposed to change to the contact lists and search for contacts to make a new call. 

Also, whenever I receive a call to my Google Voice number, the call should appear in Hangouts with notification and sound.

### Current Behavior
Whenever I click the Phone Call icon, the left contact says "Loading contacts..." but nothing happens. Unable to make a call.

Whenever I receive a new call, unlike in the regular browser, in Franz no notification or sound appears on the Hangouts window.

### Screenshots (if appropriate):
This is what happens when I try to make a call in Franz:

![Image](http://i.prntscr.com/GpuBeej7Tjabcflei0U2Ug.png)

This is what is supposed to appear:

![image](http://i.prntscr.com/v5qk88DnQCOVw1g_eNJUaw.png)

This is what's supposed to appear when I receive a call to my Google Voice number in Hangouts:

![image](http://i.prntscr.com/q8XuvuOLSCe9040Tb_Xkow.png)

But in Franz, the call does not come in. It never rings or shows any notification.

![image](http://i.prntscr.com/kt4tuH7JRYKCNIqEp7I0tw.png)

### Steps to Reproduce (for bugs)
1. Make sure to have a Google Voice number or at least be in a US/Canada IP location to be able to see the Voice Calling features.
2. Try to make or receive a call (to the GV number)
3. Notice that nothing happens on Franz, but if tried on the browser it does

### Context
Trying to make/receive calls to Google Voice number with Hangouts don't work.

### Your Environment
* Franz Version used: 5.0.0-beta10
* Operating System and version: Mac OS Sierra 10.12.6

![image](http://i.prntscr.com/3K9deWa9QI2ObHV704AzlA.png)

**Comment by adlk** [comment]
It kind of breaks my heart to close such a well described issue. However this is the wrong place. Please use the recipe repositories for better handling. 
www.github.com/meetfranz/recipe-hangouts

I've copy & pasted your issue.

**Comment by heavypackets** [comment]
This behavior appears to be a result of the disabling of web security in the Electron web view controls. I detailed the specific behavior in https://github.com/meetfranz/recipe-hangouts/issues/5. Same-origin policy is required for many parts of Google's internal API to function.

I re-enabled web security in the web view settings, and Hangouts functions correctly.

**Comment by gcarrion-gfrmedia** [comment]
That's awesome @heavypackets! Thanks! Hopefully, in the next version of Franz, we can have Hangouts and Google Voice features working again. cc. @adlk
