### ISSUE TITLE
Conflict between app command and Romanian programmer keyboard combinations

### ISSUE THREAD

**Issue by barbalata** [meetfranz/franz#302]
### Expected Behavior
When I use the command shift+alt gr+I, I expect just to type "Î" (a Romanian letter).

### Current Behavior
When I type this combination I write the letter 'Î' and I open the "Toggle Developer Tools" in the same time.

### Possible Solution
You can use this combination to be default and, in toolbar, it can exist a menu where everyone can change the shortcuts.

### Steps to Reproduce (for bugs)
1. Set your keyboard at Romanian (Programmer) mode.
2. In every space where you can write text type the combination <b>shift + alt gr + I </b>.

### Context
I always write with the Romanian letters and this issue make me to write slow or exit from application when I type other letters when the Toggle Developer Tools is open and to open this tool when I don't want that...

### Your Environment
* Franz Version used: 5.0.0-beta.13
* Operating System and version: Windows 10 - 64x

**Comment by haraldox** [comment]
@barbalata this is hard to fix, since it's the standard keyboard shortcut for the developer tools ... i don't think that windows differenciates between 'alt' and 'alt gr' modifier keys and thus if it's possible in electron.

have you tried using a keyboard mapping tool like KeyTweak or SharpKeys?

**Comment by haraldox** [comment]
closing this for now, feel free to reopen with any questions or comments!
