### ISSUE TITLE
Glitch in window display after beta update

### ISSUE THREAD

**Issue by LloydBr** [meetfranz/franz#303]
After updating Franz the window of the app doesn't show the text/chat field, nor the scroll bar on the righthand side. This appears to be happening to all of the active apps I'm using in Franz. Does anyone know how to fix this, because now it is impossible to use the chat function?

### Screenshots (if appropriate):
![schermafbeelding 2017-11-19 om 11 59 20kopie](https://user-images.githubusercontent.com/33801300/32990036-e084d786-cd21-11e7-90a5-c7b696f6d480.jpg)

* Franz Version used: 5.0.0.-beta.13
* Operating System and version: Apple MacBook Pro 15". Sierra 10.12.6 (16G29)

**Comment by adlk** [comment]
What happens when you resize the window? Does it fix the glitch?

**Comment by jsiderman-mydevices** [comment]
@LloydBr Hi there, I'm also having this same issue. Resizing the window nor zooming in and out do not resolve this. Hope that helps!

**Comment by haraldox** [comment]
restarting seems to fix the issue ... closing this for now, feel free to reopen the issue with any questions or comments!
