### ISSUE TITLE
Black tray icon in Solus OS

### ISSUE THREAD

**Issue by Jannomag** [meetfranz/franz#304]
Hi,
I installed Franz 5.0.0-beta13 on my Solus OS 3.26.2 system.
Because .deb is not supported and I don't like AppImages I extracted the .deb and copied the contents for /opt/ into my /opt/ directoriy.

Franz works great, but the tray icon is black.
With 4.0.4 it was white.
First I thought the icon was missing, because the bar is dark, but then I got a new message and a red notification dot showed that there's an icon, but black.

**Comment by adlk** [comment]
I'm merging this into #233
