### ISSUE TITLE
cannot sign in

### ISSUE THREAD

**Issue by netalij** [meetfranz/franz#305]
I just updated to the version 5 beta
and i cannot reset my password - am not recognized for either of my 2 email addresses.
wha'ts going on . ?

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Have you created an account with Franz 5? If not, Franz 4 had no accounts and you need to create a new one.

**Comment by netalij** [comment]
this explains it!
Thanks
