### ISSUE TITLE
NIGHT THEME!!

### ISSUE THREAD

**Issue by condeccs** [meetfranz/franz#308]
### Feature Description

franz should have maybe not themes, since it would be more complicted, but a "night theme" with black or dark  background and white fonts o letters

### Motivation and Context
explained above
![franz negative](https://user-images.githubusercontent.com/33830932/33016201-f3a2c0a6-cdc3-11e7-90b9-8b053e40156d.jpg)

**Comment by adlk** [comment]
Duplicate of #49
