### ISSUE TITLE
No notification in Linux Mint (Franz V5)

### ISSUE THREAD

**Issue by MegaV0lt** [meetfranz/franz#309]
### Expected Behavior

When a new message comes through one of the activated service a notification should be sent to the system notification 

### Current Behavior
There is no notification popup at all. PS: Was working in 4.x

### Your Environment

* Franz Version used: 5 Beta 13
* Operating System and version: Linux Mint 18.2 Cinnamon

**Comment by uroybd** [comment]
Same in Gnome 3.24. Franz developers may consider using popup notification due to the fact that gnome is deprecating legacy tray/app indicator API. It's already buggy in Gnome 3.24 and going to be obsolete in 3.26.

**Comment by Valforte** [comment]
I'm using mint 18.2 and this issue is not present. All notifications show normally.

**Comment by MegaV0lt** [comment]
Franz Version? V4 was working, V5 not!

**Comment by ValforteLogComex** [comment]
I'm using Franz 5 beta 14, Mint 18.2 cinnamon. All notifications are fine.

**Comment by Valforte** [comment]
I'm using Franz 5 beta 14, Mint 18.2 cinnamon. All notifications are fine.

**Comment by adlk** [comment]
@uroybd can you please provide more information about the notification API changes?

**Comment by guedressel** [comment]
I've installed Franz 5 beta 14 on my Kubuntu 16.04. Don't get any notification popups too. Though the Franz Icon in the System Tray is here and gets a red dot if new messages arrive.

**Comment by JohannesBe** [comment]
Same problem on arch linux (Linux 4.16, 64 bit) with gnome 3.28 installed

**Comment by jamtur01** [comment]
Same issue Ubuntu 18.04 with Gnome 3.28.

**Comment by calcerrada** [comment]
Fedora 26 and  Franz v5 beta 18 have the same issue

**Comment by copitz** [comment]
Had the same issue (Linux Mint 18.3 Cinnamon, Franz 5.0.0-beta.18) - doing this solved it for me:
https://askubuntu.com/a/766779/768229

**Comment by wkoncki** [comment]
@adlk Is there a chance you could look into this? It really is a bummer to have no notification of new activity besides change to tray icon. Just to clarify, when I mean notification popups I mean those things:
![screenshot from 2019-02-17 13-30-34](https://user-images.githubusercontent.com/9073427/52912986-53561600-32b9-11e9-80e7-f56f925e7765.png)
This is a working example from standalone discord.
