### ISSUE TITLE
>100% CPU-usage by Franz Helper

### ISSUE THREAD

**Issue by Rvervuurt** [meetfranz/franz#314]
### Expected Behavior
Franz Helper should not use 100% CPU power

### Current Behavior
Franz Helper is using over 100% CPU power

### Screenshots (if appropriate):
<img src="https://i.imgur.com/px77tc7.png" />

### Steps to Reproduce (for bugs)
1. Turn on Franz
2. Add some services
3. ?
4. Profit

I have a suspicion that the miner is going crazy, but not sure it's specifically that.

### Context
My computer is slowing down to a crawl. Running Franz is really making it impossible to work properly on the machine and I feel compelled to turn it off and return to the web-based services for Slack etc.
It's not a slow computer, so running Franz should not get it to slow down to a crawl.

### Your environment
* Retina 5K iMac, late 2015
* Franz Version used: Version 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: MacOS Sierra 10.12.6

**Comment by adlk** [comment]
Just to make absolutely sure, have you activated the miner?

**Comment by Rvervuurt** [comment]
Yes! And it makes about ~12 calculations a second, sometimes up to 14.
If I cancel the miner, Franz's CPU usage falls to 10% (where it was 103% before I turned it off)
