### ISSUE TITLE
Click events are not recognized when using a Wacom tablet

### ISSUE THREAD

**Issue by margotgabel** [meetfranz/franz#315]
### Expected Behavior
Clicking on stuff should work with a tablet.

### Current Behavior
Clicking on a service works but not within a service.

I suspect something going on with the Wacom driver.. (latest version)

### Steps to Reproduce (for bugs)
1. Plug your Wacom Intuos Pro and open Franz.
2. Click on a service (this works)
3. Click on a link/button within a service (does not work..)

### Your Environment
* Franz Version used: 5.0.0-beta. 13
* Operating System and version: macOS 10.13.1

**Comment by haraldox** [comment]
@margotgabel Do you still experience the issue in 5.0.0-beta.15?

**Comment by basvanbergen** [comment]
I know this issue is closed but as of late, I'm experiencing the same problem. The plugin/service part of Franz does not register my wacom clicks. Currently I'm on Franz: (5.0.0-beta.17.834) and OSX 10.11.6
