### ISSUE TITLE
No mute option for new Franz version

### ISSUE THREAD

**Issue by akspablo** [meetfranz/franz#316]
Hey guys, how are you?

First of all, congrats to Stefan.

Well, on the previous Franz version (4) we had the option to mute all the sounds, but on the 5, we don't have it. Is it possible it?

* Franz Version used: Version 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: MacOS High Sierra Version 10.13.1

Thanks Stefan!

**Comment by adlk** [comment]
Already resolved in #252 and will be shipped with beta 14
