### ISSUE TITLE
Gitter does not save login credentials

### ISSUE THREAD

**Issue by danielbayley** [meetfranz/franz#322]
### Expected Behavior
The Gitter service should remain logged in between Franz restarts.

### Current Behavior
I have to log in again every time Franz is restarted.

### Your Environment
* Franz Version used: 5.0.0-beta.13
* Operating System and version: macOS High Sierra 10.13.1

**Comment by adlk** [comment]
The recipe points towards `gitter.im/login` which is great as an entry point.
Unlike many other services, they just display the login _even_ when the user is logged in. I've updated the recipe to point to `gitter.com`. After updating the recipe and a Franz reload you should be permanently signed in into gitter.
