### ISSUE TITLE
cannot setup for custom rocket chat server with "www" in subdomain

### ISSUE THREAD

**Issue by BeneStem** [meetfranz/franz#325]
Hey there,

when setting up a custom rocket chat server for example **https://www.custom.chat** franz changes the url to **https://custom.chat** and then validates the url.
Which will not work, when the url is not reachable without _www_.

I tried to trick the url validation into always returning "true" in the rocket chat recipe but franz will still change the url by removing _www_.
Now I can at least setup the account but the web view won't load because of the changed url...

Please fix.

Greetings,
ben

**Comment by BeneStem** [comment]
I found the corresponding code that causes the error:

https://github.com/meetfranz/franz/blob/master/src/components/settings/services/EditServiceForm.js#L6

https://github.com/meetfranz/franz/blob/master/src/components/settings/services/EditServiceForm.js#L113

Per default 'normalize-url' stripsWWW:
https://www.npmjs.com/package/normalize-url#stripwww

This option needs to be disabled!

Greetings,
ben

**Comment by BeneStem** [comment]
Ok, got it. My suggested fix is the correct one.

I was able to modify the normalize-url index.js in node_modules within chrome developer console in the electron app.

Changed stripsWWW to false and saved the working url.

Not exactly user friendly but it did the trick :P

**Comment by adlk** [comment]
Thanks for investigating this issue. Would you mind opening a PR for this?

**Comment by BeneStem** [comment]
@adlk sure, can do that.

But there is another issue. After restarting franz the custom rocket chat service's window isn't loaded... :(

Removing and adding it back in again with my trick makes the window load again.
but of course all state is lost...

Not sure wether this has to do with the custom url or some other stuff.
Was not able to find a solution yet :(

**Comment by BeneStem** [comment]
Ok, I got some clues...

Somehow franz is removing the _www_ again after restaring the app.
Although no settings are changed...

The webview's src url contains the old url without _www_.

Maybe there are other places where _normalize-url_ is used.

**Comment by BeneStem** [comment]
And I found it in the code :D

https://github.com/meetfranz/franz/blob/84bff14bf649969b3729b2c751b423d33e508f0b/src/models/Service.js#L63

Will open a PR as soon as possible :)

Greetings,
ben

**Comment by BeneStem** [comment]
And the PR arrived ;)

**Comment by adlk** [comment]
Great, thank you so much for your contribution. Your PR is merged and since I need to debug some other stuff it will make it into with beta 14. 🎉

**Comment by BeneStem** [comment]
Yay. Great! Thank you so much too :)

I got really fond of Franz. Can‘t live without it anymore ;)
