### ISSUE TITLE
Todoist doesn't keep the session open after restarting Franz

### ISSUE THREAD

**Issue by noubit** [meetfranz/franz#326]
Hello. 

In Franz 5 beta13, todoist closes after restarting the app (after shut down Windows, or simply closing and reopening the app). Like in the web browser, I think the session must keep open. Don't know if it's a cookie issue, but the session closes. I'm logging in with a Google ID.
Thanks!

* Franz Version used: Franz 5 beta 13
* Operating System and version: Windows 10 x64 (autumn creators update)

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
