### ISSUE TITLE
Unable to use Wire webapp

### ISSUE THREAD

**Issue by magicalraccoon** [meetfranz/franz#328]
After opening a Wire tab, there is an error saying

> This browser is not supported.
> Download the latest version of Google Chrome, Mozilla Firefox, Opera or MS Edge. Wire for macOS and Microsoft Windows are available from get.wire.com.

### Expected Behavior
The wire webapp should work without error.

### Current Behavior
Wire throws an error while trying to use the webapp.

### Steps to Reproduce (for bugs)

1. Open a new Wire tab
2. Try to use the client.

### Your Environment

* Franz Version used: 4.04 build 40 release 1.3.1 / linux / x64
* Operating System and version: Fedora 27, x64

**Comment by adlk** [comment]
Wire has a very restrictive way to check the chrome version (and push their electron app). We have contacted them about a proper solution. 

Also: Franz 4 is no longer supported. Please upgrade to Franz 5 on www.meetfranz.com

**Comment by Intelli** [comment]
Wire still isn't supported in Franz, but works fine in other products similar to Franz (e.g. Rambox).

Supposedly Wire reached out to you guys, but hasn't heard back: https://twitter.com/wire/status/855147781035610114

Is there currently an ETA for fixing Wire support?

**Comment by Intelli** [comment]
Wire still isn't supported in Franz, but works fine in other products similar to Franz (e.g. Rambox).

Supposedly Wire reached out to you guys, but hasn't heard back: https://twitter.com/wire/status/855147781035610114

Is there currently an ETA for fixing Wire support? @adlk

**Comment by Intelli** [comment]
More information on the Franz issue is also listed here: https://github.com/wireapp/wire-webapp/issues/1209#issuecomment-300717950
