### ISSUE TITLE
Franz keeps loading zoomed all the way out

### ISSUE THREAD

**Issue by htkoca** [meetfranz/franz#332]
### Expected Behavior
Service and App UI to render at the same size as the browser.

### Current Behavior
Both browser and Franz is set to 100%, but Franz renders noticeably smaller (about 2x)

### Screenshots (if appropriate):
![screen shot 2017-11-23 at 11 15 30 am](https://user-images.githubusercontent.com/4338187/33181848-b1aeaa56-d03f-11e7-9a95-a658db644308.png)

### Possible Solution
Related to DPI settings or default electron properties?

### Steps to Reproduce (for bugs)
1. See screenshot.
2. Open Chrome and Franz.
3. Set both zoom levels in menubar to 100%.
3. Compare.

### Context
Services most importantly renders incorrectly due to this zoom level. This behaviour seemed to begin after I accidentally pressed some keyboard combination (I think). A good example is Trello. 

### Your Environment
* Franz Version used: Version 5.0.0-beta.13 (5.0.0-beta.13.316)
* Operating System and version: MacOS Sierra 10.12.6 (16G1036)
* Currently on Macbook 13" 2016, Touchbar.

**Comment by htkoca** [comment]
I seemed to have "resolved" this issue by the following steps: 
1. Clicking on the services bar 
2. Menubar > View > Actual Size

Perhaps make this a bit more accessible to the user? Unified UI <> Service zoom level would be great

**Comment by BrianGilbert** [comment]
You'd likely hit CMD and -/+

**Comment by sritampatnaik** [comment]
<kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>+</kbd> worked for me
