### ISSUE TITLE
Telegram groups messages show in Franz as "unread" even though I have notifications from them off.

### ISSUE THREAD

**Issue by AugustoResende** [meetfranz/franz#335]
Telegram groups messages show in Franz as "unread" even though I have notifications from them off.

**Comment by AGonLen** [comment]
I also noticed the same issue with Telegram.
+ Spell check is not working in Telegram.

Franz Version used: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

**Comment by adlk** [comment]
Please report service issues for telegram here: [Telegram Recipe Repository](https://github.com/meetfranz/recipe-telegram)

**Comment by AugustoResende** [comment]
Is Franz bug, not telegram bug

**Comment by AugustoResende** [comment]
@adlk Telegram groups messages show in Franz as "unread" even though I have notifications from them off.

FROM FRANZ SETTINGS...

**Comment by adlk** [comment]
yes, but Franz is split in the client (the app) and recipes (telegram, whatsapp, ...)

However, I did a check today and telegram does not display any info (we can work with) if the conversation is muted. This means that we will not be able to disable the new message badge for muted conversations.

**Comment by AugustoResende** [comment]
I have disabled ALL NOTIFICATIONS, on Franz "recipe" setting
