### ISSUE TITLE
Google Contacts Will Not Load - Hangouts and Gmail

### ISSUE THREAD

**Issue by dmkroslindale** [meetfranz/franz#336]
Franz Ver 5.0.0. -beta 13
Microsoft Windows 10 Home X64
Windows Version  10.0.15063 Build 15063

Google Contact List will not load or display in Hangouts or Gmail apps.

After creating a Google Hangouts Account as well as a Gmail Account and logging in to each, Franz gives me the web interface as expected.  However after logging in it will not load the contacts list for either Google app.

The Hangouts account appears to be searching for recent hangouts conversations, and it also appears to be locating people that have Hangouts connected, however it will not allow me to send a message to someone else using the Contact List.  When you select an option that seeks to load the Contact list so you can choose someone to message, all you get is a spinning wheel.  Since it cannot see the Contact list, it also cannot compare an address if you type-in a valid mail address or telephone number you know is in the address book.

When connecting to the Gmail account the web interface does display the available INBOX and other mail box types and you can view the various mail boxes and apparently reply to a message.  You can start a new message and start typing an e-mail address and you will see pop-up suggestions from the address book.  However, clicking on the "CONTACTS" option brings up a blank FRANZ window and nothing else happens.

The Contact List should be accessible to both apps.

In the Hangouts app Since the Contact List will not display you cannot select someone to send a text message to, or an Invite.

In the Gmail app you cannot make the web interface for Gmail (within Franz) fully functional without a workaround.

**Comment by AGonLen** [comment]
On GMail, for the contacts it opens a blank window but does not populate with the GMail contacts.

Franz Version used: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

See screenshot:

![franz_issue6](https://user-images.githubusercontent.com/24992203/33209049-69d28baa-d114-11e7-8f6a-b4f29ae43ddd.JPG)

**Comment by dmkroslindale** [comment]
This is correct.

Under the Gmail option clicking on contacts creates this blank pop-up 
page and it does not populate as expected.

Under the Hangouts option if you click on the Phone option it brings up 
a small window similar to that one would expect in a web browser, but 
all you get is a spinning wheel.

So both Google options cannot access the contacts list.

That said... when using the Gmail option and starting a new mail 
message, if you start to populate the "TO" field it _will_ offer 
suggestions from the Contact list.

Contacts is a separate page at Google and often opens in a new tab.  You 
may need to look at what URL is being called and if it is dependent on 
the cookie set that gives the browser username and password access to 
allow it to be displayed.

I like this application and hope the small issues can be worked out.  I 
would also highly encourage a Portable version.

DMK

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
[gmail recipe repository](https://github.com/meetfranz/recipe-gmail)
