### ISSUE TITLE
Services in folders

### ISSUE THREAD

**Issue by Wouter0100** [meetfranz/franz#338]
A feature request or RFC regarding organizing the services. After thinking how I could probably organize (a lot) of Slack instances, I considered folders. Like Android or iOS, where you can create folders and place apps within those folders.

This could be useful for services you don't frequently use, for example FOSS Slack's or other chat environments. How those should be managed with shortcuts, I'm not sure. This is for debate. :)

**Comment by adlk** [comment]
We already have an open feature request for this one. Merging this issue into #243
