### ISSUE TITLE
Issue with text tags in all the application

### ISSUE THREAD

**Issue by AGonLen** [meetfranz/franz#341]
Hi,
I've upgraded from Beta 13 to Beta 14, directly from the application, using the "Check for updates" button.
See what happened with all the text tags has an initial "!!!".

See screenshots attached.

Franz Version used when wrote message: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

![franz_issue2](https://user-images.githubusercontent.com/24992203/33207917-dd123c0a-d10f-11e7-913d-920482a6e972.JPG)
![franz_issue3](https://user-images.githubusercontent.com/24992203/33207921-dfa439dc-d10f-11e7-8fbd-f2f4a1d73029.JPG)
![franz_issue](https://user-images.githubusercontent.com/24992203/33207926-e17ef01c-d10f-11e7-9f7c-ab52be407ee9.JPG)

**Comment by adlk** [comment]
Ah this might be an issue with the language restructuring. Can you please try to set your language again?

**Comment by AGonLen** [comment]
Could it be because you don't have Spanish language (my system language) in your list of available languages in Franz?
![franz_issue4](https://user-images.githubusercontent.com/24992203/33208529-3617f860-d112-11e7-84b0-ee30a701893b.JPG)

**Comment by AGonLen** [comment]
I changed to a different language, and then back to English (as there's no Spanish available) and now it looks fine...
![franz_issue5](https://user-images.githubusercontent.com/24992203/33208561-5634c88a-d112-11e7-87c8-89c0730f0fd3.JPG)

**Comment by adlk** [comment]
Oh yes, thank you for pointing this out. Seems like Spanish slipped through.

**Comment by AGonLen** [comment]
No, thank you for your great and helpful application!
Can live with English language, no worries.... At least the spellcheck is working (in Spanish only for now, I mean).

**Comment by haraldox** [comment]
Fixed in 5.0.0-beta.15
