### ISSUE TITLE
Disable all notifications

### ISSUE THREAD

**Issue by AGonLen** [meetfranz/franz#344]
Is there a way (and ideally also a key shortcut) to disable notifications from all services or you have to go one by one manually disabling them?

Same as as the Disable Audio button, there could be one to Disable All Notifications.

Franz Version used: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

**Comment by adlk** [comment]
Not yet, but I'm actually planning to merge mute all notifications and mute sound into one (the bell icon)

**Comment by andermurias** [comment]
I would really appreciate if you could also disable the red dot in Mac OS, it's a bit annoying that once the notifications are disabled, I still have the red dot appearing 😢 

Anyway, nice work you have done with franz!

**Comment by adlk** [comment]
@andermurias this is a very opinionated approach to disabling notifications. I think the best option would be to provide an appearance option to hide/show the badge when a service is muted.

**Comment by haraldox** [comment]
mute all notifications and mute sound are merged and implemented in the latest version of Franz 5.0.0-beta.15! closing
