### ISSUE TITLE
Telegram stickers and images don't show since moved to v5

### ISSUE THREAD

**Issue by PashaKagan** [meetfranz/franz#345]
### Expected Behavior
Images and stickers should appear, as they did before, and as they still do in other services in Franz.

### Current Behavior
I see an empty frame where the image or sticker are supposed to be.

### Steps to Reproduce (for bugs)
Well, just being sent an image or a sticker.

### Your Environment

* Franz Version used: 5 beta 14
* Operating System and version: W10 x64

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
[telegram recipe repository](https://github.com/meetfranz/recipe-telegram)
