### ISSUE TITLE
Double notification sounds on Windows 10

### ISSUE THREAD

**Issue by cypressious** [meetfranz/franz#346]
### Expected Behavior
When receiving a message, e.g. in Telegram, I expect to hear a notification sound.

### Current Behavior
There are two overlapping sounds, once the original Telegram sound and one generic Windows notification sound.

### Your Environment

* Franz Version used: 5.0.0.beta 14
* Operating System and version: Windows 10 64 bit

**Comment by adlk** [comment]
Is this just happening with telegram?

**Comment by cypressious** [comment]
I think Twitter too.

**Comment by adlk** [comment]
I've found a missing configuration flag in the telegram and tweetdeck recipe. The update is deployed and you will be prompted soon with a message like "your services have been updated"
