### ISSUE TITLE
Quick services toggling or profiles

### ISSUE THREAD

**Issue by edgarjrg** [meetfranz/franz#347]
### Feature Description

Profiles or Quick enabling toggling of services
### Motivation and Context

**Why is this change required?**

I use Franz for work and personal accounts, but its not easy to toggle a group of services.

With the old versions the service was disable and grayed out or in the menu with an accessible toggle interface and help me quickly disable and enable all, with the new version i can disable by left clicking but the enabling is done with too many clicks, and its complicated to apply multiple times as i have to go into _Settings->Your Services_ and _Service->Enable->Save service_ * service i want to enable.

**How is this improving the Franz experience?**
Enabling quick toggling between environments 

### Mockups, Screenshots (if available):

Current behavior:
disabling
![image](https://user-images.githubusercontent.com/10213241/33226497-ff16f242-d16d-11e7-873f-b78cbd348c8d.png)
Service disappears
![image](https://user-images.githubusercontent.com/10213241/33226498-0c8100a8-d16e-11e7-8e12-c9658d1d2757.png)

**Comment by dannyqiu** [comment]
This issue is addressed in Beta 14, where disabled services still show on the sidebar.

<img width="220" alt="screen shot 2017-11-26 at 3 35 26 pm" src="https://user-images.githubusercontent.com/1170755/33244117-88e3a572-d2bf-11e7-9ed4-b045c39f8f61.png">

**Comment by adlk** [comment]
I'm merging the other discussion (profiles) into #243
