### ISSUE TITLE
Telegram: Recording sound message not possible

### ISSUE THREAD

**Issue by stefahn** [meetfranz/franz#348]
If I click on the microphone symbol in a conversation in Telegram nothing happens.
In WhatsApp for example recording sound messages works fine.

Franz Version used: 5.0.0 beta 14
Operating System and version: Windows 10, 64bit

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
[telegram recipe repository](https://github.com/meetfranz/recipe-telegram)
