### ISSUE TITLE
macOS app version force use of discrete graphic card when it is available

### ISSUE THREAD

**Issue by banneliv** [meetfranz/franz#349]
App requests use of discrete graphic card whereas integrated is enough. It result on bad a lower autonomy.

### My Environment
* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: macOS 10.13.1
* Integrated graphic card: Intel HD Graphics 530 1536 Mo
* Discrete graphic card: Radeon Pro 460 4 Go

**Comment by adlk** [comment]
Duplicate of #117
