### ISSUE TITLE
Move through tabs with ctrl+tab

### ISSUE THREAD

**Issue by kroswer** [meetfranz/franz#35]
### Current Behavior
Currently it is only possible to move between tabs using ctrl+1, ctrl+2, etc

### Feature Description
It would be nice to be able to move through tabs using ctrl+tab and/or ctrl+shift+tab, like in web browsers. 

### Context and Motivation
With more tabs the current behavior gets tricky and it would be easier and comfortable with ctrl+alt.

**Comment by adlk** [comment]
@GustavoKatel I like what I see 👍

**Comment by mateusduboli** [comment]
You could also use `CMD+[` and `CMD+]` just like chrome and safari :0
