### ISSUE TITLE
Shortcuts for sidetab wrong if service is deactivated

### ISSUE THREAD

**Issue by dennis-f** [meetfranz/franz#350]
### Expected Behavior
Skype[`Ctrl+1`] ~Hangouts[`Ctrl+2`]~ WhatsApp[`Ctrl+3`]
Displayed shortcuts should match actual shortcuts on keyboard.

### Current Behavior
Actually Skype is `Ctrl+1` and WhatsApp is `Ctrl+2`. So it skips if one or more services in the middle are deactivated.

### Your Environment
* Franz Version used: Franz 5.0.0-beta.14
* Operating System and version: Windows 10 64-bit

**Comment by haraldox** [comment]
this is fixed in the latest version of Franz 5.0.0-beta.15
