### ISSUE TITLE
Notification dot in the taskbar doesn't show a number, only a red dot

### ISSUE THREAD

**Issue by joey191** [meetfranz/franz#354]
### Expected Behavior

The badge in the taskbar should show a number for the amount of unread messages / notifications. Since my update from version 4 to version 5 it doesn't do it anymore, it only shows a red dot. Same on the beta versions.

### Current Behavior

The badge in the taskbar only shows a red dot for any unread message / notification

### Screenshots (if appropriate):
![screenshot_1](https://user-images.githubusercontent.com/34029589/33267468-e668c2da-d379-11e7-990f-c4ed0a7f50f4.png)

### Possible Solution

Maybe that's a really stupid idea but I didn't find the source files for the numbers badges (pngs or whatever), is it possible that they are missing or are they just well hidden in the files?

### Steps to Reproduce (for bugs)

1. Send yourself a mail from an account outside of Franz and wait for it to arrive or just make a reminder in Google Calendar or any other service you might use

### Context

In version 4 it was nice to quickly see the amount of unread messages / notifications with a single glimpse on the taskbar. Sometimes it's not possible to work through all emails you have and you have a few, let's say, 3 emails left. So it should show that in the taskbar. If you are gone for some minutes and another notification arrives you will see that since it should've changed to a "4" in the taskbar. Right now that's not possible since it's always only the red dot and you would need to open Franz again and again to find out if there is something new or not.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 Pro, Version 1703, Build 15063.250

**Comment by joey191** [comment]
I tried to replicate the issue with Windows 10 Pro, Version 1709, the newest, on a virtual machine and it's the same. However, I noticed that maybe there are two different areas where it can happen. The taskbar to the right where it was the same as on my initial post but to the left, if you have the default view of the windows, it shows the counter:
![screenshot_1](https://user-images.githubusercontent.com/34029589/33274050-54656f30-d38f-11e7-9682-1c448fe0f6fa.png)
On my normal Windows I use the small view which doesn't support that. So the question is: is it wanted that on the right side there is only a red dot or is it supposed to be a counter as well?

**Comment by alecive** [comment]
I believe it is wanted. And, honestly, I like only having a badge instead of a number, it's less "pressuring" :sunglasses:

**Comment by adlk** [comment]
We differentiate between the taskbar and notification area. The taskbar has an overlay for 1-9, 10+ or indirect messages. The icon in the notification area is just supposed to indicate that there are unread messages.

We had quite a lot of issues with low res displays in the past that we have decided to keep the indicator as simple as possible in the notification area.
