### ISSUE TITLE
Gmail or Google Calendar give notifications but no sound

### ISSUE THREAD

**Issue by jobo90** [meetfranz/franz#355]
### Expected Behavior

I guess it should be the case as with WhatsApp or Slack for example that a notification makes a sound.

### Current Behavior

Right now, Gmail and Google Calendar don't give any sound whatsoever although I enabled the notifications on both of them (sound for Google Calendar as well) inside the Franz app.

### Screenshots (if appropriate):
![screenshot_2](https://user-images.githubusercontent.com/34029589/33267355-76f6684e-d379-11e7-996e-971f44efe75a.png)
![screenshot_3](https://user-images.githubusercontent.com/34029589/33267358-7918493a-d379-11e7-9441-12536476b125.png)

### Steps to Reproduce (for bugs)

1. Make yourself a Google Calendar appointment with the notification set a minute before the event, go out of the Franz app and wait for the notification to arrive
2. Or send yourself a mail from an outside account to your Gmail account and wait for the notification

### Context

It would be nice to have an audible reminder if something arrives, like with WhatsApp or Slack which both work perfectly like that in Franz. I'm not sure if Gmail allows that and it is the same issue for everyone.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 Pro, Version 1703, Build 15063.250

**Comment by joey191** [comment]
Also I noticed on my Windows 10, 1703 but also on a virtual machine with 1709, that Google Calendar very often or nearly always doesn't give me any notifications except right after the start. I will test that over a longer period but something seems to be wrong there.

**Comment by haraldox** [comment]
@joey191 any updates?

**Comment by haraldox** [comment]
may be related Windows Fall Creator Update and changed notification center API
