### ISSUE TITLE
Cache file size and behavior

### ISSUE THREAD

**Issue by michaelwapp** [meetfranz/franz#356]
Franz stores cache files for each service which become really big over time. Furthermore, the cache of deleted services is not removed from the storage. 

### Expected Behavior

Franz is expected to delete the cache of deleted services. Further, the cache size should be smaller (if possible) or there should be an option to clear the cache. 

### Screenshots:
![screenshot from 2017-11-27 17-38-12](https://user-images.githubusercontent.com/19573520/33277765-ccee9788-d399-11e7-80e6-5ac365297a4d.png)

Cache folder which is used by Franz - there are more services listed than I have currently activated. 

![screenshot from 2017-11-27 17-36-10](https://user-images.githubusercontent.com/19573520/33277675-82db1bee-d399-11e7-818a-75ff735ebe2b.png)

My currently active services. 

### Your Environment

* Franz Version used: Version: 5.0.0-beta.13 Release: 1.7.9 / linux / x64
* Operating System and version: Arch Linux x86_64 (4.13.12-1-Arch) Gnome

**Comment by alecive** [comment]
What happens on standard browsers (e.g. chrome or firefox)? They don't control the cache size as well (but they allow you to delete it). Whilst I agree about the possibliity to delete cache, I don't think franz should tinker with cache sizes.

**Comment by adlk** [comment]
In Chrome every user has it's own cache. In Franz, every service has it's own cache. This is the only way to have multiple instances of every service – even with services that want to prevent that.

We should definitely remove cache files for deleted services and I can re-add the option to flush the cache.

**Comment by alexroston** [comment]
I would really appreciate the cache flush option too.

**Comment by dannyqiu** [comment]
This feature was shipped in Beta 15 🎉

**Comment by klonos** [comment]
I am using beta18 and cannot see this option in any of the configured services. Is there any way to do this manually?

**Comment by aandrieiev** [comment]
@klonos look under the Settings tab, not Services.
