### ISSUE TITLE
Whatsapp: Click on title bar always opens user contact info

### ISSUE THREAD

**Issue by bleed2002** [meetfranz/franz#357]
### Feature Description
When using the whatsapp integration a click on the title bar (where the image, name is integrated) always opens the contact info bar of that user.
In 99,9% this behaviour is not intended, I just want to move the franz window arround..

### Mockups, Screenshots (if available):
![franz1](https://user-images.githubusercontent.com/291335/33316358-fe9aa7a0-d433-11e7-8939-60bb2ce552e3.png)
![franz2](https://user-images.githubusercontent.com/291335/33316363-032a89de-d434-11e7-9df6-70507d795309.png)

**Comment by adlk** [comment]
This should be easy to fix as we just need to stop the event from bubbling when a user starts the drag event. Happy to accept a PR.
