### ISSUE TITLE
Ctrl+'-' zooms out, but unable to zoom in

### ISSUE THREAD

**Issue by honza889** [meetfranz/franz#36]
### Expected Behavior
Ctrl+'+' should zoom in and Ctrl+'-' should zoom out like in web browser

### Current Behavior
Ctrl+'-' zooms out, but Ctrl+'+' does not zoom in - it is not possible to return to original state

### Steps to Reproduce (for bugs)

1. press Ctrl+'-' when openend HipChat, Facebook or probably any Franz tab
2. the page zooms out
3. it is not possible to zoom in back - Ctrl+'+' goes to the first tab

### Context
Random Ctrl+'-' pressing makes opened Franz unusable until restarted.
It is also often very useful to have possibility to zoom chat window - for presentation, when connected to external screen or similar.

### Your Environment

* Franz Version used: 4.0.4 build 40 release 1.3.1 / linux / x64
* Operating System and version: Fedora 26

**Comment by adlk** [comment]
Franz 4 is no longer maintained. Usually we urge our users to upgrade to Franz 5 which in your case is not possible for Linux yet. Please bear with us while we are working on the Linux support.

**Comment by ChenTB86** [comment]
@adlk I also have this issue . using Franz5.1.0 on MacOS 10.14.5 (18F132) macbookpro

**Comment by gabyk** [comment]
Franz 5.1.0 on MacOS 10.12.6 still has this issue. Is any workaround available to fix this?

**Comment by lindsayj23** [comment]
Having this issue with 5.3.2 on Mac osx as well!

**Comment by lindsayj23** [comment]
Update for anyone else following along: apple + shift + '+' zooms back in!

**Comment by martinkopac19** [comment]
> Update for anyone else following along: apple + shift + '+' zooms back in!

Not working mate. Did anybody solve this? 5.3.3 on mac

**Comment by sritampatnaik** [comment]
<kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>+</kbd> worked for me
