### ISSUE TITLE
Add Google Drive service/recipe

### ISSUE THREAD

**Issue by AGonLen** [meetfranz/franz#360]
Would it be possible to add Google Drive as a service/recipe onto Franz?

Thanks!

Franz Version used: 5.0.0.beta.14
Operating System and version: Windows 10 Pro Fall Creators Update

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](http://bit.ly/franz-service-request) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
