### ISSUE TITLE
Disabled service page overlaid with current service page

### ISSUE THREAD

**Issue by leandroperezb** [meetfranz/franz#361]
### Expected Behavior
Show just the page of the current service selected

### Current Behavior
It shows the message of Google Keep disabled when i'm on Twitter (in my example)

### Screenshots (if appropriate):
![imagen](https://user-images.githubusercontent.com/11557075/33350833-ac85917c-d47f-11e7-9c9d-c2f68568ff65.png)

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Linux Mint 18.2 64bits with MATE environment

**Comment by adlk** [comment]
Does this persist when you switch between services?

**Comment by leandroperezb** [comment]
On the other services the message it's shown a sec until they load their websites. Seems like Twitter have some transparent backgrounds and the message of the service disabled it's always as background of the current page.

The other service that I have can cover it. But that it's a "flash" when I selected them that I can see the disabled page until WhatsApp, Gmail, or Messenger page are displayed
