### ISSUE TITLE
Auto-reply feature

### ISSUE THREAD

**Issue by jeremywhelchel** [meetfranz/franz#363]
Would love to have an ability to automatically reply to a message with a set response.  

### Feature Description
My use case is simple:  
I never use FB messenger, yet people insist on contacting me via this. Whenever someone sends a message, I want an automatic response with custom text (I would use: "I don't read these, email me at abc@xyz.com instead.") . 
I would pay for this, as well as some ability to run it as a cloud service. Or failing that I'd purchase and run it as a VM.  

### Motivation and Context
Auto-responses would be a great addition in general.  
I want to discourage people from using FB messenger to contact me. FB of course offers no solution to disable this. And there are surprisingly no existing tools to solve this problem.
Caveat is that they do offer auto-responses for "pages" but I want this for personal profiles.  
I also know many other people with my same desire.

**Comment by adlk** [comment]
This would require an API integration or messing around with every individual service – both things we haven't planned for the future.
