### ISSUE TITLE
Microsoft Teams Integration

### ISSUE THREAD

**Issue by casaout** [meetfranz/franz#367]
It would be great if Franz was extended with the Microsoft TEams integration (similar to Slack). They have a web client: teams.microsoft.com

Thanks!

**Comment by adlk** [comment]
Microsoft Teams is already integrated in Franz 5.
<img width="466" alt="bildschirmfoto 2017-11-29 um 14 51 07" src="https://user-images.githubusercontent.com/3265004/33378342-c192d238-d514-11e7-92e9-0bcb72ef7504.png">
