### ISSUE TITLE
Clicking on notifications in Windows 10 does not open Franz, or take you to the relevant message

### ISSUE THREAD

**Issue by rabbly** [meetfranz/franz#370]
### Expected Behavior

When you receive a notification in Windows 10 for a new message, clicking on that new message should open Franz and show the new message in the relevant application.

### Current Behavior

When clicking on a notification, the notification is dismissed but nothing else happens

### Screenshots (if appropriate):
N/A

### Possible Solution

N/A

### Steps to Reproduce (for bugs)

1. Receive Windows 10 notification from new message
2. Click on notification
3. Message is dismissed, Franz is not opened

### Context

When receiving a new message notification it's immediately relevant to see and reply to that message.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 Enterprise Version 1703 Build 15063.726

**Comment by adlk** [comment]
Can you please test this for me: if Franz is open (not minimized or in systray) clicking the notification brings you to the correct service and message?

I did a test on (Build 16299.19) and I could reproduce your issue but only when Franz is minimized.

**Comment by rabbly** [comment]
Yes, it seems to work when Franz is open. However if it's in the
background, minimised or the system tray the notification won't work.
