### ISSUE TITLE
telegram not work

### ISSUE THREAD

**Issue by yehuda-avrashi** [meetfranz/franz#374]
Telegram service does not work properly
After you enter the phone number, he does not do anything

Version Franz Version used: 5 beta 14

![image](https://user-images.githubusercontent.com/34124302/33422625-fe65aa46-d5be-11e7-89b1-8ade39ae71bf.png)

**Comment by adlk** [comment]
Can you please open the service dev tools and show me a screenshot of the logs?
(Press Alt -> Go to View -> Toggle Service Developer Tools)

**Comment by yehuda-avrashi** [comment]
![image](https://user-images.githubusercontent.com/34124302/33422972-200e7776-d5c0-11e7-9b0d-d27deed4ca47.png)


![image](https://user-images.githubusercontent.com/34124302/33423025-50efa180-d5c0-11e7-8fbe-cc8963a917bc.png)

**Comment by yehuda-avrashi** [comment]
![image](https://user-images.githubusercontent.com/34124302/33423187-caf092fa-d5c0-11e7-8ac1-ad85d21df6a6.png)

**Comment by yehuda-avrashi** [comment]
![image](https://user-images.githubusercontent.com/34124302/33423274-02ddfb30-d5c1-11e7-9518-8f4b511392cf.png)

**Comment by adlk** [comment]
I have updated the telegram recipe to get rid of this error but I'm not really sure if this error affects the actual issue of not being able to login. 
In dev tools, if you go to network, reload, and try to login. Is there anything in red? 

To get the latest version of the telegram recipe, just check for updates in settings.

**Comment by yehuda-avrashi** [comment]
![image](https://user-images.githubusercontent.com/34124302/33424723-5b64320c-d5c5-11e7-88ed-c79ffc17071c.png)


![image](https://user-images.githubusercontent.com/34124302/33424786-864e9eda-d5c5-11e7-865e-a2d101623192.png)

**Comment by yehuda-avrashi** [comment]
![image](https://user-images.githubusercontent.com/34124302/33424889-d936291a-d5c5-11e7-9f05-8eb0de52afcb.png)

**Comment by adlk** [comment]
Anyone else getting this error?

**Comment by wardcraigj** [comment]
Telegram just shows a blank page for me

**Comment by wardcraigj** [comment]
Hmm, issue still persists.

**Comment by adlk** [comment]
Can you please provide more information about the network logs?
> In dev tools, if you go to network, reload, and try to login. Is there anything in red?

**Comment by wardcraigj** [comment]
Send to have been corrected after updating

**Comment by adlk** [comment]
@wardcraigj @yehuda-avrashi  It is now fully working for you?

**Comment by yehuda-avrashi** [comment]
I checked with me
I changed my ISP and it worked right
(Apparently my ISP does some blocking)

**Comment by wardcraigj** [comment]
yep, working for me too

**Comment by adlk** [comment]
@yehuda-avrashi any chance you are in France? Got reports from another user who is an orange customer that he can't use telegram in their network.

---

I'm closing this issue for now.
