### ISSUE TITLE
Applespell 100% cpu

### ISSUE THREAD

**Issue by specialunderwear** [meetfranz/franz#375]
I pasted 100 email adresses into franz gitter and the UI totally froze. Process monitor indicates that applespell is using 100% cpu
I also tried in slack, same problem!

### Expected Behavior

I paste email and franz swallows

### Current Behavior

Franz freezes up trying to parse emails how hard can it be lmao

### Possible Solution

Allow turning off spell checking which is useless anyway for code.

### Steps to Reproduce (for bugs)

1. Paste 100 email adresses into a franz plugin text field
2. HELP UI FREEZES
3. WAIT
4. PROFIT!

### Your Environment

* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: OSX Sierra

**Comment by adlk** [comment]
This is already available in settings.

**Comment by specialunderwear** [comment]
Ok then, but the performance is really really bad when enabled, which is the default so I don;t think you can just close this bug.
