### ISSUE TITLE
Notifications window not displaying the message after clicking the notification ( ubuntu 17.10 )

### ISSUE THREAD

**Issue by vibhas77** [meetfranz/franz#376]
The message display window that opens after clicking the notification is displaying blank in service Gmail.

## Screenshot
https://ibb.co/fBOoUb

Environment
* Franz Version used: Freshly Installed 5.0.0-beta.14
* Operating System and version: Freshly Installed Ubuntu 17.10

**Comment by adlk** [comment]
I'm merging this into the related issue: #244
