### ISSUE TITLE
No notification alert for Google Chat / Hangouts on Mac OS X

### ISSUE THREAD

**Issue by isalew** [meetfranz/franz#377]
I can receive notifications for slack, but I receive no notifications for alerts from my Google Hangouts services.

### Expected Behavior

- Setup a corporate Google Hangouts service
- Receive a message from someone
- Receive an alert notification via the standard Mac OS X notification system, with a bar in the top-right corner.

### Current Behavior

- Setup a corporate Google Hangouts service
- Receive a message from someone
- Receive a red dot on the Franz app icon, but no notification

### Context

I miss alerts from my chats, causing me to reply exceptionally late to people.

### Your Environment

* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: Mac OS X 10.13.1 (17B1002)

**Comment by dkpalmer** [comment]
Can confirm this same issue.

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins

**Comment by dkpalmer** [comment]
@BrianGilbert I see this behavior for two different chat clients: Google Hangouts and Facebook messenger. It seems like maybe it's more part of the core app and not part of a specific service.
