### ISSUE TITLE
Line break Shortcut.

### ISSUE THREAD

**Issue by Zuano** [meetfranz/franz#378]
Thank you for the helpful and ingenious program. Two years ago I already donated something for Franz.

This is the first time I give a feedback. I would like to make two points:

The link in the help center refers to an invalid zendesk URL.

secondly:

I ask you to implement alt+Enter as a shortcut for the line break, because this will run synchronously with the Mac OS SMS iMessage App. Or use both (Shift + Enter and Alt + Enter). I only tried it in Franz at WhatsApp. 

At the moment it's hard to remember which Shurtcut works. It often happens to me that I send the SMS or Messenger message even though I only wanted a line break. Both in the Messages App and in Franz Messenger.

Mac OS 10.13.1
Franz Version 4.0.4

Greetings!

**Comment by adlk** [comment]
A couple of things to note: 
- This is already implemented in most services (where we don't have control over) with `shift+enter`
- You are using an old version of Franz. Please upgrade to the latest version manually 
 via www.meetfranz.com/#download

Fun fact: Franz is just a littler older than a year :smile:

**Comment by Zuano** [comment]
Thank you for your feedback.
Thought I'd been using the app for a while. However, it will probably have an anniversary soon.

iMessage uses Alt+Enter!
Shift + Enter sends the message in iMessage.. That's annoying for me. Do you think Apple will change the shortcut?
Why doesn't Franz also use Alt+Enter? Then it would at least be uniform. 

What makes you think I have an old version installed?
On the homepage you gave me, I only found the 4.0.4 version.

**Comment by MalboneStreet** [comment]
I have a feature request related to this, but not identical.  I use Franz on Mac and Windows machines.  It would be very helpful to me to have a setting I can toggle that would turn off "Enter = Send".  I prefer to compose messages in the same way that I compose a text document, and if I forget and hit Enter, the message is sent prematurely.  I would rather have to click on the Send button when I'm ready to send the message.  Thanks!
