### ISSUE TITLE
Option to remove icon from dock and add global shortcut

### ISSUE THREAD

**Issue by BinaryBen** [meetfranz/franz#38]
### Feature Description
I'm using the beta version and noticed the app finally has an icon in the menu bar for macOS. I would like an option in settings to choose between:

* Show app in dock and icon in menu bar
* Only show app in dock
* Only show icon in menu bar

As an added extra, it would be better with a global keyboard shortcut to show the app, and provide the option for the main window to disappear when not focused.

### Motivation and Context
Purely preference based. I hide my dock, but it would great to interact with Franz using a global shortcut and icon in the menu bar. An example of an app that offered this functionality is nvAlt (a fork of Notational Velocity), and I used to use this app as often as I do Franz.

This would help me stay distraction free when needed with a lot more ease, while still being contactable.

**Comment by adlk** [comment]
Thanks for opening this feature request.
The option to enable/disable the system tray icon is already in testing #2 

In the past, I've decided against a "hide from dock" option as you can't `cmd+tab` to Franz any longer which would freak out quite a large amount of users as not everyone is as tech savvy as you. The solution with having a global shortcut might however work as an alternative for power users.

Having said all the above, I believe we can add an option toggle which has to be accompanied by a clear explanation of what it does and how to restore the Franz window.

**Comment by Van-Halen** [comment]
I prefer the status bar icon, so i've hidden the dock icon of Franz by adding:

`    <key>LSUIElement</key>
    <true/>`

After line 44 in /Applications/Franz/Contents/Info.plist

**Comment by SergioSGil** [comment]
+1 option to remove icon on menu bar (MacOS) 
On Dark option icon is not working properly: 

https://imgur.com/a/Pu1F9

If i do click on the icon:
https://imgur.com/a/pTElP

**Comment by adlk** [comment]
The option to show/hide the tray icon was added in beta 11.

I'm going to merge the global shortcut request into #197 as it's a standalone feature request. (Easier to keep track of)
