### ISSUE TITLE
Twitter DM Notifications Don't Work

### ISSUE THREAD

**Issue by ChrisWiegman** [meetfranz/franz#380]
### Expected Behavior
When a new DM arrives using the "Twitter DM" service the appropriate notification should occur as it does in other services

### Current Behavior
No notification of Twitter DMs ever arrive

### Steps to Reproduce (for bugs)

1. Receive a Twitter DM
2. Look for notification (it won't be there)

### Context
Twitter DM service is pretty much worthless without proper notifications

### Your Environment

* Franz Version used: 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: macOS 10.13.1

**Comment by adlk** [comment]
Twitter DM simply does not support toast notifications as it is using the mobile twitter view which is made for mobile where the web notification concept does not exist. 

Unfortunately, this can't just be implemented.
