### ISSUE TITLE
Franz - error on Chrome being old version

### ISSUE THREAD

**Issue by dzigner** [meetfranz/franz#382]
### Current Behavior

In Franz, in all my gmail accounts I have setup, I get this error notification : This version of Chrome is no longer supported. Please upgrade to a supported browser.

Screenshot attached.
![franz-chrome error](https://user-images.githubusercontent.com/1585458/33458764-5133297a-d5dc-11e7-9e0b-e5d128eb71ff.PNG)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)

**Comment by giuliastro** [comment]
This is happening right now with latest version (5.0.0-beta.19).

**Comment by beltranrengifo** [comment]
![image](https://user-images.githubusercontent.com/19485114/49398064-920a1480-f73d-11e8-9402-061ea2a97796.png)

**Comment by maria-antignolo** [comment]
How is this closed if the problem persists?
Same problem here, same Franz version, latest of the latest Chrome, unable to use whatsapp with franz with a screen asking to update chrome.

**Comment by beltranrengifo** [comment]
Stefan told the problem is WhatsApp related. Rambox is suffering the same issue. I have it working right now in Franz, the update should arrive really soon.

**Comment by typoworx-de** [comment]
I can confirm this issue with Franz 5 (latest version available for download).

**Comment by maria-antignolo** [comment]
solved for me in ubuntu 18.04

**Comment by Zeboch** [comment]
Issue still active in Version 5.3.3 (5.3.3.1582) for Android Messages.
![image](https://user-images.githubusercontent.com/7860628/104906536-210d3180-5984-11eb-8e25-85f2240ce439.png)
