### ISSUE TITLE
Pocket Login via Google not working

### ISSUE THREAD

**Issue by fabwer** [meetfranz/franz#384]
Can not login to Service Pocket via Google login.

Getting stuck at a loading screen after choosing the account to be used for the login to pocket.
Can add screens if needed.

* Franz Version used: Franz 5.0.0-beta.14.451
* Operating System and version: macOS High Sierra 10.13.1

**Comment by vascosmota** [comment]
I am facing the same issue using the Windows app.

- Franz Version used: 5.0.0-beta.14
- Operating System and version: Microsoft Windows 10 Pro 10.0.15063

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
