### ISSUE TITLE
Disable the window contextual menu hotkeys.

### ISSUE THREAD

**Issue by gryp17** [meetfranz/franz#387]
Here is my problem: I have to constantly switch between keyboard layouts using the hotkey "alt + shift", however I have noticed that in Franz when I press "alt + shift" it opens the window > Edit contextual menu and focuses on it which is very annoying. 

### Expected Behavior
Using this hotkey shouldn't open the contextual menu (If I use skype directly I can use this hotkey, but in Franz it opens every time I switch keyboard layouts)

### Screenshots (if appropriate):
![screenshot_2017-12-01_14-18-27](https://user-images.githubusercontent.com/12124287/33482632-b0aa3abc-d6a2-11e7-933b-e8b676863437.png)

### Possible Solution
Change the hotkey or add an option to disable all hotkeys.

### Your Environment

* Franz Version used: Version: 5.0.0-beta.14 Release: 1.7.9 / linux / x64
* Operating system used: Xubuntu 16.04 (Linux version 4.4.0-101-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017)

**Comment by adlk** [comment]
Please be more specific with the linux version you are using, this makes a huge difference.

**Comment by gryp17** [comment]
Sure. I have updated the issue:

Operating system used: Xubuntu 16.04 (Linux version 4.4.0-101-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017)

**Comment by t3rmix** [comment]
Hi,
i am facing same issue with ALT+SHIFT key (which i am using to switch keyboard layout).
System: Linux Mint 18.3 Sylvia with kernel 4.10.0-40-generic.

**Comment by nemilya** [comment]
I cant reproduce this problem...
Linux Mint - 17.3 (Linux 4.4.0-36-generic)
Franz Version: 5.0.0-beta.13

Alt+Shift - no effect to Franz (I use Ctrl+Shift to keyboard switch).

**Comment by Limetris** [comment]
I have the same problem...

Linux Mint 18.1  KDE Edition

**Comment by Bo1337** [comment]
OS: Ubuntu 16.04.3 LTS
Franz Version: 4.0.4 Build: 40 Release: 1.3.1 / linux / x64
Switching language layout using Left-Alt+Shift immediately opens context menu in Franz. 
FYI Shift+Left-Alt just changes layout, no context menu is opened in Franz.

**Comment by zurabashan** [comment]
OS: Ubuntu 16.04 LTS
Franz:
Version: 4.0.4
Build: 40
Release: 1.3.1 / linux / x64

When pressing Left-Alt + Left-Shift combination I have same problem.

Can someone fix this?

**Comment by military1** [comment]
Same problem on KDE neon.

**Comment by radozaj** [comment]
Please, fix it. Alt + Shift is standard keyboard for switching keyboard layouts. I use 4.13.0-43-generic #48-**Ubuntu** SMP Wed May 16 12:18:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by malec985** [comment]
same problem. franz   5.0.0-beta.18, Kubuntu 18.04.  Pleese fix it

**Comment by pdrosos** [comment]
I have the same issue. Franz 5.0.0-beta.18, Linux Mint 19.

**Comment by thedarkeel** [comment]
The same issue here.. 
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
Linux mint 18.2
Cinnamon 3.4.6

**Comment by thiagoa** [comment]
I'm also suffering from this problem. I have many global shortcuts that us the Alt key and they don't work properly. Has anyone found a solution for this? :thinking:

**Comment by thiagoa** [comment]
Just documenting my search in finding a solution to this problem. The Slack desktop app for Linux, for example, also has the same problem. I thought it could have something to do with GTK 3's `gtk-enable-mnemonics` setting, but I've tried disabling it in many ways (locally and globally) with no success. This annoying behavior seems to be somehow hardcoded into the application.

**Comment by danjudex** [comment]
I have the same problem in windows 10, alt + shift default hot key in system
![image](https://user-images.githubusercontent.com/6211155/111603280-ff022500-87f5-11eb-83b9-b7e1f2a4a175.png)
