### ISSUE TITLE
Hide unread badge when channel notifications are dissabled

### ISSUE THREAD

**Issue by wacko** [meetfranz/franz#388]
### Expected Behavior

Unread message count should not include channels where notification are disabled

### Current Behavior

On Telegram, when a channel is silenced, and I receive a message, the red notification badge appears. It should only happen for channels with notification enabled.
The badge appears on the sidebar and on the application icon too.

It does work well on some services. I've Whatsapp and Telegram, both with some channels muted. It works well on Whatsapp, but not on Telegram.

### Steps to Reproduce

1. Open Telegram
2. Disable notifications for a channel.
3. When you receive a message, the badge appears.

### Your Environment

Franz Version used: 5.0.0-beta.14.451
Operating System and version: macOS Sierra (10.12.6)

**Comment by adlk** [comment]
The issue in telegram is now fixed.

In beta 15 I'm adding a more fine grained control for notifications and notification badges. More infos can be found in #386
