### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by adlk** [meetfranz/franz#39]
In the past we've realized that Franz users don't necessarily want to use an english-only app – if it's not needed.

### Motivation and Context
The Franz userbase is spread all over the globe and couldn't be more versatile. This is something we are very proud of and want to support better. With Franz 4 and the amazing community we've been able to translate Franz into 30+ languages and want to offer the same support to Franz 5.

# Update:
Translations are now managed via http://i18n.meetfranz.com 

**Thank you so much for your support**

**Comment by phmigotto** [comment]
Translation to Portuguese (Brazil). Keep up the good work on the app!
[pt-BR.zip](https://github.com/meetfranz/franz/files/1402314/pt-BR.zip)

**Comment by rwkyyy** [comment]
Hmm, I remember a few years back, when Franz was in beta stages, you (or someone else) asked for the community to help out in translation via a Google Sheets, isn't that valid, anymore?

**Comment by adlk** [comment]
@rwkyyy we used that to translate Franz 2 and while it worked out pretty well for the initial translations, it wasn't maintainable for updates.
I'm still looking for a proper tool/method to manage community translations on the long run.

**Comment by rwkyyy** [comment]
@adlk ah, I see, okey, I'll start translating my language (Romanian), ti'll then maybe [this](http://anthonynsimon.com/parrot.github.io/) helps

**Comment by adlk** [comment]
@rwkyyy thanks for the hint. I'll do some tests.

**Comment by Kietzmann** [comment]
I'll take Ukrainian and Russian

**Comment by felipemarinho97** [comment]
I'll take Brazilian Portuguease!

**Comment by apo-mak** [comment]
i add Greek :-)  https://github.com/meetfranz/franz/pull/80

**Comment by lmigula** [comment]
I'll have a look at german :)

**Comment by tiagossa1** [comment]
I want to upload my translation for Portuguese (Portugal). How do I do that??

**Comment by SergioSGil** [comment]
How about Spanish Translation? :)

**Comment by adlk** [comment]
@Wouter0100 if you can do the setup that would be great!

We have a #translations channel in slack. Would be great if we can use this for detailed discussions. Sign up for the community Slack here: http://slack.franz.im

**Comment by EnrikeGonzaloLegarra** [comment]
I want help you with spanish translation.

**Comment by dnlup** [comment]
I can help with italian translation

**Comment by adlk** [comment]
## Important Update:
Thank you so much for all your contributions!

I've made it easier for everyone to provide translations and do Q&A. Please head over to http://i18n.meetfranz.com, select your language and you are good to go.

If your language is missing, let me know and I'll add it.

Thanks, 
Stefan

_PS: Unfortunately, I haven't been able to import the existing translations. I'll copy/paste the existing strings over the next couple of days. If someone wants to help, let's coordinate in [Slack](http://slack.franz.im)._

**Comment by Tititesouris** [comment]
Hey, I have a question regarding the meaning of the slogan.
The welcome.slogan "Messaging that works for you".
Does it mean "Messaging service that is at your service" or "Messaging service that functions so you can use it"?

**Comment by adlk** [comment]
@Tititesouris You can leave this in english as translating it might change the meaning in quite a lot of languages. This is also the reason why I'm going to remove this string soon.

**Comment by noubit** [comment]
@adlk I downloaded the English po and i'm translating Franz in Catalan, can you add it to the repository? 
Thanks!

**Comment by adlk** [comment]
@noubit sure, please upload it here or send it to stefan@adlk.io

**Comment by noubit** [comment]
Sure! I don't know if the .po I downloaded is the full version for the program, but it's already translated it. If some strings are missing in the .po file, I will complete the translation next week. Thanks!
[ca.zip](https://github.com/meetfranz/franz/files/1484517/ca.zip)
Important: The file is zipped, Githum doesn't allow me to upload a po file.

**Comment by noubit** [comment]
Hello @adlk . I checked the Pootle server and I seen that the catalan language is already activate, but without the translation uploaded. I tried to upload my .po file and It doen't worked. Can I upload it or I have to translate via web browser?

Thanks

**Comment by noubit** [comment]
Catalan translation finished! Really excited to see it in some future version!

**Comment by adlk** [comment]
@noubit Perfect, thanks for your efforts!

**Comment by auggg** [comment]
Franz, add Lithuanian language to translate. I will help you with growing ;)

**Comment by sasa1984** [comment]
just finished translation for slovenian language :)

**Comment by Bekkenes** [comment]
Add Norwegian and i will translate it.
