### ISSUE TITLE
Unable To Connect To Franz With VPN

### ISSUE THREAD

**Issue by Joejoboi** [meetfranz/franz#390]
### Expected Behavior

Turn on VPN (Private Internet Access) and connect to services via the Franz client.
### Current Behavior

When I turn on VPN, all Franz services go offline. (Slack, Hangouts, Whatsapp, Facebook, Tweetdeck, Google Calendar, LinkedIn, Skype)

I've tested this several times to reproduce the current behavior. 

### Steps to Reproduce (for bugs)

1. Turn on VPN
2. Open Franz

### Context

I'm unable to use Franz and my current VPN provider.
### Your Environment

* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: macOS Sierra V 10.13.1

**Comment by adlk** [comment]
Duplicate of #16

**Comment by mikeolteanu** [comment]
VPN is not the same thing as a proxy.
VPN used to work a couple weeks ago, and stopped working for me and other people at the same time.
Respectfully, this is not a duplicate of #16

**Comment by mikeolteanu** [comment]
Reinstalled VPN software, issue resolved. Suspect this is related to high sierra osx update process
