### ISSUE TITLE
Unable To Download Photos From Slack Service

### ISSUE THREAD

**Issue by Joejoboi** [meetfranz/franz#392]
### Expected Behavior

Select a photo file and download it locally. 
### Current Behavior

When a file is selected, the client opens a blank browser window.
### Steps to Reproduce (for bugs)

1. Open Slack workspace service
2. Click on file for download
3. New browser window opens 
4. No file is downloaded

### Context

When I need to download a file from Slack, I have to open the workspace in my browser or application to retrieve the file. 
### Your Environment

* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: macOS Sierra V 10.13.1

**Comment by BrianGilbert** [comment]
@Joejoboi it may be that your not currently authenticated to the slack in question in your browser?
