### ISSUE TITLE
Resuming from hibernation without multiple monitors lets Franz open on non available screen

### ISSUE THREAD

**Issue by Uli-Armbruster** [meetfranz/franz#394]
### Expected Behavior
When I start Franz it should
* restore the window on the last screen if available
* on the primary screen if the last remembered screen is not avaialable

### Current Behavior
Working on a notebook, I have 2 additional monitors. I use Franz on one of that external monitors. Before I go to hibernation, I close Franz. When I resume from hibernation without external monitors and start Franz again, it's not restored to the avaialable notebook primary screen. I can't even get it into my screen with the default Windows keyboard shortcuts WIN + KEY-LEFT/RIGHT

### Your Environment
* Franz Version used: 5 Beta 14
* Operating System and version: Windows 10 Pro Build 1709

**Comment by adlk** [comment]
I'm merging this into the related issue #222.
