### ISSUE TITLE
Feature Request: Profiles (work, home, etc..)

### ISSUE THREAD

**Issue by PartisanEntity** [meetfranz/franz#396]
Hi there,

I'm really liking Franz - I would love to see the ability to set up profiles.

I use Slack and MS Teams for work only, I don't want to have them active when I am at home. It would be great to be able to set up "Profiles" - that way I can choose certain services for my "home" profile and others for my "work" profile.

So that when I launch Franz at the office, it automatically launches my work profile and I have my work-relevant services. Then when I launch Franz at home, it uses my home profile and launches my other services.

Thanks

Feature Request Template:

### Feature Description
Allow users to set up "profiles" for use at Work, Home etc...
Each profile allows a specific selection of accounts to log in to. Or it allows the same accounts but different credentials.

### Motivation and Context
We might want to log in to a different combination of services when at work, and when at home. This gives users the freedom and flexibility to adjust their services based on where they are.

### Mockups, Screenshots (if available):
n/a

**Comment by BrianGilbert** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template: 
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by LoveIsGrief** [comment]
Has any work been started on this or is it up for grabs?

**Comment by PartisanEntity** [comment]
Can we please have the incomplete tag removed? I have added the feature request template to my original post.

**Comment by OldhamMade** [comment]
It's been over a year since this was raised. This would make a great feature to provide, and I'm sure everyone who uses Franz would be happy if this were a premium feature (one that was activated after subscription). Can this be added soon?
