### ISSUE TITLE
Beta 5.0 doesn't recognise my account

### ISSUE THREAD

**Issue by randomasyalike** [meetfranz/franz#397]
### Expected Behavior
Open Franz 5.0, login with the same credentials I was using with previous version of Franz.

### Current Behavior
Error message in login screen "Email or password not valid".

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: Beta 5.0
* Operating System and version: macOS Sierra 10.12.6

**Comment by adlk** [comment]
Franz 4 had no accounts. This has been brought up a few times now and I realize that the old version had a poor wording for this. You just need to create an account with Franz 5.
