### ISSUE TITLE
Tray icon do not indicate new messages from ICQ 

### ISSUE THREAD

**Issue by nowayelse** [meetfranz/franz#399]
I use whatsapp, telegram, skype and ICQ services. All of them notifies me with sound, popups and tray red icon, except ICQ. It does not change tray icon at all. All notify flags are set, also there is one into ICQ settings. 

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 7 x64
* ICQ build 334

**Comment by BrianGilbert** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template: 
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
