### ISSUE TITLE
Negative new notifications in badge

### ISSUE THREAD

**Issue by ptrkcsk** [meetfranz/franz#401]
### Expected Behavior

I expect to not have less than zero new notifications.

### Current Behavior

I have less than zero new notifications!

### Screenshots:

![screenshot 2017-12-04 10 10 58](https://user-images.githubusercontent.com/4766244/33568716-447b804e-d8dc-11e7-9f29-2375cc04a0fb.png)

### Steps to Reproduce

I'm not sure yet. Sorry!

### Context

I'm using the following services:

- Slack
- Inbox
- Google Calendar (2 instances)
- Trello (2 instances)
- Toggl

### Your Environment

- Franz v5.0.0-beta.14.451
- macOS 10.13.1

**Comment by adlk** [comment]
Thanks for reporting this issue. I suspect Google Calendar but I'm not able to reproduce it. Can you please try to disable the calendar and see if the issue persists? If it's not the issue source, can you please try to disable every service after another to find the service that is causing the issue?

**Comment by RazvanDH** [comment]
Found a way to reproduce this:

* go to Google Calendar (I'm using the new layout)
* click on a time slot (as to create a new event)
* press ESC to cancel that

I'll see if I can open a PR that fixes that today :)

**Comment by adlk** [comment]
@RazvanDH we should do two things, 
1. don't allow negative badges in Franz
2. update the google calendar recipe to not even report negative numbers

let me know what you want to do and I'll take care of the rest

**Comment by RazvanDH** [comment]
@adlk was actually looking at solving both (still trying to replicate it locally - trying to get the calendar recipe to work locally).

I did a quick investigation and it looks like the calendar is caused by this: https://github.com/meetfranz/plugins-legacy/blob/develop/googlecalendar/webview.js#L16 (still need to check that assumption)

And the badge I assume it's here: https://github.com/meetfranz/franz/blob/master/src/webview/lib/RecipeWebview.js#L38

Will try to fix them - if I fail I'll let you know :)

**Comment by RazvanDH** [comment]
@adlk opened 2 PRs:
* Google Calendar: https://github.com/meetfranz/plugins-legacy/pull/332
* Franz: https://github.com/meetfranz/franz/pull/423

**Comment by RazvanDH** [comment]
@adlk thanks for merging the Franz change. What's the process for getting the other PR (Google Calendar) merged?

**Comment by adlk** [comment]
@RazvanDH I just realized that you have used the legacy repo. 
You need to make your changes here: https://github.com/rherwig/franz-5-googlecalendar

Right now it is a bit difficult to find the related repos but I'm working on a solution.

**Comment by ulentini** [comment]
Hello, since this was _really_ annoying me, I just did a small hotfix, and made a PR. 😄

**Comment by haraldox** [comment]
@ulentini thanks for your contribution, will review shortly
