### ISSUE TITLE
no message preview on windows 10 / telegram

### ISSUE THREAD

**Issue by rwolupo** [meetfranz/franz#404]
on windows 10 there is no message preview in the upcoming notification on telegram service. others services like whatsapp work

### Expected Behavior

having a preview message in notification
### Current Behavior

don't have a preview message in notification
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

nothing works :(

### Your Environment

* Franz Version used:
latest franz beta (-14)
* Operating System and version:
windows 10

**Comment by BrianGilbert** [comment]
@rwolupo have you tested that you get message preview when you use telegram from a web browser?

**Comment by rwolupo** [comment]
hmpf. didnt save my answer days ago. 
whatever: yes, no problems with telegram web. also no problems with rambox for example

**Comment by rwolupo** [comment]
to be more precise: in the message notification comes 
"Franz Neue Benachrichtigung" (in german)

**Comment by rwolupo** [comment]
any news on this issue?

**Comment by haraldox** [comment]
@rwolupo we'll boot up a Windows 10 VM and look into this... do you have an exact Windows version for us? thanks

**Comment by haraldox** [comment]
@adlk might be a selector issue depending on user agent?

**Comment by rwolupo** [comment]
@haraldox Windows 10, Version 1709

**Comment by haraldox** [comment]
may be related to https://github.com/meetfranz/franz/issues/232

**Comment by oskarnrk** [comment]
I think #708 and #830 are duplicates of this issue (and I have it, too)

**Comment by krupenja** [comment]
Can confirm that I am seeing this behaviour for Telegram as well. Works fine (i.e. there is a proper notification preview) at least for WhatsApp, Skype and Facebook Messenger.

I have 5.0.0-beta.18 running on Windows 10 Home x64, build 16299.371.

**Comment by dragGH102** [comment]
same here. W10 Pro (latest build I think)

**Comment by oskarnrk** [comment]
Hi all, in the **5.0.0-beta.1** version (updated today) the **Telegram notifications finally have the sender name and an extract of the test incoming**. It seems the bug is fixed (Windows 10 x64 here)
