### ISSUE TITLE
Franz with retina display and Windows 10 200% magnification appears outside monitor

### ISSUE THREAD

**Issue by Pepedou** [meetfranz/franz#407]
### Expected Behavior
Open Franz and the window will appear at the center of one of your monitors.

### Current Behavior
Open Franz and the window appears outside the side monitor. Closing and reopening doesn't solve the problem. The only way to get back the window is to ALT + TAB to Franz, press ALT + SPACEBAR to open context menu, press M to "Move" and then press Right Arrow Key to move back into view.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/6732960/33620651-0fe66862-d9ae-11e7-9b62-87ea4afd8fcc.png)

### Steps to Reproduce (for bugs)
1. Use Macbook Pro with Retina Display and Windows 10.
2. Set magnification on Macbook display to 200%, the recommended setting.
3. Connect normal Dell monitor (not retina).
4. Leave resolution in normal monitor in 100% (recommended).
5. Open Franz.
6. Franz will appear outside the monitors.

### Context
I'm just trying to open Franz. I think this began to happen when using the 5+ beta.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 1709 Build 16299.64

**Comment by adlk** [comment]
This might be related to #222.

Can you please try to quit Franz, delete the `window-state.json` in `%AppData%\Roaming\Franz\settings` and start Franz again. 

After doing that, the window should be displayed again. If yes, are your steps to reproduce this issue still valid?

**Comment by Pepedou** [comment]
I deleted the `window-state.json` file and it appears to have solved the problem.
I'll report back if it happens again.

Thanks!

**Comment by haraldox** [comment]
@Pepedou are you still experiencing the issue?

closing this for now, feel free to reopen the issue with any questions or comments!
