### ISSUE TITLE
Using MySMS with Franz

### ISSUE THREAD

**Issue by darkman-brown** [meetfranz/franz#408]
### Expected Behavior

When trying to configure MySMS with Franz, you are not able to click "Sign in with Google".

### Current Behavior

When trying to click on "Sign in with Google", nothing happens. Looks like it is able to redirect to Google's login portal.

### Steps to Reproduce (for bugs)

1. Add MySMS as a service in Franz
2. Click "Sign In"
3. Click on "Sign in with Google"
4. Nothing happens

### Context

This issue not affected persay, however if it is a service that is offered, then I would like for it to work.
### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 Pro

**Comment by adlk** [comment]
I'm merging this into the related issue (#244) as we are having issues with popup to host communication.

**Comment by Lyptik** [comment]
Reopening this, got a similar problem. Franz 5.0.0-beta.14 / Release 1.7.9 / win32 / x64

Same behavior but I do have the popup from Google, I can enter my login and password, then it "loads" ( with some graphic bug btw 75% of the popup is blank), and is never able to login into mysms.

If I do use the website app.mysms.com it works like a charm.

Also tried to logout from the website to check if it would better work on Franz but got the same behavior.

Of course tried to remove re-add the service, reload etc.

All the best and keep up the good work, Franz is a great app !

**Comment by darkman-brown** [comment]
I must be doing something wrong because I am still getting the same results. No biggie though because yes I can use the web app for mysms.
Also I do agree that Franz is a GREAT app!!
    On Tuesday, December 26, 2017, 10:45:02 AM PST, David-Alexandre Chanel <notifications@github.com> wrote:  
 
 
Reopening this, got a similar problem. Franz 5.0.0-beta.14 / Release 1.7.9 / win32 / x64

Same behavior but I do have the popup from Google, I can enter my login and password, then it "loads" ( with some graphic bug btw 75% of the popup is blank), and is never able to login into mysms.

If I do use the website app.mysms.com it works like a charm.

Also tried to logout from the website to check if it would better work on Franz but got the same behavior.

Of course tried to remove re-add the service, reload etc.

All the best and keep up the good work, Franz is a great app !
