### ISSUE TITLE
The icon does not appear.

### ISSUE THREAD

**Issue by Tainan404** [meetfranz/franz#411]
After installation the icon does not appear.
### Expected Behavior
when you search for the application, the icon appears.

### Current Behavior

The system icon appears.

### Screenshots (if appropriate):
Deepin:
![deepinscreenshot_select-area_20171206091402](https://user-images.githubusercontent.com/15806883/33659024-dc91702a-da65-11e7-8666-0f1de1696ca2.png)

Elementary OS:
![pasted image at 2017_12_06 09_13 am](https://user-images.githubusercontent.com/15806883/33659069-0873fbcc-da66-11e7-9dcf-f80c1851b713.png)

### Possible Solution
Error in reference icon path.

### Steps to Reproduce (for bugs)
1. install on a linux distribution.
2. search the app/ execute the app

### Your Environment
* Franz Version used: 5.0.0
* Operating System and version: deepin 15.5 / elementary 0.3.2

**Comment by adlk** [comment]
Already resolved in #340 and will be shipped with beta 15
