### ISSUE TITLE
Spellchecker not available for Spanish.

### ISSUE THREAD

**Issue by carlos9e** [meetfranz/franz#412]
Spellchecker for many languages available but for Spanish.

### Possible Solution
Add the Aspell or Hunspell Spanish dictionary. 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md
