### ISSUE TITLE
Outlook - Couldn't load plugin

### ISSUE THREAD

**Issue by ibdf** [meetfranz/franz#414]
In Outlook 365, when you click on a pdf attachment, outlook tries to load a preview of the pdf but fails with the message "Couldn't load plugin".

<img width="639" alt="screen shot 2017-12-06 at 12 52 24 pm" src="https://user-images.githubusercontent.com/31483572/33676669-60879800-da84-11e7-94ab-ec2038bbbe3d.png">

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
