### ISSUE TITLE
Dark tray icon on Dark Gnome Panel

### ISSUE THREAD

**Issue by ceyhunnabiyev** [meetfranz/franz#416]
### Current Behavior

Dark tray icon on Dark Panel. It doesn't matter which icon theme  selected in Gnome.
### Steps to Reproduce (for bugs)

1. Just open franz in Gnome Desktop Environment
2.
3.
4.

### Your Environment

* Franz Version used: 5.0.0-beta 14
* Operating System and version: Manjaro Gnome 17.1 pre3

**Comment by adlk** [comment]
I'm merging this into #233
