### ISSUE TITLE
disable audio icon is not intuitive.

### ISSUE THREAD

**Issue by Tainan404** [meetfranz/franz#419]
the bell icon is common in notification buttons (same on youtube), implying that clicking on it will stop the audio notifications, not the audio played inside the service.

### Expected Behavior
disable audio notifications

### Current Behavior
disable audio played into of the franz

### Possible Solution
Change the icon to a sound icon.

![sound-icon](https://user-images.githubusercontent.com/15806883/33716118-19dadfee-db3c-11e7-871c-1444e1e2b874.png)
### Your Environment

* Franz Version used: 5.0.0
* Operating System and version: deepin 15.5

**Comment by adlk** [comment]
This has been discussed a couple of times in the last few days. Beta 15 will completely revamp the behaviour of this function/icon.
