### ISSUE TITLE
Features to consider!

### ISSUE THREAD

**Issue by Rafaal911** [meetfranz/franz#422]
### Expected Behavior

The changes on Franz are great, but there are a couple of improvements that I have in mind to make it better!
1. A Light/Dark Theme for the sidebar: Better for the eyes from some people like me as more stylish to fit to the current OS choose theme

2. An Auto-Hide Side bar option: That superb sidebar where the services are located could autohide after a couple of seconds to have more windows juts for the important things. 
Maybe could work also just and option on the View Menu which says "Hide Sidebar" with a specific Keystroke to show it again.

3. Keystrokes to jump between services. This is related to my second suggestion. Just like Slack, add the option to jump between services with the Keyboard. Normally a Ctrl+1/ Cmd+1 is perfect!

4. Smaller icons on sidebar: If my second and third suggestions doesn't convince you, them please give the option to make the sidebar icons smaller. Maybe with a predefined normal and small size or just as dynamic as the text is when pressing cmd+-(minus symbol)

5. A better Mute icon: Now the bell doesn't communicate in a easy an understandable way what it actually means. For me means "notifications" or "messages". A speaker with the waves of sound could work better.

6. Group services by topics: The user could arrange the services by topics such as Personal (WhatsApp, Messenger) and Work (Slack groups, Trello, etc), and just like that expand and colapse this groups by need. There are situations when I could like to chat in my personal groups without being aware that there are all my work services as well.
![1](https://user-images.githubusercontent.com/16694630/33719732-7786bbaa-db40-11e7-9cbc-85a87557cb98.png)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: macOS 10.13.1

**Comment by BrianGilbert** [comment]
@Rafaal911 

Several of those exist or are planned
3. Already exists, check the services menu (CMD+[service number])
4. Planned
5. This is the same icon as used used by many services to mute notifications, unlikely to be changed.
6. Planned, see some early mockups at: https://github.com/meetfranz/franz/issues/415#issuecomment-349863500

**Comment by Rafaal911** [comment]
Thanks Brian for your reply!
What about 1 and 2? :)

Cheers,
Rafael

**Comment by BrianGilbert** [comment]
@adlk will have to answer those two

**Comment by adlk** [comment]
@Rafaal911 First of all, thanks for your effort and great explanation :)

1. There is already a discussion in #49 and even a PR #362 
The PR is not yet ready to be merged but it is already a good direction. I expect to ship a fully operational dark theme in the next two months.

2. This is nothing I have thought about yet. As this is something completely new and untracked, I'd suggest that you open a separate feature request here on Github using the [feature proposal template](https://raw.githubusercontent.com/meetfranz/franz/master/.github/FEATURE_PROPOSAL_TEMPLATE.md).
5. The mute icon right now _is_ misleading. But it's actually not the icon, it's the functionality. A revamped mute button is coming with beta 15.

I'm going to close this issue and wait for the feature proposal. Thanks!

**Comment by alecive** [comment]
The auto-hide behavior is actually a great idea!

**Comment by Rafaal911** [comment]
Hi Guys,

A questions:

Is possible to reduce the memory consumption of Franz in a next release? Now I am using 4 services (WhatsApp, Twitter and 2 slack workspaces) and checking on my activity monitor I see that Franz alone takes around 1GB from my memory. That is a lot!
And why are there so many Franz Helper?

Thanks!

 				
Rafael Mongelos Martens - Industrial Designer
mail: raf.mongelos@gmail.com <mailto:raf.mongelos@gmail.com>
telephone:: +595 961 411 241 <tel:+491792797303>
 <http://bit.ly/portfolio_rafael_mongelos> <https://de.linkedin.com/in/rafaelmongelos> <https://500px.com/rafmongelos> <https://soundcloud.com/rafa-mngls>

**Comment by alecive** [comment]
@Rafaal911 please open a separate issue for that.

**Comment by Rafaal911** [comment]
ok!
