### ISSUE TITLE
Ubuntu 16.04: Telegram Messages & Contacts in same window

### ISSUE THREAD

**Issue by mimre25** [meetfranz/franz#424]
In Telegram, first we can only see the contacts (see screenshot1)
upon clicking one contact, we only can see the chat but not the contacts anymore (see screenshot2)

### Expected Behavior

I assume, the idea of the 2 windows we can see in the screenshots, is that the contacts stay on the left and the chat goes on the right (screenshot 1), or the other way round (screenshot 2).
web.telegram.org lists the contacts on the left and the chat on the right

### Current Behavior

Message/Contact windows messed up.

### Screenshots (if appropriate):
Screenshot 1:
![telegram1](https://user-images.githubusercontent.com/2582811/33725839-59b14edc-db41-11e7-9577-e25200af25c6.jpg)
Screenshot 2:
![telegram2](https://user-images.githubusercontent.com/2582811/33725867-7a181e9e-db41-11e7-8b6d-92ca6a23064f.jpg)

### Possible Solution

I assume there is just a wrong target window when Franz reacts to contact selections.

### Steps to Reproduce (for bugs)

1. Use Telegram as Service
2. click on one contact

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Ubuntu 16.04

**Comment by adlk** [comment]
I can't reproduce this issue. Is this happening for anyone else?

What you can try to do is tor quit Franz, delete the cache in `~/.config/Franz/recipes/Partitions` and start Franz again. Does the problem persist?

**Comment by mimre25** [comment]
There is no folder called "Partitions", but a folder for every service. Deleting the telegram folder didn't solve the problem tho.

I will try to reproduce the problem in the coming days on another machine.
Could it be a problem with importing the settings from Franz 4?

**Comment by adlk** [comment]
A reproducible solution would be great!
The importer does nothing else than creating a new service entry. To date, no cache is imported.

**Comment by mroeling** [comment]
I think this has to do with the switch between desktop and mobile version of telegram. The screenshots show the mobile version. In Slack we talked about this specific issue: https://meetfranz.slack.com/archives/C5ULLT74P/p1511424081000161
So if this is indeed the same problem, it should be solved after the fix by @nemilya

**Comment by mimre25** [comment]
I don't have slack, but I just tried to reproduce the bug on my private machine (Ubuntu 14.04) and it doesn't happen.

Telegram was asking to switch to the Desktop version at startup indeed. I did so, and it worked fine.
Issue still on my work machine, so if you could copy the fix in here, that'd be great.

**Comment by mimre25** [comment]
So I could "fix" it. 

Just needed to go to the settings and click "switch back to Desktop Layout".

Now it looks like expected!

Thanks for the help!
