### ISSUE TITLE
Can't open Service Developer Tools

### ISSUE THREAD

**Issue by agodlydeciple** [meetfranz/franz#425]
When trying to toggle service developer tools in the latest version 5 beta, nothing appears.

### Expected Behavior

- Click on 'View' -> 'Toggle Service Developer Tools'
- Service Developer Tools open up

### Current Behavior

- Click on 'View' -> 'Toggle Service Developer Tools'
- Nothing Happens

### Possible Solution

 - Fix menu event handler to launch Service Developer Tools

### Steps to Reproduce (for bugs)

1. Click on 'View' -> 'Toggle Service Developer Tools'

### Context

- Can't test new service integration prior to submitting deploy request.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 x64

**Comment by adlk** [comment]
I can't reproduce it. Is the service you want to debug enabled in your tab bar? Any chance the dev tools are opened in background?

**Comment by agodlydeciple** [comment]
Hey @adlk The service is not currently in my tab bar, does it need to be? If so, where do I place my service files so that I can add it to the tab bar? 

The dev tools were not opened in the background.

**Comment by adlk** [comment]
Everything you need to know can be found here: https://github.com/meetfranz/plugins/blob/master/docs/integration.md

If you have further questions, please feel free to join our [Community Slack](http://slack.franz.im)
