### ISSUE TITLE
No login feature request

### ISSUE THREAD

**Issue by TheKarlo95** [meetfranz/franz#429]
Currently you have to sign up and login to use Franz. Since I see no benefit in doing this other than syncing which I don't need I would like an option to use Franz without connecting to Franz backend service.

### Feature Description
Using Franz without login option like it was before v5.

### Motivation and Context
For the most users Franz account is useless and Franz just seem to intrude users privacy by introducing, for the most people, unnecessary backend service.

**Comment by adlk** [comment]
Duplicate of #71

**Comment by joubertredrat** [comment]
@adlk #71 is locked.

Today I have a micro "internet" environment running on a local DMZ without access to internet (on this network I run webservers, dns, mx, irc and other services for research propourses). 

On this network I can't use Franz 5 because it require login to work :(
