### ISSUE TITLE
Franz Premium - Rocket Chat service doesn't show unread message count/notification

### ISSUE THREAD

**Issue by Nosferous** [meetfranz/franz#431]
### Expected Behavior
When I am away from Rocket Chat service and get a message. I expect that my service icon should have a numerical counter next to it showing me I have x Unread notifications in that service.

### Current Behavior
If I am away from Franz and receive a message in Rocket Chat service. When I view Franz my Rocket Chat service icon does not have a notification count next to it. So when I am in another service I am unaware I have unread messages in Rocket Chat.

### Screenshots (if appropriate):
This is a screenshot of having a fellow tech send me a message in Hangouts and Rocket Chat while I was away from the service. As you see Hangouts has a numerical counter of the missed message. But Rocket Chat appears I have no missed messages, when in fact I have 1 unread direct message.
<img width="737" alt="screen shot 2017-12-08 at 2 38 54 pm" src="https://user-images.githubusercontent.com/22967603/33788181-a3afa44a-dc25-11e7-80dc-3394320827d4.png">

### Steps to Reproduce (for bugs)
1. Have Franz and Rocket Chat service signed in open but be away in another application or service
2. From another account send a message to your "away" instance of Franz - Rocket Chat.
3. You may get a notification from your operating system (ie: MacOS Notifications) from Franz. But your Rocket Chat icon will be absent of numerical counter indicating unread messages.

### Context
Because I am switching applications/services a lot. If I don't have an obvious message counter, I am not aware I'm getting messages. This is leading me to randomly switching to my Rocket Chat service in Franz to discover I have dozens of unread messages.

### Your Environment
**Both Sender and Receiver machines:**

* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: OSX 10.11.6

**Comment by adlk** [comment]
@Nosferous thanks for the report. What version of RocketChat are you using?

**Comment by Nosferous** [comment]
@adlk 
Rocket.Chat Version: 0.59.4 - Commit Tag: 0.59.6

snap install of Rocket.Chat hosted on Ubuntu 16.04 LTS

**Comment by adlk** [comment]
The RocketChat recipe is now updated with new RocketChat selectors.
https://github.com/meetfranz/recipe-rocketchat/commit/792e6115596f9c51ab827f86f5f4e248d2f112de

To manually trigger the updater: 
- Go to Settings
- Scroll down
- Check for updates

**Comment by adlk** [comment]
@Nosferous we usually report just one message per channel. If you would have 3 in _IT_SupportTeam_ and 6 in _IT_AllDepartments_ Franz will just display 2 unread messages. There is also a difference if it's a direct mention (numeric count) or just a general channel message (dot indicator). 

We've made this decision after releasing Franz v1 as quite a lot of people (us included) reported that having 34 unread messages in e.g. Slack was creating unnecessary stress even though it just came from 2 channels – and this is just from one service. It might take some time to get used to but we believe that this is the "healthier" approach in busy environments.

**Comment by Nosferous** [comment]
@adlk Thank you for the explanation. I get your reasoning. For the GMail service I wish I could turn off the counter all together as an option. I already know I have unread email all day every day. So seeing it's building number stresses me out. Completely makes sense.

**Comment by adlk** [comment]
Yes, your screenshot with the unread gmail messages freaked me out a bit 😅  

With beta 15, we're introducing a more fine grained control for the message badge.
- toggle badge for services
- toggle badge when services notifications are disabled

**Comment by adlk** [comment]
Thanks a lot! You are very welcome. If anything comes up, you know where to find me.
