### ISSUE TITLE
add flatpak support

### ISSUE THREAD

**Issue by tomasabril** [meetfranz/franz#432]
Feature request:
add flatpak support using the flathub.org repository.

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

With beta 15 we will support .deb, appimage and tar.gz deployments. While I'm usually not against adding support for a new distribution channel there needs to be enough demand for it as every additional channel is an additional overhead.
