### ISSUE TITLE
[Feature request] Unable to delete the group in Telegram

### ISSUE THREAD

**Issue by sfksuperman** [meetfranz/franz#435]
In telegram, im unable to LEAVE some of the groups and the one in which im able to leave, can't delete the group from my conversation list. Please look into the matter.

**Comment by adlk** [comment]
It actually is possible. 
- Select the group in your chats list
- On the top, click on the groups name
- An overlay with settings for this group appears and somewhere in the middle, you have the option to leave the group.

**Comment by sfksuperman** [comment]
Leave is okay but why can't i delete the group conversation from my
conversation list?

**Comment by adlk** [comment]
As soon as you leave a group your conversation will be deleted and removed from your conversations list. 
<img width="471" alt="leave" src="https://user-images.githubusercontent.com/3265004/33824888-1ad2923a-de60-11e7-8117-838650add850.png">

If you think you have found a but with the telegram web interface, please report it at the telegram repository: https://github.com/zhukov/webogram

**Comment by sfksuperman** [comment]
That option is not available within franz app and i need it. If you need a
screenshot i can provide you.

**Comment by adlk** [comment]
A screenshot would be great. (Also my screenshot was made with Franz)
Please keep in mind that Franz _does not_ provide the actual Telegram client. It is using the web.telegram.org client instead

**Comment by sfksuperman** [comment]
Here is the screenshot. and it has only LEAVE option, and its also for
every group i follow, only LEAVE option is available.

**Comment by adlk** [comment]
Unfortunately that doesn't work via email :(

**Comment by sfksuperman** [comment]
What doesn't work via email?

**Comment by adlk** [comment]
The image upload

**Comment by sfksuperman** [comment]
then what shud i do?
