### ISSUE TITLE
Unable to show Franz when switching from two screens to one

### ISSUE THREAD

**Issue by fentes** [meetfranz/franz#436]
I normally use my windows pc with two screens. When I place the window at one screen and then disconnect this screen, it is not possible to use Franz. The window stays at the outside of my primary screen. Restarting the pc or Franz has no effect.

When minimize the app via the taskbar there is a short "animation" moving the app  from the outside of the screen to the taskbar.

Environment
* Franz Version used: 5.0.0-beta14
* Operating System and version: Windows 10  10.0.15063 Build 15063

**Comment by adlk** [comment]
This is related to #222 
> If this problem happens again (before I have a fix for it) go to `%AppData%\Roaming\Franz\settings` and delete the `window-state.json`.

**Comment by haraldox** [comment]
Duplicate of #222
