### ISSUE TITLE
web interface for user with franz account

### ISSUE THREAD

**Issue by as3mbus** [meetfranz/franz#437]
### Feature Description
Web based client that work just like desktop client

### Motivation and Context
I've noticed that franz now hav it's own account system working and saving all the services user uses. (CMIIW). 
With that known i think it might be cool if franz have it's own web-based client or interface, That make it possible for user to just log in via web browser and have access to all of it's service in 1 tab.

**Comment by adlk** [comment]
I wish this would be possible. Unfortunately there are so many limitations and issues that come up with a web based client. It needs to be done with frames or requires an e.g. chrome extension to enable webviews. The first solution is not possible with most services as e.g. facebook messenger doesn't allow being put into an iframe. The second might be feasible with a lot of hacking but then again is everything else than an accessible web app for all browsers and users.

On the Franz website you will soon be able to manage your account but there will be no messaging. :(
