### ISSUE TITLE
[Feature request] Unread notification count in system tray

### ISSUE THREAD

**Issue by andreasmalling** [meetfranz/franz#439]
### Feature Description
The system tray should have the possibility to show the total number of unread messages, and include a list off added services in the dropdown menu followed by their individual unread counts. When clicking a service, the main window should present that given service to the user.

### Motivation and Context
This would make navigation faster when browsing new messages, without having to open the main window first.

**Comment by haraldox** [comment]
not sure what you mean exactly, but this is already implemented in the newest releases of Franz 5.

**Comment by haraldox** [comment]
related to https://github.com/meetfranz/franz/issues/558
