### ISSUE TITLE
Mining not working

### ISSUE THREAD

**Issue by ManuelmJY** [meetfranz/franz#440]
I've enabled mining in FRANZ, but it doesn't show any calculations per sercond.

**Comment by BrianGilbert** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template: 
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by ManuelmJY** [comment]
Ok...
In 5.14 there is no option for Mining anymore.
