### ISSUE TITLE
Facebook Messenger: Your Request Couldn't be Processed

### ISSUE THREAD

**Issue by dfooter** [meetfranz/franz#443]
Trying to sign into Facebook Messenger, and I get an error page with the following message:

"Your Request Couldn't be Processed"

Was able to sign into to Messenger with Safari and no problem. There was one unread message.

Have had no problem signing into Messenger in the past, but haven't checked in the last week, problem appeared this morning.

![screen shot 2017-12-11 at 8 35 10 am](https://user-images.githubusercontent.com/9769985/33842032-402be0d4-de4e-11e7-840f-224371e3852e.png)

### Your Environment
* Franz Version used: 5.0.0-beta.14.451
* Operating System and version: MacOS 10.3.2 beta

**Comment by adlk** [comment]
When restarting Franz, does the problem persist?

**Comment by dfooter** [comment]
It seems to have resolved all on its own, thanks!


+1 858 342-2967
dfooter @ Messaging and Social Media Apps

On Dec 13, 2017 at 3:15 AM, Stefan Malzner <notifications@github.com> wrote:


When restarting Franz, does the problem persist?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meetfranz/franz/issues/443#issuecomment-351361276>, or mute
the thread

**Comment by thelocalskinny** [comment]
I am having this exact same issue, with both my Macbook and my Windows 10 laptop. I tried restarting Franz but the error persists. Any idea on next steps?

**Comment by visuelz** [comment]
@thelocalskinny I am having the same issue at the moment with my mac. I think it's on Facebook's side.

**Comment by Amal-Boban** [comment]
i have the same problem but when using chrome from mobile i could login just cant login from laptop,
