### ISSUE TITLE
[Bug] App unexpectedly closes when choosing the correct spelling from spell check list

### ISSUE THREAD

**Issue by Taitosoku** [meetfranz/franz#444]
### Current Behavior
Application closes if you use the spellcheck functionality 
Experienced in sub-apps:
- facebook messenger
- slack
- discord

### Steps to Reproduce 

1) choose a sub-app(Slack) 
2) start typing a message with at least one word spelled incorrectly
3) right click the word to get suggested spellings from spellcheck
4) select one of the suggested spellings
5) application will close on you

### Your Environment

* Franz Version used: 4..0.4
* Operating System and version: Mac, High Sierra

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)
