### ISSUE TITLE
Optional tabs for services instead of the sidebar

### ISSUE THREAD

**Issue by shlema** [meetfranz/franz#447]
It'd be nice to be able to switch to a horizontal version of the sidebar (the way it was in Franz 4.x). I normally use Franz on a portrait-oriented screen, which means that the sidebar is eating up precious screen real estate.

**Comment by dannyqiu** [comment]
I think this was already asked in #156, and that this feature will be shipped in a later version of Franz

**Comment by shlema** [comment]
you're right, I missed it. should I remove the post?

**Comment by adlk** [comment]
Don't worry, I'm just going to close it :)
