### ISSUE TITLE
[Solved] Microsoft Teams browser version not supported

### ISSUE THREAD

**Issue by firsttiger** [meetfranz/franz#450]
<img width="1117" alt="capture" src="https://user-images.githubusercontent.com/306340/33888261-86444b0c-df1a-11e7-8cb0-ad03d2cf6af3.PNG">

### Expected Behavior

When you go to the Microsoft Teams tab, I expect the Teams site to load 

### Current Behavior

The app is coming up with the message:

Hmm. Your browser version isn't supported. Quickest solution? Download the desktop app.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10

**Comment by adlk** [comment]
I shipped an update for that earlier today. Unfortunately it's a bit trickier than usual :(
I assume that due to heavy caching on their side you need to follow those steps to get MS Teams working again:

- Check for updates (in Settings). 
- After updating the service delete MS Teams
- Restart Franz
- Add MS Teams again.

Sorry for the inconvenience.

**Comment by CSJudd** [comment]
Working again, THANKS!!

**Comment by Briones** [comment]
Did you release a new version for Franz for Mac? I don't have any updates, same problem.

**Comment by adlk** [comment]
Service updates don't require an app update. It is indicated by the blue banner on the bottom that your services have been updates. Once this is done, follow the steps from above.

**Comment by jeroensak** [comment]
Mac is still affected

**Comment by adlk** [comment]
@jeroensak Have you tried the solution mentioned above?

**Comment by adlk** [comment]
@jeroensak can you please specify your exact environment (macOS version + Franz Version) as I've tested it on a few different machines and it is working at least here.

**Comment by jeroensak** [comment]
Hello Stefan,

Franz is on 5.0.0-beta.14.
My mac is on 10.13.2 (high sierra)

Is there a newer version for mac available? As this is the exact version OP said his issue was on.

Thx in advance,
Jeroen


On 21-12-17 12:27, Stefan Malzner wrote:

@jeroensak<https://github.com/jeroensak> can you please specify your exact environment (macOS version + Franz Version) as I've tested it on a few different machines and it is working at least here.
