### ISSUE TITLE
Tray icon single click should open main window

### ISSUE THREAD

**Issue by theosophist123** [meetfranz/franz#454]
### Expected Behavior

Tray icon single click should open main window
### Current Behavior

Tray icon single click opens context menu and one has to chose "show franz" from there.

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by ajelsinga** [comment]
I don't see any progress on this. Should we open a new issue on this? I agree with @theosophist123 that this is something we want.

**Comment by omercsp** [comment]
+1

Also, when the window is opened, but in the background, clicking on the tray icon should foreground the Franz window, like clicking on in the the task bar. (Linux, KDE).
