### ISSUE TITLE
Cannot open links from Franz services

### ISSUE THREAD

**Issue by heleneshaikh** [meetfranz/franz#457]
### Expected Behavior
When I click on a link within any of the Franz services, I expect to be redirected to that page.

### Current Behavior
When I click on a link within Gmail, Twitter, Messenger, Slack, etc, a new blank page open instead of redirecting me to that link. 

### Context
This issue makes using Franz really difficult

### Your Environment
* Franz Version used: Version 5.0.0-beta.14
* Operating System and version: Mac OS High Sierra

**Comment by adlk** [comment]
I assume you are using chrome?
If yes, this is a known issue with chrome. You need to restart your browser and everything should be back to normal. 

Related #272
