### ISSUE TITLE
Clicking on links opens an empty chrome window

### ISSUE THREAD

**Issue by boozi2** [meetfranz/franz#462]
inside Slack/ Whatsapp (which is the only accounts i have connected) clicking on URLs is opening a blank new browser window.

Im on the latest Version 5.0.0-beta.14 (5.0.0-beta.14.451)
Using a macbook pro 10.13.1 High Sierra

**Comment by adlk** [comment]
Duplicate of #264 (solution is there as well)

We encourage everyone to use the search before creating a new issue!

**Comment by vk-sourcefuse** [comment]
This simple solution worked for me https://askubuntu.com/questions/820900/slack-fails-to-open-links-in-ubuntu-14-04
