### ISSUE TITLE
Whatsapp - automatic media download - how disable?

### ISSUE THREAD

**Issue by TheCrazyDreamer** [meetfranz/franz#464]

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md
