### ISSUE TITLE
Add Interface for HTTP Auth

### ISSUE THREAD

**Issue by xanderiel** [meetfranz/franz#465]
### Expected Behavior
1. I add the Slack service for our company instance (using SSO login, not just email/password).
2. I navigate to the Slack service and click "Ping ID SSO Login" (from our company instance).

In the native Slack, the following happens now:

3. An HTTP Auth notification window pops up asking for company username and company password (through Ping ID)
4. Standard Slack UI comes up and is ready to use.

### Current Behavior
As opposed to the native Slack client, the following happens in Franz:

3. A white screen appears, nothing happens anymore.

### Screenshots (if appropriate):
Can share privately.

### Possible Solution
I presume it's only about Franz being able or allowing to show the standard HTTP Auth notification/input windows.

### Steps to Reproduce (for bugs)
As above.

### Context
Logging in to Slack on our company instance.

### Your Environment
5.0.0-beta.14.451

**Comment by mroeling** [comment]
A solution could be to add a username and password field in the settings page. The link for the connection could then be updated (in case of HTTP AUTH login) to username:password@domain, or by using more native solutions for http auth in electron (like [here, app::event-login](https://github.com/electron/electron/blob/master/docs/api/app.md#event-login))

**Comment by caioquirino** [comment]
@mroeling Maybe it's better to ask for the Basic HTTP Auth when it's requested, like in standard Slack UI for example, so the Franz itself don't need to have a mechanism to store the password securely, but the "inside" application itself :)

**Comment by xanderiel** [comment]
My assumption is that several people will be affected when the login goes through SSO instead of standard user/pass. Hopefully this makes the roadmap :)

**Comment by chrise92** [comment]
+1 to this. I experience similar behavior, except in my case, Franz redirects to my SSO home page, and a new Chrome tab is opened with Slack web.

**Comment by bracketslash** [comment]
+1, currently cannot use Facebook Workplace or Slack with Franz because SSO uses HTTP auth

**Comment by jpruetting** [comment]
+1 for this. Same issue with Microsoft Teams

**Comment by jpruetting** [comment]
Temporary workaround:

Franz > View > Toggle Service Developer Tools > Console

Replace USER and PASSWORD with your credentials and use this command:
```js
window.location.href = window.location.protocol + "//" + "USER" + ":" + "PASSWORD" + "@" + window.location.hostname + (window.location.port ? ":" + window.location.port : "") + window.location.pathname + window.location.search
```

User and password values must be url-encoded.

**Comment by xanderiel** [comment]
It appears this was fixed. I can now see our corporate SSO page and log in. Sometimes I need to reload the Slack instance in Franz but that's okay-ish.

**Comment by JiDoan** [comment]
I'd still benefit from being able to login using HTTP Digest auth. Will this request see the light of day?
