### ISSUE TITLE
Some facebook chats are stuck loading forever

### ISSUE THREAD

**Issue by dbogdanov** [meetfranz/franz#473]
Facebook chats are stuck loading forever for some of my contacts.

### Expected Behavior
Clicking on any facebook contact, I should see the history of conversation.

### Current Behavior
Clicking on some chats with unread messages, the history of conversation is empty being stuck on loading:

![stuck](https://user-images.githubusercontent.com/409668/34043232-6d3294ec-e1a0-11e7-99ed-790342781c17.png)

Restarting Franz solves this issue. I don't have any problem loading those chats from messenger.com.

### Your Environment

* Franz Version used: 5.0.0-beta13
* Operating System and version: Ubuntu 16.04

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
