### ISSUE TITLE
Drop images to Whatsapp and Facebook Messenger don't work and Crashes the service.

### ISSUE THREAD

**Issue by Kasukisan** [meetfranz/franz#476]
![image](https://user-images.githubusercontent.com/34579675/34051102-4e7e25da-e18b-11e7-8795-67b6ce08778c.png)

**Comment by adlk** [comment]
Duplicate of #72

**Comment by BigFunkyMan** [comment]
Hallo,
on my PC are the same Problems!
if i drop & Paste a picture in WhatsApp of Facebock franz crashed :(
