### ISSUE TITLE
Password forgot

### ISSUE THREAD

**Issue by MarcoBerb** [meetfranz/franz#477]
I have forgotten my franz password, how could i fix it?
It seems there is no way for me to send an email to my email account like in most of the other services online.
Do you have any solutions?

### Your Environment

* Franz Version used: 5
* Operating System and version: Ubuntu 16.04.3

**Comment by adlk** [comment]
Why don't you use the "Reset password" option?
<img width="520" alt="bildschirmfoto 2017-12-19 um 14 10 44" src="https://user-images.githubusercontent.com/3265004/34158635-7dc7443c-e4c6-11e7-9497-dd1e768b09e3.png">

---

_As a little side note:_ a few users got confused when switching from Franz 4 to Franz 5 as v4 had no accounts.
