### ISSUE TITLE
Google Hangouts not in English! 

### ISSUE THREAD

**Issue by rinaabadi** [meetfranz/franz#479]
I have Google Hangouts on Franz. A couple of weeks ago, Hangouts just switched over to Hebrew. No idea why. And now I can't change it back to English. I tried everything (Franz settings, Google hangout settings within Franz, google settings within regular browser, closing the app and reopening, removing hangouts and re-adding, etc.) and it's still in Hebrew. I might be missing something. But would be great if you can help!

### Expected Behavior
Google Hangouts in english

### Current Behavior
Google Hangouts in Hebrew (according to region) although my settings are all set to EN in Google. (when i open Hangouts in Chrome or other browser, it comes up in EN)

### Screenshots (if appropriate):
https://screencast.com/t/hgX53kliWxF
https://screencast.com/t/02ayRYL1qcA

### Possible Solution
YOUR CALL, just help me :-)

### Steps to Reproduce (for bugs)
1. Open Franz.
2. See Hebrew Google Hangouts.
3. Get annoyed because nothing changes it.

### Context
Hebrew is RTL and is painfully annoying to get used to 

### Your Environment
* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: macOS High Sierra version 10.13.1

**Comment by adlk** [comment]
This issue has already a few duplicates. It is known and will be fixed soon.
