### ISSUE TITLE
Google Hangouts shows numbers, but no names

### ISSUE THREAD

**Issue by mimre25** [meetfranz/franz#481]
When using google Hangouts, the messages/chats are shown with the phone numbers instead of the saved name of the person.

### Expected Behavior

Show the names and the number if possible, same as in Franz 4 (screenshot 2).

### Current Behavior

Hangout shows the numbers only (screenshot 1).

### Screenshots (if appropriate):
Franz 5 (current):
![franz5](https://user-images.githubusercontent.com/2582811/34081591-1b658a06-e31d-11e7-98b8-5bf0e3090eac.jpg)
Franz 4 (old):
![franz4](https://user-images.githubusercontent.com/2582811/34081596-2f8de186-e31d-11e7-964c-2c7705ab0d97.jpg)

### Steps to Reproduce (for bugs)

1. Use Hangouts with Franz 5

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: Ubuntu 14.04/16.04

**Comment by adlk** [comment]
This issue has already a few duplicates.
