### ISSUE TITLE
Ugly menu bar icon in Ubuntu after 5

### ISSUE THREAD

**Issue by dafeder** [meetfranz/franz#483]
The icon that displays since upgrading franz client in ubuntu is ugly, the wrong color, and missing the message count.

### Expected Behavior

Menu bar icon should be white, and display an unread count.

### Current Behavior

Icon is scaled incorrectly, and only displays a red dot if any unread messages. 

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/309671/34118148-eda541fe-e3eb-11e7-8053-29997d15aabd.png)

### Context

Mostly just ugly, but missing unread count is a regression.

### Your Environment

* Franz Version used:  5.0.0-beta.14
* Operating System and version: Ubuntu 16.04

**Comment by adlk** [comment]
Duplicate of #233
