### ISSUE TITLE
Add a "Copy URL" menu / contextual-(right-click) option

### ISSUE THREAD

**Issue by surferking** [meetfranz/franz#484]
### Feature Description
Many times in an application I need the URL of the page to reference.

A full address bar is unnecessary and would somewhat defeat the seamlessness of the experience, however a menu option to copy the current page URL would be very handy.

### Motivation and Context
* Standard browser feature but missing here.
* Helps speedy communication of page-related issues or references.

**Comment by adlk** [comment]
This is actually already implemented but a bit buggy. This was already improved and will ship with the next beta.

As this is something that is already done (and tracked internally) I'm going to close this issue.

**Comment by oojacoboo** [comment]
How is this implemented?
