### ISSUE TITLE
Skype login is in arabic even if English is selected language

### ISSUE THREAD

**Issue by rodrigolopezguerra** [meetfranz/franz#485]
I add the skype service and appears in arabic even if my PC and all the services are in english

### Expected Behavior
Login form should be in the selected lenguage

### Current Behavior
I have english as language , but skype login is in arabic (i think)

### Screenshots (if appropriate):

<img width="537" alt="2017-12-19_10h21_34" src="https://user-images.githubusercontent.com/3514141/34159049-804775b2-e4a6-11e7-9099-b130bfb70d2c.png">
<img width="704" alt="2017-12-19_10h18_26" src="https://user-images.githubusercontent.com/3514141/34159053-824b04e6-e4a6-11e7-9b1a-615d05179bdd.png">

### Steps to Reproduce (for bugs)
1. Open a fresh account.
2. Added slack/whatsapp/messegner/hangout
3. Add Skype
4. Login is in the wrong language

### Context
use the skype service

### Your Environment
Windows 10
Last version of Franz

**Comment by adlk** [comment]
This issue has already a few duplicates. It is known and will be fixed soon.
