### ISSUE TITLE
Maligned design

### ISSUE THREAD

**Issue by theqse** [meetfranz/franz#486]
The picture says it all. 

Please push the social services to be inline with top of the red box. Then the window tab width is consistent and it doesn't look odd.

Thanks. 

<img width="347" alt="screen shot 2017-12-20 at 10 03 32" src="https://user-images.githubusercontent.com/16494547/34183141-64e4ea6c-e56d-11e7-8b66-8f36a231a1c6.png">

**Comment by Wouter0100** [comment]
I don't see the issue. What is not correctly aligned here? The Franz frame seems to be correctly aligned with the recipe window.

**Comment by adlk** [comment]
As @Wouter0100 already mentioned, everything is in order here. If you eg. move line to be your first service the first tab has to respect a new virtual line.
