### ISSUE TITLE
Default Browser

### ISSUE THREAD

**Issue by NNois** [meetfranz/franz#487]
Hi,
I would like to request a default browser selection... 
Thank you for your wonderfull app !

**Comment by catapulko** [comment]
Hi,
I add to this that it would be great if the default browser selection could be overridable per service.

The use case is:
- use browser A to handle URLs in Services as default setting, BUT
-- use browser B to handle URLs in Service X
-- use browser C to handle URLs in Service Z

Might help to keep a bit of separation between multiple personalities ;)
