### ISSUE TITLE
High saturation on MacBook Pro Retina

### ISSUE THREAD

**Issue by rwkyyy** [meetfranz/franz#489]
Chat images and emojis are more intense in colors than the browser ones.

### Expected Behavior

The color should be calibrated.

### Current Behavior

Color is not calibrated

### Screenshots (if appropriate):
https://i.imgur.com/boVifg9.png left Franz; right Google Chrome. (hope is noticeable).

### Possible Solution

Add a color profile for calibrating the colors.

### Steps to Reproduce (for bugs)

1. log into messenger.com client (browser and franz)
2. open a chat
3. use emoji / stickers

### Context

It affects users because it's a very high saturation.
I've noticed this on my newer MacBook Pro 2017, on my old MacBook Pro 2015 this was not an issue, it's most probabbly the display difference and in the absence of a color profile, it renders them very intense.

### Your Environment

* Franz Version used: 5.0.0.beta-14
* Operating System and version: macOS High Sierra 10.13.2

**Comment by adlk** [comment]
I have experienced a slightly different color rendering from browser to browser but nothing so extrem than you show in your screenshot. Unfortunately this is an upstream issue and can't be solved by us. However looking into this issue as an example gives me high hopes that this might soon be an issue of the past https://github.com/electron/electron/issues/10732 (Franz is at Chrome 58)

I'm closing this issue as it should be resolved anyway as soon as we upgrade electron.
