### ISSUE TITLE
URLs Coming From Skype Do Not Open In Default Browser

### ISSUE THREAD

**Issue by georgecarstoiu** [meetfranz/franz#497]
### Expected Behavior

Clicking a link posted by one of my contacts, is opened in the default browser (in my case Chrome) as a new tab - see behavior for Messenger.

### Current Behavior

A Franz window is opened.

### Steps to Reproduce (for bugs)

1. Open link from Skype

### Context

Not opening the link in the default browser, means that the user is not logged in - no access to cookies, stored passwords etc. This can be a hassle, as now users need to manually copy the link and then paste it in their browser.

### Your Environment

* Franz Version used: 5.0 Beta 14
* Operating System and version: Win10

**Comment by BrianGilbert** [comment]
Please recreate issue in the relevant service repository:
https://bitly.com/franz-plugins
