### ISSUE TITLE
HipChat cmd-c not working

### ISSUE THREAD

**Issue by ylluminate** [meetfranz/franz#50]
I've found that cmd-c is not working to copy content in HipChat content. Right click and then selecting Copy works, but cmd-c is not.

**Comment by Kotys** [comment]
Hello, I'm MacOS High Sierra (10.13).
This bug appears on all my services (HipChat, FB Messenger, WhatsApp).
I think, it's not service relevant, it will be something global for webview and event handlers.

I'll try to find solution and send PR today.

**Comment by adlk** [comment]
Duplicate of #33
