### ISSUE TITLE
Facebook on Franz

### ISSUE THREAD

**Issue by luluvulcain** [meetfranz/franz#503]
Would it be possible to integrate Facebook into Franz please? 
Cordielament Luluvulcain

**Comment by BrianGilbert** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template: 
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by haraldox** [comment]
@luluvulcain This repository is only for the Franz client. Please use [this form](http://bit.ly/franz-service-request) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
