### ISSUE TITLE
Franz config directory using a lot of disk space

### ISSUE THREAD

**Issue by jancoow** [meetfranz/franz#504]
Hi,

The franz config dir, under ~/.config/Franz/Partitions is using 2.4GB! Why is it using so much disk space?

![image](https://user-images.githubusercontent.com/9000749/34320281-ee901652-e7f6-11e7-9633-6d84c2a28d0e.png)

**Comment by BrianGilbert** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template: 
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md

**Comment by haraldox** [comment]
addressed in already merged pull request, soon to be released

**Comment by pvinis** [comment]
This still happens. Mine is 5 GB right now..

**Comment by WladyX** [comment]
Yup, here also.

**Comment by mloskot** [comment]
I believe this needs to be reopened or it deserves a new issue.

I'm using Franz 5.3.3 on Windows 10 (10.0.1836) and File > Settings > Clear Cache does not do anything. The waiting cursor is spinning forever, no files seem to be removed, the clearing needs to be abandoned as it never finishes.

**Comment by pvinis** [comment]
I feel Franz falls into this category of app that  I really like and I really dislike at the same time :p

**Comment by chris230790** [comment]
I've resolved this issue by uninstalling the app. No, I didn't reinstall it.

**Comment by esaruoho** [comment]
I'm still using the app, but it is taking something like 1gb. I'd prefer it didn't. What should I do?

**Comment by guydepauw** [comment]
Franz 5.4.1.1703 is using 3.3Gb disk space on my macbook, despite having cleared the cache. Any suggestions?

**Comment by viplezer** [comment]
5.6.1 and taking 8 GB

**Comment by opensourceame** [comment]
I just uninstalled Franz after discovering it was using 8+GB of space.
