### ISSUE TITLE
Franz keeps XFCE4 Power Manager from suspending the system

### ISSUE THREAD

**Issue by flamusdiu** [meetfranz/franz#505]
### Expected Behavior

System should kill monitors after 10 mins then suspect a bit after that.

### Current Behavior

Computer never sleeps with Franz running.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/1879197/34323685-d9946c22-e822-11e7-800a-c6adb594adb4.png)

### Steps to Reproduce (for bugs)

1. Open Franz
2. Check Xfce Power Manager (notice the inhibiting msg)
3.
4.

### Context

Trying to just use power settings to control my computer

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: 4.14.7-1-ARCH #1 SMP PREEMPT Sun Dec 17 19:13:39 UTC 2017 x86_64 GNU/Linux

**Comment by ichramm** [comment]
It is happening to me in KDE Neon:

![image](https://user-images.githubusercontent.com/487268/74790402-40906b80-5296-11ea-87d6-41b4d6257aa8.png)
