### ISSUE TITLE
No try icon on UBuntu 18.04

### ISSUE THREAD

**Issue by NohaTech** [meetfranz/franz#507]
Hi,
Franz don't show any try/menu icon in the upper menu when running on Ubuntu 18.04.

**Comment by Mando75** [comment]
Similar issue in Arch running gnome. You just get the generic application icon.

I installed franz from the AUR, https://aur.archlinux.org/packages/franz/

See screenshot, application loads normally, but when searching in the activities menu, or when displayed in dock, there is no application icon. 

![screenshot from 2018-01-06 20-32-20](https://user-images.githubusercontent.com/5854696/34646372-33f89c00-f323-11e7-9f73-aabe8976cb7b.jpg)

**Comment by bearnardoriain** [comment]
I had a similar issue on Ubuntu 16.04 LTS, but I got around it by installing the tweak tool (available at least for GNOME and Unity) and changing my icon pack to [Papirus](http://www.omgubuntu.co.uk/2016/07/how-to-install-papirus-icon-theme-ubuntu).

**Comment by adlk** [comment]
This will be fixed with the next update which is coming in the next few days.
