### ISSUE TITLE
Disable audio not working

### ISSUE THREAD

**Issue by angeldclh** [meetfranz/franz#509]
I'm using Franz 5.0.0-beta.14 on macOS High Sierra. I keep on hearing a sound when I receive a WhatsApp message despite having disabled audio by clicking the bell on the left down corner. What I want is to receive a notification but without sound.

**Comment by adlk** [comment]
Fixed in the next update which is coming in the next few days

**Comment by angeldclh** [comment]
Not fixed at all :( I can either have both notification and sound or none of them. 5.0.0-beta.15 (5.0.0-beta.15.607)

**Comment by dancsonth** [comment]
Has this fix been released?

**Comment by angeldclh** [comment]
In 5.0.0-beta.15 it's still there :(

**Comment by jsugg** [comment]
In fact, it still happens in 5.0.0-beta.15.607

**Comment by RazZziel** [comment]
Still happens 5.0.0-beta.17, at least in Google Hangouts

**Comment by grrowl** [comment]
Still happens in Version 5.0.0-beta.18 in Messenger (for one). I worked around it by setting Messenger's internal options to not play sound (not ideal, because sometimes I want sound).

**Comment by stefek99** [comment]
The sound keeps beeping ! ! !

![image](https://user-images.githubusercontent.com/249703/47153747-6095d080-d2d8-11e8-8f5d-f1bc822ad503.png)

# Major annoyance...

**Comment by TimoRotten** [comment]
Same problem. 

Franz 5 Beta on a Macbook Pro OSX (Sierra & now Mojave) with Whatsapp.

No matter what settings I use: it always beeps. It's driving me nuts.

I'm using an external audio interface for sound, not system sound.
