### ISSUE TITLE
Can not connect Telegram Service

### ISSUE THREAD

**Issue by FranzMeyer** [meetfranz/franz#51]
Meet Franz can not connect to my Telegram service

### Expected Behavior

meet Franz can not connect to Telegram service. i tried connecting with Telegram desktop client on same computer, and it works. Telegram on Mobile works as well..
I deleted the Telegram service in Meet Franz, and then tried to re-create it, and it does not allow the creation as it can not connect.
using WhatsApp service or Slack or Messenger or Twitter work in my meet Franz installation...

### Your Environment

* Franz Version used: 4.0.4
* Operating System and version: Mac OSX 10.12.6

**Comment by rwkyyy** [comment]
Hmm, weird, I am logged in on Telegram both on OS X and on Windows, it works for me. I think you should check your credentials / recheck your settings.

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
www.github.com/meetfranz/recipe-telegram
