### ISSUE TITLE
[Feature Request] [Mac] Organize favorite clients in Touch Bar with Icon

### ISSUE THREAD

**Issue by dontwantanaccounthere** [meetfranz/franz#510]
Hey there,
at the moment there are the first clients of the list shown in the Touch Bar with the full name of the client. When Names are long there only are 4 clients in it.
It would be nice if I could organize my favorite clients in the Touch Bar independently of the sorting in the main list at the sidebar. Also I prefer Icons instead of text in Touch Bar.
Thanks!

**Comment by adlk** [comment]
I'm planning to give the TouchBar more love in the future where this is already on my todo list. Closing this as it's tracked internally
