### ISSUE TITLE
Can't disable notification badge in macOS

### ISSUE THREAD

**Issue by alex5454w** [meetfranz/franz#511]
### Expected Behavior

I would like to disable the notification badge for Franz in my Mac's dock. For some reason, however, Franz does not appear in the Mac's notification settings in the system preferences so that I cannot diable the 'number of unread messages' badge in the dock. Can you fix this? 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
More fine grained control for your notification badges are coming with the next update.

**Comment by hulianbrox** [comment]
That function would be very much appreciated. The red notification badge in the dock is very distracting.
