### ISSUE TITLE
Ability to change image for Gmail account service

### ISSUE THREAD

**Issue by remyj23** [meetfranz/franz#512]
### Feature Description

It would be awesome if I could change the image of the separate Gmail services I have on my Franz account. Even possibly changing it to the image I have set on my Gmail account as Franz already does for the slack service

### Motivation and Context

This would allow users who have multiple Gmail accounts to easily differentiate between each Gmail account by using the image used in the service selection tab of Franz.

Ability to
### Mockups, Screenshots (if available):
<!--- A picture says more than a thousand words. --

**Comment by adlk** [comment]
Custom icons are coming with the next update.

**Comment by remyj23** [comment]
That's awesome to hear Stefan!

Thank y'all,

Julian

On Jan 10, 2018 5:27 AM, "Stefan Malzner" <notifications@github.com> wrote:

Custom icons are coming with the next update.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meetfranz/franz/issues/512#issuecomment-356561315>, or mute
the thread
