### ISSUE TITLE
Disable some Skype notifications

### ISSUE THREAD

**Issue by fabiofdsantos** [meetfranz/franz#513]
### Expected Behavior
Disable Skype notifications for chats with notifications turned off.

### Current Behavior
Franz keeps notifying me as soon as a new message is posted on chats with notifications turned off.

### Screenshots
<img width="323" alt="screen shot 2017-12-26 at 21 09 55" src="https://user-images.githubusercontent.com/8303937/34364925-adcc5cf0-ea82-11e7-85a8-8edfaaa8838a.png">

### My Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: macOS High Sierra 10.13.2

**Comment by haraldox** [comment]
anyone experiencing the same issue?

**Comment by jacoblo** [comment]
Same issue here. Think it is something about mentions in conversations. Clears if open Skype app and reload Franz.

**Comment by meridius** [comment]
Same issue here. 
And I don't think it is related to mentions. I get Franz notifications on Skype group conversation with disabled notifications on that group chat even without any mentions.

**Comment by shanesmith** [comment]
I believe this PR fixes the issue: https://github.com/meetfranz/recipe-skype/pull/13

**Comment by fabiofdsantos** [comment]
This is no longer happening due to the latest update of Skype web version.
