### ISSUE TITLE
Franz using discrete GPU when FB is selected

### ISSUE THREAD

**Issue by orlleite** [meetfranz/franz#514]
I'm using OSX 10.11.6, MacBook Pro (Retina, Mid 2012). When I open Franz it starts using the discrete GPU, so it's getting more battery than it should.

I tested clearing the cache and closing all services, it still there. But when I reopen Franz it was not using discrete anymore. So I start each service at once. I found that Facebook is using discrete. Whatsapp, skype and Twitter don't. So I tested using Chrome to open the FB messager, and it's using too. So now I don't know if it's possible fix, but if Franz could not use the discrete GPU it would be great.

Doing this I found that there is a lag between saving my selected services. So if I select or deselect one service and close Franz it gets a error and the next time I open it the options I had choose are lost.

**Comment by hkalina** [comment]
Does the problem occure when you open Facebook messenger in web browser?
https://www.messenger.com

**Comment by johnhyland** [comment]
I have the same issue, in that both Facebook Messenger and Google Keep use the discrete GPU. They both do it in Chrome as well, so I doubt it's a Franz issue.

**Comment by orlleite** [comment]
@hkalina Yes, it's using discrete gpu when I open it on chrome.

**Comment by adlk** [comment]
This has been discussed quite a few times in different issues. I'll provide an option to disable GPU acceleration which is fixing this issue. Unfortunately we have seen some nasty side effects on some OSX/chromium/GPU setups. Therefore GPU acceleration will be enabled by default.

This issue is tracked internally – closing it.
