### ISSUE TITLE
Can not right click in text on chat of ChatWork

### ISSUE THREAD

**Issue by sola-msr** [meetfranz/franz#515]
### Expected Behavior

Right click to display the context menu.

### Current Behavior

Can not right click in text on chat of ChatWork.

### Screenshots (if appropriate):

![right_click](https://user-images.githubusercontent.com/13176655/34407969-775b1fb6-ec04-11e7-9e48-6cce14a0209d.gif)

### Steps to Reproduce (for bugs)

1.Open ChatWork.
2.Open chat somewhere.
3.Right click text on chat.

### Your Environment

* Franz Version used:5.0.0-beta.14
* Operating System and version:Windows10 Pro 64bit

**Comment by adlk** [comment]
Thank you for reporting this, can you tell me what options appear when you right click something? Seems like they override the default right click handling.

**Comment by sola-msr** [comment]
Thank you for your reply.
Ummmm, I'm check now, the context menu ("options" is this ?) Is displayed.
However, behavior is suspicious.
(I'm sorry if the sentences are strange, I'm not good at English...)

![right_click2](https://user-images.githubusercontent.com/13176655/34803924-53a2b8a8-f6b9-11e7-8d95-88eba3884890.gif)

**Comment by haraldox** [comment]
@sola-msr are you still experiencing the issue? closing this for now, feel free to reopen the issue with any questions or comments!

**Comment by sola-msr** [comment]
@haraldox 
@adlk 
OK,I will report again if there is something!
