### ISSUE TITLE
Office 365 links are opening in its own chrome window

### ISSUE THREAD

**Issue by jonnyeom** [meetfranz/franz#519]
When opening links in Office 365, the links do not open as a new tab in one of the open browsers (e.g. chrome for me, version 63.0.3239.108) 

### Expected Behavior
Links open in a new tab of a already open browser window.

### Current Behavior
Links open in its own chrome window.

### Your Environment
* Franz Version used: 5.0.0-beta14
* Operating System and version: Ubuntu 16.04

**Comment by colinodell** [comment]
Possible duplicate of https://github.com/meetfranz/franz/issues/381, https://github.com/meetfranz/franz/issues/244, and https://github.com/adambirds/recipe-office365-owa/issues/7?

**Comment by jonnyeom** [comment]
Yup I think so. Thank ya.
