### ISSUE TITLE
Ctrl+Tab globally blocked if Franz is started on startup as of 

### ISSUE THREAD

**Issue by kbauer** [meetfranz/franz#521]
*Still incomplete. I'll check again in the evening when I have access to an affected device.*

After a recent Windows Fall Creators Update (Windows 10 version 1709), having Franz start on Login globally blocks the `Ctrl+Tab` hotkey. 

### Expected Behavior
- In browsers and some other software, `Ctrl+Tab` should switch tabs. 
- In Emacs, pressing the sequence `Ctrl+H, C, Ctrl+Tab` should display information about the current keybinding.

### Current Behavior
- `Ctrl+Tab` does't have any effect in any other program.
- `Ctrl+Tab` switches tabs as expected inside Franz.

### Possible Solution
- Exiting Franz and starting it manually resolves the issue until the next reboot.
- It looks as if Franz is registering `Ctrl+Tab` as a global hotkey instead of a local one.

### Steps to Reproduce (for bugs)
- Update Windows 10 to Build 1709 or newer.
- Auto-run Franz on Startup.
- Open a tabbed browser supporting the `Ctrl+Tab` hotkey and check if it works.

### Context
- Issue appeared after the Build 1709 ("Fall Creators Update") feature update. 
- Sadly, the Windows update history has been cleared by the update, so I can't give further context on this aspect.
- Not reproducible on my office laptop.

### Your Environment

* Franz Version used: 4.0.4, Build: 40, Release: 1.3.1 / win32 / x64
* Operating System and version: Windows 10, 64bit, Build 1709

I sadly cannot comment on whether it is fixable by installing Franz 5.x, due to the account requirement.

**Comment by adlk** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

or the feature request template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/FEATURE_PROPOSAL_TEMPLATE.md
