### ISSUE TITLE
Some apps shut down on MacOS [Versión 5.0.0-beta.14 (5.0.0-beta.14.451)]

### ISSUE THREAD

**Issue by borisinvader** [meetfranz/franz#527]
The Messenger and Twitter tabs go blank after hibernation or some time of innavtivity.  I have to restart Franz to get them work again, it happens every time after a few hours of innavtivity or the Mac got to hibernation and get unlocked again. 

I use only 4 tabs:

Whatsapp
Twitter
Messenger &
Telegram

Whatsapp and telegram work fine all the time, but for some reason, Messenger and Twitter are buggy. 

My OS is High Sierra 10.13.2 on a MacBook Pro Retina 13" Mid 2014. 
My Franz Version is 5.0.0-beta.14 (5.0.0-beta.14.451)

Anyone else is having the same issue? How can I Fix it?

  
<img width="770" alt="captura de pantalla 2018-01-04 a la s 8 25 25 p m" src="https://user-images.githubusercontent.com/20705289/34592979-9ebc0a14-f18d-11e7-88f4-37a24a70bac0.png">
<img width="772" alt="captura de pantalla 2018-01-04 a la s 8 25 16 p m" src="https://user-images.githubusercontent.com/20705289/34592980-a09ab47a-f18d-11e7-985c-dd0306f35515.png">

**Comment by adlk** [comment]
This is a known issue. I did some improvements on this one with the next update which is coming in the next few days.
