### ISSUE TITLE
Blue screen of Franz after install on MacOS High Sierra

### ISSUE THREAD

**Issue by rhoerbe** [meetfranz/franz#528]
I installed OSX 10.13 from scratch in a Parallels VM and added Franz. After starting the application it becomes defunct.

### Expected Behavior
Allow to add service

### Current Behavior
Shows blue screen with window size buttons. There is no response on "add service" or "preferences". 

### Your Environment

* Franz Version used:
5.0.0.-beta.14.451
* Operating System and version:
OSX 10.13.2

**Comment by swrobel** [comment]
Works fine for me on 10.13.2 on an actual Mac. Sounds like a parallels issue.

**Comment by adlk** [comment]
Can you please try to open the dev tools `Cmd+Alt+I` and tell me what's on the console tab?

**Comment by rhoerbe** [comment]
![bildschirmfoto 2018-01-09 um 22 51 46](https://user-images.githubusercontent.com/4348479/34769536-5d292fbc-f5fe-11e7-8fc4-0972b09cbf37.png)

**Comment by haraldox** [comment]
@rhoerbe please show us the Console tab :)

**Comment by rhoerbe** [comment]
/Applications/3rdParty/Franz.app/Contents/Resources/app.asar/i18n/translations.js:11 Can't find translations for zh-HANT
:-*>

**Comment by haraldox** [comment]
what language do you have enabled? zh-HANT refers to Chinese

**Comment by rhoerbe** [comment]
de-at. The system is a fresh default install with Austrian settings

**Comment by haraldox** [comment]
have you tried reloading Franz with cmd+shift+R?

**Comment by rhoerbe** [comment]
Yes, but it did not help

**Comment by haraldox** [comment]
please try deleting the Franz folder in ~/Library/Application Support and try again to open Franz

**Comment by rhoerbe** [comment]
did not help, same error message in JS console

**Comment by haraldox** [comment]
the error message should not block Franz from loading though

**Comment by saviola777** [comment]
I have a similar problem on Linux (Arch Linux running [dwm](https://dwm.suckless.org/), using the [AUR build](https://aur.archlinux.org/packages/franz/)) after upgrading from [Franz4](https://aur.archlinux.org/packages/franz4-bin/). I just get a blue screen (tried removing the config, no changes), can't open the dev tools using Ctrl + Shift + I/J/C either. Any advice as to where / how to debug this? I guess this has to do with my system, but I'm stumped as to where to start tracking down the problem because I can't see any output / logs anywhere that could give me clues.

**Comment by deppiedave64** [comment]
I can confirm this problem on Arch, too. Just a blue screen.
I also tried removing the config, dev tools don't work either.
I tried the AUR build, the franz-bin package from the AUR as well as AppImages from the recent and multiple older releases, so I suppose it's not a packaging problem.

**Comment by ragusa87** [comment]
I have the same on Ubuntu 18.04, everything was working fine for 3 weeks, and this morning I got the blue screen. Removing config does not change the problem, the console can't open, and there is no output from the command-line.

**Comment by deppiedave64** [comment]
That seems likely, as I am using tmpfs, too, although I cannot confirm it right now.

**Comment by IronicBadger** [comment]
Experiencing this on a fresh Arch install of the AUR franz package.

**Comment by saviola777** [comment]
@IronicBadger Did you try using a different temporary directory? I'm using a wrapper script like this (franz is not the only application having problems with tmpfs on /tmp):

```
mkdir -p ~/tmp
export TMPDIR=~/tmp
franz
```

**Comment by IronicBadger** [comment]
@saviola777 Just tried your suggestion but no bueno.

**Comment by panchoIkatu** [comment]
I'm having the same error as @IronicBadger .
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.

**Comment by fdeizaguirre** [comment]
I'm having the same error as @IronicBadger  by installing it AUR
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.

**Comment by db0** [comment]
Same issue with fedora 29 with both the appimage and the dev version. Tried the $TMPDIR var as well with no success
