### ISSUE TITLE
Todoist service makes you login after restart

### ISSUE THREAD

**Issue by davidmoore-io** [meetfranz/franz#53]
I'm running OS X 10.12.6, with the current version of Franz  (5.0.0-beta.10). 

The Todoist service forgets I'm logged in every time I close and re-open the app, forcing a re-login every time. I'm assuming this isn't expected behaviour, as it doesn't happen with any other service I use.

I'm using a normal (ie non google/facebook omniauth) login.

**Comment by adlk** [comment]
This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
https://github.com/avatarkava/recipe-todoist

**Comment by riddla** [comment]
@adlk: can you give a hint how https://github.com/avatarkava/recipe-todoist/issues/3 could be solved? Any ideas? I would be happy to provide a pull-request to the plugin owner, maybe you had those issues with other plugins before?
