### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by DavorSaric** [meetfranz/franz#531]
Hello, I would like to delete my account. Can you point me on how to do it? Thank you!

**Comment by adlk** [comment]
This needs to be updated as soon as the next update is out, also to be GDPR compliant. In the meantime, for account deletion please send me an email.

The next version of Franz will have an option to delete your account.

**Comment by vivabonito** [comment]
Hi, could you please reach out to me about deleting my account manually? I have already removed the application from my PC. Thank you for your help in advance.

**Comment by earaujoassis** [comment]
@adlk Hey, I'd like to know how to proceed towards account termination. Thank you.

**Comment by PierreKiwi** [comment]
Hello @adlk,
Can you please share your email address regarding the deletion of my account?
Thank you.

**Comment by Celtic-Knot** [comment]
Hello @adlk,

I would like to delete my account. As you acknowledged in 2018, (above https://github.com/meetfranz/franz/issues/531#issuecomment-356555027) you need to offer this option, and you said you would be doing so. Please can you tell me how to do so now, as it isn't apparent how to do so.

Thank you.
