### ISSUE TITLE
Use franz as web app

### ISSUE THREAD

**Issue by DirkHeinke** [meetfranz/franz#532]
Hi,

is it possible to use franz as web app in a browser? I use the web apps of all kind of messengers because I don't want to install the clients from them, but it would be awesome to have all the web apps in a single web app.

Is this doable with the current architecture of franz?

Maybe it could also work like im+, where the page manages your accounts and you only have to sign in once, but more modern :smile:

**Comment by alecive** [comment]
Your idea seems pretty convoluted. You want to have a webapp version of a desktop app that wraps around webapps :-D

It defeats the purpose of Franz, which is to not have webapps but standard apps (in tabs).

**Comment by DirkHeinke** [comment]
Yes, I know. :blush:   It would be another use case. I currently have at least 5 pinned tabs with messengers and it would be nice to replace them with one.

**Comment by ginkgomzd** [comment]
...seriously dude... the whole point of Franz is to get webapps out of the browser... and combined into one window.

Does it help to know that Franz is built using a framework that disguises a web browser as a desktop application?

What do you feel you are missing that you would have if you put it back into the browser?

**Comment by DirkHeinke** [comment]
It was just a question if it would be possible with the architecture of franz...  Electron can be used to simply bundle a web app, so it is possible to unbundle it, but it can also be used for more complex things.

I'm missing the "don't need to install and available everywhere where I have a browser". And I just like to have as much as possible in a browser / as a service.

**Comment by ginkgomzd** [comment]
ah, I see.
Franz is not a webapp to be unbundled though. It is a web-app-bundler.

Maybe you could use something like pinned tabs with profile sync'ing with your browser account.

**Comment by DirkHeinke** [comment]
Thanks. That's how I currently use all the messengers:
![selection_024](https://user-images.githubusercontent.com/5230945/34586192-3ace3a0c-f1a3-11e7-9a5f-9f282bbdf730.jpg)

Though, something like [im+](https://plus.im/) in modern would be nice. Maybe I find something else...

**Comment by augnustin** [comment]
Same as @DirkHeinke here.

Desktop apps are something to install. For some people this is not much, for others this is a lot. I need to reinstall my environment quite often. Browser is stateless, it reduces quite a lot dependencies.

Anyway, too bad this is not currently possible ...

**Comment by ultrasound1372** [comment]
I actually have a use case where I need the web app, because the Electron desktop app has some kind of focus bug that makes it unusable for me most of the time due to the fact that I must use a screen reader. Browsers don't have these problems.
