### ISSUE TITLE
Alternative install path

### ISSUE THREAD

**Issue by pascalgeusen** [meetfranz/franz#534]
Franz installs in C:\Users\UserNamel\AppData\Local\Programs\franz\

But we are working in a VDI environment and I do not have rights to read/write to this folder. Is it possible to install Frans in C:\Program Files (x86)?

Kind regards.

**Comment by adlk** [comment]
I haven't been able to test this yet but you can try this: http://nsis.sourceforge.net/Which_command_line_parameters_can_be_used_to_configure_installers

**Comment by pascalgeusen** [comment]
Solution does not work. Software still installs in ...AppData\Local\...

**Comment by pascalgeusen** [comment]
Anyone?

**Comment by haraldox** [comment]
can you please provide us with your use case?

**Comment by pascalgeusen** [comment]
Franz installs in C:\Users\UserNamel\AppData\Local\Programs\franz\

But we are working in a VDI environment and I do not have rights to read/write to this folder. Is it possible to install Frans in another folder?

Kind regards.

**Comment by ckrf** [comment]
I would also find this helpful because I am trying to free space on my C: drive
