### ISSUE TITLE
Unable to share screen in Slack calls

### ISSUE THREAD

**Issue by sbuechner** [meetfranz/franz#535]
### Expected Behavior
If i use the Slack integration i want to be able to use the screen sharing feature like in the native Slack App

### Current Behavior
Button is greyed out and referencing to Slack App

### Screenshots (if appropriate):
<img width="789" alt="screenshot_qa 2018-01-04 um 11 07 23" src="https://user-images.githubusercontent.com/874299/34558791-bf074994-f13f-11e7-97bb-a78867b04345.png">

### Possible Solution
make it work ^^

### Steps to Reproduce (for bugs)
1. Create a Slack call
2. Let another user join
3. Try to share your screen
4. Error: Button is disabled 

### Context
This prevents me to use Franz for any team chat activity

### Your Environment
* Franz Version used: Version 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: MacOS HighSierra 10.13.2

**Comment by adlk** [comment]
Unfortunately this is currently not possible as they disable screen sharing for the web interface. However, we are always looking for ways to make it work. Closing this as it is tracked internally.
