### ISSUE TITLE
Messenger doesn't save notification preferences

### ISSUE THREAD

**Issue by luki-** [meetfranz/franz#536]
Since a few weeks Messenger does not store desktop notification preference. This results in notifications being disabled by default after each service reload.

### Expected Behavior
After enabling desktop notifications in Messenger settings, the preference should be saved and persistent.

### Current Behavior
Each time a Messenger service is reloaded its settings are restored to defaults.

### Steps to Reproduce (for bugs)
1. Enable desktop notifications in a Messenger service
2. Reload the service/restart Franz
3. Desktop notifications should be now disabled - the bug ;)

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: macOS 10.13.1

**Comment by adlk** [comment]
@dannyqiu fixed the issue in the messenger recipe. The update is now shipped. Thanks!

**Comment by webworker01** [comment]
Sorry when will this be added? I am on 5.0.0-beta.15 and this problem still persists.

**Comment by mark-reason** [comment]
@dannyqiu's fix does not fix the issue reported.
