### ISSUE TITLE
Links in Outlook and Office 365 Outlook open in Franz window not browser window

### ISSUE THREAD

**Issue by Letsch22** [meetfranz/franz#537]
### Expected Behavior
- Links in both Outlook.com and Office 365 Outlook should open as a new tab on the default browser

### Current Behavior
- Links in both Outlook.com and Office 365 Outlook open in a new Franz window

### Steps to Reproduce (for bugs)

1. Connect an Outlook or Outlook 365 account
2. Click a link in an email you've received
3. Notice that a new Franz window has opened, not your default browser

### Your Environment
* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10 Version 1709 Build 16299.125

**Comment by colinodell** [comment]
This has been reported a few times without any resolution yet :-/

See #244, #381, #519 and adambirds/recipe-office365-owa#7

**Comment by adlk** [comment]
The upcoming update which is coming in the next few days has an improved link handling for external URLs. (#541)
