### ISSUE TITLE
Slack Code Tags not expanding

### ISSUE THREAD

**Issue by kaialexanderfischer** [meetfranz/franz#538]
Code tag is not expanding in Slack.

### Expected Behavior
Expand code tag to it's full height.

### Current Behavior
Changes the expand button to collapse, but does not expand the code tag.

### Screenshots (if appropriate):
![2018-01-05 10_31_49-franz](https://user-images.githubusercontent.com/32815233/34603300-b4910a30-f203-11e7-8ef2-b16585237ff5.png)

![2018-01-05 10_19_08-franz](https://user-images.githubusercontent.com/32815233/34603062-9ffc6e30-f202-11e7-8be5-2dab83461527.png)

### Steps to Reproduce (for bugs)
1. Send a code tag to someone
2. Try to expand it

### Your Environment

* Franz Version used: Latest (5.0.0-beta14)
* Operating System and version: Windows 10

**Comment by adlk** [comment]
I can't reproduce this issue. Anyone else?
