### ISSUE TITLE
Problem with wechat

### ISSUE THREAD

**Issue by frenkbit** [meetfranz/franz#539]
I try to connect my wechat account but the system suggests to use the wechat native app as you can see in the attached picture.
Can you fix it?

### Screenshots (if appropriate):
<img width="1172" alt="meet_franz_wechat" src="https://user-images.githubusercontent.com/6436517/34604104-f74ade5c-f206-11e7-8cf7-0945c53dde34.png">

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by BrianGilbert** [comment]
@frenkbit Wether or not you can use the wechat service depends entirely on when your wechat account was created, you will receive the same message if you try to use the wechat we based version at https://web.wechat.com/?lang=en

I created the service but am unable to use it as mny account is too new as well.
