### ISSUE TITLE
Don't show unread count

### ISSUE THREAD

**Issue by joeclarkx** [meetfranz/franz#540]
### Feature Description
I am interested in removing the unread badge/count

The option to do so globally would be good. Being able to do it selectively per app would be better. E.g. I am interested in an unread count for Whatsapp, but not Inbox. The reason: Whatsapp notifications are often time-sensitive, whereas I prefer to 'do email' in batches during the day. The unread badge makes me itchy to check my mail when I see it.

### Motivation and Context
Being able to remove the unread badge selectively from services would remove the nudge effect making me constantly itchy to check my mail.

**Comment by adlk** [comment]
Coming with the new update in the next couple of days.
