### ISSUE TITLE
keyboard short cut for switching tabs crashes franz

### ISSUE THREAD

**Issue by MrBim** [meetfranz/franz#542]
when i use cmd + num to switch tabs in franz it is crashing. i am using a 2015 macbook pro with osx 10.12.6

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
I'm assuming you are on Franz 4 – Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)
