### ISSUE TITLE
Issue template includes broken link to service request form

### ISSUE THREAD

**Issue by nomike** [meetfranz/franz#543]
When opening a new issue, a few comments are provided in the template, telling you, amongst other things, to go to  https://goo.gl/forms/zbwlx3VFvAo2oink2q to file requests for new services to be added to Franz. However this link is dead, yielding a HTTP/404 error message from the google URL shortener.

I'm leaving the template intact below for reference (I don't know if github preserves the HTML comments).

--

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Thank you for the heads up. This issue is now resolved!
