### ISSUE TITLE
Issues zoomed in

### ISSUE THREAD

**Issue by jeroenrotty** [meetfranz/franz#546]
### Expected Behavior
I was running franz on my ipad via Duet and wanted to zoom in using CMD + which worked ( had to do that on each channel / service I was on, too bad thou. When I switched to external monitor back @home I need to do that again for each channel and service I was on.

### Current Behavior
Even when I did cmd 0 to go back to normal, switched to another channel and came back to the same one, I was back zoomed in, it's like the software doesn't remember, it's kinda frustrating now.

EDIT: it appears it only behaves so in Slack services.

Jeroen

**Comment by adlk** [comment]
Did you restart Franz in between the switch?

**Comment by jeroenrotty** [comment]
Yes I did. Multiple times, even reloading services 1 by 1, reloaded them all, restarted Franz completely, didn't do it. Just reopening it without any external monitor or iPad on my MacBook did the trick ...

**Comment by haraldox** [comment]
@jeroenrotty are you satisfied with your workaround? closing this for now, feel free to reopen the issue with any questions or comments!

**Comment by jeroenrotty** [comment]
Well, happy is a bad word for it, but sure.
