### ISSUE TITLE
This version of chrome is outdated

### ISSUE THREAD

**Issue by Seluj78** [meetfranz/franz#548]
### Expected Behavior

Using latest chrome engine

### Current Behavior

Getting a message `Using an outdated version of chrome, please update`

### Screenshots (if appropriate):
![screen shot 2018-01-09 at 8 39 45 am](https://user-images.githubusercontent.com/4641317/34709764-e6559a8c-f518-11e7-9f87-247f5187cca9.png)

Translation from french : `This version of the chrome web browser is outdated. Please install a 'compatible web browser'. 'Do not show again'`

### Context
Just installed Franz and logged in into gmail
### Your Environment
* Franz Version used: `4.0.4`
* Operating System and version: `macOS Sierra 10.12.6`

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)
