### ISSUE TITLE
Issue with formatting of Google Hangouts (Chat)

### ISSUE THREAD

**Issue by ryanclev** [meetfranz/franz#552]
Basically the chrome plugin provided by google is a nice interface easily allowing users to see all chats and respond. The list of chats or on the left and content/responses on the right. I would have thought the interface would be the same in Franz's app. But in the Franz app it is like the version in mail and not user friendly at all. When you have multiple chats going on at the same time it is very unorganized and difficult to use. 

I want to see if it is possible to update this or if you have an update already planned? 

Other than this issue I so far like the experience with Franz. But I use Google Hangouts frequently which makes me question to continue using. 

Thanks so much! 
Ryan

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
We can only use what's available on the web and chrome extensions are currently not supported.
