### ISSUE TITLE
Minimised Franz window not listed in alt/tab win/tab or in App indicator

### ISSUE THREAD

**Issue by NNois** [meetfranz/franz#553]
On W10
When minimised, windows apps are visible in the alt/tab win/tab screens. Plus an "launched" app indicator is visible in the taskbar

Actually if I minimise franz the window isn't listed anymore in the alt/Mtab and the icon in the taskbar isn't indicating the app is opened.

**Comment by vault771** [comment]
There is no way to start Franz minimized which is a big issue for me. Can you guys fix it?
I would be willing to pay for this software if it worked. I also sent a message through facebook
messenger and nobody seems to care. It's been over 2 weeks and no replies.

**Comment by haraldox** [comment]
@NNois I'm not sure, but this might be expected behavior? @adlk please clarify

@vault771 Duplicate of #567

**Comment by NNois** [comment]
nope this is not the expected behavior at all... every other windows apps leaves an highlight even if they are minimised, this bug leads to windows unability to list the windows in the alt-tab win-tab

In the screenshoot bellow every apps are minimised and the desktop is fully visible
![mdp_shoot_180115-154122](https://user-images.githubusercontent.com/2362053/34947487-8b10dc08-fa0a-11e7-9a0c-bfd87f02be8b.jpg)

**Comment by Themandunord** [comment]
+1 for me it's the same issue. 
The app disapper from the taskbar, althought the app still open.

**Comment by jnsflint** [comment]
+1 Same problem here on Windows 10

**Comment by arunr14** [comment]
+1 , same issue for a while now

**Comment by jonasjancarik** [comment]
Try right-clicking Franz in the tray/notification area and clicking "Show Franz". Seems to have fixed it for me

![image](https://user-images.githubusercontent.com/2459191/49860529-42d97900-fdfa-11e8-9930-8f1a6a82742b.png)

**Comment by Nathan-LG** [comment]
+1, same issue. Tried reinstalling and deleting Franz appdata folder.

**Comment by Protector09** [comment]
So? Any news? this still happends to me

**Comment by kimmminjae** [comment]
Same. It shouldn't go to tray when minimized. It should minimize to the task bar. I think it used to minimize to the task bar but it changed to system tray one day... Can't Alt+Tab to Franz anymore...

**Comment by williamvz** [comment]
Same here. Pin to taskbar works partially, but would love to just alt + tab back into it.

**Comment by razkif** [comment]
+1 I've also had this issue for a while now- Uninstalled Franz/Deleted AppData didn't solve the issue.

**Comment by Idoamit** [comment]
+1 Same problem here on Windows 10

**Comment by adam-py** [comment]
+1, my task switching habits make Franz hard to use on Windows

**Comment by adam-py** [comment]
Today Franz reappeared in my Alt+Tab menu.

I didn't consciously update neither Franz (on 5.0.0) nor Windows, not sure where this came from; nevertheless the problem seems solved, propose closing the issue.

**Comment by tfc903** [comment]
> Today Franz reappeared in my Alt+Tab menu.
> 
> I didn't consciously update neither Franz (on 5.0.0) nor Windows, not sure where this came from; nevertheless the problem seems solved, propose closing the issue.

I'm still having the same issue - propose not to close the issue.

**Comment by kimmminjae** [comment]
The update fixed my issue. I'm fine with this issue being closed.

**Comment by martijnkooi91** [comment]
This fixed my issue;
![image](https://user-images.githubusercontent.com/40260631/55859785-0e40b880-5b73-11e9-9018-e5d162583cad.png)
