### ISSUE TITLE
Franz option "Keep running in background" not working properly

### ISSUE THREAD

**Issue by jancoow** [meetfranz/franz#555]
Hi. When I enable the "keep running in background" option, I can't reopen franz anymore. This happens after I exit Franz with the close button, and want to reopen it by clicking on the franz shortcut. Franz is still running in the background tho, because I do receive notifications. But I can't open the window anymore. I've to pkill it first from the terminal, and then I can restart it. 

### Expected Behavior
It should reopen the window after clicking on the Franz shortcut. 

### Current Behavior
It doesn't open the window. 

### Your Environment
Franz version: 5.0.0-beta.13
Distro: Arch Linux

I'm having this bug for a few versions now.

**Comment by haraldox** [comment]
anyone experiencing the same issue?

**Comment by DaniGuardiola** [comment]
Me, ubuntu 17.10, standard GUI

**Comment by DaniGuardiola** [comment]
Oh, actually it used to happen in the past, now it won't even show up in the app bar and I can only open it again by clicking on a notification. This is after clicking the X button.

**Comment by lukasbash** [comment]
Can reproduce this!
```
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
```

Using Manjaro Linux 17.1.11

**Comment by lestevam** [comment]
I have the same problem!

Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

Using KDE Neon 5.13.4
