### ISSUE TITLE
Show number of unread messages in taskbar

### ISSUE THREAD

**Issue by maver1ck** [meetfranz/franz#558]
### Expected Behavior

I'd like to have Franz windows title in format:
Franz (x) where x is number on unreaded messages

### Current Behavior
Windows title is constant Franz

### Screenshots (if appropriate):

Franz vs Rambox
![image](https://user-images.githubusercontent.com/4006010/34779298-166314b8-f620-11e7-9dcf-824f47c2c78b.png)

### Your Environment
* Franz Version used: 5.0.0-beta.14
* Operating System and version: Windows 10.0.16299 Build 16299

**Comment by haraldox** [comment]
if you're using (large) icons only in Windows' taskbar, a badge will show you the unread count ... but adding it to the Windows title should easily be done, stay tuned!

**Comment by s1h4d0w** [comment]
Can this be reopened and added?
