### ISSUE TITLE
Select tab on mouse down, not mouse up

### ISSUE THREAD

**Issue by alexozer** [meetfranz/franz#562]
In my opinion, Franz should display a "tab" on mouse down rather than mouse up, like how tab selection works in web browsers. This lowers perceived latency greatly.

### Expected Behavior
1. Press down mouse button with cursor over tab
2. Tab renders (before mouse up)

### Current Behavior
1. Press down mouse button with cursor over tab
2. Release mouse button
3. Tab renders

### Context
Quickly switching between "tab" messenger services is a frequent occurrence, and perceiving latency makes this feel a bit annoying.

### Your Environment
* Franz Version used: 5.0.0_beta.14
* Operating System and version: Arch Linux

**Comment by adlk** [comment]
I can't speak for Linux browsers but I can't confirm this as the standard behaviour for tab selection in browsers. Furthermore it would interfere with reordering the services. 

With the information I currently have I would file this as `wontfix` – Waiting for a response.

**Comment by nemilya** [comment]
Interesting note. I just tested it on tabs in my LinuxMint's Firefox - and Tab (page) is selected just after click (button pressdown). And if I want to drag (reorderring) - I can move tab (if mouse button still pressed).

**Comment by alexozer** [comment]
Yes, tab is selected before dragging in Chrome and Firefox on Linux for me. IMO it wouldn't be a problem for Franz either since reordering likely occurs much less often than selecting services and it's easy to recover from "the service you were reordering got selected".

**Comment by adlk** [comment]
@alexozer good point ad reordering. It's actually pretty interesting to see the tiny differences between Win, Mac and Linux. 

I'll test @dannyqiu's PR to see how it feels on Mac on Win.
