### ISSUE TITLE
Migrate existing accounts to Franz 5

### ISSUE THREAD

**Issue by wayrk** [meetfranz/franz#563]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by haraldox** [comment]
Franz accounts sync automatically to all your devices in Franz 5. Just enter your account details chosen during registration for your Franz Account! :smiley:

**Comment by wayrk** [comment]
But Im using ver. 4.0.4 & its connected with 14 diff. service accounts, is there any way to transfer to another device. i.e. by copying any folders or files !!?

**Comment by BrianGilbert** [comment]
Pretty sure you just have to re-add services once you install 5

**Comment by adlk** [comment]
There is an importer of your existing services once you setup v5. However it's currently necessary to login manually to your accounts again afterwards.

@wayrk do you want to just migrate from machine A to B or do you want to use Franz on both machines?

**Comment by adlk** [comment]
I've already mentioned this in the email but I want to disclose this for the public as well.

We currently differentiate between service sync and session sync. Service sync is quite straightforward as there is no personal data involved. With session sync it's a whole different story as everyone who would ever get their hands on your sessions can use your accounts in your name. We will not add session sync before we are a 100% confident that your data is stored securely and just accessible to you.

So what is the gain for you without session sync?
You mentioned that you have 14 services. That's e.g. 14 services you don't have to configure again on another machine. 

@wayrk as this is a question and not issue, I'm going to close this. Happy to continue this conversation via emails.
