### ISSUE TITLE
how to change from telegram desktop to telegram web?

### ISSUE THREAD

**Issue by mhamri** [meetfranz/franz#564]
telegram desktop is old and obsolete, so many new features added to telegram web that desktop version doesn't support. franz is keeping asking to use desktop version and even when i say no, still it's using the desktop. i don't want the desktop version, how do i change it to the web version

### Expected Behavior
be able to switch between telegram desktop and web

### Current Behavior
it's keep asking to change to telegram desktop and there is no way to change it back or disable this notification

### Your Environment

* Franz Version used: 5 beta 14
* Operating System and version: Windows 10 pro

**Comment by nemilya** [comment]
Franz just wrap web conten from target-service url, and dont add any new logic. Is in web version (Chrome browser) it working correct?

**Comment by haraldox** [comment]
@mhamri are you still experiencing the issue? did you try @nemilya's answer?
