### ISSUE TITLE
Disable top menu toggling with alt

### ISSUE THREAD

**Issue by alexozer** [meetfranz/franz#565]
Currently, the top menu bar can be toggled by pressing the alt key. 

### Feature Description
Add an option to disable top menu toggling with alt, and an option to set whether the top menu is shown or hidden.

### Motivation and Context
The alt key prefixes all of my window manager keybindings. When I switch desktops to Franz by (for example) pressing `alt + k`, Franz detects alt is down when focused and unintentionally toggles the menubar. So, it might be nice to disable this toggling.

### Your Environment
* Franz Version used: 5.0.0_beta.14
* Operating System and version: Arch Linux

**Comment by arvigeus** [comment]
This is especially annoying when switching languages with Alt+Shift

**Comment by haraldox** [comment]
@alexozer @arvigeus we're working on a solution, stay tuned to one of our upcoming releases...

**Comment by nsrosenqvist** [comment]
In the latest beta I can't toggle the menu bar at all. Is there an option that needs to be enabled for this?

**Comment by azeleneev** [comment]
@haraldox 
Hello! Any news?

**Comment by tomsturge** [comment]
Has this issue died, not enough demand or unable to accommodate?

**Comment by cdeler** [comment]
But the issue still reproducible...
