### ISSUE TITLE
Option to launch Franz minimized, but loading services in the background

### ISSUE THREAD

**Issue by jwbambacht** [meetfranz/franz#567]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: 5.0.0-beta.14-451
* Operating System and version: MacOs 10.13.2

**Comment by vault771** [comment]
There is no way to start Franz minimized which is a big issue for me. Can you guys fix it?
I would be willing to pay for this software if it worked. I also sent a message through facebook
messenger and nobody seems to care. It's been over 2 weeks and no replies.

**Comment by haraldox** [comment]
@vault771 let me look into that

**Comment by haraldox** [comment]
@jwbambacht @vault771 could you post your reasons for this?

**Comment by haraldox** [comment]
running Franz in the background is already support, you can close the window upon first launch

**Comment by vault771** [comment]
When you start computer, Franz starts with it but won't minimize even with shortcut which set to minimize. 

![franz minimize](https://user-images.githubusercontent.com/35404222/35073993-b745da70-fbb9-11e7-95ae-9ade73e0dd6a.png)

Another problem with Franz, every time I run it pops User Access Control and asks if I want to allow it. Every single time. Don't have any problems with other apps.


![photo jan 17 7 09 35 pm](https://user-images.githubusercontent.com/35404222/35074149-8e53e3a4-fbba-11e7-95f4-16931897fc5b.jpg)

Thank you

**Comment by haraldox** [comment]
@vault771 could you please post your reasons for this, as i'm trying to understand your use case...

**Comment by theolice** [comment]
@haraldox He wants Franz to run in the background when he starts up his computer. Currently it just pops up on your screen instead and you have to minimise it manually.

The whole use case is not needing to minimise Franz manually

**Comment by mstratford** [comment]
@haraldox I am also looking for the same functionality, ideally i'd like a tidy desktop on start (mainly to hide the many windows which appear and flash as they load in).

**Comment by vault771** [comment]
@theolice thank you for backing me up! 👍

**Comment by poisonborz** [comment]
Please implement this. Every messenger app ever had this feature - from Skype to Rambox. People launch messengers always at startup, and it's a huge annoyance that the window pops up.

**Comment by alecive** [comment]
Duplicate of https://github.com/meetfranz/franz/issues/365

**Comment by poisonborz** [comment]
Everyone interested, I wrote a temporary fix in #365
