### ISSUE TITLE
Mac OS dark theme taskbar icon issue

### ISSUE THREAD

**Issue by ssgtcookie** [meetfranz/franz#571]
#This is what the franz icon looks like in the Mac OS taskbar on the default theme:
![Light theme](https://cdn.pbrd.co/images/H2KPRfc.png)

Now when you change the Mac OS theme to dark, the franz logo wont change from color. Notice how the dropbox logo is changing from black to white, and the franz logo is staying at it's black color.
![Dark theme](https://cdn.pbrd.co/images/H2KPsDd.png)

Tested at the latest versions of franz and Mac OS as of today.

Thanks guys, awesome software keep it up!

**Comment by haraldox** [comment]
are you sure? i don't have this issue :/
<img width="517" alt="screen shot 2018-01-13 at 17 16 39" src="https://user-images.githubusercontent.com/135914/34907862-9b8a474e-f885-11e7-83d4-679389ed3f5b.png">
maybe it's working because of Bartender...

can anybody confirm?

**Comment by haraldox** [comment]
@ssgtcookie what version of Franz are you using?

**Comment by ssgtcookie** [comment]
I reinstalled Mac OS High Sierra today and installed the latest franz version from the franz homepage for Mac OS today.

**Comment by haraldox** [comment]
What if you try switching Dark and Light Modes?

**Comment by ssgtcookie** [comment]
I switched a couple of times make the screenshots for this issue. Everytime I switched to the dark theme the problems shows. Maybe there are more mac users that have the same problem?

**Comment by adlk** [comment]
What is interesting for me is that the red dot should be exactly the same red in both versions. Also in previous versions (where we had no support for the dark theme) you were able to see the Franz logo, the contrast was just awful. Here I'm missing the Franz logo at all.

Can you please update your initial issue with all the necessary information like macOS version, exact Franz version and so on. Please use this [template](https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md), it makes tracking and reproducing issues much easier.

**Comment by ssgtcookie** [comment]
@adlk in my post I stated that I used the latest versions of Mac OS and franz as of yesterday. Google learns me that these are the versions used:

Franz: 5.0.0 beta 14
Mac OS: 10.13.2

I know I didnt used the bureaucratic form for this bug report but I think my initial post is quite clear on the issue. Happy to help out if you have more questions.

**Comment by haraldox** [comment]
related to #1
