### ISSUE TITLE
Add service Sococo

### ISSUE THREAD

**Issue by dm82m** [meetfranz/franz#572]
Add Sococo as service to Franz.

Details: https://www.sococo.com/

There is also a web app availble: https://app.sococo.com/a/login

Btw: within Rambox, that is already working ... ;-)

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](http://bit.ly/franz-service-request) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
