### ISSUE TITLE
Could not load service recipe.

### ISSUE THREAD

**Issue by scippio** [meetfranz/franz#573]
After upgrade from older Franz in Archlinux (this package: https://aur.archlinux.org/packages/franz ) and register franz account + importing old services I found empty Franz without any services. So... I want add my old services like Telegram, Slack etc. .... but every my service give me: "Could not load service recipe."
![](https://i.gyazo.com/cdbe8e7e0ffbac0a26ba56328f1566a1.png)

Every new service is added fine.

Franz:  5.0.0-beta.14

**Comment by esinik** [comment]
I encountered the same problem. The difference is when I tried to add new service on beta 15, service list only refresh and no any warning messages display.

**Comment by haraldox** [comment]
@scippio did you try reloading Franz with ctrl+alt+R?

**Comment by scippio** [comment]
@haraldox I tried everything... I think It's same bug as here: #171

**Comment by haraldox** [comment]
@scippio are you behind a proxy?

**Comment by scippio** [comment]
@haraldox I think no... but I don't have public IP... I'm classical behind my ISP...

**Comment by haraldox** [comment]
@scippio do you still have the same problem?

**Comment by scippio** [comment]
ok... I installed 5.0.0_beta.15-1 from Archlinux AUR and it's seems working now! Thank you.

**Comment by TristanMarion** [comment]
Hi, I encounter this issue with the last version :
```
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
```

I checked and I am not behind a proxy, do you have an idea on how to fix it ?

**Comment by marius-pop0** [comment]
@TristanMarion Im having the same problem on Manjaro. Recipes are not being downloaded for me.

**Comment by heimer16** [comment]
Same problem here.  Arch linux.  No proxy.  I get 2 errors in the developer console:

Uncaught (in promise) TypeError: Cannot read property 'autoLaunchInBackground' of undefined
    at SettingsStore._migrate (SettingsStore.js:77)
    at SettingsStore.setup (SettingsStore.js:26)
    at <anonymous>

TypeError: fetch is not a function
    at ServerApi.getRecipePackage (/usr/share/franz/resources/app.asar/api/server/ServerApi.js:379:25)
    at Promise.all.recipes.map (/usr/share/franz/resources/app.asar/api/server/ServerApi.js:568:20)
    at Array.map (native)
    at ServerApi._bulkRecipeCheck (/usr/share/franz/resources/app.asar/api/server/ServerApi.js:562:32)
    at ServerApi._mapServiceModels (/usr/share/franz/resources/app.asar/api/server/ServerApi.js:537:16)
    at ServerApi.getServices (/usr/share/franz/resources/app.asar/api/server/ServerApi.js:195:31)
    at <anonymous>

**Comment by elliotwms** [comment]
Also Arch, also getting the exact same error as @heimer16

**Comment by DanitiKain** [comment]
Yes looks like I am getting the same thing as well.  Any updates on what the issue could be.

**Comment by apinnecke** [comment]
Same over here on arch / angergos with freshly installed franz, not able to add any service:

```
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
```

**Comment by neilwightman-intergral** [comment]
I had this issue with .deb and .AppImage 
I deleted /home/<username>/.config/Franz directory then started Franz 5 and it works now.
