### ISSUE TITLE
All services lost after update to latest franz version

### ISSUE THREAD

**Issue by tofi86** [meetfranz/franz#575]
### Expected Behavior
Updating Franz should keep the registered services.

### Current Behavior
After updating to FRanz 5.0.0-beta15.607 all registered services disappeared and needed to recreate them.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: 5.0.0-beta15.607
* Operating System and version: macOS 10.13.2

**Comment by BrianGilbert** [comment]
What was the previous versuion that you had installed?  if it was from Franz4 there wasn't a clean upgrade path.

**Comment by tofi86** [comment]
no, I had the previous beta installed.

**Comment by tofi86** [comment]
Oh no, restarting Franz **again** solved the issue 🙈  All services back again!
Sorry for the wrong alert!

However, the automatic update of Franz via the blue footer banner update notification restarted the app with an empty GUI with no services. That's IMHO quite confusing...

**Comment by BrianGilbert** [comment]
@tofi86 can you please log a separate issue about that if you can recreate it?

**Comment by tofi86** [comment]
@BrianGilbert see #580

**Comment by haraldox** [comment]
could also be related to #528
