### ISSUE TITLE
Improve external link handling

### ISSUE THREAD

**Issue by haraldox** [meetfranz/franz#577]
This issue should function as a kind of super-thread collecting all previous issues and trying to classify them. Please use this issue to post all kinds of related bugs encountered and comments for possible fixes, **indicating to which class they belong**.

**Comment by haraldox** [comment]
- External links are not opened at all: #63, #135, #236, #471, 
possible workarounds: right-clicking on link in Franz and selecting "Open Link"

- External links open in Franz instead of browser: #244, #298, #381, #408, #519, #537, adambirds/recipe-office365-owa/issues/7

- Internal links open as external links in browser: 

- External links open browser, but do not load URL: #264, #272, #457, #462, 
try chrome://restart

- Default browser issues: #194, #333, #487 (feature request), #497, #530

**Comment by koma-private** [comment]
@haraldox Thank you for hard work. Would you add this related issue to the next to #244 at `External links open in Franz (instead of browser)` ?

https://github.com/koma-private/recipe-teamwork-projects/issues/1

**Comment by krysalia** [comment]
the workaround "right click and select "open link"" does not work for me (win 7 x64, fresh install of version 5). With the old version of the 5 that I had, clicking on a picture gave a small franz window with the tweet containing the picture. Now it doesn't do a thing, just like it doesn't do a thing with links.

**Comment by gimbo** [comment]
The "right click and select open link" workaround also doesn't work (for me) in the Facebook Messenger service when viewing something that's been shared by someone (e.g. a video) - there if I right-click on the link that would normally taken me to the item being shared, I just a greyed-out "open" menu item.

**Comment by StephaneLa** [comment]
@haraldox Would you add this related issue to the next to #651  at External links open browser, but do not load URL. 

Restart chrome doesn't work

**Comment by StephaneLa** [comment]
Thx for your answer on my issue. 
I tried to just "right-clicking on the link and choosing "Open Link"", but doesn't work.

**Comment by colinodell** [comment]
https://github.com/meetfranz/franz/issues/698 is another instance of "External links open in Franz"

**Comment by borismmitrovic** [comment]
had 4 on Mac, chrome -> suggestion to reset chrome fixed the problem.

**Comment by webworker01** [comment]
Please make links open in default system browser

**Comment by groop-dev** [comment]
Please let me open in the browser i choose. I dont want safari I want chrome.

**Comment by mycaule** [comment]
Also found it anoying being logged in many sites in my favorite browser, when I click on a link on Franz it opens another browser instance wth Electron, inviting me to login again. 

Example : Opening a JIRA or Confluence link inside an email service;

**Comment by davincho** [comment]
I had a similar issue where all Franz links were opened in Safari although Chrome was my default browser.

For me the following solution worked:

1. Set Safari as default browser
2. Close Safari and Chrome completely
3. Open Chrome and set it as default browser
4. Close Chrome
5. Click a link in Slack -> opens in Chrome again

**Comment by igreil** [comment]
Using 5.0.0 on Linux (SuSE Tumbleweed), all my links open in Firefox despite Chrome being the default browser. "Open Link in Browser" does not change that behavior, it still fires up Firefox.

**Comment by tnrich** [comment]
I'm still definitely seeing the opening a small blank tab issue.
This in the latest version of franz Version 5.0.1 (5.0.1.1237):

![franz](https://user-images.githubusercontent.com/2730609/54959603-e583b680-4f16-11e9-926b-d16970a2bb39.gif)

**Comment by pandaiolo** [comment]
I added a new occurrence of this bug (I think) in #1589. I did not find a workaround as 1) GMail hijacks the right click, and 2) It's probably not a link anyway.

Are there any clues on how to resolve this bug, either per service or globally?

**Comment by yuzhakovvv** [comment]
Is there a way to setup a default option of how open links? I would like to set it to Browser. Because some links are opened in Browser, but some in Popup
