### ISSUE TITLE
Can`t login with Office 365 Outlook when have a .de domain

### ISSUE THREAD

**Issue by tayfuuun** [meetfranz/franz#578]
Our company uses office 365 in the German cloud, the address ends with `.de` `outlook.office.de`

### Expected Behavior
Working with the German domain `.de` `outlook.office.de`

### Current Behavior
> Sign In
> Sorry, but we’re having trouble signing you in.
> We received a bad request.

> Additional technical information:
> --
> Correlation ID: f640c17a-9208-49af-805e-3d3b931d27bc
> Timestamp: 2018-01-15 15:05:57Z
> AADSTS50011: The reply address 'https://outlook.office365.com/owa/' does not match the reply addresses configured for the application: '00000002-0000-0ff1-ce00-000000000000'. More details: not specified

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/6418678/34948942-e45beec0-fa0e-11e7-8b23-b658f548cb7b.png)

### Steps to Reproduce (for bugs)
1. Try to login with a german office 365 account

### Context
Support of the German microsoft cloud

### Your Environment
* Franz Version used: `Version: 5.0.0-beta.15` `Release: 1.7.9 / linux / x64`
* Operating System and version: `Ubuntu 16.04 LTS` `64-bit`

**Comment by mfuhrmann** [comment]
+1

**Comment by mrmnmly** [comment]
same problem here

**Comment by bennokress** [comment]
sadly this is still an issue on beta 18
