### ISSUE TITLE
The apps do not work if Franz starts without internet connection

### ISSUE THREAD

**Issue by larichu** [meetfranz/franz#581]
When I start my computer Franz starts automatically, when I do not have internet connection (for different reasons) all the apps start blank and I have to close the app and start again.
The downside of this, is when I close the app then when I start using it againg if I minimise it. It does not stay in the taks bar and I have to search for it to use it every time.

![image](https://user-images.githubusercontent.com/35484222/34978675-4ee345a0-fa9f-11e7-9777-d8adb16f3998.png)

**Comment by haraldox** [comment]
@larichu Previous versions of Franz are not supported anymore. Please update to Franz 5.
