### ISSUE TITLE
Bad Request when trying to log into Slack

### ISSUE THREAD

**Issue by Sofoca** [meetfranz/franz#583]
### Expected Behavior
A login screen shows up after adding the Slack service. 

### Current Behavior
A browser error message appears (see screenshot).

### Screenshots (if appropriate):
<img width="811" alt="bildschirmfoto 2018-01-16 um 09 59 03" src="https://user-images.githubusercontent.com/8494954/34980226-1cb6c66a-faa4-11e7-9244-c81b2c10e523.png">

### Your Environment

* Franz Version used: Version 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: macOS High Sierra 10.13.2

**Comment by Sofoca** [comment]
Found the problem: There was no workspace set when creating the service. Maybe add an error message that represents that?

**Comment by adlk** [comment]
This message is presented by Slacks server, we don't have any influence over that. But you are indirectly highlighting another issue here: team id not required for services like Slack. ;)

**Comment by adlk** [comment]
I'm closing this issue as the actual problem is tracked internally. Thanks for your hint!
