### ISSUE TITLE
Right-Click Context Menu Within Webview Has Issues Opening

### ISSUE THREAD

**Issue by seesemichaelj** [meetfranz/franz#585]
### Expected Behavior
When I right click within a Webview/service, I expect the right-click context menu to appear immediately.

### Current Behavior
When I right click within a Webview/service, the context menu opens/closes very quickly multiple times (like a flicker). It's final state (open or close) is not persistent: sometimes it stays open, sometimes it disappears without reappearing.

Right-clicking anywhere other than the webview (i.e. on the service icon in the sidebar) works as expected. This behavior seems to be persistent across all of the services I use (Slack, Discord, Messenger, Google Keep, Google Calendar, GroupMe, and Gitter).

### Screenshots (if appropriate):
![peek 2018-01-15 17-38](https://user-images.githubusercontent.com/549323/34997164-b7f5e00c-faa9-11e7-8900-300c7b653bef.gif)

### Steps to Reproduce (for bugs)

1. Open a service (Slack, Discord, Messenger, Google Keep, Google Calendar, GroupMe, and Gitter has been tested)
2. Right-click within the webview

### Context
I'm trying to right-click to do several different options: copy links, copy images, copy image URLs, etc.

### Your Environment

* Franz Version used: 5.0.0-beta.14
* Operating System and version: **Issue exists on elementary OS Loki 0.4.1. Issue does not exist on Windows 10 Pro 1709**

I run other Electron applications in the same OS which have no issue with the context menu

**Comment by seesemichaelj** [comment]
I am not having this issue anymore after upgrading to 5.0.0-beta.15. Will verify on my work machine tomorrow before closing this issue.

**Comment by seesemichaelj** [comment]
Closed as the issue was resolved in 5.0.0-beta.15

**Comment by haraldox** [comment]
@seesemichaelj great to hear it!
