### ISSUE TITLE
Sounds even if disabled

### ISSUE THREAD

**Issue by lucosent** [meetfranz/franz#586]
Despite all the notifications are disabled for every services and for the whole Franz, I still hear sounds

**Comment by haraldox** [comment]
Thanks for your submission, to assist us with dealing with this as promptly as possible please fully apply the issue template:
https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md

**Comment by haraldox** [comment]
probably Duplicate of #509

**Comment by haraldox** [comment]
related to #460
