### ISSUE TITLE
Skype Voice and Video not usable

### ISSUE THREAD

**Issue by hpaar** [meetfranz/franz#59]
In Skype the Voice and Video Icons are greyed out

Therefore this functionalities can not be used.

* Franz Version used: 5.0.0 beta10.7
* Operating System and version: macos 10.13

**Comment by adlk** [comment]
Skype is disabling their call function for other browsers than IE except you install the chrome extension. Unfortunately the latter isn't possible. However I'll do experiments to manipulate the user
 agent to get the call function working. 
 
---

This repository is only for the Franz client. Please report issues in the dedicated recipe repository.
www.github.com/meetfranz/recipe-skype
