### ISSUE TITLE
Customize Touchbar on Mac - Smileys on Touchbar

### ISSUE THREAD

**Issue by Mulija** [meetfranz/franz#595]
### Expected Behavior

On the Mac Touchbar you could add a button for smileys. The touchbar should be customized via view or should contain the smileys by default.

### Current Behavior

Currently you can only switch between the different messengers via the touch bar

### Possible Solution

On the Mac Touchbar you could add a button for smileys. The touchbar should be customized via view or should contain the smileys by default.

### Your Environment

* Franz Version used: 5.0.0-beta.15
* Operating System and version: macOS High Sierra 10.13.2

**Comment by haraldox** [comment]
duplicate of #576 and #550

**Comment by haraldox** [comment]
Duplicate of #550
