### ISSUE TITLE
Can't add any services 

### ISSUE THREAD

**Issue by ralfbiedert** [meetfranz/franz#597]
When I start Franz (5.0.0-beta.15) and try to add a service, nothing happens (see video). At the same time, I get `not a valid semver version` errors on the developer console. 

### Expected Behavior

Adding a new service should add it.

### Current Behavior

Adding a new service does not add it.

### Screenshots (if appropriate):

[Video when clicking button](https://i.imgur.com/2kI4uKy.mp4)

![console](https://user-images.githubusercontent.com/301288/35144463-e34488be-fd04-11e7-828e-61d7fa28367a.png)

### Steps to Reproduce (for bugs)

1. Click `Add new Service`
2. Select service

### Context

I was trying to add a service.

### Your Environment

* Franz Version used: 5.0.0-beta.15
* Operating System and version: macOS 10.13.2

**Comment by haraldox** [comment]
@ralfbiedert thanks for your video, that makes it easy to understand what's going on...

did you try to remove Franz completely (also from `~/Library/Application\ Support` and re-installing?

**Comment by ralfbiedert** [comment]
Thanks for the swift reply. 

If I delete `~/Library/Application Support/Franz` Franz starts as expected, asks me to sign in, and then shows my old services (e.g., Slack, Whatsapp, ...). 

However, once I quit Franz and restart it again, the above happens.

**Comment by ralfbiedert** [comment]
Update: To "permanently" get rid of the problem until this is properly fixed by the devs, do:

- Quit Franz
- Edit `~/Library/Application Support/Franz/recipes/mailbox.org/package.json`
- Change `"version": "1.1"` to `"version": "1.1.0"`
- Start Franz
- Delete (Right click -> Delete), not disable, `mailbox.org` service.

**Comment by haraldox** [comment]
@ralfbiedert thanks for this tip, should be a quick fix
