### ISSUE TITLE
Order of some `yarn` command args

### ISSUE THREAD

**Issue by GustavoKatel** [meetfranz/franz#6]
I've noticed that in many locations you guys use `yarn add global *package-x*`. This will install the package *global* and the package *package-x*. As pointed in the `yarn` [docs](https://yarnpkg.com/lang/en/docs/cli/global/). I suppose this is not the intended behavior.

### Expected Behavior
Globally install a package

### Current Behavior
Install two packages:
- Package named *global*
- Package specified

### Possible Solution
Change the order of the arguments. Like this:
```bash
$ yarn global add package-x
```

**Comment by adlk** [comment]
You are right, this should be fixed in the docs. I need to so some checks as well if it's still necessary to install gulp 4 globally as the preferred way would be to just have it as a local dependency.

**Comment by GustavoKatel** [comment]
Well... Since you have everything on your `scripts` node in the `package.json`, you could avoid installing a global package and the package.json would point to the local gulp version (if it is indeed necessary to have it).

**Comment by adlk** [comment]
I initially had some issues with the local gulp setup but at this point I can't exactly remember what it was. However, a few simple tests will shed some light on this.

**Comment by adlk** [comment]
Was fixed in #353
