### ISSUE TITLE
I have many slack accounts and all with the same logo in the leftsidebar on mac. HOw can customize the title

### ISSUE THREAD

**Issue by francisco-ramirez** [meetfranz/franz#60]
Hi,

I have many slack accounts and all with the same logo in the left sidebar on mac. 
In windows is possible to see the name of every slack account but the mac app is not possible to see the name, that means that I can see fast where is the slack account that I search, I have to do hover over all my accounts to find it or make shortcodes.
In the mac pro I can see the name in the touchbar but I want to see the name in the app not in my touchbar.
How can customize the title or change the icon??
https://prnt.sc/h0fx2r

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by adlk** [comment]
Once you sign in into your Slack channel, Franz will replace the icon with your teams icon.
I'm closing this issue for now. If it doesn't update the icon feel free to reopen this issue and I'll flag it as "bug".
