### ISSUE TITLE
Disable audio across all services 

### ISSUE THREAD

**Issue by lklijnsma** [meetfranz/franz#601]
### Current Behavior
 I've disabled the audio but I still get the audio notifications. For example - with Whatsapp, I figured out that I have to mute each conversation individually within the service (annoying) but for Gmail, I can't turn it off at all. The audio goes off even when my computer is on mute. As you can imagine it's really irritating for my colleagues and myself. Please disable audio across all service - for real. See screenshot below that I have everything disabled from an overall settings point of view. Hope to be able to turn Franz on again but not until this issue is fixed. 

 

### Screenshots (if appropriate):
![screen shot 2018-01-22 at 12 21 54 pm](https://user-images.githubusercontent.com/35689441/35218750-0e4d0438-ff70-11e7-81ba-a55e15407dc9.png)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by haraldox** [comment]
@lklijnsma does Franz still exhibit the same behavior in your environment?

**Comment by haraldox** [comment]
related to #509

**Comment by lklijnsma** [comment]
@haraldox Yes, it does.

**Comment by Duartemartins** [comment]
For me this doesn't happen when muted but can confirm with whatsapp.

**Comment by oitray** [comment]
Still happening with Discord as well
