### ISSUE TITLE
Invite page during signup process - seeing [object Object]

### ISSUE THREAD

**Issue by danielhazrati** [meetfranz/franz#603]
### Expected Behavior
I'm not entirely sure what I expected to see.. just not [object Object] :)

### Current Behavior
See above.

### Screenshots (if appropriate):
![screenshot from 2018-01-22 18-35-18](https://user-images.githubusercontent.com/14818558/35237813-9ea45486-ffa3-11e7-887f-a233247d219a.png)

### Steps to Reproduce (for bugs)

1. Sign up as individual account
2. Select no contribution (sorry :( )

### Context
Unable to invite friends using the developer's desired functionality.

### Your Environment

* Franz Version used:  5.0.0-beta.15
* Operating System and version: Ubuntu 17.10

Please let me know if you need any more information - I hope I've been descriptive enough!

**Comment by haraldox** [comment]
@danielhazrati this has been fixed and will be merged soon...

**Comment by danielhazrati** [comment]
Hi @haraldox, apologies - I couldn't see any issues relating to this. Feel free to close this issue.

I'll keep an eye out for the merge.

**Comment by cdnbacon** [comment]
In case it's been merged, I'm seeing the same issue in Version 5.0.0-beta.15 (5.0.0-beta.15.607) on MacOS that I just downloaded now.

**Comment by haraldox** [comment]
@cdnbacon not merged yet
