### ISSUE TITLE
Change keyboard shortcuts

### ISSUE THREAD

**Issue by davejones444** [meetfranz/franz#605]
### Feature Description

I want to be able to easily change keyboard shortcuts so it can work better with my global XFCE4 shortcuts.

### Motivation and Context

* Franz Version used: 5.0.0-beta .14
* Operating System and version: MX-Linux 17

**Comment by haraldox** [comment]
Franz is open source, you can easily change the shortcuts in the code, after checking out the repo and before building from source

**Comment by davejones444** [comment]
I'm not really a coder, but thanks your the answer.

**Comment by rdewolff** [comment]
Could we reopen that request? I think the request is fair and the answer "it's open source, do it yourself" is really not the one we should expect from an open source community.

**Comment by Arthur-Henrique** [comment]
Well, I agree with @rdewolff.
It would be really nice to customize Franz shortcuts through an user-friendly option in the official application.

**Comment by rdewolff** [comment]
@haraldox, what do you think?
