### ISSUE TITLE
Screen share with Google Meet does not work

### ISSUE THREAD

**Issue by dbronk** [meetfranz/franz#606]
Connecting to Google Meet calls for audio and webcam seem to work fine.  Can not share screen though.

Windows 10
![2018_01_24_08_46_50_franz](https://user-images.githubusercontent.com/7817799/35335407-835cbac4-00e3-11e8-84b5-d215985a2ffb.png)

**Comment by haraldox** [comment]
screensharing is currently not supported in several services, thanks for bringing up Google Meet!
