### ISSUE TITLE
Viber messenger - feature request

### ISSUE THREAD

**Issue by cotbayunn** [meetfranz/franz#607]
Could you please support one more messenger that is very popular too: its name is Viber.

**Comment by haraldox** [comment]
Viber does not offer a web-based service client, thus can't be embedded in Franz!

This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by david-nedved** [comment]
HI @cotbayunn - I've actually made a franz plugin that integrates Viber (running from your desktop) into Franz here: https://github.com/david-nedved/viber-franz
