### ISSUE TITLE
Service rendering fails and displays white/orange stripes

### ISSUE THREAD

**Issue by closingin** [meetfranz/franz#609]
### Expected Behavior

Render the service properly.

### Current Behavior

The service (web view) is actually loaded (I see by moving my cursor that I can click on some links) but the rendering is messed up. Reloading the service fixes it.

I don't think it's related to the service directly, but to the way rendering checks are done on page load, so I open the issue here.

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/2735603/35350441-f1551bac-010b-11e8-8fa0-62511120a40d.png)

### Steps to Reproduce (for bugs)

I don't know, it just happened.

### Your Environment

* Franz Version used: 5.0.0-beta14
* Operating System and version: Arch Linux with linux-4.14.14-1

**Comment by haraldox** [comment]
indeed there are some issues with Arch Linux... we are currently waiting for OS updates!
