### ISSUE TITLE
Addition: Threema Web

### ISSUE THREAD

**Issue by dabenzel** [meetfranz/franz#61]
Hello,
it would be nice, if you could integrate [Threema Web](https://web.threema.ch/#/welcome).

Thanks in advance!

**Comment by adlk** [comment]
Threema is already on our service wishlist.

This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
