### ISSUE TITLE
Icon issues

### ISSUE THREAD

**Issue by haraldox** [meetfranz/franz#613]
This will become a super-issue for all issues relating to icon bugs and features.

**Comment by virhonestum** [comment]
It would be great if we could select the icon style in the task bar (dark/light), since on elementary OS 0.4.1 Loki it is black and barely visible (see attached image).

Thanks a lot!

![633d0016-d5a7-4c93-9676-9d750ea827e0](https://user-images.githubusercontent.com/26956711/35509123-416a5a40-04f3-11e8-8a76-c66dd1d0ea14.jpg)

**Comment by Jannomag** [comment]
Same here for Solus OS 3.26.2 with Budgie 10.4. Icon is black on a dark background - choosing the icon style out of "auto, black, white" would be nice.
![bildschirmfoto vom 2018-01-31 16-43-16](https://user-images.githubusercontent.com/31586674/35632086-f81fb11e-06a5-11e8-8cc5-a20399e1c06e.png)

![bildschirmfoto vom 2018-01-31 16-43-33](https://user-images.githubusercontent.com/31586674/35632063-e97c2bce-06a5-11e8-8910-14b5091acc97.png)
(it's the icon to the left of the wifi indicator)

**Comment by RBlaine95** [comment]
Same here for Arch on Gnome 3

It's the one to the right of the Bitcoin  
![image](https://user-images.githubusercontent.com/4052340/35796168-4d4d46e4-0a64-11e8-82c8-f6f775ebea51.png)

**Comment by Stanzilla** [comment]
on Windows 10 the taskbar icon looks super fuzzy as well 
![2018-02-12_16-19-34](https://user-images.githubusercontent.com/75278/36103759-951b1404-1010-11e8-84c8-ec56519c34cc.png)

**Comment by MathiasBerwig** [comment]
Clicking on Franz's dock icon launches a second icon in my Fedora 28 with gnome (the problem is related by another user in AppImage/AppImageKit/issues/260). I solved it by adding the line `StartupWMClass=franz` in the app .desktop file.

**Comment by ViperAlpha** [comment]
![image](https://user-images.githubusercontent.com/7623967/54609216-42700000-4a31-11e9-9528-ad021b79c4fa.png)
on Kubuntu 18.04, it looks like this.
