### ISSUE TITLE
Cannot "make as read" Skype messages after someone push emoticon comment to message

### ISSUE THREAD

**Issue by skibsky** [meetfranz/franz#614]
### Expected Behavior
After reading messages or click on left side "make all as read" notification about new message should dissapear

### Current Behavior
After someone click on emoticon to comment message, new notification appear and can't be read at all (even after "make all as read" notification still appears)
### Screenshots (if appropriate):
![skype_notification_issue](https://user-images.githubusercontent.com/35803168/35388146-e09c741e-01d2-11e8-9647-978b86fbbebe.jpg)

### Steps to Reproduce (for bugs)

1. Get emoticon comment by other Skype user on message in conversation

### Your Environment

* Franz Version used: 5.0.0-beta.15 (same problem occured in previous version 4.x.x)
* Operating System and version: Windows 10

**Comment by haraldox** [comment]
This repository is only for the Franz client.

this is an issue for the service recipe of skype, i've moved the issue to the appropriate repo:
