### ISSUE TITLE
Can't Change Settings

### ISSUE THREAD

**Issue by deltreey** [meetfranz/franz#615]
Some settings won't change

### Expected Behavior
Expect settings to be able to be changed

### Current Behavior
Settings don't change

### Screenshots (if appropriate):
![https://i.imgur.com/LGTapVb.gifv](https://i.imgur.com/LGTapVb.gifv)

### Possible Solution
Looks like it's failing to set, but there's no error being presented.  At least it's friendly enough not to pretend it actually changed when it didn't.

### Steps to Reproduce (for bugs)
1.  Go to settings
2.  Change any value other than "Launch Franz on start"

### Context
I was trying to make Franz minimize to tray.

### Your Environment
* Franz Version used: 5.0.0-beta.15
* Operating System and version: Windows 10

**Comment by alecive** [comment]
@deltreey your image is not loaded

**Comment by deltreey** [comment]
Yes, and the link doesn't work because of github's link wrapper but the URL is right which is why I included it. It's a gif of me clicking the settings and them not setting

**Comment by kostasx** [comment]
Same problem here. Tested this on Mac (High Sierra). Even though "Launch Franz on Start" is disabled, the settings are not retained and the option is enabled upon restarting the program.

**Comment by haraldox** [comment]
are you all using the latest beta-15?

**Comment by kostasx** [comment]
Version 5.0.0-beta.15 (5.0.0-beta.15.607)

**Comment by corradopetrelli** [comment]
The real link is this: https://i.imgur.com/LGTapVb.gif
I had the same problem but when I restart my PC this bug is disappeared.

**Comment by kostasx** [comment]
On my Mac, running High Sierra, I get the following behaviour. I open the App, disable the 'Launch on Start' option and close the App. Once I relaunch the App, the setting is not being retained.
Screen recording: https://drive.google.com/open?id=1Dp5yc9G_fgE-v0lgcjp-AFL2Pilc6Ww-

**Comment by haraldox** [comment]
@corradopetrelli @kostasx thanks for the screen recordings ... we'll look into it

**Comment by Stanzilla** [comment]
I have a feeling that they only don't work on a fresh install. After I have restarted Franz a few times, they seem to work now.

**Comment by raduchiriac** [comment]
I have to agree with @Stanzilla I could only reproduce it the very first time. 
Does not happen on a fresh build either.
