### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by calben99** [meetfranz/franz#616]
Please add instagram messaging support!

**Comment by corradopetrelli** [comment]
I would like it too!

**Comment by haraldox** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by danielfm123** [comment]
please!

**Comment by elvisbrens** [comment]
Hello, 

I just found this: https://github.com/alexdevero/franz-instagram-recipe

Seems to work under the recipe/dev folder 
I'm new to this. Is this safe to add?

**Comment by ZeroCool940711** [comment]
hey @elvisbrens how do you install that recipe? 
im on windows and cant find a way to make it work.
