### ISSUE TITLE
Add two email into Gmail's service

### ISSUE THREAD

**Issue by corradopetrelli** [meetfranz/franz#618]
I want to switch my emails with Franz but I think that there aren't this feature.
When I click on "Add account", Franz send me one the browser and It does not change anything.

**Comment by alecive** [comment]
Duplicate of #391 and #430 . See my reply there. You just need to open multiple recipes within franz and you will not have to switch any more.

(I would close the issue but I can't 😎 )

**Comment by corradopetrelli** [comment]
Thanks!
