### ISSUE TITLE
Resetted settings of desktop notifications for Facebook Messenger 

### ISSUE THREAD

**Issue by nonamehr** [meetfranz/franz#619]
### Expected Behavior
Turning off desktop notifications within the settings-dialog of Facebook Messenger should be saved and not changed after Franz-restart.

### Current Behavior
After deactivating desktop notifications and a Franz-restart, desktop notifications are active again.

### Additional Information
Checking the settings in Facebook by browser reveals that turning on or off within Franz doesn't seem to effect the settings within the webpage: The settings there remain as set before, independently from the setting in Franz.
Additionally: The bug is new to Franz 5.0.0. Franz 4 and 3 had no problems with this.

### Steps to Reproduce (for bugs)
1. Open Franz
2. Choose Facebook Messenger PlugIn
3. Go To Settings.
4. Disable Desktop notifications.
5. Quit Franz.
6. Reopen Franz.
7. Go to FB-settings again and see: Desktop notifications are turned on again.

### Context
Desktop notifications can be obtrusive if unwanted. Not being able to deactivate them since the new version of Franz is annoying.

### Your Environment
* Franz Version used: 5.0.0 beta15 (beta14 had the same problem.)
* Operating System and version: Win7 Pro 32 and 64 bit

**Comment by dannyqiu** [comment]
A decision to auto-enable the desktop notification in the Facebook Messenger Plugin is so that notifications can be controlled through Franz rather than Messenger itself. If you right click on the Messenger icon in Franz, you can disable notifications.

<img width="174" alt="screen shot 2018-01-28 at 12 47 48 pm" src="https://user-images.githubusercontent.com/1170755/35485169-7bbf2628-0429-11e8-9d27-2973da2688a3.png">

**Comment by nonamehr** [comment]
Ah ok, thanks for the solution! :-) Works fine now.
I saw this setting before but thought disabling notifications would result in complete deactivation of any kind of notification, not just desktop notifications. Maybe it would make sense to specify this by adding "Disable desktop notifications" instead of "Disable notifications".

**Comment by haraldox** [comment]
Duplicate of #536
