### ISSUE TITLE
Option to display the service name

### ISSUE THREAD

**Issue by Kwadz** [meetfranz/franz#626]
If we use multiple accounts with the same service, let's say 2 accounts of Skype, we are not able to identify them just with the icon. 

I think at least the option to display the name should be offered in the settings.

![screen shot 2018-01-29 at 18 32 08](https://user-images.githubusercontent.com/1472599/35524789-ea763148-0522-11e8-9076-8035d65382c1.png)

**Comment by haraldox** [comment]
@Kwadz if you hover over the icon, you will see the service name ... hope this resolves your issue!

**Comment by Kwadz** [comment]
No, because this is against UX. The user wastes too much time to check the good tab.

Why did you close the issue while my suggestion is relevant? If we follow your rationale, we could also say that installing [Rambox](http://rambox.pro/) resolves the issue...

I think the best approach is to offer the option, for example with an horizontal bar of tabs.
