### ISSUE TITLE
Can't connect to Franz online services

### ISSUE THREAD

**Issue by ajason08** [meetfranz/franz#627]
### Expected Behavior

normal login using my google account.

### Current Behavior

I cannot login in a specific computer (it is in my work), but I can do it in others such as my PC.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/8420899/35528879-e4870574-04f4-11e8-91c0-fb4b5a5ab4b0.png)
My internet connection is ok but the button "try again" have no any effect. And this version works well in other computer in the same lan network.

### Possible Solution

I tried removing temp files in the appData and so on, and re-install, but it doesn't works.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

Most of my time using Franz is only at work. I had used Franz in this computer since more than 1 year, but the problem started after some beta updates of version 5.0

### Your Environment

* Franz Version used: franz-setup-5.0.0-beta.15 (although version 4.0 works, certainly I prefer 5.0) 
* Operating System and version: windows 7, 64 bits.

**Comment by haraldox** [comment]
@ajason08 hope the issue did resolve in the meantime?

**Comment by karthisammannan** [comment]
I am also facing the same issue. Is there any Solution?
Thanks, advance.

**Comment by KangBeunghar** [comment]
i just have same issue 
![image](https://user-images.githubusercontent.com/4023144/37068414-28cca910-21e1-11e8-90b6-7c73e2c5fc95.png)

**Comment by paolodenti** [comment]
Same issue

**Comment by highbass** [comment]
having same issue... version 5.0.0-beta-18

**Comment by pmbuban** [comment]
same issue here. reinstalled and no luck

**Comment by Wolf2789** [comment]
Same here..

**Comment by gellouglas** [comment]
Same issue. ubuntu 16.04, franz version 5.0.0-beta-18

**Comment by jpwitkowski11** [comment]
same here too - os x mojave, franz v5.0.0-beta.18

**Comment by hoodpablo** [comment]
same issue in windows 7

**Comment by RafaBenard** [comment]
Bump, same issue :(
Franz v5.0.0-beta.18

**Comment by milansosef** [comment]
Same issue here,  v5.0.0-beta.18 on windows 10

**Comment by quangvinh1225** [comment]
Same issue on ubuntu 18.04

**Comment by gellouglas** [comment]
it seems to me that the server is down

**Comment by WeiTang114** [comment]
Same here. MacOS 10.13, v5.0.0 beta.18

**Comment by huylinharchitect** [comment]
same on win 10

**Comment by sandi0982** [comment]
same here on my windows 10. The issue is spreading.

**Comment by mtamma** [comment]
same here on windows 8.1 pro

**Comment by juvarabrera** [comment]
Same here on windows 10. using v5.0.0.beta.18

**Comment by Granvanoeli** [comment]
Same here, on Mac OS Mojave 10.14 using Version 5.0.0-beta.18 (5.0.0-beta.18.903).

**Comment by LegendNoobz** [comment]
Same here on Windows 7 pro using version 5.0.0-beta.18

**Comment by dancsonth** [comment]
I just upgraded to Mojave and Franz is not working at all. Latest MacOS on MBP15 inch, latest Franz version.

Whatever I do it is not connecting: I don't even get to the login screen:
<img width="1677" alt="screen shot 2018-10-26 at 12 53 41 am" src="https://user-images.githubusercontent.com/14165991/47545309-a135b100-d8b9-11e8-839f-ea852dbc9950.png">

**Comment by wibimaster** [comment]
Same on Ubuntu 18.04 with last Franz version

**Comment by morsstepan** [comment]
Same issue on Ubuntu 16.04 with Franz 5.0.0-beta.18

**Comment by carolus10benny** [comment]
Same issue on MacOS High Sierra version 10.13.6.. uninstall app for solution.

**Comment by HsuTing** [comment]
![screen shot 2018-10-26 at 2 00 10 pm](https://user-images.githubusercontent.com/8859179/47547307-83069a00-d927-11e8-8b2a-661c6aa41446.png)

I use [login page](https://meetfranz.com/auth/login/) and I found 503.
The server is down.

**Comment by DcR-NL** [comment]
Same on Fedora 28 with v5.0.0 beta 18.

**Comment by DIStudiosHQ** [comment]
Same here, Win10

**Comment by cenkingunlugu** [comment]
Franz API is down. Getting 503, so app itself can not connect to online services.

**Comment by DcR-NL** [comment]
I can use Franz again. Problem solved, I guess... :)

**Comment by claudiutms** [comment]
fixed for me.
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

**Comment by carolus10benny** [comment]
DONE Gaes..

**Comment by thcrnk** [comment]
Similar issue today: 
`/Applications/Franz.app/Contents/Resources/app.asar/api/utils/auth.js:42 GET https://api.franzinfra.com/health 503 (Service Unavailable: Back-end server is at capacity)`

**Comment by chanusch** [comment]
I have the same problem since today on the Windows Client. 

Version: 5.1.0. Release: 4.1.4 / win32 / x64

**Comment by msaladyk** [comment]
Same for me, macOS Mojave 10.14.5

**Comment by Kendalor** [comment]
same for me

**Comment by aclowwwn** [comment]
I guess there's something with the servers? Looks like an epidemy...

**Comment by samathos** [comment]
Same here. I do cant connect to my franz..its been working perfectly till yesterday.. sudden shutdown.. have uninstalled my 5.0 and re installed to 5.1.0 but it shows the same..anybody knows to fix this
![Franz not working](https://user-images.githubusercontent.com/51313594/58782294-cfbbfd00-85fb-11e9-8899-c9deaa833da7.PNG)

**Comment by thcrnk** [comment]
Now everything is working, the google cloud platform was offline, so I guess it is hosted there.

**Comment by julian916** [comment]
Is not working since Wednesday in my Mac 🤷‍♂

**Comment by orangerdev** [comment]
it's not working right now

**Comment by dschroed** [comment]
happening on 
OSX Mojave 10.14.6

I have had this occurring in the last 3-4 months. 

Suspecting Kaspersky Internet Security 2020 impacting this - when waking from Sleep. 
When QUITING Kaspersky and starting Franz service again, it most the times seems to run fine again.

**Comment by jdwhite** [comment]
Started seeing this again today on multiple clients.
