### ISSUE TITLE
Franz is permanently set to start up automatically when computer boots and can't be deactivated.

### ISSUE THREAD

**Issue by DrWongKC** [meetfranz/franz#629]
I can't set Franz to not start automatically after computer is booted up each time. The toggle goes to startup automatically even though I disable it earlier.

### Expected Behavior

When I disable the automatic startup after a computer boots into desktop, it should not startup automatically.

### Current Behavior

When I disable the automatic startup after a computer boots into desktop, it should not startup automatically.

### Steps to Reproduce (for bugs)

1. Simply set Franz to not start automatically, and then close it.
2. Restart computer, and Franz should not start, but now open it and leave the settings alone.
3. Restart computer
4. Once at desktop Franz with automatically startup by itself even though it never was set to startup automatically.

### Context

I just want to open Franz by myself as it's a nicer transition to using the application and my laptop as a whole.

### Your Environment

* Franz Version used:
Version 5.0.0-beta.15 (5.0.0-beta.15.607)

* Operating System and version:
Mac OS High Sierra 10.13.3 (17D47)

**Comment by corradopetrelli** [comment]
Try this solution (until Programmers delete this bug):
1. Open System Preferences.
2. Go to Users & Groups.
3. Choose your nickname on the right.
4. Choose Login items tab.
5. Check startup programs you want to remove.
6. Press the “–” sign below.
7. You’re done.
8. If you need to add an item back, press “+” and choose the app you’d like add.
9. Then restart your Mac to make the changes.

**Comment by haraldox** [comment]
@corradopetrelli thanks for the detailed workaround in the meantime, while we fix this bug!

**Comment by corradopetrelli** [comment]
@haraldox De rien!

**Comment by rgwsk65** [comment]
Any workaround for Windows 10?

**Comment by unlucio** [comment]
I keep removing this app from my startup items and it keeps setting its self back like a virus.
Why in the world an IM client should be auto-started like a demon is beyond me, but how do I stop its viral behaviour? :/

**Comment by prvst** [comment]
I'm running Franz on a Linux Mint 18.3 and I'm having the same issue. I already tried to remove the program from the startup list but every time I reboot my PC it goes back there again, Any workaround for Linux users ?

**Comment by TheBenMay** [comment]
Was having a similar issue on Ubuntu 1604. Beta 17 fixed my problem.

**Comment by jsnider** [comment]
I was having issues with this on Mac. I fixed it by unchecking the "Launch on start" setting, changing the language to spanish causing some kind reload, and then changing the language back to english. Then the change persisted.
