### ISSUE TITLE
Can't open any link or file on any service

### ISSUE THREAD

**Issue by hectorbus** [meetfranz/franz#63]
i'm Using Mac OS High Sierra 10.13

When i try to open a link or file, doesn't do it. It only opens a empty google chrome tab, but with out  content.

**Comment by adlk** [comment]
Can you please go a little into detail what services you are using?

**Comment by flim-basebone** [comment]
This happens to me too, on gmail and slack. Franz version is 4.0.4, macOS High Sierra 10.13.
I tend to hardly ever reboot/restart apps, so I'm not sure since when this might be active - I'm experiencing it for the last 3 days at least.

**Comment by hectorbus** [comment]
For me it's happening on Messenger, WhatsApp, Slack, Gmail.

**Comment by adlk** [comment]
@hectorbus & @flim-basebone what version of Franz do you use?

---

Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)

**Comment by flim-basebone** [comment]
I've upgraded to Franz 5 by downloading the latest version - it now reports itself as "5.0.0-beta.11 (5.0.0-beta.11.135)". The problem still persists - clicking on links will open an empty window in my browser.

**Comment by thenerdynerd** [comment]
I have the same issue latest Franz and previous version experience the same issue. I am now able in this beta to right click and copy link (which we didn't have before)

**Comment by gabrihellmateus** [comment]
Same here.
Version: **5.0.0-beta.13**

Can't open any link. If I right click and click on "Open Click" will open a new blank window.
I'm using Whatsapp, Messenger, Telegram and Gmail services.

**Comment by gabrihellmateus** [comment]
Turns out that is something with MacOS High Sierra, Electron and Chrome.
Updating to the latest version of Chrome fix this issue.

https://github.com/electron/electron/issues/10948

**Comment by adlk** [comment]
@gabrihellmateus thanks for the info.
@hectorbus does this solve your issue?

**Comment by flim-basebone** [comment]
Definitely works again for me - didn't make the connection to chrome before. Guess I'm slipping into a "never restart" workflow with laptops these days :-)

**Comment by Brun0urs** [comment]
Thanks guys, you saved the day!

**Comment by adlk** [comment]
I'm closing this issue as it seems to be chrome related.
