### ISSUE TITLE
Linux App Image - Fedora 27 Crash

### ISSUE THREAD

**Issue by marct83** [meetfranz/franz#632]
Upgraded to Fedora 27 now the App Image crashes the GUI. 

### Expected Behavior
Franz opens.

### Current Behavior
GUI Crashes.

### Your Environment

* Franz Version used: Newest Beta from the site
* Operating System and version: Fedora 27 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jdewinne** [comment]
Any particular error message?
I'm also on F27 (clean install) and running beta15. It works fine (except for the already known cpu usage issue).

**Comment by marct83** [comment]
Sorry. This is now working.
