### ISSUE TITLE
So there is a backdoor miner in this app

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [meetfranz/franz#633]
https://github.com/meetfranz/franz/blob/master/src/lib/Miner.js

**Comment by webworker01** [comment]
Wow thanks dude, good find

**Comment by BrianGilbert** [comment]
https://github.com/meetfranz/franz/pull/587

**Comment by RBlaine95** [comment]
It's not a backdoor miner.  
It's a donation option that can be optionally turned on.  
The button to turn it on was removed a while ago, but the script is still present. I've been using franz5 since first linux release and have never had issues relating to mining.

**Comment by haraldox** [comment]
the optional mining feature to receive a free premium account has since been long removed!

**Comment by matheusdavidson** [comment]
Not sure if it was removed, noticed from time to time franz cpu and memory usage gets crazy

**Comment by c-urrutia** [comment]
Franz was minning in my computer today! (11-19-2019)


![6e993293-aa72-4413-816d-68cd97ba6cc2](https://user-images.githubusercontent.com/49634547/69194970-19d46480-0af0-11ea-8f44-cc373fafc6d6.jpg)
- Before/After killing the app...
