### ISSUE TITLE
service available for imessage?

### ISSUE THREAD

**Issue by freudigerregt** [meetfranz/franz#634]
hi franz-app,

a question: when will franz be able to use imessage-accounts?
that's the only reason, why i don't use it yet, because: imessage everyone uses who has an iphone and it's the same like whats app.

greets flo from augsburg

**Comment by TobiasFeld** [comment]
As i know, iMessage is only integrated on mac os and ios. There is no official way to use it outside these system. That means it will not be possible to have an official service in messaging tools like franz.

**Comment by freudigerregt** [comment]
well, exactly that’s the point.
the intention of franz is to give you one solution for all purposes.

and because it’s not possible to integrate the standard-solution of apple, you won’t ever be able to have everything in one app.

you should integrate it… make an inofficial way or a plugin, why not (as long as it’s legal). 

there are a lot of plugins and add ons for mac os … and i have to say, that the desktopversion of the messages app of mac ost defintiely does not work very reliable and good.

greets flo

**Comment by ronjouch** [comment]
Would love to see iMessage supported. Previous (2016) mentions of iMessage by the Franz team on Twitter: 

- [1](https://twitter.com/franzmessenger/status/726847568819441664?lang=en): *"iMessage is technically tricky but we are looking into any possible options :)"*
- [2](https://twitter.com/franzmessenger/status/715860996489932800?lang=en): *"iMessage is going to be challenging but it's certainly on our list"*

**Comment by haraldox** [comment]
i've read somewhere that the native Messages app in macOS is actually HTML-based and rendered in a webview ... can't find the source though!

leaving this issue open, looking for contributors who'd like to investigate

**Comment by TRTAFT** [comment]
Im so excited about Franz and hating Apple right now.  If we are “allowed” to use other email platforms, I don’t understand why they won’t open up messaging.  Nobody wants to Email anymore.  All of my clients message and its so difficult to manage, archive, search.  

What are the consequences of turning iMessage off?

**Comment by BrianGilbert** [comment]
not sure if this will provide any ideas.. https://github.com/linjunpop/imessage

**Comment by dijs** [comment]
Hmm... doubt it. I checked out the source on that. Seems to just communicate with the `Messages` app for all functions. This *may* work for Mac versions of `franz`, but it is really hacky.

**Comment by jwillis0720** [comment]
@BrianGilbert it seems that ruby script is just writing an apple script to communicate with iMessage. A bit hacky if you ask me. Cool. But hacky 
 <code>
      script = <<-SCRIPT
      on run argv
              set toAddress to first item of argv
              set message to second item of argv
              tell application "Messages"
                      send message to buddy toAddress of (service 1 whose service type is iMessage)
              end tell
      end run
      SCRIPT
      `osascript -e '#{script}' '#{contact}' '#{text}'`
</code>

**Comment by adlk** [comment]
As for now, iMessage is still not feasible. 

As a heavy iMessage user, this is in my interest but there are simply no resources to add this service :(

**Comment by ArcticAnna** [comment]
Please make a huge 'release' news when you figure it out! :) 
(Sure you will). 
Anna

**Comment by andrewmclagan** [comment]
Yeah, so frustrating! As I believe like myself, this is the single reason allot of people are not using this app.

**Comment by dayrem** [comment]
New to Franz and absolutely see the value. without iMessage, I don't see me keeping/paying for the service.  @adlk figure out how to add iMessage and I (and millions of others) become paying users.

**Comment by IkenHuub** [comment]
Just to let you know, https://www.beeperhq.com/ kind of succeed. So I guess so could you. :)


"How in the world did you get iMessage to work on Android and Windows?

This was a tough one to figure out! Beeper has two ways of enabling Android, Windows and Linux users to use iMessage: we send each user a Jailbroken iPhone with the Beeper app installed which bridges to iMessage, or if they have a Mac that is always connected to the internet, they can install the Beeper Mac app which acts as a bridge. This is not a joke, it really works!"

**Comment by IkenHuub** [comment]
https://www.macrumors.com/2021/01/21/beeper-brings-imessage-to-android-and-windows/
