### ISSUE TITLE
Hipchat keeps logging me out

### ISSUE THREAD

**Issue by judithsorted** [meetfranz/franz#635]
I have been using Franz voor webwhatsapp and Hipchat.

The problem is that I have to sign in to Hipchat every time I minimize the Franz-screen.
I have the 'keep me signed in'-box checken of coarse.

**Comment by haraldox** [comment]
this is a known issue, possibly a 

Duplicate of #113

**Comment by haraldox** [comment]
Duplicate of #113

**Comment by judithsorted** [comment]
is there a way to fix it? My colleagues don't seem to have this problem

**Comment by haraldox** [comment]
@judithsorted we're looking at the problem... in the meantime, can you maybe identify what differences in the environment your colleagues have (OS, Franz version, etc.)?

**Comment by judithsorted** [comment]
I use Franz 5.0.0-beta. 15 and MacOS High Sierra. Version 10.13.2
