### ISSUE TITLE
Getting logged out from third-party Gmail accounts every time Franz is closed

### ISSUE THREAD

**Issue by filipeabperes** [meetfranz/franz#638]
I have a couple third-party email addresses that are managed through Gmail (google services), such as institutional (.edu) accounts. To log in to these accounts, the Google log in screen takes you to an institutional log in screen, where you input your credentials. On these types of account, however, every time I close Franz (full quit on Mac OS, haven't tested on other OSs) and re-open, I'm logged out and have to log back in. This does not happen for "regular" Gmail accounts, where the sessions are stored and I don't need to log back in. Also, in Chrome (and other browsers, I believe) these sessions are saved properly, so that after closing the browser these accounts are still logged in.

### Expected Behavior
Keep the session saved for institutional Gmail accounts. 

### Current Behavior
When closing and re-opening Franz institutional Gmail accounts are logged out.

### Steps to Reproduce (for bugs)
On MacOS, quit (Cmd-Q) and re-open Franz 

### Your Environment

* Franz Version used: 5.0.0-beta.15
* Operating System and version: MacOS High Sierra

**Comment by haraldox** [comment]
@filipeabperes interesting, how long does the session last in chrome?

**Comment by filipeabperes** [comment]
@haraldox Don't know if theres an actual time limit. In my experience it lasts "forever" -- until I delete cookies or something like that in some cases, or in other cases until the institution-mandated re-login time (e.g. every 30 days)

**Comment by alecive** [comment]
@haraldox could it be related to this one also? https://github.com/adambirds/recipe-office365-owa/issues/8

By the way it happens only on Linux (not on Windows), at least for me.
