### ISSUE TITLE
Skype: Copy and Paste Images

### ISSUE THREAD

**Issue by marfar00** [meetfranz/franz#639]
I cannot copy any images directly into chat with copy and paste.
I have tried with shortcuts as CTRL + C and CTRL + P , too

Your Environment
Franz Version used: 5.0.0-beta.15
Operating System and version: Windows 10

**Comment by haraldox** [comment]
@marfar00 i tested this behavior in the browser, it is exactly the same as in Franz: copying & pasting images only pastes the image URL, dragging and dropping a (native) file or image uploads correctly.

@adlk skype apparently handles this well (no bugs like with gmail #76, #476, #72, #120, #219 et al) we should look into this
