### ISSUE TITLE
Adding implementation of PulseSMS to Franz

### ISSUE THREAD

**Issue by janakjobanputra** [meetfranz/franz#64]
### Feature Description
I use PulseSMS to text from my computer for my android phone, and they use a website to connect to the account, just like Facebook Messenger and WhatsApp. I would appreciate it if Franz could connect up to PulseSMS as well.

### Motivation and Context
I assume I am not the only person who uses PulseSMS on android, and it should be pretty simple, as all it requires is another webview implementation.
This would help people who use androids text from the computer a lot more and experience the benefit that only iOS has enjoyed until now.

### Mockups, Screenshots (if available):
The github for PulseSMS is at https://github.com/klinker-apps/messenger-issues
and the messenger implementation for PulseSMS is located at https://messenger.klinkerapps.com/

Thanks.

**Comment by adlk** [comment]
This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
