### ISSUE TITLE
Autospacing in Japanese words when sending an e-mail 

### ISSUE THREAD

**Issue by bringonthenois** [meetfranz/franz#641]
### Expected Behavior

No automatic spacing between Japanese characters when sending out any e-mails via Franz
### Current Behavior

After writing an e-mail and hitting the send button, the sent e-mail will be reformatted with spacings between Japanese characters, not intended. Below is a visual exmaple

"Thi s is what happ ens when I 'm se nding an e-mai l i n Japanese."

### Context

Sending out e-mails with hard to read context means that the e-mail function in Franz, for Japanese users is not very useful. We want to write e-mails that are clean and easy to read.

### Your Environment

* Franz Version used: 5.0.0-beat.14
* Operating System and version: macOS Sierra Version 10.12.6

* It did happen with previous versions of Franz too.

**Comment by bringonthenois** [comment]
@haraldox I use both "Gmail" and "Inbox by Gmail" and the same thing happens.

Interestingly, when I use google calendar from Franz to send an invite, the issue doesn't seem to happen.

**Comment by knaoe** [comment]
Me too. I think that this issue occurs not only in e-mail but also in Slack, Messenger, etc. Sometimes it is necessary to press many delete keys when deleting characters. 

### Environment
Franz Version used: 5.0.0-beat.14 - 5.0.0-beat.15
Operating System and version: macOS High Sierra Version 10.13.1
It didn't happen with Franz 4.

**Comment by koma-private** [comment]
@bringonthenois @knaoe
Is the trouble similar to this issue? https://github.com/meetfranz/franz/issues/409

Besides, could you paste screenshots here if possible?

**Comment by knaoe** [comment]
@koma-private I think this issue is the same as #409 to me.
And it is Electron's issue https://github.com/electron/electron/issues/9173 according to the conversation.

**Comment by koma-private** [comment]
@knaoe Then we can only wait for electron's fixing IME issues, or use ESC instead of BS or DEL when cancelling IME mode in Franz.
@bringonthenois 
You said this issue also happened with previous versions of Franz (I guess you mean Franz 4). So I think https://github.com/meetfranz/franz/issues/409 might not be the root cause in your case.
Could you describe your env more specifically and paste screenshots of error here if you don't mind?
