### ISSUE TITLE
Franz 5.0 beta15 on Elementary OS starts, but does not restore after close

### ISSUE THREAD

**Issue by dominikzogg** [meetfranz/franz#642]
### Expected Behavior

I would expect, that Franz supports a click an close and resume the instance if i click to the icon on dock. (as in franz 4)

### Current Behavior

Start works, but resume after click on [x] within window does not restore the app, so i have to kill all related processes.

### Steps to Reproduce (for bugs)
1. Start Franz
2. Click on [x]
3. Try to resume (click on Icon in Dock)
4. Nothing happens

### Your Environment
* Franz Version used: 5.0 beta15
* Operating System and version: Elementary OS 0.4

**Comment by isaiasneto** [comment]
+1

**Comment by closingin** [comment]
I cannot reproduce your bug on Arch Linux, and looking at the behavior in [Tray.js](https://github.com/meetfranz/franz/blob/develop/src/lib/Tray.js) (L34-36), there is no way it would not work. I think this issue is related to elementaryOS directly.

**Comment by rubensa** [comment]
See: https://github.com/meetfranz/franz/issues/786#issuecomment-438227456
