### ISSUE TITLE
Clicking on the toast notification changes the window's state

### ISSUE THREAD

**Issue by closingin** [meetfranz/franz#645]
Bug introduced by [b82bbc8](https://github.com/meetfranz/franz/commit/b82bbc8#diff-89d547414f86210ce4395d653f1029c9R172) related to [#370](https://github.com/meetfranz/franz/issues/370) in 5.0.0-beta15 release.

### Expected Behavior
Keep the original state of the window when clicking on a notification.

### Current Behavior
- Opens Franz window and closes it immediately
- Restores its state if it was maximized

### Possible Solution
```js
// Old
mainWindow.restore();

// New
if (mainWindow.isMaximized()) {
    mainWindow.show();
} else {
    mainWindow.restore();
}
```
The above solution would fix the state bug, but as clicking on the notification actually closes the window without focusing it (at least on Gnome), focusing in both cases might be better (but I don't use Electron, it's just based on the docs):
```js
if (!mainWindow.isMaximized()) {
    mainWindow.restore();
}
mainWindow.show();
```
Or maybe just simply this would work in every cases:
```js
mainWindow.show();
```

### Steps to Reproduce (for bugs)
1. Open Franz
2. Maximize the window
3. Switch to another window
4. Receive a notification
5. Click on it

### Your Environment
* Franz Version used: 5.0.0-beta15
* Operating System and version: Arch Linux, 4.14.15-1
* Desktop environment: Gnome 3.26.2

**Comment by corradopetrelli** [comment]
I have the same problem with:
- Franz 5.0.0-beta15
- OS: Windows 10

**Comment by haraldox** [comment]
@closingin great work investigating this issue! would you be open to creating a pull request for this fix, so we can appropriately review the change?

**Comment by closingin** [comment]
There it is.

**Comment by closingin** [comment]
@mkarst20 This PR has already been merged, you can test it by using the latest Franz version.
