### ISSUE TITLE
When do we get a RPM package for Redhat Linux and SUSE Linux?

### ISSUE THREAD

**Issue by thomasmerz** [meetfranz/franz#647]
There are only DEB and AppImage Packages available, but those don't work on Redhat or SUSE :-(

**Comment by amcfillin** [comment]
Appimage worked fine on Fedora 27 for me. Just made it executable and ran it as per https://fedoraproject.org/wiki/AppImage

**Comment by rainerklier** [comment]
i found a repository  with latest franz package for opensuse:
http://download.opensuse.org/repositories/home:/Knurpht:/Extras/openSUSE_Tumbleweed

**Comment by MatthewBooth** [comment]
AppImage should work on all Linux distributions.

**Comment by thomasmerz** [comment]
@rainerklier - doesn't work on openSUSE Leap 42.3 with latest maintenance:
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  franz libappindicator1 libdbusmenu-gtk4 libindicator7

4 new packages to install.
Overall download size: 45,4 MiB. Already cached: 0 B. After the operation, additional 45,6 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package libdbusmenu-gtk4-16.04.0-3.3.x86_64                                                                                         (1/4),  48,0 KiB (148,5 KiB unpacked)
Retrieving: libdbusmenu-gtk4-16.04.0-3.3.x86_64.rpm ..........................................................................................................................[done]
Retrieving package libindicator7-12.10.2+bzr20151208-3.3.x86_64                                                                                (2/4),  34,4 KiB ( 94,5 KiB unpacked)
Retrieving: libindicator7-12.10.2+bzr20151208-3.3.x86_64.rpm .................................................................................................................[done]
Retrieving package libappindicator1-12.10.1+bzr20141110-7.3.x86_64                                                                             (3/4),  30,2 KiB ( 84,6 KiB unpacked)
Retrieving: libappindicator1-12.10.1+bzr20141110-7.3.x86_64.rpm ..............................................................................................................[done]
Retrieving package franz-5.0.0-16.1.x86_64                                                                                                     (4/4),  45,3 MiB ( 45,2 MiB unpacked)
franz-5.0.0-16.1.x86_64.rpm:
    Header V3 DSA/SHA1 Signature, key ID cdd3fc34: NOKEY
    V3 DSA/SHA1 Signature, key ID cdd3fc34: NOKEY

franz-5.0.0-16.1.x86_64 (Plain RPM files cache): Signature verification failed [4-Signatures public key is not available]
Abort, retry, ignore? [a/r/i] (a): i
Checking for file conflicts: .................................................................................................................................................[done]
(1/4) Installing: libdbusmenu-gtk4-16.04.0-3.3.x86_64 ........................................................................................................................[done]
(2/4) Installing: libindicator7-12.10.2+bzr20151208-3.3.x86_64 ...............................................................................................................[done]
(3/4) Installing: libappindicator1-12.10.1+bzr20141110-7.3.x86_64 ............................................................................................................[done]
(4/4) Installing: franz-5.0.0-16.1.x86_64 ....................................................................................................................................[done]
Additional rpm output:
warning: /var/cache/zypper/RPMS/franz-5.0.0-16.1.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID cdd3fc34: NOKEY
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chmod: cannot access '/usr/share/icons/hicolor/1024x1024': No such file or directory
chmod: cannot access '/usr/share/icons/hicolor/1024x1024/*': No such file or directory
sed: can't read /usr/share/applications/franz.desktop: No such file or directory
warning: %post(franz-5.0.0-16.1.x86_64) scriptlet failed, exit status 2

**Comment by rainerklier** [comment]
it seems that latest version of franz package in this repo has some issues...
i tried to update with this repo and it also didn't work.
i think it is the file /opt/Franz/data.tar.xz which is the only file in this package.
it seems to be a .xz archive, but in fact is a debian package.
so i created an rpm package myself using this debian package with the help of alien.
and this works for me.
you can download this rpm here:
https://mega.nz/#!TAoHRTKJ!PA2kRdViiUhCRq0kOKSSSEdeUYp5jyjaghlVTwlTQL4

**Comment by robert-zaremba** [comment]
If you already have DEB builds, then adding RPM should be fairly easy.

**Comment by ofalk** [comment]
I have some basic spec ready, but it needs some more love:
```
%define gitrel beta.18
Name:           franz
Version:        5.0.0
Release:        %{gitrel}.1%{?dist}
Summary:        Messaging app for a variety of services.

Group:          Applications/Internet
License:        Apache License 2.0
URL:            https://meetfranz.com/
Source0:        https://github.com/meetfranz/franz/archive/v%{version}-%{gitrel}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  yarn
BuildRequires:  nodejs > 6.0

%description
Messaging app for WhatsApp, Slack, Telegram, HipChat, Hangouts and many many more.

%prep
%setup -q -n %{name}-%{version}-%{gitrel}

%build
yarn
yarn build

%install
rm -rf $RPM_BUILD_ROOT
install -m755 -d $RPM_BUILD_ROOT%{_bindir}
install -m755 out/franz-%{version}-%{gitrel}-%{_arch}.AppImage $RPM_BUILD_ROOT%{_bindir}/franz

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{_bindir}/franz
%doc CHANGELOG.md CONTRIBUTING.md CODE_OF_CONDUCT.md LICENSE README.md docs/

%changelog
* Tue Nov 13 2018 Oliver Falk <oliver@linux-kernel.at> 5.0.0-beta.18-1
- Initial version
```

Of course, I'm willing to help getting this done for Fedora/RHEL. Just ping me.

**Comment by suntorytimed** [comment]
I think I just found a project for the next Hackweek ;)

**Comment by BjoernDaase** [comment]
> Fedora user. I'd also like this. Tried to convert the deb package with Alien but didn't work.

I have a perfectly working franz on Fedora 30. I used alien to convert the deb package to  rpm package an there where no problems.

**Comment by Alexvianet** [comment]
use in for rpm base https://flathub.org/apps/search/franz

**Comment by maitra** [comment]
> I have some basic spec ready, but it needs some more love:
> 
> ```
> %define gitrel beta.18
> Name:           franz
> Version:        5.0.0
> Release:        %{gitrel}.1%{?dist}
> Summary:        Messaging app for a variety of services.
> 
> Group:          Applications/Internet
> License:        Apache License 2.0
> URL:            https://meetfranz.com/
> Source0:        https://github.com/meetfranz/franz/archive/v%{version}-%{gitrel}.tar.gz
> BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
> BuildRequires:  yarn
> BuildRequires:  nodejs > 6.0
> 
> %description
> Messaging app for WhatsApp, Slack, Telegram, HipChat, Hangouts and many many more.
> 
> %prep
> %setup -q -n %{name}-%{version}-%{gitrel}
> 
> %build
> yarn
> yarn build
> 
> %install
> rm -rf $RPM_BUILD_ROOT
> install -m755 -d $RPM_BUILD_ROOT%{_bindir}
> install -m755 out/franz-%{version}-%{gitrel}-%{_arch}.AppImage $RPM_BUILD_ROOT%{_bindir}/franz
> 
> %clean
> rm -rf $RPM_BUILD_ROOT
> 
> %files
> %defattr(-,root,root,-)
> %{_bindir}/franz
> %doc CHANGELOG.md CONTRIBUTING.md CODE_OF_CONDUCT.md LICENSE README.md docs/
> 
> %changelog
> * Tue Nov 13 2018 Oliver Falk <oliver@linux-kernel.at> 5.0.0-beta.18-1
> - Initial version
> ```
> 
> Of course, I'm willing to help getting this done for Fedora/RHEL. Just ping me.
Did this make any progress? Thanks!

**Comment by ofalk** [comment]
Not from my side, I'm afraid. But I see there is a flatpak available on Fedora. Does that help?

**Comment by thomasmerz** [comment]
I don't use Franz anymore for a while. So it's not an issue for me anymore. Therefore I will close this issue as last update is also very long ago...

**Comment by ofalk** [comment]
Same here.
