### ISSUE TITLE
Franz functionality - nothing is working out of the sudden

### ISSUE THREAD

**Issue by barintsights** [meetfranz/franz#648]
I've restarted my machine, and right after the boot, when entering franz app, i couldn't see none of my previous platforms, and when i'm trying to add some, i get an loading which don't do anything.
please follow the attached video (zip)

tried to 
```
sudo apt remove --purge franz
```

and then reinstall through the dpkg. none worked

### Expected Behavior
That when franz is up and runnin, that i see my whole environment and apps.

### Current Behavior
When opening the application, all the applications i had before are missing (Whatsapp, slack, etc..)

### Video (if appropriate):
[out.ogv.zip](https://github.com/meetfranz/franz/files/1693043/out.ogv.zip)

### Steps to Reproduce (for bugs)
1. enter franz
2. open terminal
3. sudo reboot

### Your Environment
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Franz -
Version: 5.0.0-beta.15
Release: 1.7.9 / linux / x64

**Comment by haraldox** [comment]
@barintsights did you get it working in the meantime by any chance?

**Comment by barintsights** [comment]
@haraldox not yet.. still pristine view, without the ability to add applications

**Comment by barintsights** [comment]
Workaround is deleting Franz folder from home directory
```bash
sudo apt remove --purge franz
rm -rf ~/.config/Franz
```

Still weird bug. closing issue
