### ISSUE TITLE
Invite friends error

### ISSUE THREAD

**Issue by mounlion** [meetfranz/franz#649]
Mac
input value [Object object] and never change
<img width="803" alt="2018-02-05 14 08 18" src="https://user-images.githubusercontent.com/17071211/35801640-25033224-0a7e-11e8-8ed7-21d2a2aed9b8.png">

**Comment by raduchiriac** [comment]
I can confirm this. I just saw it in `Version 5.0.0-beta.15`

**Comment by haraldox** [comment]
@mounlion thanks for letting us know, this is a known issue in beta-15

@raduchiriac thanks for offering, but this is already fixed and will be released soon ... you may help us with other issues though, if you're interested 😉
