### ISSUE TITLE
External link doesn't works for each application

### ISSUE THREAD

**Issue by StephaneLa** [meetfranz/franz#651]
Gmail, slack, ... 
When I click on a link, my browser opens but the link does not run.

### Current Behavior

When I click on a link, my browser opens but the link does not run. It should opens... 

I emptied the cache, restarted and updated but it does not solve the problem

### Steps to Reproduce (for bugs)

1. Clic on a link in GMAIL in Franz
2. It does not opens the link, but it opens my browser on default page (google). 

### Your Environment

* Franz Version used: I tried the last version (without beta) then the last beta. Now i use 5.0.0-beta.15 
* Operating System and version:
MacOS High Sierra Version 10.13.2
Google Chrome last version.

**Comment by corradopetrelli** [comment]
I haven't this problem with the same version of Franz and Chrome (but I have Windows 10).

**Comment by StephaneLa** [comment]
Thx for your return corradopetrelli. 

I have a friend who use Franz (same system : franz, chrome, macos...) and he haven't this problem neither.... 

I verified the configuration of Franz, but I don't find option which help me

**Comment by haraldox** [comment]
@StephaneLa please use this super-issue to comment #577 ... have you tried right-clicking on the link and choosing "Open Link"?

**Comment by WillyReyno** [comment]
I'm having the same issue ! 

MacOS High Sierra Version 10.13.2
Franz 5.0.0-beta.14.451
Chrome 64.0.3282.119

Whenever I open a link by clicking or via "open file" a new chrome instance starts and closed right after. Then a new empty tab appears in my current instance of Chrome.

![franzbug](https://user-images.githubusercontent.com/5576482/35923564-e74734ea-0c20-11e8-88ab-cb6b6b4585a6.gif)

**Comment by haraldox** [comment]
@WillyReyno thanks for the gif, interesting behavior indeed as i haven't seen that one before! please try the latest beta.15 of Franz 5 to see if you are experiencing the same issue. may I ask what URLs you are trying to load and where you see "open file"?

**Comment by haraldox** [comment]
closing this for now, please use the super-issue #577 to comment
