### ISSUE TITLE
signal & wire service integration

### ISSUE THREAD

**Issue by larissaales** [meetfranz/franz#655]
Hey everybody!

I really would appreciate if there would be the services signal and wire integrated in franz. I saw the guide to create the own service integration, but i couldn't do it, because i don't know from where to download the integration folder.
Greetings

**Comment by haraldox** [comment]
This repository is for the Franz client only. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by TCB13** [comment]
+1 on Signal!

**Comment by krauthaufen** [comment]
Shouldn't signal be fairly easy to integrate, since it also uses electron on windows/etc?
Would make Franz incredibly more useful for lots of people.
Cheers
