### ISSUE TITLE
Can't re-open Franz, missing menubar icon.

### ISSUE THREAD

**Issue by NohaTech** [meetfranz/franz#656]
I'm running meet franz 5.0.0 -15beta and When I close it I need to login and out from my Ubuntu desktop to open it again.
It don't have any menubar icon either - this is annoying as if I close the window I need to out and in again.

**Comment by haraldox** [comment]
Can you please update your initial issue with all the necessary information like macOS version, exact Franz version and so on. Please use this [template](https://raw.githubusercontent.com/meetfranz/franz/v5.0.0-beta.14/.github/ISSUE_TEMPLATE.md), it makes tracking and reproducing issues much easier.

**Comment by rubensa** [comment]
See: https://github.com/meetfranz/franz/issues/786#issuecomment-438227456
