### ISSUE TITLE
Messenger shows notification badge for muted threads

### ISSUE THREAD

**Issue by wardcraigj** [meetfranz/franz#658]
The Messenger component shows the notification badge for messages in muted threads, unlike the behaviour of the badge in the favicon in the web app. As a user with very active muted threads throughout the day, this causes me to check messages I would normally ignore

### Expected Behavior
Muted Messenger threads should not increment the unread message badge

### Current Behavior
Muted threads increment the unread message badge

### Steps to Reproduce (for bugs)
1. Mute a thread in Messenger
2. Have someone send you a message
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by KhaVNguyen** [comment]
Having this issue as well. Only way I could get rid of it was to completely Hide the group chat to not show the badge number. Any other ideas?
