### ISSUE TITLE
New Icon for Mac to Differentiate App

### ISSUE THREAD

**Issue by lorenzolewis** [meetfranz/franz#659]
Would it be possible to have an alternative icon for the Mac app? Or the option to change the icon? I have about 50% of my apps in my dock that look like blue circles right now and Franz blends in with them all a little too well.

Maybe just an option to change the icon in the settings to one with a different background color (such as red, yellow, green, etc.)

**Comment by haraldox** [comment]
The Franz logo and brand are carefully crafted and trademarked, and the chosen blue color is integral part of it, so unfortunately we must decline your request.

but hint, hint: all i'm saying is `.icns` for any `.app`
