### ISSUE TITLE
Can't use command of copy and paste

### ISSUE THREAD

**Issue by liencode** [meetfranz/franz#660]
### Expected Behavior
If I used ⌘+C, selected text copied.

### Current Behavior
If I used ⌘+C, selected text dosen't copied.

### Your Environment
* Franz Version used: 5.0.0
* Operating System and version: Mac OSX 10.11.6

**Comment by jacoblo** [comment]
Same problem here. Very annoying and think it worked before.

**Comment by OArnarsson** [comment]
Possible duplicate of https://github.com/meetfranz/franz/issues/33?

**Comment by jacoblo** [comment]
@OArnarsson Running beta.15, beta versions (obviously) enabled and tried restarting multiple times :(

**Comment by haraldox** [comment]
Duplicate of #33

**Comment by Joejoboi** [comment]
Can we open this one back up? It appears to still be a challenge.
