### ISSUE TITLE
Add Flatpak support

### ISSUE THREAD

**Issue by Wetrain** [meetfranz/franz#661]
### Feature Description

I would to see Franz be packaged into a [Flatpak](https://flatpak.org/) and also be hosted on [Flathub](https://flathub.org/apps/)

This is a duplicate of #432, but using the correct feature request template :)

### Motivation and Context

This change will make the installation process on Linux a lot easier for distros that support Flatpak out of the box, such as Fedora, Arch.

This makes installing/Updating Franz a lot less painful for users.

Using Flatpak solves the issue of cross-platform linux support.

**Comment by haraldox** [comment]
@Wetrain The feature request template is only for Franz features, not for services. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by haraldox** [comment]
interesting proposal, as we welcome every option to make dealing with Linux easier :)

will keep that in mind, should demand arise! thanks for your submission

**Comment by focom** [comment]
Yeah flatpak would be awesome

**Comment by salaros** [comment]
+1

**Comment by bvdlingen** [comment]
+1

**Comment by Fabianoshz** [comment]
+1

**Comment by Daemoen** [comment]
:+1:

Sad that this isn't seeing any life.  AppImage has some nice features, but for people that do any automation of workstation provisioning, it is very lacking.  You wind up having to hardcode versions or links, pull in the asset, ensure that it is binary executable.... and manage the versions carefully.

**Comment by mairin** [comment]
Please make a Flatpak available :)

**Comment by klemy** [comment]
A Flatpak would be awesome! Please!

**Comment by johnvanhienen** [comment]
Would love to see a Flatpak version for similar reasons Daemoen mentioned above.

**Comment by bsucker98** [comment]
Yep, would be lot easier to deal with

**Comment by closingin** [comment]
I think the request has been understood.

But keep in mind that Franz is currently maintained by only one developer if I'm not wrong (alongside me and other contributors). It takes a lot of time to handle all those issues, especially when the development had stalled for a long time as he was sick. :slightly_smiling_face:

**Comment by bsucker98** [comment]
ah! understandable, sorry my apologies

**Comment by Daemoen** [comment]
Don't think this ticket really should be closed...  Especially since it does still gain traction.  If anything, I would have it listed as feature request/open....

**Comment by lucianoshl** [comment]
+1

**Comment by vladox** [comment]
would you accept a pull request for this?

**Comment by tallysmartins** [comment]
Up!

**Comment by closingin** [comment]
> would you accept a pull request for this?

Hi @vladox , if you have a PR to create, do so 🙂

**Comment by klemy** [comment]
Hello, what's going on here? I'm on Fedora 30 Silverblue and I sadly can not install the app... It would be truly awesome to have it on Flathub!

**Comment by tpopela** [comment]
@klemy Someone already put it there - https://flathub.org/apps/details/com.meetfranz.Franz
