### ISSUE TITLE
Main window blinking

### ISSUE THREAD

**Issue by bajzarpa** [meetfranz/franz#662]
When you switching between services with cmd+number and accidentally press two or more number together the main window starts blinking and switching between them randomly. 

### Expected Behavior
Just simply switch to the window by the last number key

### Current Behavior
The window starts blinking (switching between services) and you're unable to use the software til you restart it.

### Steps to Reproduce (for bugs)
1. Open Franz
2. Press cmd + 2 + 3 at the same time (sometimes need one more)

### Your Environment
* Franz Version used: Version 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: macOS High Sierra Version 10.13.3

**Comment by haraldox** [comment]
@bajzarpa very creative bug, i'd say 😆easy to reproduce, hard to debug! there's a similar behavior i witnessed without the shortcut too (random switching between webviews), but it's very rare and occurred only 2 times until now, but might be related to that issue... i'm guessing a loop run amok?

one for the backlog!

**Comment by haraldox** [comment]
Duplicate of #625
