### ISSUE TITLE
Google Services as Topbar

### ISSUE THREAD

**Issue by manthena** [meetfranz/franz#665]
Is there a plan to enable additional Google Services (Calendar, Drive, Contacts, Photos) in a top bar for Google accounts?

Other similar products ([Wavebox](https://wavebox.io/), [Shift](https://tryshift.com/)) has this topbar, which is very useful for quickly switching between various Google services, without having the need to go to an external browser and sign in again.

Please consider this feature request!

![image](https://user-images.githubusercontent.com/5641470/35931511-d2dfa384-0c02-11e8-8ca9-a8c9ecb26a07.png)

![image](https://user-images.githubusercontent.com/5641470/35931534-e31ad19c-0c02-11e8-80d1-a03fcc20b37c.png)

**Comment by haraldox** [comment]
@manthena Vivaldi Browser does this too as does Kiwi for G-Suite (kind of). No plans yet to copy this feature, though ... but certainly interesting!
