### ISSUE TITLE
Notifications on Mac not working for Messenger

### ISSUE THREAD

**Issue by garyrob** [meetfranz/franz#666]
When I turn on Notifications in the Messenger app, and receive a new message, I expect to see a Notification appear in the upper right of my Mac's screen.

I don't see the aforementioned Notification. Also, Franz doesn't show up in the Notifications preference pane in System Preferences. As you know, that preference pane enables you to set the type of notification to enable for each notification-supplying app. 

I will note that all this is the case in the 30 minutes after first installing and running Franz. If behavior changes over time or after rebooting, I'll update this issue.

### Your Environment

* Franz Version used: (5.0.0-beta.15.607)
* Operating System and version: macOS version 10.12.6

**Comment by garyrob** [comment]
Update: A couple hours later, Franz IS showing up in the Notifications Preference Pane. No restart was required. So, there is a problem: why does it take so long for Franz to show up? Is there something that can be done to make that happen more quickly? I had waited 30 min and was mystified; users shouldn't have to have that experience.

Note, in the interim, I did click on the Notifications option in Franz, and click twice to turn "Receive Notifications For Reactions" off and on again; that might have had an effect.

**Comment by haraldox** [comment]
@garyrob thanks for bringing this to our attention! we'll look into that...

**Comment by JanuszCh** [comment]
I am using Messenger and Slack. Except for sound notification when I got a message on Messenger I don't have any notifications (upper right corner, an icon in Dock etc).

Franz 5.0.0-beta 15
macOS 10.13.3

**Comment by AlexanderKvamme** [comment]
No notifications from facebook messenger anywhere. Pretty much the only reason why I decided to try it out :P

**Comment by lovecastle** [comment]
same with me, messenger rarely show notifications. 
Running Mac 10.13.6
Franz Version 5.0.0-beta.19.1004

**Comment by TK42DAN** [comment]
I'm signed in with gmail, two google apps accounts, and an Outlook email account and I get a red dot on the menubar icon, but no sounds or notifications on the screen or in the notification center.

**Comment by avnosov** [comment]
Same problem
MacOS 10.14.4
Franz 5.0.1.1237

**Comment by VincentVanDenBossche** [comment]
Same problem
