### ISSUE TITLE
Hello from The Lounge 👋

### ISSUE THREAD

**Issue by astorije** [meetfranz/franz#667]
Hey there!

Thanks for offering [The Lounge](https://github.com/thelounge) as part of Franz, that's awesome! I had a few thoughts, figured a GitHub issue would be the best way to keep track of them:

- [ ] Would you mind add the [GitHub topic `thelounge`](https://github.com/topics/thelounge) to this repo? 🙂

- [ ] Franz will be featured [in our new docs](https://amazing-easley-fa1e6d.netlify.com/docs/install-and-upgrade.html#services-packaging-the-lounge) (coming up with The Lounge v3) 🎉 Does this logo work for you? I have used [this one](https://github.com/meetfranz/franz/blob/master/build-helpers/images/icon.png), not sure if you prefer me to use a borderless version but that's the only one I found on this repo.

- [ ] Speaking of logo, we have an official one now. Could you use it in your [list of services](https://meetfranz.com/services/)? I'm thinking [this one](https://github.com/thelounge/thelounge.github.io/blob/astorije/logos/assets/logos/logo/TL_Grey%26Yellow_Logo_Transparent_Bg/TL_Grey%26Yellow_Logo_Transparent_Bg.svg) is probably the most appropriate to the format/colors of your website, but you can find all variants and brand guidelines [here](https://github.com/thelounge/thelounge.github.io/tree/astorije/logos/assets).

Let me know if you have any questions!

**Comment by haraldox** [comment]
hey @astorije!

thanks for the warm welcome, i'm sure we can fit that into one of our next releases... :)

more to come soon, stay tuned ;)

**Comment by haraldox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The Lounge welcome package](https://trello.com/c/aa9sBupY/7-the-lounge-welcome-package)

**Comment by astorije** [comment]
Hey @haraldox, thanks for your answer!
The first 2 points are not tied to a release on your part, but I understand the last one does. Let me know what you think.

**Comment by haraldox** [comment]
let's take this to slack: https://meetfranz.slack.com

**Comment by astorije** [comment]
Hey @haraldox, sorry but I'll politely decline, I am not going to be able to do that :)
I'll assume that the logo I used is okay by you (unless you tell me otherwise). Just make sure to use our official logo in your next release (I can help with format if you need), and if you can add [the `thelounge` GitHub topic](https://github.com/topics/thelounge), that'd be lovely 🙏

Thanks!

**Comment by xPaw** [comment]
@haraldox Slack aside, could you please update the logo on the Franz site please?
