### ISSUE TITLE
Button for login into Harvest using Power-Ups

### ISSUE THREAD

**Issue by Alexmanguinho** [meetfranz/franz#669]
The button to login into Harvest using Power-Ups is not working. When I try to click on it to login, Franz doesn't redirect to any place and I can't make the login. Is there any issue related to this problem already? It would be very good if this issue could be solved.
![harvestproblem](https://user-images.githubusercontent.com/36278841/35994736-7fe4d4fa-0cf8-11e8-97dd-06bfe1c560a1.png)

**Comment by haraldox** [comment]
@Alexmanguinho this one's hard to achieve in Franz itself, as i've had the problem myself. we would need to open a new window for the sign-in with Harvest and then return the token to Trello. Right now you are being redirected to the browser for external links 😕 

we're still investigating how to handle external links best: #577
