### ISSUE TITLE
Can't log in to my account

### ISSUE THREAD

**Issue by Santiael** [meetfranz/franz#67]
### Expected Behavior
Put my authentication requirements and log into my account.

### Current Behavior
Continues to load screen forever.

### Screenshots (if appropriate):
![issue_report_franz](https://user-images.githubusercontent.com/31523464/31869105-1cf7ca90-b77c-11e7-9eed-7193f48a55c4.png)

### Steps to Reproduce (for bugs)
1. Already have a verified account
2. Enter email and password 
3. Click to Sign In

### Your Environment

* Franz Version used: 5.0.0
* Operating System and version: Windows 10 Pro, 10.0.15063 Build 15063

**Comment by adlk** [comment]
@Santiael thanks for reporting this issue. Can you please restart Franz, open the dev tools `strg+shift+alt+i`, select the _console_ tab, try to login and paste the log here? If you don't feel comfortable posting the log here in public you can send the log dump to stefan@adlk.io 

Thank you!

**Comment by Santiael** [comment]
api\server\ServerApi.js:457 Recipe 'whatsapp' not installed, trying to fetch from server
_prepareServiceModel @ api\server\ServerApi.js:457
Promise.all.services.map @ api\server\ServerApi.js:447
_mapServiceModels @ api\server\ServerApi.js:447
getServices @ api\server\ServerApi.js:138

**Comment by Santiael** [comment]
api\server\ServerApi.js:457 Recipe 'gmailinbox' not installed, trying to fetch from server
_prepareServiceModel @ api\server\ServerApi.js:457
api\server\ServerApi.js:457 Recipe 'whatsapp' not installed, trying to fetch from server
_prepareServiceModel @ api\server\ServerApi.js:457
api\server\ServerApi.js:457 Recipe 'telegram' not installed, trying to fetch from server
_prepareServiceModel @ api\server\ServerApi.js:457

**Comment by PhriZ** [comment]
same problem here.

**Comment by adlk** [comment]
I've been able to pinpoint the issue but wasn't able to provide a proper fix yet.
If you are stuck on the landing screen, go to your recipe folder:
- Mac: `~Library/Application Support/Franz/recipes/temp`
- Windows: `%appdata%/Franz/recipes/temp`
and delete all folders in there. Restart Franz and it should work. If not, please repeat at least once more.

If you can't delete a folder (especially on windows) a system restart usually helps.

**Comment by adlk** [comment]
I have published a new version (beta 11) which should resolve this issue.
