### ISSUE TITLE
Hipchat doesn't stay logged in.

### ISSUE THREAD

**Issue by llovelock** [meetfranz/franz#679]
### Expected Behavior
Hipchat should remain logged in much like every other service.

### Current Behavior
Upon quitting and re-opening Franz, Hipchat is logged out, and credentials are forgotten every time.

### Your Environment
* Franz Version used: 5.0.0-beta. 14.451
* Operating System and version: Mac OSX 10.13

**Comment by haraldox** [comment]
Duplicate of #113
