### ISSUE TITLE
WeChat Missing from 5.0 Beta

### ISSUE THREAD

**Issue by billmccord** [meetfranz/franz#68]
I just installed the 5.0 Beta and there doesn't appear to be a WeChat service, but this service was available in 4.x of Franz.

**Comment by adlk** [comment]
The service will be re-added soon.

---

Please keep in mind that this repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.
