### ISSUE TITLE
Server not working? 

### ISSUE THREAD

**Issue by SergioSuarezDev** [meetfranz/franz#680]
Server not working, can't login to Franz.

* Franz Version used: 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: MacOS High Sierra 

![captura de pantalla 2018-02-13 a las 13 22 17](https://user-images.githubusercontent.com/3636232/36149683-f8b62a84-10c0-11e8-95c7-064adff13328.png)
![captura de pantalla 2018-02-13 a las 13 22 09](https://user-images.githubusercontent.com/3636232/36149684-f8d46bac-10c0-11e8-9f56-5c2680558fc9.png)

**Comment by Brun0urs** [comment]
Looks I have the same issue right now :(

**Comment by rkunschke** [comment]
I can confirm it. Same for me on Arch Linux.
Version: 5.0.0-beta.15

**Comment by iCodyRo** [comment]
Same problem for me.

**Comment by chucksense** [comment]
Same on macOS `10.13.3` running Franz `5.0.0-beta.14.451`.

**Comment by Loewe1000** [comment]
Same Problem here

**Comment by haraldox** [comment]
technical server problems! we're on it, please stand by...

**Comment by iCodyRo** [comment]
Works now.

**Comment by haraldox** [comment]
aaaaaaaaaand we're back to normal! :)
