### ISSUE TITLE
Draw taskbar badge with a canvas instead of using an image

### ISSUE THREAD

**Issue by Stanzilla** [meetfranz/franz#682]
This should make them less problematic when scaling and also probably a better idea than shipping numbered icons.

See https://github.com/saenzramiro/rambox/blob/3674116d500c92092bc96623a0d0ffe5053095b5/app.js#L76

**Comment by haraldox** [comment]
@Stanzilla good idea, would you be open to make a PR for this as well?

**Comment by Stanzilla** [comment]
Probably not in the near future :)
