### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Bana0615** [meetfranz/franz#685]
Clicking links opens a new blank tab instead of the link. This is happening on franz, allo, messgenger, hipchat and inbox for sure. This is on mac

**Comment by stnkl** [comment]
Might be related to this: When clicking a gmail notification it opens the window below rather than opening the mail in Franz.

![image](https://user-images.githubusercontent.com/17520641/36251390-5b872efc-1241-11e8-968d-ae3833b2d387.png)

Using 5.0.0-beta.15 on Windows 10.

**Comment by coolbeanscrypto** [comment]
I have same exact problem on both my Macs. Clicking a link in Gmail, Telegram, Slack, Discord and Tweetdeck opens a new blank Chrome window. Very frustrating as it renders Franz basically useless.

**Comment by nealjean** [comment]
Also having this issue on Macbook Pro, links in Ubuntu Franz work fine

**Comment by gerisztein** [comment]
I don't know why but typing chrome://restart on Chrome fixed the issue for me.
Not the ideal approach but it works.

**Comment by bru74** [comment]
Not sure if you've seen the other thread, but updating to latest version of Chrome fixes this.

**Comment by grimm26** [comment]
This only happens for me with Hangouts Chat.  I get a blank window for Franz as well as a window opened in Chrome for the link.  Regular hangoutss, hipchat, slack, etc etc work fine.  I'm on latest Chrome and Franz 5 beta 17
