### ISSUE TITLE
Skype calls icons on Skype are not actionable

### ISSUE THREAD

**Issue by Rossofiorentijno** [meetfranz/franz#686]
In the latest Mac Frantz release (version 5.0 beta 15.607) I added Skp service: now I can chat but can't audio or video call because icons are freezed.
![senza titolo](https://user-images.githubusercontent.com/36483774/36249160-19c1e39c-123a-11e8-8d0c-b45b88d44d32.jpeg)

![senza titolo bis](https://user-images.githubusercontent.com/36483774/36249240-4ff99496-123a-11e8-89ff-e0664b24e7bc.jpeg)

Can you please help?

Thanks

Best regard

**Comment by john-shipp** [comment]
I am experiencing this issue too, same OS as @Rossofiorentijno .

**Comment by flrizzato** [comment]
Same here.

**Comment by foofingers** [comment]
Same problem.
<img width="906" alt="screen shot 2018-03-28 at 12 02 18 am" src="https://user-images.githubusercontent.com/20081485/38009724-5fdfc334-321b-11e8-87d2-1e2202758dd4.png">
<img width="582" alt="screen shot 2018-03-28 at 12 03 30 am" src="https://user-images.githubusercontent.com/20081485/38009788-b294ba80-321b-11e8-94d6-b2e300c7f83a.png">

**Comment by RicardoMadaleno** [comment]
same here!

**Comment by Gektorian** [comment]
same here!
Version: 5.0.0-beta.21
![image](https://user-images.githubusercontent.com/3693219/50527613-1a3bc980-0af2-11e9-80ec-bd51250d67cb.png)

**Comment by closingin** [comment]
Hello,

Can you search for an already existing issue before opening a new one...? This has been asked many times, and Skype calls never worked on Franz, afaik.

#921 and #1133 already talk about this problem anyway, so can you close your issue please ? :slightly_smiling_face:

**Comment by Gektorian** [comment]
hi @closingin,
if you pay more attention you will find out that this ticket was raised on Feb 15 and it still open,
while tickets you mentioned on Apr 22 and on Nov 27, what is much later.
hence please control the level of your speech and before writing check details. thanks in advance and happy holidays!
kind regards.

**Comment by closingin** [comment]
> hi @closingin,
> if you pay more attention you will find out that this ticket was raised on Feb 15 and it still open,
> while tickets you mentioned on Apr 22 and on Nov 27, what is much later.
> hence please control the level of your speech and before writing check details. thanks in advance and happy holidays!
> kind regards.

Hello Oleg, that's my bad, apologies. We're dealing with a lot of issues so I don't spend much time on each of them, but that's not an excuse. I'll be more careful next time ! :slightly_smiling_face: :pray: 

Anyway, this issue doesn't belong to this repository, as it's related to the Skype service. @adlk already opened an issue himself [here](https://github.com/meetfranz/recipe-skype/issues/1), so we can close this one and the others I think ?

Happy holidays !

**Comment by Gektorian** [comment]
Hi @closingin, fully agree with you! Thank you very much for your support!
Happy holidays!
