### ISSUE TITLE
Instagram Direct integration

### ISSUE THREAD

**Issue by ghost** [meetfranz/franz#688]
Instagram Direct integration

Hello,

I would like to suggest to add Instagram Direct on Franz, an option that it is important for a lot of franz users.

Best regards,
Pablo K.

(Franz is awesome!!)

**Comment by closingin** [comment]
From [https://meetfranz.com/support](https://meetfranz.com/support), you can find this [Google Form](https://goo.gl/forms/zbwlx3VFvAo2oink2) for service requests.

**Comment by raynesio** [comment]
Hey both @akspablo @closingin did you manage to get the current instagram plugin for Franz to work in V5?

**Comment by closingin** [comment]
@raynesio I never heard of an Instagram plugin and I wouldn't use it anyway, that's totally unrelated to messaging. And as I said, I think that service requests don't belong here.

If you're looking for an Instagram wrapper you can find one [here](https://github.com/meetfranz/plugins/issues/30), but I don't understand why it should be added to Franz imo.

**Comment by closingin** [comment]
@GevaZeichner There's nothing on Instagram's website that allows you to use the DM feature that exists on their mobile app. So this wouldn't fit.

And anyway, new services have to be requested on the link I sent above.

@haraldox This issue can be closed.

**Comment by GevaZeichner** [comment]
It's not on their website. It's on a 3rd party app: http://igdm.me/
Requested there too.

**Comment by closingin** [comment]
@GevaZeichner But IG:dm is a software, not a web page (as far as I searched) ? Franz works by loading web pages so that wouldn't be possible.

Even if this software provided a web app, it would require you to install it on your desktop, which would mean the service wouldn't work without it. Bad user experience.

**Comment by heisenberg617** [comment]
The IG:dm project is open source, is it possible we could ascertain how they were able to get direct messaging working and somehow make that work? I understand that franz basically loads a website, so I would guess someone would have to create a website that hosts the necessary code for instagram dm and such. There is no way to put a web app into a franz recipe directly is there?

**Comment by heisenberg617** [comment]
I ended up looking around for websites that offer instagram direct messaging. I found postgrain.com which has a free tier. Only caveat is your account has to have 50 followers and 5 media posts. I am not there yet so I can't check their interface. I would surmise it could be integrated with franz.

**Comment by heisenberg617** [comment]
okay, got it to work, but looks like direct messaging is not part of the free tier

**Comment by dstanley83** [comment]
Following up on this - anyone tried to integrate IG:dm project into franz?

**Comment by closingin** [comment]
Hello @dstanley83 ! IG:dm doesn't provide a web interface (it's an electron application), so it's currently not possible to integrate it in Franz.

**Comment by onarbf** [comment]
Then let's dev a web interface for IG:DM! haha

**Comment by Ricki-BumbleDev** [comment]
Since IGDM is an electron app it already *is* a web interface, we'd just need someone to host it somewhere publicly, which, however, probably is against Instagram's TOS.

**Comment by zulumbazoid** [comment]
Did anyone got this to work in the meantime?

**Comment by realdannys** [comment]
I'd be really interested in this - perhaps someone could work out how to do it and then we can host it our selves for our private use? It's the only messaging service I use that I don't have access to on my Mac.

**Comment by closingin** [comment]
Hello @zulumbazoid and @realdannys , if you want to discuss about a feature that is related to IG:dm and not Franz, please don't do it in this repository's issues.

If you want IG:dm to work in Franz, you need this software to expose either a web app or a web server that Franz can use (web server because there's a new premium feature in Franz that allows you to add your own custom recipes directly). Otherwise it's not possible, maybe you can ask them or search for an existing issue in [their repository](https://github.com/ifedapoolarewaju/igdm).

**Comment by elvisbrens** [comment]
Hello, 

I just found this: https://github.com/alexdevero/franz-instagram-recipe

Seems to work under the recipe/dev folder 
I'm new to this. Is this safe to add?

**Comment by realdannys** [comment]
@elvisbrens that’s not Instagram DM, it’s just the Insta web interface.

**Comment by elvisbrens** [comment]
@realdannys It also has DM. When you add the service and login, look for the DM icon in the top-right corner.

**Comment by realdannys** [comment]
> @realdannys It also has DM. When you add the service and login, look for the DM icon in the top-right corner.

Ah yes sorry you're right - it appears to load the mobile view of the website. Not sure it's that much use though as you won't get any of the messaging features of Franz...notifications etc, it's basically just like loading up the mobile version of Insta in your browser. It's **something** I guess.

**Comment by MurzNN** [comment]
Instagram Direct chat already works in web version at url https://www.instagram.com/direct/inbox/ if we use user-agent from any mobile browser, eg `Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19 `

So we can easily add Instagram Direct chat, if override user-agent string!

**Comment by realdannys** [comment]
> Instagram Direct chat already works in web version at url https://www.instagram.com/direct/inbox/ if we use user-agent from any mobile browser, eg `Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19 `
> 
> So we can easily add Instagram Direct chat, if override user-agent string!

Perhaps this is the answer - the plugin above seems to access this menu but also the rest of Instagram and defaults to the homepage - it of course just acts as web browser window so you get no notifications, no symbols it has no interface with the chat - so i'm not sure if someone can build upon the mobile link to actually work with Franz features or not.

**Comment by bvrulez** [comment]
> > @realdannys It also has DM. When you add the service and login, look for the DM icon in the top-right corner.
> 
> Ah yes sorry you're right - it appears to load the mobile view of the website. Not sure it's that much use though as you won't get any of the messaging features of Franz...notifications etc, it's basically just like loading up the mobile version of Insta in your browser. It's **something** I guess.

I just wanted to add that an instagram chat would be nice even without any notification. Just to be able to use keyboards.

**Comment by leolelego** [comment]
You can do it yourself!

1) add a Custom Website service, and use the normal instagram.com url (add name, logo etc)
2) open the service and login to instagram
3) kill Franz
4) open `~/Library/Application/ Support/Ferdi/recipes/franz-custom-website/index.js` with a code editor (On Mac, will be different on Windows)
4) make it looks like this

```js
"use strict";

module.exports = Franz => class CustomWebsite extends Franz {
  overrideUserAgent() {
    return "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1";
}
  async validateUrl(url) {
     return true
  }
};
```

5) open Franz and change the URL of your service to `https://www.instagram.com/direct/inbox` (you cannot do it before editing the `index.js`)

6) close Franz
7) (optional) replace the validateUrl method in the `index.js` by this one

```
  async validateUrl(url) {
    try {
      const resp = await window.fetch(url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        }
      });
      return resp.status.toString().startsWith('2') || resp.status.toString().startsWith('3');
    } catch (err) {
      console.error(err);
    }

    return false;
  }
```

Should work!

**Comment by realdannys** [comment]
Well this is interesting - maybe we can get proper support now?

https://www.macrumors.com/2020/01/14/instagram-dms-coming-to-web/
