### ISSUE TITLE
Autostart and stay in background won't stay turned off

### ISSUE THREAD

**Issue by N8falter** [meetfranz/franz#689]
Everytime I launch Franz it turns the Autostart setting on again.

No matter if disabled in Franz' settings page or in Taskmanager directly, next time you run it it's activated again. Same thing with the "stay in background" setting. I want Franz to be closed when I click on close, but it just minimizes. I change the setting, close it, open it again and it's on again.

**Comment by hmm1050** [comment]
I am having a similar issue, I have turned off the "Launch Franz on start" feature but every time I restart Franz the "Launch Franz on start" feature turns back on.

**Comment by closingin** [comment]
Could you provide more information please ? When you open an issue, there is already a template you have to fill, designed to help developers to reproduce your bug. Franz version used and operating system at least.

**Comment by varunyellina** [comment]
Irrespective of how I remove Franz from startup i.e,

1. Preferences(Cmd + .) > General > Launch Franz on Start
2. System Preferences > Users & Groups > Login Items > Franz(delete)

It always comes back. This setting gets re-enabled automatically.

OS: macOS 10.13.3
Franz Version: 5.0.0-beta-15

**Comment by mgrabow1** [comment]
The same on Ubuntu 17.10 with Gnome 3.26.2 and Franz 5.0.0-beta-15.
No icon in the tray (not even the black one) and therefore no indication of unread messages.

**Comment by N8falter** [comment]
My Franz Version is the latest, and the problem is appearing on ALL operating systems. - was it tested at all?! I'm using it on machines with Windows7, Windows8.1, and Ubuntu 16.04 - same issue on all of them

**Comment by closingin** [comment]
@N8falter As you can see, commits have been merged addressing these issues, so wait for the next release to see if these fix your problem. You can also build franz yourself from the develop branch to check it without waiting.

**Comment by hmm1050** [comment]
@N8falter it appears this may have been fixed in todays update. I tested it twice and it was working correctly.

**Comment by iamtomlindley** [comment]
I also have this issue. Franz automatically launches on boot (macOS 10.13.3 / Franz 5.0.0-beta.16.762). Even if I disable "Launch Franz on start" in settings, every time I reboot my machine it is re-enabled.

Interestingly, it adds a new instance to User/Login Items too.

**Comment by haraldox** [comment]
This is addressed in the latest release 5.0.0-beta.16
