### ISSUE TITLE
click on notification link doesn't open franz

### ISSUE THREAD

**Issue by tomcat101** [meetfranz/franz#697]
Version 5.0.0 beta 14
When clicking on a new message notification (win 10) nothing happens, to see the message one has to open Franz and actually go to the message.

### Expected Behavior
Prior to this version clicking on notification would bring you straight to the message

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by jwbambacht** [comment]
I can confirm that on MacOs (version 5.0.0-beta.16) this is also not working. Prior versions had the same problem.
