### ISSUE TITLE
Links from Email (Gmail, Outlook) open in own window (Ubuntu)

### ISSUE THREAD

**Issue by MatthewBooth** [meetfranz/franz#698]
When I click links in Gmail or Outlook (via services) they open in a new window with no browser controls, no cookies or previous sign ins.

### Expected Behavior
Clicking links to open OS default browser

### Current Behavior
An isolated window opens up with no browser controls and no cookies. Such that any links opened often require you to re-sign into sites and services.

### Screenshots (if appropriate):
[here](https://imgur.com/a/9bNF6)
### Steps to Reproduce (for bugs)
1. Open email with link
2. Click link
3. ???
4. Profit

### Your Environment
* Franz Version used:  5.0.0-beta.15
* Operating System and version: Ubuntu 16.04.3 x86_64
* Earthly Continent: UK

**Comment by jwelton** [comment]
I think this is a duplicate of #685
