### ISSUE TITLE
Franz issues on Fedora 27

### ISSUE THREAD

**Issue by orschiro** [meetfranz/franz#701]
Tested `franz-5.0.0-beta.15-x86_64.AppImage` on Fedora 27. These are my issues:

- Missing icon in Dock
- Corrupt tray icon
- Invite broken

Attaching images:

![screenshot from 2018-02-16 16-15-38](https://user-images.githubusercontent.com/170947/36314345-d25f13ac-1334-11e8-8d06-76077e73b10b.png)
![screenshot from 2018-02-16 16-15-33](https://user-images.githubusercontent.com/170947/36314346-d28bf2a0-1334-11e8-99ee-71f1adcae5eb.png)
![screenshot from 2018-02-16 16-14-21](https://user-images.githubusercontent.com/170947/36314347-d2b42a36-1334-11e8-8ad2-33da45a0cf09.png)

**Comment by Ash258** [comment]
1. Not sure if https://github.com/meetfranz/franz/blob/master/electron-builder.yml#L24 is correctly set. 
2. Icon is there, but it's not clearly visible. (#700 , #613)
3. Maybe duplicate of #649 ?

**Comment by orschiro** [comment]
Thanks @Ash258! Will subscribe to those issues. 

Surprised seeing you here too ;-)

The Rambox custom code to show WhatsApp is currently doing it for me.

**Comment by orschiro** [comment]
> Could you search in existing issues a little bit before opening a new one 

@closingin my apologies. Will do in the future!
