### ISSUE TITLE
Notifications appear on locked session screen

### ISSUE THREAD

**Issue by moussetc** [meetfranz/franz#702]
When the windows session is locked, Slack notifications (and their content) still appear.

### Expected Behavior
For privacy/security reasons, there should be no notifications visible on a locked session.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/8834237/36316049-84da04f2-1339-11e8-9e21-a238412f3500.png)

### Your Environment
* Franz Version used: 5.0.0-beta14
* Operating System and version: Windows 10

**Comment by Ash258** [comment]
Definitely there should be option for "invincible" notification on lock screen, because everyone don't want to have this feature on. It would be bad to force everyone use this feature.

**Comment by Ash258** [comment]
Relate to #570 ?

**Comment by ptavasci** [comment]
First thing I noticed after less than 10 minutes of using it. It's a huge security issue.

**Comment by NikolaSimovic** [comment]
Any news on this?

**Comment by moussetc** [comment]
I'm not using Franz anymore, but if Franz is using the Windows 10 notification system, you can [disable Lock Screen notifications](https://www.tenforums.com/tutorials/31116-turn-off-lock-screen-notifications-windows-10-a.html) for all apps using the W10 system. Bonus: with that settings, Outlook should also stop displaying parts of your received emails for anyone to see on your locked screen...
