### ISSUE TITLE
Black Screen that only solves closing the app

### ISSUE THREAD

**Issue by DiegoBlond** [meetfranz/franz#704]
While i'm using the app on my dell, sometimes it turns into a black screen, then i have to exit the app and open it again

### Expected Behavior
Shouldn't turn intoa black screen

### Current Behavior
Black screen, usually when i'm changing between chats with ctrl+tab (Have 2 slacks, one messenger and one whatsapp)

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/25189268/36320536-aeffd0ce-132d-11e8-9521-54c9db442af8.png)

### Steps to Reproduce (for bugs)
Don't happens every time, but it's while using the app for like 20 minutes
1.
2.
3.
4.

### Your Environment
Dell notebook with windows

**Comment by dzek69** [comment]
Looks like hardware acceleration issue. Try disabling it, should be possible with --disable-gpu switch from command line.
Or try alternative software, this one looks pretty buggy and ... dead?
