### ISSUE TITLE
Services wiped and cannot add new oones

### ISSUE THREAD

**Issue by Gelio** [meetfranz/franz#705]
I was a happy user of Franz with 5 active services (Messenger, 2x Slack and 2x Inbox). Today, they failed to show up and I was greeted by the _Get started_ button and the starting screen. Moreover, there was a message on a red background at the bottom saying:

> Could not load services and user information. Try again

I tried pressing the button several times, reloaded Franz with `Ctrl + R`, restarted it by closing and opening again, all to no avail.

Additionally, when I want to add a new service it says that:

> Sorry, but no service matched your search term.

even though the search box is empty, no matter if I am browsing through _Most popular_ or _All services_ or type anything in the search box.

Note, that I have not had any problems with Franz before, I did not change any settings when this happened and my PC was also not updated/modified in any way. It was working yesterday evening and after turning my PC on today morning I noticed this.

### Expected Behavior
Franz should load services I was using before or at least let me add them back again.

### Current Behavior
All of my services were deleted and I cannot add new ones.

### Screenshots (if appropriate):
The screen I ma greeted with after starting Franz:

![image](https://user-images.githubusercontent.com/889383/36338957-2d6bcf3e-13bb-11e8-9eb7-834e3472a6d9.png)

No services available when trying to add them:

![image](https://user-images.githubusercontent.com/889383/36338960-4420af38-13bb-11e8-96f3-d5b96a2353bd.png)

### Possible Solution
No idea, but I am a Javascript developer, so if I can help solve this issue, I would gladly do so :smile: Just point me in the right direction

### Steps to Reproduce (for bugs)
No idea, because I did not modify anything and this happened. I can provide any log or debug files if necessary.

### Your Environment
* Franz Version used: 5.0.0-beta.15
* Operating System and version: Windows 10 Pro 10.0.16299

**Comment by PashaKagan** [comment]
Same happened to me this morning, came here to report.

**Comment by Pawnee** [comment]
The same problem happened to me. Cannot do anything at the moment.

**Comment by Gelio** [comment]
It started working for me again. I did not do anything, I was not even around my PC when it fixed itself, but I guess it reloaded itself.

The issue is solved for me. @PashaKagan @Pawnee does it work for you?

**Comment by Pawnee** [comment]
Yep, all good here too.

**Comment by incace** [comment]
I am having this issue this morning and it's been sitting here for about 30 minutes now. Trying to reload does nothing. Any way to fix?

**Comment by alsco77** [comment]
Anybody find a resolution/debug method or did Franz just start working again after a while?

**Comment by snisarg** [comment]
Happening to me too right now. Reinstalled the app. (Did not clear the data though) on Mac.

**Comment by boofinka** [comment]
Happening here as well.
@snisarg did reinstalling the app fix the problem?

**Comment by snisarg** [comment]
I did. I even tried wiping out all the data for a clean start. Right now it says it can't contact Franz online service. Their hosts are down? 
Also does the app need the Franz service to work? All the data it needs should all be there locally.

**Comment by pete001** [comment]
Happening to me too, i assume their user auth api is broken. We just need to wait until its back up.

**Comment by zarbin** [comment]
Happening here as well.  Will just wait :)

**Comment by kdarbela** [comment]
Having the same experience.

**Comment by lorranpego** [comment]
I am having the same problem for over 4 hours now.

**Comment by serbanmarti** [comment]
Just started not working for me as well.

**Comment by aapostol87** [comment]
Started doing the same thing for me.

**Comment by massimocuratella** [comment]
Same problem here. If I could do something I would make the app more resilient to remote failures.

**Comment by Fabian1976** [comment]
Ditto

**Comment by jnor** [comment]
Same ugh!!!

**Comment by pmasia** [comment]
Same here on a Mac OSX 10.14...

**Comment by meglizkirsche** [comment]
working for me now!

**Comment by b-reich** [comment]
@Gelio I think this is still a problem. Have this bug on linux at the moment.

**Comment by farkroft** [comment]
I'm having this problem right now, anyone how to fixed it ?

**Comment by b-reich** [comment]
> 
> 
> I'm having this problem right now, anyone how to fixed it ?

do you use pihole?
