### ISSUE TITLE
reset password token not valid

### ISSUE THREAD

**Issue by gacallea** [meetfranz/franz#709]
I'm trying to reset my password and when I click on the link in my email it says that the token is not valid.

### Expected Behavior
click on the link > to reset the password.

### Current Behavior
click on the link > token invalid

### Screenshots (if appropriate):
<img width="1327" alt="screen shot 2018-02-17 at 11 41 06" src="https://user-images.githubusercontent.com/3269984/36344973-7be046ba-13d7-11e8-91d0-9a78d945b124.png">

### Context
I'm out of my Franz app now.

### Your Environment
macOS High Sierra 10.13.3
Franz 5.0.0-beta.15 (installed via homebrew)

**Comment by adlk** [comment]
It would be interesting to see the console output of you browser. _Token is not valid_ is currently the default message before the actual check happens (we are on it).
**On top:** it would be great to know your Browser and OS

Just a general note:
- Tokens are only valid if they have been requested from the live app (not in dev environment)

**Comment by gacallea** [comment]
hi @adlk 

my browser is the latest Safari 11.0.3 on macOS High Sierra 10.13.3

I did request the password reset from the Franz client (at the login window).

I hope this can be helpful
