### ISSUE TITLE
>100% CPU Usage by Franz Helper (Version 5.0.0-beta.15)

### ISSUE THREAD

**Issue by alexwerth85** [meetfranz/franz#710]
### Expected Behavior

Franz Helper shouldn't use more than 100% CPU

### Current Behavior

Franz Helper is using over 200% CPU Power.

### Screenshots (if appropriate):
![screenshot 2018-02-19 10 11 26](https://user-images.githubusercontent.com/36621753/36370236-9edad1de-155e-11e8-86f6-4a18c4330c06.png)  

### Steps to Reproduce (for bugs)

1. Turn on Franz
2. CPU is running high
3. Macbook is slowing down and Fan is running like rendering highres Videos or something else like that

### Your Environment

* Franz Version used:  5.0.0-beta.15
* Operating System and version: 
Macbook Retina Mid 2015 | 2,8 GHz i7 | 16 GB Ram

**Comment by dzek69** [comment]
Same is on Linux Mint 18.3 x64.

After few months of this randomly happening I switched to RamBox - same thing, more features for free, doesn't require to login to own service, no flickering when switching services and of course no CPU usage bug.

**Comment by adlk** [comment]
This has been reported a few times in various issues and is tracked internally. Closing this for now.
