### ISSUE TITLE
Changing services goes into never-ending-loop

### ISSUE THREAD

**Issue by rwkyyy** [meetfranz/franz#711]
I have 4 services, and I use them all the time, sometimes I answer to a message and get two others in two different services, so I change fast with CMD + number (1-4).

I've noticed that if I change 2 or more, it will go into a changing loop.

### Expected Behavior

Service window not going in changing loop.

### Current Behavior

Service window changing from one window to another.

### Screenshots (if appropriate):
https://youtu.be/ObKPX-xcHS4

### Steps to Reproduce (for bugs)

1. select one service
2. change to another
3. change to another
4. change to another
5. it goes into loop.

### Context

Can't say it's a ground-breaking issue, but it's annoying to have to restart franz 2-3 times a day.

### Your Environment

* Franz Version used: 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: macOS High Sierra 10.13.3

**Comment by closingin** [comment]
I cannot reproduce this bug on Arch Linux, and your video is not available.

**Comment by rwkyyy** [comment]
it's only on macOS from what I noticed, on Windows is not (tested)

p.s. Updated the video so it can be viewed, my bad, sorry.

**Comment by Maxxx88** [comment]
have the same type of issues even with one active service.
since the last version, the apps is not working well at all on MacOS

**Comment by closingin** [comment]
@rwkyyy @Maxxx88 I can't test for this problem, but I'll take a look to see if I find a behavior triggering this bug when I'll have time.

**Comment by closingin** [comment]
@rwkyyy I can't test. I'm not using a Mac. And this bug doesn't seem to affect linux distributions.
