### ISSUE TITLE
Allow services to be enabled/disabled directly from service list in settings

### ISSUE THREAD

**Issue by OldhamMade** [meetfranz/franz#714]
### Feature Description
_In order to quickly enable services which are currently disabled
As a user viewing the "Your Services" listing in Settings
I want to click the "power" icon to enable the service directly and not have to go into the service's settings page to use the toggle._

### Motivation and Context

Currently, if disabled services are hidden from the sidebar, if I wish to enable a set of services, the workflow is:

1. Open Settings
1. Click "Your Services"
1. Scroll to the service you to be enabled
1. Click toggle to "Enable Service"
1. Click "Save Service"
1. Go to step `3` for each additional service

This can be annoying if you switch services on and off a lot (say, you use a set for "work" and a set for "home").

If the "power" icon were the toggle – for example, went from grey (disabled) to green (enabled) – users could save having to go through 2 extra steps per service.

**Comment by SamVanhoutte** [comment]
I was actually going to request the exact same feature.  It would be great (and save clicks) to just be able to either right-click+enable or to use the power icon as a button, so that the service would be enabled from the service list.

**Comment by OldhamMade** [comment]
@SamVanhoutte Yep, from a UX perspective the power icon "feels" like it should be clickable and should "do the right thing" and enable/disable the service. Then you click it and it takes you to the settings screen and feels "broken".
