### ISSUE TITLE
Email Client

### ISSUE THREAD

**Issue by Xavilien** [meetfranz/franz#716]
Create an email client like the mail app in macOS, just that it is integrated with the franz app

### Expected Behavior

I think there should be an email client integrated into the app, such that we can login to our emails through that client instead of relying on the website of our email servers.

### Current Behavior

Currently, emails are basically loading the website, however, this improvement means that the email client is not just loading the website.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

I would like to see this feature as currently the websites for emails are not very good. For example, the google mail website is really bad and does not support basic things like keyboard shortcuts, and the design isn't very nice. Another example would be outlook, which requires me to type in my password every time I open the franz app. Because I use a random password, it is very troublesome to find my password in my password manager. Thus, creating an original email client means that many features and functionalities that the websites cannot provide can be made possible, thus making franz easier to use. Thank you! :)

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by einfallstoll** [comment]
Franz uses web clients by design. Therefore it has to use an existing service. At the moment custom E-Mail sites are supported through Franz Premium (Rainloop. Roundcube, …)

**Comment by haraldox** [comment]
@einfallstoll thanks for the explanation! :)
