### ISSUE TITLE
Bear support

### ISSUE THREAD

**Issue by HugonatorSA** [meetfranz/franz#718]
Bear is the same as Google Keep just better

### Expected Behavior
It needs to work like the current Bear app just in Franz

### Current Behavior
It needs to work like the current Bear app just in Franz

### Possible Solution
Add Bear support
### Context
Need more support for note taking features

**Comment by nemilya** [comment]
Franz app support just services with web-version.

Based on this link, Bear dosnt have web version yet, but planned:

http://help.shinyfrog.net/discussions/bear/8717-any-news-about-a-web-version-of-bear
> we had some drawback to the web development and we had to move the release date from early 2018 to mid/summer 2018, but the development is still on track.
