### ISSUE TITLE
Custom icons disappeared

### ISSUE THREAD

**Issue by ygrange** [meetfranz/franz#722]
I have been using custom icons for some of my slack channels. For some reason those seem to have recently disappeared. If I go to the service settings, there is an option to Delete the custom icon, but if I click it nothing happens (my line of reasoning was that I could delete the icon and add it again; hoping that I still have a copy of the original).  

### Expected Behavior
Icon should show

### Current Behavior
Icon does not show

### Screenshots (if appropriate):
![screen shot 2018-02-22 at 16 42 54](https://user-images.githubusercontent.com/6578686/36548472-b0f0b5e8-17f0-11e8-8b34-6eb7bf773b06.png)
![screen shot 2018-02-22 at 16 34 12](https://user-images.githubusercontent.com/6578686/36548470-b02c99ba-17f0-11e8-92bd-6586b6165e78.png)

### Possible Solution
Fix the bug (I assume it's a bug...)

### Steps to Reproduce (for bugs)
I don't really know when this happens actually...

### Context
I think the context is obvious here: trying to have good icons.

### Your Environment
* Franz Version used: 5.0.0-beta.15.607
* Operating System and version: OSX 10.13.3

**Comment by ygrange** [comment]
(not sure why one looks like a square, and two look like a broken image. Possibly because the square is the one I tried deleting which still doesn't seem to have happened actually...)

**Comment by adlk** [comment]
Due to a change in our infrastructure the asset cdn was pointing to an old server. We have now updated our configuration and everything should be back to normal.
