### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by zalun** [meetfranz/franz#723]
After upgrading to 5 I've lost the login. Tried all my emails and I can't reset the password.

### Your Environment

* Franz Version used: 5.0.0
* Operating System and version: OSX (not that it matter)

Please help me find the email to reset the password

**Comment by closingin** [comment]
I might be wrong, but I don't think that older Franz (4 ?) accounts are compatible with Franz 5.

**Comment by adlk** [comment]
The dirty truth is that we never actually had accounts in v4. We had an email option labeled "account" which should have lead to accounts long term but we never managed to do it.

**Comment by zalun** [comment]
Ah, right - OK - I was so confused - made a new account and linked well.
Thanks
