### ISSUE TITLE
Telegram feature

### ISSUE THREAD

**Issue by acetico** [meetfranz/franz#726]
### Expected Behavior
Please show Chats & Groups separately from Channels & Bots. 
Telegram is becoming very popular, but it is messy inside since all of its possibilities are in one window.
So I suggest that you can separate personal messaging from huge amount of info from different Channels & Bots.

### Current Behavior
Everything is messed up. Personal messages get lost in the bulk of different subscriptions...

### Possible Solution
Provide different Tabs for Chats, Groups, Channels, Bots.
You may look at Telebot, an alternative Telegram client.

### Your Environment

* Franz Version used: 5.0.0-beta.14 (5.0.0-beta.14.451)
* Operating System and version: MacOS HS 10.13.3 (17D102)

**Comment by SuperMasterBlasterLaser** [comment]
It will be good idea to separate channels, groups and personal chats explicitly

**Comment by miwi-fbsd** [comment]
Actually this needs to be addressed at the telegram web team not her.

**Comment by closingin** [comment]
@acetico This is related to Telegram, not Franz.
