### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by davidgund** [meetfranz/franz#727]
After I updated Franz to version 5.0.0-beta.1.6 I'm not been able to add the services that I used to use in the app. When I try to add Whatsapp nothing happens, same to Messenger.

**Comment by haraldox** [comment]
@davidgund the update should not mess with your existing services, as those are stored in the cloud. can you post your Developer Tools Console output?

are you using a VPN by any chance?

**Comment by davidgund** [comment]
No, I’m not. Actually I downgraded the version and It worked just fine. So the problem is within this new version.

Att
David Gun

Em 28 de fev de 2018, à(s) 11:02, Harald <notifications@github.com<mailto:notifications@github.com>> escreveu:


Closed #727<https://github.com/meetfranz/franz/issues/727>.
