### ISSUE TITLE
Services disappeared and cant add new ones 

### ISSUE THREAD

**Issue by ffozsoy** [meetfranz/franz#729]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by ppoetz** [comment]
I face the same issue. 
Version installed: 5.0.0-beta.16
OS: Windows 7

After the update all my services are lost and I cannot add any.
Clicks on the services have no effect.

Restarting doesn't help either.
Next step: Reinstalling Franz... I'll let you know, if this fixes the issue.

**Comment by ppoetz** [comment]
Workaround:
* Uninstall all Versions of Franz on your system
* Download and install https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.14/franz-setup-5.0.0-beta.14.exe

**Comment by ffozsoy** [comment]
Thank you for the support. 

İt didnt work :/ I am on a mac. I love Franz and this happening made me feel like I cant even check my emails :) 

I hope there are other ways.
