### ISSUE TITLE
Disabling notification and sounds doesn't work 

### ISSUE THREAD

**Issue by PLens** [meetfranz/franz#733]
By pressing the "disable all notifications" button shaped like a bell, the sounds keep popping up when using WhatsApp within Franz.

Also, by right clicking de WhatsApp service, the text indicates all notifications should be disabled, but still sounds keep popping up when new messages arrive. Going to edit and disabling the service has the same effect.

There currently is no consistent way of disabling notification sounds from WhatsApp, not sure of other services.

Running on Franz 5.0.0.-beta.16.762

**Comment by iamtomlindley** [comment]
I also have this problem. It affects all of my services. I switch it off and next time I launch Franz it is re-enabled. Does my head in.

**Comment by Robbertdk** [comment]
I have the same problem, also macOS 10.13.3 / Franz 5.0.0-beta.16.762.

**Comment by mauodias** [comment]
Same here, I use Hangouts only and couldn't find any working way to mute the notifications

macOS 10.13.3 / Franz 5.0.0-beta.16.762

**Comment by Tulilaulu** [comment]
Same here, the mute does not mute telegram, not sure about the others. I'm using windows and 5.0.0-beta.16 version.  Does anyone know a fix for this, it might really turn me off using the service at all, even though otherwise I like it very much.

**Comment by chrisleo90** [comment]
Same here - seems to be worst with WhatsApp

macOS 10.13.3 / Franz 5.0.0-beta.17.834

**Comment by daleth** [comment]
I have the same problem on Linux running Gnome and with Telegram as Service in Franz. Both options to disable Sounds (Settings in Service and in left toolbar) are enabled. There are still sounds on incoming messages.

Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

Thanks for solving this issue.

**Comment by Leocano** [comment]
Same problem here, my workaround was disabling sounds inside each service.

Version: 5.0.0-beta.18
Release: 1.8.4 / win32 / x64

**Comment by djalmaaraujo** [comment]
#900

**Comment by camwas92** [comment]
I have the same problem, on mac and windows. It seems to be for all applications as slack also can't be muted

**Comment by paulhklam1122** [comment]
Still having this issue on the latest MacOS High Sierra 10.13.6 and running Franz version: 5.0.0-beta.18

**Comment by eusoulivres** [comment]
I have the same problem. the weird thing is that I had been using Franz on my old computer for a few weeks already without any problems. I have a new computer, which has the same OS (Windows 10) and 
using the same version of Franz (5.0.0 beta 18) and now I am experiencing this issue.

**Comment by karantan** [comment]
I've been having this problem for +6 months now. It is really annoying.

**Comment by shuriu** [comment]
Same issue. My workaround is to re-enable and disable notifications again.

I've found that after a new service update and refresh (watsapp gets updated for example), notifications are reset. So re-enabling and disabling again works for me.

It's annoying because these updates happen very often.

**Comment by alainrostain** [comment]
I'm still having this problem in April of 2020. I turn all sounds off and still get notifications. Making matters worse, the sound upset my Westie, who freaks out. Is there a workaround? Thank you!
