### ISSUE TITLE
Can't connect Google Drive with Trello inside Franz

### ISSUE THREAD

**Issue by RHEINWEB** [meetfranz/franz#735]
I think Franz doen't allow Popups. In the Service "Trello" i can't connect to Google Drive. And there is no Preview of Google Drive Docs and Images available.
![franz-trello-drive](https://user-images.githubusercontent.com/26331399/36701095-505dc0d0-1b52-11e8-9114-3699a99c45ab.png)

**Comment by Thomvh** [comment]
I will look into this!

**Comment by czukowski** [comment]
Same issue here. I think this might be because it tries to load an external URL outside of Trello service and Franz won't allow that.

**Comment by Xerus2000** [comment]
Same for the GitHub Power-Up - super annoying :/

**Comment by hannojg** [comment]
Same here, power up tries to open new browser popup for verification. Please look into this!

**Comment by pkostrzewski** [comment]
Still not fixed. Can't add GitHub account to trello because trello want to open new popup window with GitHub authorization.
