### ISSUE TITLE
Where are the configured services stored?

### ISSUE THREAD

**Issue by schmunk42** [meetfranz/franz#736]
### Expected Behavior

Look into `~/.config` (Linux)  and easily find a file with the config of the configured services/accounts.

### Current Behavior

Seeing a huge bunch of files, also caches - can't find the config.

### Context

I wanted to add the Franz service configuration to my personal (secret) dotfiles.

### Your Environment
* Franz Version used: 5.0.0-beta.15
* Operating System and version: Antergos Linux release 18.1 (ISO-Rolling) / GNOME

**Comment by haraldox** [comment]
Your service configuration of Franz 5 is stored in the cloud.

**Comment by schmunk42** [comment]
Also passwords etc...? 

Looks like I was fooled by...

> How do you handle my personal messages & chats?
Franz does not read anything you type, send or receive. That's between you and your messenger service. His only interest is to successfully deliver your messages. No nosing – all hail postal secrecy!

and

> Franz does not store your password nor does it directly access your messaging service's account!

Since there's also 

> If you explicitly opt in to synchronize your session data (session data usually does not contain any passwords) with your other computers, we will encrypt your credentials, using high security industry standards, and store them as long as necessary on our servers. The encryption of your data will happen on your computer. We will never have access to plain text credentials.

under https://meetfranz.com/privacy/

I am I right that there's no more *opt-out* for this "feature" starting from Franz 5?

**Comment by schmunk42** [comment]
@adlk If read the thread https://github.com/meetfranz/franz/issues/71#issuecomment-342815507 - actually I'd have expected that someone who closes this links me to such an important discussion.

I can understand that there needs to be some business around Franz and it's more than fair that you get something (money) back from your work.

But the way how the communication is handled is really poor and made me also look for alternatives, if you're interested you can read about the issues (statements from Franz) in this thread.
