### ISSUE TITLE
Please add hedgehog to smiles

### ISSUE THREAD

**Issue by nichcom** [meetfranz/franz#737]
Please add hedgehog smile to Franz smiles, it is currently missing.

Reason: hedgehogs are cute!

Business value: 15% increase in customer retention.

**Comment by einfallstoll** [comment]
Although I'm 100% for hedgehogs, I believe this issue is related to some service _inside_ Franz (e.g. WhatsApp, Telegram, …) and has nothing to do with the container itself. 🦔
