### ISSUE TITLE
Tray Icon wont stay pinned visible

### ISSUE THREAD

**Issue by silv3r23** [meetfranz/franz#738]
I pin the icon to the system tray but it does not stay there on Windows 10 x64 1709 (the taskbar icon is disabled)

version 5.0.0-beta.16

I tried drag n drop to pin it like other icons and manually set it up under Windows Settings "symbols at system tray". The setting switches back when mesenger has been closed or minimized to tray for a while.

**Comment by element6th** [comment]
Same problem here :(

**Comment by mkopacek** [comment]
Mee too

**Comment by rubensa** [comment]
See: https://github.com/meetfranz/franz/issues/786#issuecomment-438227456
