### ISSUE TITLE
Franz requesting dedicated gpu on MacBook Pro

### ISSUE THREAD

**Issue by im-fabian** [meetfranz/franz#741]
### Expected Behavior
I expect franz not to require the dedicated gpu within my macbook but to be fine with the less powerconsuming intel-gpu.

### Current Behavior
Franz requests the dedicated gpu of the mac which results in an inadequate power consumtion of the franz app.

### Screenshots (if appropriate):
<img width="1263" alt="franz" src="https://user-images.githubusercontent.com/31921275/36733150-f820dfb4-1bcf-11e8-9513-70ffa96315bb.png">

### Steps to Reproduce (for bugs)
1. Start Franz
2. Chat a little bit

### Context
If you are in a enviorment where it's disturbing if you fan spins up or you do not have the possibility to recharge franz is not usable as messenger.

### Your Environment
* Franz Version used: 5.0.0-beta16.762
* Operating System and version: macOS 10.13.3
* Hardware: MacBook Pro Retina mid 2015, 2,8 GHz i7, AMD Radeon R M370X 2GB, Intel Iris Pro 1536MB

**Comment by freinbichler** [comment]
duplicate of #117
