### ISSUE TITLE
[Messenger] Dark mode implementation

### ISSUE THREAD

**Issue by AJRamos308** [meetfranz/franz#744]
Greetings!

First and foremost, **great piece of software**, just started using it and no complaints so far!

So, for **Messenger** there is no official **Dark Mode**, however, there are extensions, like [**this one**](https://chrome.google.com/webstore/detail/messenger-theme-selector/cghmigojnbaajmeigfphpaiepjjhcbpe?utm_source=chrome-app-launcher-info-dialog) which can enable it in a beautiful way. 

Is there any possibility of implementing this?

Thanks in advance.
Afonso Ramos

**Comment by haraldox** [comment]
@AJRamos308 thanks for the praise, it is very much appreciated! :)

Franz does not interfere with the content of the services and I'm not sure if that will ever change. At the moment there is no extension mechanism planned... sorry to disappoint!

Best,
Harry
