### ISSUE TITLE
No services are loading after updating from Version 5.0.0-beta.14 (5.0.0-beta.14.451)

### ISSUE THREAD

**Issue by friendtam** [meetfranz/franz#746]
None of the services are loading after Franz is updated from v5.0.0-beta.14 to v5.0.0-beta.*(15 and 16)

### Expected Behavior

Updated Franz should start all the services that were previously configured.

### Current Behavior

After Auto-updating to beta 15,  it just displays the "Get Started" screen. None of the services I configured getting loaded. Tried reload Franz, signout and relogin, add New services, nothing works. It just shows the "Get Started". 

### Screenshots (if appropriate):
<img width="1452" alt="screen shot 2018-02-28 at 10 36 16" src="https://user-images.githubusercontent.com/3773506/36771038-e6e80c1e-1c73-11e8-9f88-142f1ae37efa.png">

### Possible Solution

Need to handle the Migration of the data of currently logged in services.

### Steps to Reproduce (for bugs)

1. Install beta 5.0.0.beta.14
2. Configure the services.
3. Update to bet.16

### Context

Unable to use the app. I have to manually install Franz beta.14 again and again to use the app.

### Your Environment

* Franz Version used: 
* Operating System and version: Mac OS High Sierra v10.13.3

**Comment by haraldox** [comment]
@friendtam can you please show the Developer Tools Console output?

**Comment by friendtam** [comment]
I have updated to "Version 5.0.0-beta.18 (5.0.0-beta.18.903)" and it is working fine now.
