### ISSUE TITLE
Problem with "New" Button on Office 365 Outlook service

### ISSUE THREAD

**Issue by Psykoangel** [meetfranz/franz#747]
Hi,
First of all, great application, great job ! Nothing else to say than : Bravo and stay on course !

To the point now :
I just installed Franz, created a new Office 365 Outlook service and logged in successfully. I checked my mail and tried to answer. A new Franz window opened (just like for other links when I opened them in Franz), titled with "_blank", but stood completely empty. So, I tried with the "New" button and it gave me the same result.

### Expected Behavior
Simple Clicking on "New/Answer" button in Outlook 365 should open a new window to let you write a mail and to send it, just as the web application. 

### Current Behavior
Currently, a new Franz Window opens, but stays empty.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/3429552/36788361-f346050a-1c8d-11e8-8795-4ba9e6541856.png)

### Possible Solution
Maybe a redirection issue.

### Steps to Reproduce (for bugs)
1. Install and Open Franz
2. Open Office 365 Outlook and log in
3. Click "New" button or "Answer" on a mail
4. See the "_blank"-titled Franz window opening.

### Context
I was reading my mails and tried to answer. Than, I tried to create a new mail.

### Your Environment
* Franz Version used: 5.0.0-beta.16
* Operating System and version: Windows 10 Pro x64 4Go RAM Intel Celeron G1840 2*2.80GHz

**Comment by MarkGaze** [comment]
I'm also getting this issue whenever O365 Outlook tries to open a new window

You can work around it by changing your settings in O365 to let you reply in the same window (the one in Franz)
