### ISSUE TITLE
When I restart Franz I lost all icons

### ISSUE THREAD

**Issue by corradopetrelli** [meetfranz/franz#748]
### Expected Behavior
...

### Current Behavior
Yesterday I shut down my PC and I lost all icons.
I don't shift any images.
(Look the screenshot)

### Screenshots (if appropriate):
![](https://imgur.com/xZBkLq3.jpg)
### Possible Solution
Re-insert all icons.
### Steps to Reproduce (for bugs)
I don't know.
### Context
...

### Your Environment
* Franz Version used: 5.0.0-beta 16
* Operating System and version: Windows 10

**Comment by haraldox** [comment]
@corradopetrelli can you try to delete your Franz folder in %APPDATA% and restart Franz?

**Comment by corradopetrelli** [comment]
If the problem will happen again, I do it
