### ISSUE TITLE
Todoist keeps logging out & App goes blue

### ISSUE THREAD

**Issue by sach160** [meetfranz/franz#749]
With the latest update, a new issue whereby todoist seems to keep logging out intermittently and the app goes blue. The only way to resume is to quit, reload and log back in to todoist.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.
Not possible to provide - just happens randomly without doing anything

### Your Environment

* Franz Version used: latest
* Operating System and version: mac os - latest

**Comment by kevinn** [comment]
This is happening on my end as well. 

I have Franz open and suspend the Macbook by closing the lid, resuming work will see a blue window on the franz app.

5.0.0-beta.16.762
macOS 10.13.3

**Comment by phillipprado** [comment]
I don't experience the blue window, but it does keep signing me out of Todoist every time the application refreshes. At first, I thought it was just when I close the Franz application, but I discovered that when you are in Todoist and you use cmd+r to refresh the content, it signs you out. So I think there should be a way to check a "keep me signed in" box, but that may be something that needs to change on Todoist's side, not Franz's. I don't know.

**Comment by avatarkava** [comment]
https://github.com/avatarkava/recipe-todoist/issues/3 I fixed this on my maintained version of the recipe back in February but it hasn't been integrated into the official repository (yet?) - instructions on how to fix in the meantime are there.
