### ISSUE TITLE
Tray icon is outsized in Kubuntu

### ISSUE THREAD

**Issue by jasmines** [meetfranz/franz#753]
See the screenshot:

![schermata del 2018-03-01 11-24-59](https://user-images.githubusercontent.com/894920/36839779-48a5451e-1d43-11e8-95ca-4e52517a39d1.png)

Franz icon is the one with the red circle part on it (it is the indicator of unreda messages).

**Comment by urbels** [comment]
same for me on KDE Neon.

**Comment by jasmines** [comment]
It seems solved with a new set of icons (Numix Light) but now the keep attention status is light blue instead of having the red circle.
In addiction, it would be appreciated if the circle will show the unread count...

**Comment by jasmines** [comment]
downloaded 5.0.0.17 and the problem is there again... 
WTF...

**Comment by boriseto** [comment]
`env XDG_CURRENT_DESKTOP=Unity franz`
This command fixed the problem for me on KDE Neon (16.04).

**Comment by jasmines** [comment]
@boriseto no luck in kde neon (17.10)

**Comment by boriseto** [comment]
Huh. I guess in my case it works because of libappindicator1

**Comment by jasmines** [comment]
@boriseto I've libappindicator1 installed too

**Comment by boriseto** [comment]
@jasmines just to be safe, you turned off Franz completely and run it from terminal with the command, right?

**Comment by jasmines** [comment]
@boriseto yes, of course

**Comment by boriseto** [comment]
Can't figure out why. Here it is how it looks on my desktop.
![screenshot_20180403_120925](https://user-images.githubusercontent.com/396355/38243522-12182b24-3738-11e8-8a2c-5cff6a401220.png)

**Comment by nielsonrolim** [comment]
Same with me. I'm using KDE in Majaro.

**Comment by ViperAlpha** [comment]
why wont fix?
