### ISSUE TITLE
Tray icon is flickering on Ubuntu 16.04

### ISSUE THREAD

**Issue by antoon-r** [meetfranz/franz#754]
### Expected Behavior

Icon in tray (AppIndicator) should not flicker

### Current Behavior

Icon in tray (AppIndicator) changes to no-icon placeholder (red crossed circle) every 5 seconds, no matter if there are notifications or not.

### Screenshots (if appropriate):

This is how it looks like:

![flicker](https://user-images.githubusercontent.com/22833999/36847807-7dbc1ea8-1d70-11e8-8270-a9d5ee4c4251.gif)

This is what I call the no-icon placeholder:

![icon](https://user-images.githubusercontent.com/22833999/36847846-98cab0b0-1d70-11e8-9c5e-9ce63c1a5302.png)

### Steps to Reproduce (for bugs)

On Ubuntu 16.04 LTS with Unity, update Franz using franz_5.0.0-beta.16_amd64.deb installer.

Open Franz, make sure that "Show Franz in system tray" option is enabled.

Look at the icon in the tray.

### Context

This is wery annoying because it makes me think there is new notification, but there isn't.
Solved for now by hiding this icon from tray.

### Your Environment

* Franz Version used: 5.0.0-beta.16
* Operating System and version: Linux Ubuntu 16.04 LTS x86_64 with Unity.

**Comment by monsieurluge** [comment]
Same here, same OS and versions.

**Comment by Chrizzle123** [comment]
I can confirm this issue too.

**Comment by kejml** [comment]
Happened to me on beta 16, fixed for me on beta 17

**Comment by antoon-r** [comment]
Confirm that it was fixed in 5.0.0-beta.17

**Comment by tiriana** [comment]
Is there any workaround for this? I just installed discord on ubuntu 16.04 and this flickering tray icon is very distracting.
