### ISSUE TITLE
Emoji shortcut (^⌘space) not available in edit menu

### ISSUE THREAD

**Issue by SammySdt** [meetfranz/franz#756]
Hello everyone, I have a little issue here.

### Expected Behavior
I should have the 'Emoji & symbols' item in the edit menu with the shortcut, but it doesn't appear to be available.

The strange thing is that I installed the exact same Franz app that a friend of mine has but he has the emoji shortcut and I don't. We have the same OS and pc's, the only different is that I have a touchbar and he doesn't, but I don't think the touchbar causes the problem, because in all the other apps I have the Emoji shortcut available. 

### Screenshots:
What it should be:
<img width="187" alt="capture d ecran 2018-03-02 a 10 32 26" src="https://user-images.githubusercontent.com/36632046/36892459-0b651d92-1e05-11e8-95e4-a54147bb2cda.png">

What my menu looks like:
<img width="232" alt="capture d ecran 2018-03-02 a 10 27 27" src="https://user-images.githubusercontent.com/36632046/36892468-125ac76e-1e05-11e8-8f0e-b4f6071739e0.png">

### Environment
* Franz Version used: Version 5.0.0-beta.16 (5.0.0-beta.16.762)
* Operating System and version: MacOs High Sierra 10.13.3 

Thanks for your help.

**Comment by haraldox** [comment]
this should be fixed in the next release...
