### ISSUE TITLE
Drag'n Drop Files not working (screen turns black)

### ISSUE THREAD

**Issue by SergioSGil** [meetfranz/franz#76]
Drag'n Drop Files not working on this last version

### Current Behavior

When i drag a png screenshot to Franz, sometimes the app show an black window and not send this file.

### Screenshot
https://imgur.com/a/HGjbP

### Steps to Reproduce (for bugs)

1. Open franz
2. Make a screenshot
3. Drag Screenshot to franz in a friend chat

### Your Environment

* Franz Version used:  Versión 5.0.0-beta.10 (5.0.0-beta.10.7)
* Operating System and version: Macos High Sierra (Macbook Pro 2013)

**Comment by adlk** [comment]
Can you please provide more information on this issue?

Please use the issue template as it provides most of the necessary information:
https://raw.githubusercontent.com/meetfranz/franz/master/.github/ISSUE_TEMPLATE.md

**Comment by SergioSGil** [comment]
done

**Comment by adlk** [comment]
Thanks a lot. Can you please update to the latest version to see if the issue is still happening?

**Comment by SergioSGil** [comment]
now its ok :)

**Comment by SergioSGil** [comment]
ouch! black screen again :( 

![captura de pantalla 2017-10-25 a las 13 56 52](https://user-images.githubusercontent.com/3636232/31997491-717f2b0a-b98c-11e7-9291-cf12ab2ae3de.png)

**Comment by haraldox** [comment]
Duplicate of #72
