### ISSUE TITLE
New flowdock messages do not appear if window is in focus.

### ISSUE THREAD

**Issue by travisestill** [meetfranz/franz#760]
New flowdock messages do not appear if window is in focus.

### Expected Behavior
When you receive a new message from a 1:1 message or an @mention in the Team that you are currently focused on, you should see the copy of that message in that thread.

### Current Behavior
When you receive a new message in a 1:1 conversation or an @mention in a team that is currently in focus (meaning your actively looking at that thread or 1:1), you get the notification with the copy of that message, however, the main chat window doesn't show the copy of the message. You must refresh the Flowdock service to see it. Changing tabs back and forth does not help.

### Possible Solution
Possibly the copy of that message is pushed to the notification but not the chat DOM. Push it to both.

### Steps to Reproduce (for bugs)

1.Open a 1:1 with someone and send them a message
2.have them respond while the 1:1 is still in focus
or
1. Have someone @mention you in a thread that you currently have in focus

### Context
If I miss the notification, I can't see what that person said. I can see that they sent something (indicated by the yellow dot as part of flowdock) but I have to reload the service to get the copy to show. Super annoying.

### Your Environment

* Franz Version used: 5.0.0
* Operating System and version: I have reproduced this issue using Ubuntu 2017.10, Windows 10, and Mac OSX 10.13.3

**Comment by closingin** [comment]
Are you sure it's not related to the flowdock app ? Franz works by just rendering web pages and doesn't manage their DOM. Try to reproduce this bug directly on [Flowdock](https://www.flowdock.com/login). If the problem is the same, then report the bug to their team.

If not, then what is your full Franz version (beta number) ?

**Comment by travisestill** [comment]
I'm sure. This doesn't happen when you use the dedicated app or the browser version. Doesn't happen on any mobile versions either.

**Comment by travisestill** [comment]
5.0.0-beta.16

**Comment by peterkraume** [comment]
I have the same issue. Using Franz 5.0.0-beta.18.903 on macOS 10.12.6.
The problem also occurs when Franz is running in the background. I never had these kind of problems with the native Flowdock Mac app or running Flowdock in Chrome.

**Comment by valdero** [comment]
Same issue here - Version 5.0.0-beta.18 (5.0.0-beta.18.903) on macOS 10.13.4.

**Comment by euanmillar** [comment]
Same here.  The solution is to reload Flowdock in Franz by right-clicking, and select reload, on the Flowdock icon, whenever you want to check your messages.  It's a small price to pay for an awesome free app folks.

**Comment by adimasuhid** [comment]
Also happening on my end:

Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
Operating System and version: MacOS High Sierra 10.13.5

To anyone who might find this of use, another solution for 1:1 is to close the chat box in flowdock (click `x`) and then reopen by `Start 1:1`.

**Comment by lolmaus** [comment]
I've had the same issue in Franz 4 and now having it in Franz 5 (latest beta).

Posting a demo animation:

![flowdock issue](https://i.imgur.com/MYD7aQm.gif)

Note that it's a regular thread and hidden messages do not include mentions.

I had tried contacting FlowDock support, but they didn't help.

**Comment by JoniSykes** [comment]
+1

**Comment by JoniSykes** [comment]
Is this being looked at by anyone? 
Who looks at the integrations is it Flowdock or Franz devs?

**Comment by lolmaus** [comment]
How long do we have to use Franz in a separate window?

Where is the source of the Franz integration, is it open source?

**Comment by closingin** [comment]
Hello, I didn't have enough time to check it out, but I think you should open an issue [here](https://github.com/meetfranz/recipe-flowdock) ! I guess there's a bug in the integration that has to be fixed.

**Comment by nickschot** [comment]
I'm also seeing this issue on 5.0.1.

**Comment by lolmaus** [comment]
The integration repo contains no logic at all. The issue lies within Franz itself (or in FlowDock but provoked by something unique to Franz).

**Comment by jcifuentes91** [comment]
Still getting this
