### ISSUE TITLE
Skype user requests not showing in Franz

### ISSUE THREAD

**Issue by twhiting9275** [meetfranz/franz#761]
For some reason, I'm unable to get Franz to show user contact requests. I've had quite a few go missed over the past few months, and the only way i've been able to see these is using the Skype app itself

### Expected Behavior
I'd expect that Skype add requests would go through to the Franz client and notify me as such.

### Current Behavior
Skype add requests do not go through to Franz at all, and I'm not notified

### Steps to Reproduce (for bugs)
1. Signin to Skype
2. Have someone send a contact request / add request
3. Wait for it (I waited about 2 hrs)
4. Nothing in Franz

### Your Environment
This has happened for a few months (since I started with Franz in December), on Win 10

**Comment by closingin** [comment]
Does the Skype web version actually send you a notification when you receive a friend request ? I'm not sure about that. Franz forwards web notifications to your desktop notification system, so if Skype web had delivered one, you would have received it normally.
