### ISSUE TITLE
Icon in KDE (Debian GNU Linux) deconfigured

### ISSUE THREAD

**Issue by rikex** [meetfranz/franz#762]
Version 5.0 Beta 16 in KDE.
icon is unconfigured.

On the same system, but in the MATE or LXQT Desktop the tray icon is normal.

**Comment by closingin** [comment]
What do you mean by "unconfigured" ? Can you provide a screenshot ? Did it work correctly on the beta 15 ?

**Comment by rikex** [comment]
What do you mean by "unconfigured" ?
Icon is too large. In the screen print it is possible to see.

Did it work correctly on the beta 15 ?
Correctly in Beta 14 e Beta 15

**Comment by rikex** [comment]
https://plus.google.com/photos/110962745397775453780/album/6529647898153442161/6529647900086567442?authkey=COHYlJfwla3iAg

**Comment by denis-sumin** [comment]
Same for me.

**Comment by maurehur** [comment]
I am using KDE neon and I have the same problem, any solution?

**Comment by maurehur** [comment]
I solved the problem adding "env XDG_CURRENT_DESKTOP=Unity" to franz.desktop:

sudo nano /usr/share/applications/franz.desktop

Exec="env XDG_CURRENT_DESKTOP=Unity /opt/Franz/franz" %U

**Comment by nielsonrolim** [comment]
Same for me. I'm using KDE in Manjaro.

**Comment by klemy** [comment]
Thanks @maurehur, your solution work perfectly for me!

![image](https://user-images.githubusercontent.com/10001945/45257047-a25d5e00-b39f-11e8-8d34-f6d196c50758.png)

I use :
- Franz 5.0.0-beta.18
- Ubuntu 18.04.1 LTS
- Gnome 3.28.2

**Comment by victorbrca** [comment]
> I solved the problem adding "env XDG_CURRENT_DESKTOP=Unity" to franz.desktop:
> 
> sudo nano /usr/share/applications/franz.desktop
> 
> Exec=env XDG_CURRENT_DESKTOP=Unity /opt/Franz/franz
> 
> I followed this tutorial
> https://askubuntu.com/questions/905858/appindicators-not-working-for-electron-applications-skype-for-linux-discord-et

Works for me as well on Arch with 'Franz 5.0.0-beta.18'
