### ISSUE TITLE
"You are not connected to the internet message" cannot be dismissed

### ISSUE THREAD

**Issue by swrobel** [meetfranz/franz#766]
### Expected Behavior
This message goes away automatically when I am connected. If not, it can be manually dismissed.

### Current Behavior
Message does not go away when connection is restored (I was receiving messages in Slack when I took this screenshot). View -> Reload Service or Franz does not resolve it. Only quitting the app & restarting it caused it to disappear.

### Screenshots (if appropriate):
<img width="328" alt="screen shot 2018-03-02 at 2 09 50 pm" src="https://user-images.githubusercontent.com/157270/36924495-99cda45a-1e23-11e8-8170-e0b8cfafda16.png">

### Steps to Reproduce (for bugs)

Launch the app with no valid internet connection, then restore the connection

### Your Environment

* Franz Version used: 5.0.0-beta.16 (5.0.0-beta.16.762)
* Operating System and version: macOS 10.13.2

**Comment by suburbanworrier** [comment]
Version 5.0.0-beta.18 (5.0.0-beta.18.903) has done the same for me today (running on 10.12.6 )
First occurrence in ~7 days of constant use tho.
