### ISSUE TITLE
Support Signal Secure Messenger (Feature Proposal)

### ISSUE THREAD

**Issue by robert-lieck** [meetfranz/franz#767]
### Feature Description
It would be nice (and help Franz considerably extend their user base) if the Signal secure messenger was supported, just like Whatsapp, Telegram, etc

### Motivation and Context
On moral grounds Signal is worth being supported and on commercial grounds Signal is relevant being supported because it has a huge user base.

**Comment by closingin** [comment]
I bet you didn't read the issue opening template, which tells you where to go for services request... Anyway, to answer your request, Signal doesn't have a web version, so it can't be supported by Franz as of now.

This issue can be closed.

**Comment by robert-lieck** [comment]
Thanks for the explanation! I remember reading the template (or some kind of explanation) and not fully understanding where my request should go; I also didn't identify #655 as essentially asking the same. So hopefully this issue does a better service thanks to you explanation :)

**Comment by TCB13** [comment]
+1 on Signal!

**Comment by jake-stone-germany** [comment]
+1 for Signal
I can find a web version for signal: https://signal.org/download/ 
Would be great!

**Comment by closingin** [comment]
@adlk I think you should lock this thread ?

**Comment by adlk** [comment]
Signal is not available as a web version - this is required for being available in Franz. I've been in talks with Signal and they made it clear that they are not planning to support web as a platform.
