### ISSUE TITLE
Can not add any service after updating from beta 14 (Windows 10)

### ISSUE THREAD

**Issue by ttristan** [meetfranz/franz#771]
### Expected Behavior
If I click on aservice like "Slack" "Office365" or any other service from the "Available services" window, the service should be added.

### Current Behavior
After clicking on a service, it shows a loading indication for a spolit second and nothing happens

### Steps to Reproduce (for bugs)
1. add a service

### Your Environment

* Franz Version used: updated from version 5.00 beta 14 to current beta 16
* Operating System and version: Windows 10
![image](https://user-images.githubusercontent.com/24268434/37018655-7371e33a-2115-11e8-923d-664f2ca53e6e.png)
![image](https://user-images.githubusercontent.com/24268434/37018662-7bccfede-2115-11e8-8c63-06cb6c78b297.png)

**Comment by ts-de** [comment]
short update: reinstalled previous beta 14 from https://github.com/meetfranz/franz/releases/tag/v5.0.0-beta.14 and all services are still up and running with the old version.

**Comment by kirashi3** [comment]
Can confirm; just had this bug happen to me as well.
Franz updated to 5.0.0-beta 16, claimed could not connect to Franz services despite internet working fine.
Installed 5.0.0-beta 14 again from github releases and it worked as if nothing was wrong, as it should.
