### ISSUE TITLE
All services gone after forced update from beta 14 to beta 16

### ISSUE THREAD

**Issue by ts-de** [meetfranz/franz#772]
Today my franz updated from beta version 14 to 16, although I did not chose so. After the update all services are gone and I can not add any other as reported in #771.

### Expected Behavior
- Do not update without the user initializing the update. 
- Keep the services that were added in the prior version.

### Current Behavior
- franz auotmatically updated
- all services gone
- no service can be added (#771)

### Steps to Reproduce (for bugs)
I was using the following services in version 5.00 beta 14:
Slack
Trello (2x)
Gmail
Office365
Whatsapp

### Your Environment
Franz Version used: updated from version 5.00 beta 14 to current beta 16
Operating System and version: Windows 10

![image](https://user-images.githubusercontent.com/24268434/37018993-cd7e91c4-2116-11e8-8ef2-50cbc2405ec7.png)
![image](https://user-images.githubusercontent.com/24268434/37018997-d19f08a6-2116-11e8-808c-5c4044315287.png)

**Comment by ts-de** [comment]
short update: reinstalled previous beta 14 from https://github.com/meetfranz/franz/releases/tag/v5.0.0-beta.14 and all services are still up and running with the old version.

**Comment by torch2424** [comment]
Just in case someone else stumbles upon this, downgrading didn't work for me 😢

**Comment by miogalang** [comment]
Same is happening to me. Downgrade didn't help.

![about_this_mac](https://user-images.githubusercontent.com/1471573/37068627-962ba91c-21ea-11e8-8d80-a446e8ec9fea.png)

**Comment by Lm0490** [comment]
Downgrading solved the issue for me. It is really annoying though as this is the 2nd time it happened to me. Thanks @ts-de for providing the link to the version 14.
Ps.: I am also using a mac with macOS Sierra, version 10.13.3.

**Comment by esinik** [comment]
I have the same problem. I also had this problem in beta 15. Downgrading to Beta 14 solves the issue, but it's annoying that app continuously force me to update to the new version. If I restart the app in anyway, it is updated automatically to the new version. 

![screen shot 2018-03-08 at 11 39 10](https://user-images.githubusercontent.com/3114203/37141291-9885561e-22c5-11e8-82a7-5591189fefa1.png)

**Comment by adlk** [comment]
Please follow those steps for important debugging info:
- Go to menu -> view -> toggle developer tools
- Go to console
- Provide a screenshot of the console output

If there is a message about `mailbox.org` then:
- Go to `~/Library/Application Support/Franz/recipes`
- Delete the mailbox.org folder. 
- Restart Franz

**Comment by esinik** [comment]
Thank you very much, problem is solved.
Exception message is about mailbox.org. I deleted the mailbox recipes, Franz started working normally.

**Comment by ts-de** [comment]
Hey @adlk thanks for tackling the issue. On windows I do not have the options to go to menu -> view ... and CTRL+SHIFT+ALT+I does not open then console either. Is there another way to access the console on windows?

Anyway, I gave it a go and deleted the mailbox.org recipe and it **solved the issue**

Thanks!

**Comment by adlk** [comment]
@ts-de @esinik great to hear! :tada:

@ts-de the ah sorry, I missed the windows info. Thanks for sharing the path!
In general, the menu bar on windows is only shown when pressing alt. With the next version however, we make the menu bar persistent.

**Comment by magicman32** [comment]
![file explorer](https://user-images.githubusercontent.com/15340872/52030280-3a383000-256b-11e9-85a1-5468cc5b6c1a.jpg)
![franz](https://user-images.githubusercontent.com/15340872/52030288-43290180-256b-11e9-89f6-a18e5fbf8a0b.jpg)

Windows 10............I recently had to do a system restore and now Franz wont recognise any of my installed services or allow me to click on a new service
