### ISSUE TITLE
Can't add a Custom icon for a service

### ISSUE THREAD

**Issue by AxelMonroyX** [meetfranz/franz#775]
I can't add a Custom icon for a service and when I click on save service the software don't show an error and don't save the service with the new custom icon

### Expected Behavior
Save the service with the custom icon

### Current Behavior
When you click on save service does nothing 

### Screenshots 
<img width="1060" alt="screenshot at mar 06 23-12-13" src="https://user-images.githubusercontent.com/10134378/37076440-d76ea778-2193-11e8-9c41-e3d3bec28eaf.png">

https://www.screencast.com/t/gHjlt3GNcoz2

### Steps to Reproduce (for bugs)

1. Edit or create a new service
2. Click on add custom image or icon to the service
3. Click on "Save service"

### Context
I was trying to add a new a custom image icon to a service

### Your Environment
* Franz Version used: 5.0.0-beta.16 (5.0.0-beta.16.762)
* Operating System and version: macOS High Sierra 10.13.3

**Comment by adlk** [comment]
@AxelMonroyX can you please share the image you were trying to upload here?

Best would be via dropbox or google drive as we need it in the exact same state as it is on your drive.
