### ISSUE TITLE
Slack IRC gateways are going away May 15th

### ISSUE THREAD

**Issue by mattiaerre** [meetfranz/franz#778]
as per: 

- https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP

- https://twitter.com/genehack/status/971404236490620928

it looks like "Starting on May 15th, it will no longer be possible to connect to Slack using the IRC and XMPP gateways."

will this be affecting the Franz integration w/ Slack?

**Comment by Stanzilla** [comment]
no

**Comment by mattiaerre** [comment]
thanks for confirming, closing this issue
