### ISSUE TITLE
New Google Chat: https://chat.google.com (the next hangout chat)

### ISSUE THREAD

**Issue by FreakInCage** [meetfranz/franz#779]
Hello Franz-Team,
Google have a new version from Hangouts. Its "Google Chat"
https://chat.google.com

Is is possible to include it to Franz?

Best regards from Hamburg,
Kai

**Comment by Wouter0100** [comment]
There's a service request open for this, and I've already been using it for the last month without any problems.

https://github.com/meetfranz/plugins/issues/117
