### ISSUE TITLE
FRANZ is stuck loading on messenger. Reinstall, Reload wont work.

### ISSUE THREAD

**Issue by ShaneFrost1988** [meetfranz/franz#781]
### Expected Behavior

**I want to sign into my messenger.**

### Current Behavior

Instead of signing in, or opening a loading screen, it just sticks on "sign in with messenger to get started" and loads and loads and loads. I've restarted.. I've cleared cache, forgotten service, uninstalled, reinstalled, still nothing.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/31662736/37162100-63d357e8-22c2-11e8-8885-6e04041cc13f.png)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

Windows 10
Aspire E 17 computer
Whatever the latest version of franz is on this day.

* Franz Version used:
* Operating System and version:

**Comment by szbm** [comment]
Same issue on OSX and the newest Franz. Tried to delete my cache and account, but it's still stucked in.

**Comment by ShaneFrost1988** [comment]
Yeah. I just deleted my account as well and reinstalled. Still nothing. WHAT THE FRICK.

**Comment by viper949** [comment]
Looks like everyone is having this issue

**Comment by szbm** [comment]
it's working again.

**Comment by haraldox** [comment]
anyone still experiencing this issue?

**Comment by viper949** [comment]
nope

**Comment by adlk** [comment]
We have investigated this issue and it actually was an issue by facebook on _all_ browsers except the latest chrome. As it is already mentioned here, the issue is fixed.
