### ISSUE TITLE
Messenger doesn't load

### ISSUE THREAD

**Issue by ostrovich** [meetfranz/franz#782]
Hi I've downloaded the latest version of Franz everything works right except of messenger which is not loading there is a loading wheel but nothing happens after it. Already tried to refresh it several times, and also restart the application but it still doesn't work

Using MacOS High Sierra 10.13
<img width="1214" alt="2018-03-08 18 23 49" src="https://user-images.githubusercontent.com/37187236/37162425-e4bd711e-22fd-11e8-96db-64db4b88a0a3.png">

**Comment by mauriciodelrio** [comment]
Hi, the service in Ubuntu 16.04 doesn't work too, same message.

**Comment by viper949** [comment]
Same issue started today

**Comment by pezzullig** [comment]
same here, just has a blank screen

**Comment by lophocb6** [comment]
Oh i have way tp fix this

**Comment by lophocb6** [comment]
with win 10. My computer have problem and i back off version old. Pranz run normal
