### ISSUE TITLE
Shutting down Service when laptop hibernates/close lid

### ISSUE THREAD

**Issue by aviputty** [meetfranz/franz#783]
### Expected Behavior

When I close the lid on the laptop, all the franz services shuts down. I have to restart all services within Franz. Franz is still running though. This did not happen with the previous versions of Franz.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

I should be able to continue as is when I go back to my closed laptop. This has not been an issue before and worked properly before.

### Your Environment

* Franz Version used:
* Operating System and version:
I am currently using Version 5.0.0-beta.16 (5.0.0-beta.16.762) on Mac High Sierra version 10.13.3

**Comment by Knackigkurz** [comment]
This occures with my Mac as well. It seems to be a problem of the current Operating System, since I am using the same OS and franz-version.

**Comment by aviputty** [comment]
Is there a way to get to a production version and not a beta version?
