### ISSUE TITLE
If you try to sign into a service like Hipchat or Github that redirects you once you have entered your E-Mail address the screen goes blank and nothing happens anymore

### ISSUE THREAD

**Issue by N0ps32** [meetfranz/franz#784]
### Expected Behavior

Sign-in should work

### Current Behavior

Sign-in doesn't work

### Screenshots (if appropriate):
![screenshot_20180309_204019](https://user-images.githubusercontent.com/8162415/37226450-dfa01e96-23d1-11e8-8018-84526d87d25d.png)

### Steps to Reproduce (for bugs)

1. Launch Franz and try to sign into HipChat, Github or any other service that redirects you to a new page before the login is complete.

### Your Environment

* Franz Version used: 5.0.0-beta.16 (AUR package)
* Operating System and version: Arch Linux

**Comment by N0ps32** [comment]
Update: Tried to update the devtools and also just get an empty window. Maybe this is an issue with Franz not properly supporting my window-manager i3wm?

**Comment by MarioWolters** [comment]
@N0ps32 I am getting the same response when trying to log into Office 365 applications like outlook or teams.
