### ISSUE TITLE
Franz is reloading unexpectedly

### ISSUE THREAD

**Issue by prvashisht** [meetfranz/franz#785]
I'm using a Macbook pro with High Sierra. When using different apps in fullscreen mode, I sitch to some other app from Franz, and then I switch back, Franz reloads. Not any service, but the whole Franz. It's getting very annoying each day as I toggle between different apps frequently and Franz keeps on reloading.

### Steps to Reproduce (for bugs)

1. Open Franz in full screen (I use 9 different services at a time)
2. Open another program (Chrome, Sublime text or whatever) in full screen mode and work on it.
3. After some time, switch back to Franz

### Your Environment

* Franz Version used: 5.0.0-beta.16.762
* Operating System and version: MacOS High Siera

**Comment by arekk** [comment]
+1 - the same for me - identical setup and app version

**Comment by prvashisht** [comment]
I've stopped using Franz and for the time being and am using a chrome window with pinned tabs for this purpose. Might start using again if the problem is fixed.

**Comment by markusduffek** [comment]
+1 same on Windows 10

**Comment by martsie** [comment]
Yep same, sometimes to the point where I have to force quit franz and re-open it ... high CPU usage in this new version too

**Comment by GlennBergmans** [comment]
Using 5.0.0-beta.16 PREMIUM on MacOS and also experiencing unexpected reloads. Using only 5 services, not working full screen. Always happens after waking my laptop, but also happens sometimes ***while using a service***. Fortunately, most services store the message you're typing, so data is not always lost. Extremely annoying nonetheless.

**Comment by haraldox** [comment]
please be aware, that this issue is currently being addressed!

**Comment by Regala** [comment]
Had a similar behavior using one external monitor. The solution was to open Franz on the first (main monitor) otherwise it would always crash.
