### ISSUE TITLE
Ubuntu 17.10 - When I close Franz, it will never open again even if I try to launch program.

### ISSUE THREAD

**Issue by amouratoglou** [meetfranz/franz#786]
When I close Franz by clicking the close program icon on the top left of the UI, the program won't re launch when I click Franz the program.

I'm using Ubuntu 17.10

### Expected Behavior

The program should re-open after being closed.

### Current Behavior

Franz is not launching - loading. 

In order to make it work, I open the terminal and type
```
pkill franz
franz
```
Then it will re-open normally.

But, also there is a error message on the console , this might be a different bug.
```
➜  ~ franz
<memory>:1: Invalid color constant '##d3d3d3'
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `ChromeGtkFrame::frame-color' of type `GdkColor' from rc file value ""##d3d3d3"" of type `gchararray'

```

**Comment by lexielex** [comment]
I have the same issue with Ubuntu 17.10. 

One difference: I don't get the error message on the console when re-opening through the terminal, but I can't close the terminal since this action will kill Franz as well (I get a **Close this terminal?** warning).

**Comment by alecive** [comment]
Do you have the toggle "Keep Franz in background when closing the window" set to ON in settings?

**Comment by amouratoglou** [comment]
Yes. I have that option set to ON.
It seems the program still is running, but never opens again. for example I still get desktop notifications of messages, but when try to run Franz is not working.
Also ALT-TAB keys doesn't display the program icon.

**Comment by alecive** [comment]
@amouratoglou ok so try to turn it OFF (and ideally reboot your computer so that we are sure that you are starting from a blank slate). 

I believe that it is due to that setting specifically. When is ON, the window goes in the background, is still active, but in many Linux DEs it becomes impossible to recover. 

Obviuosly, this is not a solution to the issue, but a good workaround for the time being nonetheless.

**Comment by danieltretanto** [comment]
@amouratoglou did you check whether it is still active at the Unity panel (the top bar is called with indicators and global menus)?

![panel](https://user-images.githubusercontent.com/18460606/39194290-ad14fad4-47dd-11e8-8ce4-df2eed030ad7.png)

**Comment by amouratoglou** [comment]
@danieltretanto  I'm using Ubuntu 17 with Gnome , doesn't have that panel. when I click the program again doesn't open.

**Comment by danieltretanto** [comment]
@amouratoglou it was worth the shot :smile:

**Comment by BarthyB** [comment]
I have the same trouble. Turning "Keep Franz in background when closing the window" successfully ended all processes and I'm able to reopen Franz.

Specs
- Ubuntu Budgie 17.10
- Franz 5.0.0-beta.16

**Comment by amouratoglou** [comment]
a side note: The same happens to me with for example Spotify app... it must
be something in ubutun.

**Comment by lhoggatt17** [comment]
I'm having the same issue (Ubuntu 18.04).  
When I boot, franz 'opens' (ie, it is a process that is running in the background) but the app indicator does not show up in the tray OR anywhere on the screen. Running franz spawns another process that is impossible to access.  
The strange thing is that franz worked the first time I installed it, but now that I've rebooted, even re-installing franz (after deleting every single 'franz' file) doesn't fix the issue. 

Running Franz 5.0.0-beta.18 (903 & 907).

**Comment by jcteo** [comment]
A workaround without restart the computer is killing the process...

On terminal `pkill franz`

then try open it again.

**Comment by JoranDox** [comment]
Same issue, ubuntu 18.04, no tray icon anywhere to click.

Especially annoying since I often think I've got my browser in focus and want to close a tab with ctrl+W, I close franz and need to kill it and then login to half my services again (some of them really don't want to stay logged in).

As a workaround, would I be able to block ctrl+W from closing Franz?

**Comment by rubensa** [comment]
On Ubuntu 18.04 you need to install the [Gnome Shell Extension](https://extensions.gnome.org) [TopIcons plus](https://extensions.gnome.org/extension/1031/topicons/) as Franz seem to be using legacy tray icon instead the more modern app indicator icon (might be related with https://github.com/electron/electron/issues/10427 )
