### ISSUE TITLE
Alfred integration

### ISSUE THREAD

**Issue by vanlooverenkoen** [meetfranz/franz#789]
It would be nice to see alfred integration.

ex: 
Open Slack
Open Messenger
Slack: open a channel
Slack: open a private message

Easy integration could be command line commands. So we can use it in Alfred Workflows.

**Comment by tobiasdueser** [comment]
Hey, I build a simple Alfred workflow for myself that allows to jump to Alfred tabs directly. It works like this: I added an keyword input (e.g. "whatsapp") and connected it to an "Run NSAppleScript" action. The AppleScript opens Franz and presses cmd+1 (1 for the first tab. You have to input the right tab number here). 

Download: [Franz Shortcut.alfredworkflow.zip](https://github.com/meetfranz/franz/files/1807742/Franz.Shortcut.alfredworkflow.zip)

---

I also started working on a workflow that pulls the data form the (inoffical) Franz API (I hope that's ok?!). I got the API-url and the authorization key via the developer tools in Franz. So it's a wonky implementation, but I hope an official API will be released soon. The workflow is based on the helper library by Dean Jackson [Link](http://www.deanishe.net/alfred-workflow/). 

Setup Script: 
1. pull service data from https://api.franzinfra.com/v1/me/services and save it locally 
2. download icons from Franz API (Whatsapp for example: https://api.franzinfra.com/v1/recipes/whatsapp) 

Alfred Trigger: 
1. press "f " and it shows the enabled services: 
![image](https://user-images.githubusercontent.com/1573849/37356396-29b65326-26e6-11e8-8acc-51937a748654.png)
2. Enter and you jump to the appropriate tab in Franz.

Downsides: 
* You can't simple write "whatsapp", you have to use the trigger ("f"). Has anyone an idea if you can implement keyword triggers dynamically in Alfred (like in the simple workflow above)? 
* You have to input the API Key. Currently only attainable via developer tools in Franz. 

Upsides:
* you don't have to build the workflow manuelly 
* up to date services when you execute the setup script 

Feature ideas:
* I'd love to implement the ability to pass a search term to a service, but I'm waiting for this: https://github.com/meetfranz/franz/issues/193. It could work like this: Type "whatsapp Lukas" and it jumps directly to the right conversation. 
* Fuzzy search 

If anyone is interested I could publish the status quo, but actually the code is really messy.

**Comment by vanlooverenkoen** [comment]
Thank you so much. I just added some extra features for my needs. 
Open slack channel, private message from alfred.

[Franz Shortcut.alfredworkflow.zip](https://github.com/meetfranz/franz/files/1810635/Franz.Shortcut.alfredworkflow.zip)

**Comment by dangerousn** [comment]
Hi everyone,
thanks a lot for the great franz/alfred integrations! Did someone of you manage to jump directly to a whatsapp conversation via alfred? E.g. "whatsapp Lukas" to jump directly to the right conversation?
Would love to be able to do that :)

**Comment by KyleAtDND** [comment]
@tobiasdueser I'd love to see what you have so far! kyle at designanddevelop dot io. Are you still working on it?

**Comment by tobiasdueser** [comment]
> E.g. "whatsapp Lukas" to jump directly to the right conversation?
> Would love to be able to do that :)
I would love to do that too, but I haven't found a way to focus the search box in WhatsApp, otherwise it would be doable.

Alfred: "whatsapp lukas"
Process: Open Franz -> Press cmd+X to open WhatsApp -> **focus search box** -> paste "lukas" -> press enter -> done

**Comment by AnthoPakPak** [comment]
@tobiasdueser Thanks for your workflow :) 

By the way, I think you can achieve what you want on WhatsApp by pressing Tab key, which brings focus to search box (in my tests). Hope that can help you :)

**Comment by boettges** [comment]
@tobiasdueser thanks for the workflow! It was easy to modify and works like a charm. 👍

And @AnthoPakPak thank you for the idea with the "tab" key.

My script to search WhatsApp looks like this:
```
on alfred_script(q)

tell application "Franz"
activate
end tell

tell application "System Events"
    keystroke "1" using command down
	delay 0.5
	key code 48		# Tab
end tell

end alfred_script
```

Upon this script it is also possible to manually create shortcuts for most frequented (group-)chats, given that the contact name or group description stays the same.

After the search box in Franz WhatsApp view is focused the name/search string can be passed and the key command sequence "arrow down", "return", "ESC" will close the search results, but leave the text message box of the desired chat focused.

```
	keystroke "group/chat name"
	delay 0.5
	key code 125		# Arrow Down
	key code 36		# Return
	key code 53		# ESC
```
(insert this between `key code 48` and `end tell` and alter "group/chat name" accordingly 👌)
