### ISSUE TITLE
Franz Office 365 Integration

### ISSUE THREAD

**Issue by MarioWolters** [meetfranz/franz#790]
The Franz Outlook Web App Integration is not responding after signing into my Microsoft Account.

### Expected Behavior
When I try to log into Microsoft in the Microsoft Teams Service or Office 365 Outlook Web App I want to be redirected from Franz to my Teams Site or Outlook Web app, as Franz does when logging into other services like Xing or LinkedIn. 

### Current Behavior
When trying to log into my Microsoft Account via Franz it just gives me a white space, without any further options. When I reload, the same thing happens. 

### Screenshots (if appropriate):
<img width="1440" alt="bildschirmfoto 2018-03-12 um 13 20 48" src="https://user-images.githubusercontent.com/37296596/37283452-51c3f02e-25f8-11e8-8c78-83ab871e66bf.png">
<img width="1440" alt="bildschirmfoto 2018-03-12 um 13 20 57" src="https://user-images.githubusercontent.com/37296596/37283453-51e1bca8-25f8-11e8-8445-71fa04d07158.png">
<img width="1440" alt="bildschirmfoto 2018-03-12 um 13 21 01" src="https://user-images.githubusercontent.com/37296596/37283454-51ffcc84-25f8-11e8-9ceb-31fb2d1ddc95.png">

### Possible Solution
?

### Steps to Reproduce (for bugs)
1. Add Microsoft Teams or Office 365 as your service in Franz
2. Log in with a company account
3. Nothing happens than white screen, when reloading the same thing happens

### Your Environment
- Franz Version 5.0.0
- Mac OSHigh Sierra 10.13.03
- Office 365 company account

**Comment by DwiPriyatmoko** [comment]
Hello, I have the similar question. I can login to my outlook mail and Microsoft team, but when I quit the app and then turn back on I've to log in again and write my pass and email. Can it just automatically once only?

**Comment by ericpoe** [comment]
I get similar with High Sierra 10.13.4, Franz 5.0.0-beta.18.903, Microsoft Teams. I can get the screen that asks for my email address, then I get a 401 error (according to dev tools) when it redirects to my org's SSO for O365.

Works in Ubuntu 18.04.

**Comment by nBuga** [comment]
Same problem here. After I logging in, it shows me a white page and nothing happens. If I restart Franz, I have to login again, it doesn't keep me logged.

**Comment by ronivay** [comment]
Same problem here. Slack ADFS login ends up to 401 with OSX High Sierra 10.13.4. Works fine on Windows 10. 5.0.0-beta.16 on both.

**Comment by gaspo53** [comment]
Yes, same problem here. After a success login, I have this (the same happens with other products like Franz, i.e. Station):

<img width="816" alt="image" src="https://user-images.githubusercontent.com/2250227/41549000-dfce2444-72fa-11e8-8eb4-ff419a6c6e00.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/2250227/41549008-e488a52c-72fa-11e8-8755-db800746602e.png">

**Comment by stidch** [comment]
Same problem here on **macOS High Sierra 10.13.5** and **Franz 5.0.0-beta.18** with services `Office 365 Outlook Web App` and `Microsoft Teams`.

**Comment by ettore-cerulli** [comment]
Same problem with macOS Mojave 10.14 Beta (18A293u) and Franz 5.0.0-beta.18 (5.0.0-beta.18.903) with the Office 365 Outlook Web App service.

**Comment by Axxeption** [comment]
same troubles here with Windows 10 and franz 5.0.0-beta.18, please fix this

**Comment by stidch** [comment]
Unfortunately I could not get that running on my Mac, so I've decided to switch to https://rambox.pro. With this alternative application it works without issues.

**Comment by nortimer** [comment]
same problem with ms teams. Franz 5.0.0-beta.22 and MacOS 10.14.2

**Comment by akoebbe** [comment]
FWIW if I'm not in my office (i.e. not on my company LAN) it works and when I go into the office, it will stay logged in just fine. If I have to restart Franz or it crashes and wants to re-login to Teams, it will fail again. So, for me, it only fails to get to the login screen when I'm on my company LAN.

**Comment by benjoz** [comment]
Same problem with macOS Mojave 10.14.2 with the Office 365 Outlook Web App service.

**Comment by stidch** [comment]
Look related to issue #253.

**Comment by akoebbe** [comment]
That one sounds different than this one. #253 seems to be a display/render issue and deals with Linux.

**Comment by mdahiemstra** [comment]
any ETA for a fix? The only service I am missing and forcing me to use webmail, ugghh
