### ISSUE TITLE
I am done with Franz

### ISSUE THREAD

**Issue by benameless** [meetfranz/franz#791]
I tried it, I liked it, id started not to work properly, I reinstalled it, it kept on not working, i deleted it. Nice try, let me know when it actually works.

**Comment by henrebotha** [comment]
If you cared about this working, you'd share what actually bothers you.

**Comment by benameless** [comment]
I did, got no answer. And I am sick of forums, where developers outsource the support. I would rather pay 20 or more dollars and have a working product and support if it doesn’t. No offense.

**Comment by N0ps32** [comment]
I totally agree with you. ATM the software is a dumpsterfire and the developer is not addressing any of the issues on Github. Yet he keeps sending E-Mails asking for donations.

Maybe people would donate if the software actually works. It takes 5 minutes of real world testing to see that this was never properly tested by anyone.

@henrebotha 
https://github.com/meetfranz/franz/issues/784
https://github.com/meetfranz/franz/issues/790
https://github.com/meetfranz/franz/issues/786

And in addition to that the software sometimes freezes when I switch back to it from another workspace and has to be killed.

10/10 piece of software. Can't see why people would complain if it even cannot properly do the single thing it was designed to do.

**Comment by henrebotha** [comment]
> ATM the software is a dumpsterfire and the developer is not addressing any of the issues on Github.

Every new update addresses issues I've experienced.

> Maybe people would donate if the software actually works.

The software does actually work, which I know because I've been using it since pre-v5 for multiple services including work IM.

**Comment by N0ps32** [comment]
> The software does actually work, which I know because I've been using it since pre-v5 for multiple services including work IM.

Out of 6 services I added to Franz a grand total of 2 work. I would not call that having a working product.

- HipChat: Sign in not possible
- Google calendar: Sign in not possible
- Github: Sign in not possible
- Google Keep: Sign in not possible

**Comment by henrebotha** [comment]
I just successfully signed in to Google Calendar, Google Keep, and Github. I don't have a HipChat account so not going to try it. 

I'm sure you experience bugs. I'm saying that pretending this app is broken everywhere for everyone at all times is ridiculous.

**Comment by N0ps32** [comment]
> I'm sure you experience bugs. I'm saying that pretending this app is broken everywhere for everyone at all times is ridiculous.

I never said it was broken for everyone, I said it was broken for me and some other people. If it works for you then congratz. For me it doesn't work.

The fact that OP created this issue is proof enough that it in fact doesn't work for some people.

What platform are you running on? I'm pretty sure that it'll also be broken for you if you're running it on Linux with i3wm.

**Comment by alecive** [comment]
@henrebotha I personally love Franz, I am happy with it and I use it everyday on multiple platforms. But that is only because I managed to work around all the issues I had! But all the complaints that @N0ps32 has are more than legitimate.

In general, I believe that this project has become much bigger to maintain than what two people can do in their time.

**Comment by mikedett91** [comment]
I use the app daily using pulse, messenger, gmail, ms teams, and recently added github. It works for everything I use it for pretty flawlessly. While I am not saying it is perfect but this application works  quite well for what its aim is and it is unjust to claim it is broken or a dumpster fire. 

As a proof of this, I am using Franz to write and submit this comment :)

**Comment by henrebotha** [comment]
@alecive I can agree with that, but luckily it's open source and anyone can contribute.

**Comment by adlk** [comment]
I can totally understand that some people are frustrated with Franz as some parts might not always work as excepted on certain platforms or various service configurations. 

We are constantly working on improving Franz. But please understand that we have very limited resources as we are still just two guys with an evergrowing list of tasks and bugs to tackle. We do what we can and we even get better every day – even though it doesn't seem like it for some users.

On top, we are also aware that there are some 3rd party services in Franz that are actively limiting the experience of our users with Franz. This is a major issue for us which we don't have solution for yet.

---
 
Please understand that I'm going to lock this issue in 24 hours.
