### ISSUE TITLE
Slack: cannot copy images from right-click context menu

### ISSUE THREAD

**Issue by henrebotha** [meetfranz/franz#792]
### Expected Behavior
Clicking "copy image" on the right-click context menu on a full-screen image copies the image to the OS pasteboard.

### Current Behavior
Clicking "copy image" on the right-click context menu on a full-screen image does not copy anything to the OS pasteboard. 

### Steps to Reproduce
1. Open any Slack service and find an image post.
2. Click the image once to make it fill the Slack window.
3. Right-click the image.
4. Click "copy image".

### Context
I keep trying to share images from Slack to my family on Whatsapp, but no luck.

### Your Environment
* Franz Version used: 5.0.0-beta.16.762
* Operating System and version: macOS 10.13.3

---

Note that this bug does not exist in Whatsapp, nor does it exist using the Slack web client in Chrome.

**Comment by djbotha** [comment]
This is not an issue with Slack specifically, it's an issue with all services I've used in Franz. I'm running Slack, Whatsapp Web and Discord, and it works on neither of them. 

- Franz Version: 5.0.0-beta.16
- Operating System(s): macOS 10.13.3 (17D47)

**Comment by 4ekki** [comment]
This one is crucial.

**Comment by henrebotha** [comment]
It seems copying breaks entirely sometimes. I have to restart Franz to restore copy functionality.

**Comment by cransono** [comment]
I would really like this functionality.
