### ISSUE TITLE
Slack - can't share files from google drive

### ISSUE THREAD

**Issue by NicRC** [meetfranz/franz#796]
Hi, I use Slack to work and share files.
And i have a problem, i hope we can solve this together (sorry for my english i'm from chile)

### Expected Behavior

To share files from Drive, I click on the + to the left, select share from drive, then I select the file and the message should appear.
"You have shared the X file"

### Current Behavior

When I want to share a document from my drive, the pop-up window appears, I select the file, the pop-up window closes but the file is not linked or appears.

I tried the button from Slack web and the slack application and if it works there.
It would be very useful to better integrate everything in franz.

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/35184346/37367782-2079b7c4-26e3-11e8-9696-443eb03eb8db.png)

and then

![image](https://user-images.githubusercontent.com/35184346/37367863-5a6089cc-26e3-11e8-8163-0a2e924f4514.png)

Finally Nothing (the file share in the back was made by using the Slack App for windows)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Context

i was trying to share a file to work with my mates, the fast solution was open google drive and paste the link.

### Your Environment

* Franz Version used: 5
* Operating System and version: Windows 7 64 bits

**Comment by yasn77** [comment]
I am having the same issue running in Arch Linux, so not only Windows.

**Comment by webberwang** [comment]
Same here for OSX

**Comment by mdifranc** [comment]
Same here for maxOS

**Comment by john-st** [comment]
Hi there, April 2020 now, and I’m having this issue still. Is everyone still experiencing this as well?

**Comment by NicRC** [comment]
Yes, I'm trying to attach a file in the chat from mi Google drive and show error.

Maybe it's beacuase I use slack in Franz or web app,
________________________________

**Comment by john-st** [comment]
Web app works, seems to be a Franz service issue

John

Sent from my mobile.
Springtime Design

Mobile: +31 6 51339659
Skype: johnkock2009
WeChat: johnkock

**Comment by Elegroth** [comment]
I am experiencing this issue as well.  I'm surprised this issue hasn't been worked on at all yet.

**Comment by swvanderlaan** [comment]
Yes! Same here. 

```
Sorry, I can't import folders from Google Drive.
```
