### ISSUE TITLE
can we get access to chrome://flags? 

### ISSUE THREAD

**Issue by benswolo** [meetfranz/franz#797]
I'm on windows 10, version 5. Is there a way to turn off the smooth scrolling? I know that Franz is just Chromium with a nice wrapper, but it would be great to turn off smooth scrolling.

**Comment by tjtolon** [comment]
Other perspective for this issue is that on Linux smooth scrolling seems to be off, and I would prefer to have it on there. Access to chrome://flags would be really ideal, but at least toggle for smooth scroll would be nice.

**Comment by oetiker** [comment]
access to chrome flags would be really nice

**Comment by arnabwahid** [comment]
+1
