### ISSUE TITLE
System hang every 5 seconds

### ISSUE THREAD

**Issue by andbad** [meetfranz/franz#801]
Using Franz 5.0.16 beta on Ubuntu 16.04.

### Expected Behavior
The system continue to works normally when Franz update the its services.

### Current Behavior
The system stops responding every 5 seconds for around 1 second.
Then the systray icon of Franz blink and the system resumes to works normally.

### Possible Solution
I must use old legacy version 4.0.4.

### Steps to Reproduce (for bugs)
1. Install Franz 5.0.0-beta.16 (beta) (.deb version) on Ubuntu 16.04
2. Enable WhastApp, Telegram and Slack services
3. Launch some application to make clear any interruptions (like YouTube videos, as example).

### Context
See above

### Your Environment
* Franz Version used: 5.0.0-beta.16 (beta)
* Operating System and version: Ubuntu 16.04

**Comment by adlk** [comment]
We had a rather resource heavy app-to-service process all 5 seconds to share information that also generated debug output in all services which caused the lag. 

This issue is now fixed and will be shipped next week.
