### ISSUE TITLE
Franz 5.0.0-beta.16 blue screen in message area

### ISSUE THREAD

**Issue by vastra** [meetfranz/franz#807]
Program locks up and requires restart to work again, message area goes completely blue on Windows 7 Pro 64bit.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/5039179/37643392-04a11a06-2c29-11e8-9bd1-a59b739a1ac2.png)

**Comment by abdiprawira** [comment]
same problem here, but i use Kali Rolling OS , help me

**Comment by cyan** [comment]
same here  but i dont have the top bar on windows10
