### ISSUE TITLE
Can not navigate slack history by hotkey

### ISSUE THREAD

**Issue by AndyHoang** [meetfranz/franz#809]
### Expected Behavior
In any slack service, try navigate history using hotkey (CMD + [, CMD + ])
Channel can be navigated back and forth

### Current Behavior
In any slack service, try navigate history using hotkey (CMD + [, CMD + ])
Channel can not be navigated back and forth

### Steps to Reproduce (for bugs)

1. Open a slack channel (service)
2. select back and forth some channels
3. Use hotkey to navigate channel history 
4. Nothing changed

### Your Environment

* Franz Version used: Version 5.0.0-beta.16 (5.0.0-beta.16.762)
* Operating System and version: Macos Sirrea 10.12.6 (16G1212)

**Comment by nsrosenqvist** [comment]
Many keyboard shortcuts are not working with the Slack integration. Common ones that are frustratingly not registering are CTRL/CMD+T to switch between conversations and CTRL/CMD+F that is intercepted by Franz to go into fullscreen mode. Why not just using f11 for that?

**Comment by AndyHoang** [comment]
Thanks, didn't know that f11

**Comment by suxstellino** [comment]
Hi guys, what about the history (prev/next channel or DM) navigation? Why is this issue close @AndyHoang?

**Comment by AndyHoang** [comment]
@suxstellino since its the limitation, so I think there're nothing we can do. So I closed this

**Comment by peabnuts123** [comment]
I don't see any reason why this can't be fixed. Perhaps I should raise a separate issue?
