### ISSUE TITLE
Downloading attachments error

### ISSUE THREAD

**Issue by mvc3131** [meetfranz/franz#81]
The attachments downloaded on Sierra 10.12.6 are saved without the file extension thus making them unable to use.

### Expected Behavior
Previously, If I download a file, **Document1.pdf** it would directly download the file along with the extension. And that would directly open with my default application. 

### Current Behavior
It is downloading **Document1**. It is an unspecified extension so, No application can open the file. 

### Your Environment
Macbook Pro - 15" Retina. 
Franz-5.0.0-beta.10
macOS Sierra
Version: 10.12.6

**Comment by haraldox** [comment]
downloading attachments (.pdf, .doc, .xlsx)  in Gmail works as expected for latest Franz version 5.0.0-beta.15 ... anyone else besides @metaregistrar experiencing this issue?

**Comment by haraldox** [comment]
closing this for now, feel free to reopen with any questions or comments!
