### ISSUE TITLE
Feature Request - password to open Franz

### ISSUE THREAD

**Issue by grberk** [meetfranz/franz#810]
Can Franz be set to require a password to open it? I've used similar apps, and a few others have security settings that can be configured to require a password when it first launches at Windows startup.

**Comment by joshferrell** [comment]
This would be useful for people who have chats for work that need to be secure. 

I think this would be great to attach to user profiles so you could mark a profile as "secure" and other profiles would not be affected.

**Comment by grberk** [comment]
That would work as well! :-)

**Comment by alecive** [comment]
I think it would be just a matter of having an option in the settings that asks to login every time you open franz. It shouldn't be very complicated!

**Comment by SitoriTenshi** [comment]
I actually prefer Franz but currently use Rambox only because they have the password protection feature to open it. If Franz had the password security to open it I would switch back

**Comment by iagocaldeira** [comment]
As @SitoriTenshi, I am using Rambox only to secure it on startup.

**Comment by haroldogtf** [comment]
This feature would be interesting when the user puts the computer to sleep or after some inactivity time.

**Comment by parahall** [comment]
Follow!

**Comment by scwall** [comment]
I am super interested in this option too, I subcontract with a store and I use franz for more speed. I am always forced to log out so that people can't see my messages

**Comment by novama** [comment]
I'm really interested in this feature. It's been a year, no mentions or anything was added on this.
I renewed for the second year my Frank account, however I'm afraid this app is not going to stand one more year. 
The development of a improved product seems practically stopped, which is really bad because it has a lot of potential.

**Comment by rberio** [comment]
As 3 years later and this feature still didn't show up, I I'll look for another solution e probably leaving Franz today. Really need another security layer to use Whatsapp to work.
