### ISSUE TITLE
Franz Won't Open With Most Recent Update

### ISSUE THREAD

**Issue by dcendum** [meetfranz/franz#811]
Cannot open Franz on Windows Desktop as of today's recent update. I tried to restart, open different ways (including run as admin) and it just won't open. 

* Franz Version used: newest version (update today)
* Operating System and version: Windows 10 Pro - 1709

**Comment by haraldox** [comment]
@dcendum Pleased try reinstalling Franz from the homepage...

**Comment by jaycaetano** [comment]
Have same issue on Windows 10.  with franz 5.0-beta 18.  And try reinatalling Franz from website homepage still not opening. I noticed on Task manager two process running for Franz. I have tried to uninstall and reinstall, tried running CCleaner, and killed the process running for Franz but as if beta 18 cannot run on Windows 10. 
![capture](https://user-images.githubusercontent.com/5280508/38648480-61e6fbca-3dbf-11e8-9828-85caa23d3daf.PNG)

**Comment by esovan** [comment]
i have the same problem

**Comment by iONinja** [comment]
Exactly same problem here.

**Comment by iONinja** [comment]
@dcendum @jaycaetano I rolled back to 5.0.0-beta.17 which is working.

**Comment by GrantaLisa** [comment]
Same problem here, when upgrading from 5.0.0 Beta 24 to 5.0.1 full - Have had to roll back to the beta.

**Comment by TheWitcher92** [comment]
Same issue here. Running background processes but not the actual app

**Comment by msommerx** [comment]
Same problem here... franz 5.1.0

**Comment by MathiasRenner** [comment]
Same here with franz 5.1.0

**Comment by tecnux** [comment]
Same here with franz 5.1.0

**Comment by apwnapwn** [comment]
Samr

> 
> 
> @dcendum @jaycaetano I rolled back to 5.0.0-beta.17 which is working. Link: https://github.com/meetfranz/franz/releases/tag/v5.0.0-beta.17

Thanks, that solved it for me too !

**Comment by djowinz** [comment]
Had the same issue steps I performed to fix.

- Kill all Franz task
- Uninstall Franz entirely
- Delete everything under ~/AppData/Roaming/Franz and ~/AppData/Local/franz-updater.
- Reinstall
- Relaunch

These steps resolved the issues for me. Something must be stored in Roaming folder that we specific users have set that didn't translate well through the newer version(s).

**Comment by apwnapwn** [comment]
> 
> 
> Had the same issue steps I performed to fix.
> 
>     * Kill all Franz task
> 
>     * Uninstall Franz entirely
> 
>     * Delete everything under ~/AppData/Roaming/Franz and ~/AppData/Local/franz-updater.
> 
>     * Reinstall
> 
>     * Relaunch
> 
> 
> These steps resolved the issues for me. Something must be stored in Roaming folder that we specific users have set that didn't translate well through the newer version(s).

Thank you ! I can confirm this has solved it for me :) I've been running the old beta for 2 months now, thanks for solving this !

**Comment by TheWitcher92** [comment]
> Had the same issue steps I performed to fix.
> 
> * Kill all Franz task
> * Uninstall Franz entirely
> * Delete everything under ~/AppData/Roaming/Franz and ~/AppData/Local/franz-updater.
> * Reinstall
> * Relaunch
> 
> These steps resolved the issues for me. Something must be stored in Roaming folder that we specific users have set that didn't translate well through the newer version(s).

Thanks! This fixed it for me. The newest version is running (tested after restart etc.)

**Comment by bountin** [comment]
See https://github.com/meetfranz/franz/issues/1404#issuecomment-537591242 for an easier and less intrusive way to repair the broken Application Data.
