### ISSUE TITLE
Unpacked Windows version of Franz

### ISSUE THREAD

**Issue by Ash258** [meetfranz/franz#813]
Provide more windows installers. 

```yml
electron-builder.yml
---
win:
  target:
    -target: nsis
    -target: zip
```

### Motivation and Context

OneClick installer is nice, but lots of people don't want to install in C drive or cannot due to some AD restrictions (viz: #534). You could easily provide zip version of Franz or Installer which allow set directory (`allowToChangeInstallationDirectory` for nsis)

There is no need to install Franz inside `%AppData%` or install Franz at all, when you can just unzip it or specify location.

**Comment by karl-ricken** [comment]
I think this idea is also very good and I need a version that is not installed, but only unpacked and started.
