### ISSUE TITLE
Franz doesnt recognize clicks from Wacom Graphic Tablet anymore

### ISSUE THREAD

**Issue by ElaineThreepwood** [meetfranz/franz#815]
### Expected Behavior
Up until the current update (version 5 beta 17) I was able to use Franz with my Graphic Tablet from wacom. I use the Tablet as a mouse alternative and it works with all kinds of software (Office, Firefox, Adobe programs, skype, spotify, etc). 
Before the update I was able to click and scroll also in Franz with my Tablet.
I been using Franz since 2016, never had an issue with the tablet.

### Current Behavior

With the current update Franz doesnt recognize the Tablet as an input source anymore. I cant click or scroll unless I use the integrated touchpad of my laptop. So Franz recognized the clicks/inputs from other mouse-device, but not from the tablet. 

### Steps to Reproduce (for bugs)

1. Connect a graphic tablet and use the stylus for mouse movements + inputs.
2. Run Franz. 
3. Try to switch inbetween chats or services. 

### Context

I am unable to click on the different chats, so with the current version I am totally unable to use Franz anymore.
I have now downgraded to a former version. 

### Environment
* Franz Version used: Version 5.0.0- beta17
* Operating System and version: Windows 8.1 Enterprise 
* Tablet: Wacom Bamboo Fun, Driver: 5.3.5-3

**Comment by basvanbergen** [comment]
I've got the same problem... but on osx and with an intuos 4, tried different Wacom drivers, all have the same issue.

**Comment by Gertsch** [comment]
Same here, Win10 - Wacom Intuos Pro M
