### ISSUE TITLE
CLI/API for focus mode

### ISSUE THREAD

**Issue by machinekoder** [meetfranz/franz#818]
### Feature Description

It would be great to have an API or CLI interface to enable something like a *focus mode*. With *focus mode* I mean disabling all notifications, set the status to aways/busy and whatever else is necessary to guarantee undisturbed working.

### Motivation and Context

Notifications disturb deep workers focus. With a CLI or API, we could integrate Franz into our personal focus mode scripts.

### Mockups, Screenshots (if available):

```bash
franz --focus-mode on
franz --focus-mode off
```

**Comment by alecive** [comment]
Ideally, it would be great to have a cli API for a variety of different things, not only focus mode!
