### ISSUE TITLE
Copying and pasting doesn't work during signup on Mac

### ISSUE THREAD

**Issue by tbodt** [meetfranz/franz#819]
### Expected Behavior
It should be possible to paste into the signup form.

### Current Behavior
It is not (at least on mac).

### Possible Solution
It's quite possible this is because the menubar is empty during signup, and the copy and paste items need to be in the menu for copying and pasting to work.

### Steps to Reproduce (for bugs)
1. Download and open Franz on a mac
2. Try to paste into the signup form

### Context
I can't sign up for Franz using a password from my password manager.

### Your Environment

* Franz Version used: Latest from the website, no idea what version because there's no about box as far as I can tell.
* Operating System and version: macOS 10.12.6

**Comment by jmenzler** [comment]
Same problem for the login form: I do have 50-character-passwords – not being able to copy and paste is horror.

**Comment by sushinger** [comment]
Same problem here with macOS 10.11 El Capitan … Since I always use a long strong password stored in my Password-Manager (1Password), this really keeps me sticking with Rambox-Multi-Messenger …

**Comment by eddiezane** [comment]
Appears this and #828 are related/duplicates. Issue is present in both signup and login screens.

I tested on master locally and copy/pasta works fine in dev mode but building the app (`npm run build`) makes the issue reproducible.

**Comment by chenasraf** [comment]
This is really bad, I have a generated password, typing it is horrible

**Comment by ypxio** [comment]
same here, all my password has been generated by password manager app. typing it manually doesn't make sense to me

**Comment by dinamic** [comment]
+1 on this. It makes no sense to me not to be able to paste in the generated 32+ character password.

**Comment by dinamic** [comment]
ping @adlk

**Comment by RicardoCapricciosa** [comment]
This literally breaks the app for me, I'm unable to login (unless of course I type in my 60char generated password manually, which I won't do. So I really hope this'll be fixed soon.

**Comment by silvenon** [comment]
@dinamic it didn't help. Do I execute it by chmoding and running `./paste.py`?

**Comment by dinamic** [comment]
@silvenon, you can run it via `python3 paste.py` or you can also make it executable `chmod +x paste.py` and execute it via `./paste.py` afterwards.

**Comment by dinamic** [comment]
ping @adlk
