### ISSUE TITLE
Franz does a complete reload every now and then

### ISSUE THREAD

**Issue by scotty-p** [meetfranz/franz#820]
Will be either using a tab in Franz or focused on another window and the blue loading screen will come up. All services are reloaded. 

### Expected Behavior
Franz should only reload when I select View > Reload Franz

### Current Behavior
Franz reloads on its own at random intervals

### Context
Actively using Franz or working in another application. I have 12 services in Franz

### Your Environment
* Franz Version used: 5.0.0-beta.16.762
* Operating System and version: macOS 10.13.3

**Comment by doulosyap** [comment]
I'm facing a similar problem.

My current behaviour is erratic - on startup, apparently when trying to load the WhatsApp service, Franz will restart in a loop. I have to quite Franz and restart it several times before the problem goes away, but eventually the problem will appear again without any specific input from me.

I run 4 services in Franz - WhatsApp, FB Messenger, Slack (1 account), Telegram

Franz version 5.0.0-beta.16 (5.0.0-beta.16.762)
macOS 10.13.3 (17D102)
