### ISSUE TITLE
Keep on getting audio notifications although they are turned off for each service and in general in Franz

### ISSUE THREAD

**Issue by alinabos** [meetfranz/franz#822]
I don't want to receive any audio notifications. So I turned off the audio notifications in general 
![image](https://user-images.githubusercontent.com/12828578/37766991-f3df30d0-2dc8-11e8-84a1-b8c602d8441f.png)

and also the audio notification for the service
![image](https://user-images.githubusercontent.com/12828578/37767052-1972aa16-2dc9-11e8-9294-527c072fddd2.png)

I am still getting the audio notification when I am receiving a message.

### My Environment
* Franz Version used: 5.0.0-beta.17
* Operating System and version: Windows 10 Home (64 Bit)

**Comment by bennniii** [comment]
i can confirm this bug when using an external soundcard (in my case, an apogee duet).
notifications are disabled but still audible. 

would love to see a fix for this! 

- Franz Version: 5.0.0-beta.22.1059
- OS: maxOS High Sierra 10.13.6
