### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by mrjcleaver** [meetfranz/franz#824]
### Feature Description
As a user that has lots of things in Franz, I want to be able to use Alt-tab to cycle between them and a way to see the separate applications in different windows.

### Motivation and Context
It can be hard to remember that an app is in Franz
It can be hard to find the app in Franz

Thanks, Martin.

**Comment by corrado-petrelli** [comment]
For switching the services you can use CTRL+number
![image](https://user-images.githubusercontent.com/36475130/37782758-00e01a8a-2df4-11e8-90e2-3430568eebf2.png)

**Comment by alecive** [comment]
Also, you can also cycle them with "Ctrl+PgDwn" or "Ctrl+PgUp" .

I suggest to close this.

**Comment by mrjcleaver** [comment]
I'd like multiple windows, not just to be able to switch between 10 tabs in
the same window.

Please leave it open.

**Comment by alecive** [comment]
@mrjcleaver I have no power here, so my suggestions are kind of useless anyway :sunglasses: 

But then if you need multiple windows, just open multiple chrome or firefox windows. Franz is exactly having the opposite philosophy, that is to *aggregate* all of your services into a single window.

**Comment by seanpk** [comment]
I would also like this feature - it isn't that we can't switch between services, its that sometimes it helps to see a few services on your screen at once.

**Comment by Splitframe** [comment]
I'd also like to either be able to open multiple instances of Franz at the same time or have at least a 2x1, 2x1 and 2x2 grid structure. I love that I have all logins at one place, that all log in at the same time when Franz starts, but if I want to have Gmail and WhatsApp open at the same time to monitor whats going on I always have to switch between tabs.

Bonus points for a reactive design that automatically changes in multi-tab view once a certain threshold of window size is reached. All configurable in the settings.

**Comment by TheCedarPrince** [comment]
I completely agree with @Splitframe - it would be ideal for me to have my calendar and my different email clients in different windows side-by-side in a grid-like format.

**Comment by zootie** [comment]
To me, the idea of multiple windows is to be able to view on screen more than one chat at a time (like when you're copying information from one chat into another, or chatting with multiple people in different services at the same time - ideally, also on the same service, have 2 chats open at the same time, but I understand that Franz architecture might not support that). You don't want to be switching back and forth when you can have both visible or a click away.

It can either be by having multiple Windows (each with all the services - so it might be difficult to implement w/o re-instantiating all services), or being able to selectively move services to another window, like tabs on a typical browser (Opera, Chrome, etc). You can D&D a tab to another existing browser window, or you can drop it in an empty space and instantiate a new window. You could D&D a service and drop it outside Franz to instantiate a new Window, or you could right click on a service and have an option to "Open in New Window". 

The idea is also that you already have the service(s) running on Franz. Don't want to open another browser instance to connect to the service and relogin just to have it side by side with Franz for a few minutes.

**Comment by jcalvillo** [comment]
Use case for allowing at least two concurrent open windows:

Currently, if you need to consult something in **keep** or **standard notes** while on a skype call -- your call will drop. That is, it's impossible to look at your notes while you're on a call because Franz will drop the call as soon as you move to another service (you can't open up a skype call and stay on the call while viewing other services).

**Comment by fquinner** [comment]
Would be very useful for things like switching between workspaces too. One workspace on one virtual desktop for work in one window, another for personal. Or client A in one and client B in another.

**Comment by iarigby** [comment]
I also have separate virtual desktops for each work. I need 3-4 workspaces in franz, each with different services and now I have to keep dragging the window and switching between workspaces and desktops which is very inconvenient.
