### ISSUE TITLE
Franz is blocked in full screen

### ISSUE THREAD

**Issue by Armalyca** [meetfranz/franz#825]
When I open Franz, it will always open in full screen and I can't reduce it, and when I click on the button to reduce the window, it doesn't work.

### Expected Behavior

I should be able to reduce Franz window how I want

### Current Behavior

I can't reduce Franz window, and when I click on the button to reduce the window, it doesn't work.

### Context

I like to put 2 windows on my screen but I can't because of this issue and I use Franz for a lop of app , so it is really slowing me in my work.

### Your Environment

* Franz Version used: 5.0.0-beta.17
* Operating System and version: windows 10

**Comment by nokeechia** [comment]
I have this issue too

**Comment by adlk** [comment]
As a quick fix, 
- Quit Franz
- Go to `%APPDATA%\Franz`
- Delete the window-state.json

We are going to add fullscreen controls with the next update.

**Comment by nokeechia** [comment]
Worked for , me. Thank you!

**Comment by Armalyca** [comment]
It worked for me too, thank you !!

**Comment by bittner** [comment]
Note that you can press `Ctrl`+`F` to exit (and re-enter) fullscreen.

I would suggest, though, to change the key binding to `Ctrl`+`Shift`+`F` (and optionally `F11`, maybe).

Why? Because `Ctrl`+`F` is typically used for "Edit > Find ..." (i.e. Search). "Full Screen", on the other hand, is more typically activated via `Ctrl`+`Shift`+`F` (Slack client, and others) and `F11` (Firefox, Chromium).

**Comment by bittner** [comment]
Just noted that using `<Ctrl>`+`<F>` makes it impossible to search for text in Gmail. I regularly do this for finding an email (by subject) quickly. The Franz window activates/deactivates full-screen instead.

Oh, "Find ..." wouldn't be available anyway. :unamused:

**Comment by jpinetta** [comment]
Thank you so much!

**Comment by AhmedMSalem** [comment]
Now you can press F11 only for exit and enter full screen

**Comment by tsusanka** [comment]
Ctrl + F worked for me

**Comment by BlueJaySkillClix** [comment]
Deleting window-state.json worked for me.

**Comment by ricardobossan** [comment]
> As a quick fix,
> 
> * Quit Franz
> * Go to `%APPDATA%\Franz`
> * Delete the `window-state.json`
> 
> We are going to add fullscreen controls with the next update.

This solved it for me too! Thanks!!!

**Comment by RomanTheLegend** [comment]
On that note, it would've been great to show windows menu on Alt press - just like in any other app. I had hard times getting out until I found this post. And F11 was not a shortcut that came to my mind (although I admit it should've :) )

**Comment by derekmhewitt** [comment]
Found this post with a quick google search, and F11 worked for me.  Are fullscreen controls still not implemented?  It seems like they are missing :(.

**Comment by juli0mendes** [comment]
F11 works on windows 10

**Comment by VDiabloV** [comment]
lol 2 years and still a problem
