### ISSUE TITLE
CMD + V not working on Sign up screen

### ISSUE THREAD

**Issue by dominikconrads** [meetfranz/franz#828]
Cannot paste my generated password (or any text) from my password manager into the Sign up screen.

### Expected Behavior
User should be able to paste text, like in every other program, website, app.

### Current Behavior
CMD + V is not working.

### Your Environment
* Franz Version used: 5.0.0-beta17
* Operating System and version: macOS High Sierra 10.13.3

**Comment by AntonBcolumbus** [comment]
CMD + C does not work as well. Common case, I guess.
