### ISSUE TITLE
[Feature Request] Minimize to taskbar and close to tray

### ISSUE THREAD

**Issue by VarunAgw** [meetfranz/franz#829]
Most of the good applications including Skype provide this behavior.

**Comment by adlk** [comment]
Already available, please check your settings page. 
<img width="911" alt="bildschirmfoto 2018-03-26 um 11 14 40" src="https://user-images.githubusercontent.com/3265004/37897638-e9c98156-30e6-11e8-9b80-f28c72e9bc35.png">

**Comment by VarunAgw** [comment]
`Keep Franz in background` doesn't work as intended. If I check it, it will still keep showing up in taskbar on pressing close button. If I uncheck it, it will just quit

**Comment by VarunAgw** [comment]
@adlk ^
