### ISSUE TITLE
Cannot uninstall Franz

### ISSUE THREAD

**Issue by rayoen69** [meetfranz/franz#83]
Hello everyone!

I had a problem with Franz. When I tried ininstalling Franz after using it for a little while, but when I tried, Windows said that there was a problem with the uninstallation of the program and that the app was maybe uninstalled already. 
But the app is still installed on my computer. I closed the app completely before uninstalling, but it still does the same thing.  
Can you guys help me uninstall the app? I find it very annoying because i have to close the app whenever i start my computer and if I don't, it makes these noises when I'm receiving a message.

Thank you!

* Franz Version used: 4.0.4 build 40 release:1.3.1
* Operating System and version: Windows 10.0.15063

**Comment by adlk** [comment]
This repository is for Franz 5 and later.

---

To resolve your issue, have you already removed all files from `C:\Program Files (x86)\Franz and ``%appdata%/Franz/`?
