### ISSUE TITLE
Slack shows only white page

### ISSUE THREAD

**Issue by MPW1412** [meetfranz/franz#831]
The service Slack doesn't work at all. Despite serveral reload with Ctrl + R the page stays completely white and I can't enter my login credentials.

### Expected Behavior
After enabling the service Slack in Franz, I'd expect a page to be displayed, where I can enter my login credentials.

### Current Behavior
Page stays white.

### Steps to Reproduce (for bugs)
1. Ubuntu 16.04 + Franz beta5-17
2. Enable Slack
3. Try to login -> won't work

### Your Environment
* Franz Version used: beta5-17
* Operating System and version: Ubuntu 16.04.3 64 bit

Thanks for reading.

Regards,
Matthias

**Comment by sinedied** [comment]
Same here, on OSX High Sierra, same beta version.

I can see the first login page after a Ctrl + R but after that it doesn't redirect to my company SSO page as expected, it just shows a blank page 😕

**Comment by sinedied** [comment]
Added a screenshot:
<img width="1375" alt="capture d ecran 2018-04-06 a 17 04 36" src="https://user-images.githubusercontent.com/593151/38428669-a2a35cb4-39bc-11e8-9e40-838edf41bbd6.png">

**Comment by stidch** [comment]
A get a `white screen` when using the Outlook 365 service.

**Comment by MPW1412** [comment]
Seems to be fixed in Beta 18. Make sure to just enter the subdomain, no https, not slack.com.

@stidch, please create a separate ticket for each issue.

**Comment by sinedied** [comment]
@MPW1412 Still not fixed for me in Beta 18, should be reopened.

**Comment by Hoeze** [comment]
I got the same problem with a fresh flatpak installation on ubuntu 20.04

**Comment by fonylew** [comment]
This fixed me on Linux:
`pkill -9 slack` then start Slack again.

In case anyone faces the same blank screen despite not a software issue.

**Comment by Gael42** [comment]
same here, this issue still occuring

**Comment by marquesarthur** [comment]
Got the same error yesterday after switching aps.

**Comment by SiniePalcy** [comment]
Got same error yesterday

**Comment by s-yeoyul** [comment]
Same here ....

**Comment by josyulakrishna** [comment]
I have to restart the computer every time a blank screen shows up, looks like this isn't fixed yet. Ubuntu 20.04
