### ISSUE TITLE
Update to Franz 5.0.0-beta.17 causes Franz.exe to disappear and keeps Franz from starting

### ISSUE THREAD

**Issue by alexroston** [meetfranz/franz#835]
### Expected Behavior
After updating Franz to version 5.0.0-beta.17 it should start normally displaying the client window.

### Current Behavior
After the update has finished, the client will start. There appears an error window which states that `Franz.exe` could noch be found (see screenshot below).

### Screenshots
![20180323_1722_990_l4rxob](https://user-images.githubusercontent.com/10376216/37841770-b9d33d3e-2ec0-11e8-8224-ac78594521b0.png)

### Steps to Reproduce
1. start Franz version 5.0.0-beta.16
2. update the client via the settings menu or the pop-up at the bottom line of the client which is shown when there are updates available
3. wait for the update process to finish
4. start Franz manuelly or wait until it is started automatically after the update process

### My Environment
* Franz Version used: 5.0.0-beta.17
* Operating System and version: Windows 10 Home, 64-bit, Version 1709, OS Build 16299.309

**Comment by Katastroficzny-Kaszalot** [comment]
Same happened to me.

Posting the english version of error:

![franzerror](https://user-images.githubusercontent.com/37709524/37846018-92c2e0bc-2ecc-11e8-8371-8498b654a617.png)

OS: Windows 10 Pro, 64-bit, Version 1709, OS Build 16299.309

**Comment by alexroston** [comment]
**Update:** Now the client is updating automatically after I started it. So I have to run the installer for beta version 16 everytime before starting Franz. Pretty annoying 😕.

**Comment by nsudds** [comment]
Hmm, it's working fine on my end but if you are getting the alert update every time maybe you can turn off the "include beta" feature in settings until this is resolved?
http://share.activelabs.ca/2018-03-24_18h29_05.png

**Comment by Katastroficzny-Kaszalot** [comment]
We can't turn off anything because the app is not starting. When I'm trying to run Franz it shows that error and I can't do anything. I tried to reinstall it with current version - same.

**Comment by benswolo** [comment]
Not sure if this helps, but installing the legacy version will work fine, even if you do have the franz file in the AppData folder. Now, the issue is that I can't get Google Keep on it.
OS: Windows 10 Pro, 64-bit, Version 1709, OS Build 16299.309

**Comment by adlk** [comment]
Can you please go to 
- View -> Toggle Developer Tools (not service developer tools)
- In Developer Tools; go to console.
- Is there an error or anything else?

**Comment by adlk** [comment]
@alexroston thanks for reporting this.
This happens every single time when you go back to beta 16 and install the update?

**Comment by benswolo** [comment]
This issue can be fixed by running ccleaner. I ran both the general cleaner and the registry cleaner, and reinstalled beta 17. Seems to work fine now

**Comment by Katastroficzny-Kaszalot** [comment]
@adlk now it works: I've uninstalled Franz from the Control Panel Uninstall Program section again and installed it again manually.
