### ISSUE TITLE
can't receive reset password mail

### ISSUE THREAD

**Issue by danielheene** [meetfranz/franz#838]
i can't receive a reset password mail for logging in to franz with my account. 

I didn't receive any password reset mail to my gmail account even after multiple retries in the period of maybe half a day. I've also checked my spam and other folders but there wasn't any mail. 
After setting up a new account i've received the confirmation mail instantly without any problems.
So there may be some problem with the reset password function?

I feel very certain that no mail arrived me because my account was definitely registered with the selected mail address.  

### Steps to Reproduce (for bugs)

1. open franz app for the first time and try to reset password
2. waiting for receiving a mail with a password reset link
3. don't receive any mail for the next half hour
4. repeating the steps again for some time 

### Your Environment

* Franz Version used: Version 5.0.0-beta.17 (5.0.0-beta.17.834)
* Operating System and version: macOS 10.12.6 (16G1212)

**Comment by adlk** [comment]
Can you please send me an email to stefan@adlk.io (with the email you have signed up with)?
Thanks!
