### ISSUE TITLE
ARe you planning to support other chat apps?

### ISSUE THREAD

**Issue by taewookim** [meetfranz/franz#840]
I'm interested in kakao talk, line, viber

is there a product roadmap?

**Comment by Ash258** [comment]
@taewookim You want new service? Just request it [here](https://docs.google.com/forms/d/e/1FAIpQLScG80CbnO42xVJZPXYLbtSBmOEW7v6w0WjEpIrMONdJCazefg/viewform "here").

**Comment by david-nedved** [comment]
@taewookim It's not possible to directly integrate Viber via webapp as Viber have stated several times that they WILL NOT be releasing a webapp (as of 2018) - There's a simple plugin however I've made (here)[https://github.com/david-nedved/viber-franz] that will publish the Viber desktop application to Franz.
