### ISSUE TITLE
Multi-screen display issue

### ISSUE THREAD

**Issue by Cr3z** [meetfranz/franz#844]
Display issue when disconnecting second screen

### Current Behavior

When using Franz plugin on a second screen and then disconnecting second screen, we are unable to see the Franz frame. This one actually sticks to the disconnected screen.
### Steps to Reproduce (for bugs)

1. Connect a second screen and drag the Franz frame on it
2. Reduce Franz
3. Disconnect the second screen
4. Open Franz again

### Context

Can't use Franz when my laptop isn't connected to a second screen
### Your Environment

* Franz Version used: Franz v.5.0.0-beta.17
* Operating System and version: Windows 10

**Comment by marcobeltempo** [comment]
I run into this issue daily. The only fix I've found is to:
1. Click the franz app to make sure it's opened (even though you can't see it)
2. Press `Alt` + `spacebar` 
3. Click `Maximize`

Hope this can be fixed soon.
