### ISSUE TITLE
Restart & install update doesn't work on 5.0.0-beta.16 on MacOS High Sierra 10.13.3

### ISSUE THREAD

**Issue by asfaltboy** [meetfranz/franz#846]
I have the message in my instance that says:
> A new update for Franz is available. What is new? [Restart & Install update]

### Expected Behavior

Clicking the "Restart & Install" button should download the new version, stop the old one and start with the new one (assuming it's version 5.0.0-beta.17).

### Current Behavior

The instance of franz is simply closed and not-reopened. Opening it manually results in same old version being available.

### Screenshots (if appropriate):

<img width="1172" alt="screen shot 2018-03-26 at 09 56 17" src="https://user-images.githubusercontent.com/321520/37893818-67b2874e-30dc-11e8-968c-2903e8ebe03f.png">
<img width="1172" alt="screen shot 2018-03-26 at 09 56 26" src="https://user-images.githubusercontent.com/321520/37893819-67d21974-30dc-11e8-8a2f-0cbd7a1d888e.png">

### Possible Solution

Remove franz entirely from Applications and install beta 17 manually. Not sure if this solves the issue for the next update - we'll have to see 😄

### Steps to Reproduce (for bugs)

1. Download and install version 5.0.0-beta.16
2. Launch franz and check for updates, or wait for update notification.
3. Click the "Restart & Install" button and wait.
4. See the existing beta 16 version is still installed.

### Context

I'm expecting the auto-update mechanism to work on itself.

### Your Environment

* Franz Version used: 5.0.0-beta.16
* Operating System and version: MacOS High Sierra 10.13.3 (17D102)

**Comment by adlk** [comment]
I can't reproduce this issue with the same system 🤔 
Anyone else with the same problem?

**Comment by brendanjones** [comment]
@adlk yup, happening to me exactly as described by @asfaltboy

**Comment by asfaltboy** [comment]
Just saw that this exact thing happens to me with Skype for MacOS as well. This very well may be am issue with ShipIt...

**Comment by asfaltboy** [comment]
Digging around electron/electron and other projects that use it (and subsequently ShipIt), it seems the most common cause is weird permission in the app's `Cache/X.ShipIt` directories.

While I don't know the original cause or related ticket, the workaround was simply updating the folder ownership to my own user.

     sudo chown -R $USER /Users/$USER/Library/Caches/com.meetfranz.franz.ShipIt/

@brendanjones please try it out and see if this helps you too.

**Comment by brendanjones** [comment]
I'd love to help, but I don't dare touch terminal unless I _really_ know what I'm doing. I'm a product manager; I break all the things, not fix them ;)
