### ISSUE TITLE
Tray icon disappear in Windows 8.1

### ISSUE THREAD

**Issue by dzeidzei** [meetfranz/franz#847]
### Expected Behavior
Tray icon is visible

### Current Behavior
After Franz has been running some time (over a day) tray icon goes invisible. It still reserver space in tray but it just seems to be transparent or something.

### Screenshots (if appropriate):
https://i.imgur.com/bGK7rUy.png

### Possible Solution
At least sometimes when icon changes to indicate notification (red dot) it becomes visible.

### Your Environment
* Franz Version used: 5.0.0. beta 17 (existed also in beta 16)
* Operating System and version: Windows 8.1 with latest updates

**Comment by PashaKagan** [comment]
...and on beta 18, with Windows 10 x64. Got used to the blank space by now, but... yeah, doesn't look good.

**Comment by gandreadis** [comment]
I've been having the same issue for a while now, on Windows 10 Home edition. Is there by any chance some progress towards fixing this?

**Comment by elevente** [comment]
this one still keeps happening quite frequently on Windows 10 for me
![image](https://user-images.githubusercontent.com/2589829/59430105-ac563680-8de1-11e9-95e8-f38d6f9839fe.png)
