### ISSUE TITLE
FB messenger notifications come in even if messages have been read on another device.

### ISSUE THREAD

**Issue by goleary** [meetfranz/franz#848]
### Expected Behavior
If i respond to or view messages on another device (like my phone).  I do not want to have them pop up as notifications when I return to my computer.  It becomes quite obnoxious.

### Current Behavior
when I return to computer after being away for a while I often get a barrage of notifications from facebook (through franz).

### Your Environment

* Franz Version used: 5.0.0-beta.17
* Operating System and version: window 10 x64

**Comment by adlk** [comment]
Facebook (Messenger) decides when to send and not to send notifications. Unfortunately this is nothing we have any influence on.
