### ISSUE TITLE
Can't copy text from Franz services using keyboard shortcuts

### ISSUE THREAD

**Issue by danielbecker** [meetfranz/franz#849]
When I try to copy text using `command + c`, the text does not get transferred into the clipboard.
However, right-clicking and selecting copy works fine.

I am currently on MacOS 10.13.3 using Franz 5.0.0-beta.17.834

**Comment by brendanjones** [comment]
@danielbecker https://github.com/meetfranz/franz/issues/33

**Comment by danielbecker** [comment]
Thanks, didn't realize that it was a duplicate. Closing now.
