### ISSUE TITLE
on mac click on notify

### ISSUE THREAD

**Issue by G14nLu** [meetfranz/franz#851]
i'd like that on mac application, clicking onto the notification banner, the app could open and show the service and the notification.

**Comment by ljavierrivera** [comment]
+1 to this

**Comment by Sigri44** [comment]
You have banner ?? I haven't never notif for all services..

**Comment by bartvanandel** [comment]
I'd like the same thing on Windows. Click to dismiss seems counter-intuitive compared to how other programs handle this. A close button to close seems more appropriate.
