### ISSUE TITLE
Slack doesn't mark message read after last update

### ISSUE THREAD

**Issue by jfain189** [meetfranz/franz#852]
### Steps to Reproduce (for bugs)

1. Set up slack room in Franz
2. Have someone message you
3. Read / reply to message
4. Sidebar still sees message as unread, bar at the top notifying you of messages

### Your Environment

* Franz Version used: 5.0.0-beta.17
* Operating System and version: Windows 10 Pro

**Comment by drorata** [comment]
Trying to bump this issue --- I have it as well.

**Comment by MatMaul** [comment]
Same here, and it also seems to break the time tracker to forward notifications to mobile after X minutes.
