### ISSUE TITLE
Cannot add Sendtask

### ISSUE THREAD

**Issue by Que88** [meetfranz/franz#853]
### Expected Behavior
Sendtask should be added as one of my apps on Franz

### Current Behavior
An error comes up, please check this gif: https://www.dropbox.com/s/ktag13gnd54rf1p/st.gif?dl=0

### Context
I am a team member at Sendtask and was surprised to find out that we are added from a user of ours. 
Please let me know if we can be of any help.

### Your Environment
Latest version
Win 10

**Comment by adlk** [comment]
We have updated the recipe and it's working again.
