### ISSUE TITLE
Todoist asks for login everytime I open Franz

### ISSUE THREAD

**Issue by armaduarte** [meetfranz/franz#855]
### Expected Behavior

Franz open Todoist with my account logged as other services.

### Current Behavior

I configured Franz to open when windows boots up but everytime all services are logged except Todoist.

### Steps to Reproduce (for bugs)

1. Setup Todoist in Franz with an account
2. Reboot Windows or start Franz after being closed (no taskbar icon)
3.
4.

### Context

Is not that important but should work as other services, right?

### Your Environment

* Franz Version used:
* Operating System and version:
Windows 10 Professional 64

**Comment by dbogdanov** [comment]
i have the same issue.

**Comment by stephengeoffreylynch** [comment]
Keeps asking me to log in to Todoist every time I open Franz after computer restart

**Comment by avatarkava** [comment]
https://github.com/avatarkava/recipe-todoist/issues/3 I fixed this on my maintained version of the recipe back in February but it hasn't been integrated into the official repository (yet?) - instructions on how to fix in the meantime are there.

**Comment by dbogdanov** [comment]
It would be nice to see that merged.
