### ISSUE TITLE
Windows 10 Notifications in Info Center

### ISSUE THREAD

**Issue by xenon2008** [meetfranz/franz#859]
### Current Behavior
If i get a New Message in Franz Messenger, like Whatsapp or Telegram, a Notification Banner will be Displayed in Windows 10! But when i Click at this Banner or the Notification in the Info Center Franz Messenger will not open? Other Apps will be openend when i click at the Notificationbanner or the Notification in the Info Center!

Same Error on three different Systems ;)

### Screenshots (if appropriate):
[Screenshot of Notification Banner](https://abload.de/img/unbenanntyou1k.jpg)

### Possible Solution
 - 

### Your Environment

* Franz Version used:latest Beta 5.0.0 beta 17
* Operating System and version: Windows 10 x64 Pro

**Comment by Lealen** [comment]
I have a similar issue, but rather than Franz not opening when I am clicking the notification, it just resizes the window (i have it all the time maximalized on the second screen, so it's annoying when it is making it smaller).

**Comment by krupenja** [comment]
I can confirm that I am seeing this behaviour as well, however _for Telegram only_. Clicking on a new message notification does nothing. Interestingly, it works fine at least for WhatsApp, Skype and Facebook Messenger.

I have 5.0.0-beta.18 running on Windows 10 Home x64, build 16299.371.

**Comment by renzosunico** [comment]
When I click the notification the window also resizes in background. So when I manually open the window from taskbar it is small.

**Comment by cypressious** [comment]
Any updates on this?
