### ISSUE TITLE
Add Facebook Fan Page. They eliminated it forever?

### ISSUE THREAD

**Issue by jorgekokesillo** [meetfranz/franz#86]
Hi,
in the previous version I had Facebook FanPage. What happened now? I can't find it. Best regards

**Comment by adlk** [comment]
We are going to add all the services again, please give us a little time as we are fighting a lot of battles right now.

---

This repository is only for the Franz client. Please use [this form](https://adlk.typeform.com/to/Bj7vGq) for service requests or check out the [guide](https://github.com/meetfranz/plugins) to create your own service integration.

**Comment by stefahn** [comment]
Hello Stefan,

I would love to have the Facebook page service too. I use it a lot these days and Franz was a great way to keep track of it.
I just became Premium Supporter. Hope this helps to bring the Facebook page back on soon.
