### ISSUE TITLE
Whatsapp stuck on the loading bar on Windows

### ISSUE THREAD

**Issue by NandagopalM** [meetfranz/franz#863]
### Expected Behavior
When you click on the whatsapp icon for the first time, it should load completely and show the QR code

### Current Behavior
When we click on the whatsapp icon, the loading bar gets stuck at ~80%

### Screenshots (if appropriate):
![screenshot 14](https://user-images.githubusercontent.com/33872061/38256386-c51026c6-377b-11e8-9e13-2f261b621cb5.png)

![screenshot 15](https://user-images.githubusercontent.com/33872061/38256701-89085ee0-377c-11e8-8b01-8afdaa479dcf.png)

### Steps to Reproduce (for bugs)

1. Open Franz for the first time
2. Choose Whatsapp
3. Open Whatsapp

### Context
Not able to see my Whatsapp messages

### Your Environment
* Franz Version used: Franz 5.0.0 beta-17.        Release : 1.8.2 / win32 / x64
* Operating System and version: Windows 10 Version 1803

**Comment by t2ac32** [comment]
same problem started arround may 2018
