### ISSUE TITLE
Not able to mute Whatsapp

### ISSUE THREAD

**Issue by Chompas** [meetfranz/franz#864]
Even after disabling Notifications & Audio Whatsapp audio still comes out.

### Expected Behavior
Disabled "Notifications & Audio" should mute audio on Whatsapp

### Current Behavior
With the bell icon disabled I'm still getting audio when I receive a notification (the notification banner does not appear).
I've also disabled notifications in the settings piece (screenshot attached).

### Screenshots (if appropriate):

<img width="684" alt="screenshot 2018-04-03 14 13 52" src="https://user-images.githubusercontent.com/1630109/38267403-6bf63ab2-3749-11e8-8733-17dc6be6e3fb.png">

### Steps to Reproduce (for bugs)
1. Go into settings for Whatsapp and disable Audio.
2. Also (optional) disable Audio & Notifications by clicking the bell icon. Doing this is optional since I get audio no matter if I do this step.

### Context
Trying to mute Whatsapp notifications.

### Your Environment
* Franz Version used: Version 5.0.0-beta.17 (5.0.0-beta.17.834)
* Operating System and version: macOS High Sierra 10.13.3 (17D47)

**Comment by Sef1995** [comment]
I have the same issue with version Version 5.0.0-beta.18 (5.0.0-beta.18.903)

**Comment by Duartemartins** [comment]
Same issue, it's quite annoying. 

Version 5.0.0-beta.18 (5.0.0-beta.18.903)

**Comment by virgils** [comment]
Please fix this.

**Comment by MatthieuArzel** [comment]
It would indeed be better to be able to mute in from Franz itself than from the settings of whatsapp of FB messenger.
Please work on a fix :)

**Comment by Salemoche** [comment]
The issue prevails in 2019
I'd prefer there to never be sound than not being able to mute

**Comment by micaelanon** [comment]
You can disable or control the Franz sound from speaker settings, if is not shown wait for a notification and it will be there and then level up or down or just mute the app. Hope it helps!

**Comment by charlezkwan** [comment]
> You can disable or control the Franz sound from speaker settings, if is not shown wait for a notification and it will be there and then level up or down or just mute the app. Hope it helps!

this is helpful!
