### ISSUE TITLE
Franz themes

### ISSUE THREAD

**Issue by papula** [meetfranz/franz#866]
I like Franz, is awesome, it realy works, but I want some dark themes for my eyes... Is realy hard with a white interface... Something like mozaic theme will be great!

 Franz themes

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by CodeBrauer** [comment]
https://github.com/meetfranz/franz/pull/362
