### ISSUE TITLE
Telegram notification remains unread even after opening the messages.

### ISSUE THREAD

**Issue by WiisleyU** [meetfranz/franz#867]
In any chat the number of unread messages appears even if I have already read them or the message is open. I need to start the Telegram from somewhere else (official app, mobile, browser) to clear message notifications.

### Expected Behavior
I would like the unread message counter to disappear when I read the messages.

### Current Behavior
The messages remain there as if they had not been opened or read.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: The latest, auto-updated
* Operating System and version: Windows 7 Ultimate 64-Bit

**Comment by posva** [comment]
This happened yesterday to me after opening telegram on a browser from my computer. I got a login notification on the phone and the message stays unread no matter what
