### ISSUE TITLE
CPU Usage high after sending gif with telegram

### ISSUE THREAD

**Issue by jajoho** [meetfranz/franz#868]
### Expected Behavior
CPU usage should be normal, when sending gifs with telegram

### Current Behavior
After searching and sending a gif with telegram using @gif the CPU load is very high. Sometimes this normalises after a while, sometimes I have to quit Franz to solve this.

### Screenshots (if appropriate):
<img width="222" alt="bildschirmfoto 2018-04-04 um 18 58 09" src="https://user-images.githubusercontent.com/15175599/38322422-a6261490-383a-11e8-8b66-292d1b4d4dd7.png">

### Steps to Reproduce (for bugs)
1. Go to telegram
2. Write @gif
3. Search for a gif
4. Observe CPU load

### Your Environment
Franz Version 5.0.0-beta.17 (5.0.0-beta.17.834)
macOS 10.13.4 (17E199)

**Comment by klemy** [comment]
Maybe a duplicate of https://github.com/meetfranz/franz/issues/267
