### ISSUE TITLE
AltGr + I opens developer tools in my messenger chat window

### ISSUE THREAD

**Issue by FuThe** [meetfranz/franz#871]
AltGr (right alt) + I opens developer tools in my messenger chat window.

### Expected Behavior
On View/Toogle Developer Tools you wrote "Alt+Ctrl+I" to open dev tools

### Current Behavior
Right Alt + I opens dev tools.

### Possible Solution
Turn off AltGr+I shortcut

### Context
Polish language sometimes use AltGr+O to write "ó" leeter. When I miss that "o" and hit "i" it opens dev tools and hide whole conversation window

### Your Environment
WIndows10

**Comment by bittner** [comment]
Probably a duplicate of #893.
