### ISSUE TITLE
Cannot drag window while full screen (Windows)

### ISSUE THREAD

**Issue by Skyreach** [meetfranz/franz#875]
When Franz is in full screen, it prevents you from being about to drag or move the window.

### Expected Behavior

Attempting to drag the full screen window should have the window restore while maintaining focus to allow you to move it.

### Current Behavior

As a user, if the window is full screen I should be able to drag the Franz instance window.

Attempting to drag the full screen window should have the window restore while maintaining focus to allow you to move it. It should not remain locked in full screen.

### Steps to Reproduce (for bugs)

1. Open Franz client on Windows
2. Maximize the window
3. Using the mouse cursor, attempt to move the window from the header, as though you want to go from full screen to a locked side position
4.

### Context

Breaks the windows experience.

### Your Environment

* Franz Version used: 5.0.0-beta.17
* Operating System and version: Release 1.8.4 / win32 /x64, Windows 10

**Comment by goleary** [comment]
I also can't exit fullscreen.  Franz will even cover up the windows taskbar.

I'm on 5.0.0-beta.18

**Comment by apg258** [comment]
This needs to be fixed. Working flawlessly on mac but can be extremely obnoxious on windows systems.

**Comment by Wegerich** [comment]
I am also having this problem. All other windows apps have no problem with this but it doesn't work with Franz

I'm using 
Version: 5.1.0
Release: 4.1.4 / win32 / x64
