### ISSUE TITLE
Franz 5 Beta 18 not launching (Self solved)

### ISSUE THREAD

**Issue by kikoreta** [meetfranz/franz#876]
### Expected Behavior
Start Franz app.

### Current Behavior
Start 2 process with 0 cpu usage and less than 100mb of ram and nothing more.

### Screenshots (if appropriate):
https://i.imgur.com/8xxREey.png
https://i.imgur.com/4Buawrz.png

### Possible Solution

After I started it up by cmd it show an error with the file "AppData\Roaming\Franz\config\settings.json" opened it in notepad and was full of "NULL" removing the file let's start franz again

### Steps to Reproduce (for bugs)

1.Start Franz.
2.Click on the Restart and Update button at the bottom
3.Wait to finish the install
4.Open taskmanager and see only 2 process

### Your Environment

* Franz Version used: 5 beta 18
* Operating System and version: W7 64b

**Comment by YoannMa** [comment]
Same issue on W10

The solution above worked for me too.

**Comment by CobusKruger** [comment]
@kikoreta Your solution worked perfectly; nice find.

**Comment by sorelnagy** [comment]
Yup! Worked. Nice job.

**Comment by dragGH102** [comment]
Yep, I can confirm it works on my W10 too (note that you have to kill all the launched processes in task manager first, deleting the file won't be enough)

**Comment by Gaudenz77** [comment]
I do not get it. Pleas help me: I downloaded Franz because Rambox didnt work anymore. Now the same issue with Franz happens. What do I do wrong?

**Comment by thijsgelton** [comment]
Thanks man! I figure this will work on every OS, but I can confirm it works for W10 as well.

**Comment by Sebbl22** [comment]
Same here. settings.json filled with NULL and franz won't start. Deleting the settings.json file worked.
Franz5.0.0 beta.24

**Comment by Csega** [comment]
I had the same problem with Franz5.0.0 (not beta!). But the above solution (deletion of the settings.json file) worked for me as well.

**Comment by techdogregensburg** [comment]
Worked perfectly fine with Franz 5.0.1
- Windows 10, 64bit, all Updates
My settings.json was empty.

**Comment by Bo0sted** [comment]
Thank you!

**Comment by binhvtle** [comment]
This bug also happens at ver: franz-setup-5.1.0

**Comment by makcycy** [comment]
I had the same problem. I deleting all the files in "AppData\Roaming\Franz\config\" instead of "settings.json" only and it works.

**Comment by sk8cik** [comment]
if nothing else works try to change GPUAcceleration property  in "AppData\Roaming\Franz\config"
  "enableGPUAcceleration": false,
