### ISSUE TITLE
💡 Per service spell checking (multiple language checking)

### ISSUE THREAD

**Issue by promarcel** [meetfranz/franz#877]
The feature of spell checking in Franz is unbelievable. But some times you need to work with multiple languages. 

For this it would be great to improve the current spell checking component in following way:

- Add an option to choose the language per service for spell checking. For example: WhatsApp is checked for English language and Telegram for German language. 
- Or simple choose the current language with a right-click context menu point like Google Chrome or (I don't know how voluminously it will be: checking multiple languages at once).

**Comment by Xerus2000** [comment]
It is not unbelievable, it is standard based on Chromium, they have no contribution to this afaik. 

But in Chrome, I have two languages for spell-checking (my native tongue and English), and I'd like to have the same option in Franz.

The right-click language changing menu already works, it appears when you right-click on a word that is highlighted as misspelled.

**Comment by Xerus2000** [comment]
bump
