### ISSUE TITLE
Zulip is missing from development env options.

### ISSUE THREAD

**Issue by brockwhittaker** [meetfranz/franz#88]
### Expected Behavior
Zulip should be in the list of platforms for use in the development environment as it is already available on the Beta release.

### Current Behavior
It currently is not found in the list.

### Screenshots (if appropriate):
<img width="1291" alt="screen shot 2017-10-23 at 3 04 11 pm" src="https://user-images.githubusercontent.com/10321399/31915468-70ef6c70-b803-11e7-827d-28a79396a689.png">

### Your Environment
* Franz Version used: Master w/ Electron 1.7.6
* Operating System and version: MacOS High Sierra

**Comment by adlk** [comment]
At the moment the dev API will not be synced with the live API. On top of that, in the near future, the dev DB will be reset every 24h, do not use the dev environment for any other things than developing Franz.

**Comment by brockwhittaker** [comment]
The issue is we were trying to debug a traceback that our app received through Franz, so it was important to be able to debug through the dev environment.

**Comment by adlk** [comment]
@brockwhittaker There is not much difference in dev mode compared to the production app. 
You can start Franz in dev mode but still connect to the live API with `$ yarn start:live`. However, I believe that you just need access to the console log of the actual Zulip recipe?
If so, with the production app, you can press `cmd+ctrl+alt+shift+page up` or `cmd+ctrl+alt+shift+fn+arrow up` (on macbooks) to open any service dev tools.

I can tell endless options here without knowing if any of it helps. If you need help debugging the recipe, I'm more than happy to assist you.
