### ISSUE TITLE
[Feature Request] Hosted Mattermost

### ISSUE THREAD

**Issue by edi0th** [meetfranz/franz#880]
Hi !  :+1: 

I just installed the last version (Version: 5.0.0-beta.17 | Release: 1.8.4 / linux / x64) and weirdly, I can't configure a Mattermost account that would not be selfhosted (as it's possible with RocketChat for instance). Is it on purpose or is there something i'm doing wrong ?

Thanks in advance : )

**Comment by jomaxro** [comment]
Can confirm the issue with Franz 5.0.0-beta.18, Mattermost 4.8.1. Per https://api.mattermost.com/#tag/APIv3-Deprecation APIv3 in Mattermost is deprecated, and looking at our Mattermost server logs Franz was trying to connect via APIv3. Was able to resolve the issue by setting **Allow use of API v3 endpoints** to `true`, but this will only work temporarily as APIv3 is scheduled for removal when Mattermost 5 is released.

**Comment by g3d** [comment]
Here is ad hoc solution for new mattermost version https://github.com/meetfranz/franz/issues/927#issuecomment-412261934
