### ISSUE TITLE
Rethink paid options

### ISSUE THREAD

**Issue by pztrn** [meetfranz/franz#882]
Please, rethink tariffs by allowing at least one self-hosted account for each service that allows it. For example I cannot test Mattermost with coworkers and made a decision about buying Franz.

**Comment by bittner** [comment]
@pztrn As a workaround, you can add an entry of the Mattermost domain to you `/etc/hosts` that points to the IP of your self-hosted instance. With a bit of luck this should work out-of-the-box.

**Comment by ylluminate** [comment]
I have to agree, while some services like HipChat make sense, others that are primarily hosted only such as Mattermost just don't make sense.
