### ISSUE TITLE
Custom color for sidebar

### ISSUE THREAD

**Issue by Sjoerrdd** [meetfranz/franz#883]
Hi,
It would be nice to have a custom sidebar color for each service.

Discord is dark, but the sidebar is really light, maybe You can change the background color to the theme-color from an application? 
![afbeelding](https://user-images.githubusercontent.com/19862992/38577054-1c51b74a-3d00-11e8-84ee-24fa8e318ef6.png)

**Comment by aelaa** [comment]
:heavy_plus_sign: 
I'm using dark theme everywhere, and white sidebar is a pain for my eyes

**Comment by incace** [comment]
It's easy enough on WIN to just extract the app.asar, write the styles you want into the main.css, and repack it. Make a backup of the original just in case you screw something up and the app wont load. I just spent a couple hours making a dark theme. Check it out...
![franz-incdark](https://user-images.githubusercontent.com/61343/39092151-e0a7a142-45c3-11e8-8ac4-3e3dd352d72c.png)

**Comment by frnkvieira** [comment]
That shiny white sidebar is freaking me out. It would be awesome to let us change the color.

**Comment by facosta0787** [comment]
Yes I want to change the side bar color as well

**Comment by LeBaux** [comment]
Absolutely biggest gripe at the moment for me. It is like beam lights :(

**Comment by Gaboris** [comment]
He @LeBaux just in case you missed it. There's a dark theme now in b.19.
In theory you just need to have beta updates enabled and you'll get it, or does that not help with the problem?
