### ISSUE TITLE
spell check do not stay disabled (whatsapp)

### ISSUE THREAD

**Issue by mp3qwer** [meetfranz/franz#885]
I have disabled spell checking
after restart franz spell checking in whatsapp is enabled (but switch is off)
after enable and disable spell checking is gone until restart AND only for that chat/contact which is active while disabling

I use multiple languages to chat so it is realy annoying to see all words underlined because its the wrong language

plz fix this soon 

I came to franz because this stupid bug was in whatsapp app for way to much time

**Comment by FeelTheXtasy** [comment]
Same here. I just downloaded 5.0.0-beta.18 and toggling on/off "enable spell check" did nothing. Well, toggling it on showed like 20 corrections for a word while toggling it off showed like 3 corrections for a word. Should I mention I was writing in spanish while my whole system is in english (that includes Franz of course)?

- Version: 5.0.0-beta.18.
- OS: Windows 10 Pro v1803 build 17134.112.
- OS Language: English.

**Comment by genuinefafa** [comment]
it's even worse for me, it does re enable - without modifying the switch - when I change between chats... i'm going crazy with those red underlinesssss

**Comment by nicolinux** [comment]
Issue still persists, dear devs please bump the priority up since it is _extremely_ annoying.
Thx!

**Comment by petr-nehez** [comment]
Same for me... please @adlk, try to fix it :pray:. Thanks!

**Comment by marcelbrode** [comment]
Its not a whatsapp issue. Same in telegram and discord ( Ubuntu 18.04.1 LTS )

**Comment by petr-nehez** [comment]
Well, at least for me beta20 does disable spell checker in whatsapp.

**Comment by adlk** [comment]
Spellchecker is now completely rewritten. If you are not yet part of the official rollout then please upgrade manually via meetfranz.com
