### ISSUE TITLE
about Franz's icon

### ISSUE THREAD

**Issue by TimJi** [meetfranz/franz#886]
what is Franz's icon means?

![56452](https://user-images.githubusercontent.com/11478166/38654199-aa5ae3ae-3e40-11e8-9fce-92eb9672b82f.png)

**Comment by AramLoosman** [comment]
As far as I know, it's the mustache and side whiskers of Kaiser Franz from Austria ([Image](http://cdn-2-wdh.habsburger.net/files/styles/large/public/images/teaser/kaiser_franz_joseph_i._oelgemaelde_um_1910_teaser.jpg?itok=7RuwJBBK)).

**Comment by lolmaus** [comment]
![image](https://user-images.githubusercontent.com/200884/42822708-65bf85ac-89e4-11e8-8b51-ece81a47b0d7.png)
