### ISSUE TITLE
New feature request : previous/next button in Linkedin

### ISSUE THREAD

**Issue by Cr3z** [meetfranz/franz#887]
### Expected Behavior

Add a previous/next button in LinkedIn service to go back to previous page.

### Current Behavior

Actually I need to do my research again if i want to go back to the previous page

### Steps to Reproduce (for bugs)

1. Search for someone
2. Click on his profile
3. Try to go back to the research results
4.

### Your Environment

* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 pro

**Comment by geekyPrash** [comment]
It would be a great help if this feature can be added, especially in LinkedIn there are links that can be navigated, but there is no way to go back to the previous page in Franz.

Thanks you!

**Comment by closingin** [comment]
Duplicate of #385
