### ISSUE TITLE
Franz account not found after paying for a month.

### ISSUE THREAD

**Issue by brockwhittaker** [meetfranz/franz#89]
### Current Behavior
I created an account with the Franz application using my email. I then went to purchase the subscription for one month, where the charge went through for 4 EUR. I then opened the dev version of the application and tried to log in, only to receive an, "Account not found" warning, and when I recreated with the same email, I was able to but didn't retain the subscription I paid for.

### Screenshots (if appropriate):
<img width="639" alt="screen shot 2017-10-23 at 3 07 31 pm" src="https://user-images.githubusercontent.com/10321399/31915676-32ad663c-b804-11e7-8716-be28c6e1b84b.png">
<img width="1291" alt="screen shot 2017-10-23 at 3 09 52 pm" src="https://user-images.githubusercontent.com/10321399/31915711-50e047aa-b804-11e7-81b8-13ccb15d2859.png">

### Steps to Reproduce (for bugs)
1. Create a free account in Beta app.
2. Upgrade to the 1-mo. subscription.
3. Download and install dev app.
4. Fail to log in with same credentials.
5. Create account with same credentials as before.

### Your Environment
* Franz Version used: Beta + Master
* Operating System and version: MacOS High Sierra

**Comment by adlk** [comment]
The dev app and live app do not access the same API. If you want to run the dev version with the live API please start Franz with `$ yarn start:live`

I'll add a notice in the next beta to highlight this.
