### ISSUE TITLE
Cannot download files received via slack in Franz.

### ISSUE THREAD

**Issue by Chiragpanchal27** [meetfranz/franz#890]
### Expected Behavior
It should prompt me to save the file

### Current Behavior

I had received a file via Slack. When I clicked for downloading the file, it redirected me to the clack website in a web browser wherein I was prompted to login into slack

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by rogelioprieto** [comment]
I 've downloaded the 5.6.0 (2020-11-13) version and it works,  solved the issue!
