### ISSUE TITLE
Impossible to open Franz on Ubunutu 17.10

### ISSUE THREAD

**Issue by Leuchtmarker** [meetfranz/franz#891]
### Expected Behavior

Franz should open by clicking on the icon at the app drawer or entering 'franz' in the terminal-

### Current Behavior

By entering ' franz' in the terminal the error you can see on the following screenshot appears.
It says there is an instance running but I can't find the process anywhere
### Screenshots (if appropriate):
![bildschirmfoto vom 2018-04-13 19-34-20](https://user-images.githubusercontent.com/33827531/38749474-03882ff6-3f52-11e8-8904-0eeab7181071.png)

### Steps to Reproduce (for bugs)

See above

### Your Environment

* Franz Version used: 5.0.0 beta 18
* Operating System and version: Ubuntu 17.10

**Comment by jelle619** [comment]
Strange. I'm using Ubuntu 17.10, and this has not been happening to make. Which desktop environment are you using? It could be that I'm not experiencing any issues because I'm not using the default one.

**Comment by Leuchtmarker** [comment]
@jelle619 I'm using gnome
