### ISSUE TITLE
Feature request: Not having to use an account.

### ISSUE THREAD

**Issue by jelle619** [meetfranz/franz#894]
Some might be put off by having to create an account (including me, at first). It would be nice if there would be some way to skip account creation.

### Feature Description
It would be great if you'd only be required to have an account if you would like synchronization and Pro features, but not forcing people to create one - even for the free version. This might put people off. After all, every single chat message you send and receive is going through Franz and they want to be sure that the contents of these messages are only read by you and the receiver. Having to create an account to use Franz might raise some suspicion.

### Motivation and Context
* You should not have to use an account to use an application which does not necessarily require one to use most of its features.
* More people will give Franz a shot, maybe even create an account if they really like it.
* People being put off by being forced into creating an account.

**Comment by haraldox** [comment]
> After all, every single chat message you send and receive is going through Franz and they want to be sure that the contents of these messages are only read by you and the receiver. 

This is not true: Franz does not in any way process your messages, these are processed by the services only, same way as in the browser.

**Comment by jelle619** [comment]
@haraldox I know it’s not true, but it’s what someone could think at first glance. Being forced to create an account with first and last name and connecting all kinds of services to that account... it might raise a few eyebrows (and unfortunately rightfully so these days...).
