### ISSUE TITLE
Todoist keeps logging out

### ISSUE THREAD

**Issue by stephengeoffreylynch** [meetfranz/franz#898]
Windows 10 Pro 64 bit, Version 1709, OS Build 16229.371
Chrome:  Version 65.0.3325.181 (Official Build) (64-bit)
Franx Version 5.0.0-beta.18  Release 1.8.4

I restart my computer every morning.  In Franz, the ToDoist service is always logged out after restart, and I have to log back in again.  Todoist does not seem to stay logged in after shutting down Franz and doing computer restart.  All other services stay logged in, but not ToDoist

**Comment by dbogdanov** [comment]
This is a duplicate of #855. 
I have the same issue on Ubuntu.
