### ISSUE TITLE
Red Badge Icon Not Displayed When Unread Messages Appear 

### ISSUE THREAD

**Issue by 03-triple-threat** [meetfranz/franz#9]
### Expected Behavior
After a new unread message appears, a red circular icon appears on the Franz icon as well as on the service the new message was sent in. The red icon stays on the Franz icon until the unread message is read.

### Current Behavior
No red icon appears anywhere after a new unread message appears. 

### Context
The read icon was a great notification for new messages when Franz is running in the background.

### Your Environment
Franz Version: 4.0.4
Operating System: Windows 10

**Comment by adlk** [comment]
Franz 4 is no longer maintained, please upgrade to Franz 5 (www.meetfranz.com/#download)
