### ISSUE TITLE
Icon is gone after disable service

### ISSUE THREAD

**Issue by priscilaklopper** [meetfranz/franz#90]
### Expected Behavior
Whenever I disable the service, the icon should gray out but stay on the sidebar (with a quick way to enable it again).

### Current Behavior
When I disable the service, the icon just disappears from the sidebar.

### Possible Solution
Whenever disable, the icon could be grayed out and if we right-click on it, we could see an option to enable it again.

### Context
In the last version of Franz, I was able to use a toggle and just disable the service ("log off") — I used it a lot so I can log off Slack when I was not working or disable WhatsApp (etc.) when I was working and didn't want to be disturbed.

### Your Environment
* Franz Version used: 5.0.0-beta. 10
* Operating System and version: macOS Sierra 10.12.6

**Comment by Wouter0100** [comment]
Wasn't the "mute" button used for this kind of purpose? In my opinion you misused the disable feature here. Although, there are of course different workflows and use cases :). Although, this said, there isn't any mute button anymore.

**Comment by priscilaklopper** [comment]
I don't remember how that was called before, but I don't really mean silent the notifications.
So there's no way it's back before the official app comes out (not beta version, I mean)?

**Comment by adlk** [comment]
Mute does not exist at the moment as it might solved a lot of issues but wasn't working very well with media playback as I have to mute the whole webview. 

Once I have figured out a better way to do it I'll reimplement it.

@priscilaklopper I'm working on a feature that adds spaces to Franz to enable/disable services based on the work you want to do.

**Comment by edwardpakpahan** [comment]
Mute and disable is not really the same tho.

Correct me if I am wrong, but on WhatsApp, mute = others can still that you are Online, but not when you disable WhatsApp.

What I wish to have in Beta 5 is precisely the app behaviour in the previous available app, which is to grey out the disable app for me to easily enable it again.

**Comment by haraldox** [comment]
this is implemented in Franz 5.0.0-beta.15 :)
