### ISSUE TITLE
Sounds are still playing for a several services (whatsapp, slack, etc)

### ISSUE THREAD

**Issue by djalmaaraujo** [meetfranz/franz#900]
Even if you disable sounds for each service, they are still playing for Whatsapp, Hangouts, and Slack.

### Expected Behavior
I should be able to mute sounds per services

### Current Behavior
When I mute services they still make sound

### Steps to Reproduce (for bugs)

1. Add a fresh WhatsApp
2. Receive messages, boom
3. Add a fresh hangouts
4. Receive a message, boom

### Your Environment

* Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version: MacOS Sierra, 10.13.4 (17E199)

**Comment by Brun0urs** [comment]
Same for Messenger. Thx guys!

**Comment by 5fth** [comment]
OS: macOS 10.13.2
Franz Version: 5.0.0-beta.18
Same for Slack, Whatsapp, Telegram

**Comment by BrunoCodeman** [comment]
Same here.
Linux Mint 18.3 Sylvia with Mate
Franz 5.0.0-beta
