### ISSUE TITLE
Fix missing taskbar icon on Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by wibimaster** [meetfranz/franz#905]
On some Linux distributions, no icon appear in the taskbar.
This is a common bug in many electron based applications.

### Expected Behavior

When the application is launch, icon must appear in task bar.

### Current Behavior

When the application is launch, icon doesn't appear in task bar.

### Screenshots (if appropriate):

![Task bar icon bug](https://image.ibb.co/jA42XS/bug_franz.png)

### Possible Solution

Easy to fix, just add a line into `index.js`
From: [electron-builder#2269](https://github.com/electron-userland/electron-builder/issues/2269)

### Steps to Reproduce (for bugs)

1. Start the application on Ubuntu Mate 16.04, for example.
2. Take a look on the taskbar.

### Context

Application standard use.

### Your Environment

* Franz Version used: 5.0.0-beta.18 - Release 1.8.4 / linux / x64.
* Operating System and version: Ubuntu Mate 16.04

**Comment by pslobo** [comment]
As suggested in https://github.com/laurent22/joplin/issues/86#issuecomment-376811132, adding `StartupWMClass=Franz` to the generated .desktop file solves this issue.

**Comment by develar** [comment]
Today evening (CET) electron-builder 20.26.0 will be released — `StartupWMClass` will be added correctly (thanks to @StefanTT). So, you can just update electron-builder version to upcoming 20.26.0 and this issue will be fixed.
