### ISSUE TITLE
Franz triggers Discrete Graphics Processor on MacBook Pros

### ISSUE THREAD

**Issue by jipvankuijk** [meetfranz/franz#907]
### Expected Behavior
Franz Should work on the integrated graphics module alone, for better battery life on MacBook Pro models with a Discrete Graphics Processor 

### Current Behavior
As soon as I launch Franz the Discrete Graphics Processor launches resulting in a higher wattage power usage, which drains my batter quickly.

### Possible Solution
Apple has a nice document stating how to let the application use the integrated graphics processor instead of the discrete one. 
Can be found here: https://developer.apple.com/library/content/qa/qa1734/_index.html

### Context
I don't like using Franz right now for the greatly reduced battery life it induces, which I think can be fixed easily. Current fix is disabling GPU Acceleration in the settings, but it would be better if you read the above linked document and make Franz force use the integrated graphics module. 

### Your Environment
MacBook Pro 15" Retina 2016 with 2.7 GHZ i7 6820HQ and AMD Radeon Pro 460 4GB
* Franz Version used: 5.0.0-beta.18
* Operating System and version: MacOS 10.13.4 (17E199)

**Comment by magazov** [comment]
Something related to this https://github.com/electron/electron/issues/9842
