### ISSUE TITLE
Gmail "compose in new window": opens a new window, but it's empty

### ISSUE THREAD

**Issue by seanpk** [meetfranz/franz#908]
If you want your gmail compose window to pop out, it will, but there nothing in it, just a white window titled "my-service-name".

### Expected Behavior

The gmail compose pop out should work. Sometimes this is very handy for being able to reference another email (or even content in another franz service) while writing the email.

### Current Behavior

You just get a white window, with nothing in it.

### Steps to Reproduce (for bugs)

1. start to compose a message in gmail
2. shift + click on the "pop out" button

### Context

As mentioned above, it  is really useful to reference other content that might be in franz (could be another email in gmail, or something in another integration) while writing an email. Without the ability to pop out the compose window, this can only be done by hiding and showing your authoring window and getting distracted.

### Your Environment

* Version: 5.0.0-beta.18
* Release: 1.8.4 / linux / x64
* Operating System and version: Ubuntu 17.10

**Comment by fgladu** [comment]
Still doesn't work in V5.1.0 on macOS (10.14.5)...
I'dd love to be able to use this basic gmail feature.

**Comment by andykeeley** [comment]
> Still doesn't work in V5.1.0 on macOS (10.14.5)...
> I'dd love to be able to use this basic gmail feature.

Agreed. Still a problem on 5.1 for me too. It's a very useful, basic gmail function. Helps cut through their otherwise pretty challenging UI on reading and responding to email threads.
