### ISSUE TITLE
HipChat does not automatically launch chat app

### ISSUE THREAD

**Issue by yeefom** [meetfranz/franz#91]
Upon starting, HipChat stays on the home page that says `Welcome, $USER` with a button labelled `Launch the web app`, instead of launching the web app directly.

### Expected Behavior

The web app should be launched automatically as in the previous major version.

### Current Behavior

It stays on the home page.

### Screenshot

![](https://cldup.com/VLksk9H8Ov.png) 

It stays here.

### Your Environment

* Franz Version used: beta 10
* Operating System and version: MacOS 10.13

**Comment by ylluminate** [comment]
Same here. Very peculiar behavior, but apparently somehow this needs to be triggered properly and it's not presently doing so.

**Comment by haraldox** [comment]
is this behavior still occuring??

**Comment by ylluminate** [comment]
@haraldox yes, it's still happening on both macOS and Windows. It seems to usually occur after some kind of timeout and once you have to log into HipChat again. Once in a while it just pops to that screen.

**Comment by haraldox** [comment]
how annoying is it? seems to be an issue with HipChat, but maybe we can adapt the login page URL to something different...

**Comment by ylluminate** [comment]
The most annoying part is having to login. One a couple of computers we don't have the login information handy and so that takes time and just makes folks not use Franz on those systems.

**Comment by haraldox** [comment]
@ylluminate Is the same issue happening with other HipChat (web) clients? Unfortunately I have no experience with HipChat...

**Comment by ylluminate** [comment]
@haraldox no, unfortunately it seems limited to Franz from what I can tell...

**Comment by haraldox** [comment]
hmm, i see ... might be the user agent, but i'm just thinking out loud
