### ISSUE TITLE
Franz not show after disconnecting external monitor

### ISSUE THREAD

**Issue by Jimmy20** [meetfranz/franz#911]
If you conect extended monitor and then move franz into extended desktop. Then disconnect external monitor. Now it is not possible to control franz, because it shows on disconnected screen and it is not possible to show on existing desktop.

### Possible Solution
Show only on existing desktop.

Franz version: 5.0.0-beta.18
Release: 1.8.4 /win32 / x64

**Comment by cge-io** [comment]
Hi there I am experiencing the same problem with Franz still in the now disconnected screen area. There appears to be no reset of the app's location when a screen is disconnected.

Franz version: 5.0.0-beta.18
Windows 10

**Comment by marcobeltempo** [comment]
Related to the [issue#844](https://github.com/meetfranz/franz/issues/844)

Temporary workaround is
    1. Click the franz app to make sure it's opened (even though you can't see it)
    2. Press Alt + spacebar
    3. Click Maximize

**Comment by dennis-f** [comment]
@marcobeltempo Option 2 should be an checkable option. I could then just uncheck "save window position" and could have a workaround for that. 

Normally follwing works under windows: select the desired window and press Win + <left>|<right> multiple times to bring the window to the desired position. unfortunately this does not work with franz!!

**Comment by salaros** [comment]
@marcobeltempo Your solution is nice, but if you want to prevent this from happening again just remove the content of `window-state.json` file and make it read-only
