### ISSUE TITLE
[Feature Request] - Portable version of Franz for Windows and Mac (for pen drives)

### ISSUE THREAD

**Issue by maofig** [meetfranz/franz#912]
### Feature Description

Release a fully working portable version of Franz for Windows and Mac computes, that can be used from a pen drive, without the need of installation and Administrative Permissions to use it. With an interface to safely update the client without the need of manually replace the files and without overriding settings to avoid the loosing of your own configuration.

### Motivation and Context

Sometimes, when working on computers that are not your own, i.e. conference rooms laptops or internet coffees, Franz can't be installed because of administrative permissions. In this case it would be great to have a portable version in a pen drive, ready to use and configured with your own recipes and settings.

This portable version is useful for people that travels and for professionals that sometimes needs to use other computers temporarily.

**Comment by beppe9000** [comment]
This is a great proposal.

**Comment by davedorm** [comment]
Nudge. Must agree. Although I am a Linux user at home, I run portable apps on a Windows platform when away from home, such as on a library or friend's PC. Would be nice to take these apps with me.

**Comment by AdKiller** [comment]
all good Windows utilities should be portable by default.

**Comment by beppe9000** [comment]
Also it should be added that portable versions of software are useful for people who do frequent re-installs of windows such as computer enthusiasts, overclockers, people with roaming desks at office, etc.

**Comment by TCB13** [comment]
+1 on this!

**Comment by beppe9000** [comment]
Not portable, needs login to franz to login to other services.... for now I don't even think about downloading it...

**Comment by poisonborz** [comment]
+1 It shouldn't be that much effort either.

**Comment by tonybengue** [comment]
I agree with that, **Portable version** can be the best implementation to integrate. 
For everything I need on my Windows Laptop, I search the portable version of it.
Even for Node.js, Python, Docker and so on

**Comment by crazy-max** [comment]
Franz portable is available via Portapps if you want to try: https://portapps.io/app/franz-portable/

**Comment by beppe9000** [comment]
if portable is implemented here at the source no additional work will need to be done for updates

**Comment by beppe9000** [comment]
nope
