### ISSUE TITLE
Update ready to install but update is not working

### ISSUE THREAD

**Issue by juliasteindl** [meetfranz/franz#913]
![fehlermeldung franz update](https://user-images.githubusercontent.com/38528131/38989012-9fbc2ce2-43d5-11e8-8b62-73b4a04578f6.png)

### Current Behavior
 Franz tells me to update the version (screenshot attached). It says "an update is ready to install..." but I can't start the update. The pop-up is coming 5 times per day but it's not updating.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: Version 5.0.0-beta.15 (5.0.0-beta.15.607)
* Operating System and version: MaBook Pro

**Comment by juliasteindl** [comment]
I already entered the administrator user & pw (for sure the correct ones). but still not working! thanks in advance for your help!

**Comment by hugo4711** [comment]
I have the same issue.

Version 5.0.0-beta.17 (5.0.0-beta.17.834)
MacOS Sierra 10.12.6 (16G1314)

**Comment by hugo4711** [comment]
With 5.0.0-beta.18 (5.0.0-beta.18.903) this seems to be fixed - I have not seen the nagging screen anymore since a few days.

**Comment by juliasteindl** [comment]
hello, thanks for the info. I have Version 5.0.0-beta.15 (5.0.0-beta.15.607). How can I update the version to 18?

thanks,
julia



International Athlete Management and Sports Marketing

JULIA STEINDL 
email: julia.steindl <mailto:julia.steindl@nineandone.com>@nineandone.com <mailto:sophie.gerl@nineandone.com>

www.nineandone.com <http://www.nineandone.com/>
Facebook.com/nineandone.perfect10 <http://facebook.com/nineandone.perfect10>Instagram.com/nineandone <http://instagram.com/nineandone>

**Comment by hugo4711** [comment]
try settings -> enable beta versions
