### ISSUE TITLE
Looking for a word CTRL + F/COMMAND+F

### ISSUE THREAD

**Issue by guilhermeojs** [meetfranz/franz#914]
Search for a word on the page

### Expected Behavior
Allowing the user to use CTRL+F or CMD+F on the page to search for a specifi word

### Current Behavior
You can't use CTRL+F or CMD+F on any service

### Your Environment
* Franz Version used: 5.0.0-beta.18.903
* Operating System and version: macOS High Sierra v 10.13.2

**Comment by Nighthawk22** [comment]
Maybe that's related to https://github.com/meetfranz/franz/issues/33

**Comment by dbogdanov** [comment]
This is related to #1216.
