### ISSUE TITLE
Franz in Microsoft Store (UWP App)

### ISSUE THREAD

**Issue by alexhaller** [meetfranz/franz#915]
### Feature Description
I want to install Franz directly from the Microsoft Store to use it as a much better replacement of the WhatsApp UWP App.

### Motivation and Context
* Easier installation
* Easier updates
* Easier "trust"

Thanks,
Alex

**Comment by berhir** [comment]
There are already requests to bring Franz to the Microsoft Store: #158 and #769 
As noted in the other issues it shouldn't be too much effort to do it with the [available converter](https://electronjs.org/docs/tutorial/windows-store-guide). Store apps like WhatsApp and Slack are using this converter.

I also hope that we will see Franz very soon in the Microsoft Store.

**Comment by cnf** [comment]
Also 'works in S mode'

**Comment by mundodisco8** [comment]
Plus the option to make it work with "my people" 😉
