### ISSUE TITLE
Slack "Previous channel or DM visited" and "Next channel or DM visited" Keyboard Shortcuts Do Not Work

### ISSUE THREAD

**Issue by Julian88Tex** [meetfranz/franz#917]
### Expected Behavior
* after switching to a new dm/channel in Slack clicking "CMD + [" or "CMD + ]" will allow navigation back to the previous or next dm/channel

### Current Behavior
* keyboard shortcuts have no effect

### Possible Solution
* allow for these shortcuts or specify new alternative ones

### Steps to Reproduce (for bugs)
1. Go to a DM in slack
2. Switch to a new DM
3. Click "CMD + ]"

### Context
* this works fine in Slack's downloaded app and other similar apps like Manageyum

### Your Environment
* Franz Version used: 5.0.0-beta.18
* Operating System and version: OS X 10.13.4

**Comment by nsrosenqvist** [comment]
I've found that no service specific keyboard shortcuts work, they're getting intercepted by Franz instead.

**Comment by Julian88Tex** [comment]
@nsrosenqvist interesting. I'm on a mac so that may have something to do with it.

CMD + K works but CMD + T doesn't
CMD + F does work
CMD + SHIFT + T does not work

**Comment by kip9** [comment]
Any updates on that? Is there a chance to get that fixed? Navigating to previous/next is a critical thing to have in Slack for me.

**Comment by prabhathn** [comment]
Confirmed that the following (very useful) keyboard shortcuts are not working

CMD + T (new conversation)
CMD + [  (previous convo)
CMD + ]   (next convo)

**Comment by prabhathn** [comment]
Ah.. I discovered something. It looks like the keys actually got remapped, or that the HTML5 embed of Slack has different keyboard shortcuts than their Mac App.

CMD + T is also activated by CMD + K
CMD + [ is also activated by CMD + Left Arrow
CMD + ] is also activated by CMD + Right Arrow

Not a fix, but a pretty decent workaround.
