### ISSUE TITLE
Skype Voice/video still not fixed

### ISSUE THREAD

**Issue by jarrard** [meetfranz/franz#921]
This has been a ongoing issue with franz, 

I was going to use this app for skype and a few others but until you guys address this issue then there isn't much point. It should be noted that firefox/chrome/chromium and all other browsers work fine with the web-based skype.  

Just saying, can't be that hard!

**Comment by Gektorian** [comment]
This ticket is duplicate of raised before #686. I would recommend close and merge it with #686.
