### ISSUE TITLE
Mac Notification Icon shouldn't be Franz :)

### ISSUE THREAD

**Issue by katerlouis** [meetfranz/franz#923]
### Expected Behavior

The notification icon should be the same as in the app sidebar by default.

### Current Behavior

The user can only achieve that by adding custom icons– but I don't have the exact icons that the app uses, and whenever you update the icons, I have to manually update all myself? Pretty inconvenient.

### Possible Solution

Use the ones you already are using in the app sidebar. 

### Your Environment

* Franz Version used: 5.0.0.-beta.18.903
* Operating System and version: Mac OS X High SIerra

**Comment by ager0sa** [comment]
+1

**Comment by katerlouis** [comment]
Well, that's one way to "deal" with issues :O
I'd like to reopen this atleast until the developer gives his opinion.

**Comment by fande8** [comment]
Is something going to happen with this issue? It's pretty useful feature and actually a deal-breaker for me because otherwise the notifications are confusing.

**Comment by katerlouis** [comment]
Same here.
