### ISSUE TITLE
MacOS version - Native Text Replacement Feature

### ISSUE THREAD

**Issue by Fragrancer** [meetfranz/franz#924]
Dear Franz, 

is it possible to have support for Native Mac "Text Replacement" - see below: 

![image 2018-04-23 at 6 35 31 pm](https://user-images.githubusercontent.com/29422542/39140711-bcf7ccd2-4725-11e8-8c8a-a81f3c9ef5ff.png)

It is available in all native apps developed by Apple - e.g. Safari (WebKit), Keynote, etc. 
However, it is not available in Chrome and Franz as well. 

Thanks.

**Comment by darenju** [comment]
Apparently, there exists a NPM package that does just that: [electron-text-substitutions](https://www.npmjs.com/package/electron-text-substitutions)

The API surface is very small and could (I hope…) easily be adapted on most of the services Franz includes

```javascript
import performTextSubstitution from 'electron-text-substitutions';
 
let input = document.getElementById('my-input');
performTextSubstitution(input);
```

**Comment by dhawaljoh** [comment]
Can this be re-opened? It would definitely be really nice to have!

**Comment by dhawaljoh** [comment]
A simple(r) implementation is to simply allow substitutions (Edit > Substitutions) within the app. Then, a simple bash script enables the substitutions you've defined in the Keyboard settings.

`defaults write -g WebAutomaticTextReplacementEnabled -bool true`
