### ISSUE TITLE
5.0.0-beta.18 KDE Neon memory leak

### ISSUE THREAD

**Issue by urbels** [meetfranz/franz#926]
For the second day in a row Franz uses almost 10 GB ram when left running for a night.
Proof: https://i.imgur.com/vo8ROWa.png
Anyone else got this?

Services I'm using - Skype, Discord, Telegram, Whatsapp, Trello.

**Comment by cuongtdc** [comment]
Exactly the same, it uses about 30% CPU and ~8Gb of Ram. I thought it was hacked for cryptocurrency. Had to remove the software, couldn't find any solution. Just started having this problem about a week ago. Please fix it! Thanks!

Services using: FB Messenger, Whatsapp
