### ISSUE TITLE
MatterMost >4 Not Recognized? How to add self hosted Mattermost?

### ISSUE THREAD

**Issue by tstrijdhorst** [meetfranz/franz#927]
I just read in this comment that there is no test for mattermost 4 yet: https://github.com/meetfranz/franz/issues/342#issuecomment-347119252

Is there any way to add mattermost 4 to franz? I just paid for a subscription as combining mattermost with my other clients was the whole point of looking into franz.

**Comment by bbbart** [comment]
Same question from a paying user for Mattermost 5.0.1 :-)

**Comment by g3d** [comment]
Hi guys, just bought the subscription to use self-hosted mattermost, but it don't work with latest stable release. Please address that.

**Comment by g3d** [comment]
Checked the source code & found already implemented the solution, @adlk just need to merge https://github.com/meetfranz/recipe-mattermost/pull/2/files.

If you already have an application installed & want mattermost working, here is short instruction what to do:

1. Start Franz, try to add Mattermost, receive error (if you have 4 or 5 mattermost version)
2. Quit Franz, open folder
```
* Mac: `~/Library/Application Support/Franz/recipes/mattermost`
* Windows: `%appdata%/Franz/recipes/recipes/mattermost`
* Linux: `~/.config/Franz/recipes/recipes/mattermost`
```
3. Edit index.js file according to https://github.com/meetfranz/recipe-mattermost/pull/2/files
4. As result, you should have same index.js with changed code inside `try {}` block

![changed code](http://files.g3d.codes/1._vim_index.js_vim_2018-08-11_11-58-29.jpg)
5. Start Franz again & try to add Mattermost with your url:

![Franz with Mattermost](http://files.g3d.codes/Franz_2018-08-11_11-55-40.jpg)

**Comment by pete001** [comment]
Amazing, this works perfectly!

**Comment by KrzysztofCieslak** [comment]
that helps temporary :)

**Comment by dasrappelt** [comment]
Thanks a lot! I could add the mattermost service in the settings, but it's not loading. Does anybody have an idea?
![Uploading image.png…]()

**Comment by dasrappelt** [comment]
Thanks a lot! I could add the mattermost service in the settings, but it's not loading. Does anybody have an idea?
<img width="1440" alt="bildschirmfoto 2018-10-01 um 14 58 05" src="https://user-images.githubusercontent.com/25768925/46289822-6b3b3080-c58a-11e8-9371-b4c4c0310145.png">

**Comment by cmoulliard** [comment]
I did the modification as suggestez but Franz requests to upgrade the account when we would like to account `mattermost` service. Why ?

<img width="919" alt="screenshot 2018-12-03 09 13 25" src="https://user-images.githubusercontent.com/463790/49361245-c947d980-f6db-11e8-8676-db0da612c31b.png">
