### ISSUE TITLE
Microsoft teams not working

### ISSUE THREAD

**Issue by DaRo0** [meetfranz/franz#931]
### Expected Behavior

When I login into Microsoft teams, it should redirect me to my account.

### Current Behavior

After the first screen where I insert my mail account, it appears to redirect me to my organisation URL (which is pretty normal), and when this happens, the screen turns grey (See screeenshot).

### Screenshots (if appropriate):
![captura de pantalla de 2018-04-26 12-31-02](https://user-images.githubusercontent.com/12486544/39300927-b743c690-494d-11e8-9864-2bca3423b7d9.jpg)

### Steps to Reproduce (for bugs)

1. Activate Teams service in the app
2. Put your login e-mail
3. After that step, the screen turns grey

### Context

I'm just trying to sign in

### Your Environment

* Franz Version used: franz_5.0.0-beta.18_amd64
* Operating System and version: Ubuntu Budgie 17.10 64 bits

**Comment by DaRo0** [comment]
I'll close this issue as now the service is working properly.

**Comment by weyderfs** [comment]
Same problem here I'm using Franz 5...

**Comment by DaRo0** [comment]
At the end my problem was that my network had a proxy, I don't know if this could help you

**Comment by weyderfs** [comment]
I tried acces in my home, the trouble continues.. :(

**Comment by kkirpichnikov** [comment]
We don't have a proxy. 
Well, I checked it today one more time and now it works. 
I haven't changed anything but who knows what was done behind the corp sense. Maybe iT opened something maybe something else.
