### ISSUE TITLE
Skype service not working (no login page)

### ISSUE THREAD

**Issue by Domantas97** [meetfranz/franz#932]
### Expected Behavior
When you open Skype service, it should let you to login.

### Current Behavior
There is not login page, just a white screen.

### Screenshots (if appropriate):
https://prnt.sc/jae7ou

### Your Environment
I just started using Franz, my plan is Basic.
Computer: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Operating System: Mac OS 10.13.3

**Comment by stidch** [comment]
@Domantas97 I see something very similar with `Outlook 365` and `Skype for business`. Are these services working on your side?

**Comment by closingin** [comment]
This used to happen on some installations, but as far as I know it does not occur anymore. If you can confirm, we will close this issue. :slightly_smiling_face:

**Comment by stidch** [comment]
It's probably the same as described in Issue #790 and is not solved yet.
