### ISSUE TITLE
[Feature Request] Desktop notification for Microsoft Teams

### ISSUE THREAD

**Issue by DaRo0** [meetfranz/franz#934]
### Feature Description

Having a Desktop notification when we recieve an update/message in Microsoft Teams, like the APP already has for Slack.

### Motivation and Context

* Why is this change required?
Because if you have more than 1 service, you never know when you recieve a message in Microsoft Teams, which could be important.
* How is this improving the Franz experience?
We will not need to open the APP to check which Service got the message, because we only see that there are unread notifications but not from which APP it's coming.
* What problem does it solve?
The only explaned above.

### Mockups, Screenshots (if available):

Thank you for all the work that you're doing :)

**Comment by rhabegger** [comment]
Same problem here.
v 5.0.0-beta.18
release: 1.8.4 / win32 / x64

**Comment by jdibby** [comment]
Still no notifications for Microsoft Teams

Version 5.2.0-beta.2 (5.2.0-beta.2.1423)

**Comment by cursorme** [comment]
Confirmed that on 5.2.0 final still no notifications

**Comment by fizix137** [comment]
Company just switched from Slack to Teams.  I also am part of another Team as a guest from a client.  I use Franz to be able to access both Teams accounts.  I really need to get a notification from Teams through the Teams web client, which Franz displays.

**Comment by VladyslavLeveniukSecurrency** [comment]
The same issue.
Franz 5.5.0
MacOS 10.15.7
