### ISSUE TITLE
Skype issues

### ISSUE THREAD

**Issue by mbozzola** [meetfranz/franz#936]
Please find here some issues with Skype accounts

### Expected Behavior
- Set different languages
- Open sent/received files

### Current Behavior
- Lang cannot be selected (only default english)
- Trying to open the received files, the systems opens a browser window with an URL with no results. (Example URL opened: https://weu1-api.asm.skype.com/v1/objects/0-weu-d8-5cdfb00081661fd786862b8f1a85086f/views/imgpsh_fullsize)

### Your Environment
* Franz Version used: 5.0 beta 18.903
* Operating System and version: Mac OS Sierra & Windows 10

**Comment by vavelsky** [comment]
I would add also a problem with showing unread messages. When you have a group chat opened then it shows always that there are some unread messages inside. Workaround for that is to open settings and move back to conversations but I would suggest a full fix for that issue.

**Comment by closingin** [comment]
Hello,

Changing the language is related to Skype itself and will not be managed by Franz. For the other problem, this is already being discussed in #739.

I think you can close this issue :slightly_smiling_face:
