### ISSUE TITLE
Slack Okta logins are not working

### ISSUE THREAD

**Issue by N-G-X** [meetfranz/franz#937]
When adding the Slack service and attempting to log in to a team that uses okta for signing in to that workspace, a 401 - Unauthorized error is encountered.

### Expected Behavior
When logging in to team that leverages Okta, once selecting the "Sign in with Okta" option, the user should be presented with to the sign in page for Okta where they then provide a user/pass.

### Current Behavior
When selecting the "Sign in with Okta" option, the user is then presented with a 401 - Unauthorized error page. This suggests that it is bypassing the Okta sign in page altogether.

### Steps to Reproduce (for bugs)
1. Add the Slack service
2. Attempt to sign in to a team that leverages Okta
3. Select the "Sign in with Okta" option
4. Observe the error page

### Context
I work for a company that uses Okta for authentication into several of our app and tools. If this is configured for a Slack team/workspace, the suer does not have another option to sign into Slack. They must use Okta.

### Your Environment
* Franz Version used: Version 5.0.0-beta.18 (5.0.0-beta.18.903)
* Operating System and version: macOS Sierra 10.12.6 (16G1314)

**Comment by AliShaikh94** [comment]
I'm seeing this same issue for Microsoft Teams for my business login

**Comment by spmebrge** [comment]
Try completely uninstalling the Slack Desktop client
https://osxuninstaller.com/uninstall-guides/uninstall-slack-mac-removal-guides/

Then do the re-install via this link https://twitter.com/slackhq/status/553380559620419584?lang=en
