### ISSUE TITLE
Can't add Skype for Business account

### ISSUE THREAD

**Issue by acki** [meetfranz/franz#942]
### Expected Behavior
Adding Skype fB account should work

### Current Behavior
Doesn't recognize account

### Possible Solution
Add functionality

### Steps to Reproduce (for bugs)
1. Try to add a SfB account
2. Get message "this Microsoft account does not exist"
3. This is because Skype account adding connects to the private user MS realm

### Your Environment

* Franz Version used: Latest
* Operating System and version: MS Win 10

**Comment by OskarD** [comment]
I added an "Office 365 Outlook App" and turns out it includes Skype for Business, so if you have Office 365 I guess you don't need a separate app for it

**Comment by lordee** [comment]
Whilst the outlook app approach works, notifications for skype messages are not shown on desktop when minimised to tray
