### ISSUE TITLE
Franz doesn't work with Timing tracking

### ISSUE THREAD

**Issue by pavold** [meetfranz/franz#945]
I use several services in Franz app (FB messenger, Trello, Microsoft Teams) on my Mac and I am not able to track them separately in the Timing app. I think that this is due to the same name in the app header "Franz" instead of, e.g., "Franz - Trello". Can you please fix this somehow?
I contacted the developer of Timing to provide more information on how that could be achieved.

### Expected Behavior
I can see when I was using which service.

### Current Behavior
All tracked data says just "Franz".

### Your Environment

* Franz Version used: 5.0.0-beta.18
* Operating System and version: macOS 10.13.4

**Comment by MrMage** [comment]
This is still relevant.

**Comment by Maxim-Filimonov** [comment]
Agree I'm using Timing and would love to see integration with Franz

**Comment by mmroczka** [comment]
Please add this! I also am looking for this feature. It's weird that Franz doesn't better display what you're doing anyways. :/
