### ISSUE TITLE
Window Resizes when I click a Notification

### ISSUE THREAD

**Issue by IK-CVRT** [meetfranz/franz#946]
### Expected Behavior
Using windows side snap - when I click a notification, it should take me to franz/service to read the update.

### Current Behavior
Using windows side snap - when I click a desktop notification, the franz window resizes and undocks from the side snap position.

### Steps to Reproduce (for bugs)
1. Dock Franz to the side of the screen with windows snap.
2. Trigger a Franz desktop notification (I use slack primarily)
3. Click the notification.
4. Window undocks and resizes. Gives me a sad :(

### Context
It's generally a usability killer for me to keep my left screen docked between chats and to do lists.

### Your Environment

* Franz Version used:
5.0.0-Beta 18
Release 1.8.4 / Win 32/ x64

* Operating System and version:
Windows 10 Home
Version 1709 (OS Build 16299.371)

**Comment by GerritK** [comment]
Same here. Very annoying.

**Comment by bimbo1989** [comment]
Same here!
It can be reproduced even with clicking the notification when Franz is in the taskbar.
Usually I keep it full screen, if I re-open it from the taskbar it reopens full screen fine, but if I click the notification it reopens in a tiny window.

**Comment by fagnerpsantos** [comment]
Same here!

**Comment by PlaceboPRS** [comment]
Not sure if this is the same issue but I'm having a really annoying full screen related issue, I leave Franz set to full screen when it's minimised etc. If I click the Franz icon to view it it is opened and still full screen remembering how I'd left it, when I receive a Whatsapp message notification I click that and it opens Franz but Franz is now windowed not fullscreen, super annoying :(

**Comment by PlaceboPRS** [comment]
Not sure if this is the same issue but I'm having a really annoying full screen related issue, I leave Franz set to full screen when it's minimised etc. If I click the Franz icon to view it it is opened and still full screen remembering how I'd left it, when I receive a Whatsapp message notification I click that and it opens Franz but Franz is now windowed not fullscreen, super annoying :(

> 
> 
> Not sure if this is the same issue but I'm having a really annoying full screen related issue, I leave Franz set to full screen when it's minimised etc. If I click the Franz icon to view it it is opened and still full screen remembering how I'd left it, when I receive a Whatsapp message notification I click that and it opens Franz but Franz is now windowed not fullscreen, super annoying :(

Just enabled Messenger notifications now and it has the same effect, fullscreen Franz becomes Windowed Franz when I open Franz by clicking a notification :(

**Comment by closingin** [comment]
No need to quote your own message and repost it. We're aware of problems with the window behavior on notification click, but people post too much messages/issues about it, that's annoying.

@adlk I wonder if creating another notice for this bug could prevent people from creating new issues again til it's fixed ?

**Comment by davimello28** [comment]
This also happens on Linux version. Samething here.

**Comment by mastercko** [comment]
Is there a reason that this bug was closed. Has it been fixed? I am stifll experiencing this on version 5.1.0 on Windows 10

**Comment by PlaceboPRS** [comment]
FWIW it's fixed for me on Windows 10, or at least I haven't seen the issue happen since the update that presumably fixed it.

**Comment by davimello28** [comment]
I am still having this on Linux.

**Comment by mastercko** [comment]
Still experiencing this issue on:

- Version: 5.2.1-beta.1
- Release: 4.2.4 / win32 / x64
