### ISSUE TITLE
[Bug] Unable to launch Franz from the sidebar in 18.04

### ISSUE THREAD

**Issue by kabeersvohra** [meetfranz/franz#948]
If franz is running (icon in the statusbar) there is no way to open it by clicking on the favourites icon in the sidebar. The only way to open it is to click on the icon in the statusbar and then click 'show franz'

Thanks

**Comment by ragusa87** [comment]
Hello, I got the same issue. 
It's probably because the dock try to open a new instance and it's already running.
> An instance of Franz is already running. Exiting...
This should toggle the "Show Franz" option instead of exiting !

Thanks in advance.
