### ISSUE TITLE
Allow multiple installs of Franz

### ISSUE THREAD

**Issue by mideeks** [meetfranz/franz#949]
### Feature Description
On my Mac I would like the ability to have multiple installs of Franz. This will let me separate Work vs Personal accounts or perhaps Chat vs Email.

### Motivation and Context
This will let me have a separate window and notification for Chat vs Email or maybe Personal vs Work accounts.
Use cases:
- While I'm at work I can close my personal window and not be distracted by that.
- Chat is often very busy but less important. Email/Calendar is infrequent but often very important. Being notified when I have a new email or meeting vs just another new chat message would be very useful.

**Comment by TobiasFeld** [comment]
This would be great!
