### ISSUE TITLE
Use Telegram Desktop for Franz instead of Web based version

### ISSUE THREAD

**Issue by punkguy48** [meetfranz/franz#95]
I use Telegram in a daily basis, and the web based version lacks of many functions that the desktop version has (emojis/sticker/gif sidebar, for example).
It would be great to integrate the Desktop version in Franz.
Thanks!

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used: 5.0.0-beta.10
* Operating System and version: macOS Sierra, 10.12.6

**Comment by adlk** [comment]
Unfortunately this is not possible as Franz works like a web browser and can't run native apps.
