### ISSUE TITLE
Lock passcode

### ISSUE THREAD

**Issue by xavrb** [meetfranz/franz#950]
### Feature Description
A way to set up a lock code that has to be entered in order to use Franz.

### Motivation and Context

The code should not be implemented by a single service because for instance, Telegram doesn't allow to set up a code on the web version. Franz is used on business environments and I think it would be a great adition to its capabilities by making it a bit safer to use.

### Mockups, Screenshots (if available):
![screenshot_20180504_145237](https://user-images.githubusercontent.com/4543127/39649272-dfce84c0-4faa-11e8-96b0-bd7b07c23105.png)

**Comment by Maxzilla60** [comment]
I wholeheartedly agree!

This should be labeled as a `feature-request`.
