### ISSUE TITLE
Franz Gmail and Todoist for Gmail addon

### ISSUE THREAD

**Issue by azawalich** [meetfranz/franz#952]
Hello, I recently have added the Todoist for Gmail addon to Chrome, and it works perfectly. Is there any way to enable this addon in Franz GMail service?

**Comment by wowo101** [comment]
I just stumbled upon this: https://github.com/avatarkava/recipe-todoist

**Comment by Freakachoo** [comment]
Same question for "Sortd" please.

**Comment by nettnaut** [comment]
> Hello, I recently have added the Todoist for Gmail addon to Chrome, and it works perfectly. Is there any way to enable this addon in Franz GMail service?

+1
