### ISSUE TITLE
 Franz's window does not appear v5.0.0 beta 18

### ISSUE THREAD

**Issue by Espi13** [meetfranz/franz#953]
I have version 5.0.0 beta 18 and two processes are opened but Franz's window never appears.

The beta 17 works for me without problems 
![8fb70482204836ff84a0b08e201d4313](https://user-images.githubusercontent.com/25864885/39756668-b787f168-52ca-11e8-9a9a-d263462896b8.png)

**Comment by n4ru** [comment]
+1

**Comment by luisguilhermemsalmeida** [comment]
Unnistalling and installing beta 17 worked for me

**Comment by Espi13** [comment]
@luisguilhermemsalmeida  yep I know, I publish it to inform and they can fix it,
