### ISSUE TITLE
Copying images from Discord context menu is not working

### ISSUE THREAD

**Issue by adolfovalle** [meetfranz/franz#956]
When you right click an image on discord and select the option to copy image, it doesn't get copied into the clipboard.

Expected Behavior:
-The image should be copied to the clipboard

Current Behavior:
-The image doesn't get copied to the clipboard

Screenshots:
1. I click to copy this image

![image](https://user-images.githubusercontent.com/8953663/39799471-bfbd6cbc-533a-11e8-9421-427a0bd3698c.png)

2. When trying to paste, it's pasting the image that i had previously put on my clipboard

![image](https://user-images.githubusercontent.com/8953663/39799296-23094e5e-533a-11e8-9e66-5460e5c83fee.png)

Steps to Reproduce:

1. Enter any server that lets you upload images in Discord while using Franz
2. Right click an image in the chat, and select the 'Copy image' option
3. Paste it into the chat input
4. It will paste what you previously had on the clipboard, proving that the image wasn't saved

Context:
-It affects everyday use of Discord

Environment:
* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 10 Pro

**Comment by erseco** [comment]
Also fails on Ubuntu 18.04 with 5.1.0 version. I can't paste images from clipboard on Hangouts Chat
