### ISSUE TITLE
Messenger Service not working on W7

### ISSUE THREAD

**Issue by DShoby** [meetfranz/franz#957]
### Expected Behavior
When I click on the Messenger Service, it should ask me to connect or display the service interface. 

### Current Behavior
When I click on the Messenger Service, I get a blank page. 

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/16755777/39817525-ae86d97e-539e-11e8-933f-0bad87d3b30d.png)

### Your Environment
* Franz Version used: 5.0.0-beta.18
* Operating System and version: Windows 7 Enterprise SPK 1 

### Update May 5th 
It now works properly.

**Comment by lophocb6** [comment]
Same me

**Comment by Mvpl** [comment]
I'm having the same issue with version 4.0.4 on debian linux

**Comment by lophocb6** [comment]
May be facebook lock

**Comment by syphen** [comment]
Also experiencing this. When I load up the Service Developer Tools...it shows a 500 error trying to retrieve messenger.com.

**Comment by lophocb6** [comment]
Everybody use win 10 build 1703 or higher. This error back up old version everything will be ok
