### ISSUE TITLE
[Feature Request] Scaling of sidebart/franz UI and  hiding menu bar

### ISSUE THREAD

**Issue by osleg** [meetfranz/franz#959]
Franz supports scaling of the messengers by using regular Ctrl++/- bindings.
Yet, only the messangers are scaled, the sidebar always stays same size.

That a problem on a non desktop environments under linux with HiDPI.
Using AwesomeWM franz looks like that
![image](https://user-images.githubusercontent.com/207721/39886566-68a97a90-54c2-11e8-8f23-3fa3e1668abc.png)
The side panel is HUGE while the rest of the messenger is scaled down using ctrl--.

Also it would be nice to be able to hide top menu bar as it unneeded in general, and when it is needed it can be toggled to show by pressing Alt, just like in slack

**Comment by alecive** [comment]
1. Theming, scaling, customizing the side bar is a problem many users have, and there are plenty of issues related to it already!

2. The menu bar was hidden by default (and toggle-able with `Alt`, similarly to e.g. Firefox--I'm using `bspwm` so I think we have a very similar setup).  A recent update started to show it on linux (which I hate too), and @adlk told me that a PR to fix it would be more than welcome.. but I don't really know how many PRs are actually merged, so I didn't bother :sunglasses:
