### ISSUE TITLE
Open franz from tray

### ISSUE THREAD

**Issue by pushsla** [meetfranz/franz#962]
Good day! It would be very cool if Franz, as in the previous version, will open from the tray when calling command. Now he returns that Franz is already running. If, when you enter a command with Franz running, it will be opened from the tray, many Linux users will be grateful =)

**Comment by etrigan63** [comment]
Actually I am experiencing the opposite problem. I can only bring up the running instance of Franz from the appidicator icon in Ubuntu Mate. If I click on the icon in the menu or dock (I am currently using plank) nothing happens. Whereas other Electron apps like Mailspring bring up the running instance. I don't know if this happens in the Windows or Mac versions.

**Comment by pushsla** [comment]
Oh, i`m sorry. It`s my mistake. I meant that Franz opens only from the tray. When using a command, or starting an application from the menu, nothing happens. This is my bad English.
