### ISSUE TITLE
Cannot upgrade my account to pro

### ISSUE THREAD

**Issue by JohnnyUT** [meetfranz/franz#964]
I just tried to upgrade my account from within the app to the pro version but it appears as if there is some problem with the initial request sent to the franz API.

### Expected Behavior
If I click on the "I want to support franz" button in the account tab I want to see some new window where I can enter my payment details.

### Current Behavior
If I click the button nothing happens. In the dev tools I see the following error message:

Failed to load resource: the server responded with a status of 400 (Bad Request)
api.franzinfra.com/v1/payment/init

### Possible Solution
Fix the request as HTTP status code 400 indicates that some request params are missing or wrong.

### Steps to Reproduce (for bugs)
1. go to account tab in the app
2. select any subscription plan
3. click on "I want support franz" button
4. nothing happens -> check error log

### Context
I wanted to upgrade my account so I can use all services

### Your Environment
* Franz Version used: 5.0.0-beta.18
* Operating System and version: Win 10 Professional x64

**Comment by crash-47** [comment]
The same for me too

**Comment by austintruchan** [comment]
Same for me.

**Comment by tobiasdraeger** [comment]
And for me as well.

**Comment by JohnnyUT** [comment]
Appears to work now again! 👍
