### ISSUE TITLE
Messenger service is a blank screen

### ISSUE THREAD

**Issue by jarvisluong** [meetfranz/franz#965]
### Expected Behavior
When I add Messenger as a service and open that service, the window is just white blank

### Current Behavior
It should open a messenger login form perhaps?

### Screenshots (if appropriate):
[https://imgur.com/a/JTMu9fr](bug)

### Steps to Reproduce (for bugs)
1. Download Franz
2. Make an account an login
3. Add Messenger as a service
4. Open messenger service and see a blank window

### Your Environment

* Franz Version used: 5.0.0-beta18
* Operating System and version: macOS 10.13.4

**Comment by MartinDelille** [comment]
I have this blank issue from time to time (not especially on login).

**Comment by closingin** [comment]
Duplicate of #1220, seems like it has nothing to do with Franz.
