### ISSUE TITLE
Serious memory issues over 10 GB memory usage of franz helper 

### ISSUE THREAD

**Issue by gilgoldzweig** [meetfranz/franz#966]
I'm running Franz version 5.0.0-beta.18
With 1.09 GB cache(I don't know if it is important but anyway)
 
My machine is 
MacBook Pro (Retina, 13-inch, Early 2015)
Processor: 3.1 GHz Intel Core i7
Memory: 16 GB 1867 MHz DDR3
Graphics: Intel Iris Graphics 6100 1536 MB

Services used:
Whatsapp, Messenger, Slack, Telegram, Hangout

After around 2:30 hours of 90% background use and around 10% foreground use 
Franz is using around 10 GB of memory 

I've added a picture from my Activity monitor

<img width="543" alt="screen shot 2018-05-13 at 14 51 49" src="https://user-images.githubusercontent.com/16510428/39966998-3845ae1c-56bd-11e8-8364-c56d87da6b1e.png">
<img width="543" alt="screen shot 2018-05-13 at 14 41 02" src="https://user-images.githubusercontent.com/16510428/39966975-e5498724-56bc-11e8-964f-d36f1d25bdac.png">

**Comment by cnf** [comment]
it's still an issue, though

**Comment by bvdlingen** [comment]
Franz is using 12gb on my computer, this is really an issue

**Comment by cnf** [comment]
I canceled my subscription to Franz, it seems no attention is given to this issue.
