### ISSUE TITLE
[Feature request] Support for macOS share extensions 

### ISSUE THREAD

**Issue by leninebike** [meetfranz/franz#968]
### Feature Description

The possibility of each service enabled in Franz to have its own entry in the macOS share menu, as described in https://developer.apple.com/macos/human-interface-guidelines/extensions/share-extensions/

### Motivation and Context
* This functionality would make the share of docs and images a lot easier.
* This functionally would make Franz feel more native to the system.

**Comment by Prettycode-KC** [comment]
I second that idead!

**Comment by CoVoCre** [comment]
Oh I agree so much !!!! Integration with native functionalities like this are amazing !
I guess someone who also has the need and the experience could work on a PR ?
