### ISSUE TITLE
[Feature request] Add reaction to messages on Skype

### ISSUE THREAD

**Issue by vavelsky** [meetfranz/franz#972]
### Feature Description
Adding reaction to each message in the private chat, group chat. 
It is done in the native app as a small icon next to each message.
It contains also the feature to add reaction by clicking the reaction added by someone else.

### Motivation and Context
* It is not required but nice to have while the native Skype app has.
* More like the real Skype than the web one.
* Increase UX.

### Mockups, Screenshots (if available):
<img width="424" alt="zrzut ekranu 2018-05-17 o 13 41 55" src="https://user-images.githubusercontent.com/15970065/40175392-3b239784-59d8-11e8-97ef-12eaf674dfc1.png">
<img width="107" alt="zrzut ekranu 2018-05-17 o 13 42 10" src="https://user-images.githubusercontent.com/15970065/40175397-422b5378-59d8-11e8-9898-f3ba0261dd34.png">
<img width="430" alt="zrzut ekranu 2018-05-17 o 13 42 19" src="https://user-images.githubusercontent.com/15970065/40175402-47a71dfa-59d8-11e8-84be-2445d356f42e.png">

**Comment by closingin** [comment]
Hello,

This issue has nothing to do with Franz itself, it is related to Skype.

Can you close this please ? :slightly_smiling_face:
