### ISSUE TITLE
[Feature request] Tagging people in group chats on Skype

### ISSUE THREAD

**Issue by vavelsky** [meetfranz/franz#973]
### Feature Description
The user is able to tag anyone in the group using @ and type the name, then choose a name from the list people that is in the group.
The user is able to tag all people using @all tag.
After all the specific people or all in the group chats receives the notification.

### Motivation and Context
* Not needed but useful in group chats
* Easier communication in group chats like in the heavy native app.
* Speaking directly to someone in the group chats without notifying everyone.

**Comment by closingin** [comment]
Hello,

This issue has nothing to do with Franz itself, this is related to Skype.

Can you close this please ? :slightly_smiling_face:
