### ISSUE TITLE
[Feature request] add quip

### ISSUE THREAD

**Issue by omgp0ni3s** [meetfranz/franz#977]
possible to add quip as an app?

Thank you! Awesome product so far.

**Comment by Julian88Tex** [comment]
@adlk I've started a repo for Quip: https://github.com/Julian88Tex/recipe-quip

Could we get an official repo started so I can make a PR into it? I don't know node.js so I'm definitely going to need some community help but started with the basics at least. Thanks!

**Comment by Julian88Tex** [comment]
@adlk we've gotten the repo in a pretty good state... notifications are working

<img width="154" alt="Screenshot 2020-03-07 19 34 55" src="https://user-images.githubusercontent.com/459099/76156249-82018300-60ac-11ea-9abe-72c1042db6ea.png">
