### ISSUE TITLE
Trello issues

### ISSUE THREAD

**Issue by Pappas-ZA** [meetfranz/franz#981]
Installed version 5.00-beta.18
Added TRELLO service
Requested login
Subsequent to this screen stays blank
Tried removing and reinstalling service and same issue

**Comment by barto74** [comment]
Same here on 5.0.0-beta.19 (5.0.0-beta.19.1004)
Trello remains totally blank and it doesn't show notification alerts either.
Removing service doesn't help, restarting Franz doesn't help either.
