### ISSUE TITLE
Facebook messenger follows links inside of franz

### ISSUE THREAD

**Issue by marinegrau** [meetfranz/franz#983]
### Expected Behavior

All links to facebook should be opened in a browser.

### Current Behavior

However some of them f.e. "infos about this conversation -> person's name" or "empty chat -> person's name" follows the link inside the app and there's no way to get back to the message view
### Steps to Reproduce (for bugs)

1. click on (i) symbol in top right corner
2. click on name
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:
5.0.0
macOS 10.13.4

**Comment by maver1ck** [comment]
I have the same issue.

**Comment by jgrim** [comment]
+1 same issue here too

**Comment by stevelacey** [comment]
I imagine there are lots of places in Franz this can happen – any kind of keyboard shortcut for the back button would be a handy addition to save users in-the-know from having to restart Franz

**Comment by bakshi** [comment]
Same here +1
