### ISSUE TITLE
Cannot pass the login screen

### ISSUE THREAD

**Issue by dbfin** [meetfranz/franz#984]
So, I used Franz some time ago before switching to Rambox due to some video accelerator problems or something like that which was resolved by Rambox but not Franz. 

So, I just heard about Franz 5, a new version of it, so decided to give it a try again. But when I start it, the first thing I see is a blue screen asking me to create an account or use an existing one. There are some service icons below as well, but nothing happens if I click them. 

So, I thought at first that it asks me to either create a new service account or use an existing one, but no, it seems that it wants me to create a Franz account? 

What is that? And why do I need it to basically run a bunch of web windows under different profiles within an app (this is what these programs among which Franz is one basically do)? 

I am confused and sorry but suspicious. Are you going to keep a list of my service IDs on your servers? 

Well, I will keep using Rambox for now. Actually I do not even have a reason to move from it, but just heard about Franz 5 and wanted to check it out for some wows. Will have to postpone this until this is resolved.

**Comment by bmelman** [comment]
Same here, I am not going to use a messaging application that requires me to create a third party account. For the sake of security, transparency and gdpr.

**Comment by echosa** [comment]
I agree with both of you. I expected this to work like Trillian, Adium, etc. where I would open Franz then immediate add my Slack, Discord, etc. accounts.

Looking a bit into it in [Franz's Privacy Statement](https://meetfranz.com/privacy/), two things stand out to me.

First:

```
Unlike the impression, Franz is very close to a web browser and does not need direct access to external service API's. That means Franz does not store any of your external service login credentials on your computer or on a cloud service. The only data that is stored are cookies and the browser cache – exactly as it is when using a web browser like Safari or Chrome.
```

> like Safari and Chrome

Neither Safari nor Chrome require me to have a third-party, middleman account between me and Slack, et al. (Also, is that a subtle snub of Firefox? Just curious.)

Second:

```
In order to save your configuration and provide features like settings synchronization or the Franz Premium Supporter plans, we require to store some data about you.

This data contains the following personal information:

    Your name
    Email address
    Encrypted password
    Organization/Company
```

I don't want my configuration saved. I don't want to use features such as sync. I do not desire a premium plan. Therefore, the data required for those things should not be required from me.

**Comment by simon-clarkstone** [comment]
Franz 4 worked just fine without an account. I can't find out how to download old versions from their website though.
