### ISSUE TITLE
[Advice] If you are using this application or uploading to some package repository, please use this flags for installation.

### ISSUE THREAD

**Issue by Kuchiriel** [meetfranz/franz#986]
If you are using this application or uploading to some package repository, please use this flags for installation.

```
yarn install \
--prod \
--silent \
--pure-lockfile \
--ignore-optional \
--link-duplicates \
--skip-integrity-check
```

Will take much less time, there no need to install dev dependencies.

**Comment by oliver-gramberg** [comment]
Can you please put some meaningful description of your advice in the issue title? (I can't.)
