### ISSUE TITLE
Migrate to another platform (Gitlab or another) to keep things moving

### ISSUE THREAD

**Issue by julian-alarcon** [meetfranz/franz#991]
Hi!

You should consider the migration to another platform after the MS announcement of the acquisition of GitHub.
http://www.itprotoday.com/open-source/why-open-source-software-moving-gitlab-after-microsoft-github-deal
https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/
https://dev.to/maxart2501/what-i-think-is-bad-about-microsoft-acquiring-github-gme
https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/
https://blog.github.com/2018-06-04-github-microsoft/

**Comment by bittner** [comment]
LOL! 18 downvotes.

Franz users don't care about software freedom. Important that things a "gratis".  (Similar example [here](https://github.com/meetfranz/franz/issues/1167#issuecomment-506388621).)
