### ISSUE TITLE
Lack of screen sharing in slack

### ISSUE THREAD

**Issue by thomasjwebb** [meetfranz/franz#992]
### Feature Description
I would like to be able to initiate screen sharing in slack. I can view other screens but cannot share my own except by using slack's official client.

### Motivation and Context
slack and franz are generally very useful in business/IT applications, particularly in pair programming. However sharing one's own screen is an important part of pair programming when one is the "driver". Without this feature, one is forced to either use slack's official client or a separate system (such as `zoom.us`). This is yet one more feature that can allow people to use Franz for all messaging needs instead of having to mix and match.

### Mockups, Screenshots
<img src="https://tr4.cbsistatic.com/hub/i/r/2017/05/17/b656a740-666b-4d08-af8e-2931d540a20a/resize/770x/96fc6218dd698bcc45e29fb7371def79/slackcall2.jpg" width="400" />

**Comment by TeraNovaLP** [comment]
@thomasjwebb This will be currently not possible, see:

![2018-08-02 14_53_18-share your screen with slack calls slack help center](https://user-images.githubusercontent.com/16338782/43584903-fc2ff3ec-9663-11e8-90ec-2b972c251be3.png)
