### ISSUE TITLE
Franz Window is not displayed on Win10

### ISSUE THREAD

**Issue by JuKo007** [meetfranz/franz#993]
Since the last update the Interface for Franz is not displayed any longer. If I double click on the icon, I get a loading wheel next to my mouse very briefly but then nothing happens. There is an instance of Franz running in the task manager though.

### Expected Behavior

Double clicking on the icon should start Franz and display the interface

### Current Behavior

If I double click on the icon, I get a loading wheel next to my mouse very briefly but then nothing happens.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version: Win 10 Pro

**Comment by HoracioDos** [comment]
Same here. I guess it could be related to some KB fix

**Comment by yihengli** [comment]
Same issue detected. Tested on WIndows 10 RS4.

**Comment by fnewbrough2** [comment]
I get a blank windows but it works when I set it to window 7 compatibility mode.

**Comment by yihengli** [comment]
Tested with win7 compatibility mode, same issue. There are two tasks in task manager with no windows dispalyed

**Comment by tmartin67** [comment]
Same here. beta13 works directly after installation but also does not display the window. In both cases 13 and 18, there are two "Franz" processes active. In multi-monitor/Extend mode only one of those can be killed, in multi-monitor/Duplicate mode both can be killed.

**Comment by martwalter** [comment]
Got the same issue now. Yesterday it worked fine. There where no windows updates installed between. I already reinstalled Franz. Only two franz processes shown but no window or trayicon. Compatibility mode seems not to have an effect. Is there an fix for this?

**Comment by tmartin67** [comment]
Thanks, @martwalter, this worked for me also

**Comment by yihengli** [comment]
Confirmed that @martwalter 's trick solved my beta18 issue on Win10

**Comment by JuKo007** [comment]
@martwalter ´s solution works for me aswell! Nice find, thanks a lot!

**Comment by seane** [comment]
"SOLUTION (thanks to comment from @martwalter ): Delete the Franz folder in AppDate/Roaming (hidden folder) before you do a fresh install of Franz."

Should be *AppData* folder, not AppDate

**Comment by Embraser01** [comment]
Thanks for this solution, I found that you just need to delete the file `window-state.json` inside `AppData/Roaming/Franz` to make it work (for my case).

Also I deleted two cache folders `Cache` & `GPUCache`

**Comment by sebastianjena** [comment]
Solution with AppData/Roaming works, had this problem today
