### ISSUE TITLE
Franz 5.0 beta 8 doesn't open link in Chrome, it opens a small popup instead 

### ISSUE THREAD

**Issue by longtth** [meetfranz/franz#995]
Franz 5.0 beta 8 doesn't open link in Chrome, it opens a small popup instead 

### Expected Behavior

If I clicked on a link in email/chat from Franz, it should open that link in my default browser (Chrome) instead of open an small popup in Franz itself. 

### Current Behavior

Franz open an small blank popup

### Screenshots (if appropriate):
![20180611_095543_greenshot](https://user-images.githubusercontent.com/1010849/41210739-aa681e10-6d5d-11e8-80b1-25f3da4b520b.png)

### Possible Solution

n/a 
### Steps to Reproduce (for bugs)

1. Add Office 365 to Franz 
2. Receive an email with links. 
3. Click on a link. 

### Your Environment

* Franz Version used: 5.0 beta 8 
* Operating System and version: Windows 10 64bit EN.

**Comment by jwelton** [comment]
👍 

Happens for me too with the following:
Service: Gmail
Version: Version 5.0.0-beta.18 (5.0.0-beta.18.903)

**Comment by jwelton** [comment]
Possible duplicate of #685
