### ISSUE TITLE
Installing from AUR

### ISSUE THREAD

**Issue by SethGower** [meetfranz/franz#996]
I am trying to install from the AUR, and it seems to be failing during the `build()` step on the `yarn install`... step. I get this [output](https://gist.github.com/SethGower/e6838dd146b7528f6886dd61a5a7c319) from this step when run manually. 

### Your Environment

* Franz Version used: 5.0.0.0_beta.17
* Operating System and version:`Linux daedalus 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux`

**Comment by eevahr** [comment]
as you can see at the [aur page for franz](https://aur.archlinux.org/packages/franz/), that packages is flagged out of date and probably not maintained by the submitter. \
You will have better luck with [franz-bin](https://aur.archlinux.org/packages/franz-bin/).
