### ISSUE TITLE
Extreme CPU and RAM usage in idle

### ISSUE THREAD

**Issue by falkenhawk** [meetfranz/franz#997]
![image](https://user-images.githubusercontent.com/14310995/41397728-6c198f90-6fb5-11e8-9849-91e7f5174fca.png)

I have the following services added: hangouts chat, gitter, discord (not logged in), messenger, pushbullet, todoist (not logged in), whatsapp (not logged in), hipchat (not logged in)

From time to time the CPU usage goes crazy when doing nothing (?)
How to debug it? Which service could cause it?

**Comment by fire1ce** [comment]
Getting 7GB of ram use at macOS app.

**Comment by unhawkable** [comment]
![image](https://user-images.githubusercontent.com/14310995/42883937-480bcf5c-8a9d-11e8-82df-b72d4fa56523.png)
jesus

**Comment by cnf** [comment]
Memory usage is excessive for me as well.

**Comment by drewrisinger** [comment]
I had this happen twice: this morning and last week. Franz hit about 50-60% CPU usage when disconnected from Internet (i.e. laptop with no WiFi connection). I killed the process without screenshot. Recipes used:

- Telegram
- Facebook Messenger
- GroupMe
- Pushbullet
- WhatsApp

![image](https://user-images.githubusercontent.com/10198051/46354821-8743de00-c62d-11e8-948a-28acc41dfd56.png)

**Comment by unhawkable** [comment]
The workaround could be: remove Pushbullet

**Comment by cnf** [comment]
I don't have pushbullet enabled.

I am down to slack, the lounge, discord, telegram, whatsapp, and ms teams,

I already disabled linked-in, gitter, github, steam, and trello to try get the memory and cpu usage under control.

**Comment by Frozen-byte** [comment]
With Steam, Franz jumps to 17% CPU-Load on my PC.

**Comment by SpectralKH** [comment]
Happens to me as well. Got 8 Gmail accounts and that results in 6GB of RAM usage. Inactive tabs should be moved to the hard drive instead of being kept in RAM.

Could also reload periodically, maybe weekly. Some sort of adblock could be considered as well.

**Comment by InfoSec812** [comment]
Similar issues for me as well. To the point that my Linux ThinkPad is overheating and going into thermal throttling. I have removed Franz from auto-start and have just been using the webapps and I do not encounter any issues. 

Services:
* Slack
* Google Chat
* GMail
* Google Calendar
* Discord
* Gitter.im

**Comment by Charistoph** [comment]
Facing the same issue with Whatsapp, FB, 3 x Slack, Discord.

**Comment by glasgowm148** [comment]
Same issue, I have lots of stuff open - but seems like resource management could be better? if I've not touched the tab in a couple minutes - as posted above said - move inactive tabs to hard drive.

**Comment by w0k3** [comment]
It's melting my poor ultrabook, even the latest Franz version. No matter which services are enabled. No matter which platform it's running on. This is a long term bug (or probably a series of bugs), I have to seek for alternatives.

**Comment by cnf** [comment]
10 to 20% cpu usage, ALL the time, and 6G of ram... This is just getting insane...

**Comment by cnf** [comment]
It seems there are a lot of tickets on CPU load, and memory usage, and no real acknowledgement from @adlk. This just kills my battery, I'm very close to canceling my premium, and looking for other pastures. On my surface-go, I just can't even run franz, or it cooks it, and drains the battery so fast, it becomes unusable.

I understand this can be hard, but to not even acknowledge the issue is mighty frustrating.

**Comment by mattsday** [comment]
Also seeing very CPU on Linux vs Mac. Idling enough to take a good chunk of battery life away and make it more or less unusable.

![Screenshot of high CPU in htop](https://msday.co.uk/images/franz-high-cpu.png)

Using:

- WhatsApp
- Hangouts Chat
- Gmail
- Google Calendar
- Google SMS
- Slack
- Todoist

More than happy to help profile and troubleshoot!

**Comment by leoagm** [comment]
Same issues happening on Linux (Ubuntu 18). With 3 services (2 slack spaces and whatsapp) I have a consumption around 12Gg!!! It's a lot and sadly it will lead me to stop using it.

**Comment by bvdlingen** [comment]
Franz is using 12gb on my computer, this is really an issue

**Comment by cnf** [comment]
I canceled my subscription to Franz. It seems no attention is paid to paying customer feedback on this.

**Comment by falkenhawk** [comment]
@cnf you may try https://github.com/TheGoddessInari/hamsket

**Comment by dukele-taulia** [comment]
I stopped using it because of excessive (memory mainly but also CPU) resource usage.

**Comment by cnf** [comment]
I did as @falkenhawk suggested, and moved entirely over to hamsket, @dukele-taulia.

**Comment by probablykasper** [comment]
I would recommend trying out [Ferdi](https://github.com/getferdi/ferdi) (Franz fork).

For me, Ferdi is currently taking up 1.5GB of RAM with 6 Gmail accounts. In contrast, I mentioned previously Franz used 6GB of RAM for 8 Gmail accounts. Ferdi has a hibernation feature as well, though it's not a per-service setting and I think you'll miss out on notifications with it enabled.

**Comment by falkenhawk** [comment]
Ferdi has its own performance problems: https://github.com/getferdi/ferdi/issues/62
Not sure if they are simply carried over from Franz, or have a different cause.
And hamsket (or maybe it was actually rambox which hamsket forked from) somehow managed (still being just an electron wrapper as well, similarly to Franz, Ferdi and bunch of other similar apps) to be much less resource-demanding, especially when idling.
That gives hope (to me at least) that there is a solution to the performance issues, only if authors of those resource hogs could care more about identifying the real cause...

**Comment by probablykasper** [comment]
This is true, but I still thought I'd throw Ferdi out there because for me it's the best solution because it uses 3x less RAM (in my case) and I've tried Hamsket, Rambox, Station etc and hated their UIs.

 for me it uses 3x less RAM which makes it acceptable for me. I've tried Hamsket and hated it's

**Comment by poisonborz** [comment]
@probablykasper thanks for doing so. After a bit of usage, its a better alternative to Franz in every way. Franz is mostly on a thin lifeline in terms of features - I guess its kept alive to keep the subscription money flowing. No response to user feedback at all.

**Comment by SalahAdDin** [comment]
I think it is realted to using embedded browsers, i saw this problem in Station too.

**Comment by WorLord** [comment]
Ancient versions of electron, node, and V8 are all reasonable causes for this.  Hamsket does better than the other ones because it's up to electron 8.3.3 and a much more recent version of chrome.  It barely takes up 8% CPU on my laptop, and that's with 5 processes running.
