### ISSUE TITLE
Microsoft Teams Service not Working in Windows 10

### ISSUE THREAD

**Issue by fnewbrough2** [meetfranz/franz#998]
I was just evaluating franz and Microsoft teams service will not work. It comes up to a blank screen once logging in. I also tested this on Linux on on Linux teams works fine so it is probably a minor issue.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Franz Version used:
* Operating System and version:

**Comment by ScottGuymer** [comment]
I have a very similar issue to this on Mac when using teams. I think it may be the fact that whilst teams uses Azure AD login our instance backs off onto an on premise ADFS server which uses different auth methods depending on your current network location. 

Teams in Franz seems to work fine when presented with forms based auth but not when presented with basic auth. 

However slack in franz goes through the same auth methods and works fine
