### ISSUE TITLE
[Feature Request] Open links in default browser

### ISSUE THREAD

**Issue by JCKodel** [meetfranz/franz#999]
### Feature Description

Now Franz opens links on an Electron popup (and that hardly work).
It would be nice an option to open links on the default web browser.

### Motivation and Context
* Why is this change required?
Because some links doesn't open correctly on the popups (and other requires cookies, saved passwords and other stuff available only on our default browser).

* How is this improving the Franz experience?
I don't need to do manual work (copy and paste links).

* What problem does it solve?
Allows me to open links in an environment where they actually work.

**Comment by koma-private** [comment]
@JCKodel This topic is discussed at https://github.com/meetfranz/franz/issues/577

**Comment by yuzhakovvv** [comment]
Is there a way to setup a default option of how open links? I would like to set it to Browser. Because some links are opened in Browser, but some in Popup
